### ISSUE TITLE
Missing support for 'Standard_Fx' VM sizes

### ISSUE THREAD

**Issue by pedgar** [Azure/azure-sdk-for-python#1007]
It appears that support for many newer virtual machine size types is missing from the Azure SDK for Python.

The VM size types appear to be defined in the following file:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-compute/azure/mgmt/compute/models/compute_management_client_enums.py

This file is missing the following VM size types from class 'VirtualMachineSizeTypes':
"Standard_F1"
"Standard_F2"
"Standard_F4"
"Standard_F8"
"Standard_F16"
"Standard_F1s"
"Standard_F2s"
"Standard_F4s"
"Standard_F8s"
"Standard_F16s"
"Standard_H8"
"Standard_H16"
"Standard_H8m"
"Standard_H16m"
"Standard_H16r"
"Standard_H16mr"
"Standard_L4s"
"Standard_L8s"
"Standard_L16s"
"Standard_L32s"
"Standard_NV6"
"Standard_NV12"
"Standard_NV24"
"Standard_NC6"
"Standard_NC12"
"Standard_NC24"
"Standard_NC24r"

REPRO:
1) Setup a VM using a type from the list above
2) Using the Azure SDK for Python, try to list all virtual machines

ACTUAL BEHAVIOR:
Traceback (most recent call last):
  "/pexbot/azuremanager.py", line 191, in _get_all_instances
    for vm in self._compute_client.virtual_machines.list_all():
  File "/usr/lib/python2.7/dist-packages/msrest/paging.py", line 64, in __iter__
    for i in self.next():
  File "/usr/lib/python2.7/dist-packages/msrest/paging.py", line 105, in next
    self._derserializer(self, self._response)
  File "/usr/lib/python2.7/dist-packages/msrest/serialization.py", line 623, in __call__
    value = self.deserialize_data(raw_value, attr_type)
  File "/usr/lib/python2.7/dist-packages/msrest/serialization.py", line 727, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/usr/lib/python2.7/dist-packages/msrest/serialization.py", line 749, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/usr/lib/python2.7/dist-packages/msrest/serialization.py", line 738, in deserialize_data
    return self(obj_type, data)
  File "/usr/lib/python2.7/dist-packages/msrest/serialization.py", line 623, in __call__
    value = self.deserialize_data(raw_value, attr_type)
  File "/usr/lib/python2.7/dist-packages/msrest/serialization.py", line 738, in deserialize_data
    return self(obj_type, data)
  File "/usr/lib/python2.7/dist-packages/msrest/serialization.py", line 623, in __call__
    value = self.deserialize_data(raw_value, attr_type)
  File "/usr/lib/python2.7/dist-packages/msrest/serialization.py", line 731, in deserialize_data
    return self.deserialize_enum(data, obj_type)
  File "/usr/lib/python2.7/dist-packages/msrest/serialization.py", line 858, in deserialize_enum
    raise DeserializationError(error.format(data, enum_obj))
DeserializationError: u'Standard_F8' is not valid value for enum <enum 'VirtualMachineSizeTypes'>

EXPECTED BEHAVIOR:
It should return a list of all virtual machines - no exception should be raised.

**Comment by huguesv** [comment]
Thanks for the report. I've filed an issue against the api spec repository. When the swagger spec is updated, we'll generate an updated compute client and we'll post here to let you know when it's available.

**Comment by lmazuel** [comment]
Hi @pedgar (and thank you @huguesv :))
Yes, the size is missing but I'm surprised you got an issue, this is supposed to be optional and NOT parsed as an enum (return as string) to avoid exactly your situation (size change to fast to force an enum).
Could you confirm to version of the package you are using?

**Comment by pedgar** [comment]
Hi @lmazuel, 

Here's the list of package versions I'm using:
python-azure-common                    1.1.1-2
python-azure-mgmt-compute              0.30.0~rc1-2
python-azure-mgmt-network              0.30.0~rc1-2
python-azure-mgmt-nspkg                1.0.0-2
python-azure-mgmt-resource             0.30.0~rc1-2
python-azure-mgmt-storage              0.30.0~rc1-2
python-azure-nspkg                     1.0.0-2
python-azure-storage                   0.30.0-2
python-msrestazure                     0.1.1-2

Are you saying that this would be fixed in a newer version?

**Comment by lmazuel** [comment]
Yes, sure at 99.99%, rc1/2 are deprecated since a long time. We already start removing "rc" like this compute:
https://pypi.python.org/pypi/azure-mgmt-compute/0.32.0

Start a fresh virtual env and install compute:
```console
pip install azure-mgmt-compute
```
You will have some breaking changes compared to rc2. Unfortunately it was necessary (it's the purpose of rc to make tiny breaking changes). Latest tutorial is here:
https://github.com/Azure-Samples/virtual-machines-python-manage

I keep this issue open til you confirm it's ok with the new package.

Thank you

**Comment by pedgar** [comment]
OK, I tried with python-azure-mgmt-compute_0.32.1-1.   It no longer blows up with a deserialization error when a VM is using one of the newer size types.   

Thanks!
