### ISSUE TITLE
'No module named enum' when running azure with ansible

### ISSUE THREAD

**Issue by andreasur** [Azure/azure-sdk-for-python#1015]
**Python:** 2.7.10
**OS:** OSX 10.11.1 (15B42)

Doing a clean install on a new virtualenv via `pip` on OSX

```bash
mkvirtualenv azure
workon azure
pip install ansible
pip install azure==2.0.0rc5
```

Then launching a playbook e.g with `azure_rm_virtualmachineimage_facts` task

```bash
ansible-playbook -i hosts test.yml
```

Results in this error

```python
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, 
"msg": "Do you have azure==2.0.0rc5 installed? Try `pip install azure==2.0.0rc5`- No module named enum"}
```

Installing `enum` explicitly didn't help, I tried:

```python
pip install enum
pip install enum34 # Tried the backport too
```

Correct me if I'm wrong but I think it should work out of the box with the steps above?

**Comment by lmazuel** [comment]
Hi @andreasur 
Yes, this should work out of the box. We need `enum34` in Python 2.7 ([see here](https://github.com/Azure/msrest-for-python/blob/master/setup.py#L57)). Could you `pip freeze` to get me an idea of your installed dependencies?

Thank you

**Comment by lmazuel** [comment]
Your message is created here:
https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/azure_rm_common.py#L76-L94

So I guess the first line failed, even before reading the azure SDK (`from enum import Enum`). I tried to reproduce on a Python 2.7.11 but wasn't able :(. Could you try a simple: `from enum import Enum` from the Python in your venv?

**Comment by andreasur** [comment]
Hi,

doing `from enum import Enum` in venv works. Here' the output from `pip freeze`:

```
ansible==2.2.1.0
appdirs==1.4.2
azure==2.0.0rc5
azure-batch==0.30.0rc5
azure-common==1.1.4
azure-graphrbac==0.30.0rc5
azure-mgmt==0.30.0rc5
azure-mgmt-authorization==0.30.0rc5
azure-mgmt-batch==0.30.0rc5
azure-mgmt-cdn==0.30.0rc5
azure-mgmt-cognitiveservices==0.30.0rc5
azure-mgmt-commerce==0.30.0rc5
azure-mgmt-compute==0.30.0rc5
azure-mgmt-keyvault==0.30.0rc5
azure-mgmt-logic==0.30.0rc5
azure-mgmt-network==0.30.0rc5
azure-mgmt-notificationhubs==0.30.0rc5
azure-mgmt-nspkg==1.0.0
azure-mgmt-powerbiembedded==0.30.0rc5
azure-mgmt-redis==0.30.0rc5
azure-mgmt-resource==0.30.0rc5
azure-mgmt-scheduler==0.30.0rc5
azure-mgmt-storage==0.30.0rc5
azure-mgmt-web==0.30.0rc5
azure-nspkg==1.0.0
azure-servicebus==0.20.2
azure-servicemanagement-legacy==0.20.3
azure-storage==0.32.0
cffi==1.9.1
cryptography==1.7.2
enum34==1.1.6
futures==3.0.5
idna==2.4
ipaddress==1.0.18
Jinja2==2.8.1
MarkupSafe==0.23
packaging==16.8
paramiko==2.1.2
pyasn1==0.2.3
pycparser==2.17
pycrypto==2.6.1
pyparsing==2.1.10
python-dateutil==2.6.0
PyYAML==3.12
requests==2.13.0
six==1.10.0
```

I'm not sure but this could also be an issue with ansible. However very strange.

At first I thought it had something to do with having ansible installed with brew, but I uninstalled it, uninstalled ansible from every other location as well making sure that `which ansible` points to the virtualenv

**Comment by andreasur** [comment]
As a side note: tried updating the venv python to `2.7.13` but that didn't help.

**Comment by lmazuel** [comment]
I have no idea, since `enum34` is installed :(. If you are sure Ansible is launched using this venv, there is no reason to get a `No module named enum` error message.
Are you comfortable to edit the file in Ansible and remove the try/catch, so we can get the full stacktrace?

**Comment by andreasur** [comment]
Sure, here's the full traceback

```python
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/var/folders/68/sbd6v6tn1b76_bxx1gz3vkdr0000gn/T/ansible_bKC4Ba/ansible_module_azure_rm_virtualmachineimage_facts.py", line 111, in <module>
    from ansible.module_utils.azure_rm_common import *
  File "/var/folders/68/sbd6v6tn1b76_bxx1gz3vkdr0000gn/T/ansible_bKC4Ba/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py", line 75, in <module>
ImportError: No module named enum
```

**Comment by andreasur** [comment]
It seems like this issue is probably related to ansible itself. I will post the issue there, but any help is still appreciated!

**Comment by lmazuel** [comment]
This does not match the last files on Ansible, [line 111](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_virtualmachineimage_facts.py#L111) and [line 75](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/azure_rm_common.py#L75) are not imports :(
I don't understand and I'm not able to reproduce... `enum` is not specific to Azure, this is a pretty generic package. Maybe you could pring `sys.path` to see if this is not the venv you thought was loaded?

**Comment by bearrito** [comment]
I'm able to replicate something similar. Does the maintainer need more information?

**Comment by lmazuel** [comment]
The recent [requests 2.14 problem](https://github.com/kennethreitz/requests/issues/4006) makes me think that maybe it's because enum is installed using some setuptools feature:
```python
    extras_require={
        ":python_version<'3.4'": ['enum34>=1.0.4'],
    }
```
maybe on old pip it's silently broken and ignored. Do you have the version of pip? We support pip >= 6.0.
