### ISSUE TITLE
Please enter password for encrypted keyring

### ISSUE THREAD

**Issue by AnushaY1** [Azure/azure-sdk-for-python#1018]
every time it is asking for enter password when calling api.
how to resolve this one.
```console
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/msrest/paging.py", line 60, in __iter__
    for i in self.next():
  File "/usr/local/lib/python2.7/dist-packages/msrest/paging.py", line 92, in next
    self._response = self._get_next(self.next_link)
  File "/usr/local/lib/python2.7/dist-packages/azure/mgmt/resource/resources/operations/resource_groups_operations.py", line 97, in internal_paging
    request, header_parameters, **operation_config)
  File "/usr/local/lib/python2.7/dist-packages/msrest/service_client.py", line 180, in send
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests_oauthlib/oauth2_session.py", line 346, in request
    self.token_updater(token)
  File "/usr/local/lib/python2.7/dist-packages/msrestazure/azure_active_directory.py", line 186, in _default_token_cache
    keyring.set_password(self.cred_store, self.store_key, str(token))
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 48, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/usr/lib/python2.7/dist-packages/keyring/backends/file.py", line 87, in set_password
    password_encrypted = self.encrypt(password.encode('utf-8'))
  File "/usr/lib/python2.7/dist-packages/keyring/backends/file.py", line 271, in encrypt
    cipher = self._create_cipher(self.keyring_key, salt, IV)
  File "/usr/lib/python2.7/dist-packages/keyring/util/properties.py", line 52, in __get__
    return self.fget(obj)
  File "/usr/lib/python2.7/dist-packages/keyring/backends/file.py", line 213, in keyring_key
    self._unlock()
  File "/usr/lib/python2.7/dist-packages/keyring/backends/file.py", line 258, in _unlock
    raise ValueError("Incorrect Password")
ValueError: Incorrect Password
```

thanks

**Comment by AnushaY1** [comment]
i did this version
  pip install azure==2.0.0rc6​

Thanks  lmazuel

**Comment by AnushaY1** [comment]
Python version: 2.7.12
pip install azure==2.0.0rc6​
apt-get install build-essential libffi-dev python-dev
pip install cryptography
pip install azure-mgmt-commerce

can you please help me to solve this.

**Comment by AnushaY1** [comment]
azure==2.0.0rc6
azure-batch==1.0.0
azure-common==1.1.4
azure-mgmt==0.30.0rc6
azure-mgmt-authorization==0.30.0rc6
azure-mgmt-batch==1.0.0
azure-mgmt-commerce==0.30.0rc6
azure-mgmt-compute==0.30.0rc6
azure-mgmt-keyvault==0.30.0rc6
azure-mgmt-logic==1.0.0
azure-mgmt-network==0.30.0rc6
azure-mgmt-nspkg==1.0.0
azure-mgmt-redis==1.0.0
azure-mgmt-resource==0.30.0rc6
azure-mgmt-scheduler==1.0.0
azure-mgmt-storage==0.30.0rc6
azure-mgmt-web==0.31.0
azure-nspkg==1.0.0
azure-servicebus==0.20.3
azure-servicemanagement-legacy==0.20.4
azure-storage==0.33.0

**Comment by lmazuel** [comment]
@annatisch have you an idea here?

**Comment by AnushaY1** [comment]
Hi,

  can any one please solve this problem

thanks

**Comment by lmazuel** [comment]
Hi @AnushaY1 
I'm not sure what is happening exactly, but your `keyring` version seems to be old, could you update it and retry: `pip install -U keyring`

**Comment by AnushaY1** [comment]
Hi lmazuel,

    keyring==10.4.0

**Comment by lmazuel** [comment]
@AnushaY1 the file "keyring/backends/file.py" has been removed in keyring 8.0, you can't have it if your version is 10.4.0, please update your stacktrace. Please also note your system (Ubuntu 16.04. etc.)

**Comment by AnushaY1** [comment]
issue solved.
Thanks..

**Comment by lmazuel** [comment]
Could you share how you solve this issue? Thanks.

**Comment by AnushaY1** [comment]
my system version Ubuntu 14.04 &  upgraded to 16.04. there i did n't find  any issue like enter password....

**Comment by lmazuel** [comment]
@AnushaY1 thanks for the feedback!
