### ISSUE TITLE
Updating an ad app registration to set a pre_authorized_applications fails

### ISSUE THREAD

**Issue by bmc-msft** [Azure/azure-sdk-for-python#10407]
- **Package Name**: azure-graphrbac
- **Package Version**: 0.61.1 
- **Operating System**: linux
- **Python Version**: 3.7.5

**Describe the bug**
Trying to update an existing app registration to add a pre-authorized app generates an error.

**To Reproduce**
```
grant_id = 'XXXX'
approved_app_id = 'YYYY'
update_app_object_id = 'ZZZ'
client = get_client_from_cli_profile(GraphRbacManagementClient)
params = ApplicationUpdateParameters(
            pre_authorized_applications=[
                PreAuthorizedApplication(
                    app_id=approved_app_id,
                    permissions=[
                        PreAuthorizedApplicationPermission(
                            direct_access_grant=False,
                            access_grants=[grant_id],
                        )
                    ],
                )
            ]
)
client.applications.patch(update_app_object_id, params)
```

**Expected behavior**
preAuthorizedApplications in the app manifest now has the new app listed.

What I'm getting instead is:
```
Traceback (most recent call last):
  File "sample.py", line 359, in <module>
    main()
  File "sample.py", line 346, in main
    client.setup_rbac()
  File "sample.py", line 154, in setup_rbac
    client.applications.patch(app.object_id, params)
  File "/home/USER/.venv/VENV_NAME/lib/python3.7/site-packages/azure/graphrbac/operations/applications_operations.py", line 328, in patch
    raise models.GraphErrorException(self._deserialize, response)
azure.graphrbac.models.graph_error_py3.GraphErrorException: A value without a type name was found and no expected type is available. When the model is specified, each value in the payload must have a type which can be either specified in the payload, explicitly by the caller or implicitly inferred from the parent value.
```

**Comment by kaerm** [comment]
@bmc-msft thanks for reporting this, someone should look at this //cc: @lilyjma @mayurid

**Comment by lmazuel** [comment]
Azure AD Graph API is now deprecated. We do not support SDK fixes to this product anymore. Please refer to this issue for additional way to get support to move to Microsoft Graph API:
https://github.com/azure-deprecation/dashboard/issues/60
