### ISSUE TITLE
Virtual machines get status problem

### ISSUE THREAD

**Issue by zabranskiy** [Azure/azure-sdk-for-python#1062]
Sometimes in my script on the get operation:

```
for vm in compute_client.virtual_machines.list(RESOURCE_GROUP): 
    vm_info = compute_client.virtual_machines.get(RESOURCE_GROUP, vm.name, expand='instanceView')
```

I get error:
```console
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 228, in _get_conn
    conn = self.pool.get(block=self.block, timeout=timeout)
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 588, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 231, in _get_conn
    raise ClosedPoolError(self, "Pool is closed.")
requests.packages.urllib3.exceptions.ClosedPoolError: HTTPSConnectionPool(host='management.azure.com', port=443): Pool is closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/msrest/service_client.py", line 180, in send
    **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests_oauthlib/oauth2_session.py", line 360, in request
    headers=headers, data=data, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/msrest/pipeline.py", line 73, in execute_hook
    return self._client_hooks[event](func, self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/msrest/pipeline.py", line 167, in __call__
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/msrest/pipeline.py", line 135, in send
    request, stream, timeout, verify, cert, proxies)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='management.azure.com', port=443): Pool is closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "azurescript.py", line 404, in <module>
    check_vm_statutes(compute_client, network_client)
  File "azurescript.py", line 258, in check_vm_statutes
    RESOURCE_GROUP, vm.name, expand='instanceView')
  File "/usr/local/lib/python3.4/dist-packages/azure/mgmt/compute/operations/virtual_machines_operations.py", line 364, in get
    response = self._client.send(request, header_parameters, **operation_config)
  File "/usr/local/lib/python3.4/dist-packages/msrest/service_client.py", line 206, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "/usr/local/lib/python3.4/dist-packages/msrest/exceptions.py", line 47, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/usr/local/lib/python3.4/dist-packages/msrest/service_client.py", line 180, in send
    **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests_oauthlib/oauth2_session.py", line 360, in request
    headers=headers, data=data, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/msrest/pipeline.py", line 73, in execute_hook
    return self._client_hooks[event](func, self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/msrest/pipeline.py", line 167, in __call__
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/msrest/pipeline.py", line 135, in send
    request, stream, timeout, verify, cert, proxies)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(e, request=request)
msrest.exceptions.ClientRequestError: Error occurred in request., ConnectionError: HTTPSConnectionPool(host='management.azure.com', port=443): Pool is closed.
```

This did not happen before. I thought that the problem with ssl and checked certificate, but all is well with it. How can i fix that?

**Comment by lmazuel** [comment]
Hi @zabranskiy 

It's a `requests` error I've never seen :(. Based on some search, could you provide:
- Your `requests` version -> If not latest could you try latest?
- Are you using thread? -> If yes, you should have one client per thread.

I will continue to think about it. Might ask directly `requests` on their Github repo.

Thanks,

FYI @brettcannon

**Comment by silencev** [comment]
I experienced same issue before when using **AzureOperationPoller** to deploy 20 resources concurrently
```python
2017-03-23 06:24:30,106 [9068:11688] azure_status.py:30 - ERROR - Uncaught exception
Traceback (most recent call last):
  File "D:\home\Python35\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 228, in _get_conn
    conn = self.pool.get(block=self.block, timeout=timeout)
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\home\Python35\lib\site-packages\requests\adapters.py", line 423, in send
    timeout=timeout
  File "D:\home\Python35\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 588, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "D:\home\Python35\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 231, in _get_conn
    raise ClosedPoolError(self, "Pool is closed.")
requests.packages.urllib3.exceptions.ClosedPoolError: HTTPSConnectionPool(host='management.azure.com', port=443): Pool is closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\home\Python35\lib\site-packages\msrest\service_client.py", line 180, in send
    **kwargs)
  File "D:\home\Python35\lib\site-packages\requests_oauthlib\oauth2_session.py", line 360, in request
    headers=headers, data=data, **kwargs)
  File "D:\home\Python35\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\home\Python35\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "D:\home\Python35\lib\site-packages\msrest\pipeline.py", line 73, in execute_hook
    return self._client_hooks[event](func, self, *args, **kwargs)
  File "D:\home\Python35\lib\site-packages\msrest\pipeline.py", line 167, in __call__
    result = func(*args, **kwargs)
  File "D:\home\Python35\lib\site-packages\msrest\pipeline.py", line 135, in send
    request, stream, timeout, verify, cert, proxies)
  File "D:\home\Python35\lib\site-packages\requests\adapters.py", line 490, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='management.azure.com', port=443): Pool is closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "preallocate.py", line 46, in <module>
    mgr.run()
  File "..\epas_libs\epas\provision_manager.py", line 35, in run
    self.process(message)
  File "..\epas_libs\epas\provision_manager.py", line 147, in process
    executor.execute()
  File "..\epas_libs\epas\commands\executor.py", line 35, in execute
    self._next_command = command_instance.do_command()
  File "..\epas_libs\epas\commands\preallocate_commands.py", line 902, in do_command
    result = async_poller.result(timeout=30)
  File "D:\home\Python35\lib\site-packages\msrestazure\azure_operation.py", line 473, in result
    self.wait(timeout)
  File "D:\home\Python35\lib\site-packages\msrestazure\azure_operation.py", line 486, in wait
    raise self._exception
  File "D:\home\Python35\lib\site-packages\msrestazure\azure_operation.py", line 367, in _start
    self._poll(update_cmd)
  File "D:\home\Python35\lib\site-packages\msrestazure\azure_operation.py", line 439, in _poll
    self._operation.async_url, headers)
  File "D:\home\Python35\lib\site-packages\azure\mgmt\resource\resources\operations\deployments_operations.py", line 233, in get_long_running_status
    request, header_parameters, **operation_config)
  File "D:\home\Python35\lib\site-packages\msrest\service_client.py", line 206, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "D:\home\Python35\lib\site-packages\msrest\exceptions.py", line 47, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "D:\home\Python35\lib\site-packages\msrest\service_client.py", line 180, in send
    **kwargs)
  File "D:\home\Python35\lib\site-packages\requests_oauthlib\oauth2_session.py", line 360, in request
    headers=headers, data=data, **kwargs)
  File "D:\home\Python35\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\home\Python35\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "D:\home\Python35\lib\site-packages\msrest\pipeline.py", line 73, in execute_hook
    return self._client_hooks[event](func, self, *args, **kwargs)
  File "D:\home\Python35\lib\site-packages\msrest\pipeline.py", line 167, in __call__
    result = func(*args, **kwargs)
  File "D:\home\Python35\lib\site-packages\msrest\pipeline.py", line 135, in send
    request, stream, timeout, verify, cert, proxies)
  File "D:\home\Python35\lib\site-packages\requests\adapters.py", line 490, in send
    raise ConnectionError(e, request=request)
msrest.exceptions.ClientRequestError: Error occurred in request., ConnectionError: HTTPSConnectionPool(host='management.azure.com', port=443): Pool is closed.
```

**Comment by zabranskiy** [comment]
Hi @lmazuel

1) Python 3.4.2 
selective pip3 freeze result:
```
azure==1.0.3
azure-common==1.1.4
azure-mgmt==0.20.2
azure-mgmt-common==0.20.0
azure-mgmt-compute==0.33.0
azure-mgmt-network==0.30.1
azure-mgmt-nspkg==1.0.0
azure-mgmt-resource==0.31.0
azure-mgmt-storage==0.31.0
azure-monitor==0.1.0
azure-nspkg==1.0.0
azure-servicebus==0.21.0
azure-servicemanagement-legacy==0.20.5
azure-storage==0.34.0
requests==2.13.0
requests-oauthlib==0.8.0
urllib3==1.20
```

2) No, I don't use threads.
3) In my log I see next error timings:
07:45:02 -> 08:00:15 -> 09:40:36 -> 11:34:57 ->  11:54:16  -> 12:21:51 -> ...

Thanks

**Comment by lmazuel** [comment]
Hi @zabranskiy 

It's missing `msrest` in your pip freeze it's strange (because we see it in your stacktrace, and anyway without msrest you're not doing anything). 

Anyway, I think I understand what happens. 

Do you think it's possible if I create a bugfix branch on `msrest` repo with a 0.4.8rc1, to test it live on your situation? Or it's critical data you can't afford to risk with a rc release?

Thanks,

**Comment by zabranskiy** [comment]
Hi @lmazuel

pip3 freeze was selective, all pip3 output:

```
PyJWT==1.4.2
SecretStorage==2.3.1
adal==0.4.5
appdirs==1.4.3
asn1crypto==0.22.0
azure==1.0.3
azure-common==1.1.4
azure-mgmt==0.20.2
azure-mgmt-common==0.20.0
azure-mgmt-compute==0.33.0
azure-mgmt-network==0.30.1
azure-mgmt-nspkg==1.0.0
azure-mgmt-resource==0.31.0
azure-mgmt-storage==0.31.0
azure-monitor==0.1.0
azure-nspkg==1.0.0
azure-servicebus==0.21.0
azure-servicemanagement-legacy==0.20.5
azure-storage==0.34.0
certifi==2017.1.23
cffi==1.10.0
chardet==2.3.0
colorama==0.3.2
cryptography==1.8.1
enum34==1.1.6
html5lib==0.999
idna==2.5
isodate==0.5.4
keyring==10.3.1
msrest==0.4.7
msrestazure==0.4.7
oauthlib==2.0.2
packaging==16.8
pyasn1==0.1.9
pycparser==2.17
pyparsing==2.2.0
python-dateutil==2.6.0
pytz==2016.10
requests==2.13.0
requests-oauthlib==0.8.0
six==1.10.0
urllib3==1.20
virtualenv==1.11.6
wheel==0.24.0
```

Yes, I can test bugfix on my side and will write about results in this thread.

Thanks

**Comment by lmazuel** [comment]
Hi @zabranskiy 

I made a branch and a PR to fix this issue. The branch is building msrest 0.4.8rc1. I made my own testing and everything seems fine. If you have the opportunity to test it in your scenario, would be awesome :)

https://github.com/Azure/msrest-for-python/pull/29
https://github.com/Azure/msrest-for-python/tree/poolfix

Thank you!

**Comment by zabranskiy** [comment]
Hi @lmazuel 

Seems like it is all ok. No same Traceback in my logs.

Thanks

**Comment by lmazuel** [comment]
Hi @zabranskiy , good to hear! My PR is now green on Travis, so I will do more testing and release a 0.4.8 with the fix next week probably. Thank you a lot for the testing!

FYI @silencev since you experienced the issue too
