### ISSUE TITLE
KeyError: 'account_type' when run example program

### ISSUE THREAD

**Issue by manabuishii** [Azure/azure-sdk-for-python#1078]
Azure support Twitter account said me to ask here.

I execute script 
http://azure-sdk-for-python.readthedocs.io/en/latest/

when execute

```
async_create = storage_client.storage_accounts.create(
    'my_resource_group',
    'my_storage_account',
    {
        'location':'westus',
        'account_type':'Standard_LRS'
    }
)
```

I got error

```
python /work/test.py Traceback (most recent call last):
  File "/work/test.py", line 33, in <module>
    'account_type': 'Standard_LRS'
  File "/usr/local/lib/python3.6/site-packages/azure/mgmt/storage/operations/storage_accounts_operations.py", line 156, in create
    body_content = self._serialize.body(parameters, 'StorageAccountCreateParameters')
  File "/usr/local/lib/python3.6/site-packages/msrest/serialization.py", line 301, in body
    data = _convert_to_datatype(data, data_type, self.dependencies)
  File "/usr/local/lib/python3.6/site-packages/msrest/serialization.py", line 171, in _convert_to_datatype
    localtypes) for key in data
  File "/usr/local/lib/python3.6/site-packages/msrest/serialization.py", line 171, in <dictcomp>
    localtypes) for key in data
KeyError: 'account_type'
```

I only change location to `japaneast` .

I use python 3.6.1

What do I set to account_type ?

**Comment by lmazuel** [comment]
Hi @manabuishii 

You're right I forgot to update this code after the latest storage pacakge update... Let me this that asap.

Thanks and sorry for the time wasted

**Comment by lmazuel** [comment]
Hi @manabuishii 

The doc is fixed, sorry for that again.

Thanks,

**Comment by manabuishii** [comment]
Thanks !
