### ISSUE TITLE
ModuleNotFoundError: No module named 'azure.mgmt.iothub.iot_hub_client'

### ISSUE THREAD

**Issue by lexguy20** [Azure/azure-sdk-for-python#10915]
I am trying to generate sas token as:
az iot hub generate-sas-token --duration 3600 -n <hub name>
and getting following error:
The command failed with an unexpected error. Here is the traceback:

No module named 'azure.mgmt.iothub.iot_hub_client'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 625, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 689, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 682, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 324, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 531, in default_command_handler
    return op(**command_args)
  File "/home/nraza/.azure/cliextensions/azure-cli-iot-ext/azext_iot/operations/hub.py", line 1324, in iot_hub_monitor_events
    repair=repair, login=login, content_type=content_type, device_query=device_query)
  File "/home/nraza/.azure/cliextensions/azure-cli-iot-ext/azext_iot/operations/hub.py", line 1366, in _iot_hub_monitor_events
    target = get_iot_hub_connection_string(cmd, hub_name, resource_group_name, include_events=True, login=login)
  File "/home/nraza/.azure/cliextensions/azure-cli-iot-ext/azext_iot/common/_azure.py", line 112, in get_iot_hub_connection_string
    client = iot_hub_service_factory(cmd.cli_ctx)
  File "/home/nraza/.azure/cliextensions/azure-cli-iot-ext/azext_iot/_factory.py", line 28, in iot_hub_service_factory
    from azure.mgmt.iothub.iot_hub_client import IotHubClient
ModuleNotFoundError: No module named 'azure.mgmt.iothub.iot_hub_client'

Any idea? Thanks

**Comment by lexguy20** [comment]
I made it work by removing CLI extention as:
az extension remove --name azure-cli-iot-ext
and then added it back:
az extension add --name azure-cli-iot-ext
Now I am using cli with no problem, not sure it is a bug in extension.
Thanks

**Comment by kaerm** [comment]
Thanks @lexguy20 for reporting this! @nickzhums I am not sure if this is library related, probably should be moved to CLI?
