### ISSUE TITLE
Creating ContentKeyPolicies Error: caused by ResponseError('too many 500 error responses')

### ISSUE THREAD

**Issue by anogueirac** [Azure/azure-sdk-for-python#11142]
Hello,
As I was trying to create a ContentKeyPolicy with the Python SDK, once I built all the Options, the error I get with create_or_update module is:

```
Traceback (most recent call last):
  File "./ams.py", line 122, in <module>
    GetorCreateContentKeyPolicy(connection,RESOUCE_GROUP_NAME, ACCOUNT_NAME,"policy2")
  File "./ams.py", line 97, in GetorCreateContentKeyPolicy
    policy = client.content_key_policies.create_or_update(resource,account,contentKeyPolicyName,options)
  File "/home/sftpuser/.local/lib/python2.7/site-packages/azure/mgmt/media/operations/_content_key_policies_operations.py", line 256, in create_or_update
    response = self._client.send(request, stream=False, **operation_config)
  File "/home/sftpuser/.local/lib/python2.7/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "/home/sftpuser/.local/lib/python2.7/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/home/sftpuser/.local/lib/python2.7/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/home/sftpuser/.local/lib/python2.7/site-packages/msrest/pipeline/requests.py", line 72, in send
    return self.next.send(request, **kwargs)
  File "/home/sftpuser/.local/lib/python2.7/site-packages/msrest/pipeline/requests.py", line 137, in send
    return self.next.send(request, **kwargs)
  File "/home/sftpuser/.local/lib/python2.7/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/home/sftpuser/.local/lib/python2.7/site-packages/msrest/pipeline/requests.py", line 193, in send
    self.driver.send(request.http_request, **kwargs)
  File "/home/sftpuser/.local/lib/python2.7/site-packages/msrest/universal_http/requests.py", line 333, in send
    return super(RequestsHTTPSender, self).send(request, **requests_kwargs)
  File "/home/sftpuser/.local/lib/python2.7/site-packages/msrest/universal_http/requests.py", line 145, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "/home/sftpuser/.local/lib/python2.7/site-packages/msrest/exceptions.py", line 54, in raise_with_traceback
    raise error
msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/*****************************************/resourceGroups/VOD_System/providers/Microsoft.Media/mediaServices/videoprocessor/contentKeyPolicies/policy2?api-version=2018-07-01 (Caused by ResponseError('too many 500 error responses',))
```
The code I used is:

```
policy = client.content_key_policies.get(resource,account,contentKeyPolicyName)
if not policy:
primaryKey = ContentKeyPolicySymmetricTokenKey(key_value = TokenSigningKey)

  alternateKeys = []
  requiredClaims = [ContentKeyPolicyTokenClaim]
  option2 =  ContentKeyPolicyTokenRestriction(issuer=Issuer,audience=Audience,primary_verification_key=primaryKey,restriction_token_type="Jwt",required_claims=requiredClaims)
  options = [ContentKeyPolicyOption(configuration=ContentKeyPolicyClearKeyConfiguration(), restriction=option2)]
  policy = client.content_key_policies.create_or_update(resource,account,contentKeyPolicyName,options)
```
Thank you for your help,
BR.

https://github.com/Azure/azure-sdk-for-python/blob/6393fa41d767f5f57c69768352638ece1d51bbaa/sdk/media/azure-mgmt-media/azure/mgmt/media/operations/_content_key_policies_operations.py#L196

**Comment by acorn20180214** [comment]
@anogueirac,  as discussed,  it should be an issue with payload:  

requiredClaims = [ContentKeyPolicyTokenClaim]  

=>  

requiredClaims = [ContentKeyPolicyTokenClaim(claim_type="abc", claim_value="def"), ContentKeyPolicyTokenClaim(claim_type="urn:microsoft:azure:mediaservices:contentkeyidentifier")]

**Comment by akucer** [comment]
Closing out - please reopen if last feedback didn't resolve issue for you.
