### ISSUE TITLE
pip install azure-storage==0.37.0 fails

### ISSUE THREAD

**Issue by gison93** [Azure/azure-sdk-for-python#11413]
- **Package Name**:  azure-storage
- **Package Version**:  0.37.0
- **Operating System**: Windows-10
- **Python Version**: 3.6.2 

**Describe the bug**
pip install azure-storage==0.37.0 generates the error:
ERROR: Command errored out with exit status 1: python setup.py egg_info
**To Reproduce**
1.  pip install azure-storage==0.37.0

**Comment by lmazuel** [comment]
Hi @gison93 
This is by design, pip will print in output the rationale behind it:

```
> pip install azure-storage==0.37.0
Collecting azure-storage==0.37.0
  Downloading https://files.pythonhosted.org/packages/5d/cd/cac628adf6cb0086a24c20d76609445f1bf841483d56ec9f5645bbaa9ab7/azure-storage-0.37.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\lmazuel\AppData\Local\Temp\pip-install-576sqseg\azure-storage\setup.py", line 55, in <module>
        raise RuntimeError(message)
    RuntimeError:

    Starting with v0.37.0, the 'azure-storage' meta-package is deprecated and cannot be installed anymore.
    Please install the service specific packages prefixed by `azure` needed for your application.

    The complete list of available packages can be found at:
    https://aka.ms/azsdk/python/all

    Here's a non-exhaustive list of common packages:

    - [azure-storage-blob](https://pypi.org/project/azure-storage-blob) : Blob storage client
    - [azure-storage-file-share](https://pypi.org/project/azure-storage-file-share) : Storage file share client
    - [azure-storage-file-datalake](https://pypi.org/project/azure-storage-file-datalake) : ADLS Gen2 client
    - [azure-storage-queue](https://pypi.org/project/azure-storage-queue): Queue storage client


    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\lmazuel\AppData\Local\Temp\pip-install-576sqseg\azure-storage\
```

Thanks!

**Comment by gison93** [comment]
Hi @lmazuel, thank you for the quick answer. My bad, I read that is deprecated but I missed "cannot be installed anymore".
Actually the issue arised because I had a job that installed azure-storage without specifying the version.
In the next days I will switch to the new specific package.

Thanks again!
