### ISSUE TITLE
Uploading file to blob where blob-name contains '\x01\x05' fails.

### ISSUE THREAD

**Issue by tompauwaert** [Azure/azure-sdk-for-python#11577]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.3.1
- **Operating System**: macOS High Sierra Version 10.13.6
- **Python Version**: 3.7.7

**Describe the bug**
Uploading a file which has "\x01\x05" in the filename fails.
This occurs when using BlobClient.upload_blob() as well when using the storage explorer to upload a directory containing such files. Each file with such a path fails. 
StorageExplorer version 1.13.0 with AzCopy version: 10.4.2; or
StorageExplorer version 1.12.0 with AzCopy version 10.3.3

**To Reproduce**
1. Generate a file with filename containing "\x01x05" and attempt to upload it using either BlobClient.upload_blob("path/to/\x01x05filename.txt") or use azure storage explorer to upload the file.

These here are the logs for from storage explorer of uploading such a file.

```
2020/05/21 09:04:58 AzcopyVersion  10.3.3
2020/05/21 09:04:58 OS-Environment  darwin
2020/05/21 09:04:58 OS-Architecture  amd64
2020/05/21 09:04:58 Log times are in UTC. Local time is 21 May 2020 11:04:58
2020/05/21 09:04:58 Job-Command copy /Users/tom/Desktop/invalid_filename.txt https://awprod1.blob.core.windows.net/raw-engie-mail2/%01%05invalid_filename.txt?se=2020-06-20t09%3A04%3A57z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28 --output-type=json --overwrite=prompt --cancel-from-stdin --follow-symlinks --recursive --from-to=LocalBlob --blob-type=Detect --put-md5 
2020/05/21 09:04:58 Number of CPUs: 8
2020/05/21 09:04:58 Max file buffer RAM 4.000 GB
2020/05/21 09:04:58 Max concurrent network operations: 128 (Based on number of CPUs. Set AZCOPY_CONCURRENCY_VALUE environment variable to override)
2020/05/21 09:04:58 Check CPU usage when dynamically tuning concurrency: true (Based on hard-coded default. Set AZCOPY_TUNE_TO_CPU environment variable to true or false override)
2020/05/21 09:04:58 Max concurrent transfer initiation routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_FILES environment variable to override)
2020/05/21 09:04:58 Max open files when downloading: 7751 (auto-computed)
2020/05/21 09:04:58 PERF: primary performance constraint is Unknown. States: R:  0, D:  0, W:  0, F:  0, B:  0, E:  0, T:  0, GRs:  0
2020/05/21 09:04:58 JobID=4d002098-a002-0048-6871-66df28400a87, credential type: Anonymous
2020/05/21 09:04:58 scheduling JobID=4d002098-a002-0048-6871-66df28400a87, Part#=0, Transfer#=0, priority=0
2020/05/21 09:04:58 INFO: [P#0-T#0] has worker 21 which is processing TRANSFER
2020/05/21 09:04:58 INFO: [P#0-T#0] Starting transfer: Source "/Users/tom/Desktop/\x01\x05invalid_filename.txt" Destination "https://awprod1.blob.core.windows.net/raw-engie-mail2/%01%05invalid_filename.txt?se=2020-06-20t09%3A04%3A57z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28". Specified chunk size 8388608
2020/05/21 09:04:58 ==> REQUEST/RESPONSE (Try=1/22.946232ms, OpTime=249.37585ms) -- RESPONSE STATUS CODE ERROR
   HEAD https://awprod1.blob.core.windows.net/raw-engie-mail2/%01%05invalid_filename.txt?se=2020-06-20t09%3A04%3A57z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28&timeout=901
   User-Agent: [Microsoft Azure Storage Explorer, 1.12.0, darwin,  AzCopy/10.3.3 Azure-Storage/0.7 (go1.13; darwin)]
   X-Ms-Client-Request-Id: [94d7600b-e4f7-4dbc-6676-985a046bf5a6]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   RESPONSE Status: 400 Bad Request
   Content-Length: [324]
   Content-Type: [text/html; charset=us-ascii]
   Date: [Thu, 21 May 2020 09:04:58 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
Response Details: 

2020/05/21 09:04:58 ERR: [P#0-T#0] UPLOADFAILED: /Users/tom/Desktop/invalid_filename.txt : 000 : Could not check file existence. -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /Users/runner/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=) =====
Description=400 Bad Request, Details: (none)
   HEAD https://awprod1.blob.core.windows.net/raw-engie-mail2/%01%05invalid_filename.txt?se=2020-06-20t09%3A04%3A57z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28&timeout=901
   User-Agent: [Microsoft Azure Storage Explorer, 1.12.0, darwin,  AzCopy/10.3.3 Azure-Storage/0.7 (go1.13; darwin)]
   X-Ms-Client-Request-Id: [94d7600b-e4f7-4dbc-6676-985a046bf5a6]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   RESPONSE Status: 400 Bad Request
   Content-Length: [324]
   Content-Type: [text/html; charset=us-ascii]
   Date: [Thu, 21 May 2020 09:04:58 GMT]
   Server: [Microsoft-HTTPAPI/2.0]



   Dst: https://awprod1.blob.core.windows.net/raw-engie-mail2/%01%05invalid_filename.txt?se=2020-06-20t09%3A04%3A57z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28
2020/05/21 09:04:58 JobID=4d002098-a002-0048-6871-66df28400a87, Part#=0, TransfersDone=1 of 1
2020/05/21 09:04:58 all parts of entire Job 4d002098-a002-0048-6871-66df28400a87 successfully completed, cancelled or paused
2020/05/21 09:05:00 PERF: primary performance constraint is Unknown. States: R:  0, D:  0, W:  0, F:  0, B:  0, E:  0, T:  0, GRs: 128
```

Code to upload file using upload_blob with the associated stacktrace:
```
with open('/Users/tom/Desktop/\x01\x05invalid_filename.txt', 'rb') as data: 
  ...:     container_client.upload_blob('\x01\x05invalid_filename.txt', data)
  ...: 
Traceback (most recent call last):
  File "/Users/tom/.local/share/virtualenvs/aw-back-udw5yDb0/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-25379575d209>", line 2, in <module>
    container_client.upload_blob('\x01\x05invalid_filename.txt', data)
  File "/Users/tom/.local/share/virtualenvs/aw-back-udw5yDb0/lib/python3.7/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/Users/tom/.local/share/virtualenvs/aw-back-udw5yDb0/lib/python3.7/site-packages/azure/storage/blob/_container_client.py", line 843, in upload_blob
    **kwargs
  File "/Users/tom/.local/share/virtualenvs/aw-back-udw5yDb0/lib/python3.7/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/Users/tom/.local/share/virtualenvs/aw-back-udw5yDb0/lib/python3.7/site-packages/azure/storage/blob/_blob_client.py", line 496, in upload_blob
    return upload_block_blob(**options)
  File "/Users/tom/.local/share/virtualenvs/aw-back-udw5yDb0/lib/python3.7/site-packages/azure/storage/blob/_upload_helpers.py", line 104, in upload_block_blob
    **kwargs)
  File "/Users/tom/.local/share/virtualenvs/aw-back-udw5yDb0/lib/python3.7/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 212, in upload
    raise models.StorageErrorException(response, self._deserialize)
  File "/Users/tom/.local/share/virtualenvs/aw-back-udw5yDb0/lib/python3.7/site-packages/azure/storage/blob/_generated/models/_models_py3.py", line 1459, in __init__
    self.error = deserialize(model_name, response)
  File "/Users/tom/.local/share/virtualenvs/aw-back-udw5yDb0/lib/python3.7/site-packages/msrest/serialization.py", line 1293, in __call__
    data = self._unpack_content(response_data, content_type)
  File "/Users/tom/.local/share/virtualenvs/aw-back-udw5yDb0/lib/python3.7/site-packages/msrest/serialization.py", line 1439, in _unpack_content
    raw_data.headers
  File "/Users/tom/.local/share/virtualenvs/aw-back-udw5yDb0/lib/python3.7/site-packages/msrest/pipeline/universal.py", line 226, in deserialize_from_http_generics
    return cls.deserialize_from_text(body_bytes, content_type)
  File "/Users/tom/.local/share/virtualenvs/aw-back-udw5yDb0/lib/python3.7/site-packages/msrest/pipeline/universal.py", line 203, in deserialize_from_text
    raise DeserializationError("Cannot deserialize content-type: {}".format(content_type))
msrest.exceptions.DeserializationError: Cannot deserialize content-type: text/html
```

This happens whenever the desination blob_name contains the invalid characters in the path. Uploading a file from a local path containing the invalid characters, to a blob at a path without these characters does work. 
When the blob path also contains these characters the operation fails.

The documentation at does not specify these characters as invalid:
https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#blob-names

**Expected behavior**
The file is uploaded correctly; or at least a better error message is provided when there is a failure due to an invalid filename/blob-name.

**Comment by xiafu-msft** [comment]
Hi @tompauwaert  

"\x01x05" was taken as "x05", and  "" seems not to be a valid name even you create the file locally. If you skip '\' in this way "\\x01x05" you should be able to create a file with this name \x01x05.

Let me know if I didn't understand you problem properly!

**Comment by tompauwaert** [comment]
Hi @xiafu-msft,
Thanks for the response.
Apparently I made a small mistake in the bug-report. The filename should contain "\x01\x05" instead of "\x01x05" (lacking the second slash). But the end-result should still be the same in both  cases.

I've uploaded the file I created locally to recreate the issue. (I hope the encoding of the filename passes through correctly after uploading). But, this file created without any issues on my mac. Python also did not have any issues opening the file and reading/writing to it. Only the azure sdk had issues with it.

For mac the set of invalid characters for names seems to be limited to: 
```: on disk, in classic Mac OS, and at the Carbon layer in macOS; / at the Unix layer in macOS```
source: https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations
Which seems consistent with what I've experienced in macOS.

[invalid_filename.txt](https://github.com/Azure/azure-sdk-for-python/files/4687568/invalid_filename.txt)

I'm not sure what you mean by: 
"If you skip '' in this way "\x01x05" you should be able to create a file with this name \x01x05."

**Comment by xiafu-msft** [comment]
Hi @tompauwaert 

Thanks for the details! I wasn't able to create a file with this name "\x01\x05" on windows. If you refers to the reserved characters in other file systems, you will see ` " * / : < > ? \ |` are reserved. Service side should also using the same set of reserved characters ` " * / : < > ? \ |`. 

I can download that file (on windows), while the downloaded file has is named "invalid_filename.txt", I guess the file name is not as expected.. So the problem could be mac support more characters as file name than other file systems does.

```
I'm not sure what you mean by:
"If you skip '' in this way "\x01x05" you should be able to create a file with this name \x01x05."
```
Sorry about the confusion, I mean "\\x01\\x05". However I checked the uploaded file on portal, it was transformed to "<no name>/x01/x05.txt"

**Comment by tompauwaert** [comment]
Ah, I think I understand the confusion.
The filename does not actually contain, literally ```\x01\x05```. As in, the name of the file is not:
```backslash x 0 1 backslash x 0 5```. Those are the unicode encodings of the characters.

So the unicode encoding of the full filename, from python would be: 
```
In[9]: print('"\x01\x05"')
""
In[10]: '\x01\x05invalid_filename.txt'.encode('utf-8')
Out[10]: b'\x01\x05invalid_filename.txt'
```
The filename is not actually using the reserved backslash character ```\```, it's only using it as escape sequence.

It does seem like the uploaded file with invalid filename upon downloading no longer contains the two characters at the start of the filename. However, this python code should generate the file:

Here's some python code from interactive shell that better illustrates what I mean: 
```
# Works on Mac
with open('/Users/tom/Downloads/\x01\x05test-name.txt', 'w') as f:
   ...:     f.write('Here, have some content, Mr. file.')
   ...:     
# Does not work - because the file does not exist with this name
with open('/Users/tom/Downloads/test-name.txt', 'r') as f:
   ...:     print(f'The content: {f.read()}')
   ...:     
Traceback (most recent call last):
  File "/Users/tom/.local/share/virtualenvs/aw-back-udw5yDb0/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-a771228c0aa4>", line 1, in <module>
    with open('/Users/tom/Downloads/test-name.txt', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tom/Downloads/test-name.txt'

# This works however, because the filename is correct now.
with open('/Users/tom/Downloads/\x01\x05test-name.txt', 'r') as f:
   ...:     print(f'The content: {f.read()}')
   ...:     
The content: Here, have some content, Mr. file.

#
# Then uploading this to blob
#
from dotenv import load_dotenv
load_dotenv()
Out[18]: True
from azure.storage.blob import ContainerClient, BlobClient
from azure.identity import DefaultAzureCredential
cc = ContainerClient('https://<storage_account>.blob.core.windows.net', 'test', DefaultAzureCredential())

# Upload the to a blob-path that has the same filename as the local filename. Fails, because of the characters \x01\x05
with open('/Users/tom/Downloads/\x01\x05test-name.txt', 'r') as f:
   ...:     bc = cc.get_blob_client('parentdir/\x01\x05test-name.txt')
   ...:     bc.upload_blob(f.read())
   ...:     
Traceback (most recent call last):
  File "/Users/tom/.local/share/virtualenvs/aw-back-udw5yDb0/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-23-4b56ea8904d2>", line 3, in <module>
    bc.upload_blob(f.read())
  File "/Users/tom/.local/share/virtualenvs/aw-back-udw5yDb0/lib/python3.7/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/Users/tom/.local/share/virtualenvs/aw-back-udw5yDb0/lib/python3.7/site-packages/azure/storage/blob/_blob_client.py", line 496, in upload_blob
    return upload_block_blob(**options)
  File "/Users/tom/.local/share/virtualenvs/aw-back-udw5yDb0/lib/python3.7/site-packages/azure/storage/blob/_upload_helpers.py", line 104, in upload_block_blob
    **kwargs)
  File "/Users/tom/.local/share/virtualenvs/aw-back-udw5yDb0/lib/python3.7/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 212, in upload
    raise models.StorageErrorException(response, self._deserialize)
  File "/Users/tom/.local/share/virtualenvs/aw-back-udw5yDb0/lib/python3.7/site-packages/azure/storage/blob/_generated/models/_models_py3.py", line 1459, in __init__
    self.error = deserialize(model_name, response)
  File "/Users/tom/.local/share/virtualenvs/aw-back-udw5yDb0/lib/python3.7/site-packages/msrest/serialization.py", line 1320, in __call__
    data = self._unpack_content(response_data, content_type)
  File "/Users/tom/.local/share/virtualenvs/aw-back-udw5yDb0/lib/python3.7/site-packages/msrest/serialization.py", line 1474, in _unpack_content
    raw_data.headers
  File "/Users/tom/.local/share/virtualenvs/aw-back-udw5yDb0/lib/python3.7/site-packages/msrest/pipeline/universal.py", line 226, in deserialize_from_http_generics
    return cls.deserialize_from_text(body_bytes, content_type)
  File "/Users/tom/.local/share/virtualenvs/aw-back-udw5yDb0/lib/python3.7/site-packages/msrest/pipeline/universal.py", line 203, in deserialize_from_text
    raise DeserializationError("Cannot deserialize content-type: {}".format(content_type))
msrest.exceptions.DeserializationError: Cannot deserialize content-type: text/html

# Removing these characters from the blob-path works. Local python has no issue with these characters, so if we remove them from the blob-path, there are no issues.
with open('/Users/tom/Downloads/\x01\x05test-name.txt', 'r') as f:
   ...:     bc = cc.get_blob_client('parentdir/test-name.txt')
   ...:     bc.upload_blob(f.read())
   ...:     

```

**Comment by xiafu-msft** [comment]
hi @tompauwaert 

Thanks for clarifying!
The file name cannot have control characters, so if you want to put '\\x01' as a character in file name then service doesn't allow.
`some ASCII or Unicode characters, like control characters (0x00 to 0x1F, \u0081, etc.), are also not allowed`
Here is the name rules for storage blob https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata

Let me know if you have any concern!

**Comment by tompauwaert** [comment]
Ah yes. I missed that in the documentation.
Is it possible to give a clearer error message as to why the uploading fails? The current error gives little indication as to where the actual issue is.

Considering the fact that some of these characters are 'hardly visible', it makes for very strenuous debugging without a clearer indication of what went wrong.

**Comment by xiafu-msft** [comment]
Hi @tompauwaert 
It's a good feedback, thanks. We will talk to service to see if the error message could be more specific!

**Comment by xiafu-msft** [comment]
I will close this issue for now! feel free to open it if you have any concern!
