### ISSUE TITLE
azure 2.0.0 python library does not install via pip using Python 2.7.6

### ISSUE THREAD

**Issue by danhigham** [Azure/azure-sdk-for-python#1181]
The packaged version of Python on Ubuntu 14.04 is 2.7.6

When trying to install the azure python lib via pip installation fails;

```
pip install azure==2.0.0
Downloading/unpacking azure==2.0.0
  Downloading azure-2.0.0-py2.py3-none-any.whl
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1266, in prepare_files
    req_to_install.extras):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2291, in requires
    dm = self._dep_map
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2484, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2508, in _compute_dependencies
    parsed = next(parse_requirements(distvers))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 45, in <lambda>
    next = lambda o: o.next()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2573, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'azure-batch ~=3.0.0', 'at', ' ~=3.0.0')

Storing debug log for failure in /root/.pip/pip.log
```

**Comment by danhigham** [comment]
I should add the same happens when not specifying a version too

**Comment by lmazuel** [comment]
Hi @danhigham 

Minimal version of pip required is 6.0, and support for PEP440. Please update your pip on your virtual environment, and everything will be ok. This is written on the PyPI webpage of ["azure"](https://pypi.python.org/pypi/azure), but I will add it in the [installation page on RTD as well](http://azure-sdk-for-python.readthedocs.io/en/latest/installation.html).

Thank you,
