### ISSUE TITLE
azure-mgmt-network version 10.2.0 not supported in westeurope (ApplicationGateway)

### ISSUE THREAD

**Issue by hanifahhad** [Azure/azure-sdk-for-python#11816]
- **Package Name**: 
azure-mgmt-network
- **Package Version**: 
10.2.0
- **Operating System**:
Linux Alpine 3.11.5
- **Python Version**: 
3.8.2
**Describe the bug**
I'm using the azure-mgmt-network to get backend health information for the Azure Application Gateway. Few hours ago, the package version 10.2.0, API version 2020_04_01, is giving unsupported api.

Older versions are working fine, like 10.1.0 

**Expected behavior**
Backend health status 

**Traceback**

Traceback (most recent call last): File "/usr/lib/python3.8/site-packages/azure/mgmt/network/v2020_04_01/operations/_application_gateways_operations.py", line 724, in backend_health raw_result = self._backend_health_initial( File "/usr/lib/python3.8/site-packages/azure/mgmt/network/v2020_04_01/operations/_application_gateways_operations.py", line 685, in _backend_health_initial raise exp msrestazure.azure_exceptions.CloudError: Azure Error: NoRegisteredProviderFound Message: No registered resource provider found for location 'westeurope' and API version '2020-04-01' for type 'applicationGateways'. The supported api-versions are '2014-12-01-preview, 2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-06-01, 2016-07-01, 2016-08-01, 2016-09-01, 2016-10-01, 2016-11-01, 2016-12-01, 2017-03-01, 2017-04-01, 2017-06-01, 2017-08-01, 2017-09-01, 2017-10-01, 2017-11-01, 2018-01-01, 2018-02-01, 2018-03-01, 2018-04-01, 2018-05-01, 2018-06-01, 2018-07-01, 2018-08-01, 2018-10-01, 2018-11-01, 2018-12-01, 2019-02-01, 2019-04-01, 2019-06-01, 2019-07-01, 2019-08-01, 2019-09-01, 2019-11-01, 2019-12-01, 2020-01-01, 2020-03-01'. The supported locations are 'westus, eastus, northeurope, westeurope, eastasia, southeastasia, northcentralus, southcentralus, centralus, eastus2, japaneast, japanwest, brazilsouth, australiaeast, australiasoutheast, centralindia, southindia, westindia, canadacentral, canadaeast, westcentralus, westus2, ukwest, uksouth, koreacentral, koreasouth, francecentral, australiacentral, southafricanorth, uaenorth'.

**Comment by jeking3** [comment]
When I try to back off to azure-mgmt-network 9.x and run the same test I get:

msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/.../providers/Microsoft.Network/locations/eastus/operations/6f9361e5-b775-445a-bbe9-c134643396e8?api-version=2019-11-01 (Caused by ResponseError('too many 502 error responses'))

I wonder what happened at Azure...

**Comment by jeking3** [comment]
So this is not a bug in the library; see: https://status.azure.com/en-us/status

**Comment by hanifahhad** [comment]
The issue has been resolved. azure-mgmt-network version 10.2.0 is supported again (westeurope)
