### ISSUE TITLE
The property "key" must be a valid JsonWebKey object 

### ISSUE THREAD

**Issue by erikanderson** [Azure/azure-sdk-for-python#11822]
- **Package Name**: azure.keyvault.keys
- **Package Version**: 4.1.0
- **Operating System**: OSX
- **Python Version**: 3.8

**Describe the bug**
Using the [import_key method on KeyClient](https://docs.microsoft.com/en-us/python/api/azure-keyvault-keys/azure.keyvault.keys.keyclient?view=azure-python#import-key-name--key----kwargs-) with a valid [JsonWebKey](https://docs.microsoft.com/en-us/python/api/azure-keyvault-keys/azure.keyvault.keys.jsonwebkey?view=azure-python) object results in `The property "key" must be a valid JsonWebKey object `

**To Reproduce**
1. Create key_client, for example using UsernamePasswordCredential 
```
import secrets
from azure.identity import UsernamePasswordCredential
from azure.keyvault.keys import KeyClient
from azure.keyvault.keys import JsonWebKey

credential = UsernamePasswordCredential(
    '04b07795-8ddb-461a-bbee-02f9e1bf7b46', #static Azure CLI Client ID 
    "account@example.com", 
    "password", 
    resource='https://vault.azure.net', 
    tenant_id='tenantId,
    logging_enable=True
)

key_client = KeyClient(
    vaultUri, 
    credential,
    logging_enable=True
)
```
2. Generate JsonWebKey
```
        importTest = JsonWebKey(
               kid="importTest",
               kty="RSA",
               k=secrets.token_bytes(32)
               key_ops=["encrypt", "decrypt", "sign", "verify", "wrapKey", "unwrapKey"],
        )
```
3. Import key 
```
key = key_client.import_key(
        "importTest",
        importTest
)
```
**Expected behavior**
JsonWebKey is imported to keyvault

**Additional context**
Trace
```
Traceback (most recent call last):
  File "ImportTest.py", line 73, in <module>
    key = key_client.import_key(
  File "/Users/*****/venv/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/Users/*****/venv/lib/python3.8/site-packages/azure/keyvault/keys/_client.py", line 532, in import_key
    bundle = self._client.import_key(
  File "/Users/*****/venv/lib/python3.8/site-packages/azure/keyvault/keys/_shared/_generated/v7_0/operations/_key_vault_client_operations.py", line 165, in import_key
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/Users/*****/venv/lib/python3.8/site-packages/azure/core/exceptions.py", line 102, in map_error
    raise error
azure.core.exceptions.HttpResponseError: (BadParameter) The property "key" must be a valid JsonWebKey object.
```

**Comment by kaerm** [comment]
@erikanderson thanks for reporting this, @chlowell can you take a look at this

**Comment by chlowell** [comment]
These examples are valid in the narrow sense that our library allows constructing them. However, our library doesn't attempt to validate them as JWKs. It leaves that to Key Vault, which is the source of the error message. The first example can't be an RSA key, because `k` should be the bytes of a symmetric key. The second example includes no key material, which is to say it has nothing to import. If you're trying to create a new RSA key, [create_rsa_key](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-keyvault-keys/4.1.0/azure.keyvault.keys.html#azure.keyvault.keys.KeyClient.create_rsa_key) is a much easier way to do that. If you do need to import an existing key, our test suite has a working example of [importing an RSA key](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py#L116) which shows the required fields.

**Comment by erikanderson** [comment]
Ok, thank you very much @chlowell , will take a look at the test suite, test some more on end and then report back here
