### ISSUE TITLE
VSCodeCredential CredentialUnavailableError on Linux

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#11914]
`VSCodeCredential` may raise an error stating no user is logged in even when one is:
```
>>> from azure.identity import VSCodeCredential
>>> VSCodeCredential().get_token('scope')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/azure/identity/_credentials/vscode_credential.py", line 57, in get_token
    raise CredentialUnavailableError(message="No Azure user is logged in to Visual Studio Code.")
azure.identity._exceptions.CredentialUnavailableError: No Azure user is logged in to Visual Studio Code.
```
This occurs on Linux when using Python 2.7, and when using Python 3.8 on some distros.

Related: #11738

**Comment by xiangyan99** [comment]
Fixed in #11915
