### ISSUE TITLE
import error in azure-core-tracing

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#11927]
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/azure/core/tracing/__init__.py#L5

This line should be modified to 

```
from azure.core.tracingimport AbstractSpan, SpanKind, HttpSpanMixin
```

However, when that is done the CI fails.

**Steps to reprodce:**

Installed this with the removed _abstract_span from the import line

The wheels are created using
```
python setup.py bdist_wheel
```
```
pip install azure_core-1.6.1-py2.py3-none-any.whl
```
followed by 
```
 pip install azure_core_tracing_opentelemetry-1.0.0b5-py2.py3-none-any.whl
```

Here is the stack trace.
```
$ python example.py
Traceback (most recent call last):
  File "example.py", line 2, in <module>
    from azure.core.settings import settings
  File "C:\Users\Administrator\Documents\Workspace\azure-sdk-for-python\sdk\core\azure-core-tracing-opentelemetry\dist\envimport\lib\site-packages\azure\core\__init__.py", line 30, in <module>
    from ._pipeline_client import PipelineClient
  File "C:\Users\Administrator\Documents\Workspace\azure-sdk-for-python\sdk\core\azure-core-tracing-opentelemetry\dist\envimport\lib\site-packages\azure\core\_pipeline_client.py", line 29, in <module>
    from .pipeline import Pipeline
  File "C:\Users\Administrator\Documents\Workspace\azure-sdk-for-python\sdk\core\azure-core-tracing-opentelemetry\dist\envimport\lib\site-packages\azure\core\pipeline\__init__.py", line 178, in <module>
    from ._base import Pipeline  # pylint: disable=wrong-import-position
  File "C:\Users\Administrator\Documents\Workspace\azure-sdk-for-python\sdk\core\azure-core-tracing-opentelemetry\dist\envimport\lib\site-packages\azure\core\pipeline\_base.py", line 35, in <module>
    from azure.core.pipeline.policies import HTTPPolicy, SansIOHTTPPolicy
  File "C:\Users\Administrator\Documents\Workspace\azure-sdk-for-python\sdk\core\azure-core-tracing-opentelemetry\dist\envimport\lib\site-packages\azure\core\pipeline\policies\__init__.py", line 32, in <module>
    from ._distributed_tracing import DistributedTracingPolicy
  File "C:\Users\Administrator\Documents\Workspace\azure-sdk-for-python\sdk\core\azure-core-tracing-opentelemetry\dist\envimport\lib\site-packages\azure\core\pipeline\policies\_distributed_tracing.py", line 32, in <module>
    from azure.core.settings import settings
  File "C:\Users\Administrator\Documents\Workspace\azure-sdk-for-python\sdk\core\azure-core-tracing-opentelemetry\dist\envimport\lib\site-packages\azure\core\settings.py", line 35, in <module>
    from azure.core.tracing import AbstractSpan
  File "C:\Users\Administrator\Documents\Workspace\azure-sdk-for-python\sdk\core\azure-core-tracing-opentelemetry\dist\envimport\lib\site-packages\azure\core\tracing\__init__.py", line 5, in <module>
    from azure.core.tracing import AbstractSpan, SpanKind, HttpSpanMixin
ImportError: cannot import name 'AbstractSpan' from 'azure.core.tracing' (C:\Users\Administrator\Documents\Workspace\azure-sdk-for-python\sdk\core\azure-core-tracing-opentelemetry\dist\envimport\lib\site-packages\azure\core\tracing\__init__.py)
```

**Comment by lmazuel** [comment]
After invstigation it's a misunderstanding (I take the blame for it)
