### ISSUE TITLE
invalid json in swagger_to_sdk_config.json

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-sdk-for-python#12080]
Python SDK builds are failing for my new pull request at https://github.com/Azure/azure-rest-api-specs/pull/9859. The error is:

```
2020-06-16T23:06:12.433Z: Getting swagger_to_sdk_config.json file from "Azure/azure-sdk-for-python/master/swagger_to_sdk_config.json"...
[
  '##[error]2020-06-16T23:06:12.994Z: Failed to run SDK Automation: SyntaxError: Unexpected token } in JSON at position 382, {} '
]
SyntaxError: Unexpected token } in JSON at position 382
JSON.parse (<anonymous>)
    at SpecificationPullRequestGeneration.getSwaggerToSDKFileContent (/z/lib/specificationPullRequestGeneration.js:216:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async SpecificationPullRequestGeneration.getSDKRepository (/z/lib/specificationPullRequestGeneration.js:139:44)
    at async SpecificationPullRequestGeneration.addReadmeMdFileToGenerateForSDKRepository (/z/lib/specificationPullRequestGeneration.js:183:31)
    at async SpecificationPullRequest.addReadmeMdFilesToGenerateToSDKRepositories (/z/lib/specificationPullRequest.js:265:21)
    at async SpecificationPullRequest.populateSDKRepositoryReadmeMdFilesToGenerate (/z/lib/specificationPullRequest.js:81:9)
    at async SpecificationPullRequest.generateModifiedServices (/z/lib/specificationPullRequest.js:49:9)
    at async /z/lib/sdkAutomation.js:74:13
    at async executeAndLog (/z/lib/sdkAutomation.js:305:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! openapi-sdk-automation@13.0.1-7.20200605.3 start: `node lib/cli/cli.js`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the openapi-sdk-automation@13.0.1-7.20200605.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I think it is because #11654 committed invalid json 18 hours ago:
https://github.com/Azure/azure-sdk-for-python/pull/11654/files#diff-40123192e960d9409ef3d787d75962cdR11

cc @NullMDR @zikalino

**Comment by NullMDR** [comment]
Already fixed. Thanks for raising up this issue.
