### ISSUE TITLE
AZURE_RM_STORAGEACCOUNT module not working 

### ISSUE THREAD

**Issue by SudeepParajuli** [Azure/azure-sdk-for-python#1218]
**Python version : 2.7.13**
**Ansible version : 2.3.1**
**azure version : 2.0.0rc5**

I was trying to use **azure_rm_storageaccount** module to create a new storage account in azure cloud via ansible . I was getting the following error during ansible run : 

```
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/wh/pfvl8qvs0x5_pz59b64nkknr0000gn/T/ansible_aoOgG3/ansible_module_azure_rm_storageaccount.py", line 154, in <module>
    from ansible.module_utils.azure_rm_common import *
  File "/var/folders/wh/pfvl8qvs0x5_pz59b64nkknr0000gn/T/ansible_aoOgG3/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py", line 29, in <module>
ImportError: No module named packaging.version

fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/wh/pfvl8qvs0x5_pz59b64nkknr0000gn/T/ansible_aoOgG3/ansible_module_azure_rm_storageaccount.py\", line 154, in <module>\n    from ansible.module_utils.azure_rm_common import *\n  File \"/var/folders/wh/pfvl8qvs0x5_pz59b64nkknr0000gn/T/ansible_aoOgG3/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 29, in <module>\nImportError: No module named packaging.version\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}

```

**Comment by lmazuel** [comment]
Hi @SudeepParajuli 

This is not an Azure SDK for Python issue, but an Ansible issue, please open an issue on their repo, so it's labeled and tracked correctly.
That being said, this issue is most of the time an old version of setuptools. You might update your setuptools to fix it.
Thank you,
