### ISSUE TITLE
ContentDecodePolicy generates __new__() error

### ISSUE THREAD

**Issue by TheHunter896** [Azure/azure-sdk-for-python#12203]
**Using azure-storage-blob 12.3.1**

### Steps to reproduce
At some point in your code, __init__ or just in a plain file initialize a **BlobServiceClient** class with the classmethod **from_connection_string** with your own storage account connection string

Use then **get_container_client** to get your container client.

```python
service = BlobServiceClient.from_connection_string({your_connection_string}) #error happens here
container_service = service.get_container_client({your_container})
```
Run this, the output will be ->
```python
Traceback (most recent call last):
  File "C:/Users/DavidBros/Documents/ai_scripts/pdf_reader/test.py", line 4, in <module>
    {your_connection_string})
  File "C:\Users\DavidBros\Documents\ai_scripts\pdf_reader\env\lib\site-packages\azure\storage\blob\_blob_service_client.py", line 167, in from_connection_string
    return cls(account_url, credential=credential, **kwargs)
  File "C:\Users\DavidBros\Documents\ai_scripts\pdf_reader\env\lib\site-packages\azure\storage\blob\_blob_service_client.py", line 126, in __init__
    super(BlobServiceClient, self).__init__(parsed_url, service='blob', credential=credential, **kwargs)
  File "C:\Users\DavidBros\Documents\ai_scripts\pdf_reader\env\lib\site-packages\azure\storage\blob\_shared\base_client.py", line 109, in __init__
    self._config, self._pipeline = self._create_pipeline(self.credential, storage_sdk=service, **kwargs)
  File "C:\Users\DavidBros\Documents\ai_scripts\pdf_reader\env\lib\site-packages\azure\storage\blob\_shared\base_client.py", line 240, in _create_pipeline
    ContentDecodePolicy(response_encoding="utf-8"),
  File "C:\Users\DavidBros\AppData\Local\Programs\Python\Python37\Lib\typing.py", line 813, in __new__
    obj = super().__new__(cls, *args, **kwds)
TypeError: object.__new__() takes exactly one argument (the type to instantiate)
```
The main issue:

```python
  File "C:\Users\DavidBros\AppData\Local\Programs\Python\Python37\Lib\typing.py", line 813, in __new__
    obj = super().__new__(cls, *args, **kwds)
TypeError: object.__new__() takes exactly one argument (the type to instantiate)
```

```python 
policies = [
            QueueMessagePolicy(),
            config.headers_policy,
            config.proxy_policy,
            config.user_agent_policy,
            StorageContentValidation(),
            StorageRequestHook(**kwargs),
            self._credential_policy,
            ContentDecodePolicy(response_econding="utf-8"), #This line is causing the error
            RedirectPolicy(**kwargs),
            StorageHosts(hosts=self._hosts, **kwargs),
            config.retry_policy,
            config.logging_policy,
            StorageResponseHook(**kwargs),
            DistributedTracingPolicy(**kwargs),
            HttpLoggingPolicy(**kwargs)
        ]
```

### Expected behaviour:
The object BlobServiceClient initializes correctly and returns an authenticated object.

My pip freeze:

```
adal==1.2.2
annualinsight==1.0
azure==4.0.0
azure-applicationinsights==0.1.0
azure-batch==4.1.3
azure-cognitiveservices-nspkg==3.0.1
azure-cognitiveservices-search-newssearch==1.0.0
azure-cognitiveservices-search-nspkg==3.0.1
azure-common==1.1.23
azure-core==1.1.1
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-datalake-store==0.0.48
azure-eventgrid==1.3.0
azure-graphrbac==0.40.0
azure-identity==1.3.1
azure-keyvault==1.1.0
azure-loganalytics==0.1.0
azure-mgmt==4.0.0
azure-mgmt-advisor==1.0.1
azure-mgmt-applicationinsights==0.1.1
azure-mgmt-authorization==0.50.0
azure-mgmt-batch==5.0.1
azure-mgmt-batchai==2.0.0
azure-mgmt-billing==0.2.0
azure-mgmt-cdn==3.1.0
azure-mgmt-cognitiveservices==3.0.0
azure-mgmt-commerce==1.0.1
azure-mgmt-compute==4.6.2
azure-mgmt-consumption==2.0.0
azure-mgmt-containerinstance==1.5.0
azure-mgmt-containerregistry==2.8.0
azure-mgmt-containerservice==4.4.0
azure-mgmt-cosmosdb==0.4.1
azure-mgmt-datafactory==0.6.0
azure-mgmt-datalake-analytics==0.6.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-datamigration==1.0.0
azure-mgmt-devspaces==0.1.0
azure-mgmt-devtestlabs==2.2.0
azure-mgmt-dns==2.1.0
azure-mgmt-eventgrid==1.0.0
azure-mgmt-eventhub==2.6.0
azure-mgmt-hanaonazure==0.1.1
azure-mgmt-iotcentral==0.1.0
azure-mgmt-iothub==0.5.0
azure-mgmt-iothubprovisioningservices==0.2.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-loganalytics==0.2.0
azure-mgmt-logic==3.0.0
azure-mgmt-machinelearningcompute==0.4.1
azure-mgmt-managementgroups==0.1.0
azure-mgmt-managementpartner==0.1.1
azure-mgmt-maps==0.1.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-media==1.0.0
azure-mgmt-monitor==0.5.2
azure-mgmt-msi==0.2.0
azure-mgmt-network==2.7.0
azure-mgmt-notificationhubs==2.1.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-policyinsights==0.1.0
azure-mgmt-powerbiembedded==2.0.0
azure-mgmt-rdbms==1.9.0
azure-mgmt-recoveryservices==0.3.0
azure-mgmt-recoveryservicesbackup==0.3.0
azure-mgmt-redis==5.0.0
azure-mgmt-relay==0.1.0
azure-mgmt-reservations==0.2.1
azure-mgmt-resource==2.2.0
azure-mgmt-scheduler==2.0.0
azure-mgmt-search==2.1.0
azure-mgmt-servicebus==0.5.3
azure-mgmt-servicefabric==0.2.0
azure-mgmt-signalr==0.1.1
azure-mgmt-sql==0.9.1
azure-mgmt-storage==10.0.0
azure-mgmt-subscription==0.2.0
azure-mgmt-trafficmanager==0.50.0
azure-mgmt-web==0.35.0
azure-nspkg==3.0.2
azure-servicebus==0.21.1
azure-servicefabric==6.3.0.0
azure-servicemanagement-legacy==0.20.6
azure-storage==0.36.0
azure-storage-blob==12.3.1
azure-storage-common==1.4.2
azure-storage-file==1.4.0
azure-storage-queue==1.4.0
certifi==2019.9.11
cffi==1.13.2
chardet==3.0.4
cryptography==2.8
fuzzywuzzy==0.17.0
idna==2.8
isodate==0.6.0
msal==1.0.0
msal-extensions==0.1.3
msrest==0.6.10
msrestazure==0.6.2
newsapi==0.1.1
numpy==1.17.4
oauthlib==3.1.0
pandas==0.25.3
portalocker==1.5.2
pycparser==2.19
PyJWT==1.7.1
pyodbc==4.0.27
pypdfy==0.1.1
python-dateutil==2.8.1
pytz==2019.3
pywin32==227
PyYAML==5.3.1
requests==2.22.0
requests-oauthlib==1.3.0
six==1.13.0
urllib3==1.25.6
``` 

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by xiafu-msft** [comment]
azure-storage==0.36.0 is not expected to be here, would you like to create a new virtual environment and do pip install azure-storage-blob to see if your problem could be resolved?

**Comment by xiafu-msft** [comment]
Hi @TheHunter896 

It looks like this issue is not actionable for Storage SDK side, so we will close this issue for now. Feel free to reopen it if you have any question!

**Comment by jiasli** [comment]
Noticed you have 

```
azure-core==1.1.1
```

In this version, `ContentDecodePolicy` doesn't have `__init__`.

https://github.com/Azure/azure-sdk-for-python/blob/azure-core_1.1.1/sdk/core/azure-core/azure/core/pipeline/policies/_universal.py#L415

```py
class ContentDecodePolicy(SansIOHTTPPolicy):
    ...
    @classmethod
    def deserialize_from_text(
```

Passing `response_econding="utf-8"` is equivalent to passing it to `object()` which causes the failure in `typing.py`.

```py
class Generic:
    def __new__(cls, *args, **kwds):
        if super().__new__ is object.__new__ and cls.__init__ is not object.__init__:
            obj = super().__new__(cls)
        else:
            obj = super().__new__(cls, *args, **kwds)
```

`ContentDecodePolicy.__init__` was added by https://github.com/Azure/azure-sdk-for-python/pull/9595:

```py
class ContentDecodePolicy(SansIOHTTPPolicy):
    def __init__(self, response_encoding=None, **kwargs):  # pylint: disable=unused-argument
        # type: (Optional[str], Any) -> None
        self._response_encoding = response_encoding
```

Please update to the latest compatible version of `azure-core`:

```
pip install --upgrade azure-core
```
