### ISSUE TITLE
Diagnostic Setting Azure B2C - Resource provider not supported: microsoft.azureactivedirectory

### ISSUE THREAD

**Issue by erikanderson** [Azure/azure-sdk-for-python#12250]
- **azure.mgmt.monitor**
- **0.10.0**
- **OSX**
- **3.8.3**

**Describe the bug**
Listing of diagnostic settings in Azure AD B2C doesn't seem to be possible. 

**To Reproduce**
1. Get credential and attempt to list diagnostic settings
```
from msrestazure.azure_active_directory import UserPassCredentials
from azure.mgmt.monitor import MonitorManagementClient

def getUserPassCredential():
    credential = UserPassCredentials(
        serviceAccountPrincipalName, 
        serviceAccountPrincipalPassword, 
        tenant_id=tenant_id,
    )
    return credential

def getDiagnosticSetting(envName):
    credentials = getUserPassCredential()
    client = MonitorManagementClient(
        credentials, 
        subscription_id
    )
    print(client.diagnostic_settings.list(
  '/subscriptions/*******/resourceGroups/********/providers/Microsoft.AzureActiveDirectory/b2cDirectories/****.onmicrosoft.com'
      )
    )

getDiagnosticSetting()
```
2. Receive error: 
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/*********/code/*********-*********/*********/__main__.py", line 4, in <module>
    app.run()
  File "/Users/*********/code/*********-*********/*********/app.py", line 91, in run
    *********.azuread.diagnosticSetting.getDiagnosticSetting(envName)
  File "/Users/*********/code/*********-*********/*********/azuread/diagnosticSetting.py", line 26, in getDiagnosticSetting
    print(client.diagnostic_settings.list(
  File "/Users/*********/code/*********-*********/*******/lib/python3.8/site-packages/azure/mgmt/monitor/v2017_05_01_preview/operations/_diagnostic_settings_operations.py", line 264, in list
    raise models.ErrorResponseException(self._deserialize, response)
azure.mgmt.monitor.v2017_05_01_preview.models._models_py3.ErrorResponseException: Resource provider not supported: microsoft.azureactivedirectory
```
**Expected behavior**
List of diagnostic settings is returned 

**Additional context**
Working from this documentation: https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-monitor/0.10.0/azure.mgmt.monitor.html

Attempting to automate final step here: https://docs.microsoft.com/en-us/azure/active-directory-b2c/azure-monitor

**Comment by erikanderson** [comment]
Got the same thing when I tried using the same subscription/account/etc here: 
https://docs.microsoft.com/en-us/rest/api/monitor/diagnosticsettings/list
```
{
  "code": "ResourceNotSupported",
  "message": "Resource provider not supported: microsoft.azureactivedirectory"
}
```
So not limited to this SDK, closing
