### ISSUE TITLE
HttpOperationError is not defined for logic app workflow trigger

### ISSUE THREAD

**Issue by Lilja** [Azure/azure-sdk-for-python#12335]
- **Package Name**: azure-mgmt-logic
- **Package Version**: 3.0.0
- **Operating System**: N/A
- **Python Version**: N/A

**Describe the bug**
The exception is not imported for this file: https://github.com/Azure/azure-sdk-for-python/blob/aff33bd40c12b16ec3eeaf9ccb7925f884a8a913/sdk/logic/azure-mgmt-logic/azure/mgmt/logic/operations/workflow_triggers_operations.py#L287

```
Traceback (most recent call last):
  File "azure_test.py", line 41, in <module>
    x = logic_client.workflow_triggers.run(resource_group, action, "manual")
  File "/Users/lilja/venv/lib/python3.8/site-packages/azure/mgmt/logic/operations/workflow_triggers_operations.py", line 290, in run
    raise HttpOperationError(self._deserialize, response, 'object')
NameError: name 'HttpOperationError' is not defined
```

**Comment by kaerm** [comment]
Thanks @Lilja for reporting this, @nickzhums can you take a look at this?

**Comment by changlong-liu** [comment]
Hi @lmazuel , this looks like a codegen issue since HttpOperationError is not imported.  Would you help to have a look, thank you!

**Comment by lmazuel** [comment]
Created an autorest issue https://github.com/Azure/autorest.python/issues/703

**Comment by lmazuel** [comment]
@RodgeFu @changlong-liu This is a Swagger issue that is fixed in https://github.com/Azure/azure-rest-api-specs/pull/8934
You can decide to re-ship a stable version 3.1.0 or 3.0.1 using autorest v4 of latest swagger in order to fix this issue

**Comment by changlong-liu** [comment]
Hi service team,  I see new features and block changes in https://github.com/Azure/azure-rest-api-specs/pull/8934. Would you help to submit sdk-release-request if the changes are ready to release? Thanks.

**Comment by SatishBoddu-MSFT** [comment]
Hello @Lilja , @lmazuel Apologies for the delayed response. I see that this issue is opened a long time ago and no further activity had taken place. So wanted to check if we are good to close this issue?
