### ISSUE TITLE
Unable to initiate BlobServiceClient on Alpine Linux

### ISSUE THREAD

**Issue by marcoszh** [Azure/azure-sdk-for-python#12739]
- **azure-storage-blob**: 
- **azure-core-1.7.0 azure-storage-blob-12.3.2**: 
- **Alpine Linux 3.10**:
- **3.7.7**: 

**Describe the bug**
Cannot initiate BlobServiceClient with the correct connection string. Codes work fine on Ubuntu, but fail with Alpine Linux.

**To Reproduce**
1. Call blob_service_client = BlobServiceClient.from_connection_string(connect_str) on Alpine Linux 3.1

**Expected behavior**
Successful client establishment

**Screenshots**
/ # python3 test.py
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    blob_service_client = BlobServiceClient.from_connection_string(connect_str)
  File "/usr/lib/python3.7/site-packages/azure/storage/blob/_blob_service_client.py", line 167, in from_connection_string
    return cls(account_url, credential=credential, **kwargs)
  File "/usr/lib/python3.7/site-packages/azure/storage/blob/_blob_service_client.py", line 126, in __init__
    super(BlobServiceClient, self).__init__(parsed_url, service='blob', credential=credential, **kwargs)
  File "/usr/lib/python3.7/site-packages/azure/storage/blob/_shared/base_client.py", line 109, in __init__
    self._config, self._pipeline = self._create_pipeline(self.credential, storage_sdk=service, **kwargs)
  File "/usr/lib/python3.7/site-packages/azure/storage/blob/_shared/base_client.py", line 224, in _create_pipeline
    config = kwargs.get("_configuration") or create_configuration(**kwargs)
  File "/usr/lib/python3.7/site-packages/azure/storage/blob/_shared/base_client.py", line 390, in create_configuration
    sdk_moniker="storage-{}/{}".format(kwargs.pop('storage_sdk'), VERSION), **kwargs)
  File "/usr/lib/python3.7/site-packages/azure/core/pipeline/policies/_universal.py", line 200, in __init__
    platform.platform()
  File "/usr/lib/python3.7/platform.py", line 1390, in platform
    libcname, libcversion = libc_ver(sys.executable)
  File "/usr/lib/python3.7/platform.py", line 196, in libc_ver
    executable = os.path.realpath(executable)
  File "/usr/lib/python3.7/posixpath.py", line 395, in realpath
    path, ok = _joinrealpath(filename[:0], filename, {})
  File "/usr/lib/python3.7/posixpath.py", line 443, in _joinrealpath
    path, ok = _joinrealpath(path, os.readlink(newpath), seen)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/python3'

**Additional context**

**Comment by marcoszh** [comment]
I have bypassed the issue by replacing the platform.platform() call with a fixed string in /azure/core/pipeline/policies/_universal.py.
