### ISSUE TITLE
Azure Storage Blob: delete_blobs returns warning when using list[dict] as argument

### ISSUE THREAD

**Issue by dr-dolittle** [Azure/azure-sdk-for-python#12778]
- **Package Name**: azure.storage.blob
- **Package Version**:  12.3.2
- **Operating System**: Windows
- **Python Version**:  3.8.1

I retrieve blobs matching a certain pattern and then delete them:

```
from azure.storage.blob import ContainerClient, BlobProperties
from azure.core.paging import ItemPaged
from typing import List

blob_paged: ItemPaged[BlobProperties] = container_client.list_blobs(name_starts_with=prefix)
blob_list: List[dict] = list(blob_paged)
number_of_blobs: int = len(blob_list)

if number_of_blobs > 0:
    container_client.delete_blobs(*blob_list, delete_snapshots="include")
    log.debug(f"Deleted '{ number_of_blobs }' blobs and snapshots...")   
else:
    log.debug(f"No blobs to be deleted...")
```

It works but it emits the following warning logs for each request made through the deletion process:

```
Failed to parse headers (url=https://xxx.blob.core.windows.net:443/?comp=batch): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "xxx\__app__\.venv\lib\site-packages\urllib3\connectionpool.py", line 446, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "xxx\__app__\.venv\lib\site-packages\urllib3\util\response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
```

Is this intended? If not, can you please fix that?

Thanks

**Comment by xiafu-msft** [comment]
Hi @dr-dolittle 

Thanks for reporting this issue! the pr above should resolve the problem!

**Comment by dr-dolittle** [comment]
@xiafu-msft Just tested it again. The warning is still displayed

```
Failed to parse headers (url=https://xxx.blob.core.windows.net:443/?comp=batch): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "C:\xxx\__app__\.venv\lib\site-packages\urllib3\connectionpool.py", line 446, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "C:\xxx\__app__\.venv\lib\site-packages\urllib3\util\response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
```
