### ISSUE TITLE
Creating, listing, accessing datastores from using a Workspace object that was got from azureml.core.Workspace.list raises an exception AttributeError: 'GenericResourceExpanded' object has no attribute 'workspaceid'

### ISSUE THREAD

**Issue by tam203** [Azure/azure-sdk-for-python#12948]
- **Package Name**: azureml-core
- **Package Version**: 1.11.0
- **Operating System**: macOS Catalina 10.15.5
- **Python Version**: Python 3.8.5

**Describe the bug**
Creating, listing, accessing datastores from using a Workspace object that was got from `azureml.core.Workspace.list` raises an exception `AttributeError: 'GenericResourceExpanded' object has no attribute 'workspaceid'`.

**To Reproduce**

Run this code on the above version. With `SUBSCRIPTION_ID` set in env var.

```python
from azureml.core import Workspace
from azureml.core.datastore import Datastore
from msrest.exceptions import HttpOperationError
import os

SUBSCRIPTION_ID = os.environ.get('SUBSCRIPTION_ID')

ws_list = Workspace.list(SUBSCRIPTION_ID)
ws = next(iter(ws_list.values()))[0]

## uncomment this next line and the code will work as expected
# ws = Workspace(ws.subscription_id, ws.resource_group, ws.name)

ds_name = "mytest"

try:
    homespace_datastore = Datastore.get(ws, ds_name)
    print(f"Datastore {ds_name} exists")
except HttpOperationError:
    print(f"Datastore {ds_name} does not exist")

```

**Expected behavior**
The code prints either `Datastore mytest does not exist` or `Datastore mytest exists`

**Note:** replacing the Workspace object for from the `list` operation with one 'manually' created resolves the issue see commented out code (`ws = Workspace(ws.subscription_id, ws.resource_group, ws.name)`)

**Screenshots**

**Additional context**
Traceback
```
Traceback (most recent call last):
  File "/Users/theo/repos/az-ml-personal-files-connect/issue.py", line 17, in <module>
    homespace_datastore = Datastore.get(ws, ds_name)
  File "/Users/theo/external/miniconda3/azml/lib/python3.8/site-packages/azureml/core/datastore.py", line 141, in get
    return Datastore._client().get(workspace, datastore_name)
  File "/Users/theo/external/miniconda3/azml/lib/python3.8/site-packages/azureml/data/datastore_client.py", line 65, in get
    return _DatastoreClient._get(workspace, datastore_name)
  File "/Users/theo/external/miniconda3/azml/lib/python3.8/site-packages/azureml/data/datastore_client.py", line 543, in _get
    client = _DatastoreClient._get_client(ws, auth, host)
  File "/Users/theo/external/miniconda3/azml/lib/python3.8/site-packages/azureml/data/datastore_client.py", line 730, in _get_client
    ws._workspace_name), ws._workspace_id, ws.discovery_url)
  File "/Users/theo/external/miniconda3/azml/lib/python3.8/site-packages/azureml/core/workspace.py", line 1230, in _workspace_id
    self._workspace_id_internal = self._workspace_autorest_object.workspaceid
AttributeError: 'GenericResourceExpanded' object has no attribute 'workspaceid'
```

Environment:
```

channels:
  - defaults
dependencies:
  - ca-certificates=2020.6.24=0
  - certifi=2020.6.20=py38_0
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - ncurses=6.2=h0a44026_1
  - openssl=1.1.1g=h1de35cc_0
  - pip=20.1.1=py38_1
  - python=3.8.5=h26836e1_0
  - readline=8.0=h1de35cc_0
  - setuptools=49.2.0=py38_0
  - sqlite=3.32.3=hffcf06c_0
  - tk=8.6.10=hb0a8c7a_0
  - wheel=0.34.2=py38_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - adal==1.2.4
    - applicationinsights==0.11.9
    - azure-common==1.1.25
    - azure-core==1.7.0
    - azure-graphrbac==0.61.1
    - azure-identity==1.2.0
    - azure-mgmt-authorization==0.60.0
    - azure-mgmt-containerregistry==2.8.0
    - azure-mgmt-keyvault==2.2.0
    - azure-mgmt-resource==10.2.0
    - azure-mgmt-storage==11.1.0
    - azureml-automl-core==1.11.0
    - azureml-core==1.11.0
    - azureml-dataprep==2.0.2
    - azureml-dataprep-native==14.2.1
    - azureml-dataset-runtime==1.11.0.post1
    - azureml-pipeline==1.11.0
    - azureml-pipeline-core==1.11.0
    - azureml-pipeline-steps==1.11.0
    - azureml-sdk==1.11.0
    - azureml-telemetry==1.11.0
    - azureml-train==1.11.0
    - azureml-train-automl-client==1.11.0
    - azureml-train-core==1.11.0
    - azureml-train-restclients-hyperdrive==1.11.0
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - cffi==1.14.1
    - chardet==3.0.4
    - cloudpickle==1.5.0
    - contextlib2==0.6.0.post1
    - cryptography==3.0
    - distro==1.5.0
    - docker==4.2.2
    - dotnetcore2==2.1.14
    - fusepy==3.0.1
    - idna==2.10
    - importlib-metadata==1.7.0
    - isodate==0.6.0
    - jeepney==0.4.3
    - jmespath==0.10.0
    - jsonpickle==1.4.1
    - msal==1.4.3
    - msal-extensions==0.1.3
    - msrest==0.6.18
    - msrestazure==0.6.4
    - ndg-httpsclient==0.5.1
    - numpy==1.19.1
    - oauthlib==3.1.0
    - pathspec==0.8.0
    - portalocker==1.7.1
    - pyarrow==0.17.1
    - pyasn1==0.4.8
    - pycparser==2.20
    - pyjwt==1.7.1
    - pyopenssl==19.1.0
    - python-dateutil==2.8.1
    - pytz==2020.1
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - ruamel-yaml==0.16.10
    - ruamel-yaml-clib==0.2.0
    - secretstorage==3.1.2
    - six==1.15.0
    - urllib3==1.25.10
    - websocket-client==0.57.0
    - zipp==3.1.0

```

**Comment by rastala** [comment]
@tam203 In this case, the Workspace.list doesn't return the full workspace object, it only returns basic information about existing workspaces in the subscription. The reason for this behavior is to keep the API calls efficient. 

To get a full object for specific workspace, call Workspace.get(...).

I created a documentation bug to our backlog to make this behavior more clear.
