### ISSUE TITLE
Management - Consumption Package Using Outdated API Version

### ISSUE THREAD

**Issue by sas-adstut** [Azure/azure-sdk-for-python#12995]
- **Package Name**: azure-mgmt-consumption
- **Package Version**: 3.0.0
- **Operating System**: MacOS
- **Python Version**: 3.6.5

**Describe the bug**
This package defines its api_version as "2019-04-01-preview", however, "2019-10-01" is the current version according to the Consumption REST documentation.  The following error is encountered when attempting to list reservation recommendations using this package and its 2019-04-01-preview api_version, which seems to indicate that the 2019-04-01-preview API version is not a valid option any more:

```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    for rec in client.reservation_recommendations.list():
  File "/Users/xxxxxxxx/.virtualenvs/azure/lib/python3.6/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/Users/xxxxxxxx/.virtualenvs/azure/lib/python3.6/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/Users/xxxxxxxx/.virtualenvs/azure/lib/python3.6/site-packages/azure/mgmt/consumption/operations/reservation_recommendations_operations.py", line 94, in internal_paging
    raise models.ErrorResponseException(self._deserialize, response)
azure.mgmt.consumption.models.error_response_py3.ErrorResponseException: (InvalidResourceType) The resource type 'ReservationRecommendations' could not be found in the namespace 'Microsoft.Consumption' for api version '2019-04-01-preview'. The supported api-versions are '2018-03-31,2018-06-30,2018-08-31,2018-10-01,2019-01-01,2019-01-01-preview,2019-05-01,2019-10-01'.
```

**To Reproduce**
1. With proper CLI credentials and python packages in place, run the following python script:
```
#!/usr/bin/env python3
from azure.common import credentials
from azure.mgmt.consumption import ConsumptionManagementClient

creds, sub = credentials.get_azure_cli_credentials()
client = ConsumptionManagementClient(creds, sub)
print(sub)
for rec in client.reservation_recommendations.list():
    print(rec)
```

**Expected behavior**
Expected behavior is to receive the response from the reservation recommendation endpoint instead of the invalid resource type error.

**All azure packages and versions installed in my virtual environment**
```
$ pip list | grep azure
azure-cli-core          2.10.1
azure-cli-nspkg         3.0.4
azure-cli-telemetry     1.0.4
azure-common            1.1.25
azure-core              1.8.0
azure-mgmt-consumption  3.0.0
azure-mgmt-core         1.0.0
azure-mgmt-resource     10.1.0
azure-mgmt-subscription 0.6.0
azure-nspkg             3.0.2
msrestazure             0.6.4
```

**Comment by ramaganesan-rg** [comment]
This doesnt appear to a service issue. Please let the team know if you need further assistance.
