### ISSUE TITLE
Error deploying ML model on ACI

### ISSUE THREAD

**Issue by jay2017-git** [Azure/azure-sdk-for-python#12996]
I'm trying to deploy my ML model on ACI using this code.
`
from azureml.core.webservice import AciWebservice, Webservice
from azureml.exceptions import WebserviceException

deployment_config = AciWebservice.deploy_configuration(cpu_cores=2, memory_gb=6)
aci_service_name = 'ml-model'

try:
    service = Webservice(ws, name=aci_service_name)
    if service:
        service.delete()
except WebserviceException as e:
    print()

service = Model.deploy(ws, aci_service_name, [kp_model], inference_config, deployment_config)

service.wait_for_deployment(True)
print(service.state)
`

Here is the error am getting

`2020-08-10T11:01:28,103498848+00:00 - rsyslog/run 
2020-08-10T11:01:28,109724839+00:00 - nginx/run 
2020-08-10T11:01:28,111248110+00:00 - gunicorn/run 
EdgeHubConnectionString and IOTEDGE_IOTHUBHOSTNAME are not set. Exiting...
2020-08-10T11:01:28,192849628+00:00 - iot-server/finish 1 0
2020-08-10T11:01:28,194532107+00:00 - Exit code 1 is normal. Not restarting iot-server.
Starting gunicorn 19.9.0
Listening at: http://127.0.0.1:31311 (18)
Using worker: sync
worker timeout is set to 300
Booting worker with pid: 42
SPARK_HOME not set. Skipping PySpark Initialization.
Exception in worker process
Traceback (most recent call last):
  File "/azureml-envs/azureml_d31cd964833447a6573171273c4f1235/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/azureml-envs/azureml_d31cd964833447a6573171273c4f1235/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/azureml-envs/azureml_d31cd964833447a6573171273c4f1235/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/azureml-envs/azureml_d31cd964833447a6573171273c4f1235/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/azureml-envs/azureml_d31cd964833447a6573171273c4f1235/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/azureml-envs/azureml_d31cd964833447a6573171273c4f1235/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/azureml-envs/azureml_d31cd964833447a6573171273c4f1235/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/var/azureml-server/wsgi.py", line 1, in <module>
    import create_app
  File "/var/azureml-server/create_app.py", line 3, in <module>
    from app import main
  File "/var/azureml-server/app.py", line 31, in <module>
    import main as user_main
ModuleNotFoundError: No module named 'main'
Worker exiting (pid: 42)
Shutting down: Master
Reason: Worker failed to boot.
2020-08-10T11:01:28,524618650+00:00 - gunicorn/finish 3 0
2020-08-10T11:01:28,526020716+00:00 - Exit code 3 is not normal. Killing image`

**Comment by chunyu3** [comment]
azureml.core.webservice is not mgmt package.

**Comment by rodrigofp-cit** [comment]
Exactly the same here.
I have no clue where to start debugging.
Any suggestions?

**Comment by shivanissambare** [comment]
The first step in debugging errors is to get your deployment logs.

Can you run and check : az ml service get-logs --verbose --workspace-name <my workspace name> --name <service name>

You can also follow our troubleshooting guide : 
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-troubleshoot-deployment?tabs=azcli

Let us know if this doesn't help.

Thank you!

**Comment by shivanissambare** [comment]
Closing this issue, please feel free to re-open/ping us incase you need more help.
Thank you!

**Comment by shivanissambare** [comment]
Closing this issue, please re-open or let us know in case you need more help.
Thank you!

**Comment by shivanissambare** [comment]
#please-close
