### ISSUE TITLE
KeyError: 'refreshToken'

### ISSUE THREAD

**Issue by ojarva** [Azure/azure-sdk-for-python#1304]
Refreshing tokens seems to be broken with `KeyError: 'refreshToken'`.

Code used to initialize ComputeManagementClient:

```
import adal
from msrestazure.azure_active_directory import AdalAuthentication
from azure.mgmt.compute import ComputeManagementClient

LOGIN_ENDPOINT = 'https://login.microsoftonline.com/'
TENANT = 'tenant-id-here'
resource = 'https://management.core.windows.net/' #AAD graph resource

client = 'client-id-here'
key = 'client-password-here'

context = adal.AuthenticationContext(LOGIN_ENDPOINT+TENANT)
credentials = AdalAuthentication(
    context.acquire_token_with_client_credentials,
    resource,
    client,
    key
)

subscription_id = 'subscription-id-here'

client = ComputeManagementClient(credentials, subscription_id)
print client.virtual_machines.list_all().next().name
```

This works fine (i.e., app has been configured properly to Azure, and the code above prints VM name properly).

However, when the same client was in interactive python console overnight, running `client.virtual_machines.list_all().next().name` prints following traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "azure-vm/dev/lib/python2.7/site-packages/msrest/paging.py", line 109, in __next__
    self.advance_page()
  File "azure-vm/dev/lib/python2.7/site-packages/msrest/paging.py", line 95, in advance_page
    self._response = self._get_next(self.next_link)
  File "azure-vm/dev/lib/python2.7/site-packages/azure/mgmt/compute/compute/v2016_04_30_preview/operations/virtual_machines_operations.py", line 732, in internal_paging
    request, header_parameters, **operation_config)
  File "azure-vm/dev/lib/python2.7/site-packages/msrest/service_client.py", line 176, in send
    session = self.creds.signed_session()
  File "azure-vm/dev/lib/python2.7/site-packages/msrestazure/azure_active_directory.py", line 615, in signed_session
    raw_token = self._adal_method(*self._args, **self._kwargs)
  File "azure-vm/dev/lib/python2.7/site-packages/adal/authentication_context.py", line 160, in acquire_token_with_client_credentials
    return self._acquire_token(token_func)
  File "azure-vm/dev/lib/python2.7/site-packages/adal/authentication_context.py", line 109, in _acquire_token
    return token_func(self)
  File "azure-vm/dev/lib/python2.7/site-packages/adal/authentication_context.py", line 158, in token_func
    return token_request.get_token_with_client_credentials(client_secret)
  File "azure-vm/dev/lib/python2.7/site-packages/adal/token_request.py", line 304, in get_token_with_client_credentials
    token = self._find_token_from_cache()
  File "azure-vm/dev/lib/python2.7/site-packages/adal/token_request.py", line 128, in _find_token_from_cache
    return self._cache_driver.find(cache_query)
  File "azure-vm/dev/lib/python2.7/site-packages/adal/cache_driver.py", line 182, in find
    is_resource_tenant_specific)
  File "azure-vm/dev/lib/python2.7/site-packages/adal/cache_driver.py", line 168, in _refresh_entry_if_necessary
    return self._refresh_expired_entry(entry)
  File "azure-vm/dev/lib/python2.7/site-packages/adal/cache_driver.py", line 146, in _refresh_expired_entry
    token_response = self._refresh_function(entry, None)
  File "azure-vm/dev/lib/python2.7/site-packages/adal/token_request.py", line 137, in _get_token_with_token_response
    refresh_token = entry[TOKEN_RESPONSE_FIELDS.REFRESH_TOKEN]
KeyError: 'refreshToken'
```

See exact versions from attached [requirements.txt](https://github.com/Azure/azure-sdk-for-python/files/1155000/requirements.txt)

**Comment by lmazuel** [comment]
Thanks @ojarva for the feedback.
@yugangw-msft seems a ADAL issue, what do you think?

**Comment by yugangw-msft** [comment]
Token refreshing is not available with service principals as AAD doesn't give out a refreshToken, hence the failure. ADAL has made a [change](https://github.com/AzureAD/azure-activedirectory-library-for-python/pull/87) to avoid this uncaught exception, and just returns None. Still the client code, maybe msrest runtime, needs to handle the case and invoke `acquire_token_with_client_credentials` again.

**Comment by yugangw-msft** [comment]
Suggest 'by design', unless we want to handle token expiration in the msrest-azure layer

**Comment by lmazuel** [comment]
@ojarva Based on @yugangw-msft PR, this is fixed in ADAL 0.4.6 (yours is 0.4.5). See release note:
https://github.com/AzureAD/azure-activedirectory-library-for-python/releases/tag/0.4.6

Could be update ADAL and let us know if this is solved?

**Comment by ojarva** [comment]
@lmazuel sorry about the delay. I'll try this and report back after the key expires, so in few hours / tomorrow.

**Comment by ojarva** [comment]
I can confirm updating ADAL to 0.4.6 fixes this issue.

**Comment by lmazuel** [comment]
Thank you for the confirmation @ojarva !
