### ISSUE TITLE
Unable to query backups with filter and startTime

### ISSUE THREAD

**Issue by DataDecay** [Azure/azure-sdk-for-python#13123]
- **Package Name**: azure-mgmt-recoveryservicesbackup
- **Package Version**: 0.6.0
- **Operating System**: Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
- **Python Version**: Python 3.6.10

**Describe the bug**
I am unable to query the recoveryservicesbackup api using the python sdk for date ranges on startTime.

**To Reproduce**
1. ```
>>> iaasvm_odata_filter = "startTime eq '2020-08-1400:32:38'"
>>> backups = conn.azure_sdk_client.backup_jobs.list('auto-infrastructure-as-code-backup-vault', 'auto_infrastructure_as_code', filter=iaasvm_odata_filter)
>>> for backup in backups:
...     str(backup.properties.start_time)
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/philipkrauss/miniconda3/envs/dev_azure24/lib/python3.6/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/Users/philipkrauss/miniconda3/envs/dev_azure24/lib/python3.6/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/Users/philipkrauss/miniconda3/envs/dev_azure24/lib/python3.6/site-packages/azure/mgmt/recoveryservicesbackup/operations/_backup_jobs_operations.py", line 110, in internal_paging
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: BMSUserErrorGetJobsInvalidInput
Message: The inputs specified for Get jobs API are incorrect. Please check your inputs and try again.
Make sure your filter parameters are following these guidelines - The OData filter options. status eq { InProgress , Completed , Failed , CompletedWithWarnings , Cancelled , Cancelling } and backupManagementType eq {AzureIaasVM, MAB, DPM, AzureBackupServer, AzureSql } and operation eq { ConfigureBackup , Backup , Restore , DisableBackup , DeleteBackupData } and jobId eq {guid} and startTime eq { yyyy-mm-dd hh:mm:ss PM } and endTime eq { yyyy-mm-dd hh:mm:ss PM }.
```

or a filter such as

```
>>> iaasvm_odata_filter = "startTime ge '{}T00:00:00Z'".format(datetime.datetime.now().date())
>>> backups = conn.azure_sdk_client.backup_jobs.list('auto-infrastructure-as-code-backup-vault', 'auto_infrastructure_as_code', filter=iaasvm_odata_filter)
>>> for backup in backups:
...     str(backup.properties.start_time)
...
'2020-08-14 00:32:38.202948+00:00'
'2020-08-13 00:32:42.812803+00:00'
'2020-08-12 00:32:14.893336+00:00'
'2020-08-11 00:32:31.104376+00:00'
'2020-08-10 14:28:14.387283+00:00'
'2020-08-10 14:24:14.013058+00:00'
```

**Expected behavior**

using a filter like:

```
iaasvm_odata_filter = "startTime ge '{}T00:00:00Z'".format(datetime.datetime.now().date())
```

should return nothing, as i have no backups today yet.

**Screenshots**
na

**Additional context**
I will be honest this could be me not hitting the mark on whats expected, however following the exceptions, suggestion

startTime eq { yyyy-mm-dd hh:mm:ss PM }

```
>>> iaasvm_odata_filter = "startTime ge '2020-08-14 16:37:05 PM'"
>>> backups = conn.azure_sdk_client.backup_jobs.list('auto-infrastructure-as-code-backup-vault', 'auto_infrastructure_as_code', filter=iaasvm_odata_filter)
>>> for backup in backups:
...     str(backup.properties.start_time)
...
'2020-08-14 00:32:38.202948+00:00'
'2020-08-13 00:32:42.812803+00:00'
'2020-08-12 00:32:14.893336+00:00'
'2020-08-11 00:32:31.104376+00:00'
'2020-08-10 14:28:14.387283+00:00'
'2020-08-10 14:24:14.013058+00:00'
```

still no luck.

**Comment by pvrk** [comment]
@sambitratha: Can we provide some suggestion here?

**Comment by sambitratha** [comment]
retain_until field should be of format **2020-08-31T00:00:00.000Z**
Here is a snapshot how this can be generated
`
from datetime import datetime, timedelta

retain_until = (datetime.utcnow() + timedelta(days=30)).strftime('%d-%m-%Y')
`

**Comment by DataDecay** [comment]
> retain_until field should be of format **2020-08-31T00:00:00.000Z**
> Here is a snapshot how this can be generated
> `
> from datetime import datetime, timedelta
> 
> retain_until = (datetime.utcnow() + timedelta(days=30)).strftime('%d-%m-%Y')
> `

i did try that formatting suggestion:

`iaasvm_odata_filter = "startTime ge '{}T00:00:00Z'".format(datetime.datetime.now().date())`

Which results in the same format.

**Comment by sambitratha** [comment]
Hi @DataDecay  in filter strings only **eq** is supported. So you may have to replace the ge by eq. 
And can you please try the filter **startTime eq '2020-08-18 05:29:36 AM'**

@pvrk  can we please add someone from service team for quicker resolution to this problem?

**Comment by DataDecay** [comment]
@sambitratha so there is no way to query backup data from a date range?

**Comment by pvrk** [comment]
@DataDecay : Can you please elaborate on the date range? I think 'startTime eq' and 'endTime eq' should act as a date range, right?

**Comment by DataDecay** [comment]
@pvrk you know what, i get what you are saying now, i was thinking from a single record standpoint. However this can be used for an entire range of records. Thank you! i will test this and reply back.

**Comment by pvrk** [comment]
@DataDecay : Thanks. We will keep the issue open for few days, in case you find any more issues. Otherwise, I hope this can be closed.

**Comment by pvrk** [comment]
@DataDecay : A gentle reminder. Were you able to test? Can I close this issue?

**Comment by DataDecay** [comment]
Yes this can be closed as working as intended.
