### ISSUE TITLE
receive_subscription_async.py fails to execute

### ISSUE THREAD

**Issue by yodobrin** [Azure/azure-sdk-for-python#13157]
- **Package Name**: zure-servicebus
- **Package Version**: 0.50.3
- **Operating System**: mac OS / VisualStudio online
- **Python Version**: 3.7.7 / 3.8.3

**Describe the bug**
trying to run the example file receive_subscription_async.py
fails with the following error:

**_Traceback (most recent call last):
  File "topic_rec.py", line 33, in <module>
    loop.run_until_complete(main())
  File "/opt/python/3.8.3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "topic_rec.py", line 20, in main
    async with servicebus_client:
AttributeError: __aexit___**

I have attempted to run this both from my local (mac) and from visual studio online. errors are similar.

**To Reproduce**
1. copy from sdk/servicebus/azure-servicebus/samples/async_samples/receive_subscription_async.py 
2. replace with valid connection string, subscription and topic name
3. try to run the code

**Expected behavior**
code should receive messages from topic without errors and print the content to the console, process should terminate only when shutting down the program by ctrl+c

**Screenshots**

**Additional context**

**Comment by KieranBrantnerMagee** [comment]
Thanks to the thorough detail you provided above, the issue is clear:  the sample you linked is for our latest release, preview version 7.0.0b5.  However, you’re using the last non-preview release, 0.50.3, which is what pip would give you unless you provided --pre.

There are some relevant links at the top of [our readme](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/servicebus/azure-servicebus) concerning this version documentation split, for your convenience you can find the 0.50.3 samples [here](https://github.com/Azure/azure-sdk-for-python/tree/servicebus_v0.50.3/sdk/servicebus/azure-servicebus/samples).

Feel free to shout if this doesn't fully address the problem, or if any further questions.

**Comment by yodobrin** [comment]
Thank you, indeed after testing with latest, the code works as expected.
