### ISSUE TITLE
msrest.exceptions.ClientRequestError: Error occurred in request., InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.

### ISSUE THREAD

**Issue by arpitkath** [Azure/azure-sdk-for-python#13443]
- **azure-mgmt-alertsmanagement**: 
- **azure-mgmt-alertsmanagement==0.1.0
msrest==0.6.18
msrestazure==0.6.4**: 
- **Mac**:
- **python 3.7**: 

**Getting the below stack trace **
```Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/msrest/pipeline/requests.py", line 72, in send
    return self.next.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/msrest/pipeline/requests.py", line 137, in send
    return self.next.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/msrest/pipeline/requests.py", line 193, in send
    self.driver.send(request.http_request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/msrest/universal_http/requests.py", line 333, in send
    return super(RequestsHTTPSender, self).send(request, **requests_kwargs)
  File "/usr/local/lib/python3.8/site-packages/msrest/universal_http/requests.py", line 139, in send
    response = session.request(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 318, in prepare
    self.prepare_auth(auth, url)
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 549, in prepare_auth
    r = auth(self)
  File "/usr/local/lib/python3.8/site-packages/requests_oauthlib/oauth2_auth.py", line 33, in __call__
    raise InsecureTransportError()
oauthlib.oauth2.rfc6749.errors.InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "azure_auth.py", line 21, in <module>
    for alert in client.alerts.get_all():
  File "/usr/local/lib/python3.8/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/usr/local/lib/python3.8/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/usr/local/lib/python3.8/site-packages/azure/mgmt/alertsmanagement/operations/alerts_operations.py", line 195, in internal_paging
    response = self._client.send(request, stream=False, **operation_config)
  File "/usr/local/lib/python3.8/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/msrest/pipeline/requests.py", line 94, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "/usr/local/lib/python3.8/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/usr/local/lib/python3.8/site-packages/msrest/pipeline/requests.py", line 72, in send
    return self.next.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/msrest/pipeline/requests.py", line 137, in send
    return self.next.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/msrest/pipeline/requests.py", line 193, in send
    self.driver.send(request.http_request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/msrest/universal_http/requests.py", line 333, in send
    return super(RequestsHTTPSender, self).send(request, **requests_kwargs)
  File "/usr/local/lib/python3.8/site-packages/msrest/universal_http/requests.py", line 139, in send
    response = session.request(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 318, in prepare
    self.prepare_auth(auth, url)
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 549, in prepare_auth
    r = auth(self)
  File "/usr/local/lib/python3.8/site-packages/requests_oauthlib/oauth2_auth.py", line 33, in __call__
    raise InsecureTransportError()
msrest.exceptions.ClientRequestError: Error occurred in request., InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.
```

**Code To Reproduce**
```
cred = dict with values of tenant id, client id, client secret and subscription

credentials = ServicePrincipalCredentials(tenant=cred['tenant_id'], client_id=cred['client_id'], secret=cred['secret'])

client = AlertsManagementClient(
    credentials,
    cred['subs']
)
 
for alert in client.alerts.get_all():
    print((alert.name))
```

**Additional context**
Trying to get all active alerts in a subscription using python SDK.

**Comment by changlong-liu** [comment]
I @arpitkath ,

Is this a duplicated case with https://github.com/Azure/azure-sdk-for-python/issues/13478?
I see you have set OAUTHLIB_INSECURE_TRANSPORT as 1,  but azure client requires HTTPs.

**Comment by soped** [comment]
I have the same issue on AlertsManagementClient and i'm not setting/changing OAUTHLIB_INSECURE_TRANSPORT anywhere

Win10
python 3.7
azure-mgmt-alertsmanagement==0.1.0
msrest==0.6.10
msrestazure==0.6.2
updated to:
msrest==0.6.18
msrestazure==0.6.4:
and still the same error


`credentials = ServicePrincipalCredentials(
        client_id=APPLICATION_ID,
        secret=APPLICATION_SECRET,
        tenant=TENANT_ID
    )

client = AlertsManagementClient(credentials=credentials, subscription_id=SUBSCRIPTION_ID)
alerts = client.alerts.get_all()
for alert in alerts:
    print(alert.name)
`

Stacktrace:
`Traceback (most recent call last):
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\msrest\pipeline\requests.py", line 72, in send
    return self.next.send(request, **kwargs)
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\msrest\pipeline\requests.py", line 137, in send
    return self.next.send(request, **kwargs)
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\msrest\pipeline\__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\msrest\pipeline\requests.py", line 193, in send
    self.driver.send(request.http_request, **kwargs)
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\msrest\universal_http\requests.py", line 333, in send
    return super(RequestsHTTPSender, self).send(request, **requests_kwargs)
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\msrest\universal_http\requests.py", line 142, in send
    **kwargs)
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\requests\sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\requests\sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\requests\models.py", line 317, in prepare
    self.prepare_auth(auth, url)
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\requests\models.py", line 548, in prepare_auth
    r = auth(self)
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\requests_oauthlib\oauth2_auth.py", line 33, in __call__
    raise InsecureTransportError()
oauthlib.oauth2.rfc6749.errors.InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Dev/Python/Microsoft/Azure-pySDK/AlertsManagement/alerts-management.py", line 33, in <module>
    for alert in alerts:
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\msrest\paging.py", line 143, in __next__
    self.advance_page()
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\msrest\paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\azure\mgmt\alertsmanagement\operations\alerts_operations.py", line 195, in internal_paging
    response = self._client.send(request, stream=False, **operation_config)
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\msrest\service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\msrest\pipeline\__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\msrest\pipeline\__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\msrest\pipeline\requests.py", line 94, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\msrest\exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\msrest\pipeline\requests.py", line 72, in send
    return self.next.send(request, **kwargs)
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\msrest\pipeline\requests.py", line 137, in send
    return self.next.send(request, **kwargs)
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\msrest\pipeline\__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\msrest\pipeline\requests.py", line 193, in send
    self.driver.send(request.http_request, **kwargs)
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\msrest\universal_http\requests.py", line 333, in send
    return super(RequestsHTTPSender, self).send(request, **requests_kwargs)
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\msrest\universal_http\requests.py", line 142, in send
    **kwargs)
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\requests\sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\requests\sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\requests\models.py", line 317, in prepare
    self.prepare_auth(auth, url)
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\requests\models.py", line 548, in prepare_auth
    r = auth(self)
  File "C:\Dev\Python\Microsoft\Azure-pySDK\venv\lib\site-packages\requests_oauthlib\oauth2_auth.py", line 33, in __call__
    raise InsecureTransportError()
msrest.exceptions.ClientRequestError: Error occurred in request., InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.`

**Comment by changlong-liu** [comment]
Hi @soped @arpitkath , would you try the new alertsmanagement package here: https://pypi.org/project/azure-mgmt-alertsmanagement/0.2.0rc2/
