### ISSUE TITLE
SDK using localhost instead of actual server

### ISSUE THREAD

**Issue by arpitkath** [Azure/azure-sdk-for-python#13478]
- **azure-mgmt-alertsmanagement:**: 
- **azure-mgmt-alertsmanagement==0.1.0
msrest==0.6.18
msrestazure==0.6.4:**: 
- **MacOS**:
- **Python 3.7**: 

**HTTP connection using localhost instead of actual server**
Getting the below exception when trying to use azure SDK.
```
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /subscriptions/<subscription>/providers/Microsoft.AlertsManagement/alerts?api-version=2018-05-05 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10b028340>: Failed to establish a new connection: [Errno 61] Connection refused'))

```

Full stack stace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10b028340>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 754, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 754, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 754, in urlopen
    return self.urlopen(
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /subscriptions/<subscription>/providers/Microsoft.AlertsManagement/alerts?api-version=2018-05-05 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10b028340>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

**To Reproduce**
```
from azure.common.credentials import ServicePrincipalCredentials
from azure.mgmt.alertsmanagement import AlertsManagementClient


# Somewhere in webapp_example.py, before the app.run for example
import os 
os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'

credentials = ServicePrincipalCredentials(tenant=cred['tenant_id'], client_id=cred['client_id'], secret=cred['secret'])

client = AlertsManagementClient(
    credentials,
    cred['subs']
)
 
for alert in client.alerts.get_all():
    print((alert.name))
```

**Comment by changlong-liu** [comment]
Hi @arpitkath , I don't reproduce localhost problem in my side. 
The SDK use 'https://management.azure.com' as the default visit url: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/_configuration.py#L37

Would check your domain system, or is there any firewall between your computer and the internet?

**Comment by changlong-liu** [comment]
And why do  you need this? 
~~~
import os 
os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'
~~~

HTTPs is requried for azure management client.
