### ISSUE TITLE
Failed to upload any CSV file greater than 9MB

### ISSUE THREAD

**Issue by imdaslayer** [Azure/azure-sdk-for-python#13878]
- **Package Name**: Azure Blob storage
- **Package Version**: Azure Blob storage v12.5.0 
- **Operating System**:Windows 10
- **Python Version**: 3.7

**Describe the bug**

it failed to upload any csv have a size greater than 9MB.
any CSV less than 9MB works perfect

```
with open(upload_file_path, "rb") as data:
    blob_client.upload_blob(data,overwrite=True)
```

**To Reproduce**
1. upload any csv greater than 9MB

**Expected behavior**
expect to upload successfully

**Screenshots**
```
Traceback (most recent call last):

  File "C:\untitled0.py", line 49, in <module>
    blob_client.upload_blob(data,overwrite=True)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\tracing\decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\storage\blob\_blob_client.py", line 539, in upload_blob
    return upload_block_blob(**options)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\storage\blob\_upload_helpers.py", line 106, in upload_block_blob
    **kwargs)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\storage\blob\_generated\operations\_block_blob_operations.py", line 217, in upload
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\policies\_redirect.py", line 157, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\storage\blob\_shared\policies.py", line 515, in send
    raise err

  File "C:\SDK\Anaconda3\lib\site-packages\azure\storage\blob\_shared\policies.py", line 489, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\storage\blob\_shared\policies.py", line 290, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 103, in send
    self._sender.send(request.http_request, **request.context.options),

  File "C:\SDK\Anaconda3\lib\site-packages\azure\storage\blob\_shared\base_client.py", line 319, in send
    return self._transport.send(request, **kwargs)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\transport\_requests_basic.py", line 284, in send
    raise error

ServiceResponseError: ('Connection aborted.', timeout('The write operation timed out'))

```
**Additional context**

**Comment by tasherif-msft** [comment]
Hi @imdaslayer, I was not able to reproduce this issue on my end (experimented with 11MB and 600MB CSV files). Would you be able to provide me with logs during the attempt of this operation?

Thank you :)

**Comment by imdaslayer** [comment]
hi @tasherif-msft  what logs do you need?

**Comment by imdaslayer** [comment]
this is what i got in return

`Traceback (most recent call last):

  File "C:\upload.py", line 197, in UploadToBlob
    blob_client.upload_blob(data,overwrite=True)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\tracing\decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\storage\blob\_blob_client.py", line 539, in upload_blob
    return upload_block_blob(**options)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\storage\blob\_upload_helpers.py", line 106, in upload_block_blob
    **kwargs)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\storage\blob\_generated\operations\_block_blob_operations.py", line 217, in upload
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\policies\_redirect.py", line 157, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\storage\blob\_shared\policies.py", line 515, in send
    raise err

  File "C:\SDK\Anaconda3\lib\site-packages\azure\storage\blob\_shared\policies.py", line 489, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\storage\blob\_shared\policies.py", line 290, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py", line 103, in send
    self._sender.send(request.http_request, **request.context.options),

  File "C:\SDK\Anaconda3\lib\site-packages\azure\storage\blob\_shared\base_client.py", line 319, in send
    return self._transport.send(request, **kwargs)

  File "C:\SDK\Anaconda3\lib\site-packages\azure\core\pipeline\transport\_requests_basic.py", line 284, in send
    raise error

ServiceRequestError: The operation did not complete (write) (_ssl.c:2408)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\upload.py", line 285, in <module>
    main()

  File "C:\upload.py", line 274, in main
    UploadToBlob(AZURE_STORAGE_CONNECTION_STRING,fileName)

  File "C:\upload.py", line 209, in UploadToBlob
    e=e+ " toblob error"

TypeError: unsupported operand type(s) for +: 'ServiceRequestError' and 'str'`



**below are my codes**

`def UploadToBlob(connect_str,fileName):
    try:
        # Create the BlockBlockService that is used to call the Blob service for the storage account
        print("connecting to blob, please wait")
        blob_service_client = BlobServiceClient.from_connection_string(connect_str)
        print("connection to blob established")
        # define container name
        container_name ="rawdata"
        print(container_name)
        # block_blob_service.create_container(container_name)


        local_path = r'C:\datafile'
        print(fileName)

        full_path_to_file =os.path.join(local_path, fileName)

        # Write text to the file.

        print("Temp file = " + full_path_to_file)
        print("\nUploading to Blob storage as blob" + fileName)

        # Upload the created file, use local_file_name for the blob name

        blob_client = blob_service_client.get_blob_client(container=container_name, blob=fileName)

        print("\nUploading to Azure Storage as blob:\n\t" + fileName)
        
        #Upload the created file
        with open(full_path_to_file, "rb") as data:
            blob_client.upload_blob(data,overwrite=True)
            
        print("\nUpload completed:\n\t" + fileName)



    except Exception as e:
        e=e+ " toblob error"
        recordlogs(e)`

**Comment by xiafu-msft** [comment]
Hi @imdaslayer

I will try to reproduce it tomorrow and get back to you!

**Comment by imdaslayer** [comment]
hi @xiafu-msft 
can you reproduce it on your side?

**Comment by xiafu-msft** [comment]
Hi @imdaslayer 

Sorry I forgot to update the issue, I tried to reproduce while I wasn't able to... Did you get this figured out?

**Comment by imdaslayer** [comment]
@xiafu-msft no, issue still here, no idea why this happen

**Comment by tasherif-msft** [comment]
Hi @imdaslayer, is the 9MB always the same exact 9MB failure (this might just be a memory issue)? a workaround to this would be using smaller chunks for the upload.

**Comment by erfannariman** [comment]
We are having the same issue which only occurs on of our colleagues windows laptop. Also sometimes the error is the timeout, other times:

```
 The operation did not complete (write) (_ssl.c:2317)
 ```

**Comment by daberlin** [comment]
Must be a Windows isssue.
The same script with the same ~120MiB JSON file works perfectly on Linux, but runs into these errors on Windows:

- azure.core.exceptions.ServiceRequestError: The operation did not complete (write) (_ssl.c:2393)
or
- azure.core.exceptions.ServiceResponseError: ('Connection aborted.', TimeoutError('The write operation timed out'))
