### ISSUE TITLE
ServicePrincipalCredentials' object has no attribute 'get_token'

### ISSUE THREAD

**Issue by kaimast** [Azure/azure-sdk-for-python#14059]
I'm running the following code (derived from the [examples](https://github.com/Azure-Samples/virtual-machines-python-manage/blob/master/example.py)).

```python
import os

from azure.common.credentials import ServicePrincipalCredentials
from azure.mgmt.compute import ComputeManagementClient

def get_credentials():
    subscription_id = os.environ['AZURE_SUBSCRIPTION_ID']
    credentials = ServicePrincipalCredentials(
        client_id=os.environ['AZURE_CLIENT_ID'],
        secret=os.environ['AZURE_CLIENT_SECRET'],
        tenant=os.environ['AZURE_TENANT_ID']
    )
    return credentials, subscription_id

credentials, subscription_id = get_credentials()
compute_client = ComputeManagementClient(credentials, subscription_id)


print('\nList VMs in subscription')
for vm in compute_client.virtual_machines.list_all():
    print("\tVM: {}".format(vm.name))
```

However I get the following error. ([and others seem too](https://stackoverflow.com/questions/64063850/azure-python-sdk-serviceprincipalcredentials-object-has-no-attribute-get-to) )

```
Traceback (most recent call last):
  File "./azure_generate_config.py", line 22, in <module>
    for vm in compute_client.virtual_machines.list_all():
  File "/home/kai/.local/lib/python3.8/site-packages/azure/core/paging.py", line 122, in __next__
    return next(self._page_iterator)
  File "/home/kai/.local/lib/python3.8/site-packages/azure/core/paging.py", line 74, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/home/kai/.local/lib/python3.8/site-packages/azure/mgmt/compute/v2020_06_01/operations/_virtual_machines_operations.py", line 1115, in get_next
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/home/kai/.local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/home/kai/.local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/kai/.local/lib/python3.8/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/home/kai/.local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/kai/.local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/kai/.local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/home/kai/.local/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 157, in send
    response = self.next.send(request)
  File "/home/kai/.local/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry.py", line 436, in send
    response = self.next.send(request)
  File "/home/kai/.local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
    _await_result(self._policy.on_request, request)
  File "/home/kai/.local/lib/python3.8/site-packages/azure/core/pipeline/_tools.py", line 29, in await_result
    result = func(*args, **kwargs)
  File "/home/kai/.local/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 93, in on_request
    self._token = self._credential.get_token(*self._scopes)
AttributeError: 'ServicePrincipalCredentials' object has no attribute 'get_token'
```
Any idea what am I doing wrong? Are the examples outdated?

**Comment by changlong-liu** [comment]
Hi @kaimast ,

Are you using the latest azure-mgmt-compute package?

The sample for latest package can be found here: https://github.com/Azure-Samples/azure-samples-python-management/tree/master/samples/compute

And here is a migration guide for using the latest sdk: https://github.com/Azure/azure-sdk-for-python/blob/master/doc/sphinx/python_mgmt_migration_guide.rst

**Comment by 3ttp** [comment]
?? ??????? 29 ??????? 2020 ?? 5:31 ?? ??? changlong-liu <notifications@github.com>:Hi @kaimast ,Are you using the latest azure-mgmt-compute package?The sample for latest package can be found here: https://github.com/Azure-Samples/azure-samples-python-management/tree/master/samples/computeAnd here is a migration guide for using the latest sdk: https://github.com/Azure/azure-sdk-for-python/blob/master/doc/sphinx/python_mgmt_migration_guide.rst?You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by kaimast** [comment]
Thank you! That sample works indeed :)
