### ISSUE TITLE
PipelineRun.wait_for_completion(show_output=True) raises UnicodeEncodeError

### ISSUE THREAD

**Issue by gison93** [Azure/azure-sdk-for-python#14139]
- **Package Name**: azureml-core
- **Package Version**: 1.0.62
- **Operating System**: vs2017-win2016
- **Python Version**: 3.6.8 x64

**Describe the bug**
Calling wait_for_completion for a PipelineRun object with show_output=True raise error:

```
UnicodeEncodeError: 'charmap' codec can't encode character '\ufffd' in position 71: character maps to <undefined>
```

Full traceback:

```
Traceback (most recent call last):
  File "build_pipeline.py", line 230, in <module>
    pipe_exp.wait_for_completion()
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\azureml\pipeline\core\run.py", line 271, in wait_for_completion
    raise_on_error=raise_on_error)
##[error]Cmd.exe exited with code '1'.
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\azureml\pipeline\core\run.py", line 679, in wait_for_completion
    raise_on_error=raise_on_error)
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\azureml\pipeline\core\run.py", line 738, in _stream_run_output
    num_printed_lines = incremental_print(content, num_printed_lines)
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\azureml\pipeline\core\run.py", line 706, in incremental_print
    print(line)
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ufffd' in position 71: character maps to <undefined>
```

Looking at the line in the logs that causes the issue I find:
```
>>>   YYYY/MM/DD HH:mm:SS logger.go:297: [doTurnOffAzsecpack] output:● mdsd.service
```

I suspect that ● is not encoded properly into tab when printed on the console.

**Expected behavior**
Successful experiment without error due to encoding.

**Comment by diondrapeck** [comment]
Hi @amitsethitx - there is not yet a resolution for this. While we are working to fix it, please set the `show_output` param to `True` in order to avoid this error.

**Comment by diondrapeck** [comment]
This issue has been resolved.

**Comment by swatig007** [comment]
closing since this issue is resolved
