### ISSUE TITLE
[AppConfig] Unhandled exception when connection string secret has incorrect padding

### ISSUE THREAD

**Issue by avanigupta** [Azure/azure-sdk-for-python#14140]
- **Package Name**: azure-appconfiguration
- **Package Version**: 1.1.0
- **Operating System**: Windows 10
- **Python Version**: Python 3.7.4

**Describe the bug**
If the "Secret" segment of a connection string has less or more number of characters, it cannot be base 64 decoded.
If this invalid connection string is used to create AzureAppConfigurationClient, the application fails with UnexpectedError before sending a request to App Configuration. According to the official [documentation](https://docs.python.org/3/library/base64.html#base64.b64decode), this exception can be handled for providing a better error message to users.

**To Reproduce**
Use Azure CLI (2.12.0 or later) to run any appconfig data operation with connection string argument. For example, run this command without any changes:

`az appconfig kv show --key TestKey --connection-string Endpoint=testing.io;Id=xyz;Secret=abc
`

UnexpectedError: The command failed with an unexpected error. Here is the traceback:
Incorrect padding
Traceback (most recent call last):
  File "D:\Code\AppConfig\azure-cli\env\lib\site-packages\knack\cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "d:\code\appconfig\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 654, in execute
    raise ex
  File "d:\code\appconfig\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "d:\code\appconfig\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "D:\Code\AppConfig\azure-cli\env\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "d:\code\appconfig\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "d:\code\appconfig\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "d:\code\appconfig\azure-cli\src\azure-cli-core\azure\cli\core\commands\arm.py", line 756, in handler
    show_exception_handler(ex)
  File "d:\code\appconfig\azure-cli\src\azure-cli-core\azure\cli\core\commands\arm.py", line 772, in show_exception_handler
    raise ex
  File "d:\code\appconfig\azure-cli\src\azure-cli-core\azure\cli\core\commands\arm.py", line 754, in handler
    return getter(**args)
  File "d:\code\appconfig\azure-cli\src\azure-cli\azure\cli\command_modules\appconfig\keyvalue.py", line 609, in show_key
    key_value = azconfig_client.get_configuration_setting(key=key, label=label, accept_datetime=datetime)
  File "D:\Code\AppConfig\azure-cli\env\lib\site-packages\azure\core\tracing\decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "D:\Code\AppConfig\azure-cli\env\lib\site-packages\azure\appconfiguration\_azure_appconfiguration_client.py", line 259, in get_configuration_setting
    **kwargs
  File "D:\Code\AppConfig\azure-cli\env\lib\site-packages\azure\appconfiguration\_generated\operations\_azure_app_configuration_operations.py", line 367, in get_key_value
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "D:\Code\AppConfig\azure-cli\env\lib\site-packages\azure\core\pipeline\_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "D:\Code\AppConfig\azure-cli\env\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "D:\Code\AppConfig\azure-cli\env\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "D:\Code\AppConfig\azure-cli\env\lib\site-packages\azure\appconfiguration\_azure_appconfiguration_requests.py", line 75, in send
    self._signed_request(request)
  File "D:\Code\AppConfig\azure-cli\env\lib\site-packages\azure\appconfiguration\_azure_appconfiguration_requests.py", line 53, in _signed_request
    decoded_secret = base64.b64decode(self._credentials.secret)
  File "C:\Users\avgupta\AppData\Local\Programs\Python\Python37\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

**Expected behavior**
Users may inadvertently copy paste the connection string with the last character missing. It would be useful to get an error message indicating that the connection string is invalid.

**Comment by xiangyan99** [comment]
Hi @avanigupta 

We made a fix in https://github.com/Azure/azure-sdk-for-python/pull/14145. Could you help to take a look to see if this is what you expected?

Thanks.

**Comment by avanigupta** [comment]
Hi @xiangyan99, thanks for the quick response! LGTM.

**Comment by xiangyan99** [comment]
Fixed. Will be available in next release.
