### ISSUE TITLE
[ServiceBus] Backfill async test_sb_client

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#14204]
**Is your feature request related to a problem? Please describe.**
Currently in servicebus tests, there is a file, test_sb_client.py  There was however no async version when track2 was created, and it has only recently begun being populated.  This should likely be back-filled with the missing sync tests.

**Describe the solution you'd like**
Pretty much a 1:1 copy of the existing sync tests.  HOWEVER.  Two major callouts:
1. If any tests seem to duplicate functionality or can be combined, take that liberty.  This is to the point of...
2. We are becoming more and more mindful of how long the livetest suite is taking to run.  If the test is only a second/few seconds with a cached resource, that's A-OK; but multi-second sleeps, tests approaching minute+, start to get leery, so when porting over, make sure things stay brief and if they're not, let's identify that. (don't have to fix all of them, but let's know what we're getting into and not dramatically increase our net runtime)

**Describe alternatives you've considered**
No real alternative here.  Test gaps are test gaps, let's get the spackle.

**Additional context**
Reach out to @KieranBrantnerMagee or @yunhaoling for information on how to run these tests.  An azure subscription will be helpful, but in a worst case I can proofread the prospective change and smoketest it in my env.

**Comment by swathipil** [comment]
**Create async tests to mirror the following sync tests**

**Existing async tests that mirror sync tests**

* test_async_sb_client_close_spawned_handlers
* test_client_sas_credential_async
* test_sb_client_bad_entity_async

**Comment by swathipil** [comment]
**Bug found with credential when authenticating and sending messages with ServiceBusSender. Issue created:** 

Following test failing:
- test_sb_client_incorrect_queue_conn_str
```python
    @pytest.mark.liveTest
    @pytest.mark.live_test_only
    @CachedResourceGroupPreparer(name_prefix='servicebustest')
    @CachedServiceBusNamespacePreparer(name_prefix='servicebustest')
    @ServiceBusNamespaceAuthorizationRulePreparer(name_prefix='servicebustest')
    @ServiceBusQueuePreparer(name_prefix='servicebustest_qone', parameter_name='wrong_queue', dead_lettering_on_message_expiration=True)
    @ServiceBusQueuePreparer(name_prefix='servicebustest_qtwo', dead_lettering_on_message_expiration=True)
    @ServiceBusQueueAuthorizationRulePreparer(name_prefix='servicebustest_qtwo')
    async def test_sb_client_incorrect_queue_conn_str_async(self, servicebus_queue_authorization_rule_connection_string, servicebus_queue, wrong_queue, **kwargs):
        
        client = ServiceBusClient.from_connection_string(servicebus_queue_authorization_rule_connection_string)
        async with client:
            # Validate that the wrong queue with the right credentials fails.
            with pytest.raises(ValueError):
                async with client.get_queue_sender(wrong_queue.name) as sender:
                    await sender.send_messages(ServiceBusMessage("test"))

            # But that the correct one works.
            async with client.get_queue_sender(servicebus_queue.name) as sender:
                await sender.send_messages(ServiceBusMessage("test")) 

            # Now do the same but with direct connstr initialization.
            with pytest.raises(ValueError):
                async with ServiceBusSender._from_connection_string(
                    servicebus_queue_authorization_rule_connection_string,
                    queue_name=wrong_queue.name,
                ) as sender:
                        await sender.send_messages(ServiceBusMessage("test"))

            async with ServiceBusSender._from_connection_string(
                servicebus_queue_authorization_rule_connection_string,
                queue_name=servicebus_queue.name,
            ) as sender:
                await sender.send_messages(ServiceBusMessage("test"))
```

Error log:
```
    @pytest.mark.liveTest
    @pytest.mark.live_test_only
    @CachedResourceGroupPreparer(name_prefix='servicebustest')
    @CachedServiceBusNamespacePreparer(name_prefix='servicebustest')
    @ServiceBusNamespaceAuthorizationRulePreparer(name_prefix='servicebustest')
    @ServiceBusQueuePreparer(name_prefix='servicebustest_qone', parameter_name='wrong_queue', dead_lettering_on_message_expiration=True)
    @ServiceBusQueuePreparer(name_prefix='servicebustest_qtwo', dead_lettering_on_message_expiration=True)
    @ServiceBusQueueAuthorizationRulePreparer(name_prefix='servicebustest_qtwo')
    async def test_sb_client_incorrect_queue_conn_str_async(self, servicebus_queue_authorization_rule_connection_string, servicebus_queue, wrong_queue, **kwargs):
    
        client = ServiceBusClient.from_connection_string(servicebus_queue_authorization_rule_connection_string)
        async with client:
            # Validate that the wrong queue with the right credentials fails.
            with pytest.raises(ValueError):
                async with client.get_queue_sender(wrong_queue.name) as sender:
                    await sender.send_messages(ServiceBusMessage("test"))
    
            # But that the correct one works.
            async with client.get_queue_sender(servicebus_queue.name) as sender:
                await sender.send_messages(ServiceBusMessage("test"))
    
            # Now do the same but with direct connstr initialization.
            with pytest.raises(ValueError):
                async with ServiceBusSender._from_connection_string(
                    servicebus_queue_authorization_rule_connection_string,
                    queue_name=wrong_queue.name,
                ) as sender:
                        await sender.send_messages(ServiceBusMessage("test"))

            async with ServiceBusSender._from_connection_string(
                servicebus_queue_authorization_rule_connection_string,
>               queue_name=servicebus_queue.name,
            ) as sender:

async_tests\test_sb_client_async.py:166:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
..\azure\servicebus\aio\_base_handler_async.py:131: in __aenter__
    await self._open_with_retry()
..\azure\servicebus\aio\_base_handler_async.py:332: in _open_with_retry
    return await self._do_retryable_operation(self._open)
..\azure\servicebus\aio\_base_handler_async.py:212: in _do_retryable_operation
    last_exception = await self._handle_exception(exception)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <azure.servicebus.aio._servicebus_sender_async.ServiceBusSender object at 0x000001E65302D390>, exception = ValueError('get_token must be a coroutine function')

    async def _handle_exception(self, exception):
        # pylint: disable=protected-access
        error = _create_servicebus_exception(_LOGGER, exception)

        try:
            # If SessionLockLostError or ServiceBusConnectionError happen when a session receiver is running,
            # the receiver should no longer be used and should create a new session receiver
            # instance to receive from session. There are pitfalls WRT both next session IDs,
            # and the diversity of session failure modes, that motivates us to disallow this.
            if (
                self._session
                and self._running
                and isinstance(error, (SessionLockLostError, ServiceBusConnectionError))
            ):
                self._session._lock_lost = True
                await self._close_handler()
                raise error
        except AttributeError:
            pass

        if error._shutdown_handler:
            await self._close_handler()
        if not error._retryable:
>           raise error
E           azure.servicebus.exceptions.ServiceBusError: Handler failed: get_token must be a coroutine function.

..\azure\servicebus\aio\_base_handler_async.py:160: ServiceBusError
...
ERROR    azure.servicebus.aio._base_handler_async:exceptions.py:172 Unexpected error occurred (ValueError('get_token must be a coroutine function')). Handler shutting down.   
Traceback (most recent call last):
  File "C:\Users\swathip\Documents\forks\azure-sdk-for-python\sdk\servicebus\azure-servicebus\azure\servicebus\aio\_base_handler_async.py", line 208, in _do_retryable_operation
  File "C:\Users\swathip\Documents\forks\azure-sdk-for-python\sdk\servicebus\azure-servicebus\azure\servicebus\aio\_servicebus_sender_async.py", line 158, in _open
    auth = None if self._connection else (await create_authentication(self))
  File "C:\Users\swathip\Documents\forks\azure-sdk-for-python\sdk\servicebus\azure-servicebus\azure\servicebus\aio\_async_utils.py", line 55, in create_authentication
    transport_type=client._config.transport_type,
  File "c:\users\swathip\documents\env37\lib\site-packages\uamqp\authentication\cbs_auth_async.py", line 268, in __init__
    is_coroutine(get_token)
  File "c:\users\swathip\documents\env37\lib\site-packages\uamqp\authentication\cbs_auth_async.py", line 33, in is_coroutine
    raise ValueError("get_token must be a coroutine function")
ValueError: get_token must be a coroutine function
```

**Comment by swathipil** [comment]
* add test `test_sb_client_incorrect_queue_conn_str` after fixing issue #16031 in separate PR
* completed all tests for this issue
