### ISSUE TITLE
backup_protectable_items_operations: Input provided for the call is invalid

### ISSUE THREAD

**Issue by ecgg** [Azure/azure-sdk-for-python#1422]
**Version info**
```
pip3 freeze:
azure-mgmt-recoveryservicesbackup==0.1.1
msrest==0.4.14
msrestazure==0.4.13
```
**Issue**

Following the test case [here](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt/tests/recoveryservicesbackup_testcase.py) I do the following.

The backup vault is in another resource group ( config['Backup']['ResourceGroup'] ) than the VM. I can add the VM to backups via Azure Portal.
 

```
container_name = "iaasvmcontainer;" + "iaasvmcontainerv2;" + group + ";" + vm_name
logging.info('container name: {}'.format(container_name))
pi_name = "vm;iaasvmcontainerv2;" + group + ";" + vm_name
logging.info('protected item name: {}'.format(pi_name))

protectable_items = recovery_client.backup_protectable_items.list(bkp_vlt, config['Backup']['ResourceGroup'], raw=True)
vm_to_bkp  = next(protectable_item for protectable_item in protectable_items if container_name.lower() in protectable_item.name.lower()).properties
```

This results in

```
2017-09-08 16:21:14,488 container name: iaasvmcontainer;iaasvmcontainerv2;ecaz_infra;ecazjump1
2017-09-08 16:21:14,488 protected item name: vm;iaasvmcontainerv2;ecaz_infra;ecazjump1

Input provided for the call is invalid
Please check the required inputs Traceback (most recent call last):
  File "./azure-backup-create.py", line 114, in <module>
    vm_to_bkp  = next(protectable_item for protectable_item in protectable_items if container_name.lower() in protectable_item.name.lower()).properties
  File "./azure-backup-create.py", line 114, in <genexpr>
    vm_to_bkp  = next(protectable_item for protectable_item in protectable_items if container_name.lower() in protectable_item.name.lower()).properties
  File "/home/gabrigr/.local/lib/python3.6/site-packages/msrest/paging.py", line 109, in __next__
    self.advance_page()
  File "/home/gabrigr/.local/lib/python3.6/site-packages/msrest/paging.py", line 95, in advance_page
    self._response = self._get_next(self.next_link)
  File "/home/gabrigr/.local/lib/python3.6/site-packages/azure/mgmt/recoveryservicesbackup/operations/backup_protectable_items_operations.py", line 107, in internal_paging
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: BMSUserErrorInvalidInput
Message: Input provided for the call is invalid
Please check the required inputs
```

**Comment by lmazuel** [comment]
@DheerendraRathor, what do you think?

**Comment by DheerendraRathor** [comment]
@ecgg Can you give me request id for debugging purpose? It is present in raised exception. You can add try except block around list protectable item code and request id is present in exception as `exp.request_id` where exp is an instance of CloudError.

**Comment by ecgg** [comment]
Here's what I did

```
    try:

        protectable_items = recovery_client.backup_protectable_items.list(bkp_vlt, config['Backup']['ResourceGroup'], raw=True)

    # find protectable items and see if one matched request vm
        vm_to_bkp  = next(protectable_item for protectable_item in protectable_items if container_name.lower() in protectable_item.name.lower()).properties

    except CloudError as err:
        logging.info(err.message)
        print(err.request_id)
```

And here's the output:

```
2017-09-08 22:34:49,359 Input provided for the call is invalid
Please check the required inputs
0a3648cf-2d70-472f-a1f2-84f8652ce351
```

**Comment by DheerendraRathor** [comment]
@ecgg 
Please use list call as per following code:
```python
iaasvm_odata_filter = "backupManagementType eq 'AzureIaasVM'"
protectable_items = client.backup_protectable_items.list(bkp_vlt, config['Backup']['ResourceGroup'], filter=iaasvm_odata_filter, raw=True)    
```

These filters were introduced due to recent service side changes. I'll update tests and SDK to incorporate these soon.

**Comment by ecgg** [comment]
That worked - thank you
