### ISSUE TITLE
Server error while create/updating a machine.

### ISSUE THREAD

**Issue by dpedu2** [Azure/azure-sdk-for-python#1431]
I received this traceback and error while creating a machine:

```
Traceback (most recent call last):
  File "xxxxx.py", line 552, in create_or_update
    return self._cluster.cmc.virtual_machines.create_or_update(self.resource_group, self.machine)
  File "/usr/local/lib/python2.7/dist-packages/azure/mgmt/compute/computemanagement.py", line 8114, in create_or_update
    result = client2.get_long_running_operation_status(response.azure_async_operation)
  File "/usr/local/lib/python2.7/dist-packages/azure/mgmt/compute/computemanagement.py", line 2898, in get_long_running_operation_status
    raise error
AzureHttpError: <!DOCTYPE html>
<html>
    <head>
        <title>Runtime Error</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} 
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </style>
    </head>

    <body bgcolor="white">

            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>Runtime Error</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.
            <br><br>

            <b>Details:</b> To enable the details of this specific error message to be viewable on remote machines, please create a &lt;customErrors&gt; tag within a &quot;web.config&quot; configuration file located in the root directory of the current web application. This &lt;customErrors&gt; tag should then have its &quot;mode&quot; attribute set to &quot;Off&quot;.<br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

&lt;!-- Web.Config Configuration File --&gt;

&lt;configuration&gt;
    &lt;system.web&gt;
        &lt;customErrors mode=&quot;Off&quot;/&gt;
    &lt;/system.web&gt;
&lt;/configuration&gt;</pre></code>

                  </td>
               </tr>
            </table>

            <br>

            <b>Notes:</b> The current error page you are seeing can be replaced by a custom error page by modifying the &quot;defaultRedirect&quot; attribute of the application&#39;s &lt;customErrors&gt; configuration tag to point to a custom error page URL.<br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

&lt;!-- Web.Config Configuration File --&gt;

&lt;configuration&gt;
    &lt;system.web&gt;
        &lt;customErrors mode=&quot;RemoteOnly&quot; defaultRedirect=&quot;mycustompage.htm&quot;/&gt;
    &lt;/system.web&gt;
&lt;/configuration&gt;</pre></code>

                  </td>
               </tr>
            </table>

            <br>

    </body>
</html>
```

Now, I'm pretty confident that this is a server-side issue. I'm posting it here in case I'm wrong as Azure's support told me to. The code I'm using to call the Azure SDK hasn't changed in some time; the error is very seldom seen and seems to randomly happen, irrespective of code or parameter changes. I think this supports my idea of a server-side issue - would anyone mind confirming my suspicions? If not, I'm happy to provide more detail.

**Comment by lmazuel** [comment]
Hi @dpedu2 

This version of compute was in preview, and is now deprecated and no longer supported anymore, please update to version at least 1.0.0.

Thanks,

**Comment by dpedu2** [comment]
Sounds like you're familiar with this problem; is there something specific that was changed you can point to?

**Comment by lmazuel** [comment]
I'm not sure I understand your question :(
If your question is about migration information from 0.20.0 to 1.0.0, there is this document which explains how to migrate from 0.20.0 to 0.30.0 (there is more change here than from 0.30.0 to 1.0.0).
https://github.com/Azure/azure-sdk-for-python/wiki/Migrate-from-1.0.x-0.20.0-to-2.0.0-0.30.0

But I would recommend starting with official samples:
https://github.com/Azure-Samples/virtual-machines-python-manage

**Comment by lmazuel** [comment]
Closing this issue for inactivity, and since this preview version of the Python SDK is out of support.
