### ISSUE TITLE
azure-mgmt-iothub

### ISSUE THREAD

**Issue by waytai** [Azure/azure-sdk-for-python#1439]
my platform is ubuntu14.04 and my python is 2.7.6
when I run the example in azure-mgmt-iothub

Traceback (most recent call last):
  File "createiot.py", line 15, in <module>
    'mypassword',      # Your password
  File "/usr/local/lib/python2.7/dist-packages/msrestazure/azure_active_directory.py", line 366, in __init__
    self.set_token()
  File "/usr/local/lib/python2.7/dist-packages/msrestazure/azure_active_directory.py", line 403, in set_token
    raise_with_traceback(AuthenticationError, "", err)
  File "/usr/local/lib/python2.7/dist-packages/msrest/exceptions.py", line 50, in raise_with_traceback
    raise error
msrest.exceptions.AuthenticationError: , InvalidClientIdError: (invalid_request) AADSTS50059: No tenant-identifying information found in either the request or implied by any provided credentials.

**Comment by lmazuel** [comment]
Hi @waytai 

Could you share the code and not only the stacktrace?

Note that the error seems to say that your credentials are not valid for your operation, it's probably not a Python issue but a credential configuration.

**Comment by waytai** [comment]
It's alright now， thank you
