### ISSUE TITLE
BlobService.put_blob needs timeout parameter

### ISSUE THREAD

**Issue by cedricyau** [Azure/azure-sdk-for-python#153]
It seems like sometime my socket connections from a Linux Azure VM to Azure Storage are stalling.  Can we add a timeout parameter to pub_blob like some of the other functions?

Traceback below:

```
Unexpected upload error: <class 'socket.error'>
Traceback (most recent call last):
  File "GetHistory.py", line 81, in getAndUploadHist
    _bs.put_blob('thistory',filename,sz ,x_ms_blob_type='BlockBlob')
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/blobservice.py", line 693, in put_blob
    self._perform_request(request)
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/storageclient.py", line 143, in _perform_request
    resp = self._filter(request)
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/storageclient.py", line 132, in _perform_request_worker
    return self._httpclient.perform_request(request)
  File "/usr/local/lib/python2.7/dist-packages/azure/http/httpclient.py", line 190, in perform_request
    self.send_request_body(connection, request.body)
  File "/usr/local/lib/python2.7/dist-packages/azure/http/httpclient.py", line 173, in send_request_body
    connection.send(request_body)
  File "/usr/lib/python2.7/httplib.py", line 805, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 104] Connection reset by peer
```

**Comment by crwilcox** [comment]
Issue Migrated to https://github.com/Azure/azure-storage-python/issues/17
