### ISSUE TITLE
azure-mgmt-digitaltwins failing basic import

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#15590]
install the package -> import * from azure.mgmt.digitaltwins

```
INFO:root:Importing all modules from namespace [azure.mgmt.digitaltwins] to verify dependency
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vsts/work/1/s/sdk/digitaltwins/azure-mgmt-digitaltwins/.tox/depends/lib/python2.7/site-packages/azure/mgmt/digitaltwins/__init__.py", line 13, in <module>
    from ._azure_digital_twins_management_client import AzureDigitalTwinsManagementClient
  File "/home/vsts/work/1/s/sdk/digitaltwins/azure-mgmt-digitaltwins/.tox/depends/lib/python2.7/site-packages/azure/mgmt/digitaltwins/_azure_digital_twins_management_client.py", line 16, in <module>
    from .operations import DigitalTwinsOperations
  File "/home/vsts/work/1/s/sdk/digitaltwins/azure-mgmt-digitaltwins/.tox/depends/lib/python2.7/site-packages/azure/mgmt/digitaltwins/operations/__init__.py", line 12, in <module>
    from ._digital_twins_operations import DigitalTwinsOperations
  File "/home/vsts/work/1/s/sdk/digitaltwins/azure-mgmt-digitaltwins/.tox/depends/lib/python2.7/site-packages/azure/mgmt/digitaltwins/operations/_digital_twins_operations.py", line 17, in <module>
    from .. import models
  File "/home/vsts/work/1/s/sdk/digitaltwins/azure-mgmt-digitaltwins/.tox/depends/lib/python2.7/site-packages/azure/mgmt/digitaltwins/models/__init__.py", line 30, in <module>
    from ._models import CheckNameRequest
  File "/home/vsts/work/1/s/sdk/digitaltwins/azure-mgmt-digitaltwins/.tox/depends/lib/python2.7/site-packages/azure/mgmt/digitaltwins/models/_models.py", line 88, in <module>
    class DigitalTwinsResource(Model):
  File "/home/vsts/work/1/s/sdk/digitaltwins/azure-mgmt-digitaltwins/.tox/depends/lib/python2.7/site-packages/azure/mgmt/digitaltwins/models/_models.py", line 128, in DigitalTwinsResource
    sku = DigitalTwinsSkuInfo()
NameError: name 'DigitalTwinsSkuInfo' is not defined
```

I will note that while the above error is from the py27 env. The failure occurred on [all platforms.](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=637495&view=results)

**Comment by annatisch** [comment]
Yeah this is a known issue - I believe the SDK in master is T1, and the currently published SDK is the T2 release that's being maintained in this branch:
https://github.com/Azure/azure-sdk-for-python/tree/release/v3/sdk/digitaltwins/azure-mgmt-digitaltwins

I'm not sure what the timeframe is for merging the T2 SDK into master.

**Comment by scbedd** [comment]
Thanks for the heads up Anna! Do you think we could just merge the T2 one into master then? 

The reason I ask, is you're saying that the currently published SDK is the T2 release, so we wouldn't be losing anything right?

All that being said I know there is a plan that the mgmt folks are working off of, and I don't want to mess with that if it incurs additional effort.

**Comment by annatisch** [comment]
Yeah that would be my preference too - I don't like the master is broken. Though I will leave that to @changlong-liu  :)

**Comment by changlong-liu** [comment]
Hi @scbedd , @annatisch ,

The master branch code for digitaltwins is old and there are errors. 
Digitialtwins is currently released as Track1,  so the latest code is in release/v3 branch.

I tend to delete the digitaltwins code in master branch to avoid this confusing. And adding @msyyc  to know this.

**Comment by changlong-liu** [comment]
Closing this issue since new digitaltwins has been released.
CC to @msyyc
