### ISSUE TITLE
Cannot load blobs from mcr.microsoft.com/azure-blob-storage:1.3

### ISSUE THREAD

**Issue by thomasstaltner** [Azure/azure-sdk-for-python#15638]
After installing azure-storage-blob from this (https://pypi.org/project/azure-storage-blob/) website, the following error occurs:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/_download.py", line 366, in _initial_request
    **self._request_options
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/_generated/operations/_blob_operations.py", line 179, in download
    raise models.StorageErrorException(response, self._deserialize)
azure.storage.blob._generated.models._models_py3.StorageErrorException: Operation returned an invalid status 'The value for one of the HTTP headers is not in the correct format.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/project/src/App.py", line 249, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/project/src/App.py", line 236, in main
    await start_ocpp_central_system(module_client)
  File "/opt/project/src/App.py", line 78, in start_ocpp_central_system
    config = blob_storage_conn.load_module_config_from_local_blob()
  File "/opt/project/src/blob_storage_connection.py", line 41, in load_module_config_from_local_blob
    return self.__configs_container_client.download_blob(f'{blob_name}.json').readall()
  File "/usr/local/lib/python3.7/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/_container_client.py", line 997, in download_blob
    return blob_client.download_blob(offset=offset, length=length, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/_blob_client.py", line 674, in download_blob
    return StorageStreamDownloader(**options)
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/_download.py", line 316, in __init__
    self._response = self._initial_request()
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/_download.py", line 403, in _initial_request
    process_storage_error(error)
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/_shared/response_handlers.py", line 147, in process_storage_error
    raise error
azure.core.exceptions.HttpResponseError: The value for one of the HTTP headers is not in the correct format.
RequestId:ad257ddf-b23f-4c62-91fc-a6b769453812
Time:2020-12-03T22:14:53.4286927Z
ErrorCode:InvalidHeaderValue
Error:None
HeaderName:x-ms-version
HeaderValue:2020-02-10
ExceptionDetails:None
ExceptionMessage:The value 2020-02-10 provided for request header x-ms-version is invalid.
StackTrace:Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.InvalidHeaderProtocolException: The value 2020-02-10 provided for request header x-ms-version is invalid.
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.RunVersionCheck() in F:\Storage-XStore\src\XFE\common\Protocols\REST\src\BasicHttpProcessorWithAuthAndAccountContainerBase.cs:line 788
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.ProcessImpl(AsyncIteratorContext`1 async)+MoveNext() in F:\Storage-XStore\src\XFE\common\Protocols\REST\src\BasicHttpProcessorWithAuthAndAccountContainerBase.cs:line 1538
```

Seems like there is an issue with the 'x-ms-version' header.
The steps to load blobs were retrieved from: [here](https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.containerclient?view=azure-python#download-blob-blob--offset-none--length-none----kwargs-)

Following specifications are used:
- Docker running on MacOs
- successfully running mcr.microsoft.com/azure-blob-storage:1.3
- NodeJs already connects to this container using the same connection string as in this case

Code:
```
class BlobStorageConnection:
    ...
    @property
    def __conn_string(self):
        str = f'DefaultEndpointsProtocol=http;BlobEndpoint=http://blobstorageoniotedge:11002/{self.__storage_account_name};AccountName={self.__storage_account_name};AccountKey={self.__storage_account_key};'
        return str

    def __init__(self):
        self.__blob_service_client = BlobServiceClient.from_connection_string(conn_str=self.__conn_string)
        self.__configs_container_client = self.__blob_service_client.get_container_client(self.__config_blob_container)

    def load_module_config_from_local_blob(self, blob_name: str = MODULE_NAME) -> str:
        return self.__configs_container_client.download_blob(f'{blob_name}.json').readall()
```

**Comment by xiafu-msft** [comment]
Hi @thomasstaltner 

Thanks for reaching out. It seems you are using storage emulator, can you try to install blob 12.4.0 using this:
`pip install azure-storage-blob==12.4.0` and see if this works?

Let me know if it doesn't work either.
