### ISSUE TITLE
asynchronous block blob client can't reuse connection to a BlobServiceClient

### ISSUE THREAD

**Issue by scivm** [Azure/azure-sdk-for-python#15773]
- **azure.storage.blob.aio**: 
- **12.6.0**: 
- **Linux**:
- **3.8**: 

**Describe the bug**
Have to create new connection for every request to BlobServiceClient when using the azure.storage.blob.aio.  Would like to download a set of blobs in asynchronous manner with a precreated BlobServiceClient.  The performance for the set is slower then when downloading using the synchronous library because of the overhead required to create the connection.

**To Reproduce**

Example code:
```
MyClass
    def __init__(self):
        self.blob_service_client_async = getBlobServiceClientAsync()

    async def get_models_async_reuse(self, id):
        input = [('type1',id,"i"),('type2',id,"ir"),('type3',id,"ir"),('type4',id,"ir")]
        return await asyncio.gather(*[self.fetch_model_async_reuse(modeltype, bodyId, training_level) for (type,id,training_level) in input])

    async def fetch_model_async_reuse(self, attr, bodyId, training_level):
        async with self.blob_service_client_async:
            container_client = self.blob_service_client_async.get_container_client("modelstorage")
            blob_client = container_client.get_blob_client(f'{attr}-{bodyId}-{training_level}.model')
            try:
                stream = await blob_client.download_blob()
                model_bytes = await stream.readall()
            except ResourceNotFoundError:
                print("No blob found.")
            return model_bytes

def getBlobServiceClientAsync():
    client_id = ""
    client_secret = ""
    tenant_id = ""
    vault_url = ""
    connection_string = getModelStorageConnectionString(client_id, client_secret, tenant_id, vault_url)
    from azure.storage.blob.aio import BlobServiceClient
    return BlobServiceClient.from_connection_string(connection_string)

tic = time.perf_counter()
loop = asyncio.get_event_loop()
models = loop.run_until_complete(MyClass.get_models_async_reuse("xxx"))
loop.close()
toc = time.perf_counter()
print(f"model fetch time async in {toc - tic:0.4f}")
```

```
Traceback (most recent call last):
  File "test3.py", line 131, in <module>
    models = loop.run_until_complete(invoice.get_models_async_reuse("14813"))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "test3.py", line 31, in get_models_async_reuse
    return await asyncio.gather(*[self.fetch_model_async_reuse(modeltype, bodyId, training_level) for (modeltype,bodyId,training_level) in input])
  File "test3.py", line 65, in fetch_model_async_reuse
    stream = await blob_client.download_blob()
  File "/home/mshamber/.local/lib/python3.8/site-packages/azure/core/tracing/decorator_async.py", line 74, in wrapper_use_tracer
    return await func(*args, **kwargs)
  File "/home/mshamber/.local/lib/python3.8/site-packages/azure/storage/blob/aio/_blob_client_async.py", line 361, in download_blob
    await downloader._setup()  # pylint: disable=protected-access
  File "/home/mshamber/.local/lib/python3.8/site-packages/azure/storage/blob/aio/_download_async.py", line 225, in _setup
    self._response = await self._initial_request()
  File "/home/mshamber/.local/lib/python3.8/site-packages/azure/storage/blob/aio/_download_async.py", line 265, in _initial_request
    location_mode, response = await self._clients.blob.download(
  File "/home/mshamber/.local/lib/python3.8/site-packages/azure/storage/blob/_generated/aio/operations_async/_blob_operations_async.py", line 174, in download
    pipeline_response = await self._client._pipeline.run(request, stream=True, **kwargs)
  File "/home/mshamber/.local/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 215, in run
    return await first_node.send(pipeline_request)
  File "/home/mshamber/.local/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/mshamber/.local/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/mshamber/.local/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  [Previous line repeated 5 more times]
  File "/home/mshamber/.local/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect_async.py", line 64, in send
    response = await self.next.send(request)
  File "/home/mshamber/.local/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/mshamber/.local/lib/python3.8/site-packages/azure/storage/blob/_shared/policies_async.py", line 99, in send
    response = await self.next.send(request)
  File "/home/mshamber/.local/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/mshamber/.local/lib/python3.8/site-packages/azure/storage/blob/_shared/policies_async.py", line 56, in send
    response = await self.next.send(request)
  File "/home/mshamber/.local/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/mshamber/.local/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/mshamber/.local/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 116, in send
    await self._sender.send(request.http_request, **request.context.options),
  File "/home/mshamber/.local/lib/python3.8/site-packages/azure/storage/blob/_shared/base_client_async.py", line 173, in send
    return await self._transport.send(request, **kwargs)
  File "/home/mshamber/.local/lib/python3.8/site-packages/azure/storage/blob/_shared/base_client_async.py", line 173, in send
    return await self._transport.send(request, **kwargs)
  File "/home/mshamber/.local/lib/python3.8/site-packages/azure/core/pipeline/transport/_aiohttp.py", line 177, in send
    result = await self.session.request(
AttributeError: 'NoneType' object has no attribute 'request'
```

**Expected behavior**
Ability to share connection in a multi-threaded safe manner.  Asynchronous download should be able to outperform synchronous download for a set of blobs.

**Comment by lmazuel** [comment]
Hi @scivm 
`async with self.blob_service_client_async:` will close the transport layer when you got out of it. As a consequence, calling twice `fetch_model_async_reuse` will make the second call on a closed connection.

You need to execute your entire code inside a `async with self.blob_service_client_async`.

**Comment by scivm** [comment]
I am currently using a long lived BlobServiceClient singleton instance that is reused among different threads for downloading blobs.   So same idea doesn't work with the aio package.  

Based on your feedback, I tried creating a single connection to download 4 blobs worked and functionally it works fine.    

```
    async def get_models_async(self, bodyId):
        blob_service_client_async = getBlobServiceClientAsync(self.blob_session)
        async with blob_service_client_async:
            input = [('model1',bodyId,"i"),('model2',bodyId,"ir"),('model3',bodyId,"ir"),('model4',bodyId,"ir")]
            return await asyncio.gather(*[self.fetch_model_async(blob_service_client_async, modeltype, bodyId, training_level) for (modeltype,bodyId,training_level) in input])
```

There is an issue is that this async download of 4 blobs is slower then sync download.

I noticed the time for connection is 10x higher for aio package

```
    from azure.storage.blob import BlobServiceClient
    tic = time.perf_counter()
    blob_session = requests.session()
    client = BlobServiceClient.from_connection_string(connection_string)
    toc = time.perf_counter()
    print(f"time to create sync connection: {toc - tic:0.4f}")
```
time to create sync connection: 0.0005

```
    tic = time.perf_counter()
    from azure.storage.blob.aio import BlobServiceClient
    client = BlobServiceClient.from_connection_string(connection_string)
    toc = time.perf_counter()
    print(f"time to create async connection: {toc - tic:0.4f}")
```

time to create async connection: 0.0115









Except it was still slower then creating a non AIO connection and  downloading the 4 in a synchronous manner.

**Comment by xiafu-msft** [comment]
Hi @scivm 

If you get a a blobclient using `blob_service_client_async.get_blob_client()` and use `async with blob_client:` then it will not close the connection of blob_service_client and you don't have to initialize multiple blob_service_client.

Let me know if it doesn't help
