### ISSUE TITLE
[Eventgrid] Improve error message when providing wrong authentication

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#15939]
Upon providing wrong key for authentication during publisher client, we get 
```
UnboundLocalError: local variable 'authentication_policy' referenced before assignment on providing wrong credential in the publisher client
```

This message must improve - perhaps start with insisting on providing an AzureKeyCredential?

**Comment by lmazuel** [comment]
Can you paste a full example with the full stacktrace of this?

**Comment by rakshith91** [comment]
> Can you paste a full example with the full stacktrace of this?

```
>>> e  = EventGridPublisherClient("https://rakshith-eg.westus-1.eventgrid.azure.net/api/events", "dsf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\Documents\Workspace\azure-sdk-for-python\envtrace\lib\site-packages\azure\eventgrid\_publisher_client.py", line 75, in __init__
    policies=EventGridPublisherClient._policies(credential, **kwargs),
  File "C:\Users\Administrator\Documents\Workspace\azure-sdk-for-python\envtrace\lib\site-packages\azure\eventgrid\_publisher_client.py", line 82, in _policies
    auth_policy = _get_authentication_policy(credential)
  File "C:\Users\Administrator\Documents\Workspace\azure-sdk-for-python\envtrace\lib\site-packages\azure\eventgrid\_helpers.py", line 87, in _get_authentication_policy
    return authentication_policy
UnboundLocalError: local variable 'authentication_policy' referenced before assignment
```

**Comment by lmazuel** [comment]
That's a bug in this code:
https://github.com/Azure/azure-sdk-for-python/blob/c2dea16a2d3b202dfa46a93b2bfadff44a020287/sdk/eventgrid/azure-eventgrid/azure/eventgrid/_helpers.py#L77-L87

If all `if` are wrong, we reach a return on an undeclared variable.

Correct code:
```python
def _get_authentication_policy(credential):
    if credential is None:
        raise ValueError("Parameter 'self._credential' must not be None.")
    if isinstance(credential, AzureKeyCredential):
        return AzureKeyCredentialPolicy(credential=credential, name=constants.EVENTGRID_KEY_HEADER)
    if isinstance(credential, EventGridSharedAccessSignatureCredential):
        return EventGridSharedAccessSignatureCredentialPolicy(
            credential=credential,
            name=constants.EVENTGRID_TOKEN_HEADER
        )
    raise ValueError("The provided credential should be an instance of EventGridSharedAccessSignatureCredentialPolicy or AzureKeyCredentialPolicy")
```
