### ISSUE TITLE
Error writing to local Blob storage using azure-storage-blob 12.6

### ISSUE THREAD

**Issue by cclague** [Azure/azure-sdk-for-python#15957]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.6
- **Operating System**: Raspbian GNU/Linux 10 (buster)
- **Python Version**: 3.7.3

**Describe the bug**
Get `ErrorCode:InvalidHeaderValue` when attempting to write to local storage using version 12.6. Version 2.1 appears to work correctly.

**To Reproduce**
Using code sample from this project:
```
import os
from azure.storage.blob import BlobClient

BLOB_CONNECTION_STRING = 'DefaultEndpointsProtocol=http;AccountName=<account name>;AccountKey=<account key>;BlobEndpoint=http://127.0.0.1:11002/<account name>;'

container = 'iot-timing-upload'
blob_file_name = 'anon.txt'
full_path='/home/pi/anon.txt'

blob = BlobClient.from_connection_string(conn_str=BLOB_CONNECTION_STRING, container_name=container, blob_name=blob_file_name)

with open(full_path, "rb") as data:
    blob.upload_blob(data)
```

**Error**:
```Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_upload_helpers.py", line 106, in upload_block_blob
    **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 222, in upload
    raise models.StorageErrorException(response, self._deserialize)
azure.storage.blob._generated.models._models_py3.StorageErrorException: Operation returned an invalid status 'The value for one of the HTTP headers is not in the correct format.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testblob12.6.py", line 13, in <module>
    blob.upload_blob(data)
  File "/home/pi/.local/lib/python3.7/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_blob_client.py", line 539, in upload_blob
    return upload_block_blob(**options)
  File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_upload_helpers.py", line 158, in upload_block_blob
    process_storage_error(error)
  File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_shared/response_handlers.py", line 147, in process_storage_error
    raise error
azure.core.exceptions.HttpResponseError: The value for one of the HTTP headers is not in the correct format.
RequestId:fc81ad90-1e8d-4574-8a2e-95b4c9e5e158
Time:2020-12-31T12:27:13.0600996Z
ErrorCode:InvalidHeaderValue
Error:None
HeaderName:x-ms-version
HeaderValue:2020-02-10
ExceptionDetails:None
ExceptionMessage:The value 2020-02-10 provided for request header x-ms-version is invalid.
StackTrace:Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.InvalidHeaderProtocolException: The value 2020-02-10 provided for request header x-ms-version is invalid.
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.RunVersionCheck() in F:\Storage-XStore\src\XFE\common\Protocols\REST\src\BasicHttpProcessorWithAuthAndAccountContainerBase.cs:line 788
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.ProcessImpl(AsyncIteratorContext`1 async)+MoveNext() in F:\Storage-XStore\src\XFE\common\Protocols\REST\src\BasicHttpProcessorWithAuthAndAccountContainerBase.cs:line 1537
```

**Expected behavior**
Upload file to blob

**Additional context**
Works correctly using same connection string with azure-storage-blob 2.1.0

**Comment by asergaz** [comment]
This relates with Microsoft Q&A thread: https://docs.microsoft.com/en-us/answers/questions/212065/index.html

**Comment by xiafu-msft** [comment]
Hi @cclague

There is an workaround: set api_version="2019-12-12" when initiating BlobClient
eg. BlobClient.from_connection_string(your_con_str, your_container_name, your_blob_name, api_version="2019-12-12")

we have customers reporting the similar issue before, and we reached out to another team for help https://github.com/MicrosoftDocs/azure-docs/issues/65265 let me check if there's any updates

**Comment by xiafu-msft** [comment]
Hi @cclague 

Here is what service people responded in https://github.com/MicrosoftDocs/azure-docs/issues/65265
`can you try the version 1.4.0 of "Azure Blob Storage on IoT Edge" module, and let us know if you still have this issue?`

**Comment by kooryliu** [comment]
@xiafu-msft, I'm working with Jetson nano and running on ubuntu18.04.  When I tried to write data to container in the IoT Edge blob, I got the same error as above. Neither workaround doesn't work in my environment. 
1. For changing api_version to '2019-07-07' or anyother date, I got the same ErrorCode:InvalidHeaderValue.
2. For install version 1.4.0 of "Azure Blob Storage on IoT Edge" module, jetson nano is Arm64v8, the latest version is 1.2.0.
Do you have any other workaround to try?

**Comment by kooryliu** [comment]
My problem was solve according this 
https://github.com/pczhao1210/Azure-IoT-Edge-Demo/tree/master/Azure_Storage_Blob_SDK

**Comment by cclague** [comment]
Hi - version 1.4.0 of "Azure Blob Storage on IoT Edge" module works - thank you!
