### ISSUE TITLE
ServiceBus: Async permanent receiver failing due to authorization timeout

### ISSUE THREAD

**Issue by danidelvalle** [Azure/azure-sdk-for-python#16037]
- **Package Name**:  azure-servicebus
- **Package Version**:  7.0.0
- **Operating System**: Linux Debian/Ubuntu
- **Python Version**: 3.7.9
- **uamqp Version**: 1.2.12

**Describe the bug**
An async permanent service bus receiver is failing due to authorization timeout after some hours of operation. 

The below debug logs should indicate that the token refreshing is working:

```
2020-12-24 06:35:36,199 uamqp.authentication.cbs_auth_async [INFO] Token on connection b'SBReceiver-REDACTED' will expire soon - attempting to refresh.
2020-12-24 06:35:36,199 azure.identity.aio._internal.decorators [INFO] ManagedIdentityCredential.get_token succeeded
```

But it is not. After a large amount of token refreshing attempts (at ~50ms intervals), the following exception is thrown, and the connection is closed:

```
2020-12-24 06:45:19,000 azure.servicebus.aio._base_handler_async [ERROR] Unexpected error occurred (TimeoutError('Authorization timeout.')). Handler shutting down.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/servicebus/aio/_base_handler_async.py", line 181, in _do_retryable_operation
    return await operation(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/azure/servicebus/aio/_servicebus_receiver_async.py", line 343, in _receive
    receiving = await amqp_receive_client.do_work_async()
  File "/usr/local/lib/python3.7/site-packages/uamqp/async_ops/client_async.py", line 378, in do_work_async
    if not await self.client_ready_async():
  File "/usr/local/lib/python3.7/site-packages/uamqp/async_ops/client_async.py", line 360, in client_ready_async
    if not await self.auth_complete_async():
  File "/usr/local/lib/python3.7/site-packages/uamqp/async_ops/client_async.py", line 346, in auth_complete_async
    raise TimeoutException("Authorization timeout.")
TimeoutError: Authorization timeout.
```

**To Reproduce**
1. Create an async receiver using DefaultAzureCredential
2. Start an indefinite iteration to create a permanent receiver waiting for messages
3. After some hours of operation, the program will fail due to authorization timeout

**Expected behavior**
Authorization refreshing is managed successfully by the library. 

**Code**
Basic code to reproduce the issue:

```python
from datetime import datetime
from asyncio import get_event_loop, sleep
from azure.identity.aio import DefaultAzureCredential
from azure.servicebus.aio import ServiceBusClient
from azure.servicebus import ServiceBusReceiveMode

import logging

logging.basicConfig(level=logging.DEBUG, format="%(asctime)-15s %(name)s [%(levelname)s] %(message)s")

SB_NAMESPACE_FQDN = "..."
QUEUE_NAME = "..."


async def receive_forever():
    attempt = 0
    while True:
        start = datetime.now()
        try:
            attempt += 1
            logging.info(f"== Starting attempt={attempt}")

            async with DefaultAzureCredential(exclude_environment_credential=True) as credential:
                service_bus_client = ServiceBusClient(SB_NAMESPACE_FQDN, credential, logging_enable=True)
                async with service_bus_client:
                    queue_receiver = service_bus_client.get_queue_receiver(
                        QUEUE_NAME,
                        receive_mode=ServiceBusReceiveMode.RECEIVE_AND_DELETE,
                    )
                    async with queue_receiver:
                        while True:
                            messages = await queue_receiver.receive_messages(max_message_count=1, max_wait_time=30)
                            if messages:
                                logging.debug(f"Received: {messages[0]}")
        except Exception:
            logging.exception(f"== Running for {datetime.now()-start}")
            await sleep(10)


if __name__ == "__main__":
    loop = get_event_loop()
    loop.run_until_complete(receive_forever())
```

Please find attached an reduced output log.

[reduced.log](https://github.com/Azure/azure-sdk-for-python/files/5786745/reduced.log)

**Comment by yunhaoling** [comment]
hey @danidelvalle , thanks for reaching out.

how often does the issue happen on your side -- I'm wondering if this is a transient error due to network or it's always happening after several hours on your side?

**Comment by danidelvalle** [comment]
thanks @yunhaoling

A deeper log analysis seems to reveal a pattern: it's happening each 21 hours and 45 minutes. Notice that there are a pair of exceptions (marked).

```sh
2020-12-12 08:38:37,000 azure.servicebus.aio._base_handler_async [ERROR] Unexpected error occurred (TimeoutError('Authorization timeout.')). Handler shutting down.
2020-12-12 08:38:37,696 root [ERROR] == Running for 21:45:04.776952

2020-12-13 06:24:27,000 azure.servicebus.aio._base_handler_async [ERROR] Unexpected error occurred (TimeoutError('Authorization timeout.')). Handler shutting down.
2020-12-13 06:24:27,730 root [ERROR] == Running for 21:45:40.023172

2020-12-14 04:10:18,000 azure.servicebus.aio._base_handler_async [ERROR] Unexpected error occurred (TimeoutError('Authorization timeout.')). Handler shutting down.
2020-12-14 04:10:18,079 root [ERROR] == Running for 21:45:40.338596

*** 2020-12-15 14:54:06,000 azure.servicebus.aio._base_handler_async [ERROR] Unexpected error occurred (TimeoutError('Authorization timeout.')). Handler shutting down.
*** 2020-12-15 14:54:06,125 root [ERROR] == Running for 21:04:44.669384

2020-12-16 12:39:59,000 azure.servicebus.aio._base_handler_async [ERROR] Unexpected error occurred (TimeoutError('Authorization timeout.')). Handler shutting down.
2020-12-16 12:39:59,723 root [ERROR] == Running for 21:45:43.587637

2020-12-17 10:25:51,000 azure.servicebus.aio._base_handler_async [ERROR] Unexpected error occurred (TimeoutError('Authorization timeout.')). Handler shutting down.
2020-12-17 10:25:51,412 root [ERROR] == Running for 21:45:41.677686

*** 2020-12-19 02:10:18,000 azure.servicebus.aio._base_handler_async [ERROR] Unexpected error occurred (TimeoutError('Authorization timeout.')). Handler shutting down.
*** 2020-12-19 02:10:18,116 root [ERROR] == Running for 22:45:27.377614

2020-12-19 23:56:07,000 azure.servicebus.aio._base_handler_async [ERROR] Unexpected error occurred (TimeoutError('Authorization timeout.')). Handler shutting down.
2020-12-19 23:56:07,102 root [ERROR] == Running for 21:45:38.975030

2020-12-20 21:41:50,000 azure.servicebus.aio._base_handler_async [ERROR] Unexpected error occurred (TimeoutError('Authorization timeout.')). Handler shutting down.
2020-12-20 21:41:50,550 root [ERROR] == Running for 21:45:33.436991

2020-12-21 19:27:36,000 azure.servicebus.aio._base_handler_async [ERROR] Unexpected error occurred (TimeoutError('Authorization timeout.')). Handler shutting down.
2020-12-21 19:27:36,491 root [ERROR] == Running for 21:45:35.931191

2020-12-23 05:04:43,000 azure.servicebus.aio._base_handler_async [ERROR] Unexpected error occurred (TimeoutError('Authorization timeout.')). Handler shutting down.
2020-12-23 05:04:43,942 root [ERROR] == Running for 21:45:14.129917


```

**Comment by yunhaoling** [comment]
@danidelvalle , I'm currently running your code on a linux vm, let's see if I could reproduce the issue.

btw, does this issue happen when you're using a connection string?

**Comment by danidelvalle** [comment]
> btw, does this issue happen when you're using a connection string?

I hadn't tried it as managed identities are the way to go when running on Azure, I'm going to test it just in case it helps to isolate the root cause.

**Comment by yunhaoling** [comment]
hey @danidelvalle , sorry I was unable to produce the issue.
I kicked off a program on a VM which used managed identity for authentication and let it ran for several days but nothing went wrong.

Can you help check if there's any maintenance work in your VM/Networking which run periodically (every 21hour and 45 mins)?
