### ISSUE TITLE
Add gitpython and pygithub to azure-devtools requirements

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#16070]
dataplane code generation using Track2 fail initially because the two packages aren't installed as requirements. These are required to generate code with track2 and fail with the following:

```
Traceback (most recent call last): File "/mnt/c/Users/Administrator/Documents/Workspace/azure-sdk-for-python/envatt/bin/generate_sdk", line 11, in <module> load_entry_point('azure-sdk-tools', 'console_scripts', 'generate_sdk')() File "/mnt/c/Users/Administrator/Documents/Workspace/azure-sdk-for-python/envatt/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point return get_distribution(dist).load_entry_point(group, name) File "/mnt/c/Users/Administrator/Documents/Workspace/azure-sdk-for-python/envatt/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point return ep.load() File "/mnt/c/Users/Administrator/Documents/Workspace/azure-sdk-for-python/envatt/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load return self.resolve() File "/mnt/c/Users/Administrator/Documents/Workspace/azure-sdk-for-python/envatt/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve module = __import__(self.module_name, fromlist=['__name__'], level=0) File "/mnt/c/Users/Administrator/Documents/Workspace/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/generate_sdk.py", line 6, in <module> from .swaggertosdk.SwaggerToSdkNewCLI import ( File "/mnt/c/Users/Administrator/Documents/Workspace/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/swaggertosdk/SwaggerToSdkNewCLI.py", line 9, in <module> from git import Repo, GitCommandError ModuleNotFoundError: No module named 'git'

fixed by  ---> pip install gitpython

load_entry_point('azure-sdk-tools', 'console_scripts', 'generate_sdk')() File "/mnt/c/Users/Administrator/Documents/Workspace/azure-sdk-for-python/envatt/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point return get_distribution(dist).load_entry_point(group, name) File "/mnt/c/Users/Administrator/Documents/Workspace/azure-sdk-for-python/envatt/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point return ep.load() File "/mnt/c/Users/Administrator/Documents/Workspace/azure-sdk-for-python/envatt/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load return self.resolve() File "/mnt/c/Users/Administrator/Documents/Workspace/azure-sdk-for-python/envatt/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve module = __import__(self.module_name, fromlist=['__name__'], level=0) File "/mnt/c/Users/Administrator/Documents/Workspace/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/generate_sdk.py", line 6, in <module> from .swaggertosdk.SwaggerToSdkNewCLI import ( File "/mnt/c/Users/Administrator/Documents/Workspace/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/swaggertosdk/SwaggerToSdkNewCLI.py", line 11, in <module> from .SwaggerToSdkCore import ( File "/mnt/c/Users/Administrator/Documents/Workspace/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/swaggertosdk/SwaggerToSdkCore.py", line 13, in <module> from github import Github, UnknownObjectException ModuleNotFoundError: No module named 'github'

fixed by ---> pip install pygithub
```

**Comment by lmazuel** [comment]
Could you give more context? 
Where did you see that?

**Comment by rakshith91** [comment]
This was seen when trying to generate azure attestation service  for track2. I know we don't own it - but i'm sure this will be seen when generating any service with track2.

**Comment by lmazuel** [comment]
Closing, will revisit as we have issue
