### ISSUE TITLE
VaultSecretGroup: TypeError: 'Subresource' object is not iterable   [jython]

### ISSUE THREAD

**Issue by Voronenko** [Azure/azure-sdk-for-python#1610]
When using Azure SDK under jython, in case if we configure VaultSecretGroup - we get unexpected exception  

TypeError: 'Subresource' object is not iterable 

This is caused by fact, that in 
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-compute/azure/mgmt/compute/v2017_03_30/models/vault_secret_group.py#L28

we have mapping
```
'source_vault': {'key': 'sourceVault', 'type': 'SubResource'},
```

while right mapping which plays well, seems to be 

```
'source_vault': {'key': 'sourceVault', 'type': 'SourceVault'},
```

i.e. portion of the code might be

```
...
VaultSecretGroup(
                source_vault=SourceVault(id=vault_info.id),
                vault_certificates=[
                    VaultCertificate(
                        certificate_url=certificate_url,
                        certificate_store="My"
                    )
                ]
            )
...
```

The change also does not harm original python flow.

**Comment by lmazuel** [comment]
Thanks for the report @Voronenko 
Do you have a complete stacktrace? No just `TypeError: 'Subresource' object is not iterable`? Your fix might work, but I'm not sure there not is not a deeper issue (SubResource _may_ be fine in some context). Did you try using CPython? What version of Jython are you using?
Thanks,

**Comment by Voronenko** [comment]
1. I need jython, as engine I am integrating azure part into uses that python dialect
2. Jython version - 2.7.1
3.  Versions of compute & network:
  jython ":azure-mgmt-compute:2.0.0:azure"
  jython ":azure-mgmt-network:1.5.0:azure"
4.
For code 
```
VaultSecretGroup(
                source_vault=SubResource(id=vault_info.id),
                vault_certificates=[
                    VaultCertificate(
                        certificate_url=certificate_url,
                        certificate_store="My"
                    )
                ]
            ))
```

callstack is

```
Caused by: javax.script.ScriptException: TypeError: 'SubResource' object is not iterable in <script> at line number 204
at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:222)
at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:59)
at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
at com.xebialabs.platform.script.jython.JythonSupport.$anonfun$executeScript$3(JythonSupport.scala:42)
... 34 more
Caused by: Traceback (most recent call last):
File "<script>", line 204, in <module>
File "__pyclasspath__/azure/mgmt/compute/compute/v2017_03_30/operations/virtual_machines_operations.py", line 180, in create_or_update
File "__pyclasspath__/msrest/serialization.py", line 301, in body
File "__pyclasspath__/msrest/serialization.py", line 181, in _convert_to_datatype
File "__pyclasspath__/msrest/serialization.py", line 181, in _convert_to_datatype
File "__pyclasspath__/msrest/serialization.py", line 181, in _convert_to_datatype
File "__pyclasspath__/msrest/serialization.py", line 181, in _convert_to_datatype
File "__pyclasspath__/msrest/serialization.py", line 155, in _convert_to_datatype
File "__pyclasspath__/msrest/serialization.py", line 181, in _convert_to_datatype
File "__pyclasspath__/msrest/serialization.py", line 181, in _convert_to_datatype
File "__pyclasspath__/msrest/serialization.py", line 168, in _convert_to_datatype
TypeError: 'SubResource' object is not iterable

at org.python.core.Py.TypeError(Py.java:265)
at org.python.core.PyObject.__iter__(PyObject.java:900)
at org.python.core.PyObjectDerived.__iter__(PyObjectDerived.java:890)
at msrest.serialization$py._convert_to_datatype$13(__pyclasspath__/msrest/serialization.py:185)
at msrest.serialization$py.call_function(__pyclasspath__/msrest/serialization.py)
at org.python.core.PyTableCode.call(PyTableCode.java:171)
at org.python.core.PyBaseCode.call(PyBaseCode.java:171)
at org.python.core.PyFunction.__call__(PyFunction.java:434)
at msrest.serialization$py._convert_to_datatype$13(__pyclasspath__/msrest/serialization.py:185)
at msrest.serialization$py.call_function(__pyclasspath__/msrest/serialization.py)
at org.python.core.PyTableCode.call(PyTableCode.java:171)
at org.python.core.PyBaseCode.call(PyBaseCode.java:171)
at org.python.core.PyFunction.__call__(PyFunction.java:434)
at msrest.serialization$py._convert_to_datatype$13(__pyclasspath__/msrest/serialization.py:185)
at msrest.serialization$py.call_function(__pyclasspath__/msrest/serialization.py)
at org.python.core.PyTableCode.call(PyTableCode.java:171)
at org.python.core.PyBaseCode.call(PyBaseCode.java:171)
at org.python.core.PyFunction.__call__(PyFunction.java:434)
at msrest.serialization$py._convert_to_datatype$13(__pyclasspath__/msrest/serialization.py:185)
at msrest.serialization$py.call_function(__pyclasspath__/msrest/serialization.py)
at org.python.core.PyTableCode.call(PyTableCode.java:171)
at org.python.core.PyBaseCode.call(PyBaseCode.java:171)
at org.python.core.PyFunction.__call__(PyFunction.java:434)
at msrest.serialization$py._convert_to_datatype$13(__pyclasspath__/msrest/serialization.py:185)
at msrest.serialization$py.call_function(__pyclasspath__/msrest/serialization.py)
at org.python.core.PyTableCode.call(PyTableCode.java:171)
at org.python.core.PyBaseCode.call(PyBaseCode.java:171)
at org.python.core.PyFunction.__call__(PyFunction.java:434)
at msrest.serialization$py.body$30(__pyclasspath__/msrest/serialization.py:302)
at msrest.serialization$py.call_function(__pyclasspath__/msrest/serialization.py)
at org.python.core.PyTableCode.call(PyTableCode.java:171)
at org.python.core.PyBaseCode.call(PyBaseCode.java:308)
at org.python.core.PyBaseCode.call(PyBaseCode.java:162)
at org.python.core.PyFunction.__call__(PyFunction.java:434)
at org.python.core.PyMethod.__call__(PyMethod.java:156)
at azure.mgmt.compute.compute.v2017_03_30.operations.virtual_machines_operations$py.create_or_update$7(__pyclasspath__/azure/mgmt/compute/compute/v2017_03_30/operations/virtual_machines_operations.py:224)
at azure.mgmt.compute.compute.v2017_03_30.operations.virtual_machines_operations$py.call_function(__pyclasspath__/azure/mgmt/compute/compute/v2017_03_30/operations/virtual_machines_operations.py)
at org.python.core.PyTableCode.call(PyTableCode.java:171)
at org.python.core.PyBaseCode.call(PyBaseCode.java:308)
at org.python.core.PyBaseCode.call(PyBaseCode.java:199)
at org.python.core.PyFunction.__call__(PyFunction.java:482)
at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
at org.python.core.PyMethod.__call__(PyMethod.java:228)
at org.python.pycode._pyx99.f$0(<script>:210)
at org.python.pycode._pyx99.call_function(<script>)
at org.python.core.PyTableCode.call(PyTableCode.java:171)
at org.python.core.PyCode.call(PyCode.java:18)
at org.python.core.Py.runCode(Py.java:1614)
at org.python.core.__builtin__.eval(__builtin__.java:497)
at org.python.core.__builtin__.eval(__builtin__.java:501)
at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:259)
at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
... 36 more
```

I also confirm that per change suggested in first comment - code runs like a charm both in python and jython.

**Comment by lmazuel** [comment]
`_convert_to_datatype` does not exist anymore, could you update your `msrest` and `msrestazure` lib? They are compatible with network/compute you use.

**Comment by Voronenko** [comment]
Dear Imazuel,

  I can confirm that with upgraded msrest/msrestazure works smoothly.

```
  jython ":msrest:0.4.18"
  jython ":msrestazure:0.4.16" 
```

**Comment by lmazuel** [comment]
Thanks @Voronenko !
