### ISSUE TITLE
Python3.6.9 azure-storage-blob: TypeError: new enumerations must be created as `ClassName([mixin_type,] enum_type)`

### ISSUE THREAD

**Issue by qizhen816** [Azure/azure-sdk-for-python#16594]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.7.0, 12.7.1
- **Operating System**: Ubuntu
- **Python Version**: 3.6.9

**Describe the bug**
```
Python 3.6.9 (default, Jul  3 2019, 15:36:16)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import azure.storage.blob
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qizhen/.local/lib/python3.6/site-packages/azure/storage/blob/__init__.py", line 10, in <module>
    from ._blob_client import BlobClient
  File "/home/qizhen/.local/lib/python3.6/site-packages/azure/storage/blob/_blob_client.py", line 24, in <module>
    from ._shared.base_client import StorageAccountHostsMixin, parse_connection_str, parse_query
  File "/home/qizhen/.local/lib/python3.6/site-packages/azure/storage/blob/_shared/base_client.py", line 44, in <module>
    from .constants import STORAGE_OAUTH_SCOPE, SERVICE_HOST_BASE, CONNECTION_TIMEOUT, READ_TIMEOUT
  File "/home/qizhen/.local/lib/python3.6/site-packages/azure/storage/blob/_shared/constants.py", line 8, in <module>
    from .._generated import AzureBlobStorage
  File "/home/qizhen/.local/lib/python3.6/site-packages/azure/storage/blob/_generated/__init__.py", line 9, in <module>
    from ._azure_blob_storage import AzureBlobStorage
  File "/home/qizhen/.local/lib/python3.6/site-packages/azure/storage/blob/_generated/_azure_blob_storage.py", line 19, in <module>
    from .operations import ServiceOperations
  File "/home/qizhen/.local/lib/python3.6/site-packages/azure/storage/blob/_generated/operations/__init__.py", line 9, in <module>
    from ._service_operations import ServiceOperations
  File "/home/qizhen/.local/lib/python3.6/site-packages/azure/storage/blob/_generated/operations/_service_operations.py", line 15, in <module>
    from .. import models as _models
  File "/home/qizhen/.local/lib/python3.6/site-packages/azure/storage/blob/_generated/models/__init__.py", line 10, in <module>
    from ._models_py3 import AccessPolicy
  File "/home/qizhen/.local/lib/python3.6/site-packages/azure/storage/blob/_generated/models/_models_py3.py", line 15, in <module>
    from ._azure_blob_storage_enums import *
  File "/home/qizhen/.local/lib/python3.6/site-packages/azure/storage/blob/_generated/models/_azure_blob_storage_enums.py", line 29, in <module>
    class AccessTier(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
  File "/usr/lib/python3.6/enum.py", line 119, in __prepare__
    member_type, first_enum = metacls._get_mixins_(bases)
  File "/usr/lib/python3.6/enum.py", line 441, in _get_mixins_
    raise TypeError("new enumerations must be created as "
TypeError: new enumerations must be created as `ClassName([mixin_type,] enum_type)`
```

**To Reproduce**
1. `pip install azure-storage-blob`
2. `python3 import azure.storage.blob`

BTW, 
Version 12.6.0 works fine.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by tasherif-msft** [comment]
Hi @qizhen816 are you still experiencing this issue? if so, are you attempting to run this in a venv?

**Comment by qizhen816** [comment]
@tasherif-msft It's working now, using azure-storage-blob-12.8.0.

**Comment by deeTEEcee** [comment]
I just found this and hit this issue. 
* Python 3.7.2
* Debian 9

I've tried versions 12.8.0, 12.8.1, 12.7.0 and they all fail. 12.6.0 works. 
cc: @tasherif-msft

**Comment by shaozhenged** [comment]
> 12.6.0

Thanks,I ｍet the same issue,with python 3.6.13 and package 12.8.0.It works,downgrade to 12.6.0.

**Comment by deeTEEcee** [comment]
@qizhen816 can we reopen this? This seems to still be happening with the latest.

**Comment by deeTEEcee** [comment]
Requirements: 
```
azure-core==1.10.0
azure-storage-blob==12.9.0 (or the latest)
azure-storage-file-datalake==12.5.0
```

If I just run an import in the python shell
```
>>> from azure.storage.filedatalake import DataLakeServiceClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/azure/storage/filedatalake/__init__.py", line 7, in <module>
    from ._download import StorageStreamDownloader
  File "/usr/local/lib/python3.7/site-packages/azure/storage/filedatalake/_download.py", line 8, in <module>
    from ._deserialize import from_blob_properties
  File "/usr/local/lib/python3.7/site-packages/azure/storage/filedatalake/_deserialize.py", line 15, in <module>
    from ._models import FileProperties, DirectoryProperties, LeaseProperties, DeletedPathProperties, StaticWebsite, \
  File "/usr/local/lib/python3.7/site-packages/azure/storage/filedatalake/_models.py", line 11, in <module>
    from azure.storage.blob import LeaseProperties as BlobLeaseProperties
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/__init__.py", line 10, in <module>
    from ._blob_client import BlobClient
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/_blob_client.py", line 26, in <module>
    from ._shared.base_client import StorageAccountHostsMixin, parse_connection_str, parse_query, TransportWrapper
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/_shared/base_client.py", line 38, in <module>
    from .constants import STORAGE_OAUTH_SCOPE, SERVICE_HOST_BASE, CONNECTION_TIMEOUT, READ_TIMEOUT
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/_shared/constants.py", line 8, in <module>
    from .._generated import AzureBlobStorage
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/_generated/__init__.py", line 9, in <module>
    from ._azure_blob_storage import AzureBlobStorage
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/_generated/_azure_blob_storage.py", line 21, in <module>
    from .operations import ServiceOperations
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/_generated/operations/__init__.py", line 9, in <module>
    from ._service_operations import ServiceOperations
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/_generated/operations/_service_operations.py", line 15, in <module>
    from .. import models as _models
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/_generated/models/__init__.py", line 10, in <module>
    from ._models_py3 import AccessPolicy
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/_generated/models/_models_py3.py", line 15, in <module>
    from ._azure_blob_storage_enums import *
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/_generated/models/_azure_blob_storage_enums.py", line 29, in <module>
    class AccessTier(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
  File "/usr/local/lib/python3.7/enum.py", line 129, in __prepare__
    member_type, first_enum = metacls._get_mixins_(bases)
  File "/usr/local/lib/python3.7/enum.py", line 466, in _get_mixins_
    raise TypeError("new enumerations should be created as "
TypeError: new enumerations should be created as `EnumName([mixin_type, ...] [data_type,] enum_type)`
```

**Comment by qizhen816** [comment]
It looks the error occurs again in the newest version. @deeTEEcee reported and my colleague found it too.

**Comment by lmazuel** [comment]
Could people with the issue confirmed the version of `six` there are using? There was a bug in `six` that is fixed starting 1.11.0, that _may_ explain the issue. Thanks.

**Comment by lmazuel** [comment]
Ok, I can indeed reproduce the issue with six 1.10.0, not with any version since 1.11.0. 

Since `azure-core` 1.11.0, the minimum version required for `six` is 1.11.0 (was 1.6.0). Storage packages have a dependency on `azure-core>=1.10.0`. Therefore, it's indeed possible to get a storage package installed with `azure-core` 1.10.0 and `six` 1.6.0, while having no warning or no sign of dependencies trouble. 

Short term fix is to update six to at least 1.11.0 (ideally the last one), or install fresh venv.

Long term fix storage packages must require `azure-core` at least to be 1.11.0, I created a dedicated issue for that: https://github.com/Azure/azure-sdk-for-python/issues/22215

I'm suggesting to close this issue, since we understand the cause and I created a more dedicated issue for the dependency update.

**Comment by tasherif-msft** [comment]
@lmazuel sounds good. I can put out PRs to update the packages!

**Comment by Scherlac** [comment]
I hade a similar issue with ADF see: [link](https://github.com/pysmt/pysmt/issues/652#issuecomment-1119297102)

In my case it was caused by pysmt-0.9.0 package, witch had silently overwritten my previously installed six-1.16.0 package with version 1.10.0. They are already on it and the next release should fix that.
