### ISSUE TITLE
[ServiceBus] Creating resources with mgmt randomly results in ResourceExistsError

### ISSUE THREAD

**Issue by swathipil** [Azure/azure-sdk-for-python#16645]
- **Package Name**: [azure-servicebus]
- **Package Version**: 7.0.2
- **Operating System**: Windows
- **Python Version**: 3.9

**Describe the bug**
When creating resources by running the `mgmt_*.py` samples, they randomly fail with the following error: `azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'Conflict'`. This happens both locally and in the test pipeline. For example, if we were running a sample multiple times in rapid succession or in parallel that created a topic named `demo_topic` in the same resource group and SB namespace, it is possible that one sample would try to create a `demo_topic` before the other sample could delete the `demo_topic` that it created.

To ensure this was not happening, for each resource being created, a UUID was added to the name to ensure that multiple resources with the same name were not being created at the same time before they could be deleted. This results in the same error randomly, even when the resource does not already exist.

**To Reproduce**
1. Run any of the samples named `mgmt_*.py` (and add env variables as needed). Like [`mgmt_rule.py`](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/servicebus/azure-servicebus/samples/sync_samples/mgmt_rule.py)
2. This will randomly result in the error.

**Expected behavior**
I expect the sample to create and delete the resource using the `ServiceBusAdministrationClient` without the ResourceExistsError each time it is run.

**Screenshots**
Sample Error Log:
```
-- List Rules
Rule Name: $Default
Rule Name: sb_mgmt_rule18ba42ea-215e-43b6-a958-bc66d10ecc1e    
Rule Name: sb_mgmt_rule88d8ab79-b463-4337-8d81-264b120c0342    
Rule Name: sb_mgmt_rule8e1c13a5-ac73-411c-b7a3-03160ce13814    
                                                               
-- Create Rule
Creating rule sb_mgmt_rulea8e2fce7-c833-4e27-9de8-b2bbf4a4ab4c.
Traceback (most recent call last):
  File "C:\Users\swathip\Documents\forks\azure-sdk-for-python\sdk\servicebus\azure-servicebus\samples\sync_samples\mgmt_rule.py", line 63, in <module>   
    create_rule(servicebus_mgmt_client)
  File "C:\Users\swathip\Documents\forks\azure-sdk-for-python\sdk\servicebus\azure-servicebus\samples\sync_samples\mgmt_rule.py", line 33, in create_rule
    servicebus_mgmt_client.create_rule(TOPIC_NAME, SUBSCRIPTION_NAME, RULE_NAME)
  File "C:\Users\swathip\Documents\env39\lib\site-packages\azure\servicebus\management\_management_client.py", line 1045, in create_rule
    entry_ele = self._impl.rule.put(
  File "C:\Users\swathip\Documents\env39\lib\site-packages\azure\servicebus\management\_generated\operations\_rule_operations.py", line 188, in put      
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "c:\users\swathip\documents\forks\azure-sdk-for-python\sdk\core\azure-core\azure\core\exceptions.py", line 102, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'Conflict'
```
**Additional context**
Since these samples randomly fail in the test pipeline due to this error, they have been added to the `IGNORED_SAMPLES` section of [`test_run_samples.py`](https://github.com/Azure/azure-sdk-for-python/blob/62eaa68c22426789ba9b4677840b35ded6064010/scripts/devops_tasks/test_run_samples.py#L23). After fixing the bug, these samples should be removed from `IGNORED_SAMPLES`.

**Comment by swathipil** [comment]
this affects the following samples:
```
"mgmt_queue.py",
"mgmt_rule.py",
"mgmt_subscription.py",
"mgmt_topic.py",
"mgmt_queue_async.py",
"mgmt_rule_async.py",
"mgmt_subscription_async.py",
"mgmt_topic_async.py",
```
