### ISSUE TITLE
Unable to authenticate against Azure Stack

### ISSUE THREAD

**Issue by charliejllewellyn** [Azure/azure-sdk-for-python#1669]
Hi,

This could be related to as I previously got this working by working by making some amendments to the code but I believe it has stopped working since this change was implemented.

I am again using this module indirectly via Ansible. I am using Active Directory Auth. I have set the following parameters with Ansible.

```
export AZURE_AD_USER=<username>@<domain>.onmicrosoft.com
export AZURE_PASSWORD='******'
export AZURE_SUBSCRIPTION_ID=<uuid>
export AZURE_CLOUD_ENVIRONMENT="https://management.local.azurestack.external/metadata/endpoints?api-version=2016-01-01"
export REQUESTS_CA_BUNDLE=//etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
```

When running Ansible I receive the following error:

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_qcS34j/ansible_module_azure_rm_resourcegroup.py", line 259, in <module>
    main()
  File "/tmp/ansible_qcS34j/ansible_module_azure_rm_resourcegroup.py", line 256, in main
    AzureRMResourceGroup()
  File "/tmp/ansible_qcS34j/ansible_module_azure_rm_resourcegroup.py", line 140, in __init__
    supports_tags=True)
  File "/tmp/ansible_qcS34j/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py", line 274, in __init__
  File "/usr/lib/python2.7/site-packages/msrestazure/azure_active_directory.py", line 369, in __init__
    self.set_token()
  File "/usr/lib/python2.7/site-packages/msrestazure/azure_active_directory.py", line 415, in set_token
    raise_with_traceback(AuthenticationError, "", err)
  File "/usr/lib/python2.7/site-packages/msrest/exceptions.py", line 48, in raise_with_traceback
    raise error
msrest.exceptions.AuthenticationError: , MissingTokenError: (missing_token) Missing access token parameter.

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_qcS34j/ansible_module_azure_rm_resourcegroup.py\", line 259, in <module>\n    main()\n  File \"/tmp/ansible_qcS34j/ansible_module_azure_rm_resourcegroup.py\", line 256, in main\n    AzureRMResourceGroup()\n  File \"/tmp/ansible_qcS34j/ansible_module_azure_rm_resourcegroup.py\", line 140, in __init__\n    supports_tags=True)\n  File \"/tmp/ansible_qcS34j/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 274, in __init__\n  File \"/usr/lib/python2.7/site-packages/msrestazure/azure_active_directory.py\", line 369, in __init__\n    self.set_token()\n  File \"/usr/lib/python2.7/site-packages/msrestazure/azure_active_directory.py\", line 415, in set_token\n    raise_with_traceback(AuthenticationError, \"\", err)\n  File \"/usr/lib/python2.7/site-packages/msrest/exceptions.py\", line 48, in raise_with_traceback\n    raise error\nmsrest.exceptions.AuthenticationError: , MissingTokenError: (missing_token) Missing access token parameter.\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
```

Running this against public Azure works fine.

```
export AZURE_CLOUD_ENVIRONMENT="AzureCloud"
```

We have an Azure Stack development environment I would be happy for you to use to test against if it would help development?

**Comment by lmazuel** [comment]
Hi @charliejllewellyn testing the env would be awesome indeed :)

@yugangw-msft are you doing some magic to authenticate the CLI against AzureStack?

**Comment by charliejllewellyn** [comment]
@lmazuel I've sent some details through in a mail for our Lab :)

**Comment by charliejllewellyn** [comment]
I have spent a little time on this and we have discovered that the issue is being caused because the resource being set when fetching a token is the ARM endpoint, it appears with Azure Stack this resource should be the active_directory_resource_id.

I have a thread open on the MSDN forum discussing this in more detail here, https://social.msdn.microsoft.com/Forums/azure/en-US/20845560-cb08-4e6e-9cf7-4406c0e7e535/azure-compatabilty?forum=AzureStack.

**Comment by lmazuel** [comment]
Thanks @charliejllewellyn that helps a lot!
It's on me, and I did a PR for that:
https://github.com/Azure/msrestazure-for-python/pull/65

I need more testing, since it's critical, but should releasable soon.

Thanks again!

**Comment by lmazuel** [comment]
msrestazure with the fix is released.
Thanks!
