### ISSUE TITLE
AttributeError: 'ServicePrincipalCredentials' object has no attribute 'get_token'

### ISSUE THREAD

**Issue by sanju918** [Azure/azure-sdk-for-python#16923]
Script for China cloud
I'm getting the error **AttributeError: 'ServicePrincipalCredentials' object has no attribute 'get_token'** what am I doing wrong.

```
from azure.common.credentials import ServicePrincipalCredentials
from msrestazure.azure_cloud import AZURE_CHINA_CLOUD
from azure.mgmt.resource.resources import ResourceManagementClient
from my_az_keyvault import KeyVault

def get_cred():
    china_tenant_id = 'xyz'
    china_cloud_mgr_id = 'abcd'
    vault = KeyVault(vault_name='my-valut')

    china_cloud_key = vault.get('azure-china-resource-reader')
    resource_mgr_cred = ServicePrincipalCredentials(
        client_id=china_cloud_mgr_id,
        secret=china_cloud_key,
        tenant=china_tenant_id,
        china=True,
        base_url=AZURE_CHINA_CLOUD.endpoints.resource_manager,
        credential_scope=[AZURE_CHINA_CLOUD.endpoints.resource_manager + "/.default"]
    )
    return resource_mgr_cred

def get_tags_subs(subscription_id):
    sub_scope = 'subscriptions/' + subscription_id
    resource_mgmt_client = ResourceManagementClient(
        credential=get_cred(),
        subscription_id=subscription_id,
        base_url=AZURE_CHINA_CLOUD.endpoints.resource_manager
    )

    tags = resource_mgmt_client.tags.get_at_scope(sub_scope)
    return tags


def main():
    print(get_tags_subs('abcd-efgh-igk-lmnopqr'))


if __name__ == '__main__':
    main()
```

These are the requirements I installed

```
my-az-keyvault==1.0.0.post332
azure-mgmt-subscription==0.6.0
azure-mgmt-resource>=1.15.0
```

Complete error 

```
Retrieving Secret: 'azure-china-resource-reader' with parameters:
{
  "version": null
}
Traceback (most recent call last):
  File "main.py", line 80, in <module>
    main()
  File "main.py", line 76, in main
    print(get_tags_subs('abcd-efgh-igk-lmnopqr'))
  File "main.py", line 71, in get_tags_subs
    tags = resource_mgmt_client.tags.get_at_scope(sub_scope)
  File "/Users/sanjayq/azure/Azure-China/env/lib/python3.7/site-packages/azure/mgmt/resource/resources/v2020_06_01/operations/_tags_operations.py", line 541, in get_at_scope
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/Users/sanjay/azure/Azure-China/env/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/Users/sanjay/azure/Azure-China/env/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/sanjay/azure/Azure-China/env/lib/python3.7/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/Users/sanjay/azure/Azure-China/env/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/sanjay/azure/Azure-China/env/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/sanjay/azure/Azure-China/env/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/Users/sanjay/azure/Azure-China/env/lib/python3.7/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/Users/sanjay/azure/Azure-China/env/lib/python3.7/site-packages/azure/core/pipeline/policies/_retry.py", line 435, in send
    response = self.next.send(request)
  File "/Users/sanjay/azure/Azure-China/env/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 69, in send
    _await_result(self._policy.on_request, request)
  File "/Users/sanjay/azure/Azure-China/env/lib/python3.7/site-packages/azure/core/pipeline/_tools.py", line 29, in await_result
    result = func(*args, **kwargs)
  File "/Users/sanjay/azure/Azure-China/env/lib/python3.7/site-packages/azure/core/pipeline/policies/_authentication.py", line 93, in on_request
    self._token = self._credential.get_token(*self._scopes)
AttributeError: 'ServicePrincipalCredentials' object has no attribute 'get_token'

```

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by chlowell** [comment]
The latest azure-mgmt-resource (15.x) expects a credential from azure-identity, whose ClientSecretCredential is the equivalent of azure.common.credentials.ServicePrincipalCredentials. You will also need to configure the credential and client to use Azure China Cloud. The relevant snippets of your code above would look something like this afterward:

```py
from azure.identity import ClientSecretCredential

credential = ClientSecretCredential(
    tenant_id=china_tenant_id,
    client_id=china_cloud_mgr_id,
    client_secret=china_cloud_key,
    authority=AZURE_CHINA_CLOUD.endpoints.active_directory
)

resource_mgmt_client = ResourceManagementClient(
    credential=credential,
    subscription_id=subscription_id,
    base_url=AZURE_CHINA_CLOUD.endpoints.resource_manager,
    credential_scopes=[AZURE_CHINA_CLOUD.endpoints.active_directory_resource_id + "/.default"]
)
```

(Related: #14919, #16908)

**Comment by jsntcy** [comment]
Close this as solution is provided.
