### ISSUE TITLE
Can't export devices from my IOTHub

### ISSUE THREAD

**Issue by alexandreg19** [Azure/azure-sdk-for-python#1695]
- **OS and version used:** <VERSION>  Ubuntu 16.04 (Bash For Windows)

- **Python runtime used:** <VERSION>  Python 3.5.2 (default, Sep 14 2017, 22:51:06)

- **SDK version used:** <VERSION>  
azure-iothub-service-client==1.1.0.19
azure-mgmt-iothub==0.2.2
azure==2.0.0

# Description of the issue:

When I try to use the iot_hub_resource.export_devices() method, I got an Error : `too many 500 error responses`
I don't know if it's caused by an argument, an other error in my code, or anything..
I just followed this document : http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.iothub.operations.html

I don't have any issue when I try to use other methods, like : 
```
- iot_hub_resource.get()
- iot_hub_resource.get_quota_metrics()
- iot_hub_resource.get_stats()
```

# Code sample exhibiting the issue:

```
authentication_endpoint = 'https://login.microsoftonline.com/'
resource = 'https://management.core.windows.net/'

context = adal.AuthenticationContext(authentication_endpoint + tenant_id)
token_response = context.acquire_token_with_client_credentials(resource, application_id, application_secret)

credential = AADTokenCredentials(token_response)

container_name = 'backupfiles-' + datetime.now().strftime("%Y-%m-%d")

blob_service = BlockBlobService(account_name=storage_account_name, account_key=storage_account_key)
containers = blob_service.list_containers()

if container_name in [c.name for c in containers]:
    print("Container %s already exist" % container_name)
else:
    blob_service.create_container(container_name, public_access=PublicAccess.Container)
    print("Container %s created" % container_name)

client = IotHubClient(credential,subscription_id)
client.iot_hub_resource.export_devices(resourcegroup,resourcename,'https://mystorage.blob.core.windows.net/' + container_name, False)
```

# Console log of the issue:

```
Traceback (most recent call last):
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 712, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Devices/IotHubs/xxx/exportDevices?api-version=2016-02-03 (Caused by ResponseError('too many 500 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/msrest/service_client.py", line 194, in send
    **kwargs)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/requests_oauthlib/oauth2_session.py", line 360, in request
    headers=headers, data=data, **kwargs)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/requests/adapters.py", line 499, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Devices/IotHubs/xxx/exportDevices?api-version=2016-02-03 (Caused by ResponseError('too many 500 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "export_devices.py", line 55, in <module>
    client.iot_hub_resource.export_devices(resourcegroup,resourcename,'https://mystorage.blob.core.windows.net/' + container_name + '/' + blob_filename, False)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/azure/mgmt/iothub/operations/iot_hub_resource_operations.py", line 1327, in export_devices
    request, header_parameters, body_content, **operation_config)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/msrest/service_client.py", line 220, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/msrest/exceptions.py", line 45, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/msrest/service_client.py", line 194, in send
    **kwargs)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/requests_oauthlib/oauth2_session.py", line 360, in request
    headers=headers, data=data, **kwargs)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/requests/adapters.py", line 499, in send
    raise RetryError(e, request=request)
msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Devices/IotHubs/xxx/exportDevices?api-version=2016-02-03 (Caused by ResponseError('too many 500 error responses',))
```

Hope you could help me.
Thanks,

Regards,
Alexandre

**Comment by lmazuel** [comment]
Hi @alexandreg19 
This is most likely a RestAPI issue :/
@annatisch do you you have contact on the IoTHub team we can tag here?

**Comment by annatisch** [comment]
Sure, @zolvarga might be able to take a look :)

**Comment by alexandreg19** [comment]
Hi @annatisch @lmazuel 

Any news on this subject ?
I originaly post this issue on the sdk-python-iot repo, but @zolvarga told me that it concerns the management repo (if I'm correct), so here I am. 

Regards,
Alexandre

**Comment by lmazuel** [comment]
Hi @alexandreg19 
That's indeed a Management issue, but it's also a HTTP 500, meaning that's a RestAPI issue more than a Python issue. I made a few search, tagging specifically IoTMgmt this time:

@mastermanu @andrew-buckley could you please help with this ARM issue that returns a 500?
Thanks,

**Comment by lmazuel** [comment]
@alexandreg19 Could you activate the logs:
```python
import logging
logging.basicConfig(logging.DEBUG)
```
And sent it to me by private email? \<my_github_alias\>@microsoft.com
Thanks!

**Comment by lmazuel** [comment]
@alexandreg19 answer from @mastermanu after investigation on the server side:

> This is what we see on the server side:
> Microsoft.Azure.Devices.ResourceProvider.Exceptions.ResourceProviderException: Internal Error ---> Microsoft.Azure.Devices.Common.Cloud.Exceptions.IotHubException: Error: BadRequest {"Message":"ErrorCode:BlobContainerValidationError;Unauthorized to write to output blob container.","ExceptionMessage":"Tracking ID:45b22aea56e64c0faf97279c07f11c02-G:0-TimeStamp:12/21/2017 18:01:05"}
> 
> That basically means the URI passed in on the Export request does not include a SAS token that IoT Hub can use to actually write out to the blip.
> 
> Secondly, that RP import / export API is actually deprecated (we probably need to update our documentation to indicate this). It should still work, but you can make a call directly to the Data Plane using SharedAccessPolicy credentials instead. Our swagger documentation is again lacking here (needs to be cleaned and updated), but here is our C# SDK file that shows how to export and import via data plane:
> 
> https://github.com/Azure/azure-iot-sdk-csharp/blob/1f23ed79504913984b769aeb83a73ce88027c53f/service/Microsoft.Azure.Devices/HttpRegistryManager.cs

**Comment by alexandreg19** [comment]
Hi !

As I said to @lmazuel , I followed this hint and it's a little bit better. Here my code updated with the SASToken : 

```
sas = BlobSharedAccessSignature(dest_storage_name, dest_storage_key)
container_token = sas.generate_container(
    container_name,
    ContainerPermissions.WRITE + BlobPermissions.CREATE + BlobPermissions.WRITE,
    datetime.now() + timedelta(hours=1)
)
blob_filename = "backup-{}".format(datetime.now().strftime("%Y%m%d"))

url = blob_service.make_blob_url(container_name, blob_filename, sas_token=container_token)
print(url)
exit(0)
client.iot_hub_resource.export_devices(rg,iothub.name,url,False)
```

Now, blobs are created, but there is nothing in it. The script creates 5 blobs (one for each failed execution ) and do nothing more, and finally end with the Internal Error.

Regards, 
Alexandre

**Comment by alexandreg19** [comment]
Hi @lmazuel @mastermanu,

My issue is now fixed thanks to you two.
It was indeed the SAS token : 

```
container_permissions = ContainerPermissions.WRITE
blob_permissions = BlobPermissions.CREATE + BlobPermissions.WRITE + BlobPermissions.READ + BlobPermissions.DELETE

container_token = sas.generate_container(
            container_name,
            container_permissions + blob_permissions,
            datetime.now() + timedelta(hours=1)
        )

blob_filename = "backup-{}".format(datetime.now().strftime("%Y%m%d"))
url = blob_service.make_blob_url(container_name, blob_filename, sas_token=container_token)

client.iot_hub_resource.export_devices(rg, iothub.name, url, True)
```

All is working great now, thank you for the help.

Regards,
Alexandre
