### ISSUE TITLE
Azure Datalake Gen2 Move File/Folder Issue

### ISSUE THREAD

**Issue by aaptl** [Azure/azure-sdk-for-python#17119]
**Describe the bug**
When trying to get azure.storage.filedatalake rename_file method working for an existing file_client I receive the following error:
***Exception or Stack Trace***
(SourcePathNotFound) The source path for a rename operation does not exist.
RequestId:ca943fb7-c01f-001b-4ea9-111833000000
Time:2021-03-05T10:23:17.9985950Z
ERROR:waitress:Exception while serving /api/
Traceback (most recent call last):
  File "C:\Users\ankit\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 350, in service
    task.service()
  File "C:\Users\ankit\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 171, in service
    self.execute()
  File "C:\Users\ankit\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 441, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\ankit\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\ankit\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\ankit\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ankit\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ankit\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\ankit\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ankit\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\ankit\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\ankit\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.

***Code Snippet***
 file_system_client = service_client.get_file_system_client(file_system=containerName)
       directory_client = file_system_client.get_directory_client(existingfilefolderpath)
       directory_client.rename_directory(directory_client.file_system_name + newfilefolderpath)
**Screenshots**
i have tried this way as well but notgetting solution
![docx](https://user-images.githubusercontent.com/30947120/110104148-cbbe9f80-7dcc-11eb-8225-8e415544b041.png)

Thanks...

**Comment by tasherif-msft** [comment]
Hi @aaptl what datalake version are you using?
