### ISSUE TITLE
Unable to download file from blob storage due to SSL error

### ISSUE THREAD

**Issue by deepaleekhare31** [Azure/azure-sdk-for-python#17477]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.7.1
- **Operating System**: Windows 10
- **Python Version**: 3.7.3

**Describe the bug**
Unable to download file from blob storage due to SSL error
**Error** 
azure.core.exceptions.ServiceRequestError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

**Expected behaviour**
Zip File should be downloaded.

**Code Used**
blob_service_client = BlobServiceClient.from_connection_string(CONNECT_STR)
download_file_path = os.path.join(path.strip(), 'HelloWorld.zip')
blob_client = blob_service_client.get_blob_client(container=container_name, blob=blobname)
print("\nDownloading blob to \n\t" + download_file_path)
with open(download_file_path, "wb") as my_blob:
    blob_data = blob_client.download_blob()
    blob_data.readinto(my_blob)
**** Tried with below commented part - Still facing the same error *****
#####with**_ open(download_file_path, "wb") as download_file:
#####download_file.write(blob_client.download_blob().readall())

**Error** 
azure.core.exceptions.ServiceRequestError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

**Steps Followed**
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python

**Comment by chlowell** [comment]
Thanks for opening this issue, we'll investigate as soon as possible.

**Comment by tasherif-msft** [comment]
Hi @deepaleekhare31, could you specify the failing line? is it `blob_data = blob_client.download_blob()`?

**Comment by deepaleekhare31** [comment]
Yes, that's right.

**Comment by deepaleekhare31** [comment]
Here are the logs in detail:

C:\Python37\python.exe C:/Users/Utility/DownloadArtifact.py

Downloading blob to 
	C:\Users\Utility\Artifact.zip
Traceback (most recent call last):
  File "C:/Users/Utility/DownloadArtifact.py", line 46, in <module>
    browse_path(UTF_PATH=str(sys.argv))
  File "C:/Users/Utility/DownloadArtifact.py", line 42, in browse_path
    **download_file.write(blob_client.download_blob().readall())**
  File "C:\Python37\lib\site-packages\azure\core\tracing\decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\azure\storage\blob\_blob_client.py", line 820, in download_blob
    return StorageStreamDownloader(**options)
  File "C:\Python37\lib\site-packages\azure\storage\blob\_download.py", line 316, in __init__
    self._response = self._initial_request()
  File "C:\Python37\lib\site-packages\azure\storage\blob\_download.py", line 366, in _initial_request
    **self._request_options
  File "C:\Python37\lib\site-packages\azure\storage\blob\_generated\operations\_blob_operations.py", line 182, in download
    pipeline_response = self._client._pipeline.run(request, stream=True, **kwargs)
  File "C:\Python37\lib\site-packages\azure\core\pipeline\_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "C:\Python37\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "C:\Python37\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "C:\Python37\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "C:\Python37\lib\site-packages\azure\core\pipeline\policies\_redirect.py", line 158, in send
    response = self.next.send(request)
  File "C:\Python37\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "C:\Python37\lib\site-packages\azure\storage\blob\_shared\policies.py", line 515, in send
    raise err
  File "C:\Python37\lib\site-packages\azure\storage\blob\_shared\policies.py", line 489, in send
    response = self.next.send(request)
  File "C:\Python37\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "C:\Python37\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "C:\Python37\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "C:\Python37\lib\site-packages\azure\storage\blob\_shared\policies.py", line 290, in send
    response = self.next.send(request)
  File "C:\Python37\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "C:\Python37\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "C:\Python37\lib\site-packages\azure\core\pipeline\_base.py", line 103, in send
    self._sender.send(request.http_request, **request.context.options),
  File "C:\Python37\lib\site-packages\azure\storage\blob\_shared\base_client.py", line 325, in send
    return self._transport.send(request, **kwargs)
  File "C:\Python37\lib\site-packages\azure\core\pipeline\transport\_requests_basic.py", line 285, in send
    raise error
azure.core.exceptions.ServiceRequestError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

Process finished with exit code 1

**Comment by tasherif-msft** [comment]
Hi @deepaleekhare31 do you happen to be using some sort of a proxy?
This issue seems to occur when the remote endpoint (azure) is not signed with a certificate in your local certificate authority store.

Useful links https://stackoverflow.com/questions/64981482/azure-python-sdk-throwing-ssl-bad-handshake-error-when-connecting-from-service-p and https://github.com/Azure/azure-sdk-for-python/issues/1384

If troubleshooting this issue does not work, you can create your own `session` object and set `session.verify=False` and pass it while instantiation your client. 

```
import requests
session = requests.session()
session.verify = False
BlobServiceClient.from_connection_string(CONNECT_STR, session=session)
...
```
Let me know what approach works for you.

**Comment by chobostar** [comment]
I had similar issue during local testing with self-signed certs and Azurite. 

this construction helped me:
```
blob_service_client = BlobServiceClient.from_connection_string(conn_str=os.environ.get("AZURE_STORAGE_CONNECTION_STRING"),
                                                               retry_total=0,
                                                               connection_verify=False)
```

Package version: 12.11.0
