### ISSUE TITLE
Error when executing python Azure Function: RuntimeError: Attempted to compile AOT function without the compiler used by `numpy.distutils` present

### ISSUE THREAD

**Issue by ZXeno** [Azure/azure-sdk-for-python#17510]
I have an HttpTrigger Azure Function written in Python with a dependency that has a child dependency on `numba` that throws the following error when the function is executed in the Azure production environment:

    ``` Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.my_function
     ---> Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException: Result: Failure
    Exception: RuntimeError: Attempted to compile AOT function without the compiler used by `numpy.distutils` present. If using conda try:
    
    #> conda install gcc_linux-64 gxx_linux-64
    Stack:   File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py", line 284, in _handle__function_load_request
        func = loader.load_function(
      File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 40, in call
        return func(*args, **kwargs)
      File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/loader.py", line 76, in load_function
        mod = importlib.import_module(fullmodname)
      File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 790, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/home/site/wwwroot/my_function/__init__.py", line 2, in <module>
        from rembg.bg import remove
      File "/home/site/wwwroot/.python_packages/lib/site-packages/rembg/bg.py", line 6, in <module>
        from pymatting.alpha.estimate_alpha_cf import estimate_alpha_cf
      File "/home/site/wwwroot/.python_packages/lib/site-packages/pymatting/__init__.py", line 2, in <module>
        import pymatting_aot.cc
      File "/home/site/wwwroot/.python_packages/lib/site-packages/pymatting_aot/cc.py", line 54, in <module>
        compile_modules()
      File "/home/site/wwwroot/.python_packages/lib/site-packages/pymatting_aot/cc.py", line 8, in compile_modules
        cc = CC("aot")
      File "/home/site/wwwroot/.python_packages/lib/site-packages/numba/pycc/cc.py", line 65, in __init__
        self._toolchain = Toolchain()
      File "/home/site/wwwroot/.python_packages/lib/site-packages/numba/pycc/platform.py", line 78, in __init__
        self._raise_external_compiler_error()
      File "/home/site/wwwroot/.python_packages/lib/site-packages/numba/pycc/platform.py", line 121, in _raise_external_compiler_error
        raise RuntimeError(msg)
    
       at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters, FunctionInvocationContext context) in /src/azure-functions-host/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs:line 93
       at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) in /src/azure-functions-host/src/WebJobs.Script/Description/FunctionInvokerBase.cs:line 82
       at Microsoft.Azure.WebJobs.Script.Description.FunctionGenerator.Coerce[T](Task`1 src) in /src/azure-functions-host/src/WebJobs.Script/Description/FunctionGenerator.cs:line 225
       at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
       at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 555
       at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 503
       at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 281
       --- End of inner exception stack trace ---
       at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 328
       at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 94
    ```

 This will run locally with no issues on my Windows 10 machine and Linux Mint laptop. This is only happening after it has been deployed to Azure, and I can't seem to narrow down what I'm missing or if this is an actual bug in the Azure environment.

* specifying specific version(s) of `numba` in the requirements.txt file
* specifying specific version(s) of `numpy` in the requirements.txt file
* specifying all dependencies and child dependencies with versions specified and in specific order
* using the following command and flags for builds and deployments: `func azure functionapp publish <my_app>` with these flags: `--build remote` and `--build-native-deps`, and `--build local` on my linux machine.
* changing from an AppService App running python 3.8 to an Azure Functions App with python 3.9 (preview)

[This file](https://github.com/numba/numba/blob/master/numba/pycc/platform.py) seems to contain the exact error thrown. Running through how that error gets raised, it looks like it's trying to check for an external compiler in the Azure Functions environment at runtime, and fails to find one (function defined on line 46: `_check_external_compiler()`). Without seeing the actual error thrown by that function, it's hard to determine if it's because it can't find it, or because it can't write to the file-system, as alluded to in the comment on [line 61](https://github.com/numba/numba/blob/bb2ec93fe107339d752bb03bde49f505fa2ed02c/numba/pycc/platform.py#L61)

This leads me to believe its an issue with the Azure Functions execution environment.

**Comment by chlowell** [comment]
Hi @ZXeno, thanks for opening this issue. I agree it appears to be an issue with the Azure Functions runtime environment. I doubt anyone working on that tracks issues in this repository, so I'll close this in favor of Azure/azure-functions-python-worker#835.

**Comment by ZXeno** [comment]
@chlowell Thank you, apologies for posting it in the wrong location.
