### ISSUE TITLE
[Azure Identity] Support auth code flow in WSL Ubuntu 18.04

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-sdk-for-python#17615]
Test script:

```py
from azure.identity import InteractiveBrowserCredential

InteractiveBrowserCredential().get_token('https://management.azure.com/.default')
```

This works in WSL Ubuntu 20.04, but fails in 18.04:

```
InteractiveBrowserCredential.get_token failed: Failed to open a browser
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    InteractiveBrowserCredential().get_token('https://management.azure.com/.default')
  File "/home/user2/env36/lib/python3.6/site-packages/azure/identity/_internal/interactive.py", line 136, in get_token
    result = self._request_token(*scopes, **kwargs)
  File "/home/user2/env36/lib/python3.6/site-packages/azure/identity/_internal/decorators.py", line 45, in wrapper
    return fn(*args, **kwargs)
  File "/home/user2/env36/lib/python3.6/site-packages/azure/identity/_credentials/browser.py", line 88, in _request_token
    raise CredentialUnavailableError(message="Failed to open a browser")
azure.identity._exceptions.CredentialUnavailableError: Failed to open a browser
```

Root cause and more info: https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/332

**Comment by chlowell** [comment]
This works for me on 18.04.5, using either WSL 1 (4.4.0-19041-Microsoft) or 2 (5.4.72-microsoft-standard-WSL2). I don't know what the key difference between our environments could be; can you please add the output of `lsb_release -a`?
