### ISSUE TITLE
ManagedIdentityCredential: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by pmbrull** [Azure/azure-sdk-for-python#17661]
- **Package Name**: azure-identity
- **Package Version**: 1.5.0
- **Operating System**: Linux
- **Python Version**: 3.6

**Describe the bug**
We have an App Function with an MSI, and we retrieve some secrets from an Azure Key Vault. We use the DefaultAzureCredential to authenticate to the azure-keyvault-secrets SecretClient. When performing around 200 sequential calls to the endpoint, we start getting the following error:

```
ManagedIdentityCredential: maximum recursion depth exceeded Stack:
[...]
File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/keyvault/secrets/_client.py", line 72, in get_secret
[...]
File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/identity/_credentials/default.py", line 144, in get_token return super(DefaultAzureCredential, self).get_token(*scopes, **kwargs) 
File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/identity/_credentials/chained.py", line 90, in get_token raise ClientAuthenticationError(message=message)
```

Which not only fails the execution, but leaves the application in a faulty state until it gets manually restarted.

**To Reproduce**
1. Configure App Function with MSI (python 3.6, Linux OS, EP1:1 plan).
2. Add policy in Key Vault for the App Function.
3. Run a couple of hundreds of sequential calls to the function, which retrieves some secrets from the key vault using azure-keyvault-secrets SecretClient.

**Expected behavior**
The application runs correctly and does not leave the App Function service in a faulty state.

**Additional context**
The app function is rather simple. It retrieves the secrets which are used to authenticate against an Azure SQL database to perform some pandas operations.

Thanks,
Pere

**Comment by iscai-msft** [comment]
Thank you for filing this issue @pmbrull , we are investigating

**Comment by chlowell** [comment]
Thank you for opening this issue. I haven't been able to reproduce the error, and don't see where ManagedIdentityCredential would recurse. Can you please share more of the stack, showing the recursion? If it isn't already included in your logs, it should be after you enable debug level logging, either for the root, or "azure" or "azure.identity" specifically.

**Comment by pmbrull** [comment]
Hi,

Thank you for your answer. I've also been surfing the source code and it also bugs me not being able to find the recursion spot :/

I've (tried to) enable the Debug level:

host.json:
```
"logging": {
        "logLevel": {
        "default": "Debug"
        }
    }
```
And in Azure Identity: `DefaultAzureCredential(logging_enable=True)`.

However, the logs are not giving out any interesting extras:

```
No environment configuration found.
ManagedIdentityCredential will use App Service managed identity
Connecting to Azure Key Vault <kv-instance>
EnvironmentCredential.get_token failed: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
DefaultAzureCredential - EnvironmentCredential is unavailable
Request URL: 'http://169.254.129.3:8081/msi/token?api-version=REDACTED&resource=REDACTED'
Request method: 'GET'
Request headers:
'secret': 'REDACTED'
'User-Agent': 'azsdk-python-identity/1.5.0 Python/3.6.13 (Linux-4.15.0-135-generic-x86_64-with-debian-10.8)'
No body was attached to the request
AppServiceCredential.get_token failed: maximum recursion depth exceeded
ManagedIdentityCredential.get_token failed: maximum recursion depth exceeded
DefaultAzureCredential.get_token failed: ManagedIdentityCredential raised unexpected error "maximum recursion depth exceeded"
DefaultAzureCredential failed to retrieve a token from the included credentials. Attempted credentials: EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured. ManagedIdentityCredential: maximum recursion depth exceeded
Result: Failure Exception: ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials. Attempted credentials: EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured. ManagedIdentityCredential: maximum recursion depth exceeded Stack: File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/dispatcher.py", line 357, in _handle__invocation_request self.__run_sync_func, invocation_id, fi.func, args) File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run result = self.fn(*self.args, **self.kwargs) File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/dispatcher.py", line 542, in __run_sync_func return func(**params) File "/home/site/wwwroot/AmiRequest/__init__.py", line 89, in main user=kv_handler.get_secret(os.environ["<secret-name>"]), File "/home/site/wwwroot/utils/kv_utils.py", line 44, in get_secret return self.client.get_secret(secret).value File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer return func(*args, **kwargs) File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/keyvault/secrets/_client.py", line 72, in get_secret **kwargs File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/keyvault/secrets/_generated/_operations_mixin.py", line 1475, in get_secret return mixin_instance.get_secret(vault_base_url, secret_name, secret_version, **kwargs) File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/keyvault/secrets/_generated/v7_1/operations/_key_vault_client_operations.py", line 276, in get_secret pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs) File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 211, in run return first_node.send(pipeline_request) # type: ignore File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send response = self.next.send(request) File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send response = self.next.send(request) File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send response = self.next.send(request) [Previous line repeated 2 more times] File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send response = self.next.send(request) File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/core/pipeline/policies/_retry.py", line 435, in send response = self.next.send(request) File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/keyvault/secrets/_shared/challenge_auth_policy.py", line 111, in send self._handle_challenge(request, challenge) File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/keyvault/secrets/_shared/challenge_auth_policy.py", line 137, in _handle_challenge self._token = self._credential.get_token(scope) File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/identity/_credentials/default.py", line 144, in get_token return super(DefaultAzureCredential, self).get_token(*scopes, **kwargs) File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/identity/_credentials/chained.py", line 90, in get_token raise ClientAuthenticationError(message=message)
```

Please, let me know if I am messing the debug config, and I'll force the error again.

Thanks,
Pere

**Comment by chlowell** [comment]
I don't know all the details of Azure Functions integration with `logging`. Your log output looks like it's just info level, so perhaps the host.json setting doesn't apply to all loggers. In my repro app I explicitly enabled debug logging for the library (which [configures the credential to include exception info](https://github.com/Azure/azure-sdk-for-python/blob/873435f4bd7b749f9c87b07442b96ba42ccfaf90/sdk/identity/azure-identity/azure/identity/_credentials/chained.py#L83)):
```py
import logging
import azure.functions as func
from azure.identity import ChainedTokenCredential

class FailCredential:
    def get_token(self, *args, **kwargs):
        self.get_token(*args, **kwargs)

def main(req: func.HttpRequest) -> func.HttpResponse:
    logger = logging.getLogger('azure.identity')
    logger.setLevel(logging.DEBUG)

    credential = ChainedTokenCredential(FailCredential())

    try:
        credential.get_token('https://vault.azure.net/.default')
        response = "it worked?"
    except Exception as ex:
        response = str(ex)

    return func.HttpResponse(response)
```

Running that function gets me a Warning message in Application Insights that includes a traceback:
```
ChainedTokenCredential.get_token failed: FailCredential raised unexpected error "maximum recursion depth exceeded"
Traceback (most recent call last):
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/identity/_credentials/chained.py", line 67, in get_token
    token = credential.get_token(*scopes, **kwargs)
  File "/home/site/wwwroot/HttpTrigger/__init__.py", line 7, in get_token
    self.get_token(*args, **kwargs)
  File "/home/site/wwwroot/HttpTrigger/__init__.py", line 7, in get_token
    self.get_token(*args, **kwargs)
  File "/home/site/wwwroot/HttpTrigger/__init__.py", line 7, in get_token
    self.get_token(*args, **kwargs)
  [Previous line repeated 325 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by pmbrull** [comment]
Hi @chlowell,

Thanks for the snippet! Setting the logger as you suggested worked wonders.

Let me add here the new piece of logging I found which allows us to trace a bit better the internal calls:

```
AppServiceCredential.get_token failed:
maximum recursion depth exceeded in comparison Traceback (most recent call last): 
File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/identity/_internal/get_token_mixin.py", line 70, in get_token token = self._request_token(*scopes) 
File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/identity/_credentials/app_service.py", line 46, in _request_token return self._client.request_token(*scopes, **kwargs) 
File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/identity/_internal/managed_identity_client.py", line 72, in request_token response = self._pipeline.run(request) 
File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 211, in run return first_node.send(pipeline_request) # type: ignore 
File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send response = self.next.send(request) 
File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send response = self.next.send(request) 
File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/core/pipeline/policies/_retry.py", line 435, in send response = self.next.send(request) 
File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send response = self.next.send(request) 
File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send response = self.next.send(request) 
File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send response = self.next.send(request) 
File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 103, in send self._sender.send(request.http_request, **request.context.options), 
File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 246, in send **kwargs) 
File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/opencensus/ext/requests/trace.py", line 194, in wrap_session_request result = wrapped(*args, **kwargs) 
File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/opencensus/ext/requests/trace.py", line 194, in wrap_session_request result = wrapped(*args, **kwargs) 
File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/opencensus/ext/requests/trace.py", line 194, in wrap_session_request result = wrapped(*args, **kwargs) [Previous line repeated 301 more times] 
File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/requests/sessions.py", line 516, in request prep = self.prepare_request(req) 
File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/requests/sessions.py", line 459, in prepare_request hooks=merge_hooks(request.hooks, self.hooks), 
File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/requests/models.py", line 315, in prepare self.prepare_headers(headers) 
File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/requests/models.py", line 445, in prepare_headers self.headers = CaseInsensitiveDict() 
File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/requests/structures.py", line 46, in __init__ self.update(data, **kwargs) 
File "/usr/local/lib/python3.6/_collections_abc.py", line 839, in update if isinstance(other, Mapping): 
File "/usr/local/lib/python3.6/abc.py", line 184, in __instancecheck__ if subclass in cls._abc_cache: 
File "/usr/local/lib/python3.6/_weakrefset.py", line 75, in __contains__ return wr in self.data RecursionError: maximum recursion depth exceeded in comparison
```

Also, we've been working with Azure Support Engineers and by caching the secrets as global vars, we mitigated this error. So this is not top critical now :)

In case this happens to anyone else:

```python
CACHED_DATA = None

def main(req):
    global CACHED_DATA
    if CACHED_DATA is None:
        CACHED_DATA = load_json()

    # ... use CACHED_DATA in code
```

Thanks,
Pere

**Comment by rakshith91** [comment]
> It looks like the issue origins in the `opencensus` tracing.

Hi @pmbrull  - Would you be able to check if the recursion is still occurring without opencensus? I don't see which part of OC exporter would cause a recursion.

we are not able to reproduce the issue on our end

**Comment by lzchen** [comment]
@pmbrull 
Can you try removing the `tracer =` line? Just leave the `config_integration` line for `requests` and see if the issue is reproducible.

**Comment by pmbrull** [comment]
Hi @lzchen, I reached out to the people with access to the codebase and looks like this has been refactored so we cannot test it anymore.

I guess we can close this issue for now.

Thanks!
