### ISSUE TITLE
Custom Vision Service Api Won't install

### ISSUE THREAD

**Issue by aribornstein** [Azure/azure-sdk-for-python#1781]
```

(C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35) C:\local>pip install "git+https://github.com/Azure/azure-sdk-for-python#egg=azure-cognitiveservices-vision-customvision&subDirectory=azure-cognitiveservices-vision-customvision"
Collecting azure-cognitiveservices-vision-customvision from git+https://github.com/Azure/azure-sdk-for-python#egg=azure-cognitiveservices-vision-customvision&subDirectory=azure-cognitiveservices-vision-customvision
  Cloning https://github.com/Azure/azure-sdk-for-python to c:\users\ari-ra~1\appdata\local\temp\pip-build-7xsm397o\azure-cognitiveservices-vision-customvision
    Complete output from command python setup.py egg_info:
    Start  C:\Users\ARI-RA~1\AppData\Local\Temp\pip-build-7xsm397o\azure-cognitiveservices-vision-customvision\azure-nspkg\setup.py
    running egg_info
    error: error in 'egg_base' option: 'pip-egg-info' does not exist or is not a directory

    ----------------------------------------
Exception:
Traceback (most recent call last):
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\pip\commands\install.py", line 310, in run
    wb.build(autobuilding=True)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\pip\wheel.py", line 750, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\pip\req\req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\pip\req\req_set.py", line 601, in _prepare_file
    abstract_dist.prep_for_dist()
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\pip\req\req_set.py", line 127, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\pip\req\req_install.py", line 425, in run_egg_info
    command_desc='python setup.py egg_info')
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\pip\utils\__init__.py", line 718, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in C:\Users\ARI-RA~1\AppData\Local\Temp\pip-build-7xsm397o\azure-cognitiveservices-vision-customvision\

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\pip\commands\install.py", line 350, in run
    requirement_set.cleanup_files()
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\pip\utils\build.py", line 38, in __exit__
    self.cleanup()
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\pip\utils\build.py", line 42, in cleanup
    rmtree(self.name)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\pip\_vendor\six.py", line 686, in reraise
    raise value
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\shutil.py", line 488, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\shutil.py", line 378, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\shutil.py", line 378, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\shutil.py", line 378, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\shutil.py", line 378, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\shutil.py", line 378, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\shutil.py", line 378, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\shutil.py", line 378, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\shutil.py", line 383, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\pip\utils\__init__.py", line 110, in rmtree_errorhandler
    if os.stat(path).st_mode & stat.S_IREAD:
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\ARI-RA~1\\AppData\\Local\\Temp\\pip-build-7xsm397o\\azure-cognitiveservices-vision-customvision\\azure-cognitiveservices-vision-contentmoderator\\azure\\cognitiveservices\\vision\\contentmoderator\\models\\create_video_reviews_body_item_video_frames_item_metadata_item.py'
You are using pip version 8.1.2, however version 9.0.1 is available.``
```

**Comment by lmazuel** [comment]
That's not SDK issue, you need to enable long path for git:
`git config --system core.longpaths true`

https://stackoverflow.com/a/26111092/4074838

**Comment by aribornstein** [comment]
I did run that command. This is error you what get after resolving that issue. I believe it is because git allows you to clone the directory but the file name is still too long for the windows file system. 

In order to get the code to run I had to clone to my c drive and manually pip install locally.

I can reproduce on more than one machine so it is worth looking into. 

The culprit seems to be two issues

1)one file with absurdly long non pep8 compliant name. I'd recommend renaming that file in the repo.

2) the egg redirect seems to be broken so this pip install command pulls the entire azure python sdk

**Comment by lmazuel** [comment]
Ok, if git is ok, then you need Python 3.6 and Longpath support on Windows:
https://docs.python.org/3/using/windows.html#removing-the-max-path-limitation

1- I don't see why you think this filename is not pep8 compliant? pep8 is about max characters, not long filename.
2- With a pip install from git, pip is clone the entire repo. I don't think there is something we can do about this (or it's pip enhancement).
