### ISSUE TITLE
[BUG][azure-mgmt-cognitiveservices] AttributeError: 'ServicePrincipalCredentials' object has no attribute 'get_token'

### ISSUE THREAD

**Issue by fsharpn00b** [Azure/azure-sdk-for-python#17919]
- **Package Name**: 
msrestazure, azure-mgmt-cognitiveservices

- **Package Version**: 
msrestazure==0.6.4
azure-mgmt-cognitiveservices==11.0.0

- **Operating System**:
Windows 10 Enterprise 20H2

- **Python Version**: 
3.9.1

**Describe the bug**
I am unable to list or create resources with the Azure Management for Cognitive Services library.

**To Reproduce**
1. Run the following code:
```python
from msrestazure.azure_active_directory import ServicePrincipalCredentials
from azure.mgmt.cognitiveservices import CognitiveServicesManagementClient
from azure.mgmt.cognitiveservices.models import CognitiveServicesAccount, Sku

service_principal_application_id = "PASTE_YOUR_SERVICE_PRINCIPAL_APP_ID_HERE"
service_principal_secret = "PASTE_YOUR_SERVICE_PRINCIPAL_SECRET_HERE"
subscription_id = "PASTE_YOUR_AZURE_SUBSCRIPTION_ID_HERE"
tenant_id = "PASTE_YOUR_TENANT_ID_HERE"
resource_group_name = "PASTE_YOUR_RESOURCE_GROUP_NAME_HERE"

credentials = ServicePrincipalCredentials(service_principal_application_id, service_principal_secret, tenant=tenant_id)
client = CognitiveServicesManagementClient(credentials, subscription_id)

print("Resources in resource group: " + resource_group_name)
for x in client.accounts.list_by_resource_group(resource_group_name) :
	print(x)
	print()
```

Output:
```
Resources in resource group: jawe
Traceback (most recent call last):
  File "C:\Users\<user>\Documents\Work\backup\ms_work\quickstarts_20190604\ARM_Python\bug_report.txt", line 15, in <module>
    for x in client.accounts.list_by_resource_group(resource_group_name) :
  File "C:\Program Files\Python\Lib\site-packages\azure\core\paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "C:\Program Files\Python\Lib\site-packages\azure\core\paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "C:\Program Files\Python\Lib\site-packages\azure\mgmt\cognitiveservices\operations\_accounts_operations.py", line 370, in get_next
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "C:\Program Files\Python\Lib\site-packages\azure\core\pipeline\_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "C:\Program Files\Python\Lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "C:\Program Files\Python\Lib\site-packages\azure\mgmt\core\policies\_base.py", line 47, in send
    response = self.next.send(request)
  File "C:\Program Files\Python\Lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "C:\Program Files\Python\Lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "C:\Program Files\Python\Lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "C:\Program Files\Python\Lib\site-packages\azure\core\pipeline\policies\_redirect.py", line 158, in send
    response = self.next.send(request)
  File "C:\Program Files\Python\Lib\site-packages\azure\core\pipeline\policies\_retry.py", line 445, in send
    response = self.next.send(request)
  File "C:\Program Files\Python\Lib\site-packages\azure\core\pipeline\_base.py", line 69, in send
    _await_result(self._policy.on_request, request)
  File "C:\Program Files\Python\Lib\site-packages\azure\core\pipeline\_tools.py", line 29, in await_result
    result = func(*args, **kwargs)
  File "C:\Program Files\Python\Lib\site-packages\azure\core\pipeline\policies\_authentication.py", line 93, in on_request
    self._token = self._credential.get_token(*self._scopes)
AttributeError: 'ServicePrincipalCredentials' object has no attribute 'get_token'
```

Indeed, the ServicePrincipalCredentials class has 'set_token' but no 'get_token':
https://github.com/Azure/msrestazure-for-python/blob/8849f398b6ebd4607de63c2f5d1318f44ec1d822/msrestazure/azure_active_directory.py#L328

**Expected behavior**
The code above should output a list of resources in my resource group.
I have verified that my service principal credentials, etc. work correctly using Azure Management for Cognitive Services in the Azure SDK for JS.

**Additional context**
If I should file this against Azure /msrestazure-for-python instead, just let me know.

**Comment by chlowell** [comment]
azure-mgmt-cognitiveservices 11.0 expects a credential from azure-identity, whose ClientSecretCredential is the equivalent of msrestazure.azure_active_directory.ServicePrincipalCredentials. It takes the same information but its parameters are slightly different:

```py
from azure.identity import ClientSecretCredential
from azure.mgmt.cognitiveservices import CognitiveServicesManagementClient

credential = ClientSecretCredential(tenant_id, service_principal_application_id, service_principal_secret)
client = CognitiveServicesManagementClient(credential, subscription_id)
```

(Related: #14919, #16908, #16923)

**Comment by fsharpn00b** [comment]
@chlowell Wonderful, I am now able to create/list/delete resources again. I will update our sample accordingly. Thank you!
