### ISSUE TITLE
BlobService sync execution

### ISSUE THREAD

**Issue by frankShih** [Azure/azure-sdk-for-python#17933]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.5.0
- **Operating System**: WIN 10
- **Python Version**: 3.7.3

**Describe the bug**
The BlobClient does not run as expected. I try to download a file from blob storage and append new records to it, then upload the file.

```
from azure.storage.blob import BlobServiceClient, BlobClient, ContainerClient, __version__
from datetime import datetime
import pandas as pd

result={}
result['uid'] = None
result['source'] = None
result['req_time'] = None
result['pred_val'] = None
result['real_val'] = None
result['elasped_time(ms)']=None
result_df = pd.DataFrame(result, index=[0])

root_path='.'
file_name = '_records.csv'
remote_path = f'prediction/{datetime.today().strftime("%Y-%m")}/{file_name}'
local_path = f'{root_path}/{file_name}'
blob_client = blob_service_client.get_blob_client(container=container_name, blob=remote_path)
if blob_client.exists():
    with open(local_path, "wb") as fd:
        fd.write(blob_client.download_blob().readall())
    df = pd.read_csv(local_path)
    result_df = pd.concat([df, result_df])

result_df.to_csv(local_path, index=False)
with open(local_path, "rb") as fd:
    blob_client.upload_blob(fd, overwrite=True)
```

But an error occurred:
```
Traceback (most recent call last):
  File ".\az_storage.py", line 93, in <module>
    result_df.to_csv(local_path, index=False)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\generic.py", line 3403, in to_csv
    storage_options=storage_options,
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\io\formats\format.py", line 1083, in to_csv
    csv_formatter.save()
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\io\formats\csvs.py", line 234, in save
    storage_options=self.storage_options,
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\io\common.py", line 647, in get_handle
    newline="",
OSError: [Errno 22] Invalid argument: './_records.csv'
```

**To Reproduce**
Every time when there is no "_record.csv" on the local machine, it fails.
It seems that `to_csv()` is executed before `fd.write(blob_client.download_blob().readall())` is completed?

**Expected behavior**
I assume that the code should be sync.

---
Any suggestion is appreciated. If there is a better way to achieve this, please tell me.
Thanks in prior.

**Comment by kristapratico** [comment]
Thanks for the feedback, we'll investigate asap.

**Comment by frankShih** [comment]
[Update]

If I write my code in this way, everything is fine:
```
blob_client = blob_service_client.get_blob_client(container=CONTAINER_NAME, blob=remote_path)
if blob_client.exists():
    df = pd.read_csv(BytesIO(blob_client.download_blob().readall()))
    print(df.shape)
    result_df = pd.concat([df, result_df])

print(result_df.shape)
stream=BytesIO()
result_df.to_csv(stream, index=False)
blob_client = blob_service_client.get_blob_client(container=CONTAINER_NAME, blob=remote_path)
blob_client.upload_blob(stream.getvalue(), overwrite=True)
```

So, maybe the root cause is 'saving the file to local'?

**Comment by tasherif-msft** [comment]
Hi @frankShih, `readall()` is blocking until all is downloaded. I believe the issue you encountered might have to do with path naming. But I can assure you that the operation is sync/blocking until complete.

Let me know if you have any further questions.

**Comment by frankShih** [comment]
Got it, thanks for your reply.
