### ISSUE TITLE
azure-blob-storage throw DeserializationError  

### ISSUE THREAD

**Issue by gdippolito** [Azure/azure-sdk-for-python#18600]
- **Package Name**: azure-storage-blob
- **Package Version**:  12.8.1
- **Operating System**: Ubuntu 18.04
- **Python Version**: 3.7.9

**Describe the bug**
Occasionally an exception is thrown while fetching a blob from a storage container. 

**To Reproduce**
1. Fetch blob using async blob client
2. An exception is thrown (quite rarely)

**Expected behavior**
Exception should be handled and the blob image should be re-fetched.

**Additional context**
Stack trace:
```
ERROR 2021-05-08 04:52:38,236 image_storage.training_image_storage load_image status=error, duration_ms=11.299999999999999
Traceback (most recent call last):
  File "/app/binary.runfiles/image_storage/training_image_storage.py", line 124, in load_image
    image = self._hot_storage.load_image(run_id, self._camera_position, image_timestamp_us)
  File "/app/binary.runfiles/image_storage/azure_image_storage.py", line 200, in load_image
    return self._get_shard(image_timestamp_us).load_image(run_id, camera_position, image_timestamp_us)
  File "/app/binary.runfiles/image_storage/azure_image_storage.py", line 57, in load_image
    loop=self._get_or_create_event_loop(),
  File "/app/python_runtime/python3/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/app/python_runtime/python3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/app/binary.runfiles/image_storage/azure_image_storage.py", line 77, in _load_blob_async_into_byte_stream
    storage_stream_downloader = await blob_client.download_blob()
  File "/app/binary.runfiles/pip-services/pypi__azure_core/azure/core/tracing/decorator_async.py", line 74, in wrapper_use_tracer
    return await func(*args, **kwargs)
  File "/app/binary.runfiles/pip-services/pypi__azure_storage_blob/azure/storage/blob/aio/_blob_client_async.py", line 464, in download_blob
    await downloader._setup()  # pylint: disable=protected-access
  File "/app/binary.runfiles/pip-services/pypi__azure_storage_blob/azure/storage/blob/aio/_download_async.py", line 250, in _setup
    self._response = await self._initial_request()
  File "/app/binary.runfiles/pip-services/pypi__azure_storage_blob/azure/storage/blob/aio/_download_async.py", line 299, in _initial_request
    **self._request_options)
  File "/app/binary.runfiles/pip-services/pypi__azure_storage_blob/azure/storage/blob/_generated/aio/operations/_blob_operations.py", line 179, in download
    error = self._deserialize(_models.StorageError, response)
  File "/app/binary.runfiles/pip-services/pypi__msrest/msrest/serialization.py", line 1367, in __call__
    data = self._unpack_content(response_data, content_type)
  File "/app/binary.runfiles/pip-services/pypi__msrest/msrest/serialization.py", line 1541, in _unpack_content
    raw_data.headers
  File "/app/binary.runfiles/pip-services/pypi__msrest/msrest/pipeline/universal.py", line 226, in deserialize_from_http_generics
    return cls.deserialize_from_text(body_bytes, content_type)
  File "/app/binary.runfiles/pip-services/pypi__msrest/msrest/pipeline/universal.py", line 203, in deserialize_from_text
    raise DeserializationError("Cannot deserialize content-type: {}".format(content_type))
msrest.exceptions.DeserializationError: Cannot deserialize content-type: text/html
```

**Comment by xiafu-msft** [comment]
Hi @gdippolito
Thanks for reaching out.
Is that blob a static website? since usually the content-type is not text/html.

**Comment by gdippolito** [comment]
hi @xiafu-msft,

We are only storing images in this storage account. 

I think somehow the wrong response was sent back to the client. Is it possible that a different return code from 200 was not properly handled and the html was parsed?

**Comment by xiafu-msft** [comment]
Hi @gdippolito 

Can you call get_blob_properties() on the blob which throws error message and send me all of the result of get_blob_properties() call.
Thanks so much for your help!

**Comment by gdippolito** [comment]
HI @xiafu-msft, 

I'm not able to reproduce this problem since it only happen very sporadically. 

Since I have reported this problem I didn't experience it since. 

I believe something went wrong while performing this specific request. 

Let me know if you need anything else from me.
