### ISSUE TITLE
async blob client download_blob error: 'NoneType' object has no attribute 'request'

### ISSUE THREAD

**Issue by michael1011101** [Azure/azure-sdk-for-python#19033]
- **azure.storage.blob.aio**: 
- **12.8.1**: 
- **Linux**:
- **3.8.5**: 

**Describe the bug**
Get one new BlobClient to download blob by using azure.storage.blob.aio. And want to download a set of blobs in asynchronous manner with a precreated ContainerClient. Then the asynchronous performance is not ideal.

**To Reproduce**
```
class MyClass(object):

    def __init__(self, account_name, account_key, container_name):
        self.account_name = account_name
        self.account_key = account_key
        self.container_name = container_name
        self.container_client = self._get_container_client()
    
    def _get_container_client(self):
        account_url = AZURE_ACCOUNT_URL_FORMAT.format(account_name=self.account_name)
        return ContainerClient(account_url = account_url,
                            container_name = self.container_name, 
                            credential = self.account_key)

    async def list_item(self, name_starts_with="", delimiter="/", item_type=(BlobPrefix,)):
        item_list = []
        async with self.container_client as client:
            async for item in client.walk_blobs(name_starts_with=name_starts_with, delimiter = delimiter):
                if isinstance(item, item_type):
                    item_list.append(item)
        return item_list

    async def read_file(self, filepath):
        blob_client = self.container_client.get_blob_client(filepath) 
        try:
            downloader = await blob_client.download_blob()
            return await downloader.readall()
        except ResourceNotFoundError:
            return None
    
    async def fetch_all_files(self):
        dir_list = await self.list_item(delimiter="/", item_type=(BlobPrefix,))
        
        path_formatted = "{folder}/dummy_file"
        filepath = [ path_formatted.format(folder=dir.name.strip("/")) for dir in dir_list ]
        print(filepath)

        task_list = [self.read_file(path) for path in filepath]
        done, _ = await asyncio.wait(task_list)
        return done

async def main():
    azure_class = MyClass(account_name=ACCOUNT_NAME, account_key=ACCOUNT_KEY, container_name=CONTAINER_NAME)

    print( await azure_class.fetch_all_files() )

if __name__ == "__main__":
    asyncio.run( main() )
```
python run logs
```
> python azure_test.py 
['folder1/dummy_file', 'folder2/dummy_file']
{<Task finished name='Task-4' coro=<MyClass.read_file() done, defined at azure_test.py:40> exception=AttributeError("'NoneType' object has no attribute 'request'")>, <Task finished name='Task-5' coro=<MyClass.read_file() done, defined at azure_test.py:40> exception=AttributeError("'NoneType' object has no attribute 'request'")>}
Task exception was never retrieved
future: <Task finished name='Task-4' coro=<MyClass.read_file() done, defined at azure_test.py:40> exception=AttributeError("'NoneType' object has no attribute 'request'")>
Traceback (most recent call last):
  File "azure_test.py", line 43, in read_file
    downloader = await blob_client.download_blob()
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/core/tracing/decorator_async.py", line 74, in wrapper_use_tracer
    return await func(*args, **kwargs)
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/storage/blob/aio/_blob_client_async.py", line 464, in download_blob
    await downloader._setup()  # pylint: disable=protected-access
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/storage/blob/aio/_download_async.py", line 250, in _setup
    self._response = await self._initial_request()
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/storage/blob/aio/_download_async.py", line 293, in _initial_request
    location_mode, response = await self._clients.blob.download(
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/storage/blob/_generated/aio/operations/_blob_operations.py", line 174, in download
    pipeline_response = await self._client._pipeline.run(request, stream=True, **kwargs)
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 215, in run
    return await first_node.send(pipeline_request)
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  [Previous line repeated 5 more times]
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect_async.py", line 64, in send
    response = await self.next.send(request)
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/storage/blob/_shared/policies_async.py", line 99, in send
    response = await self.next.send(request)
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/storage/blob/_shared/policies_async.py", line 56, in send
    response = await self.next.send(request)
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 116, in send
    await self._sender.send(request.http_request, **request.context.options),
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/storage/blob/_shared/base_client_async.py", line 180, in send
    return await self._transport.send(request, **kwargs)
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/core/pipeline/transport/_aiohttp.py", line 184, in send
    result = await self.session.request(    # type: ignore
AttributeError: 'NoneType' object has no attribute 'request'
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<MyClass.read_file() done, defined at azure_test.py:40> exception=AttributeError("'NoneType' object has no attribute 'request'")>
Traceback (most recent call last):
  File "azure_test.py", line 43, in read_file
    downloader = await blob_client.download_blob()
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/core/tracing/decorator_async.py", line 74, in wrapper_use_tracer
    return await func(*args, **kwargs)
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/storage/blob/aio/_blob_client_async.py", line 464, in download_blob
    await downloader._setup()  # pylint: disable=protected-access
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/storage/blob/aio/_download_async.py", line 250, in _setup
    self._response = await self._initial_request()
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/storage/blob/aio/_download_async.py", line 293, in _initial_request
    location_mode, response = await self._clients.blob.download(
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/storage/blob/_generated/aio/operations/_blob_operations.py", line 174, in download
    pipeline_response = await self._client._pipeline.run(request, stream=True, **kwargs)
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 215, in run
    return await first_node.send(pipeline_request)
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  [Previous line repeated 5 more times]
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect_async.py", line 64, in send
    response = await self.next.send(request)
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/storage/blob/_shared/policies_async.py", line 99, in send
    response = await self.next.send(request)
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/storage/blob/_shared/policies_async.py", line 56, in send
    response = await self.next.send(request)
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 116, in send
    await self._sender.send(request.http_request, **request.context.options),
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/storage/blob/_shared/base_client_async.py", line 180, in send
    return await self._transport.send(request, **kwargs)
  File "/home/myname/tools/miniconda3/envs/exporter/lib/python3.8/site-packages/azure/core/pipeline/transport/_aiohttp.py", line 184, in send
    result = await self.session.request(    # type: ignore
AttributeError: 'NoneType' object has no attribute 'request'
```

**Expected behavior**
Asynchronous download should be able to work successfully.
And except that asynchronous method should be able to outperform synchronous download for a set of blobs.

**Additional context**
There are two blobs in storage container: `folder1/dummy_file` and `folder2/dummy_file`.

**Comment by annatisch** [comment]
Thanks @michael1011101!
Adding @xiafu-msft and @tasherif-msft from the Storage team to help take a look.

I believe you could expect to see this error if the client had been "closed".
For example, if I call `container_client.get_blob_client()` - the resulting blob client is sharing a connection with the parent container client. Therefore, if the `async with` statement is exited for the container, the blob clients will also be closed.

**Comment by michael1011101** [comment]
> Therefore, if the `async with` statement is exited for the container, the blob clients will also be closed.

I'm not very clear about that. So does it mean that it cannot use container client with `async with` statement?

**Comment by tasherif-msft** [comment]
Hi @michael1011101 I believe the issue here has to do with `async with self.container_client as client:` 
This context manager will close the session object created for your client instance. i.e, you'd have to reinstantiate or avoid using a context manager if you're planning to use this client in multiple places and only close it in the final call.

Let me know if this helps

**Comment by michael1011101** [comment]
> I believe the issue here has to do with async with self.container_client as client

Correct. I remove the line of `async with self.container_client as client` and it works for me.
Then there are two lines of the logs that confuse me.
```
...
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f08b7a6ddf0>
Unclosed connector
...
```
Does it mean that I need to close the client session and connector manually? Could you give me an example?

**Comment by tasherif-msft** [comment]
Hi @michael1011101, yes there is an unclosed connection once you remove the context manager because you wouldn't have closed the connection.
You're either going to have to improve your logic so that you use your context manager at a better location. Or manually `.open()` and `.close()` appropriately.
At the moment you're using `self.container_client` closing it then attempting to reuse its connection later on, hence your issue.

**Comment by michael1011101** [comment]
Hi @tasherif-msft ,
> You're either going to have to improve your logic so that you use your context manager at a better location. 
I am use these codes for the first time. So you means a better location, could you give me an example? or help me to find the better place.

**Comment by amishra-dev** [comment]
@michael1011101 Tamer is asking you to refactor your code, we cannot help you with that as it can depend on a host of other factors that we do not have visibility into.
