### ISSUE TITLE
azure.mgmt.storage.v2015_06_15.operations.list does not work

### ISSUE THREAD

**Issue by jpoizat** [Azure/azure-sdk-for-python#1914]
Hello,

I'm trying to use the storage_accounts.list function on azure.mgmt.storage.StorageManagementClient.
when iterating over the StorageAccountPaged Iterator, I get the following :

```
Traceback (most recent call last):
  File "start_azure_sync.py", line 108, in <module>
    main()
  File "start_azure_sync.py", line 72, in main
    storage_account_list = collector.export_storage_accounts()
  File "/home/jpt/itop_azure_sync/lib/azurecollector.py", line 141, in export_storage_accounts
    azure_type=azuretemplates.STORAGE_ACCOUNT)
  File "/home/jpt/itop_azure_sync/lib/azurecollector.py", line 88, in export_resource
    azure_type=azure_type, group=group.id))
  File "/home/jpt/itop_azure_sync/lib/azurecollector.py", line 67, in export_list
    for azure_object in azure_list:
  File "/usr/local/lib/python3.5/dist-packages/msrest/paging.py", line 109, in __next__
    self.advance_page()
  File "/usr/local/lib/python3.5/dist-packages/msrest/paging.py", line 95, in advance_page
    self._response = self._get_next(self.next_link)
  File "/usr/local/lib/python3.5/dist-packages/azure/mgmt/storage/v2016_12_01/operations/storage_accounts_operations.py", line 448, in internal_paging
    header_parameters.update(custom_headers)
```

**Comment by jpoizat** [comment]
Found out I was using list instead of list_by_resource_group... sorry about that.

**Comment by lmazuel** [comment]
no problem :)
