### ISSUE TITLE
SDK Usage in unittests end up in azure.core.exceptions.ClientAuthenticationError:uthentication failed: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by AlexHiesch** [Azure/azure-sdk-for-python#19264]
- **Package Name & Version**: 

azure-common                    1.1.26
azure-core                      1.10.0
azure-datalake-store            0.0.51
azure-identity                  1.5.0
azure-storage-blob              12.7.1
azure-storage-file-datalake     12.2.2

- **Operating System**:
MAC OSX 11.4 Big Sur

- **Python Version**: 
3.8.4, 3.9.4

**Describe the bug**
The intention is here simply to write a unittest that asserts if files are present in a given ADLS path

1. Authenticate and get a token with Service Principal and Azure Python SDK
2. with the token create a file system client
3. retrieve the content of a given ADLS filepath
4. assert that the content is not empty (returned length of list is > 0)

Either through pytest or unittests it always ends up in:
`azure.core.exceptions.ClientAuthenticationError:uthentication failed: maximum recursion depth exceeded while calling a Python object`

**To Reproduce**

Just execute either unittest variants:
pytest version:
```python
from azure.core._match_conditions import MatchConditions
from azure.datalake.store import lib
from azure.identity import ClientSecretCredential
from azure.storage.filedatalake import DataLakeServiceClient
from azure.storage.filedatalake._models import ContentSettings
import pytest
import os
import logging
import logging.config

AppAdlsName= "please-replace-this"
AppAdlsFs= "please-replace-this"
AppAdlsContainer= "please-replace-this"
AppAdlsSpId= "please-replace-this"
AppAdlsSpSecret= "please-replace-this"
AppAdlsSpTenant= "please-replace-this"


logger = logging.getLogger('azure.identity')
logger.setLevel(logging.DEBUG)

class Test_Reader:

    def test_data_availability(self, getContent):

        contents = []
        
        paths = getContent
        
        for path in paths:
            path_qualifier = path.name.split("/")
            if len(path_qualifier) == 1 and path_qualifier[0].startswith(""):
                print(path_qualifier[0])
                contents.append(path_qualifier[0])
        assert len(contents) > 0


@pytest.fixture
def authenticate():
    account_url = "{}://{}.dfs.core.windows.net".format("https", AppAdlsName)
    my_credential = ClientSecretCredential(AppAdlsSpTenant, AppAdlsSpId, AppAdlsSpSecret)
    service_client = DataLakeServiceClient(account_url=account_url, credential=my_credential)
    file_system_client = service_client.get_file_system_client(file_system=AppAdlsContainer)
    return file_system_client

@pytest.fixture
def getContent(authenticate):
    file_system_client = authenticate
    content = file_system_client.get_paths("/")
    return content
```

unittest version:
```python
from azure.core._match_conditions import MatchConditions
from azure.datalake.store import lib
from azure.identity import ClientSecretCredential
from azure.storage.filedatalake import DataLakeServiceClient
from azure.storage.filedatalake._models import ContentSettings
import pytest
import os
import logging

AppAdlsName= "please-replace-this"
AppAdlsFs= "please-replace-this"
AppAdlsContainer= "please-replace-this"
AppAdlsSpId= "please-replace-this"
AppAdlsSpSecret= "please-replace-this"
AppAdlsSpTenant= "please-replace-this"

import unittest

class TestStringMethods(unittest.TestCase):

    def test_upper(self):
        logger = logging.getLogger('azure.identity')
        logger.setLevel(logging.DEBUG)
        account_url = "{}://{}.dfs.core.windows.net".format("https", AppAdlsName)
        my_credential = ClientSecretCredential(AppAdlsSpTenant, AppAdlsSpId, AppAdlsSpSecret)
        service_client = DataLakeServiceClient(account_url=account_url, credential=my_credential)
        file_system_client = service_client.get_file_system_client(file_system=AppAdlsContainer)
        content = file_system_client.get_paths("/")

        contents = []
        
        paths = content
        
        for path in paths:
            path_qualifier = path.name.split("/")
            if len(path_qualifier) == 1 and path_qualifier[0].startswith(""):
                print(path_qualifier[0])
                contents.append(path_qualifier[0])

        self.assertGreater(len(contents),0)

if __name__ == '__main__':
    unittest.main()
```

**Expected behavior**
Unittests running fine without recursion isuses and test passes

**Screenshots**
N/A

**Additional context**
Here's the full trace:
`The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/azure/identity/_internal/get_token_mixin.py", line 67, in get_token
    token = self._acquire_token_silently(*scopes)
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/azure/identity/_internal/decorators.py", line 50, in wrapper
    raise_from(auth_error, ex)
  File "<string>", line 3, in raise_from
azure.core.exceptions.ClientAuthenticationError: Authentication failed: maximum recursion depth exceeded while calling a Python object
WARNING  azure.identity._internal.get_token_mixin:get_token_mixin.py:81 ClientSecretCredential.get_token failed: Authentication failed: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/azure/identity/_internal/decorators.py", line 45, in wrapper
    return fn(*args, **kwargs)
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/azure/identity/_internal/client_credential_base.py", line 36, in _acquire_token_silently
    app = self._get_app()
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/azure/identity/_internal/client_credential_base.py", line 58, in _get_app
    self._msal_app = self._create_app(msal.ConfidentialClientApplication)
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/azure/identity/_internal/msal_credentials.py", line 62, in _create_app
    app = cls(
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/msal/application.py", line 238, in __init__
    self.authority = Authority(
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/msal/authority.py", line 83, in __init__
    openid_config = tenant_discovery(
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/msal/authority.py", line 142, in tenant_discovery
    resp = http_client.get(tenant_discovery_endpoint, **kwargs)
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/azure/identity/_internal/msal_client.py", line 105, in get
    response = self._pipeline.run(request)
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry.py", line 435, in send
    response = self.next.send(request)
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 103, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 260, in send
    response = self.session.request(  # type: ignore
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/urllib3/connection.py", line 392, in connect
    self.ssl_context = create_urllib3_context(
  File "/Users/hiescha/Code/frontend/venv2/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 303, in create_urllib3_context
    context.options |= options
  File "/Users/hiescha/.pyenv/versions/3.8.4/lib/python3.8/ssl.py", line 602, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/Users/hiescha/.pyenv/versions/3.8.4/lib/python3.8/ssl.py", line 602, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/Users/hiescha/.pyenv/versions/3.8.4/lib/python3.8/ssl.py", line 602, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 449 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object`

**Comment by chlowell** [comment]
Thanks for opening this issue. I haven't seen this error before but after some searching I see it's often caused by monkeypatching `ssl` (see e.g. https://github.com/psf/requests/issues/3752#issuecomment-294603631 and https://github.com/benoitc/gunicorn/issues/1566#issuecomment-364710908). Do you know of anything in your environment that might patch networking libraries?

Also, do you see this error outside of unit tests? For example, when simply authenticating:
```py
credential = ClientSecretCredential(AppAdlsSpTenant, AppAdlsSpId, AppAdlsSpSecret)
credential.get_token("https://storage.azure.com/.default")
```

**Comment by AlexHiesch** [comment]
thanks @chlowell for the quick response.

the pytest warnings summary is indeed mentioning something about monkey patch and this referred issue:
https://github.com/gevent/gevent/issues/1016

I tried to reorder the imports, having gevent and monkey first, patching it but unfortunately without any success.

In other github issues there's even a curious goerge edition of this patch: https://github.com/spyoungtech/grequests/issues/97

I have no clue what's going on here. And yes, running your snippet with the credential works fine in case it's executed by the python binary but as soon as you initate it via pytest or python -m pytest you will end up with the recursion issue.



```

================================================================================================================= warnings summary =================================================================================================================
venv/lib/python3.9/site-packages/grequests.py:22
  /Users/hiescha/Code/frontend/venv/lib/python3.9/site-packages/grequests.py:22: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.util.ssl_ (/Users/hiescha/Code/frontend/venv/lib/python3.9/site-packages/urllib3/util/ssl_.py)', 'urllib3.util (/Users/hiescha/Code/frontend/venv/lib/python3.9/site-packages/urllib3/util/__init__.py)']. 
    curious_george.patch_all(thread=False, select=False)

venv/lib/python3.9/site-packages/gevent/monkey.py:1037
  /Users/hiescha/Code/frontend/venv/lib/python3.9/site-packages/gevent/monkey.py:1037: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.util.ssl_ (/Users/hiescha/Code/frontend/venv/lib/python3.9/site-packages/urllib3/util/ssl_.py)', 'urllib3.util (/Users/hiescha/Code/frontend/venv/lib/python3.9/site-packages/urllib3/util/__init__.py)']. 
    _queue_warning(

-- Docs: https://docs.pytest.org/en/stable/warnings.html

```

**Comment by chlowell** [comment]
Then it seems your test environment loads grequests which in turn loads gevent, which patches ssl, and the fix would be to ensure this happens before requests imports ssl. I don't have a clue either, I can only speak to (parts of) the Azure SDK. Maybe you could apply the patch earlier in the test run lifecycle, e.g. in pytest's conftest.py?
