### ISSUE TITLE
VisualStudioCodeCredential fails with invalid_grant due to expired refresh token

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#19509]
Traceback looks like this:
```
VisualStudioCodeCredential.get_token failed: Azure Active Directory error '(invalid_grant) AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2021-03-10T02:17:41.9328984Z and was inactive for 90.00:00:00.
Trace ID: d3242419-68cc-4186-b7d6-472a1b9d7700
Correlation ID: 82cfdcde-ed8e-4f59-b859-603927a48c2c
Timestamp: 2021-06-21 16:56:07Z'
Traceback (most recent call last):
  File "identity\azure-identity\azure\identity\_credentials\vscode.py", line 138, in get_token
    return super(VisualStudioCodeCredential, self).get_token(*scopes, **kwargs)
  File "identity\azure-identity\azure\identity\_internal\get_token_mixin.py", line 72, in get_token
    token = self._request_token(*scopes)
  File "identity\azure-identity\azure\identity\_credentials\vscode.py", line 149, in _request_token
    return self._client.obtain_token_by_refresh_token(scopes, refresh_token, **kwargs)
  File "identity\azure-identity\azure\identity\_internal\aad_client.py", line 62, in obtain_token_by_refresh_token
    return self._process_response(response, now)
  File "identity\azure-identity\azure\identity\_internal\aad_client_base.py", line 119, in _process_response
    _raise_for_error(response, content)
  File "identity\azure-identity\azure\identity\_internal\aad_client_base.py", line 248, in _raise_for_error
    raise ClientAuthenticationError(message=message, response=response.http_response)
azure.core.exceptions.ClientAuthenticationError: Azure Active Directory error '(invalid_grant) AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2021-03-10T02:17:41.9328984Z and was inactive for 90.00:00:00.
Trace ID: d3242419-68cc-4186-b7d6-472a1b9d7700
Correlation ID: 82cfdcde-ed8e-4f59-b859-603927a48c2c
Timestamp: 2021-06-21 16:56:07Z'
```
This happens because the credential redeems the refresh token stored by VS Code's Azure extension for access tokens but doesn't update that refresh token when Azure AD returns a new one alongside an access token. Presumably, the Azure extension does update its refresh token. So someone who relies on VisualStudioCodeCredential but doesn't actively use the extension may eventually see this error.

**Comment by xiangyan99** [comment]
The new azure account extension broke the vscode credential.

Close this one because it is tracked in another one.
