### ISSUE TITLE
[Event Hubs & AMQP Python] Receive performance analysis

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#19796]
Link credit:
- 300 (default) vs 5000 vs 20000 (extreme large value)
  - validate link credit is working first

Message:
- large (e.g. over 100kb per message) vs small (100b per message)

Partition:
- single vs all

Event Hub:
- basic tier vs premium tier
- through put unit 1 vs max allowed

Threading:
- single vs multiple

Resource region:
- vm/eh source in same region (e.g. both in US) vs in remote region (e.g. one in Europe and the other in US)

**Comment by swathipil** [comment]
error when receiving messages of size `16`:
```
EventProcessor instance 'c6ce75d5-4989-4a04-bb63-c404cf5cc7dd' of eventhub 'swathip-test-eventhub' partition '0' consumer group '$Default'. An error occurred while receiving. The exception is TypeError('isinstance() arg 2 must be a type or tuple of types',).
Traceback (most recent call last):
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/_consumer.py", line 223, in receive
    max_batch_size=max_batch_size
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/pyamqp/client.py", line 635, in receive_message_batch
    receiving = self.do_work(batch=max_batch_size)
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/pyamqp/client.py", line 283, in do_work
    return self._client_run(**kwargs)
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/pyamqp/client.py", line 569, in _client_run
    self._connection.listen(wait=self._socket_timeout, **kwargs)
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/pyamqp/_connection.py", line 553, in listen
    new_frame = self._read_frame(wait=wait, **kwargs)
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/pyamqp/_connection.py", line 183, in _read_frame
    return self._transport.receive_frame(**kwargs)
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/pyamqp/_transport.py", line 410, in receive_frame
    header, channel, payload = self.read(**kwargs)
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/pyamqp/_transport.py", line 363, in read
    read_frame_buffer.write(read(8, buffer=frame_header, initial=True))
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/pyamqp/_transport.py", line 535, in _read
    nbytes = self.sock.recv_into(view[length:])
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/_eventprocessor/event_processor.py", line 331, in _do_receive
    consumer.receive(self._batch, self._max_batch_size, self._max_wait_time)
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/_consumer.py", line 232, in receive
    isinstance(exception, errors.LinkErrorCondition.DetachForced)
TypeError: isinstance() arg 2 must be a type or tuple of types

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sync_receive.py", line 97, in <module>
    test_receive_fixed_amount()
  File "sync_receive.py", line 83, in test_receive_fixed_amount
    starting_position="-1"
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/_consumer_client.py", line 413, in receive
    self._receive(on_event, batch=False, max_batch_size=1, **kwargs)
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/_consumer_client.py", line 328, in _receive
    event_processor.start()
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/_eventprocessor/event_processor.py", line 367, in start
    self._do_receive(partition_id, consumer)
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/_eventprocessor/event_processor.py", line 344, in _do_receive
    partition_id, consumer, CloseReason.OWNERSHIP_LOST
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/_eventprocessor/event_processor.py", line 295, in _close_consumer
    consumer.close()
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/_client_base.py", line 584, in close
    self._close_handler()
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/_client_base.py", line 530, in _close_handler
    self._handler.close()  # close the link (sharing connection) or connection (not sharing)
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/pyamqp/client.py", line 231, in close
    self._link.detach(close=True)
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/pyamqp/link.py", line 242, in detach
    self._outgoing_detach(close=close, error=error)
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/pyamqp/link.py", line 206, in _outgoing_detach
    self._session._outgoing_detach(detach_frame)
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/pyamqp/session.py", line 297, in _outgoing_detach
    self._connection._process_outgoing_frame(self.channel, frame)
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/pyamqp/_connection.py", line 479, in _process_outgoing_frame
    self._send_frame(channel, frame)
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/pyamqp/_connection.py", line 211, in _send_frame
    self._transport.send_frame(channel, frame, **kwargs)
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/pyamqp/_transport.py", line 428, in send_frame
    self.write(data)
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/pyamqp/_transport.py", line 400, in write
    self._write(s)
  File "/home/swathip/test-env36/lib/python3.6/site-packages/azure/eventhub/pyamqp/_transport.py", line 563, in _write
    n = write(s)
  File "/usr/lib/python3.6/ssl.py", line 944, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by rakshith91** [comment]
https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/_layouts/OneNote.aspx?id=%2Fteams%2FAzureDeveloperExperience%2FShared%20Documents%2FLanguage%20-%20Python%2FAzure%20SDK%20-%20Language%20-%20Python&wd=target%28Services.one%7C7EDF4D8F-3CF7-4200-BCD2-567D6A7E429C%2FSync%20Receive%20-%20perf%20test%7CE3DFCB05-9B3B-4675-A0FF-008F133DC5BD%2F%29
onenote:https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/Shared%20Documents/Language%20-%20Python/Azure%20SDK%20-%20Language%20-%20Python/Services.one#Sync%20Receive%20-%20perf%20test&section-id={7EDF4D8F-3CF7-4200-BCD2-567D6A7E429C}&page-id={E3DFCB05-9B3B-4675-A0FF-008F133DC5BD}&end
