### ISSUE TITLE
Role assignment creation fails

### ISSUE THREAD

**Issue by frrossms** [Azure/azure-sdk-for-python#20054]
- **Package Name**: azure-mgmt-authorization
- **Package Version**: 1.0.0
- **Operating System**: Linux (Ubuntu 20.04 under WSL)
- **Python Version**: 3.8.10

**Describe the bug**

Creating a role assignment with the SDK is sending an incorrect HTTP request body. Instead of sending something of the form

```
{
   ...
   "properties": { ... }
}
```

the value of `properties` is being sent as the top-level object in the request body.

**To Reproduce**

Create a resource group, and then run

```
from azure.identity import DefaultAzureCredential
from azure.mgmt.authorization import AuthorizationManagementClient
from uuid import uuid4

CREDENTIAL = DefaultAzureCredential()
SUBSCRIPTION_ID = "<put in your subscription>"

auth_client = AuthorizationManagementClient(CREDENTIAL, SUBSCRIPTION_ID)
auth_client.role_assignments.create(
    "<resource group name>",
    uuid4(),
    {  # This grants CosmosDB Network contributor privileges
        'role_definition_id': '4d97b98b-1d4f-4787-a291-c67834d212e7',
        'principal_id': 'a232010e-820c-4083-83bb-3ace5fc29d0b',
    }
)
```

This results in:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/frross/.local/lib/python3.8/site-packages/azure/mgmt/authorization/v2015_07_01/operations/_role_assignments_operations.py", line 331, in create
    body_content = self._serialize.body(parameters, 'RoleAssignmentCreateParameters')
  File "/home/frross/.local/lib/python3.8/site-packages/msrest/serialization.py", line 628, in body        
    raise errors[0]
  File "/home/frross/.local/lib/python3.8/site-packages/msrest/serialization.py", line 250, in validate    
    Serializer.validate(value, debug_name, **self._validation.get(attr_name, {}))
  File "/home/frross/.local/lib/python3.8/site-packages/msrest/serialization.py", line 730, in validate    
    raise ValidationError("required", name, True)
msrest.exceptions.ValidationError: Parameter 'RoleAssignmentCreateParameters.properties' can not be None. 
```

**Expected behavior**
A successful response saying that the role has been assigned.

**Additional context**
I suspect this is the same problem that we hit with azure-cosmosdb last week where upgrade to the SDK's infrastructure had broken the module. I can be reached internally as frross.

**Comment by BigCat20196** [comment]
hi @frrossms , Thanks for the feedback !

We prefer to call the model in the model to fill in the parameters. suah as:
```
from azure.mgmt.authorization.v2018_09_01_preview import models as authorization_model

auth_client.role_assignments.create(
    GROUP_NAME,
    role_name,
    authorization_model.RoleAssignmentCreateParameters(
        role_definition_id='4d97b98b-1d4f-4787-a291-c67834d212e7',
        principal_id='a232010e-820c-4083-83bb-3ace5fc29d0b'
    )
)
```

If you prefer JSON format, please follow the example below:
```
auth_client.role_assignments.create(
    GROUP_NAME,
    role_name,
    {  # This grants CosmosDB Network contributor privileges
        'properties': {
            'roleDefinitionId': '4d97b98b-1d4f-4787-a291-c67834d212e7',
            'principalId': 'a232010e-820c-4083-83bb-3ace5fc29d0b',
        }
    }
)

```

Hope this unblocks you

**Comment by frrossms** [comment]
Ah, it's not flattened in the Swagger definition. Got it.
________________________________
