### ISSUE TITLE
azure-mgmt-batch==16.0.0 Error creating pool with user assigned identity. azure.core.exceptions.HttpResponseError: (InvalidQueryParameterValue)

### ISSUE THREAD

**Issue by natbprice** [Azure/azure-sdk-for-python#20220]
- **Package Name**: azure-mgmt-batch
- **Package Version**: 16.0.0
- **Operating System**: Microsoft Windows 10 Enterprise
- **Python Version**: 3.9.0

**Describe the bug**
Unable to create pool with user assigned identity.

```
Traceback (most recent call last):
  File "c:\AzureDevOps\ModelingBatchJobs\run_batch_job\test_script.py", line 72, in <module>
    batch_client.pool.create(
  File "C:\AzureDevOps\ModelingBatchJobs\run_batch_job\.venv\lib\site-packages\azure\mgmt\batch\operations\_pool_operations.py", line 228, in create
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (InvalidQueryParameterValue) {'lang': 'en-US', 'value': 'Value for one of the query parameters specified in the request URI is invalid.\nRequestId:5dc602a7-3128-457e-a9b2-df14dcc0a455\nTime:2021-08-10T20:45:19.1463551Z'}
Code: InvalidQueryParameterValue
Message: {'lang': 'en-US', 'value': 'Value for one of the query parameters specified in the request URI is invalid.\nRequestId:5dc602a7-3128-457e-a9b2-df14dcc0a455\nTime:2021-08-10T20:45:19.1463551Z'}
```

**To Reproduce**
1. Create a batch account
2. Create a managed identity
3. Attempt to create a pool using user assigned managed identity
```
import azure.mgmt.batch as az_batch
import azure.mgmt.batch.models as az_batch_models
from azure.identity import DefaultAzureCredential

subscription_id = 'subscription_id'
batch_url = 'url'
identity_arm = 'identity_arm'
account_name = 'account'
rg_name = 'resource_group'
        
# Credentials
credentials = DefaultAzureCredential(exclude_shared_token_cache_credential=True)

# Batch client
batch_client = az_batch.BatchManagementClient(
    credential=credentials,
    subscription_id=subscription_id,
    base_url=batch_url
)
# # azure-mgmt-batch==15.0.0
# batch_client = az_batch.BatchManagement(
#     credential=credentials,
#     subscription_id=subscription_id
# )

vm_cfg = az_batch_models.VirtualMachineConfiguration(
    image_reference=az_batch_models.ImageReference(
        publisher='MicrosoftWindowsServer', 
        offer='WindowsServer', 
        version='latest',
        sku='2019-Datacenter-Core-smalldisk'
    ),
    node_agent_sku_id='batch.node.windows amd64'
)

pool = az_batch_models.Pool(
    # # azure-mgmt-batch==15.0.0
    # identity=az_batch_models.BatchPoolIdentity(
    #     type=az_batch_models.PoolIdentityType.USER_ASSIGNED,
    #     user_assigned_identities={
    #         identity_arm: az_batch_models.Components81XseeSchemasBatchpoolidentityPropertiesUserassignedidentitiesAdditionalproperties()
    #     },
    # ),
    identity=az_batch_models.BatchPoolIdentity(
        type=az_batch_models.PoolIdentityType.USER_ASSIGNED,
        user_assigned_identities={
            identity_arm: az_batch_models.UserAssignedIdentities()
        },
    ),
    display_name='managedidentitytest',
    vm_size='STANDARD_D1_V2',
    deployment_configuration=az_batch_models.DeploymentConfiguration(
        virtual_machine_configuration=vm_cfg,
    ),
    scale_settings=az_batch_models.ScaleSettings(
        fixed_scale=az_batch_models.FixedScaleSettings(
            target_dedicated_nodes=1,
            target_low_priority_nodes=0
        )
    ),
    task_slots_per_node=1,
    start_task=None,
)

# Batch client
batch_client.pool.create(
    resource_group_name=rg_name,
    account_name=account_name,
    pool_name='managedidentitytest',
    parameters=pool
)
```

**Expected behavior**
Pool with managed identity is created successfully.

**Additional context**
Documentation for azure.mgmt.batch.models.BatchPoolIdentity is unclear. What value should we use for the string component in the dictionary for argument `user_assigned_identities`? Documentation from package version 15.0.0 previously stated: 

"The user identity dictionary key references will be ARM resource ids in the form:     '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identityName}'"

**Comment by swathipil** [comment]
@natbprice thanks for opening the issue! Routing this to the correct people.

**Comment by RAY-316** [comment]
hi @natbprice I think  `user_assigned_identities` in `azure-mgmt-batch==15.0.0` in your sample seems unclear. Can you continue to provide parameters as 15.0.0 because it seems no changes about `identities` in 16.0.0
![image](https://user-images.githubusercontent.com/59104634/129675666-5091d6ed-2151-4b9c-97ef-b589b744905b.png)

**Comment by natbprice** [comment]
@RAY-316 Using your example I receive the following error:

```
AttributeError: module 'azure.mgmt.batch.models' has no attribute 'Components81XseeSchemasBatchpoolidentityPropertiesUserassignedidentitiesAdditionalproperties'
```

In my original example, I was following the [BatchPoolIdentity Class documentation](https://docs.microsoft.com/en-us/python/api/azure-mgmt-batch/azure.mgmt.batch.models.batchpoolidentity?view=azure-python) where it seems to indicate I should now use `UserAssignedIdentities()`.

**Comment by natbprice** [comment]
@RAY-316 Let me know if you need anything else from me to reproduce this bug. 

**Relevant change in docs:**
[16.0.0 docs azure.mgmt.batch.models.BatchPoolIdentity](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-batch/16.0.0/azure.mgmt.batch.models.html#azure.mgmt.batch.models.BatchPoolIdentity)
[15.0.0 docs azure.mgmt.batch.models.BatchPoolIdentity](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-batch/15.0.0/azure.mgmt.batch.models.html#azure.mgmt.batch.models.BatchPoolIdentity)

**Removed class**
[15.0.0 azure.mgmt.batch.models.Components81XseeSchemasBatchpoolidentityPropertiesUserassignedidentitiesAdditionalproperties](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-batch/15.0.0/azure.mgmt.batch.models.html#azure.mgmt.batch.models.Components81XseeSchemasBatchpoolidentityPropertiesUserassignedidentitiesAdditionalproperties)

**Comment by natbprice** [comment]
@swathipil @RAY-316 I am following up on this ticket to see if you have been able to reproduce this issue or if you need anything else from me. Thanks

**Comment by swathipil** [comment]
@natbprice - thanks for your patience on this! I let @RAY-316 know that you have responded, so hopefully they should get back to you ASAP!

**Comment by RAY-316** [comment]
hi @natbprice I think 'user_assigned_identities' should be defined like this:
```
user_assigned_identities={
            f'/subscriptions/{subscription_id}/resourceGroups/default-azurebatch-japaneast/providers/'
            f'Microsoft.ManagedIdentity/userAssignedIdentities/{id1}': az_batch_models.UserAssignedIdentities()
        }
```
Here is my basis:https://github.com/Azure/azure-rest-api-specs/blob/main/specification/batch/resource-manager/Microsoft.Batch/stable/2021-06-01/examples/PoolCreate_UserAssignedIdentities.json#L32

**Comment by natbprice** [comment]
Hi @RAY-316, sorry somehow I missed this GitHub notification that you replied. 

I believe I am defining the user identity correctly. It works with `
azure-mgmt-batch==15.0.0`. Here is a full example:

```
import azure.mgmt.batch as az_batch
import azure.mgmt.batch.models as az_batch_models
from azure.identity import DefaultAzureCredential

subscription_id = 'myid'
account_name = 'smecoami'
region = 'eastus2'
batch_url = f'https://{account_name}.{region}.batch.azure.com'
rg_name = 'AMI'
identity_name = 'myidentity'
identity_id = f'/subscriptions/{subscription_id}/resourceGroups/{rg_name}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identity_name}'
        
# Credentials
credentials = DefaultAzureCredential(exclude_shared_token_cache_credential=True)

# Batch client
batch_client = az_batch.BatchManagementClient(
    credential=credentials,
    subscription_id=subscription_id,
    base_url=batch_url
)
# # azure-mgmt-batch==15.0.0
# batch_client = az_batch.BatchManagement(
#     credential=credentials,
#     subscription_id=subscription_id
# )

vm_cfg = az_batch_models.VirtualMachineConfiguration(
    image_reference=az_batch_models.ImageReference(
        publisher='MicrosoftWindowsServer', 
        offer='WindowsServer', 
        version='latest',
        sku='2019-Datacenter-Core-smalldisk'
    ),
    node_agent_sku_id='batch.node.windows amd64'
)

pool = az_batch_models.Pool(
    # # azure-mgmt-batch==15.0.0
    # identity=az_batch_models.BatchPoolIdentity(
    #     type=az_batch_models.PoolIdentityType.USER_ASSIGNED,
    #     user_assigned_identities={
    #         identity_id: az_batch_models.Components81XseeSchemasBatchpoolidentityPropertiesUserassignedidentitiesAdditionalproperties()
    #     },
    # ),
    identity=az_batch_models.BatchPoolIdentity(
        type=az_batch_models.PoolIdentityType.USER_ASSIGNED,
        user_assigned_identities={
            identity_id: az_batch_models.UserAssignedIdentities()
        },
    ),
    display_name='managedidentitytest',
    vm_size='STANDARD_D1_V2',
    deployment_configuration=az_batch_models.DeploymentConfiguration(
        virtual_machine_configuration=vm_cfg,
    ),
    scale_settings=az_batch_models.ScaleSettings(
        fixed_scale=az_batch_models.FixedScaleSettings(
            target_dedicated_nodes=1,
            target_low_priority_nodes=0
        )
    ),
    task_slots_per_node=1,
    start_task=None,
)

# Batch client
batch_client.pool.create(
    resource_group_name=rg_name,
    account_name=account_name,
    pool_name='managedidentitytest',
    parameters=pool
)
```

**Comment by natbprice** [comment]
Hi @RAY-316, sorry somehow I missed this GitHub notification that you replied.

I believe I am defining the user identity correctly. It works with azure-mgmt-batch==15.0.0. Here is a full example:

```
import azure.mgmt.batch as az_batch
import azure.mgmt.batch.models as az_batch_models
from azure.identity import DefaultAzureCredential

subscription_id = 'myid'
account_name = 'myaccount'
region = 'eastus2'
batch_url = f'https://{account_name}.{region}.batch.azure.com'
rg_name = 'myrg'
identity_name = 'myidentity'
identity_id = f'/subscriptions/{subscription_id}/resourceGroups/{rg_name}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identity_name}'
        
# Credentials
credentials = DefaultAzureCredential(exclude_shared_token_cache_credential=True)

# Batch client
batch_client = az_batch.BatchManagementClient(
    credential=credentials,
    subscription_id=subscription_id,
    base_url=batch_url
)
# # azure-mgmt-batch==15.0.0
# batch_client = az_batch.BatchManagement(
#     credential=credentials,
#     subscription_id=subscription_id
# )

vm_cfg = az_batch_models.VirtualMachineConfiguration(
    image_reference=az_batch_models.ImageReference(
        publisher='MicrosoftWindowsServer', 
        offer='WindowsServer', 
        version='latest',
        sku='2019-Datacenter-Core-smalldisk'
    ),
    node_agent_sku_id='batch.node.windows amd64'
)

pool = az_batch_models.Pool(
    # # azure-mgmt-batch==15.0.0
    # identity=az_batch_models.BatchPoolIdentity(
    #     type=az_batch_models.PoolIdentityType.USER_ASSIGNED,
    #     user_assigned_identities={
    #         identity_id: az_batch_models.Components81XseeSchemasBatchpoolidentityPropertiesUserassignedidentitiesAdditionalproperties()
    #     },
    # ),
    identity=az_batch_models.BatchPoolIdentity(
        type=az_batch_models.PoolIdentityType.USER_ASSIGNED,
        user_assigned_identities={
            identity_id: az_batch_models.UserAssignedIdentities()
        },
    ),
    display_name='managedidentitytest',
    vm_size='STANDARD_D1_V2',
    deployment_configuration=az_batch_models.DeploymentConfiguration(
        virtual_machine_configuration=vm_cfg,
    ),
    scale_settings=az_batch_models.ScaleSettings(
        fixed_scale=az_batch_models.FixedScaleSettings(
            target_dedicated_nodes=1,
            target_low_priority_nodes=0
        )
    ),
    task_slots_per_node=1,
    start_task=None,
)

# Batch client
batch_client.pool.create(
    resource_group_name=rg_name,
    account_name=account_name,
    pool_name='managedidentitytest',
    parameters=pool
)
```

**Comment by natbprice** [comment]
@RAY-316 Please let me know if you are able to reproduce this issue using the example I provided in previous comment. Thanks!
