### ISSUE TITLE
azure-data-tables==12.1.0 Batch transaction fails if update mode is set for all transactions

### ISSUE THREAD

**Issue by natbprice** [Azure/azure-sdk-for-python#20247]
- **Package Name**: azure-data-tables
- **Package Version**: 12.1.0
- **Operating System**: Microsoft Windows 10 Enterprise
- **Python Version**: 3.9.0

**Describe the bug**
Batch transaction fails if update mode is set for all transactions.

```
Traceback (most recent call last):
  File "c:\AzureDevOps\ModelingBatchJobs\run_batch_job\test_batch_insert.py", line 21, in <module>
    table_client.submit_transaction(operations)
  File "C:\AzureDevOps\ModelingBatchJobs\run_batch_job\.venv\lib\site-packages\azure\data\tables\_table_client.py", line 731, in submit_transaction
    return self._batch_send(*batched_requests.requests, **kwargs)  # type: ignore
  File "C:\AzureDevOps\ModelingBatchJobs\run_batch_job\.venv\lib\site-packages\azure\data\tables\_base_client.py", line 295, in _batch_send
    parts = list(response.parts())
  File "C:\AzureDevOps\ModelingBatchJobs\run_batch_job\.venv\lib\site-packages\azure\core\pipeline\transport\_base.py", line 604, in parts
    responses = self._get_raw_parts()
  File "C:\AzureDevOps\ModelingBatchJobs\run_batch_job\.venv\lib\site-packages\azure\core\pipeline\transport\_base.py", line 561, in _get_raw_parts
    return self._decode_parts(message, http_response_type, requests)
  File "C:\AzureDevOps\ModelingBatchJobs\run_batch_job\.venv\lib\site-packages\azure\core\pipeline\transport\_base.py", line 533, in _decode_parts
    changeset_responses = self._decode_parts(raw_reponse, http_response_type, changeset_requests)
  File "C:\AzureDevOps\ModelingBatchJobs\run_batch_job\.venv\lib\site-packages\azure\core\pipeline\transport\_base.py", line 526, in _decode_parts
    requests[index],
IndexError: tuple index out of range
```

**To Reproduce**
1. Insert entities with update mode set

```
from azure.identity import DefaultAzureCredential
from azure.data.tables import TableServiceClient

account = "myaccount"
table = "mytable"

credential = DefaultAzureCredential(exclude_shared_token_cache_credential = True)
table_service = TableServiceClient(endpoint="https://{}.table.core.windows.net/".format(account), credential=credential)

table_client = table_service.create_table_if_not_exists(table_name=table)

entity1 = {"PartitionKey": "pk001", "RowKey": "rk001",
           "Value": 1, "day": "Monday", "float": 1.001}
entity2 = {"PartitionKey": "pk001", "RowKey": "rk002",
           "Value": 2, "day": "Tuesday", "float": 2.002}

operations = [
    ("upsert", entity1, {"mode": "merge"}),
    ("upsert", entity2, {"mode": "replace"})
]
table_client.submit_transaction(operations)
```

**Expected behavior**
Transactions are successfully completed without errors

**Comment by annatisch** [comment]
Thanks for the report @natbprice - this is very curious.
I will try to repro in a test ASAP.

**Comment by annatisch** [comment]
Thanks again @natbprice - this was a great catch!
The bug was that we were incorrectly comparing the `mode` value to the enum such that the string comparison would fail (using `is` instead of `==`).
I have opened a PR with a fix here: #20264 
Once that's merged, the fix will ship in the next release in September.
In the meantime, you can be unblocked by using the enum value instead of the string:
```python
from azure.data.tables import UpdateMode

operations = [
    ("upsert", entity1, {"mode": UpdateMode.MERGE}),
    ("upsert", entity2, {"mode": UpdateMode.REPLACE})
]
table_client.submit_transaction(operations)
```

**Comment by annatisch** [comment]
Unfortunately the release has been delayed from September into October - as another fix we are trying to ship is still undergoing some changes.
However the workaround above (using the enum rather than the string values) should work in the meantime.

**Comment by annatisch** [comment]
This bug fix has now been released :)
