### ISSUE TITLE
"Fatal error on SSL transport" when exiting python script

### ISSUE THREAD

**Issue by rjohnsonrxr** [Azure/azure-sdk-for-python#20482]
- **Package Name**: azure-eventhub-checkpointstoreblob-aio
- **Package Version**: 1.1.4
- **Operating System**: MacOs 10.15.7
- **Python Version**: 3.9.1

**Describe the bug**
Error is occurring after exiting python program : 

> Fatal error on SSL transport
> protocol: <asyncio.sslproto.SSLProtocol object at 0x7faedb601f70>
> transport: <_SelectorSocketTransport closing fd=22>
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 918, in write
>     n = self._sock.send(data)
> OSError: [Errno 9] Bad file descriptor

**To Reproduce**
Minimal repro : 
```
import asyncio
import time
import atexit

from azure.eventhub.aio import EventHubConsumerClient
from azure.eventhub.extensions.checkpointstoreblobaio import BlobCheckpointStore

def end_process():
    time.sleep(4)

atexit.register(end_process)

# note : fill in blob_account_url, container_name, credential here
checkpoint_store = BlobCheckpointStore(
        blob_account_url="", 
        container_name="",
        credential="")

# note : fill in endpoint
client = EventHubConsumerClient.from_connection_string("Endpoint=", consumer_group="$Default", checkpoint_store=checkpoint_store)

async def on_event_batch(partition_context, reports):
    print("processing events")
    await partition_context.update_checkpoint()

async def main():
    task = asyncio.ensure_future(
        client.receive_batch(
            on_event_batch=on_event_batch,
            starting_position=-1,
            max_wait_time=60,
            max_batch_size=200
        )
    )
    
    while(True):
        await asyncio.sleep(30)
        task.cancel()
        break;

async def close():
    await client.close()
    await checkpoint_store.close()

if __name__ == '__main__':
    try:
        asyncio.run(main())
        asyncio.run(close())

    except Exception as e:
        atexit._run_exitfuncs()
        raise(e)

    atexit._run_exitfuncs()

```

**Expected behavior**
Error should not occur

**Screenshots**

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by yunhaoling** [comment]
hey @rjohnsonrxr, I am able to reproduce the issue on windows which gave me more information on the error:
```
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x00000170FC06A608>
transport: <_SelectorSocketTransport closing fd=440>
Traceback (most recent call last):
  File "..\envs\env37\lib\asyncio\selector_events.py", line 870, in write
    n = self._sock.send(data)
OSError: [WinError 10038] An operation was attempted on something that is not a socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "..\envs\env37\lib\asyncio\sslproto.py", line 680, in _process_write_backlog
    self._transport.write(chunk)
  File "..\envs\env37\lib\asyncio\selector_events.py", line 874, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "..\envs\env37\lib\asyncio\selector_events.py", line 683, in _fatal_error
    self._force_close(exc)
  File "..\envs\env37\lib\asyncio\selector_events.py", line 695, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "..\envs\env37\lib\asyncio\base_events.py", line 691, in call_soon
    self._check_closed()
  File "..\envs\env37\lib\asyncio\base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

Process finished with exit code 0
```

according to the doc of [`asyncio.run`](https://docs.python.org/3/library/asyncio-task.html#asyncio.run):

> This function always creates a new event loop and closes it at the end. It should be used as a main entry point for asyncio programs, and should ideally only be called once.

So I think it's because the underlying ssl obj is hooked with one asyncio loop in the first `asyncio.run`, and the loop get closed after the running which leads to the second call find that the previous loop hooked with the ssl obj is already closed.


To bypass it, you could use the same loop to run those two method, so your code could be like:


```
if __name__ == '__main__':
    try:
        loop = asyncio.get_event_loop()
        loop.run_until_complete(main())  # same loop
        loop.run_until_complete(close())  # same loop
    except Exception as e:
        atexit._run_exitfuncs()
        raise(e)

    atexit._run_exitfuncs()
```

Please let me whether it works for you or you need any other help.
