### ISSUE TITLE
ManagedIdentityCredential fails DefaultAzureCredential on other cloud provider's compute instances

### ISSUE THREAD

**Issue by EpicWink** [Azure/azure-sdk-for-python#20554]
- **Package Name**: azure-identity
- **Package Version**: 1.6.1
- **Operating System**: Linux, Ubuntu 20.04 Focal
- **Python Version**: 3.8.10

**Describe the bug**
When using `azure.identity.DefaultAzureCredential` on another cloud provider's compute instance, when `http://169.254.169.254` is used by `azure.identity.ImdsCredential` (for `azure.identity.ManagedIdentityCredential`), the cloud provider responds with something `ImdsCredential` can't handle, which it then throws a `ClientAuthenticationError` which is indistinguishable from a true authentication failure.

**To Reproduce**
1. Start a basic HTTP server
   ```shell
   $ sudo python
   ```
   ```python
   >>> import werkzeug
   >>> @werkzeug.wrappers.Request.application
   ... def app(request):
   ...     return werkzeug.wrappers.Response(
   ...         "<html><body><p>spam</p></body></html>",
   ...         mimetype="text/html")
   >>> werkzeug.serving.run_simple("10.70.131.160", 80, app)
   ```
2. Forward address
   ```shell
   $ sudo iptables -t nat -A OUTPUT -d 169.254.169.254 -j DNAT --to-destination 10.70.131.160
   ```
3. Use `DefaultAzureCredential`
   ```python
   >>> import azure.identity
   >>> c = azure.identity.DefaultAzureCredential()
   >>> c.get_token("https://storage.azure.com/.default")
   ```

**Expected behavior**
`azure.identity.ManagedIdentityCredential` is soft-failed in the chain, allowing subsequent credential types to be tried.

**Actual behavior**
```
[ WARNING] azure.identity._internal.decorators: EnvironmentCredential.get_token failed: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Traceback (most recent call last):
  File "/media/linux-data/venvs/azauth/lib/python3.8/site-packages/azure/identity/_internal/decorators.py", line 27, in wrapper
    token = fn(*args, **kwargs)
  File "/media/linux-data/venvs/azauth/lib/python3.8/site-packages/azure/identity/_credentials/environment.py", line 115, in get_token
    raise CredentialUnavailableError(message=message)
azure.identity._exceptions.CredentialUnavailableError: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
[    INFO] azure.identity._credentials.chained: DefaultAzureCredential - EnvironmentCredential is unavailable
[    INFO] azure.core.pipeline.policies.http_logging_policy: Request URL: 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=REDACTED&resource=REDACTED'
[    INFO] azure.core.pipeline.policies.http_logging_policy: Request method: 'GET'
[    INFO] azure.core.pipeline.policies.http_logging_policy: Request headers:
[    INFO] azure.core.pipeline.policies.http_logging_policy:     'User-Agent': 'azsdk-python-identity/1.6.1 Python/3.8.10 (Linux-5.11.0-27-generic-x86_64-with-glibc2.29)'
[    INFO] azure.core.pipeline.policies.http_logging_policy: No body was attached to the request
[   DEBUG] urllib3.connectionpool: Starting new HTTP connection (1): 169.254.169.254:80
[   DEBUG] urllib3.connectionpool: http://169.254.169.254:80 "GET /metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://storage.azure.com HTTP/1.1" 200 37
[    INFO] azure.core.pipeline.policies.http_logging_policy: Response status: 200
[    INFO] azure.core.pipeline.policies.http_logging_policy: Response headers:
[    INFO] azure.core.pipeline.policies.http_logging_policy:     'Content-Type': 'text/html; charset=utf-8'
[    INFO] azure.core.pipeline.policies.http_logging_policy:     'Content-Length': '37'
[    INFO] azure.core.pipeline.policies.http_logging_policy:     'Server': 'Werkzeug/2.0.1 Python/3.8.10'
[    INFO] azure.core.pipeline.policies.http_logging_policy:     'Date': 'Mon, 06 Sep 2021 08:34:13 GMT'
[    INFO] azure.core.pipeline.policies.http_logging_policy: Request URL: 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=REDACTED&resource=REDACTED'
[    INFO] azure.core.pipeline.policies.http_logging_policy: Request method: 'GET'
[    INFO] azure.core.pipeline.policies.http_logging_policy: Request headers:
[    INFO] azure.core.pipeline.policies.http_logging_policy:     'Metadata': 'REDACTED'
[    INFO] azure.core.pipeline.policies.http_logging_policy:     'User-Agent': 'azsdk-python-identity/1.6.1 Python/3.8.10 (Linux-5.11.0-27-generic-x86_64-with-glibc2.29)'
[    INFO] azure.core.pipeline.policies.http_logging_policy: No body was attached to the request
[   DEBUG] urllib3.connectionpool: Resetting dropped connection: 169.254.169.254
[   DEBUG] urllib3.connectionpool: http://169.254.169.254:80 "GET /metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://storage.azure.com HTTP/1.1" 200 37
[    INFO] azure.core.pipeline.policies.http_logging_policy: Response status: 200
[    INFO] azure.core.pipeline.policies.http_logging_policy: Response headers:
[    INFO] azure.core.pipeline.policies.http_logging_policy:     'Content-Type': 'text/html; charset=utf-8'
[    INFO] azure.core.pipeline.policies.http_logging_policy:     'Content-Length': '37'
[    INFO] azure.core.pipeline.policies.http_logging_policy:     'Server': 'Werkzeug/2.0.1 Python/3.8.10'
[    INFO] azure.core.pipeline.policies.http_logging_policy:     'Date': 'Mon, 06 Sep 2021 08:34:13 GMT'
[ WARNING] azure.identity._internal.get_token_mixin: ImdsCredential.get_token failed: Unexpected content type "text/html; charset=utf-8"
Traceback (most recent call last):
  File "/media/linux-data/venvs/azauth/lib/python3.8/site-packages/azure/identity/_internal/get_token_mixin.py", line 72, in get_token
    token = self._request_token(*scopes)
  File "/media/linux-data/venvs/azauth/lib/python3.8/site-packages/azure/identity/_credentials/imds.py", line 93, in _request_token
    six.raise_from(ClientAuthenticationError(message=ex.message, response=ex.response), None)
  File "<string>", line 3, in raise_from
azure.core.exceptions.ClientAuthenticationError: Unexpected content type "text/html; charset=utf-8"
[ WARNING] azure.identity._internal.decorators: ManagedIdentityCredential.get_token failed: Unexpected content type "text/html; charset=utf-8"
Traceback (most recent call last):
  File "/media/linux-data/venvs/azauth/lib/python3.8/site-packages/azure/identity/_internal/decorators.py", line 27, in wrapper
    token = fn(*args, **kwargs)
  File "/media/linux-data/venvs/azauth/lib/python3.8/site-packages/azure/identity/_credentials/managed_identity.py", line 88, in get_token
    return self._credential.get_token(*scopes, **kwargs)
  File "/media/linux-data/venvs/azauth/lib/python3.8/site-packages/azure/identity/_internal/get_token_mixin.py", line 72, in get_token
    token = self._request_token(*scopes)
  File "/media/linux-data/venvs/azauth/lib/python3.8/site-packages/azure/identity/_credentials/imds.py", line 93, in _request_token
    six.raise_from(ClientAuthenticationError(message=ex.message, response=ex.response), None)
  File "<string>", line 3, in raise_from
azure.core.exceptions.ClientAuthenticationError: Unexpected content type "text/html; charset=utf-8"
[ WARNING] azure.identity._credentials.chained: DefaultAzureCredential.get_token failed: ManagedIdentityCredential raised unexpected error "Unexpected content type "text/html; charset=utf-8""
Traceback (most recent call last):
  File "/media/linux-data/venvs/azauth/lib/python3.8/site-packages/azure/identity/_credentials/chained.py", line 67, in get_token
    token = credential.get_token(*scopes, **kwargs)
  File "/media/linux-data/venvs/azauth/lib/python3.8/site-packages/azure/identity/_internal/decorators.py", line 27, in wrapper
    token = fn(*args, **kwargs)
  File "/media/linux-data/venvs/azauth/lib/python3.8/site-packages/azure/identity/_credentials/managed_identity.py", line 88, in get_token
    return self._credential.get_token(*scopes, **kwargs)
  File "/media/linux-data/venvs/azauth/lib/python3.8/site-packages/azure/identity/_internal/get_token_mixin.py", line 72, in get_token
    token = self._request_token(*scopes)
  File "/media/linux-data/venvs/azauth/lib/python3.8/site-packages/azure/identity/_credentials/imds.py", line 93, in _request_token
    six.raise_from(ClientAuthenticationError(message=ex.message, response=ex.response), None)
  File "<string>", line 3, in raise_from
azure.core.exceptions.ClientAuthenticationError: Unexpected content type "text/html; charset=utf-8"
[ WARNING] azure.identity._credentials.chained: DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
	ManagedIdentityCredential: Unexpected content type "text/html; charset=utf-8"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/linux-data/venvs/azauth/lib/python3.8/site-packages/azure/identity/_credentials/default.py", line 150, in get_token
    return super(DefaultAzureCredential, self).get_token(*scopes, **kwargs)
  File "/media/linux-data/venvs/azauth/lib/python3.8/site-packages/azure/identity/_credentials/chained.py", line 90, in get_token
    raise ClientAuthenticationError(message=message)
azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
	ManagedIdentityCredential: Unexpected content type "text/html; charset=utf-8"
```

**Workaround**
```python
import azure.identity

class ManagedIdentityCredential(azure.identity.ManagedIdentityCredential):
    def get_token(self, *scopes, **kwargs):
        try:
            return super().get_token(*scopes, **kwargs)
        except azure.core.exceptions.ClientAuthenticationError as e:
            if str(e).lower().startswith("unexpected"):
                raise azure.identity.CredentialUnavailableError(
                    f"[{e.__class__.__name__}] {e}"
                ) from e
            raise

credential = azure.identity.DefaultAzureCredential(
    exclude_managed_identity_credential=True,
)
credential.credentials += (ManagedIdentityCredential(),)
```

**Comment by chlowell** [comment]
Thanks for opening this issue. DefaultAzureCredential and ManagedIdentityCredential are designed for applications that deploy to Azure, so this isn't unexpected. I don't want to change ManagedIdentityCredential's error behavior in this scenario because I think doing so without breaking code deployed to Azure would require a fragile special case and unnecessarily complicate the implementation. I suggest working around this by either constructing a custom credential chain for your application (see the [readme](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/README.md#defining-a-custom-authentication-flow-with-chainedtokencredential)) or simply excluding managed identity from DefaultAzureCredential:
```py
DefaultAzureCredential(exclude_managed_identity_credential=True)
```

**Comment by EpicWink** [comment]
@chlowell could I suggest having `ImdsCredential` raise a subclass of `ClientAuthenticationError` so my workaround doesn't use fragile inspection of messages? This would be a 100% backwards-compatible change

**Comment by chlowell** [comment]
In your example the exception is `ClientAuthenticationError,` are you seeing something else in deployment? As I wrote above, there are simpler workarounds that don't involve inspecting error messages. Do these not work in your application?

**Comment by EpicWink** [comment]
`ClientAuthenticationError` is the error I am seeing in the current version. Disabling the managed-identity would mean I can't use makes identity credentials when my app is deployed to Azure

**Comment by chlowell** [comment]
That's true. How do you want to authenticate to Azure services when deployed to the other cloud?

**Comment by EpicWink** [comment]
We get a client credential from a secrets store. This is made transparent to users by a `TokenCredential` implementation we add to `DefaultAzureCredential`'s `credentials`.

**Comment by chlowell** [comment]
Modifying `DefaultAzureCredential.credentials` is fragile because its elements and their ordering may change between versions. I suggest moving away from `DefaultAzureCredential`. It's designed for simpler scenarios. You can create similar composite credentials with `ChainedTokenCredential` or, if it makes sense for your application, use configuration to choose a specific credential type.

**Comment by EpicWink** [comment]
Thanks for the advice, good idea. Is there any chance [`azure.identity._internal.managed_identity_client.ManagedIdentityClientBase._process_response`](https://github.com/Azure/azure-sdk-for-python/blob/f1d0d20b84fc2cfe0e7cfcfc0e5422e05f67ccbf/sdk/identity/azure-identity/azure/identity/_internal/managed_identity_client.py#L45-L85) could raise a specific subclass of `azure.core.exceptions.ClientAuthenticationError` (eg `UnexpectedAuthenticationResponse`) when it receives a response it can't handle? This would allow users of `azure.identity.ManagedIdentityCredential` to manually handle this scenario themselves, and would be a minor and backwards-compatible change. I'm happy to make the PR myself
