### ISSUE TITLE
BlobClient.upload_blob_from_url fails with InvalidBlockList

### ISSUE THREAD

**Issue by bmc-msft** [Azure/azure-sdk-for-python#20650]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.8.1
- **Operating System**: Ubuntu 18.04
- **Python Version**: 3.8.5

**Describe the bug**
Using an instance of `BlobClient`, I am uploading a large set of files via remote URLs to a storage account.  The files vary in size between 20KB and 600MB. 
 Roughly 1 in 1000 fail with an HttpResponseError exception with the error code of InvalidBlockList.

The code is effectively:

```python
service_client = BlobServiceClient.from_connection_string(connection_string)
container_client = service_client.get_container_client(container)
blob_client = container_client.get_blob_client(blob_path)
blob_client.upload_blob_from_url(url, overwrite=True, timeout=60*60*24)
```

```
Traceback (most recent call last):
  File "/home/user/project/.direnv/python-3.8.5/lib/python3.8/site-packages/azure/storage/blob/_blob_client.py", line 559, in upload_blob_from_url
    return self._client.block_blob.put_blob_from_url(**options)
  File "/home/user/project/.direnv/python-3.8.5/lib/python3.8/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 469, in put_blob_from_url
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'The specified block list is invalid.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "upload-files.py", line 33, in <module>
    main()
  File "upload-files.py", line 21, in main
    blob_client.upload_blob_from_url(entry.url, overwrite=True, timeout=60*60*24)
  File "/home/user/project/.direnv/python-3.8.5/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/user/project/.direnv/python-3.8.5/lib/python3.8/site-packages/azure/storage/blob/_blob_client.py", line 561, in upload_blob_from_url
    process_storage_error(error)
  File "/home/user/project/.direnv/python-3.8.5/lib/python3.8/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/user/project/.direnv/python-3.8.5/lib/python3.8/site-packages/azure/core/exceptions.py", line 247, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/user/project/.direnv/python-3.8.5/lib/python3.8/site-packages/azure/storage/blob/_blob_client.py", line 559, in upload_blob_from_url
    return self._client.block_blob.put_blob_from_url(**options)
  File "/home/user/project/.direnv/python-3.8.5/lib/python3.8/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 469, in put_blob_from_url
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: The specified block list is invalid.
RequestId:bf13c64a-d01e-0086-0c4e-a65bdf000000
Time:2021-09-10T14:21:30.6851450Z
ErrorCode:InvalidBlockList
Error:None
```

**To Reproduce**
1. Upload a large # of files from remote URLs using `upload_blob_from_url` of varying sizes.
 
**Expected behavior**
No exception generated.

**Comment by tasherif-msft** [comment]
Hi @bmc-msft could you provide me with a fresh failure/request-id so we can investigate it on our side

**Comment by bmc-msft** [comment]
Unfortunately not easily.  I will do my best to replicate it again in the near future.
