### ISSUE TITLE
Azure Python SDK Resource Graph crashes when trying to retrieve results

### ISSUE THREAD

**Issue by fabiansald** [Azure/azure-sdk-for-python#20748]
- **Package Name**: 
azure-mgmt-resourcegraph
- **Package Version**: 
8.0.0
- **Operating System**:
macOS 10.15.7
```
Darwin MCV7Q8MNHX 19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 22 19:49:55 PDT 2021; root:xnu-6153.141.35~1/RELEASE_X86_64 x86_64
```
- **Python Version**: 
```
Python 3.9.6 (default, Jun 29 2021, 06:20:32)
```
**Describe the bug**
Can't create Azure Resource Graph client:
```
File "/Users/fabi8483/src/python/kql/kmpoffice/.venv/lib/python3.9/site-packages/azure/common/credentials.py", line 72, in get_token
    _, token, fulltoken = credentials._token_retriever()  # pylint:disable=protected-access
```

**To Reproduce**
1. Install required packages:
packaging
msrestazure
azure-identity
azure-core
azure-mgmt-resourcegraph
azure-mgmt-resource
azure-cli-core
2. run the following script:
```
# Import Azure Resource Graph library
#import packaging
import azure.mgmt.resourcegraph as arg

# Import specific methods and models from other libraries
from azure.identity import AzureCliCredential
#from azure.common.credentials import get_azure_cli_credentials
from azure.common.client_factory import get_client_from_cli_profile
from azure.mgmt.resource import SubscriptionClient

# Wrap all the work in a function
def getresources( strQuery ):
    # Get your credentials from Azure CLI (development only!) and get your subscription list
    #subsClient = get_client_from_cli_profile(SubscriptionClient)
    print("\nGetting Azure Credential\n")
    credential = AzureCliCredential()
    print("\nGetting Azure Subscriptions\n")
    subsClient = SubscriptionClient(credential)
    subsRaw = []
    for sub in subsClient.subscriptions.list():
        print(f"\nSubscription: { sub }")
        subsRaw.append(sub.as_dict())
    subsList = []
    print("\nRetrieving subs id\n")
    for sub in subsRaw:
        subsList.append(sub.get('subscription_id'))

    # Create Azure Resource Graph client and set options
    print("\nCreating Azure Resource Graph Client\n")
    argClient = get_client_from_cli_profile(arg.ResourceGraphClient)
    argQueryOptions = arg.models.QueryRequestOptions(result_format="objectArray")

    print("\nCreating Query\n")
    # Create query
    argQuery = arg.models.QueryRequest(subscriptions=subsList, query=strQuery, options=argQueryOptions)

    print("\nGetting results:\n")
    # Run query
    argResults = argClient.resources(argQuery)

    # Show Python object
    print(argResults)

getresources("Resources | project name, type | limit 10")
```
3. Receive error message from line 40:
```
Traceback (most recent call last):
  File "/Users/fabi8483/src/python/kql/kmpoffice/./query.py", line 45, in <module>
    getresources("Resources | project name, type | limit 10")
  File "/Users/fabi8483/src/python/kql/kmpoffice/./query.py", line 40, in getresources
    argResults = argClient.resources(argQuery)
  File "/Users/fabi8483/src/python/kql/kmpoffice/.venv/lib/python3.9/site-packages/azure/mgmt/resourcegraph/operations/_resource_graph_client_operations.py", line 6
7, in resources
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/Users/fabi8483/src/python/kql/kmpoffice/.venv/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/Users/fabi8483/src/python/kql/kmpoffice/.venv/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/fabi8483/src/python/kql/kmpoffice/.venv/lib/python3.9/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/Users/fabi8483/src/python/kql/kmpoffice/.venv/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/fabi8483/src/python/kql/kmpoffice/.venv/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/fabi8483/src/python/kql/kmpoffice/.venv/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/Users/fabi8483/src/python/kql/kmpoffice/.venv/lib/python3.9/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/Users/fabi8483/src/python/kql/kmpoffice/.venv/lib/python3.9/site-packages/azure/core/pipeline/policies/_retry.py", line 445, in send
    response = self.next.send(request)
  File "/Users/fabi8483/src/python/kql/kmpoffice/.venv/lib/python3.9/site-packages/azure/core/pipeline/policies/_authentication.py", line 117, in send
    self.on_request(request)
  File "/Users/fabi8483/src/python/kql/kmpoffice/.venv/lib/python3.9/site-packages/azure/core/pipeline/policies/_authentication.py", line 94, in on_request
    self._token = self._credential.get_token(*self._scopes)
  File "/Users/fabi8483/src/python/kql/kmpoffice/.venv/lib/python3.9/site-packages/azure/common/credentials.py", line 72, in get_token
    _, token, fulltoken = credentials._token_retriever()  # pylint:disable=protected-access
TypeError: _retrieve_token() missing 1 required positional argument: 'token_resource'
```

**Expected behavior**
KQL query gets executed and shows results successfully 

**Screenshots**

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by BigCat20196** [comment]
Hi @fabiansald, Thanks for the feedback! 

After my investigation, It is not recommended to use the following code to create an `Azure Resource Graph Client`.

```
# Create Azure Resource Graph client and set options
    print("\nCreating Azure Resource Graph Client\n")
    argClient = get_client_from_cli_profile(arg.ResourceGraphClient)
    argQueryOptions = arg.models.QueryRequestOptions(result_format="objectArray")
``` 

You can try to replace it with the following code.
```
# Create Azure Resource Graph client and set options
    print("\nCreating Azure Resource Graph Client\n")
    argClient = arg.ResourceGraphClient(credential)
    argQueryOptions = arg.models.QueryRequestOptions(result_format="objectArray")
```

Please kindly let us know if it solves the issue.

**Comment by fabiansald** [comment]
Hi! Thanks! Checking

**Comment by fabiansald** [comment]
It worked! Thanks a lot!
