### ISSUE TITLE
Auth with `az login` doesn't work for `DefaultAzureCredential`

### ISSUE THREAD

**Issue by Qi77Qi** [Azure/azure-sdk-for-python#20826]
- **Package Name**: azure-identity
- **Package Version**: 1.6.1
- **Operating System**: Ubuntu 18.04.5 LTS
- **Python Version**: 3.6

**Describe the bug**
`DefaultAzureCredential` doesn't work with `az login` credential.

**To Reproduce**
1. Run `az login`
2. Run the following script

```
import os

from azure.identity import DefaultAzureCredential
from azure.storage.blob import BlobServiceClient

def get_service(storage_account_name: str):
    default_credential = DefaultAzureCredential(logging_enable=True)
    service = BlobServiceClient(account_url=f"https://{storage_account_name}.blob.core.windows.net/", credential=default_credential)
    return service

client = get_service(<some storage account>).get_blob_client(<some container>, <some blob name>)
with open(<some file>, "rb") as data:
    client.upload_blob(data)
```

**Expected behavior**
File is uploaded to azure storage successfully

**Screenshots**

**Additional context**
The user I'm using is granted storage contributor role in portal properly, but I still get the following error
```
using DefaultAzureCredential
EnvironmentCredential.get_token failed: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
ImdsCredential.get_token failed: ManagedIdentityCredential authentication unavailable, no managed identity endpoint found.
ManagedIdentityCredential.get_token failed: ManagedIdentityCredential authentication unavailable, no managed identity endpoint found.
SharedTokenCacheCredential.get_token failed: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/usr/local/lib/python3.9/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 230, in upload
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'This request is denied to perform this operation using this permission.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/qi/Documents/GitHub/terra-notebook-utils/tests/manual_azure_test.py", line 19, in <module>
    client.upload_blob(data)
  File "/usr/local/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/azure/storage/blob/_blob_client.py", line 693, in upload_blob
    return upload_block_blob(**options)
  File "/usr/local/lib/python3.9/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/usr/local/lib/python3.9/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/usr/local/lib/python3.9/site-packages/azure/core/exceptions.py", line 247, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/usr/local/lib/python3.9/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/usr/local/lib/python3.9/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 230, in upload
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: This request is denied to perform this operation using this permission.
RequestId:265ff602-e01e-0061-15b4-b37e0d000000
Time:2021-09-27T15:29:05.8007397Z
ErrorCode:AuthorizationPermissionDenied
Error:None
```

**Comment by xiangyan99** [comment]
Thanks for your feedback. 

Could you give us more information how you configured managed identity?

For more information, you can access https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/Troubleshoot.md#troubleshooting-managed-identity-authentication-issues

**Comment by Qi77Qi** [comment]
@xiangyan99 thanks for getting back to me. I initially ran into issue with managed identity, but after talking to support, that seems to be related to deny assignments in a managed resource group. So don't worry about managed identity anymore.

I revised this issue to just about having issue about auth with `az login`....The steps to produce is about the same except I'm doing `az login` instead of relying on managed identity for an azure vm

**Comment by xiangyan99** [comment]
It seems to me you got the token successfully but the token does not have right permission to perform the operation.

Could you double check the permissions?

And could you tell us which version of azure-identity library are you using?

Thank you.
