### ISSUE TITLE
_retrieve_token() missing 1 required positional argument: 'token_resource'

### ISSUE THREAD

**Issue by frank-lsf** [Azure/azure-sdk-for-python#21313]
- **Package Name**: azure-cli
- **Package Version**: 2.29.0
- **Operating System**: macOS Big Sur 11.6
- **Python Version**: Python 3.8.11

**Describe the bug**

Try to create a resource with azure-cli, calling from Python, and I got:

```
Checking Azure environment settings
Traceback (most recent call last):
  File "/Users/lsf/opt/miniconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/Users/lsf/opt/miniconda3/lib/python3.8/site-packages/ray/scripts/scripts.py", line 1970, in main
    return cli()
  File "/Users/lsf/opt/miniconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lsf/opt/miniconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/lsf/opt/miniconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/lsf/opt/miniconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lsf/opt/miniconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/lsf/opt/miniconda3/lib/python3.8/site-packages/ray/scripts/scripts.py", line 963, in up
    create_or_update_cluster(
  File "/Users/lsf/opt/miniconda3/lib/python3.8/site-packages/ray/autoscaler/_private/commands.py", line 239, in create_or_update_cluster
    config = _bootstrap_config(config, no_config_cache=no_config_cache)
  File "/Users/lsf/opt/miniconda3/lib/python3.8/site-packages/ray/autoscaler/_private/commands.py", line 322, in _bootstrap_config
    resolved_config = provider_cls.bootstrap_config(config)
  File "/Users/lsf/opt/miniconda3/lib/python3.8/site-packages/ray/autoscaler/_private/_azure/node_provider.py", line 309, in bootstrap_config
    return bootstrap_azure(cluster_config)
  File "/Users/lsf/opt/miniconda3/lib/python3.8/site-packages/ray/autoscaler/_private/_azure/config.py", line 22, in bootstrap_azure
    config = _configure_resource_group(config)
  File "/Users/lsf/opt/miniconda3/lib/python3.8/site-packages/ray/autoscaler/_private/_azure/config.py", line 58, in _configure_resource_group
    resource_client.resource_groups.create_or_update(
  File "/Users/lsf/opt/miniconda3/lib/python3.8/site-packages/azure/mgmt/resource/resources/v2021_04_01/operations/_resource_groups_operations.py", line 154, in create_or_update
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/Users/lsf/opt/miniconda3/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/Users/lsf/opt/miniconda3/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/lsf/opt/miniconda3/lib/python3.8/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/Users/lsf/opt/miniconda3/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/lsf/opt/miniconda3/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/lsf/opt/miniconda3/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/Users/lsf/opt/miniconda3/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/Users/lsf/opt/miniconda3/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry.py", line 445, in send
    response = self.next.send(request)
  File "/Users/lsf/opt/miniconda3/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 117, in send
    self.on_request(request)
  File "/Users/lsf/opt/miniconda3/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 94, in on_request
    self._token = self._credential.get_token(*self._scopes)
  File "/Users/lsf/opt/miniconda3/lib/python3.8/site-packages/azure/common/credentials.py", line 72, in get_token
    _, token, fulltoken = credentials._token_retriever()  # pylint:disable=protected-access
TypeError: _retrieve_token() missing 1 required positional argument: 'token_resource'
```

**To Reproduce**

I'm using Ray Autoscaler. `ray up azure.yaml`.

**Expected behavior**

Should not crash

**Screenshots**

**Additional context**

**Comment by lmazuel** [comment]
@franklsf95 for clarity, we can't fix azure-common at this point based on internal changes in CLI core packages, so the way going forward is to use azure-identity and AzureCLICredential. I'm sorry we didn't communicated this in a more clear way, I'm taking the feedback on this.

**Comment by franklsf95** [comment]
@lmazuel I see. Looks like the Ray package imported something from `azure.common`. I'll go ask them to fix this.

**Comment by lmazuel** [comment]
I'm making the error more explicit though:
https://github.com/Azure/azure-sdk-for-python/pull/21337
