### ISSUE TITLE
[azure-mgmt-subscription ] The methods subscriptions.list() or subscriptions.get() raise error "Bearer token authentication is not permitted for non-TLS protected"

### ISSUE THREAD

**Issue by jon-trust** [Azure/azure-sdk-for-python#21411]
- **Package Name**: azure-mgmt-subscription 
- **Package Version**: 
azure-mgmt-subscription               1.0.0
azure-mgmt-core                       1.3.0
- **Operating System**:
Windows 10
- **Python Version**: 
Python 3.7.4

**Describe the bug**
The methods subscriptions.list() or subscriptions.get() do not work. It throws an error on `azure.core.exceptions.ServiceRequestError: Bearer token authentication is not permitted for non-TLS protected (non-https) URLs.`

**To Reproduce**
```python
from azure.mgmt.subscription import SubscriptionClient
credentials = DefaultAzureCredential()
subscription_id = "ce162fe1-38d1-496d-9a1a-XXXXXXXXXXXX"
sub_client = SubscriptionClient(credentials, subscription_id)
for item in sub_client.subscriptions.list():
    print(item)
```

**Expected behavior**
I expect it to work :)

**Additional context**
I tried to add the `url_base="https://management.azure.com"` on the SubscriptionClient to no avail. Same error.

Full error:
```python
Traceback (most recent call last):
  File "azure_get_actions.py", line 38, in <module>
    for item in sub_client.subscriptions.list():
  File "C:\Python37\lib\site-packages\azure\core\paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "C:\Python37\lib\site-packages\azure\core\paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "C:\Python37\lib\site-packages\azure\mgmt\subscription\operations\_subscriptions_operations.py", line 224, in get_next
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "C:\Python37\lib\site-packages\azure\core\pipeline\_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "C:\Python37\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "C:\Python37\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "C:\Python37\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "C:\Python37\lib\site-packages\azure\mgmt\core\policies\_base.py", line 47, in send
    response = self.next.send(request)
  File "C:\Python37\lib\site-packages\azure\core\pipeline\policies\_redirect.py", line 158, in send
    response = self.next.send(request)
  File "C:\Python37\lib\site-packages\azure\core\pipeline\policies\_retry.py", line 467, in send
    raise err
  File "C:\Python37\lib\site-packages\azure\core\pipeline\policies\_retry.py", line 445, in send
    response = self.next.send(request)
  File "C:\Python37\lib\site-packages\azure\core\pipeline\policies\_authentication.py", line 117, in send
    self.on_request(request)
  File "C:\Python37\lib\site-packages\azure\core\pipeline\policies\_authentication.py", line 91, in on_request
    self._enforce_https(request)
  File "C:\Python37\lib\site-packages\azure\core\pipeline\policies\_authentication.py", line 55, in _enforce_https
    "Bearer token authentication is not permitted for non-TLS protected (non-https) URLs."
azure.core.exceptions.ServiceRequestError: Bearer token authentication is not permitted for non-TLS protected (non-https) URLs.
```

**Comment by SaurabhSharma-MSFT** [comment]
@jon-trust Thanks for your feedback. We are closing this issue. Please feel free to open a new issue when you
