### ISSUE TITLE
_acquire_token_with_authorization_code question

### ISSUE THREAD

**Issue by marcus-sds** [Azure/azure-sdk-for-python#2153]
When I deploy test with examples code for AzureResourceViewer, error message is like below. Is it issue of python module?

   2018-03-13T00:55:27.78+0000 [APP/PROC/WEB/0] ERR [2018-03-13 00:55:27,782] ERROR in app: Exception on /authorized [GET]
   2018-03-13T00:55:27.78+0000 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2018-03-13T00:55:27.78+0000 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
   2018-03-13T00:55:27.78+0000 [APP/PROC/WEB/0] ERR     response = self.full_dispatch_request()
   2018-03-13T00:55:27.78+0000 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
   2018-03-13T00:55:27.78+0000 [APP/PROC/WEB/0] ERR     rv = self.handle_user_exception(e)
   2018-03-13T00:55:27.78+0000 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
   2018-03-13T00:55:27.78+0000 [APP/PROC/WEB/0] ERR     reraise(exc_type, exc_value, tb)
   2018-03-13T00:55:27.78+0000 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
   2018-03-13T00:55:27.78+0000 [APP/PROC/WEB/0] ERR     rv = self.dispatch_request()
   2018-03-13T00:55:27.78+0000 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
   2018-03-13T00:55:27.78+0000 [APP/PROC/WEB/0] ERR     return self.view_functions[rule.endpoint](**req.view_args)
   2018-03-13T00:55:27.78+0000 [APP/PROC/WEB/0] ERR   File "/home/vcap/app/AzureResourceViewer/views.py", line 82, in authorized_view
   2018-03-13T00:55:27.78+0000 [APP/PROC/WEB/0] ERR     token_response = auth.get_tokens(auth_code)
   2018-03-13T00:55:27.78+0000 [APP/PROC/WEB/0] ERR   File "/home/vcap/app/AzureResourceViewer/auth.py", line 47, in get_tokens
   2018-03-13T00:55:27.78+0000 [APP/PROC/WEB/0] ERR     token_response = adal._acquire_token_with_authorization_code(
   2018-03-13T00:55:27.78+0000 [APP/PROC/WEB/0] ERR AttributeError: 'module' object has no attribute '_acquire_token_with_authorization_code'

**Comment by lmazuel** [comment]
Definitely this code is outdated and should be removed from the repo :(
Please consider AzureResourceViewer as deprecated

**Comment by lmazuel** [comment]
Closing, this I remove this deprecated samples today
