### ISSUE TITLE
DefaultAzureCredential is not working with az login

### ISSUE THREAD

**Issue by tmakowka-tc** [Azure/azure-sdk-for-python#21718]
- **Package Name**: azure-identity
- **Package Version**: 1.7.1
- **Operating System**: Windows 10
- **Python Version**: 3.9.7

**Describe the bug**
I'm trying to connect to a Key Vault from my dev environment, using DefaultAzureCredential, previously having logged in with az login. The code should run using managed identity in Azure, for development purposes a locally signed in user with az login should be used. Thus DefaultAzureCredential is used for having a transparent authentication method.

The following error is coming up:
```DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
        EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot.this issue.
        ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.
        SharedTokenCacheCredential: Azure Active Directory error '(invalid_grant) AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2021-11-03T12:41:45.9066517Z and was inactive for 12:00:00.
Trace ID: d2308115-d11f-40a6-abcb-a75405669000
Correlation ID: f73357cd-663c-42f2-81e7-645fba74634f
Timestamp: 2021-11-11 16:08:54Z'
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
Traceback (most recent call last):
  File "D:\tmp\test\test.py", line 16, in <module>
    saConnectionString = kvClient.get_secret("storage-connection-string")
  File "D:\tmp\test\.venv\lib\site-packages\azure\core\tracing\decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "D:\tmp\test\.venv\lib\site-packages\azure\keyvault\secrets\_client.py", line 67, in get_secret
    bundle = self._client.get_secret(
  File "D:\tmp\test\.venv\lib\site-packages\azure\keyvault\secrets\_generated\_operations_mixin.py", line 1515, in get_secret
    return mixin_instance.get_secret(vault_base_url, secret_name, secret_version, **kwargs)
  File "D:\tmp\test\.venv\lib\site-packages\azure\keyvault\secrets\_generated\v7_2\operations\_key_vault_client_operations.py", line 286, in get_secret
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "D:\tmp\test\.venv\lib\site-packages\azure\core\pipeline\_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "D:\tmp\test\.venv\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "D:\tmp\test\.venv\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "D:\tmp\test\.venv\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "D:\tmp\test\.venv\lib\site-packages\azure\core\pipeline\policies\_redirect.py", line 158, in send
    response = self.next.send(request)
  File "D:\tmp\test\.venv\lib\site-packages\azure\core\pipeline\policies\_retry.py", line 445, in send
    response = self.next.send(request)
  File "D:\tmp\test\.venv\lib\site-packages\azure\keyvault\secrets\_shared\challenge_auth_policy.py", line 111, in send
    self._handle_challenge(request, challenge)
  File "D:\tmp\test\.venv\lib\site-packages\azure\keyvault\secrets\_shared\challenge_auth_policy.py", line 137, in _handle_challenge
    self._token = self._credential.get_token(scope)
  File "D:\tmp\test\.venv\lib\site-packages\azure\identity\_credentials\default.py", line 172, in get_token
    return super(DefaultAzureCredential, self).get_token(*scopes, **kwargs)
  File "D:\tmp\test\.venv\lib\site-packages\azure\identity\_credentials\chained.py", line 108, in get_token
    raise ClientAuthenticationError(message=message)
azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
        EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot.this issue.
        ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.
        SharedTokenCacheCredential: Azure Active Directory error '(invalid_grant) AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2021-11-03T12:41:45.9066517Z and was inactive for 12:00:00.
Trace ID: d2308115-d11f-40a6-abcb-a75405669000
Correlation ID: f73357cd-663c-42f2-81e7-645fba74634f
Timestamp: 2021-11-11 16:08:54Z'
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
```

**To Reproduce**
1. az login
2. Run the following code

```
from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient

credential = DefaultAzureCredential()
KVUri = f"https://keyVaultName.vault.azure.net"
kvClient = SecretClient(vault_url=KVUri, credential=credential)

secret = kvClient.get_secret("mysecret")
```

**Expected behavior**
The code should authenticate with my logged in user (logged in via az login).

**Screenshots**

**Additional context**

**Comment by xiangyan99** [comment]
@tmakowka-tc Thanks for the feedback.

From the log:
SharedTokenCacheCredential: Azure Active Directory error '(invalid_grant) AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2021-11-03T12:41:45.9066517Z and was inactive for 12:00:00.

Seems like it failed because the token expired.

Could you check the code if this was the case?

Thanks.

**Comment by tmakowka-tc** [comment]
@xiangyan99 Thanks for taking time to look into this. I saw this warning, and re-tried "az login", but the issue remains. Could you please tell me where to check for the validity of the token, or how to refresh it?

Thanks

**Comment by riedgar-ms** [comment]
I'm seeing a similar issue (I'm on `azure-identity` version 1.7.0). I'm running in a notebook, and have the following block of code:
```python
from azure.identity import AzureCliCredential, DefaultAzureCredential

creds = DefaultAzureCredential(exclude_interactive_browser_credential=False)
cli_creds = AzureCliCredential()
```
I can use the `cli_creds` object in a subsequent call to `BlobServiceClient`. However, if I try using the `creds` object instead, I get an error very much like that reported by @tmakowka-tc .

**Comment by xiangyan99** [comment]
@riedgar-ms Thanks for the information. Could you share the logs when you use creds?

**Comment by tmakowka-tc** [comment]
@xiangyan99 Could you please look into my comment on how to refresh the token via az login? I wonder if there's anything I can do from my side to fix this. 

Thanks!

**Comment by riedgar-ms** [comment]
So using the two above credentials, if I create a `BlobServiceClient` with the `cli_creds` things work. If I use `creds`, then the returned error is:
```
ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot.this issue.
	ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.
	SharedTokenCacheCredential: Azure Active Directory error '(invalid_grant) AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2021-05-25T20:50:03.8578657Z and was inactive for 90.00:00:00.
Trace ID: b1f8cf77-5a56-4dbe-884b-497ac9884900
Correlation ID: 9fc784f0-09d9-47dd-a793-ce90b4a533f9
Timestamp: 2021-11-16 14:25:07Z'
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
```
The relevant part of the stacktrace appears to be:
```
~\AppData\Local\Continuum\miniconda3\envs\my-conda-env\lib\site-packages\azure\core\paging.py in __next__(self)
    127         if self._page_iterator is None:
    128             self._page_iterator = itertools.chain.from_iterable(self.by_page())
--> 129         return next(self._page_iterator)
    130 
    131     next = __next__  # Python 2 compatibility.

~\AppData\Local\Continuum\miniconda3\envs\my-conda-env\lib\site-packages\azure\core\paging.py in __next__(self)
     74             raise StopIteration("End of paging")
     75         try:
---> 76             self._response = self._get_next(self.continuation_token)
     77         except AzureError as error:
     78             if not error.continuation_token:

~\AppData\Local\Continuum\miniconda3\envs\my-conda-env\lib\site-packages\azure\storage\blob\_list_blobs_helper.py in _get_next_cb(self, continuation_token)
     74                 maxresults=self.results_per_page,
     75                 cls=return_context_and_deserialized,
---> 76                 use_location=self.location_mode)
     77         except StorageErrorException as error:
     78             process_storage_error(error)

~\AppData\Local\Continuum\miniconda3\envs\my-conda-env\lib\site-packages\azure\storage\blob\_generated\operations\_container_operations.py in list_blob_hierarchy_segment(self, delimiter, prefix, marker, maxresults, include, timeout, request_id, cls, **kwargs)
   1322         # Construct and send request
   1323         request = self._client.get(url, query_parameters, header_parameters)
-> 1324         pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
   1325         response = pipeline_response.http_response
   1326 

~\AppData\Local\Continuum\miniconda3\envs\my-conda-env\lib\site-packages\azure\core\pipeline\_base.py in run(self, request, **kwargs)
    209             else _TransportRunner(self._transport)
    210         )
--> 211         return first_node.send(pipeline_request)  # type: ignore

~\AppData\Local\Continuum\miniconda3\envs\my-conda-env\lib\site-packages\azure\core\pipeline\_base.py in send(self, request)
     69         _await_result(self._policy.on_request, request)
     70         try:
---> 71             response = self.next.send(request)
     72         except Exception:  # pylint: disable=broad-except
     73             if not _await_result(self._policy.on_exception, request):

~\AppData\Local\Continuum\miniconda3\envs\my-conda-env\lib\site-packages\azure\core\pipeline\_base.py in send(self, request)
     69         _await_result(self._policy.on_request, request)
     70         try:
---> 71             response = self.next.send(request)
     72         except Exception:  # pylint: disable=broad-except
     73             if not _await_result(self._policy.on_exception, request):

~\AppData\Local\Continuum\miniconda3\envs\my-conda-env\lib\site-packages\azure\core\pipeline\_base.py in send(self, request)
     69         _await_result(self._policy.on_request, request)
     70         try:
---> 71             response = self.next.send(request)
     72         except Exception:  # pylint: disable=broad-except
     73             if not _await_result(self._policy.on_exception, request):

~\AppData\Local\Continuum\miniconda3\envs\my-conda-env\lib\site-packages\azure\core\pipeline\_base.py in send(self, request)
     69         _await_result(self._policy.on_request, request)
     70         try:
---> 71             response = self.next.send(request)
     72         except Exception:  # pylint: disable=broad-except
     73             if not _await_result(self._policy.on_exception, request):

~\AppData\Local\Continuum\miniconda3\envs\my-conda-env\lib\site-packages\azure\core\pipeline\_base.py in send(self, request)
     69         _await_result(self._policy.on_request, request)
     70         try:
---> 71             response = self.next.send(request)
     72         except Exception:  # pylint: disable=broad-except
     73             if not _await_result(self._policy.on_exception, request):

~\AppData\Local\Continuum\miniconda3\envs\my-conda-env\lib\site-packages\azure\core\pipeline\_base.py in send(self, request)
     69         _await_result(self._policy.on_request, request)
     70         try:
---> 71             response = self.next.send(request)
     72         except Exception:  # pylint: disable=broad-except
     73             if not _await_result(self._policy.on_exception, request):

~\AppData\Local\Continuum\miniconda3\envs\my-conda-env\lib\site-packages\azure\core\pipeline\policies\_authentication.py in send(self, request)
    115         :type request: ~azure.core.pipeline.PipelineRequest
    116         """
--> 117         self.on_request(request)
    118         try:
    119             response = self.next.send(request)

~\AppData\Local\Continuum\miniconda3\envs\my-conda-env\lib\site-packages\azure\core\pipeline\policies\_authentication.py in on_request(self, request)
     92 
     93         if self._token is None or self._need_new_token:
---> 94             self._token = self._credential.get_token(*self._scopes)
     95         self._update_headers(request.http_request.headers, self._token.token)
     96 

~\AppData\Local\Continuum\miniconda3\envs\my-conda-env\lib\site-packages\azure\identity\_credentials\default.py in get_token(self, *scopes, **kwargs)
    170             return token
    171 
--> 172         return super(DefaultAzureCredential, self).get_token(*scopes, **kwargs)

~\AppData\Local\Continuum\miniconda3\envs\my-conda-env\lib\site-packages\azure\identity\_credentials\chained.py in get_token(self, *scopes, **kwargs)
    106                     "https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot."
    107         _LOGGER.warning(message)
--> 108         raise ClientAuthenticationError(message=message)
```
And finally, Python is `3.6.13 (default, Sep 23 2021, 07:38:49) [MSC v.1916 64 bit (AMD64)]`, and the pip packages are:
```
Name: azure-core
Version: 1.19.1
Summary: Microsoft Azure Core Library for Python
Home-page: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/core/azure-core
Author: Microsoft Corporation
Author-email: azpysdkhelp@microsoft.com
License: MIT License
Location: c:\users\riedgar\appdata\local\continuum\miniconda3\envs\sdkv2-nb-experiments\lib\site-packages
Requires: requests, six
Required-by: azure-identity, azure-mgmt-core, azure-storage-blob, azure-storage-file-share
---
Name: azure-identity
Version: 1.7.0
Summary: Microsoft Azure Identity Library for Python
Home-page: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/identity/azure-identity
Author: Microsoft Corporation
Author-email: azpysdkhelp@microsoft.com
License: MIT License
Location: c:\users\riedgar\appdata\local\continuum\miniconda3\envs\sdkv2-nb-experiments\lib\site-packages
Requires: azure-core, cryptography, msal, msal-extensions, six
---
Name: azure-storage-blob
Version: 12.5.0
Summary: Microsoft Azure Blob Storage Client Library for Python
Home-page: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-blob
Author: Microsoft Corporation
Author-email: ascl@microsoft.com
License: MIT License
Location: c:\users\riedgar\appdata\local\continuum\miniconda3\envs\sdkv2-nb-experiments\lib\site-packages
Requires: azure-core, cryptography, msrest
```

**Comment by xiangyan99** [comment]
@tmakowka-tc @riedgar-ms Thanks for your information. What happened here is DefaultAzureCredential found a refresh token in the cache but it expired. DefaultAzureCredential stopped there with the error message. It happens usually because you logged in with visual studio but had not used it again for some time.

This is by design because if there is a refresh token found, we don't want to silently use another one if it expires. Instead we explicitly fail with the message.

If you really want to skip using the cached one, you can add exclude_shared_token_cache_credential=True when you create DefaultAzureCredential:

credential = DefaultAzureCredential(exclude_shared_token_cache_credential=True)

please let us know if it does not work for you.

**Comment by riedgar-ms** [comment]
That does work (although there was a warning about `EnvironmentCredential.get_token failed` but that must have failed over to the next method.

> This is by design because if there is a refresh token found, we don't want to silently use another one if it expires. Instead we explicitly fail with the message.

Could the error message be made a bit more explicit? This was a token I had no idea was lying around, and the error message didn't point me at Visual Studio.

**Comment by tmakowka-tc** [comment]
@xiangyan99 Unfortunately this does not work in my situation. I changed my code as you suggested:

`credential = DefaultAzureCredential(exclude_shared_token_cache_credential=True)`

The error now is:

```
DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
        EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot.this issue.
        ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.
        VisualStudioCodeCredential: Azure Active Directory error '(invalid_grant) AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2021-11-10T16:10:58.1328010Z and was inactive for 12:00:00.
Trace ID: 347c12ac-3d1a-4f00-91f2-1937a60c4f00
Correlation ID: 3fa69d2d-b588-4894-b6e3-99aead44d120
Timestamp: 2021-11-17 09:42:41Z'
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
Traceback (most recent call last):
  File "D:\tmp\test\test.py", line 16, in <module>
    saConnectionString = kvClient.get_secret("storage-connection-string")
  File "D:\tmp\test\.venv\lib\site-packages\azure\core\tracing\decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "D:\tmp\test\.venv\lib\site-packages\azure\keyvault\secrets\_client.py", line 67, in get_secret
    bundle = self._client.get_secret(
  File "D:\tmp\test\.venv\lib\site-packages\azure\keyvault\secrets\_generated\_operations_mixin.py", line 1515, in get_secret
    return mixin_instance.get_secret(vault_base_url, secret_name, secret_version, **kwargs)
  File "D:\tmp\test\.venv\lib\site-packages\azure\keyvault\secrets\_generated\v7_2\operations\_key_vault_client_operations.py", line 286, in get_secret
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "D:\tmp\test\.venv\lib\site-packages\azure\core\pipeline\_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "D:\tmp\test\.venv\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "D:\tmp\test\.venv\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "D:\tmp\test\.venv\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "D:\tmp\test\.venv\lib\site-packages\azure\core\pipeline\policies\_redirect.py", line 158, in send
    response = self.next.send(request)
  File "D:\tmp\test\.venv\lib\site-packages\azure\core\pipeline\policies\_retry.py", line 445, in send
    response = self.next.send(request)
  File "D:\tmp\test\.venv\lib\site-packages\azure\keyvault\secrets\_shared\challenge_auth_policy.py", line 111, in send
    self._handle_challenge(request, challenge)
  File "D:\tmp\test\.venv\lib\site-packages\azure\keyvault\secrets\_shared\challenge_auth_policy.py", line 137, in _handle_challenge
    self._token = self._credential.get_token(scope)
  File "D:\tmp\test\.venv\lib\site-packages\azure\identity\_credentials\default.py", line 172, in get_token
    return super(DefaultAzureCredential, self).get_token(*scopes, **kwargs)
  File "D:\tmp\test\.venv\lib\site-packages\azure\identity\_credentials\chained.py", line 108, in get_token
    raise ClientAuthenticationError(message=message)
azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
        EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot.this issue.
        ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.
        VisualStudioCodeCredential: Azure Active Directory error '(invalid_grant) AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2021-11-10T16:10:58.1328010Z and was inactive for 12:00:00.
Trace ID: 347c12ac-3d1a-4f00-91f2-1937a60c4f00
Correlation ID: 3fa69d2d-b588-4894-b6e3-99aead44d120
Timestamp: 2021-11-17 09:42:41Z'
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
```

**Comment by xiangyan99** [comment]
@tmakowka-tc Sorry for the inconvenience. This is same issue, when searching VS code credential we found a refresh token which expired. You can add exclude_visual_studio_code_credential=True to disable it:

credential = DefaultAzureCredential(exclude_shared_token_cache_credential=True, exclude_visual_studio_code_credential=True)

Can you take another try?

For the priorities of the DefaultAzureCredential, you can refer

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/README.md#DefaultAzureCredential

We agree the experience is a little bit challenging. We will revisit the design.

Thanks.

**Comment by tmakowka-tc** [comment]
@xiangyan99 Thanks for the update, it's working now for me also with this option enabled!

I'm wondering why the process of retrieving a valid credential is stopping when an invalid token is found. Wouldn't it be better to just continue searching for valid credentials in this case? 

However, thanks for helping me to fix this!

**Comment by xiangyan99** [comment]
@tmakowka-tc Yes. This is a good point. Our design to try to avoid the scenario that some customers log in with VS code and they expect to use VS code credential to authorize but if the credential expires, we automatically use Azure CLI without any information. That might cause some security concerns. (Because you may operate on another account without awareness).

We see your pain and we will re-visit the design.

Thanks again for reporting the issue.
