### ISSUE TITLE
AttributeError: 'coroutine' object has no attribute 'http_response'

### ISSUE THREAD

**Issue by Cukkimo** [Azure/azure-sdk-for-python#21736]
Packages:

azure-core==1.20.1
azure-storage-blob==12.9.0 

OS: Linux
Python 3.9 also with 3.6

I simply try to list containers. Throws error: AttributeError: 'coroutine' object has no attribute 'http_response'
There is proxy involved in this setup, but it seems to work fine with older version of the library.

I can paste Dockerfile and the full example code if requested.

```
Traceback (most recent call last):
  File "/test.py", line 31, in <module>
    loop.run_until_complete(future)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/lib64/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/test.py", line 20, in main
    async for c in client.list_containers():
  File "/usr/local/lib/python3.9/site-packages/azure/core/async_paging.py", line 154, in __anext__
    return await self.__anext__()
  File "/usr/local/lib/python3.9/site-packages/azure/core/async_paging.py", line 157, in __anext__
    self._page = await self._page_iterator.__anext__()
  File "/usr/local/lib/python3.9/site-packages/azure/core/async_paging.py", line 99, in __anext__
    self._response = await self._get_next(self.continuation_token)
  File "/usr/local/lib/python3.9/site-packages/azure/storage/blob/aio/_models.py", line 54, in _get_next_cb
    return await self._command(
  File "/usr/local/lib/python3.9/site-packages/azure/storage/blob/_generated/aio/operations/_service_operations.py", line 352, in list_containers_segment
    pipeline_response = await self._client._pipeline.run(request, stream=False, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base_async.py", line 215, in run
    return await first_node.send(pipeline_request)
  File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  [Previous line repeated 4 more times]
  File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/policies/_redirect_async.py", line 64, in send
    response = await self.next.send(request)
  File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/azure/storage/blob/_shared/policies.py", line 490, in send
    if is_retry(response, retry_settings['mode']):
  File "/usr/local/lib/python3.9/site-packages/azure/storage/blob/_shared/policies.py", line 84, in is_retry
    status = response.http_response.status_code
AttributeError: 'coroutine' object has no attribute 'http_response'
sys:1: RuntimeWarning: coroutine '_SansIOAsyncHTTPPolicyRunner.send' was never awaited
```

Main points of the example code. Other code is just setting proxy configuration like in the samples.
```
from azure.storage.blob.aio import BlobServiceClient

...

async with client:
    async for c in client.list_containers():
        logger.info(c)
```

I expect this to simply print out the containers

Possibly related to: 
#https://github.com/Azure/azure-sdk-for-python/issues/21061
#https://github.com/Azure/azure-sdk-for-python/issues/21639

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by xiangyan99** [comment]
@tasherif-msft 
In https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/policies_async.py#L16, should we import StorageRetryPolicy from policies_async not policies?

**Comment by iscai-msft** [comment]
hey @Cukkimo, can you confirm that you're following [this](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/samples/blob_samples_proxy_configuration.py) exact sample file and trying to adapt it to async? It would be great if you could share all of your code so we can confirm.

**Comment by Cukkimo** [comment]
https://github.com/Azure/azure-sdk-for-python/issues/9311
I think this was the issue here. 


I made this program originally ~2 years ago, and back then there was examples to directly put proxies in initialized client internal attribute `_config.proxy_policies.proxies = proxies

Which seemed quite off, but it worked back then.

Now when revisiting this year ago I changed it to the deprecated example in the issue where using `create_configuration()` and passing it to the client constructor via `_configuration`.

Now when there is an actual proxy argument available in the client constructor it does what it should.
The error message raised, thou, is not very helpful in this situation.

**Comment by iscai-msft** [comment]
Agreed. Thanks for confirming that it was following the old sample that caused your issue. The old sample was definitely was definitely not the best implementation since it was using private code, and it wasn't clear how to adapt it from sync to async. The issue was caused because the `create_configuration` call in the sample introduced some sync-only policies to your async code, which caused the "coroutine" error. I went ahead and fixed the sample yesterday, can you confirm making the [following changes](https://github.com/Azure/azure-sdk-for-python/pull/21762/files) to your code fixes your issue?

**Comment by Cukkimo** [comment]
Yes, now it seems to work as intended.

**Comment by iscai-msft** [comment]
@Cukkimo thank you for raising this issue and helping us improve our samples
