### ISSUE TITLE
Can't connect to azure when using python sdk：SSLError

### ISSUE THREAD

**Issue by youngbm** [Azure/azure-sdk-for-python#2181]
I'm using  Azure python SDK azure (2.0.0) to connect to Azure. The scripts work on other environment. But i can't work on the new one.  I got error：

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
Traceback (most recent call last):
  File "main.py", line 170, in <module>
    g_conf, server_info=prepare_install()
  File "main.py", line 134, in prepare_install
    server_info=createZbxHosts(ZBX_FILE_TEMPLATE, ZBX_AGENT_HOSTS_FILE, ZBX_HANDLE_TEMPLATE, ZBX_HANDLE_HOSTS_FILE, g_conf)
  File "/home/ngcvc/ezxiezh/zabbix/monitor/create_ansible_hosts.py", line 203, in createZbxHosts
    credentials, subscription_id= get_credentials(g_conf)
  File "/home/ngcvc/ezxiezh/zabbix/monitor/create_ansible_hosts.py", line 54, in get_credentials
    cloud_environment =  AZURE_PUBLIC_CLOUD,
  File "/usr/lib/python2.7/site-packages/msrestazure/azure_active_directory.py", line 440, in __init__
    self.set_token()
  File "/usr/lib/python2.7/site-packages/msrestazure/azure_active_directory.py", line 473, in set_token
    raise_with_traceback(AuthenticationError, "", err)
  File "/usr/lib/python2.7/site-packages/msrest/exceptions.py", line 48, in raise_with_traceback
    raise error
msrest.exceptions.AuthenticationError: , SSLError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /92e84ceb-fbfd-47ab-be52-080c6b87953f/oauth2/token (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))
```

Here is my main function of loging：
```
def get_credentials(g_conf):
    subscription_id = XXXXXX
    credentials = ServicePrincipalCredentials(
        client_id =XXXX
        secret    = XXXXX,
        tenant    = XXXXXX,
        cloud_environment =  AZURE_PUBLIC_CLOUD,
       #verify=False
    )
    return credentials, subscription_id

def GetAllResourceByLogin(credentials, subscription_id):
    compute_client = ComputeManagementClient(credentials, subscription_id)
    network_client = NetworkManagementClient(credentials, subscription_id)

    network_interfaces = network_client.network_interfaces.list_all()
    for nic in network_interfaces:
        g_AllResourceById[nic.id] = nic
        g_NetworkInterfaces.append(nic)

    virtual_networks   = network_client.virtual_networks.list_all()
    for vnet in virtual_networks:
        g_AllResourceById[vnet.id] = vnet
        g_VirtualNetworks.append(vnet)

    virtual_machines = compute_client.virtual_machines.list_all()
    for vm in virtual_machines:
        g_AllResourceById[vm.id] = vm
        g_VirtualMachines.append(vm)
```

**Comment by youngbm** [comment]
I workmate helps me to solve， it's because the moudel of  pyopenssl.
