### ISSUE TITLE
[BUG Bash] delete_blobs doesn't work with azurite

### ISSUE THREAD

**Issue by morland96** [Azure/azure-sdk-for-python#21872]
**Describe the bug**
When use delete_blobs, azurite refused with status code 400

***Exception or Stack Trace***
python exception:
```
  File "FileOperator_spec.py", line 172, in empty_data_folders_does_not_raise
    self.data_container_client.delete_blobs(*blobs)
  File "venv/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "venv/lib/python3.9/site-packages/azure/storage/blob/_container_client.py", line 1302, in delete_blobs
    return self._batch_send(*reqs, **options)
  File "venv/lib/python3.9/site-packages/azure/storage/blob/_shared/base_client.py", line 322, in _batch_send
    process_storage_error(error)
  File "venv/lib/python3.9/site-packages/azure/storage/blob/_shared/response_handlers.py", line 110, in process_storage_error
    _LOGGER.warning(
Message: 'Unexpected return type % from ContentDecodePolicy.deserialize_from_http_generics.'
Arguments: (<class 'NoneType'>,)
```

azurite debug error:
```
2021-11-24T04:11:02.906Z bdacffce-65a7-410d-b728-cb53fdc240fc info: BlobStorageContextMiddleware: RequestMethod=POST RequestURL=http://127.0.0.1/devstoreaccount1/tmp-data?restype=container&comp=batch RequestHeaders:{"host":"127.0.0.1:10000","user-agent":"azsdk-python-storage-blob/12.9.0 Python/3.9.7 (macOS-11.6-x86_64-i386-64bit)","accept-encoding":"gzip, deflate","accept":"*/*","connection":"keep-alive","x-ms-version":"2020-10-02","content-type":"multipart/mixed; boundary=batch_89ba4f78-4cdc-11ec-aad1-acde48001122","content-length":"4024","x-ms-date":"Wed, 24 Nov 2021 04:11:02 GMT","x-ms-client-request-id":"89bc7e7e-4cdc-11ec-aad1-acde48001122","authorization":"SharedKey devstoreaccount1:W+FzGbp15qwKN5hKiIXXQ/z13ILlF7bBK4XKPRaakj8="} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2021-11-24T04:11:02.906Z bdacffce-65a7-410d-b728-cb53fdc240fc info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=tmp-data Blob=
2021-11-24T04:11:02.906Z bdacffce-65a7-410d-b728-cb53fdc240fc verbose: DispatchMiddleware: Dispatching request...
2021-11-24T04:11:02.906Z bdacffce-65a7-410d-b728-cb53fdc240fc error: DispatchMiddleware: Incoming URL doesn't match any of swagger defined request patterns.
2021-11-24T04:11:02.906Z bdacffce-65a7-410d-b728-cb53fdc240fc error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2021-11-24T04:11:02.906Z bdacffce-65a7-410d-b728-cb53fdc240fc error: ErrorMiddleware: ErrorName=UnsupportedRequestError ErrorMessage=Incoming URL doesn't match any of swagger defined request patterns.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders=undefined ErrorHTTPBody=undefined ErrorStack="UnsupportedRequestError: Incoming URL doesn't match any of swagger defined request patterns.\n    at Object.dispatchMiddleware [as default] (/usr/local/lib/node_modules/azurite/dist/src/blob/generated/middleware/dispatch.middleware.js:41:30)\n    at /usr/local/lib/node_modules/azurite/dist/src/blob/generated/ExpressMiddlewareFactory.js:49:42\n    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/azurite/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/local/lib/node_modules/azurite/node_modules/express/lib/router/index.js:317:13)\n    at /usr/local/lib/node_modules/azurite/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/local/lib/node_modules/azurite/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/local/lib/node_modules/azurite/node_modules/express/lib/router/index.js:275:10)\n    at blobStorageContextMiddleware (/usr/local/lib/node_modules/azurite/dist/src/blob/middlewares/blobStorageContext.middleware.js:73:5)\n    at /usr/local/lib/node_modules/azurite/dist/src/blob/middlewares/blobStorageContext.middleware.js:15:16\n    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/azurite/node_modules/express/lib/router/layer.js:95:5)"
2021-11-24T04:11:02.906Z bdacffce-65a7-410d-b728-cb53fdc240fc error: ErrorMiddleware: Set HTTP code: 400
2021-11-24T04:11:02.906Z bdacffce-65a7-410d-b728-cb53fdc240fc error: ErrorMiddleware: Set HTTP body: undefined
2021-11-24T04:11:02.906Z bdacffce-65a7-410d-b728-cb53fdc240fc info: EndMiddleware: End response. TotalTimeInMS=0 StatusCode=400 StatusMessage=undefined Headers={"server":"Azurite-Blob/3.14.3"}
```
***Code Snippet***
```
            blobs = self.data_container_client.list_blobs(name_starts_with="")
            self.data_container_client.delete_blobs(*blobs)
```

**Setup (please complete the following information):**
 - Python Version: 3.9
 - SDK Version: azure-storage-blob==12.9.0
 - azurite: 3.14.3

**Comment by amishra-dev** [comment]
@blueww / @tasherif-msft can you folks please look into what happened here?

**Comment by blueww** [comment]
@morland96 

Per the request Uri, this is a Blob Batch request. 
`RequestURL=http://127.0.0.1/devstoreaccount1/tmp-data?restype=container&comp=batch`

Azurite still not support Blob Batch. 
We already have an issue to track it: https://github.com/Azure/Azurite/issues/287

**Comment by tasherif-msft** [comment]
Hi @morland96 please track on Azurite as per @blueww's rec. I will proceed to close this issue.

**Comment by verikono** [comment]
This occurs with azure.storage.filedatalake,DataLakeFileClient alone.
 - python 3.7
 - azure-core 1.21.1
 - azure-identity 1.7.1
 - azure-storage-file-datalake 12.5.0

```python
with DataLakeFileClient(
  account_url="https://myadlg2.core.windows.net"
  file_system_name="someblobcontainer",
  file_path="somefolder/somefile.txt",
  credential=DefaultAzureCredential()
) as client:
  result = client.delete_file()
```

```python
  File "/mnt/workhdd/projects/python/py-ent-adlgen2/venv/lib/python3.7/site-packages/azure/storage/filedatalake/_path_client.py", line 261, in _delete
    process_storage_error(error)
  File "/mnt/workhdd/projects/python/py-ent-adlgen2/venv/lib/python3.7/site-packages/azure/storage/filedatalake/_deserialize.py", line 139, in process_storage_error
    'Unexpected return type % from ContentDecodePolicy.deserialize_from_http_generics.', type(error_body))
Message: 'Unexpected return type % from ContentDecodePolicy.deserialize_from_http_generics.'
Arguments: (<class 'NoneType'>,)
```

**Comment by verikono** [comment]
This occurs with azure.storage.filedatalake,DataLakeFileClient alone.
 - python 3.7
 - azure-core 1.21.1
 - azure-identity 1.7.1
 - azure-storage-file-datalake 12.5.0

```python
with DataLakeFileClient(
  account_url="https://myadlg2.core.windows.net"
  file_system_name="someblobcontainer",
  file_path="somefolder/somefile.txt",
  credential=DefaultAzureCredential()
) as client:
  result = client.delete_file()
```

throws:


```python
  File "/mnt/myproject/venv/lib/python3.7/site-packages/azure/storage/filedatalake/_path_client.py", line 261, in _delete
    process_storage_error(error)
  File "/mnt/myproject/venv/lib/python3.7/site-packages/azure/storage/filedatalake/_deserialize.py", line 139, in process_storage_error
    'Unexpected return type % from ContentDecodePolicy.deserialize_from_http_generics.', type(error_body))
Message: 'Unexpected return type % from ContentDecodePolicy.deserialize_from_http_generics.'
Arguments: (<class 'NoneType'>,)
```
