### ISSUE TITLE
(None) Operation xxx not found when re-run to create gateway connection.

### ISSUE THREAD

**Issue by xingyu-long** [Azure/azure-sdk-for-python#22061]
- **Package Name**: 
azure.mgmt.network
- **Package Version**: 
19.2.0
- **Operating System**:
Cent OS
- **Python Version**: 
Python 3.8.8

**Describe the bug**
I'd like to create or update the gateway connection. i.e., It will create a gateway connection when it doesn't exist, otherwise, it will be updated or kept the old one. That's the API (`client.virtual_network_gateway_connections.begin_create_or_update()`) said. But when I re-run with the same connection name it will throw the following error. By the way, I used expressRoute from Azure VMware Solution.

```
Provisioning geteway connection (xxxxx-avs-connect-test-3)
HttpResponseError when privioning gateway connection (xxxxx-avs-connect-test-3)
Traceback (most recent call last):
  File "/home/xxxxx/.pyenv/versions/anaconda3-2021.05/lib/python3.8/site-packages/azure/core/polling/base_polling.py", line 483, in run
    self._poll()
  File "/home/xxxxx/.pyenv/versions/anaconda3-2021.05/lib/python3.8/site-packages/azure/core/polling/base_polling.py", line 519, in _poll
    self.update_status()
  File "/home/xxxxx/.pyenv/versions/anaconda3-2021.05/lib/python3.8/site-packages/azure/core/polling/base_polling.py", line 561, in update_status
    _raise_if_bad_http_status_and_method(self._pipeline_response.http_response)
  File "/home/xxxxx/.pyenv/versions/anaconda3-2021.05/lib/python3.8/site-packages/azure/core/polling/base_polling.py", line 112, in _raise_if_bad_http_status_and_method
    raise BadStatus(
azure.core.polling.base_polling.BadStatus: Invalid return status 404 for 'GET' operation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxxxx/learning_cloud/azure_example/reproduce_connection_exception.py", line 53, in <module>
    create_or_update_gateway_connection(client,
  File "/home/xxxxx/learning_cloud/azure_example/reproduce_connection_exception.py", line 15, in create_or_update_gateway_connection
    result = creation.result()
  File "/home/xxxxx/.pyenv/versions/anaconda3-2021.05/lib/python3.8/site-packages/azure/core/polling/_poller.py", line 255, in result
    self.wait(timeout)
  File "/home/xxxxx/.pyenv/versions/anaconda3-2021.05/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/xxxxx/.pyenv/versions/anaconda3-2021.05/lib/python3.8/site-packages/azure/core/polling/_poller.py", line 275, in wait
    raise self._exception # type: ignore
  File "/home/xxxxx/.pyenv/versions/anaconda3-2021.05/lib/python3.8/site-packages/azure/core/polling/_poller.py", line 192, in _start
    self._polling_method.run()
  File "/home/xxxxx/.pyenv/versions/anaconda3-2021.05/lib/python3.8/site-packages/azure/core/polling/base_polling.py", line 487, in run
    raise HttpResponseError(
azure.core.exceptions.HttpResponseError: (None) Operation c2b81c7b-fec0-4507-a081-fd3521ab6db7 not found.
Code: None
Message: Operation c2b81c7b-fec0-4507-a081-fd3521ab6db7 not found.
```

**To Reproduce**
```
from azure.identity import AzureCliCredential
from azure.mgmt.network import NetworkManagementClient
from azure.core import exceptions


def create_or_update_gateway_connection(client, resource_group, connection_name, config):
    print("Provisioning geteway connection"
          " ({})".format(connection_name))
    try:
        creation = client.virtual_network_gateway_connections.begin_create_or_update(
            resource_group,
            connection_name,
            config
        )
        result = creation.result()
        print("Provisioned geteway connection"
              " ({})".format(connection_name))
        return result
    except exceptions.HttpResponseError:
        print("HttpResponseError when privioning gateway "
              "connection ({})".format(connection_name))
        raise


credential = AzureCliCredential()
sub_id = "xxxxxxx"

client = NetworkManagementClient(credential, sub_id)

resource_group = "Azure-DEV-ENV-RG"
location = "eastus"

connection_name = "xxxx-avs-connect-test-3"
gateway_id = "xxxxx"
auth_key = "xxxxxx"
express_route_id = "xxxxxx"
connection_config = {
    "location": location,
    "properties": {
        "virtualNetworkGateway1": {
            "id": gateway_id
        },
        "enableBgp": "false",
        "connectionType": "ExpressRoute",
        "routingWeight": 10,
        "authorizationKey": auth_key,
        "usePolicyBasedTrafficSelectors": "false",
        "peer": {
            "id": express_route_id
        }
    }
}
create_or_update_gateway_connection(client,
                                    resource_group,
                                    connection_name,
                                    connection_config)
```

**Expected behavior**
It should no error even with the same connection_name.

**Screenshots**

**Additional context**

**Comment by msyyc** [comment]
According to log info:
> azure.core.exceptions.HttpResponseError: (None) Operation c2b81c7b-fec0-4507-a081-fd3521ab6db7 not found.

Hi @service team, the error is returned by service. Appreciate if you could provide some suggestion.

**Comment by xiangyan99** [comment]
Since this is a service issue rather than an SDK issue. We will close this one. 

Please feel free to open a support ticket for the service team.

Thanks.
