### ISSUE TITLE
AttributeError: 'CredentialAdaptor' object has no attribute '_token_retriever'

### ISSUE THREAD

**Issue by mickare** [Azure/azure-sdk-for-python#22073]
- **Package Name**: azure-core
- **Package Version**: 1.21.1
- **Operating System**: macOS Monterey
- **Python Version**: 3.9

**Describe the bug**
Deploying a ray cluster to azure fails with an internal credential error in the Azure core commons package.

**To Reproduce**
Following the Azure guide at https://docs.ray.io/en/latest/cluster/cloud.html

1. Configure the ray deployment for Azure
2. Run `ray up azure-example-full.yaml`
3. Fail `AttributeError: 'CredentialAdaptor' object has no attribute '_token_retriever'`

**Expected behavior**
No internal error.

**Logs**
```
Traceback (most recent call last):
  File "/Users/mickare/git/raydemo/venv/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/Users/mickare/git/raydemo/venv/lib/python3.9/site-packages/ray/scripts/scripts.py", line 1989, in main
    return cli()
  File "/Users/mickare/git/raydemo/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mickare/git/raydemo/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/mickare/git/raydemo/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mickare/git/raydemo/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mickare/git/raydemo/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mickare/git/raydemo/venv/lib/python3.9/site-packages/ray/scripts/scripts.py", line 971, in up
    create_or_update_cluster(
  File "/Users/mickare/git/raydemo/venv/lib/python3.9/site-packages/ray/autoscaler/_private/commands.py", line 233, in create_or_update_cluster
    config = _bootstrap_config(config, no_config_cache=no_config_cache)
  File "/Users/mickare/git/raydemo/venv/lib/python3.9/site-packages/ray/autoscaler/_private/commands.py", line 316, in _bootstrap_config
    resolved_config = provider_cls.bootstrap_config(config)
  File "/Users/mickare/git/raydemo/venv/lib/python3.9/site-packages/ray/autoscaler/_private/_azure/node_provider.py", line 309, in bootstrap_config
    return bootstrap_azure(cluster_config)
  File "/Users/mickare/git/raydemo/venv/lib/python3.9/site-packages/ray/autoscaler/_private/_azure/config.py", line 22, in bootstrap_azure
    config = _configure_resource_group(config)
  File "/Users/mickare/git/raydemo/venv/lib/python3.9/site-packages/ray/autoscaler/_private/_azure/config.py", line 58, in _configure_resource_group
    resource_client.resource_groups.create_or_update(
  File "/Users/mickare/git/raydemo/venv/lib/python3.9/site-packages/azure/mgmt/resource/resources/v2021_04_01/operations/_resource_groups_operations.py", line 154, in create_or_update
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/Users/mickare/git/raydemo/venv/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/Users/mickare/git/raydemo/venv/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/mickare/git/raydemo/venv/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/mickare/git/raydemo/venv/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/Users/mickare/git/raydemo/venv/lib/python3.9/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/Users/mickare/git/raydemo/venv/lib/python3.9/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/Users/mickare/git/raydemo/venv/lib/python3.9/site-packages/azure/core/pipeline/policies/_retry.py", line 445, in send
    response = self.next.send(request)
  File "/Users/mickare/git/raydemo/venv/lib/python3.9/site-packages/azure/core/pipeline/policies/_authentication.py", line 117, in send
    self.on_request(request)
  File "/Users/mickare/git/raydemo/venv/lib/python3.9/site-packages/azure/core/pipeline/policies/_authentication.py", line 94, in on_request
    self._token = self._credential.get_token(*self._scopes)
  File "/Users/mickare/git/raydemo/venv/lib/python3.9/site-packages/azure/common/credentials.py", line 72, in get_token
    _, token, fulltoken = credentials._token_retriever()  # pylint:disable=protected-access
AttributeError: 'CredentialAdaptor' object has no attribute '_token_retriever'

```

**Additional context**
It seems that the commons' credential class is expecting another type from the internal `_cred_dict` dictionary?
Maybe a type check is missing?

**Comment by launchpad15** [comment]
@azure-sdk

**Comment by xiangyan99** [comment]
Could you share more information how you pass in the credential when you provision the resource?

**Comment by mickare** [comment]
@xiangyan99 There is no "passing" of the credential. It should be automatically deducted from the azure CLI as credential provider. See: https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/_private/_azure/config.py#L37

Ray's autoscaller calls [`def get_client_from_cli_profile(client_class, **kwargs):` in azure commons](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-common/azure/common/client_factory.py#L50).

```py
def get_client_from_cli_profile(client_class, **kwargs):
    """Return a SDK client initialized with current CLI credentials, CLI default subscription and CLI default cloud.
    This method will fill automatically the following client parameters:
    - credentials/credential
    - subscription_id
    - base_url
    Parameters provided in kwargs will override CLI parameters and be passed directly to the client.
    ...
    """
```


@mario-s-duarte Cool & thanks for the hint. Still, I think it is a major bug in the Azure SDK.

**Comment by xiangyan99** [comment]
Looks like you are using track 1 auth system which is not fully compatible with track 2 libraries (azure-core is track 2 library).

You can refer https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/migration_guide.md#authenticating-through-the-azure-CLI to see how to migrate.

**Comment by mickare** [comment]
Please mark deprecated methods. E.g. [use a `@deprecated` annotation](https://stackoverflow.com/a/30253848).
