### ISSUE TITLE
Not able to authenticate using certificate based service principle on ADFS based Azure Stack environment.

### ISSUE THREAD

**Issue by pyprateek** [Azure/azure-sdk-for-python#22181]
I created Certificate-based service principle on Azure Stack setup. I am getting following exception while firing any API:
The below exception is when the certificate is passed in PEM format.

Traceback (most recent call last):
  File "/root/ADFScert.py", line 60, in <module>
    for vm in vm_list:
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/mgmt/compute/v2017_12_01/operations/_virtual_machines_operations.py", line 1238, in get_next
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/core/pipeline/policies/_retry.py", line 445, in send
    response = self.next.send(request)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/core/pipeline/policies/_authentication.py", line 117, in send
    self.on_request(request)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/core/pipeline/policies/_authentication.py", line 94, in on_request
    self._token = self._credential.get_token(*self._scopes)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/identity/_internal/get_token_mixin.py", line 72, in get_token
    token = self._request_token(*scopes)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/identity/_internal/decorators.py", line 45, in wrapper
    return fn(*args, **kwargs)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/identity/_internal/client_credential_base.py", line 42, in _request_token
    raise ClientAuthenticationError(message=message)
azure.core.exceptions.ClientAuthenticationError: Authentication failed: MSIS9622: Client authentication failed. Please verify the credential provided for client authentication is valid.

The certificate was downloaded from Azure Stack machine in PFX format and converted to PEM using below command.
openssl pkcs12 -in VtasAZS-app2-AES256.pfx -out encrypted-cert.pem -nodes

The below code is used for this:
`credentials = CertificateCredential(tenant_id, client_id, certificate_path=path, **kwargs)
scope = "openid profile offline_access" + " " + resource + "/.default"
computeclient = ComputeManagementClient(credentials, subscription_id, base_url=base_url,
                                        profile=KnownProfiles.v2019_03_01_hybrid, resource=resource, credential_scopes=[scope])
vm_list = computeclient.virtual_machines.list_all()
for vm in vm_list:
    print('vm name is %s', vm.name)`

We have tried this with python SDK and powershell also.
On the same setup, there is client-secret based service principle also created, using which authentication is working fine,

Can someone help with this?

**Comment by yunhaoling** [comment]
thanks @pyprateek for reaching out! we'll investigate it ASAP.

**Comment by xiangyan99** [comment]
@azure stack folks, could you help to check if this is the right way to get certificate for azure stack use?
