### ISSUE TITLE
Azure function: AttributeError: 'SubscriptionClient' object has no attribute 'subscriptions'

### ISSUE THREAD

**Issue by DohyeonEom** [Azure/azure-sdk-for-python#22273]
- Package Name: azure-mgmt-subscription
 - Package Version: 2.0.0

I'm using Azure function app, durable function for listing the subscriptions and go through each sub to do some process. My code was working fine until a few days ago that it stopped to work by giving this error:
AttributeError: 'SubscriptionClient' object has no attribute 'subscriptions'

I got this result after upgrading the package version. (azure-mgmt-subscription 1.0.0 -> 2.0.0)

https://docs.microsoft.com/en-us/python/api/azure-mgmt-subscription/azure.mgmt.subscription.subscriptionclient?view=azure-python This document does not apply to the 2.0.0 version any more.

How to get list of subscriptions from upgraded module?

**Comment by tjprescott** [comment]
@msyyc can you please address?

**Comment by msyyc** [comment]
According to [CHANGELOG](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/subscription/azure-mgmt-subscription/CHANGELOG.md#200-2021-11-25), `azure-mgmt-subscriptions==2.0.0` removes `SubscriptionsOperations`. You could try to use latest `azure-mgmt-resource`.
```
from azure.mgmt.resource.subscriptions import SubscriptionClient
```
It still has `SubscriptionsOperations`

**Comment by DohyeonEom** [comment]
Thank.
I found a guide on using azure-mgmt-resource and
Tried to follow the guide.
[](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate-user-credentials)

```
credential = ClientSecretCredential(
        tenant_id=tenant_id,
        client_id=client_id,
        client_secret=client_secret
        )

subscription_client = SubscriptionClient(credential)

subscription = next(subscription_client.subscriptions.list())
print(subscription.subscription_id)
```

However, the following message occurs:
```
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    subscription = next(subscription_client.subscriptions.list())
  File "/root/acc/lib/python3.8/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
StopIteration
```
am i missing something?
I need help.

**Comment by msyyc** [comment]
Here is the sample : https://github.com/Azure-Samples/azure-samples-python-management/blob/main/samples/resources/manage_resource_subscriptions.py#L23-L26

**Comment by DohyeonEom** [comment]
@msyyc 
I solved it by referring to the sample.
thank you.

**Comment by DohyeonEom** [comment]
I solved it by referring to the sample.
thank you.
