### ISSUE TITLE
DeserializationError when calling virtual_machine_scale_sets.begin_deallocate()

### ISSUE THREAD

**Issue by mjneuharth** [Azure/azure-sdk-for-python#22488]
- **Package Name**: azure-mgmt-compute
- **Package Version**: 24.0.0
- **Operating System**: MacOS 12.1
- **Python Version**: 3.9.9

**Describe the bug**
I am working with virtual machine scale sets in this python. I have elsewhere been able to call, for example, **virtual_machine_scale_sets.begin_create_or_update()** to throw a revised scale_set object at the scale set to increase the capacity from 1 to 3 instances.

In the instance of the **begin_deallocate()** method, I am getting this error when attempting to use this method with one or two instanceIds in a list,

`msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'list' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'list' object has no attribute 'get'`

I realize that msrest is implicated in the error but I wonder whether it is how azure-mgmt-compute is interacting with msrest that is the issue...

The specific python in this case looks like this,

`
 client_compute.virtual_machine_scale_sets.begin_deallocate(
     rg[key]['Name'],
     rg[key]['ScaleSet']['Name'],
     scale_victims
 )
`

Where 
- **rg[key]['Name']** contains the name of the resource group where my scale set resides
- **rg[key]['ScaleSet']['Name']** contains the name of the scale set
- scale_victims is a list of instanceIds (here: ['0', '2'])

Here, scale_victims is a list of str, as necessitated by the **begin_deallocate** method,

1. https://docs.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2021_07_01.operations.virtualmachinescalesetsoperations?view=azure-python#azure-mgmt-compute-v2021-07-01-operations-virtualmachinescalesetsoperations-begin-deallocate
2. https://docs.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2021_07_01.models.virtualmachinescalesetvminstanceids?view=azure-python

**To Reproduce**
1. Use the begin_deallocate() method against a working scale set with one of the instanceIds (in a list) in the scale set.

**Expected behavior**
I would have expected no errors and that the included instanceIds would be deallocated from the from scale set

**Additional context**
Here's the full output from the errors I am receiving within the venv where I am working,

I have inserted **<TRUNCATED_PATH>** to remove some of the noise

Traceback (most recent call last):
  File "<TRUNCATED_PATH>/.venv/lib/python3.9/site-packages/msrest/serialization.py", line 1428, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "<TRUNCATED_PATH>/.venv/lib/python3.9/site-packages/msrest/serialization.py", line 1193, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "<TRUNCATED_PATH>/.venv/lib/python3.9/site-packages/msrest/serialization.py", line 1222, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
AttributeError: 'list' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<TRUNCATED_PATH>/.venv/lib/python3.9/site-packages/msrest/serialization.py", line 620, in body
    data = deserializer._deserialize(data_type, data)
  File "<TRUNCATED_PATH>/.venv/lib/python3.9/site-packages/msrest/serialization.py", line 1446, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "<TRUNCATED_PATH>/.venv/lib/python3.9/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "<TRUNCATED_PATH>/.venv/lib/python3.9/site-packages/msrest/serialization.py", line 1428, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "<TRUNCATED_PATH>/.venv/lib/python3.9/site-packages/msrest/serialization.py", line 1193, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "<TRUNCATED_PATH>/.venv/lib/python3.9/site-packages/msrest/serialization.py", line 1222, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, AttributeError: 'list' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<TRUNCATED_PATH>/finpack_scaler.py", line 539, in <module>
    main()
  File "<TRUNCATED_PATH>/finpack_scaler.py", line 516, in main
    client_compute.virtual_machine_scale_sets.begin_deallocate(
  File "<TRUNCATED_PATH>/.venv/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "<TRUNCATED_PATH>/.venv/lib/python3.9/site-packages/azure/mgmt/compute/v2021_07_01/operations/_virtual_machine_scale_sets_operations.py", line 1514, in begin_deallocate
    raw_result = self._deallocate_initial(
  File "<TRUNCATED_PATH>/.venv/lib/python3.9/site-packages/azure/mgmt/compute/v2021_07_01/operations/_virtual_machine_scale_sets_operations.py", line 1446, in _deallocate_initial
    _json = self._serialize.body(vm_instance_i_ds, 'VirtualMachineScaleSetVMInstanceIDs')
  File "<TRUNCATED_PATH>/.venv/lib/python3.9/site-packages/msrest/serialization.py", line 622, in body
    raise_with_traceback(
  File "<TRUNCATED_PATH>/.venv/lib/python3.9/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "<TRUNCATED_PATH>/.venv/lib/python3.9/site-packages/msrest/serialization.py", line 620, in body
    data = deserializer._deserialize(data_type, data)
  File "<TRUNCATED_PATH>/.venv/lib/python3.9/site-packages/msrest/serialization.py", line 1446, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "<TRUNCATED_PATH>/.venv/lib/python3.9/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "<TRUNCATED_PATH>/.venv/lib/python3.9/site-packages/msrest/serialization.py", line 1428, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "<TRUNCATED_PATH>/.venv/lib/python3.9/site-packages/msrest/serialization.py", line 1193, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "<TRUNCATED_PATH>/.venv/lib/python3.9/site-packages/msrest/serialization.py", line 1222, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'list' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'list' object has no attribute 'get'

**Comment by mccoyp** [comment]
Hi @mjneuharth, thank you for opening an issue! I'll tag the appropriate folks so we can look into this as soon as possible.

**Comment by BigCat20196** [comment]
Hi @mjneuharth, thanks for your feedback !

About `scale_victims` in your code, which cannot be passed directly as a parameter. After my investigation, it needs to use the `VirtualMachineScaleSetVMInstanceIDs` model to help it transform.

like this:
```
from azure.mgmt.compute.models import VirtualMachineScaleSetVMInstanceIDs

scale_victims = VirtualMachineScaleSetVMInstanceIDs(instance_ids=scale_victims)
client_compute.virtual_machine_scale_sets.begin_deallocate( rg[key]['Name'], rg[key]['ScaleSet']['Name'], scale_victims )
```

pls let me know if I could help more.

**Comment by mjneuharth** [comment]
Now that I see what I missed here in the documentation, I see it everywhere.

Thanks for the answer and the help!
