### ISSUE TITLE
`conda` builds failing to activate conda environment 

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#22498]
Going to temporarily disable to investigate. [Failure Example](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1294466&view=logs&j=b802d761-4de6-5d2b-4125-4029375fdf3c&t=31dafbb5-4fef-5d1f-1a95-3d624645488a&l=65)

Error looks like:

```
source /usr/share/miniconda/bin/activate azure-core
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/azure-core/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/share/miniconda/envs/azure-core/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/share/miniconda/envs/azure-core/lib/python3.9/site-packages/pytest/__main__.py", line 7, in <module>
    raise SystemExit(pytest.main())
  File "/usr/share/miniconda/envs/azure-core/lib/python3.9/site-packages/_pytest/config/__init__.py", line 105, in main
    config = _prepareconfig(args, plugins)
  File "/usr/share/miniconda/envs/azure-core/lib/python3.9/site-packages/_pytest/config/__init__.py", line 257, in _prepareconfig
    return pluginmanager.hook.pytest_cmdline_parse(
  File "/usr/share/miniconda/envs/azure-core/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/share/miniconda/envs/azure-core/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/share/miniconda/envs/azure-core/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/usr/share/miniconda/envs/azure-core/lib/python3.9/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/share/miniconda/envs/azure-core/lib/python3.9/site-packages/_pytest/helpconfig.py", line 90, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/usr/share/miniconda/envs/azure-core/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/share/miniconda/envs/azure-core/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/share/miniconda/envs/azure-core/lib/python3.9/site-packages/_pytest/config/__init__.py", line 836, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/share/miniconda/envs/azure-core/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1044, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/share/miniconda/envs/azure-core/lib/python3.9/site-packages/_pytest/config/__init__.py", line 992, in _preparse
```

Occurrences starting ~noon today.

![image](https://user-images.githubusercontent.com/45376673/149416178-0c276471-7b4d-421f-a151-c953ea965236.png)

This is an agent change. I haven't touched this process in a while.

Update 7/12/2022 Now it's also occurring with [this PR](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1703356&view=logs&jobId=b802d761-4de6-5d2b-4125-4029375fdf3c)

**Comment by zooba** [comment]
Looks like it's probably mismatched pytest_asyncio version:

```
<all the traceback above>
...
  File "/usr/share/miniconda/envs/azure-core/lib/python3.9/site-packages/pytest_asyncio/plugin.py", line 53, in pytest_addoption
    parser.addini(
  File "/usr/share/miniconda/envs/azure-core/lib/python3.9/site-packages/_pytest/config/argparsing.py", line 177, in addini
    assert type in (None, "pathlist", "args", "linelist", "bool")
```
