### ISSUE TITLE
Azure Key Vault - Error while reading a certificate with KeyType 'rsa' using Python SDK

### ISSUE THREAD

**Issue by mccoyp** [Azure/azure-sdk-for-python#22797]
This issue is named after the ICM describing the bug: https://portal.microsofticm.com/imp/v3/incidents/details/284919597

Below is a stack trace of the error a user got when trying to get a certificate that was created outside the SDK with a key type of "rsa" (specified in lower case). The root of the issue seems to be that the `key_type` property of the fetched certificate's KeyProperties is the string `"rsa"`, which we would usually expect to be in all upper case. Calling `KeyType("rsa")` raises the error below.

```
2022-01-19 08:23:59,899 azure.core.pipeline.policies.http_logging_policy INFO         'Content-Length': '3467'
ValueError: 'rsa' is not a valid KeyType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 14, in <module>
    cert = cert_client.get_certificate('adapter-service')
  File "/usr/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/azure/keyvault/certificates/_client.py", line 169, in get_certificate
    return KeyVaultCertificate._from_certificate_bundle(certificate_bundle=bundle)
  File "/usr/lib/python3.8/site-packages/azure/keyvault/certificates/_models.py", line 325, in _from_certificate_bundle
    policy = CertificatePolicy._from_certificate_policy_bundle(certificate_bundle.policy)
  File "/usr/lib/python3.8/site-packages/azure/keyvault/certificates/_models.py", line 824, in _from_certificate_policy_bundle
    key_type=KeyType(key_properties.key_type) if key_properties and key_properties.key_type else None,
  File "/usr/lib/python3.8/enum.py", line 304, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.8/enum.py", line 595, in __new__
    raise exc
  File "/usr/lib/python3.8/enum.py", line 579, in __new__
    result = cls._missing_(value)
  File "/usr/lib/python3.8/enum.py", line 608, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'rsa' is not a valid KeyType
```

One solution would be to ignore casing when declaring a KeyType, which may be necessary in at least some cases since the service can evidently return lower-cased key types. We could also try to upper-case the `key_type` we get from a certificate bundle before referencing KeyType without changing how the enum is used.

**Comment by mccoyp** [comment]
Status update: currently waiting to see if we can learn more about the user's ability to use the certificate in question. Cryptographic keys generally have to have case-sensitive key types, so it's surprising that a key with an "rsa" key type was created in the first place. If this isn't meant to happen, we probably shouldn't support case-insensitive key type creation.

**Comment by mccoyp** [comment]
From user:
> This is the first time we have used the Python SDK to get these certificates. They can be downloaded using the CLI. And I think the .NET client libraries work also.
>
> I'm guessing this is an issue with the Python SDK. It uses an enum to represent the key type, and enums in Python are case sensitive when constructed from a string, e.g. like here:
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_models.py#L832

If these certificates exist in Key Vault and can be downloaded by other means, I think it makes sense to support retrieving them through the Python SDK as well. It doesn't guarantee that the key can be used, but case-sensitivity and formatting requirements are the service's concern. We should be able to represent output that the service presents us with.

**Comment by mccoyp** [comment]
A fix for this issue will be included in the next stable release of Key Vault packages (currently planned for early March).
