### ISSUE TITLE
SM client should follow redirects

### ISSUE THREAD

**Issue by paulmey** [Azure/azure-sdk-for-python#228]
RDFE sometimes issues a redirect to another instance. The client library should follow the redirect (instead of throwing an exception):

Traceback (most recent call last):
  File "c:\python34\lib\site-packages\azure\servicemanagement\servicemanagementclient.py", line 95, in _perform_request
    resp = self._filter(request)
  File "c:\python34\lib\site-packages\azure\http\httpclient.py", line 211, in perform_request
    self.respheader, respbody)
azure.http.HTTPError: Temporary Redirect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "myscript.py", line 17, in <module>
    sub = sms.get_subscription();
  File "c:\python34\lib\site-packages\azure\servicemanagement\servicemanagementservice.py", line 981, in get_subscription
    Subscription)
  File "c:\python34\lib\site-packages\azure\servicemanagement\servicemanagementclient.py", line 108, in _perform_get
    response = self._perform_request(request)
  File "c:\python34\lib\site-packages\azure\servicemanagement\servicemanagementclient.py", line 97, in _perform_request
    return _management_error_handler(ex)
  File "c:\python34\lib\site-packages\azure\servicemanagement\__init__.py", line 983, in _management_error_handler
    return _general_error_handler(http_error)
  File "c:\python34\lib\site-packages\azure\__init__.py", line 844, in _general_error_handler
    raise WindowsAzureError(_ERROR_UNKNOWN.format(str(http_error)))
azure.WindowsAzureError: Unknown error (Temporary Redirect)

**Comment by huguesv** [comment]
Closing, if you still have trouble using the latest SDK, please reopen an issue.
