### ISSUE TITLE
use azure-sdk-for-python, error SubscriptionNotFound

### ISSUE THREAD

**Issue by Liuzhj** [Azure/azure-sdk-for-python#2302]
my code:

```
GROUP_NAME = 'clusters'
subscription_id = '1f665246-xxxx-433c-b512-ff18f570edd3'
credentials = UserPassCredentials('xxx@xxrvicex1.partner.onmschina.cn', 'xxx', cloud_environment=AZURE_CHINA_CLOUD)

compute_client = ComputeManagementClient(credentials, subscription_id)

for vm in compute_client.virtual_machines.list(GROUP_NAME):
    print("\tVM: {}".format(vm.name))
```

```
Traceback (most recent call last):
  File "china.py", line 16, in <module>
    for vm in compute_client.virtual_machines.list(GROUP_NAME):
  File "/home/xx@xx.com/hadoop-wd_python_env/lib/python2.7/site-packages/msrest-0.4.27-py2.7.egg/msrest/paging.py", line 121, in __next__
    self.advance_page()
  File "/home/xx@xx.com/hadoop-wd_python_env/lib/python2.7/site-packages/msrest-0.4.27-py2.7.egg/msrest/paging.py", line 107, in advance_page
    self._response = self._get_next(self.next_link)
  File "/home/xx@xx.com/hadoop-wd_python_env/lib/python2.7/site-packages/azure_mgmt_compute-3.1.0rc3-py2.7.egg/azure/mgmt/compute/v2017_12_01/operations/virtual_machines_operations.py", line 863, in internal_paging
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: SubscriptionNotFound
Message: The subscription '1f665246-xxx-433c-b512-ff18f570edd3' could not be found.
```

I'm sure the subscription is correct , i don't know what happend , 
how to solve it ? 
Thanks.

**Comment by Liuzhj** [comment]
I'm used Azure China , may be  need to add some parameter in my code,

**Comment by prburgu** [comment]
Yes, I think you would need to pass `base_url` parameter for `ComputeManagementClient`. I think, the default is `https://management.azure.com` and for China cloud it could be different.

**Comment by Liuzhj** [comment]
@prburgu Thank you very much , this problem is solved ,Thank you .

**Comment by sagu94271** [comment]
@Liuzhj Can you also provide the python code by which we can set base_url parameter for ComputeManagementClient.

**Comment by khaoulaB1** [comment]
**my code :** 
def run_example():
    """Resource Group management example."""
    
    # Create the Resource Manager Client with an Application (service principal) token provider
subscription_id = os.environ.get(
       'AZURE_SUBSCRIPTION_ID',
       'xxxxxxxxxxxxxxxxxxxxxxxx')
credentials = ServicePrincipalCredentials(
    client_id = 'xxxxxxxxxxxxxxxxxx',
    secret = 'xxxxxxxxxxxxxxxxxx',
    tenant = 'xxxxxxxxxxx'
)
authorization_client = AuthorizationManagementClient(
    credentials,
    subscription_id
)
resource_client = ResourceManagementClient(
    credentials,
    subscription_id
)

print("List Resource Groups")
for item in resource_client.resource_groups.list():
    print_item(item)
 **The error:**

]# python example.py
List Resource Groups
Traceback (most recent call last):
  File "example.py", line 53, in <module>
    for item in resource_client.resource_groups.list():
  File "/usr/lib/python2.7/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/usr/lib/python2.7/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/usr/lib/python2.7/site-packages/azure/mgmt/resource/resources/v2018_05_01/operations/resource_groups_operations.py", line 517, in internal_paging
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: InvalidSubscriptionId
Message: The provided subscription identifier '{xxxxxxxxxxxxxxxxxxxxxxxx}' is malformed or invalid.


Any help with this please i'm trying to manage azure ressource group with a python api
