### ISSUE TITLE
azure-mgmt-sql - create sql server is broken

### ISSUE THREAD

**Issue by prburgu** [Azure/azure-sdk-for-python#2306]
With `0.8.6 (2018-03-22)` version of `azure-mgmt-sql`, create sql server is broken. Getting the following error with Python 3. Downgrading to `0.8.5 (2018-01-18)` fixes the issue.

```
2018-03-29T17:04:29.4238366Z   File "/mnt/data_disk/vsts/vsts-agent/agent-0/_work/28/s/test/miniconda/lib/python3.5/site-packages/azure/mgmt/sql/operations/servers_operations.py", line 394, in create_or_update
2018-03-29T17:04:29.4258486Z     **operation_config
2018-03-29T17:04:29.4277918Z   File "/mnt/data_disk/vsts/vsts-agent/agent-0/_work/28/s/test/miniconda/lib/python3.5/site-packages/azure/mgmt/sql/operations/servers_operations.py", line 318, in _create_or_update_initial
2018-03-29T17:04:29.4297909Z     url = self.create_or_update.metadata['url']
2018-03-29T17:04:29.4316476Z AttributeError: 'function' object has no attribute 'metadata'
```

**Comment by lmazuel** [comment]
Could you precise what version of Python? I can't reproduce the issue.

**Comment by prburgu** [comment]
```
Python 3.5.4 |Continuum Analytics, Inc.| (default, Aug 14 2017, 12:43:10)
```

**Comment by lmazuel** [comment]
Cannot reproduce it:
```shell
> conda create -n env3.5-conda python=3.5
> conda activate env3.5-conda
> pip install azure-mgmt-sql==0.8.6
> python
```
```python
>>> from azure.mgmt.sql import *
>>> from msrest.authentication import Authentication
>>> client = SqlManagementClient(Authentication(), "subscriptionid")
>>> client.servers.create_or_update("RGNAME", "SERVERNAME", {"location":"westus"})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\lmazuel\AppData\Local\conda\conda\envs\env3.5-conda\lib\site-packages\azure\mgmt\sql\operations\servers_operations.py", line 394, in create_or_update
    **operation_config
  File "C:\Users\lmazuel\AppData\Local\conda\conda\envs\env3.5-conda\lib\site-packages\azure\mgmt\sql\operations\servers_operations.py", line 351, in _create_or_update_initial
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: SubscriptionNotFound
Message: The subscription 'subscriptionid' could not be found.
```
This message is way later then the exception you get. I can also confirm that the attribute is here:
```
>>> from azure.mgmt.sql.operations import *
>>> print(ServersOperations.create_or_update.metadata)
{'url': '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}'}
```

So my guess is you have a corrupted env somehow.

**Comment by prburgu** [comment]
The above steps are not reproducing the problem for me either. However, our tests are failing with the following error even with fresh env.

```
2018-03-30T17:36:25.2021870Z   File "/mnt/data_disk/vsts/vsts-agent/agent-0/_work/28/s/azure/tests/test_db.py", line 44, in test_create_and_update_sql_server
2018-03-30T17:36:25.2038455Z     self._create_server()
2018-03-30T17:36:25.2053976Z   File "/mnt/data_disk/vsts/vsts-agent/agent-0/_work/28/s/azure/tests/test_db.py", line 54, in _create_server
2018-03-30T17:36:25.2070168Z     self.admin_passwd)
2018-03-30T17:36:25.2086837Z   File "/mnt/data_disk/vsts/vsts-agent/agent-0/_work/28/s/azure/accloud/acazure/operations/sqlserver_operations.py", line 95, in create_sql_server
2018-03-30T17:36:25.2103416Z     administrator_login_password=admin_passwd
2018-03-30T17:36:25.2120192Z   File "/mnt/data_disk/vsts/vsts-agent/agent-0/_work/28/s/azure/miniconda/lib/python3.5/site-packages/retrying.py", line 49, in wrapped_f
2018-03-30T17:36:25.2136862Z     return Retrying(*dargs, **dkw).call(f, *args, **kw)
2018-03-30T17:36:25.2153252Z   File "/mnt/data_disk/vsts/vsts-agent/agent-0/_work/28/s/azure/miniconda/lib/python3.5/site-packages/retrying.py", line 206, in call
2018-03-30T17:36:25.2170003Z     return attempt.get(self._wrap_exception)
2018-03-30T17:36:25.2186668Z   File "/mnt/data_disk/vsts/vsts-agent/agent-0/_work/28/s/azure/miniconda/lib/python3.5/site-packages/retrying.py", line 247, in get
2018-03-30T17:36:25.2203650Z     six.reraise(self.value[0], self.value[1], self.value[2])
2018-03-30T17:36:25.2220244Z   File "/mnt/data_disk/vsts/vsts-agent/agent-0/_work/28/s/azure/miniconda/lib/python3.5/site-packages/six.py", line 693, in reraise
2018-03-30T17:36:25.2236771Z     raise value
2018-03-30T17:36:25.2252935Z   File "/mnt/data_disk/vsts/vsts-agent/agent-0/_work/28/s/azure/miniconda/lib/python3.5/site-packages/retrying.py", line 200, in call
2018-03-30T17:36:25.2269489Z     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
2018-03-30T17:36:25.2285913Z   File "/mnt/data_disk/vsts/vsts-agent/agent-0/_work/28/s/azure/accloud/acazure/acazure_clients.py", line 97, in wrapped
2018-03-30T17:36:25.2302236Z     return func(*args, **kwargs)
2018-03-30T17:36:25.2319769Z   File "/mnt/data_disk/vsts/vsts-agent/agent-0/_work/28/s/azure/miniconda/lib/python3.5/site-packages/azure/mgmt/sql/operations/servers_operations.py", line 394, in create_or_update
2018-03-30T17:36:25.2337403Z     **operation_config
2018-03-30T17:36:25.2354275Z   File "/mnt/data_disk/vsts/vsts-agent/agent-0/_work/28/s/azure/miniconda/lib/python3.5/site-packages/azure/mgmt/sql/operations/servers_operations.py", line 318, in _create_or_update_initial
2018-03-30T17:36:25.2375132Z     url = self.create_or_update.metadata['url']
2018-03-30T17:36:25.2393874Z AttributeError: 'function' object has no attribute 'metadata'
```
Looking at the code it has something like this.

```
    def _create_or_update_initial(
            self, resource_group_name, server_name, parameters, custom_headers=None, raw=False, **operation_config):
        api_version = "2015-05-01-preview"

        # Construct URL
        url = self.create_or_update.metadata['url']
```

```
    def create_or_update(
            self, resource_group_name, server_name, parameters, custom_headers=None, raw=False, **operation_config):
```

```
    create_or_update.metadata = {'url': '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}'}
```

It appears `create_or_update` is defined as a function as well as a member. May be you should change the member name or get the url in `_create_or_update_initial` as follows.
```
        # Construct URL
        url = create_or_update.metadata['url']
```

**Comment by lmazuel** [comment]
Seems you're using a wrapping function:
```python
   File "/mnt/data_disk/vsts/vsts-agent/agent-0/_work/28/s/azure/accloud/acazure/acazure_clients.py", line 97, in wrapped
     return func(*args, **kwargs)
```
My guess is that in the process of wrapping the function, you lost the metadata dictionary associated to the function. Could you share a little more code about your wrapper?

**Comment by prburgu** [comment]
Here are the details about wrapper.

```
def count_ops(func, operation_name):
    def wrapped(*args, **kwargs):
        if operation_name not in AZURE_OP_COUNT:
            AZURE_OP_COUNT[operation_name] = 0
        AZURE_OP_COUNT[operation_name] += 1
        return func(*args, **kwargs)
    return wrapped
```

```
def wrap_operations_with_retry(azure_client):
    # Wrap every method of the *Operations objects with retry logic
    for attr_name in dir(azure_client):
        if not attr_name.startswith("_"):
            attr = getattr(azure_client, attr_name)
            if attr.__class__.__name__.endswith("Operations"):
                for method_name, method in inspect.getmembers(attr, inspect.ismethod):
                    if not method_name.startswith("_"):
                        operation_name = attr.__class__.__name__ + "." + method_name
                        setattr(attr,
                                method_name,
                                retry(**default_retry_kwargs)(count_ops(method, operation_name))
                               )
```

**Comment by lmazuel** [comment]
Ok, so that's definitely the problem. You replace the method by a new one that doesn't have the attribute. After your `setattr`, you should do something like:
```python
try:
    wrapped_method = getattr(attr, method_name)
    setattr(wrapped_method, "metadata", method.metadata)
except AttributeError:
    pass  # This version of SDK has no metadata dict
```

**Comment by prburgu** [comment]
Thank you. I tried this and it works great. Closing this ticket.
