### ISSUE TITLE
resolve dependency issue with sphinx doc generation and markupsafe

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#23133]
Seeing this error in the "Generate Docs" step of CI:

```
INFO:root:Sphinx api-doc command: ['sphinx-apidoc', '--no-toc', '--module-first', '-o', '.tox/dist/unzipped/docgen', '.tox/dist/unzipped/', '.tox/dist/unzipped/test*', '.tox/dist/unzipped/example*', '.tox/dist/unzipped/sample*', '.tox/dist/unzipped/setup.py']
Traceback (most recent call last):
  File "/mnt/vss/_work/1/s/sdk/formrecognizer/azure-ai-formrecognizer/.tox/sphinx/bin/sphinx-apidoc", line 5, in <module>
    from sphinx.ext.apidoc import main
  File "/mnt/vss/_work/1/s/sdk/formrecognizer/azure-ai-formrecognizer/.tox/sphinx/lib/python3.9/site-packages/sphinx/ext/apidoc.py", line 31, in <module>
    from sphinx.cmd.quickstart import EXTENSIONS
  File "/mnt/vss/_work/1/s/sdk/formrecognizer/azure-ai-formrecognizer/.tox/sphinx/lib/python3.9/site-packages/sphinx/cmd/quickstart.py", line 44, in <module>
    from sphinx.util.template import SphinxRenderer
  File "/mnt/vss/_work/1/s/sdk/formrecognizer/azure-ai-formrecognizer/.tox/sphinx/lib/python3.9/site-packages/sphinx/util/template.py", line 16, in <module>
    from jinja2 import TemplateNotFound
  File "/mnt/vss/_work/1/s/sdk/formrecognizer/azure-ai-formrecognizer/.tox/sphinx/lib/python3.9/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/mnt/vss/_work/1/s/sdk/formrecognizer/azure-ai-formrecognizer/.tox/sphinx/lib/python3.9/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/mnt/vss/_work/1/s/sdk/formrecognizer/azure-ai-formrecognizer/.tox/sphinx/lib/python3.9/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/mnt/vss/_work/1/s/sdk/formrecognizer/azure-ai-formrecognizer/.tox/sphinx/lib/python3.9/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe'
```

Example build: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1376909&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=651a14cc-88df-515d-1311-e0e8b23b578a&l=1229

`sphinx` uses `jinja2` which takes a dependency on a library called [markupsafe](https://pypi.org/project/markupsafe/).
 `markupsafe` released a new package, 2.1.0, which appears to have breaking changes which are failing our CI.

**Comment by scbedd** [comment]
Resolved in #23132
