### ISSUE TITLE
ServiceBus timeout exception type

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [Azure/azure-sdk-for-python#23217]
- **Package Name**: service-bus
- **Package Version**: 7.3.3
- **Operating System**: Linux
- **Python Version**: 3.9

**Describe the bug**
Due to authorization timeout in amqp layer, we got an exception like

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/azure/servicebus/aio/_base_handler_async.py", line 246, in _do_retryable_operation
    return await operation(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/azure/servicebus/aio/_servicebus_receiver_async.py", line 318, in _open
    while not await self._handler.client_ready_async():
  File "/usr/local/lib/python3.9/site-packages/uamqp/async_ops/client_async.py", line 356, in client_ready_async
    if not await self.auth_complete_async():
  File "/usr/local/lib/python3.9/site-packages/uamqp/async_ops/client_async.py", line 342, in auth_complete_async
    raise TimeoutException("Authorization timeout.")
TimeoutError: Authorization timeout.
```

however, in other context a `Timeout` from amqp is mapped to OperationTimeoutError

https://github.com/Azure/azure-sdk-for-python/blob/f68dd959a659579d299177195ea846b01aa16dc2/sdk/servicebus/azure-servicebus/azure/servicebus/aio/_base_handler_async.py#L347

which is much nicer to deal with.

**Expected behavior**
Receive an exception of type OperationTimeoutError

**Comment by andrea-cassioli-maersk** [comment]
Sorry, I have not realised that the exception is actually caught and does not bubble up to the caller.
