### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable in msal_client.py

### ISSUE THREAD

**Issue by micafer** [Azure/azure-sdk-for-python#23483]
- **Azure.Identity**: 
- **1.8.0**: 
- **Ubuntu 20.04**:
- **Python 3.8**: 

**Describe the bug**

Sometimes when authenticating with ClientSecretCredential class I get this error:

```py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/azure/identity/_internal/decorators.py", line 56, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/azure/identity/_credentials/user_password.py", line 58, in _request_token
    return app.acquire_token_by_username_password(
  File "/usr/local/lib/python3.8/dist-packages/msal/application.py", line 1417, in acquire_token_by_username_password
    user_realm_result = self.authority.user_realm_discovery(
  File "/usr/local/lib/python3.8/dist-packages/msal/authority.py", line 128, in user_realm_discovery
    resp.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/azure/identity/_internal/msal_client.py", line 55, in raise_for_status
    if "error" in content or "error_description" in content:
TypeError: argument of type 'NoneType' is not iterable
```

**To Reproduce**
The error appears sometimes, I cannot reproduce the error with a fixed set ot steps.

**Expected behavior**

It should raise a ClientAuthenticationError with the correct error.

**Additional context**

I suggest to change this line:
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/azure/identity/_internal/msal_client.py#L53

from:
```py
if ContentDecodePolicy.CONTEXT_NAME in self._response.context:
```
to:
```py
if ContentDecodePolicy.CONTEXT_NAME in self._response.context and self._response.context[ContentDecodePolicy.CONTEXT_NAME]:
```

**Comment by catalinaperalta** [comment]
Thanks for reporting this @micafer! We'll investigate and get back to you ASAP.

**Comment by xiangyan99** [comment]
Thanks for reporting the issue. The fix has been merged and will be available in next release.
