### ISSUE TITLE
flask run throws `ImportError: No module named azure.storage.blob`

### ISSUE THREAD

**Issue by cindyloo** [Azure/azure-sdk-for-python#23516]
% flask run

Usage: flask run [OPTIONS]

Error: While importing "app", an ImportError was raised:

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/Users/cindybishop/Documents/GitHub/chomskyvschomsky/chomskyPipeline/app.py", line 4, in <module>
    from azure.storage.blob import BlobServiceClient, BlobClient, ContainerClient, __version__
ImportError: No module named azure.storage.blob

this doesn't happen if I run `python3 app.py`

**Comment by cindyloo** [comment]
I had to do this from within a venv and it is running now
