### ISSUE TITLE
Service Bus Error , session object does not exist in obtain_token_by_client_secret

### ISSUE THREAD

**Issue by piotrjedrys-tomtom** [Azure/azure-sdk-for-python#23588]
- **Package Name**: azsdk-python-identity
- **Package Version**: 1.8.0
- **Operating System**: mac
- **Python Version**: 3.7.9

**Describe the bug**
It appears that when asynchronous connection is used, after one hour the token is being internally refreshed (or obtained) but the AsyncTransportProtocol does not have session object set anymore and is not anymore the session owner, which ends with ServiceBusError:

```
2022-03-18 11:04:41,398 - INFO - Connection b'SBSender-e999f6b6-3dc0-4010-a18d-70adcd06371c' state changed from <ConnectionState.START: 0> to <ConnectionState.START: 0>
2022-03-18 11:04:41,400 - INFO - Request URL: 'https://login.microsoftonline.com/...../oauth2/v2.0/token'/nRequest method: 'POST'/nRequest headers:/n    'Content-Type': 'application/x-www-form-urlencoded'/n    'User-Agent': 'azsdk-python-identity/1.8.0 Python/3.7.9 (Darwin-20.6.0-x86_64-i386-64bit)'/nA body is sent with the request
2022-03-18 11:04:41,401 - ERROR - Unexpected error occurred (AttributeError("'NoneType' object has no attribute 'request'")). Handler shutting down.
Traceback (most recent call last):
  File "/Users/xyz/.pyenv/versions/3.7.9/envs/3.7.9-venv2/lib/python3.7/site-packages/azure_servicebus-7.1.0-py3.7.egg/azure/servicebus/aio/_base_handler_async.py", line 205, in _do_retryable_operation
  File "/Users/xyz/.pyenv/versions/3.7.9/envs/3.7.9-venv2/lib/python3.7/site-packages/azure_servicebus-7.1.0-py3.7.egg/azure/servicebus/aio/_servicebus_sender_async.py", line 173, in _open
  File "/Users/xyz/.pyenv/versions/3.7.9/envs/3.7.9-venv2/lib/python3.7/site-packages/uamqp-1.4.1-py3.7-macosx-10.15-x86_64.egg/uamqp/async_ops/client_async.py", line 246, in open_async
  File "/Users/xyz/.pyenv/versions/3.7.9/envs/3.7.9-venv2/lib/python3.7/site-packages/uamqp-1.4.1-py3.7-macosx-10.15-x86_64.egg/uamqp/async_ops/client_async.py", line 201, in _build_session_async
  File "/Users/xyz/.pyenv/versions/3.7.9/envs/3.7.9-venv2/lib/python3.7/site-packages/uamqp-1.4.1-py3.7-macosx-10.15-x86_64.egg/uamqp/authentication/cbs_auth_async.py", line 283, in create_authenticator_async
  File "/Users/xyz/.pyenv/versions/3.7.9/envs/3.7.9-venv2/lib/python3.7/site-packages/uamqp-1.4.1-py3.7-macosx-10.15-x86_64.egg/uamqp/authentication/cbs_auth_async.py", line 287, in update_token
  File "/Users/xyz/.pyenv/versions/3.7.9/envs/3.7.9-venv2/lib/python3.7/site-packages/azure/identity/aio/_credentials/default.py", line 141, in get_token
    return await self._successful_credential.get_token(*scopes, **kwargs)
  File "/Users/xyz/.pyenv/versions/3.7.9/envs/3.7.9-venv2/lib/python3.7/site-packages/azure/identity/aio/_internal/decorators.py", line 19, in wrapper
    token = await fn(*args, **kwargs)
  File "/Users/xyz/.pyenv/versions/3.7.9/envs/3.7.9-venv2/lib/python3.7/site-packages/azure/identity/aio/_credentials/environment.py", line 103, in get_token
    return await self._credential.get_token(*scopes, **kwargs)
  File "/Users/xyz/.pyenv/versions/3.7.9/envs/3.7.9-venv2/lib/python3.7/site-packages/azure/identity/aio/_internal/get_token_mixin.py", line 66, in get_token
    token = await self._request_token(*scopes, **kwargs)
  File "/Users/xyz/.pyenv/versions/3.7.9/envs/3.7.9-venv2/lib/python3.7/site-packages/azure/identity/aio/_credentials/client_secret.py", line 69, in _request_token
    return await self._client.obtain_token_by_client_secret(scopes, self._secret, **kwargs)
  File "/Users/xyz/.pyenv/versions/3.7.9/envs/3.7.9-venv2/lib/python3.7/site-packages/azure/identity/aio/_internal/aad_client.py", line 60, in obtain_token_by_client_secret
    return await self._run_pipeline(request, **kwargs)
  File "/Users/xyz/.pyenv/versions/3.7.9/envs/3.7.9-venv2/lib/python3.7/site-packages/azure/identity/aio/_internal/aad_client.py", line 96, in _run_pipeline
    response = await self._pipeline.run(request, retry_on_methods=self._POST, **kwargs)
  File "/Users/xyz/.pyenv/versions/3.7.9/envs/3.7.9-venv2/lib/python3.7/site-packages/azure/core/pipeline/_base_async.py", line 215, in run
    return await first_node.send(pipeline_request)
  File "/Users/xyz/.pyenv/versions/3.7.9/envs/3.7.9-venv2/lib/python3.7/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/Users/xyz/.pyenv/versions/3.7.9/envs/3.7.9-venv2/lib/python3.7/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/Users/xyz/.pyenv/versions/3.7.9/envs/3.7.9-venv2/lib/python3.7/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  [Previous line repeated 1 more time]
  File "/Users/xyz/.pyenv/versions/3.7.9/envs/3.7.9-venv2/lib/python3.7/site-packages/azure/core/pipeline/policies/_retry_async.py", line 147, in send
    response = await self.next.send(request)
  File "/Users/xyz/.pyenv/versions/3.7.9/envs/3.7.9-venv2/lib/python3.7/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/Users/xyz/.pyenv/versions/3.7.9/envs/3.7.9-venv2/lib/python3.7/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/Users/xyz/.pyenv/versions/3.7.9/envs/3.7.9-venv2/lib/python3.7/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  [Previous line repeated 1 more time]
  File "/Users/xyz/.pyenv/versions/3.7.9/envs/3.7.9-venv2/lib/python3.7/site-packages/azure/core/pipeline/_base_async.py", line 116, in send
    await self._sender.send(request.http_request, **request.context.options),
  File "/Users/xyz/.pyenv/versions/3.7.9/envs/3.7.9-venv2/lib/python3.7/site-packages/azure/core/pipeline/transport/_requests_asyncio.py", line 145, in send
    self.session.request,
AttributeError: 'NoneType' object has no attribute 'request'
2022-03-18 11:04:41,421 - ERROR - Handler failed: 'NoneType' object has no attribute 'request'. : Service Bus Error occurred, could not be established with queue prod-scan-queue.


```

**To Reproduce**
1. 
create transport and connection
async.sleep(3610)
and run new connection (in meantime the problem should be visible from the internal code

**Expected behavior**
Token refreshed correctly, no error

**Comment by yunhaoling** [comment]
hey @piotrjedrys-tomtom, do you mind sharing your code snippets for repro?
