### ISSUE TITLE
ValueError: No value for given attribute

### ISSUE THREAD

**Issue by mpender** [Azure/azure-sdk-for-python#23914]
- **Package Name**: azure.mgmt.loganalytics
- **Package Version**:  13.0.0b2
- **Operating System**:  12.12.1 (Monterey)
- **Python Version**:  3.9

**Describe the bug**
listing all datasources for a workspace returns iterator object azure.core.paging.ItemPaged at X that is not iterable 
Passing a string to the filter argument results in a http exception message, omitting it entirely also results in an exception

**To Reproduce** 

``` 
def listworkspaces(subscription: str):
    client = LogAnalyticsManagementClient(credentials, subscription)
    datasources = client.data_sources.list_by_workspace(rg, workspace_name, filter=None)
    print(datasources)
    for i in datasources:
        print(i)
```

**Expected behavior**
iterable objects contain json data 

**Screenshots**

Incomplete environment configuration. These variables are set: AZURE_CLIENT_ID, AZURE_TENANT_ID
<iterator object azure.core.paging.ItemPaged at 0x103f1ad60>
Traceback (most recent call last):
  File "/Users/USER/Documents/scripts/Azure/register-vms.py", line 47, in <module>
    main()
  File "/Users/USER/Documents/scripts/Azure/register-vms.py", line 44, in main
    listworkspaces(sub)
  File "/Users/USER/Documents/scripts/Azure/register-vms.py", line 38, in listworkspaces
    for i in datasources:
  File "/Users/USER/.pyenv/versions/3.9.0/Python.framework/Versions/3.9/lib/python3.9/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/Users/USER/.pyenv/versions/3.9.0/Python.framework/Versions/3.9/lib/python3.9/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/Users/USER/.pyenv/versions/3.9.0/Python.framework/Versions/3.9/lib/python3.9/site-packages/azure/mgmt/loganalytics/operations/_data_sources_operations.py", line 446, in get_next
    request = prepare_request(next_link)
  File "/Users/USER/.pyenv/versions/3.9.0/Python.framework/Versions/3.9/lib/python3.9/site-packages/azure/mgmt/loganalytics/operations/_data_sources_operations.py", line 412, in prepare_request
    request = build_list_by_workspace_request(
  File "/Users/USER/.pyenv/versions/3.9.0/Python.framework/Versions/3.9/lib/python3.9/site-packages/azure/mgmt/loganalytics/operations/_data_sources_operations.py", line 167, in build_list_by_workspace_request
    query_parameters['$filter'] = _SERIALIZER.query("filter", filter, 'str')
  File "/Users/USER/.pyenv/versions/3.9.0/Python.framework/Versions/3.9/lib/python3.9/site-packages/msrest/serialization.py", line 691, in query
    output = self.serialize_data(data, data_type, **kwargs)
  File "/Users/USER/.pyenv/versions/3.9.0/Python.framework/Versions/3.9/lib/python3.9/site-packages/msrest/serialization.py", line 758, in serialize_data
    raise ValueError("No value for given attribute")
ValueError: No value for given attribute

**Additional context**

**Comment by l0lawrence** [comment]
Thanks for the feedback, we'll investigate asap.

**Comment by msyyc** [comment]
Hi @mpender, type of `filter` is `str` so `none` is invalid. please refer [example](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/stable/2020-08-01/examples/DataSourcesListByWorkspace.json#L6) to pass in right params

**Comment by QawYousef** [comment]
ValueError: No points given

**Comment by QawYousef** [comment]
KIndly, assist me in this. I am trying to plot the ConvexHull for Breast cancer dataset by applying pca

The above error comes and stops my progress.

Regards

**Comment by QawYousef** [comment]
I wrote this code:
# Scatterplot against PC1 and PC2
fig, ax = plt.subplots(1,1, figsize=(16,12))

# Row masks for each category
rows_0 = Y==0;
rows_1 = Y==1; 
rows_2 = Y==2; 

# Plot
ax.scatter(df_pca.loc[rows_0.tolist(), 1], df_pca.loc[rows_0.tolist(), 2], c='blue', edgecolor='k', s=120, label='Zero')
ax.scatter(df_pca.loc[rows_1.tolist(), 1], df_pca.loc[rows_1.tolist(), 2], c='red', edgecolor='k', s=120, label='One')
ax.scatter(df_pca.loc[rows_2.tolist(), 1], df_pca.loc[rows_2.tolist(), 2], c='green', edgecolor='k', s=120, label='Two')

# Encircle the boundaries
encircle(df_pca.loc[rows_0.tolist(), 1], df_pca.loc[rows_0.tolist(), 2], ec="blue", fc="none", linewidth=2.5)
encircle(df_pca.loc[rows_1.tolist(), 1], df_pca.loc[rows_1.tolist(), 2], ec="firebrick", fc="none", linewidth=2.5)
#encircle(df_pca.loc[rows_2.tolist(), 1], df_pca.loc[rows_2.tolist(), 2], ec="green", fc="none", linewidth=2.5)

# Shading
encircle(df_pca.loc[rows_1.tolist(), 1], df_pca.loc[rows_1.tolist(), 2], ec="k", fc="firebrick", alpha=0.05)
encircle(df_pca.loc[rows_0.tolist(), 1], df_pca.loc[rows_0.tolist(), 2], ec="k", fc="blue", alpha=0.05)
#encircle(df_pca.loc[rows_2.tolist(), 1], df_pca.loc[rows_2.tolist(), 2], ec="k", fc="green", alpha=0.05)

# Labels
ax.set_title("Phishing Data for 1, 2 & 3: Scatterplot of First Two PCA directions", fontsize=22)
ax.set_xlabel("1st Principal Component", fontsize=22)
ax.set_ylabel("2nd Principal Component", fontsize=22)
ax.legend(loc='best', title='Transaction Type', fontsize=16)
plt.show();

Still the error is unresolved
