### ISSUE TITLE
 ManagedIdentityCredential authentication unavailable, no managed identity endpoint found for aio ManagedIdentity

### ISSUE THREAD

**Issue by suxi-ms** [Azure/azure-sdk-for-python#24142]
- **Package Name**: azure-storage-blob==12.8.1
- **Package Version**: 12.8.1
- **Operating System**: 18.04.1-Ubuntu
- **Python Version**: 3.9

**Describe the bug**
Error " azure.identity._exceptions.CredentialUnavailableError: ManagedIdentityCredential authentication unavailable, no managed identity endpoint found." occured when query request increased but it works well when QPS is low. The logic is the request is to download blob. When this error occurred, request latency will increase a lot.

**To Reproduce**
1. use flask to host a request. in the request, we have a  aio blob service client and we download blobs. The blob service client is initialized when the server is hosted.
2. do stress test to the API

**Expected behavior**
 Should not raise such error as the MI can works time before and after the error.

**Screenshots**

Here is my trace stack.
`
Traceback (most recent call last):
 File "/venv/lib/python3.9/site-packages/azure/storage/blob/aio/_download_async.py", line 293, in _initial_request
 location_mode, response = await self._clients.blob.download(
 File "/venv/lib/python3.9/site-packages/azure/storage/blob/_generated/aio/operations/_blob_operations.py", line 174, in download
 pipeline_response = await self._client._pipeline.run(request, stream=True, **kwargs)
 File "/venv/lib/python3.9/site-packages/azure/core/pipeline/_base_async.py", line 215, in run
 return await first_node.send(pipeline_request)
 File "/venv/lib/python3.9/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
 response = await self.next.send(request) # type: ignore
 File "/venv/lib/python3.9/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
 response = await self.next.send(request) # type: ignore
 File "/venv/lib/python3.9/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
 response = await self.next.send(request) # type: ignore
 [Previous line repeated 3 more times]
 File "/venv/lib/python3.9/site-packages/azure/core/pipeline/policies/_authentication_async.py", line 73, in send
 await await_result(self.on_request, request)
 File "/venv/lib/python3.9/site-packages/azure/core/pipeline/_tools_async.py", line 36, in await_result
 return await result # type: ignore
 File "/venv/lib/python3.9/site-packages/azure/core/pipeline/policies/_authentication_async.py", line 51, in on_request
 self._token = await self._credential.get_token(*self._scopes)
 File "/venv/lib/python3.9/site-packages/azure/identity/aio/_internal/decorators.py", line 17, in wrapper
 token = await fn(*args, **kwargs)
 File "/venv/lib/python3.9/site-packages/azure/identity/aio/_credentials/managed_identity.py", line 93, in get_token
 return await self._credential.get_token(*scopes, **kwargs)
 File "/venv/lib/python3.9/site-packages/azure/identity/aio/_internal/get_token_mixin.py", line 62, in get_token
 token = await self._request_token(*scopes)
 File "/venv/lib/python3.9/site-packages/azure/identity/aio/_credentials/imds.py", line 57, in _request_token
 raise CredentialUnavailableError(message=message)
azure.identity._exceptions.CredentialUnavailableError: ManagedIdentityCredential authentication unavailable, no managed identity endpoint found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
 rv = self.dispatch_request()
 File "/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
 return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
 File "/usr/app/src/rca/dataset_manager/entrypoints/flask_app.py", line 220, in list_data_sets
 datasets, has_next_link = services.list_data_sets(
 File "/usr/app/src/rca/dataset_manager/service_layer/services.py", line 419, in list_data_sets
 contents = blob_repo.get_metas(uuids)
 File "/usr/app/src/rca/dataset_manager/adapters/data_set_blob_repo.py", line 65, in get_metas
 return self.blob_async.get_jsons(paths)
 File "/usr/app/src/rca/common/azure/blob_service_client.py", line 196, in get_jsons
 res = self.loop.run_until_complete(self.__get_json_tasks(paths))
 File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
 return future.result()
 File "/usr/app/src/rca/common/azure/blob_service_client.py", line 277, in __get_json_tasks
 res = await asyncio.gather(*tasks)
 File "/usr/app/src/rca/common/azure/blob_service_client.py", line 253, in __get_json_async
 downloaded, etag = await self.__get_async(path)
 File "/usr/app/src/rca/common/azure/blob_service_client.py", line 238, in __get_async
 downloader = await blob_client.download_blob()
 File "/venv/lib/python3.9/site-packages/azure/core/tracing/decorator_async.py", line 74, in wrapper_use_tracer
 return await func(*args, **kwargs)
 File "/venv/lib/python3.9/site-packages/azure/storage/blob/aio/_blob_client_async.py", line 464, in download_blob
 await downloader._setup() # pylint: disable=protected-access
 File "/venv/lib/python3.9/site-packages/azure/storage/blob/aio/_download_async.py", line 250, in _setup
 self._response = await self._initial_request()
 File "/venv/lib/python3.9/site-packages/azure/storage/blob/aio/_download_async.py", line 318, in _initial_request
 if self._start_range is None and error.response.status_code == 416:
AttributeError: 'NoneType' object has no attribute 'status_code'
`

Such logic works well when QPS is low.

**Additional context**

**Comment by suxi-ms** [comment]
Thank you for the quick response @xiangyan99 ,  I have only one blobServiceClient instance for the whole service and it is only initialized once. But for the blobClient, every time I download some blob, it is a new instance.  I used the blob client to download blob. So for your question, I think my answer is yes, I reused the blob service client, but the error is thrown

**Comment by suxi-ms** [comment]
any update on this?

**Comment by suxi-ms** [comment]
> @suxi-ms Thanks for the updates.
> 
> @tasherif-msft could you help to check what's your token caching policy for storage?

any update on this question?

**Comment by suxi-ms** [comment]
Kindly ping， if you need more information about my code, feel free to reach me

**Comment by xiangyan99** [comment]
@jalauzon-msft @vincenttran-msft could you help to take a look?
