### ISSUE TITLE
DefaultAzureCredential and ImdsCredential deadlocks on macOS

### ISSUE THREAD

**Issue by mickare** [Azure/azure-sdk-for-python#24458]
- **Package Name**: azure-identity
- **Package Version**: 1.10.0
- **Operating System**: macOS Monterey (12.3.1)
- **Python Version**: 3.10.4

**Describe the bug**
On MacOS the `ImdsCredential` **always** freezes / deadlocks for 5 minutes. Consequentially the `DefaultAzureCredential` and `ManagedIdentityCredential` are affected by this deadlock too.

**To Reproduce**
1. Connect via VPN to company network and use proxy
2. Try to use a the `DefaultAzureCredential` on MacOS

```python
credential = DefaultAzureCredential()
credential.get_token("https://storage.azure.com/user_impersonation")
```

**Expected behavior**
No deadlock or freeze!

**Screenshots**

**Additional context**
Freezing call in `imds.py`: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/azure/identity/_credentials/imds.py#L80

Interrupted stacktrace:
```python
Traceback (most recent call last):
  File "/Users/someuser/somepath/test.py", line 161, in <module>
    api_token = credential.get_token(scope)
  File "/Users/someuser/somepath/venv/lib/python3.10/site-packages/azure/identity/_credentials/default.py", line 175, in get_token
    return super(DefaultAzureCredential, self).get_token(*scopes, **kwargs)
  File "/Users/someuser/somepath/venv/lib/python3.10/site-packages/azure/identity/_credentials/chained.py", line 83, in get_token
    token = credential.get_token(*scopes, **kwargs)
  File "/Users/someuser/somepath/venv/lib/python3.10/site-packages/azure/identity/_internal/decorators.py", line 32, in wrapper
    token = fn(*args, **kwargs)
  File "/Users/someuser/somepath/venv/lib/python3.10/site-packages/azure/identity/_credentials/managed_identity.py", line 123, in get_token
    return self._credential.get_token(*scopes, **kwargs)
  File "/Users/someuser/somepath/venv/lib/python3.10/site-packages/azure/identity/_internal/get_token_mixin.py", line 76, in get_token
    token = self._request_token(*scopes, **kwargs)
  File "/Users/someuser/somepath/venv/lib/python3.10/site-packages/azure/identity/_credentials/imds.py", line 80, in _request_token
    self._client.request_token(*scopes, connection_timeout=0.3, retry_total=0)
  File "/Users/someuser/somepath/venv/lib/python3.10/site-packages/azure/identity/_internal/managed_identity_client.py", line 125, in request_token
    response = self._pipeline.run(request, retry_on_methods=[request.method], **kwargs)
  File "/Users/someuser/somepath/venv/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/Users/someuser/somepath/venv/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/someuser/somepath/venv/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/someuser/somepath/venv/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/Users/someuser/somepath/venv/lib/python3.10/site-packages/azure/core/pipeline/policies/_retry.py", line 446, in send
    response = self.next.send(request)
  File "/Users/someuser/somepath/venv/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/someuser/somepath/venv/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/someuser/somepath/venv/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/Users/someuser/somepath/venv/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 103, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/Users/someuser/somepath/venv/lib/python3.10/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 327, in send
    response = self.session.request(  # type: ignore
  File "/Users/someuser/somepath/venv/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/someuser/somepath/venv/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/someuser/somepath/venv/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/Users/someuser/somepath/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/someuser/somepath/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/someuser/somepath/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
```

**Workaround**
Set the `read_timeout` from 300 seconds to a small value:
```python
credential = DefaultAzureCredential(read_timeout=1)
```
Or disable the managed identity client in the `DefaultAzureCredential`:
```python
credential = DefaultAzureCredential(exclude_managed_identity_credential=True)
```

**Related issues**
- #21878
- #21500

**Comment by mickare** [comment]
Curl on the IMDS service IP 169.254.169.254 results in a timeout!

```bash
curl 'http://169.254.169.254/metadata/identity/oauth2/token' -v
* Uses proxy env variable no_proxy == '127.0.0.*,172.17.*,localhost'
* Uses proxy env variable http_proxy == 'http://localhost:3128'
*   Trying 127.0.0.1:3128...
* Connected to localhost (127.0.0.1) port 3128 (#0)
> GET http://169.254.169.254/metadata/identity/oauth2/token HTTP/1.1
> Host: 169.254.169.254
> User-Agent: curl/7.79.1
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
* Mark bundle as not supporting multiuse
* HTTP 1.0, assume close after body
< HTTP/1.0 400 Fail to directly connect with 169.254.169.254
< 
* Closing connection 0
```

**Comment by xiangyan99** [comment]
Thanks for reaching out.

To make sure I understand correctly, it only repros when you have VPN connected and proxy set, right?

Because we have code self._client.request_token(*scopes, connection_timeout=0.3, retry_total=0), I am wondering if the root cause may be related to the VPN and/or proxy?

Could you help to check if it repros in such scenarios:
1. No VPN, No proxy
2. VPN, No proxy
3. Proxy, no VPN

This can help us narrow down the cause.

Thank you.

**Comment by mickare** [comment]
I tested a little bit more and it seems to be a problem of the network configuration on the Mac. Since it is a managed device I'll to close this comment and forward this issue internally.

It works as expected on another linux machine without any vpn&proxy. It will not timeout and curl reports after 3 seconds that it failed to connect (as expected).

To summarize, if I understand it correctly: `169.254.169.254` is a private IP that is used for hosting a vm-local managed identity service. The SDK relies on the connection to NOT be established before it jumps to the next credential in the chain. But if the TCP connection is created anyway (e.g. proxy) and no EOF is returned the ImdsCredential will run into the default HTTP socket timeout.

**Comment by mickare** [comment]
Now I'm thinking why the `ImdsCredential` is using the proxy anyway? It would not solve my issue because the problem would still persist. But now it's a security question.

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/azure/core/pipeline/transport/_aiohttp.py#L101

**Comment by mickare** [comment]
Found another temporary solution: Add `169.254.169.254` to your `no_proxy` environment variable.

**Comment by xiangyan99** [comment]
Thank you for the updates. 

169.254.169.254 is IMDS endpoint. It can only be accessible when your VM is hosted in Azure.

In terms of your question
why the ImdsCredential is using the proxy anyway

This is by design that all our http requests honor your proxy settings.

Could you describe your case a little more to help us understand why this may cause security concerns?

Thanks.
