### ISSUE TITLE
CertificateCredential with password

### ISSUE THREAD

**Issue by dfroger** [Azure/azure-sdk-for-python#24907]
I'm looking for a working example of creating a certificate with password that can be used with `CertificateCredential(tenant_id=..., client_id=..., certificate_data=..., password=...)`.

I can make it work without password, but don't understand how to do with password.

Thanks!

# Without password: it works

I generate a user certificate + private key PEM file like this:

```bash
# Create the CA private key
openssl genrsa -out ca.key 4096

# Create and self sign the Root Certificate
openssl req -x509 -new -nodes -key ca.key -sha256 -days 1024 -out ca.crt -subj "/C=FR/ST=France/L=Rennes/O=ca/CN=ca"

# Create user private key.
openssl genrsa -out user.key 2048

# Create user certificate signing request.
openssl req -new -sha256 -key user.key -subj "/C=FR/ST=France/L=Rennes/O=corp/CN=user" -out user.csr

# Makes the user certificate using CA private key
openssl x509 -req -in user.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out user.crt -days 500 -sha256

# Gather certificate and private key
cat user.crt user.key > user.pem
```

and I can setup a `CertificateCredential` like this:

```python
>>> from pathlib import Path
>>> from azure.identity import CertificateCredential

>>> CertificateCredential( tenant_id="xxx",  client_id="xxx",  certificate_data=Path("user.pem").read_bytes() )
<azure.identity._credentials.certificate.CertificateCredential object at 0x7f8e659aba50>

 ```

# With password: it fails

Now, I'm trying the same thing with a encrypted private key:

```bash
# Create the CA private key
openssl genrsa -out ca.key 4096

# Create and self sign the Root Certificate
openssl req -x509 -new -nodes -key ca.key -sha256 -days 1024 -out ca.crt -subj "/C=FR/ST=France/L=Rennes/O=ca/CN=ca"

# Create encrypted user private key.
openssl genrsa -des -out user2.key -passout 'pass:mypassword' 2048

# Create user certificate signing request.
openssl req -new -sha256 -key user2.key -subj "/C=FR/ST=France/L=Rennes/O=corp/CN=user2" -out user2.csr -passin 'pass:mypassword'   

# Makes the user certificate using CA private key
openssl x509 -req -in user2.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out user2.crt -days 500 -sha256

# Gather certificate and private key
cat user2.crt user2.key > user2.pem 
```

but setup a `CertificateCredential` fails:

```python
>>> CertificateCredential(tenant_id="xxx", client_id="xxx",  certificate_data=Path("user2.pem").read_bytes(),  password="mypassword")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/venv/lib/python3.7/site-packages/azure/identity/_credentials/certificate.py", line 53, in __init__
    client_credential = get_client_credential(certificate_path, **kwargs)
  File "path/to/venv/lib/python3.7/site-packages/azure/identity/_credentials/certificate.py", line 92, in get_client_credential
    cert = x509.load_pem_x509_certificate(certificate_data, default_backend())
  File "/path/to/venv/lib/python3.7/site-packages/cryptography/x509/base.py", line 514, in load_pem_x509_certificate
    return rust_x509.load_pem_x509_certificate(data)
ValueError: Unable to load PEM file. See https://cryptography.io/en/latest/faq/#why-can-t-i-import-my-pem-file for more details. InvalidData(InvalidByte(4, 45))
```

# Environement

```
uname -a
Linux dfroger-laptop 5.4.0-105-generic #119-Ubuntu SMP Mon Mar 7 18:49:24 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux


$ openssl version
OpenSSL 1.1.1f  31 Mar 2020


$ python --version
Python 3.7.11

$ pip list
Package            Version
------------------ ---------
azure-core         1.24.1
azure-identity     1.6.0
certifi            2022.6.15
cffi               1.15.0
charset-normalizer 2.0.12
cryptography       37.0.2
idna               3.3
msal               1.18.0
msal-extensions    0.3.1
pip                20.1.1
portalocker        2.4.0
pycparser          2.21
PyJWT              2.4.0
requests           2.28.0
setuptools         47.1.0
six                1.16.0
typing-extensions  4.2.0
urllib3            1.26.9

**Comment by kristapratico** [comment]
Hello thanks for the detailed feedback, @xiangyan99 can you take a look?

**Comment by dfroger** [comment]
@xiangyan99 yes of course, I didn't noticed I pinned an old version...

Here is the update with azure-identity 1.10.0

```python
>>> CertificateCredential(tenant_id="xxx", client_id="xxx",  certificate_data=Path("user2.pem").read_bytes(),  password="mypassword")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/venv/lib/python3.7/site-packages/azure/identity/_credentials/certificate.py", line 54, in __init__
    client_credential = get_client_credential(certificate_path, **kwargs)
  File "/path/to/venv/lib/python3.7/site-packages/azure/identity/_credentials/certificate.py", line 131, in get_client_credential
    cert = load_pem_certificate(certificate_data, password)
  File "/path/to/venv/lib/python3.7/site-packages/azure/identity/_credentials/certificate.py", line 80, in load_pem_certificate
    cert = x509.load_pem_x509_certificate(certificate_data, default_backend())
  File "/path/to/venv/lib/python3.7/site-packages/cryptography/x509/base.py", line 514, in load_pem_x509_certificate
    return rust_x509.load_pem_x509_certificate(data)
ValueError: Unable to load PEM file. See https://cryptography.io/en/latest/faq/#why-can-t-i-import-my-pem-file for more details. InvalidData(InvalidByte(4, 45))
```
```bash
$ pip list
Package            Version
------------------ ---------
azure-core         1.24.1
azure-identity     1.10.0
certifi            2022.6.15
cffi               1.15.0
charset-normalizer 2.0.12
cryptography       37.0.2
idna               3.3
msal               1.18.0
msal-extensions    1.0.0
pip                20.1.1
portalocker        2.4.0
pycparser          2.21
PyJWT              2.4.0
requests           2.28.0
setuptools         47.1.0
six                1.16.0
typing-extensions  4.2.0
urllib3            1.26.9
```

I'm pretty that's a stupid error and I'm passing bad input to `CertificateCredential`.

**Comment by xiangyan99** [comment]
Can you try install cryptography==3.4.8?

It seems to me a regression in cryptography library.

**Comment by xiangyan99** [comment]
Thanks for the update.
