### ISSUE TITLE
azure-common: Imports adal, but adal not in install_requires

### ISSUE THREAD

**Issue by major** [Azure/azure-sdk-for-python#24948]
- **Package Name**: `azure-common`
- **Package Version**: `1.1.22`
- **Operating System**: `Fedora 37`
- **Python Version**: `3.11.0b3`

**Describe the bug**
The `azure-common` package imports `adal` in `azure/common/client_factory.py`, but `adal` is not in `install_requires` within `setup.py`. That causes an error during Fedora RPM package builds because `azure.common.client_factory` cannot be imported:

```
Check import: azure.common.client_factory
Traceback (most recent call last):
  File "/usr/lib/rpm/redhat/import_all_modules.py", line 171, in <module>
    main()
    ^^^^^^
  File "/usr/lib/rpm/redhat/import_all_modules.py", line 167, in main
    import_modules(modules)
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/rpm/redhat/import_all_modules.py", line 100, in import_modules
    importlib.import_module(module)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 939, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/builddir/build/BUILDROOT/python-azure-common-1.1.22-1.fc37.x86_64/usr/lib/python3.11/site-packages/azure/common/client_factory.py", line 17, in <module>
    import adal
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'adal'
```

**To Reproduce**
1. Install `azure-common` in a virtual environment
2. Run `python` and type `import azure.common.client_factory`
3. Traceback appears

**Expected behavior**
I expect to be able to import modules from `azure.common` successfully.

**Comment by xiangyan99** [comment]
Thanks for reporting the issue.

It is by design that we don't msrestazure and adal libraries.

azure-common is used by both track 1 and track 2 libraries and only track 1 libraries need azure.common.client_factory.

So we decided to make track 1 libraries require msrestazure and adal rather than setting the requirements in azure-common.

Can we disable the auto-importing?

Thanks.
