### ISSUE TITLE
Getting "Internal Server Error" from receive_subscription_message?

### ISSUE THREAD

**Issue by olavt** [Azure/azure-sdk-for-python#2495]
I have the following code being called in an endless loop:

```
    def _wait_for_transition_to_next_state(self):
        self.logger.info ("Waiting for environment to respond to action...")
        # Wait for new CO2 sensor data to be received
        try:
            msg = self.bus_service.receive_subscription_message('sensordata', 'test', peek_lock=True, timeout=60)
            if msg.body is not None:
                self._process_sensor_data(msg.body)
                msg.delete()
        except requests.exceptions.ReadTimeout:
            self.logger.exception("ReadTimeout from ServiceBusService.receive_subscription_message")
```

It was running with no issues for about 14 days until it crashed with:

2018-04-28 00:38:04.908 - INFO - Waiting for environment to respond to action...
Traceback (most recent call last):
  File "c:\Users\olavt\source\repos\gym_co2_ventilation\examples\test_keras_rl_production.py", line 88, in <module>
    history = dqn.fit(env, nb_max_episode_steps=nb_episode_steps, nb_steps=nb_episode_steps*nb_episodes, visualize=True, verbose=2)
  File "C:\Users\olavt\AppData\Local\Programs\Python\Python36\lib\site-packages\rl\core.py", line 168, in fit
    observation, r, done, info = env.step(action)
  File "C:\Users\olavt\AppData\Local\Programs\Python\Python36\lib\site-packages\gym\wrappers\time_limit.py", line 31, in step
    observation, reward, done, info = self.env.step(action)
  File "c:\users\olavt\source\repos\gym_co2_ventilation\gym_co2_ventilation\envs\co2_ventilation_production_env.py", line 64, in step
    self._wait_for_transition_to_next_state()
  File "c:\users\olavt\source\repos\gym_co2_ventilation\gym_co2_ventilation\envs\co2_ventilation_production_env.py", line 109, in _wait_for_transition_to_next_state
    msg = self.bus_service.receive_subscription_message('sensordata', 'test', peek_lock=True, timeout=60)
  File "C:\Users\olavt\AppData\Local\Programs\Python\Python36\lib\site-packages\azure\servicebus\servicebusservice.py", line 1091, in receive_subscription_message
    timeout)
  File "C:\Users\olavt\AppData\Local\Programs\Python\Python36\lib\site-packages\azure\servicebus\servicebusservice.py", line 732, in peek_lock_subscription_message
    response = self._perform_request(request)
  File "C:\Users\olavt\AppData\Local\Programs\Python\Python36\lib\site-packages\azure\servicebus\servicebusservice.py", line 1230, in _perform_request
    return _service_bus_error_handler(ex)
  File "C:\Users\olavt\AppData\Local\Programs\Python\Python36\lib\site-packages\azure\servicebus\_serialization.py", line 589, in _service_bus_error_handler
    return _general_error_handler(http_error)
  File "C:\Users\olavt\AppData\Local\Programs\Python\Python36\lib\site-packages\azure\servicebus\_common_error.py", line 49, in _general_error_handler
    raise AzureHttpError(message, http_error.status)
azure.common.AzureHttpError: Internal Server Error
<Error><Code>500</Code><Detail>Error during communication with Service Bus. Check the connection information, then retry. TrackingId:1b7fa4d3-cd9d-41b1-b42b-29850af1d73d_G33, SystemTracker:olavthomeautomation:Topic:sensordata, Timestamp:4/28/2018 12:38:45 AM</Detail></Error>
PS C:\Users\olavt\source\repos\gym_co2_ventilation>

Should really "Internal Server Error" be exposed to the caller? Shouldn't the cause of the "Internal Server Error" be mapped to some more appropriate exception?

**Comment by lmazuel** [comment]
You're right, a client should never see any `500` error, that's a bug from the RestAPI side.

However, since we're talking here about the Python SDK, I'm not in the SB team, and it will be best to open a support ticket for the SB team with your TrackingId and symptoms (saying you're using the HTTP endpoint).

Thank you for the report, I'm sure the SB team will take over the issue and solve it.
Thanks again!
