### ISSUE TITLE
BlobServiceClient list_containers throws AuthorizationFailure

### ISSUE THREAD

**Issue by padauer** [Azure/azure-sdk-for-python#25220]
**Issue:**
Blob Service Client list_containers fails with AuthorizationFailure
It worked until 1 or 2 weeks ago. I dont run this script very often. But we didnt change a thing...

**Code snippet**
```python
from azure.identity import ClientSecretCredential
creds = ClientSecretCredential(tenant_id, client_id, client_secret)
bsc = BlobServiceClient(account_url=storage_account.primary_endpoints.blob, credential=creds)
for container in bsc.list_containers(include_metadata=True):
    print(container)
```

**Stack trace:**
```
Tuple timeout setting is deprecated
Traceback (most recent call last):
  File "C:\<path>\.env\lib\site-packages\azure\storage\blob\_models.py", line 377, in _get_next_cb
    return self._command(
  File "C:\<path>\.env\lib\site-packages\azure\storage\blob\_generated\operations\_service_operations.py", line 337, in list_containers_segment
    raise models.StorageErrorException(response, self._deserialize)
azure.storage.blob._generated.models._models_py3.StorageErrorException: Operation returned an invalid status 'This request is not authorized to perform this operation.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.
RequestId:6ea43839-f01e-001d-4eb2-97e748000000
Time:2022-07-14T18:47:41.4785118Z</Message></Error>
``` 

**Expected behavior**
List all containers in Storage Account

**Setup**
Python 3.10.5
```
Package             Version
------------------- ---------
azure-common        1.1.28
azure-core          1.24.2
azure-identity      1.10.0
azure-mgmt-core     1.3.1
azure-mgmt-resource 21.1.0
azure-mgmt-storage  20.0.0
azure-storage-blob  12.13.0
```

**Additional context**
Error also occurs when storage accounts are public and service principal has Owner permissions.

**Comment by xiangyan99** [comment]
Thanks for reaching out. 

Could you enable log to get more details?

```py
import logging
logging.basicConfig(filename='c:/temp/log.log', level=logging.DEBUG)
```

**Comment by padauer** [comment]
@xiangyan99 
here are the logs:
```
INFO:azure.core.pipeline.policies.http_logging_policy:Request URL: 'https://login.microsoftonline.com/<tenant>/v2.0/.well-known/openid-configuration'
Request method: 'GET'
Request headers:
    'User-Agent': 'azsdk-python-identity/1.10.0 Python/3.10.5 (Windows-10-10.0.19042-SP0)'
No body was attached to the request
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): login.microsoftonline.com:443
DEBUG:urllib3.connectionpool:https://login.microsoftonline.com:443 "GET /<tenant>/v2.0/.well-known/openid-configuration HTTP/1.1" 200 1753
INFO:azure.core.pipeline.policies.http_logging_policy:Response status: 200
Response headers:
    'Cache-Control': 'max-age=86400, private'
    'Content-Type': 'application/json; charset=utf-8'
    'Strict-Transport-Security': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Access-Control-Allow-Methods': 'REDACTED'
    'P3P': 'REDACTED'
    'x-ms-request-id': '9b1462a0-19b3-49ae-9820-eed30b6f5100'
    'x-ms-ests-server': 'REDACTED'
    'X-XSS-Protection': 'REDACTED'
    'Set-Cookie': 'REDACTED'
    'Date': 'Fri, 15 Jul 2022 04:31:23 GMT'
    'Content-Length': '1753'
DEBUG:msal.authority:openid_config = {'token_endpoint': 'https://login.microsoftonline.com/<tenant>/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/<tenant>/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/<tenant>/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/<tenant>/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/<tenant>/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/<tenant>/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/<tenant>/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
DEBUG:msal.application:Region to be used: None
DEBUG:msal.application:Found 0 RTs matching {'environment': 'login.microsoftonline.com', 'home_account_id': None, 'family_id': '1'}
DEBUG:msal.application:Found 0 RTs matching {'environment': 'login.microsoftonline.com', 'home_account_id': None, 'client_id': '<client_id>'}
INFO:azure.core.pipeline.policies.http_logging_policy:Request URL: 'https://login.microsoftonline.com/common/discovery/instance?api-version=REDACTED&authorization_endpoint=REDACTED'
Request method: 'GET'
Request headers:
    'Accept': 'application/json'
    'User-Agent': 'azsdk-python-identity/1.10.0 Python/3.10.5 (Windows-10-10.0.19042-SP0)'
No body was attached to the request
DEBUG:urllib3.connectionpool:https://login.microsoftonline.com:443 "GET /common/discovery/instance?api-version=1.1&authorization_endpoint=https://login.microsoftonline.com/common/oauth2/authorize HTTP/1.1" 200 945
INFO:azure.core.pipeline.policies.http_logging_policy:Response status: 200
Response headers:
    'Cache-Control': 'max-age=86400, private'
    'Content-Type': 'application/json; charset=utf-8'
    'Strict-Transport-Security': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Access-Control-Allow-Methods': 'REDACTED'
    'P3P': 'REDACTED'
    'x-ms-request-id': '4efcc1c1-211c-44ac-92d2-1c0d8a9f6400'
    'x-ms-ests-server': 'REDACTED'
    'X-XSS-Protection': 'REDACTED'
    'Set-Cookie': 'REDACTED'
    'Date': 'Fri, 15 Jul 2022 04:31:23 GMT'
    'Content-Length': '945'
DEBUG:msal.telemetry:Generate or reuse correlation_id: fd8012b5-2f8b-4468-ad1a-c9d54894ec19
INFO:azure.core.pipeline.policies.http_logging_policy:Request URL: 'https://login.microsoftonline.com/<tenant>/oauth2/v2.0/token'
Request method: 'POST'
Request headers:
    'Accept': 'application/json'
    'x-client-sku': 'REDACTED'
    'x-client-ver': 'REDACTED'
    'x-client-os': 'REDACTED'
    'x-client-cpu': 'REDACTED'
    'x-ms-lib-capability': 'REDACTED'
    'client-request-id': 'REDACTED'
    'x-client-current-telemetry': 'REDACTED'
    'x-client-last-telemetry': 'REDACTED'
    'User-Agent': 'azsdk-python-identity/1.10.0 Python/3.10.5 (Windows-10-10.0.19042-SP0)'
A body is sent with the request
DEBUG:urllib3.connectionpool:https://login.microsoftonline.com:443 "POST /<tenant>/oauth2/v2.0/token HTTP/1.1" 200 1457
INFO:azure.core.pipeline.policies.http_logging_policy:Response status: 200
Response headers:
    'Cache-Control': 'no-store, no-cache'
    'Pragma': 'no-cache'
    'Content-Type': 'application/json; charset=utf-8'
    'Expires': '-1'
    'Strict-Transport-Security': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'P3P': 'REDACTED'
    'client-request-id': 'REDACTED'
    'x-ms-request-id': 'a8d4f46c-7050-4bf7-8bde-482259f54e00'
    'x-ms-ests-server': 'REDACTED'
    'x-ms-clitelem': 'REDACTED'
    'X-XSS-Protection': 'REDACTED'
    'Set-Cookie': 'REDACTED'
    'Date': 'Fri, 15 Jul 2022 04:31:23 GMT'
    'Content-Length': '1457'
DEBUG:msal.token_cache:event={
    "client_id": "<client_id>",
    "data": {
        "claims": "{\"access_token\": {\"xms_cc\": {\"values\": [\"CP1\"]}}}",
        "scope": [
            "https://management.azure.com/.default"
        ]
    },
    "environment": "login.microsoftonline.com",
    "grant_type": "client_credentials",
    "params": null,
    "response": {
        "access_token": "********",
        "expires_in": 3599,
        "ext_expires_in": 3599,
        "token_type": "Bearer"
    },
    "scope": [
        "https://management.azure.com/.default"
    ],
    "token_endpoint": "https://login.microsoftonline.com/<tenant>/oauth2/v2.0/token"
}
INFO:azure.identity._internal.get_token_mixin:ClientSecretCredential.get_token succeeded
INFO:azure.core.pipeline.policies.http_logging_policy:Request URL: 'https://management.azure.com/subscriptions/<subscription>/resourcegroups?api-version=REDACTED'
Request method: 'GET'
Request headers:
    'Accept': 'application/json'
    'x-ms-client-request-id': 'fc1a82a2-03f6-11ed-8c4c-7c214a5a0298'
    'User-Agent': 'azsdk-python-azure-mgmt-resource/21.1.0 Python/3.10.5 (Windows-10-10.0.19042-SP0)'
    'Authorization': 'REDACTED'
No body was attached to the request
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): management.azure.com:443
DEBUG:urllib3.connectionpool:https://management.azure.com:443 "GET /subscriptions/<subscription>/resourcegroups?api-version=2021-04-01 HTTP/1.1" 200 849
INFO:azure.core.pipeline.policies.http_logging_policy:Response status: 200
Response headers:
    'Cache-Control': 'no-cache'
    'Pragma': 'no-cache'
    'Content-Type': 'application/json; charset=utf-8'
    'Content-Encoding': 'REDACTED'
    'Expires': '-1'
    'Vary': 'REDACTED'
    'x-ms-ratelimit-remaining-subscription-reads': '11998'
    'x-ms-request-id': '9a7fbd4f-46fc-42a0-98c9-04d649c935aa'
    'x-ms-correlation-request-id': 'REDACTED'
    'x-ms-routing-request-id': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Date': 'Fri, 15 Jul 2022 04:31:24 GMT'
    'Content-Length': '849'
DEBUG:msal.application:Cache hit an AT
DEBUG:msal.telemetry:Generate or reuse correlation_id: b98caf5a-9729-40e0-b245-61326c16e76a
INFO:azure.identity._internal.get_token_mixin:ClientSecretCredential.get_token succeeded
INFO:azure.core.pipeline.policies.http_logging_policy:Request URL: 'https://management.azure.com/subscriptions/<subscription>/resourceGroups/<resource-group>/providers/Microsoft.Storage/storageAccounts?api-version=REDACTED'
Request method: 'GET'
Request headers:
    'Accept': 'application/json'
    'x-ms-client-request-id': 'fc7ac268-03f6-11ed-80d8-7c214a5a0298'
    'User-Agent': 'azsdk-python-azure-mgmt-storage/20.0.0 Python/3.10.5 (Windows-10-10.0.19042-SP0)'
    'Authorization': 'REDACTED'
No body was attached to the request
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): management.azure.com:443
DEBUG:urllib3.connectionpool:https://management.azure.com:443 "GET /subscriptions/<subscription>/resourceGroups/<resource-group>/providers/Microsoft.Storage/storageAccounts?api-version=2021-09-01 HTTP/1.1" 200 None
INFO:azure.core.pipeline.policies.http_logging_policy:Response status: 200
Response headers:
    'Cache-Control': 'no-cache'
    'Pragma': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json'
    'Content-Encoding': 'REDACTED'
    'Expires': '-1'
    'Vary': 'REDACTED'
    'x-ms-request-id': '48785042-7fd8-49eb-86f5-a9406936a300'
    'Strict-Transport-Security': 'REDACTED'
    'Server': 'Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0'
    'x-ms-ratelimit-remaining-subscription-reads': '11999'
    'x-ms-correlation-request-id': 'REDACTED'
    'x-ms-routing-request-id': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Date': 'Fri, 15 Jul 2022 04:31:24 GMT'
DEBUG:msal.application:Found 0 RTs matching {'environment': 'login.microsoftonline.com', 'home_account_id': None, 'client_id': '<client_id>'}
DEBUG:msal.telemetry:Generate or reuse correlation_id: 7d38db68-9bbf-460b-9e71-7244e2756405
INFO:azure.core.pipeline.policies.http_logging_policy:Request URL: 'https://login.microsoftonline.com/<tenant>/oauth2/v2.0/token'
Request method: 'POST'
Request headers:
    'Accept': 'application/json'
    'x-client-sku': 'REDACTED'
    'x-client-ver': 'REDACTED'
    'x-client-os': 'REDACTED'
    'x-client-cpu': 'REDACTED'
    'x-ms-lib-capability': 'REDACTED'
    'client-request-id': 'REDACTED'
    'x-client-current-telemetry': 'REDACTED'
    'x-client-last-telemetry': 'REDACTED'
    'User-Agent': 'azsdk-python-identity/1.10.0 Python/3.10.5 (Windows-10-10.0.19042-SP0)'
A body is sent with the request
DEBUG:urllib3.connectionpool:https://login.microsoftonline.com:443 "POST /<tenant>/oauth2/v2.0/token HTTP/1.1" 200 1383
INFO:azure.core.pipeline.policies.http_logging_policy:Response status: 200
Response headers:
    'Cache-Control': 'no-store, no-cache'
    'Pragma': 'no-cache'
    'Content-Type': 'application/json; charset=utf-8'
    'Expires': '-1'
    'Strict-Transport-Security': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'P3P': 'REDACTED'
    'client-request-id': 'REDACTED'
    'x-ms-request-id': 'a8d4f46c-7050-4bf7-8bde-482264f54e00'
    'x-ms-ests-server': 'REDACTED'
    'x-ms-clitelem': 'REDACTED'
    'X-XSS-Protection': 'REDACTED'
    'Set-Cookie': 'REDACTED'
    'Date': 'Fri, 15 Jul 2022 04:31:24 GMT'
    'Content-Length': '1383'
DEBUG:msal.token_cache:event={
    "client_id": "<client_id>",
    "data": {
        "claims": "{\"access_token\": {\"xms_cc\": {\"values\": [\"CP1\"]}}}",
        "scope": [
            "https://storage.azure.com/.default"
        ]
    },
    "environment": "login.microsoftonline.com",
    "grant_type": "client_credentials",
    "params": null,
    "response": {
        "access_token": "********",
        "expires_in": 3599,
        "ext_expires_in": 3599,
        "token_type": "Bearer"
    },
    "scope": [
        "https://storage.azure.com/.default"
    ],
    "token_endpoint": "https://login.microsoftonline.com/<tenant>/oauth2/v2.0/token"
}
INFO:azure.identity._internal.get_token_mixin:ClientSecretCredential.get_token succeeded
INFO:azure.core.pipeline.policies.http_logging_policy:Request URL: 'https://<storage-account>.blob.core.windows.net/?comp=REDACTED&include=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.13.0 Python/3.10.5 (Windows-10-10.0.19042-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'fcc3e24e-03f6-11ed-8506-7c214a5a0298'
    'Authorization': 'REDACTED'
No body was attached to the request
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): <storage-account>.blob.core.windows.net:443
DEBUG:urllib3.connectionpool:https://<storage-account>.blob.core.windows.net:443 "GET /?comp=list&include=metadata HTTP/1.1" 403 246
INFO:azure.core.pipeline.policies.http_logging_policy:Response status: 403
Response headers:
    'Content-Length': '246'
    'Content-Type': 'application/xml'
    'Server': 'Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'f355204b-901e-001b-3603-981d44000000'
    'x-ms-client-request-id': 'fcc3e24e-03f6-11ed-8506-7c214a5a0298'
    'x-ms-error-code': 'REDACTED'
    'Date': 'Fri, 15 Jul 2022 04:31:24 GMT'

```

**Comment by padauer** [comment]
Hi,

It was actually a Network issue.
We use a cloudproxy. once disabled everything works.
Sorry!
