### ISSUE TITLE
ImportError: cannot import name 'BlobClient' from 'azure.storage.blob' (/usr/lib/python3/dist-packages/azure/storage/blob/__init__.py)

### ISSUE THREAD

**Issue by wtam** [Azure/azure-sdk-for-python#25232]
- **Package Name**:  azure-storage-blob 
- **Package Version**: 12.13.0 and all old pkg
- **Operating System**: WSL:Ubuntu
- **Python Version**:  3.8.10

**Describe the bug**
ImportError: cannot import name 'BlobClient' from 'azure.storage.blob' (/usr/lib/python3/dist-packages/azure/storage/blob/__init__.py)

**To Reproduce**
1. from azure.storage.filedatalake import DataLakeServiceClient

**Expected behavior**
Import ok

**Screenshots**
Traceback (most recent call last):
  File "AAD_ADLS_Client.py", line 143, in <module>
    sample.data_lake_service_sample()
  File "AAD_ADLS_Client.py", line 59, in data_lake_service_sample
    from azure.storage.filedatalake import DataLakeServiceClient
  File "/usr/lib/python3/dist-packages/azure/storage/filedatalake/__init__.py", line 7, in <module>
    from ._data_lake_file_client import DataLakeFileClient
  File "/usr/lib/python3/dist-packages/azure/storage/filedatalake/_data_lake_file_client.py", line 12, in <module>
    from ._path_client import PathClient
  File "/usr/lib/python3/dist-packages/azure/storage/filedatalake/_path_client.py", line 15, in <module>
    from azure.storage.blob import BlobClient
ImportError: cannot import name 'BlobClient' from 'azure.storage.blob' (/usr/lib/python3/dist-packages/azure/storage/blob/__init__.py)

**Additional context**
pip3 freeze
adal==1.2.7
aiohttp==3.6.2
ansiwrap==0.8.4
applicationinsights==0.11.9
argcomplete==1.8.1
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.5
async-timeout==3.0.1
attrs==19.3.0
Automat==0.8.0
azure==4.0.0
azure-ai-textanalytics==1.0.0b1
azure-appconfiguration==1.0.0
azure-applicationinsights==0.1.0
azure-batch==12.0.0
azure-cli==2.0.81
azure-cli-core==2.0.81
azure-cli-telemetry==1.0.4
azure-cognitiveservices-anomalydetector==0.2.0
azure-cognitiveservices-formrecognizer==0.1.0
azure-cognitiveservices-knowledge-qnamaker==0.1.0
azure-cognitiveservices-language-luis==0.5.0
azure-cognitiveservices-language-spellcheck==2.0.0
azure-cognitiveservices-language-textanalytics==0.2.0
azure-cognitiveservices-personalizer==0.1.0
azure-cognitiveservices-search-autosuggest==0.2.0
azure-cognitiveservices-search-customimagesearch==0.2.0
azure-cognitiveservices-search-customsearch==0.3.0
azure-cognitiveservices-search-entitysearch==2.0.0
azure-cognitiveservices-search-imagesearch==2.0.0
azure-cognitiveservices-search-newssearch==2.0.0
azure-cognitiveservices-search-videosearch==2.0.0
azure-cognitiveservices-search-visualsearch==0.2.0
azure-cognitiveservices-search-websearch==2.0.0
azure-cognitiveservices-vision-computervision==0.5.0
azure-cognitiveservices-vision-contentmoderator==1.0.0
azure-cognitiveservices-vision-customvision==1.0.0
azure-cognitiveservices-vision-face==0.4.0
azure-common==1.1.24
azure-core==1.24.2
azure-cosmos==3.1.1
azure-cosmosdb-table==1.0.6
azure-datalake-store==0.0.48
azure-devops==0.17.0
azure-eventgrid==1.3.0
azure-eventhub==5.0.0
azure-eventhub-checkpointstoreblob==1.0.0
azure-eventhub-checkpointstoreblob-aio==1.0.0
azure-functions-devops-build==0.0.22
azure-graphrbac==0.61.1
azure-identity==1.7.0
azure-keyvault==4.0.0
azure-keyvault-certificates==4.0.0
azure-keyvault-keys==4.1.0b1
azure-keyvault-secrets==4.1.0b1
azure-loganalytics==0.1.0
azure-mgmt==5.0.0a1
azure-mgmt-advisor==3.0.0
azure-mgmt-alertsmanagement==0.2.0rc2
azure-mgmt-apimanagement==0.1.0
azure-mgmt-appconfiguration==0.3.0
azure-mgmt-applicationinsights==0.2.0
azure-mgmt-appplatform==0.1.0
azure-mgmt-attestation==0.1.0
azure-mgmt-authorization==0.60.0
azure-mgmt-automation==0.1.1
azure-mgmt-azurestack==0.1.0
azure-mgmt-batch==7.0.0
azure-mgmt-billing==0.2.0
azure-mgmt-botservice==0.2.0
azure-mgmt-cdn==4.1.0rc1
azure-mgmt-cognitiveservices==5.0.0
azure-mgmt-commerce==1.0.1
azure-mgmt-compute==10.0.0
azure-mgmt-consumption==3.0.0
azure-mgmt-containerinstance==1.5.0
azure-mgmt-containerregistry==10.0.0
azure-mgmt-containerservice==8.2.0
azure-mgmt-core==1.3.1
azure-mgmt-cosmosdb==0.11.0
azure-mgmt-costmanagement==0.1.0
azure-mgmt-databoxedge==0.1.0
azure-mgmt-databricks==0.1.0
azure-mgmt-datafactory==0.8.0
azure-mgmt-datalake-analytics==0.6.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-datamigration==4.0.0
azure-mgmt-datashare==0.1.0rc1
azure-mgmt-deploymentmanager==0.2.0
azure-mgmt-devspaces==0.2.0
azure-mgmt-devtestlabs==4.0.0
azure-mgmt-dns==3.0.0
azure-mgmt-documentdb==0.1.3
azure-mgmt-edgegateway==0.1.0
azure-mgmt-eventgrid==3.0.0rc4
azure-mgmt-eventhub==3.0.0
azure-mgmt-frontdoor==0.3.0
azure-mgmt-hanaonazure==0.12.0
azure-mgmt-hdinsight==1.4.0
azure-mgmt-healthcareapis==0.1.0
azure-mgmt-hybridcompute==0.1.1
azure-mgmt-imagebuilder==0.3.0
azure-mgmt-iotcentral==2.0.0
azure-mgmt-iothub==0.10.0
azure-mgmt-iothubprovisioningservices==0.2.0
azure-mgmt-keyvault==2.0.0
azure-mgmt-kusto==0.5.0
azure-mgmt-labservices==0.1.1
azure-mgmt-loganalytics==0.2.0
azure-mgmt-logic==4.0.0rc2
azure-mgmt-machinelearningcompute==0.4.1
azure-mgmt-machinelearningservices==0.1.0
azure-mgmt-maintenance==0.1.0
azure-mgmt-managedservices==1.0.0
azure-mgmt-managementgroups==0.2.0
azure-mgmt-managementpartner==0.1.1
azure-mgmt-maps==0.1.0
azure-mgmt-marketplaceordering==0.2.1
azure-mgmt-media==2.1.0
azure-mgmt-mixedreality==0.1.0
azure-mgmt-monitor==0.7.0
azure-mgmt-msi==1.0.0
azure-mgmt-netapp==0.8.0
azure-mgmt-network==9.0.0
azure-mgmt-notificationhubs==2.1.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-operationsmanagement==0.1.0
azure-mgmt-peering==0.1.0rc2
azure-mgmt-policyinsights==0.4.0
azure-mgmt-powerbidedicated==0.1.0
azure-mgmt-powerbiembedded==2.0.0
azure-mgmt-privatedns==0.1.0
azure-mgmt-rdbms==1.9.0
azure-mgmt-recoveryservices==0.4.0
azure-mgmt-recoveryservicesbackup==0.6.0
azure-mgmt-redis==7.0.0rc1
azure-mgmt-relay==0.2.0
azure-mgmt-reservations==0.7.0
azure-mgmt-resource==21.1.0
azure-mgmt-resourcegraph==2.0.0
azure-mgmt-scheduler==2.0.0
azure-mgmt-search==2.1.0
azure-mgmt-security==0.3.0
azure-mgmt-serialconsole==0.1.0
azure-mgmt-servermanager==2.0.0
azure-mgmt-servicebus==0.6.0
azure-mgmt-servicefabric==0.4.0
azure-mgmt-signalr==0.3.0
azure-mgmt-sql==0.16.0
azure-mgmt-sqlvirtualmachine==0.5.0
azure-mgmt-storage==20.0.0
azure-mgmt-storagecache==1.3.0
azure-mgmt-storagesync==0.2.0
azure-mgmt-subscription==0.5.0
azure-mgmt-timeseriesinsights==0.1.0
azure-mgmt-trafficmanager==0.51.0
azure-mgmt-vmwarecloudsimple==0.2.0
azure-mgmt-web==0.44.0
azure-multiapi-storage==0.2.4
azure-nspkg==3.0.2
azure-servicebus==0.50.2
azure-servicefabric==7.0.0.0
azure-servicemanagement-legacy==0.20.7
azure-storage-blob==12.9.0
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-file-datalake==12.0.0b7
azure-storage-file-share==12.0.1
azure-storage-queue==12.4.0
azure-template==0.0.1
azureml-automl-core==1.43.0.post2
azureml-automl-runtime==1.43.0
azureml-contrib-notebook==1.43.0
azureml-core==1.43.0
azureml-dataprep==4.0.4
azureml-dataprep-native==38.0.0
azureml-dataprep-rslex==2.6.3
azureml-dataset-runtime==1.43.0
azureml-defaults==1.43.0
azureml-explain-model==1.43.0
azureml-inference-server-http==0.4.13
azureml-interpret==1.43.0
azureml-mlflow==1.43.0.post1
azureml-pipeline==1.43.0
azureml-pipeline-core==1.43.0
azureml-pipeline-steps==1.43.0
azureml-sdk==1.43.0
azureml-telemetry==1.43.0
azureml-train-automl==1.43.0
azureml-train-automl-client==1.43.0
azureml-train-automl-runtime==1.43.0.post1
azureml-train-core==1.43.0
azureml-train-restclients-hyperdrive==1.43.0
azureml-training-tabular==1.43.0
azureml-widgets==1.43.0
backcall==0.2.0
backports.tempfile==1.0
backports.weakref==1.0.post1
bcrypt==3.1.7
bleach==5.0.1
blinker==1.4
bokeh==2.4.3
boto==2.49.0
boto3==1.20.19
botocore==1.23.19
bottle==0.12.21
cachetools==5.2.0
certifi==2019.11.28
cffi==1.14.0
chardet==3.0.4
Click==7.0
cloud-init==20.1
cloudpickle==2.1.0
colorama==0.4.3
command-not-found==0.3
configobj==5.0.6
configparser==3.7.4
constantly==15.1.0
contextlib2==21.6.0
cryptography==2.8
Cython==0.29.17
dask==2.30.0
databricks-cli==0.17.0
dataclasses==0.6
dbus-python==1.2.16
debugpy==1.6.2
decorator==5.1.1
defusedxml==0.7.1
dill==0.3.5.1
distributed==2.30.1
distro==1.4.0
distro-info===0.23ubuntu1
docker==5.0.3
dotnetcore2==3.1.23
entrypoints==0.3
executing==0.8.3
fabric==2.5.0
fastjsonschema==2.15.3
fire==0.4.0
Flask==1.0.3
flatbuffers==2.0
fsspec==2022.5.0
fusepy==3.0.1
future==0.18.2
gensim==3.8.3
gitdb==4.0.9
GitPython==3.1.27
google-api-core==2.8.2
google-auth==2.8.0
googleapis-common-protos==1.56.3
gunicorn==20.1.0
HeapDict==1.0.1
httplib2==0.14.0
humanfriendly==4.18
hyperlink==19.0.0
idna==2.8
importlib-metadata==4.12.0
incremental==16.10.1
inference-schema==1.3.0
interpret-community==0.26.0
interpret-core==0.2.7
invoke==1.3.0
ipykernel==6.15.1
ipython==8.4.0
ipython-genutils==0.2.0
ipywidgets==7.7.1
isodate==0.6.1
itsdangerous==1.1.0
javaproperties==0.6.0
jedi==0.18.1
Jinja2==2.10.1
jmespath==0.9.4
joblib==0.14.1
jsmin==2.2.2
json-logging-py==0.2
jsondiff==1.1.1
jsonpatch==1.22
jsonpickle==2.2.0
jsonpointer==2.0
jsonschema==3.2.0
jupyter-client==6.1.12
jupyter-core==4.11.1
jupyterlab-widgets==1.1.1
keras2onnx==1.6.0
keyring==18.0.1
knack==0.9.0
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
lightgbm==3.2.1
llvmlite==0.36.0
locket==1.0.0
MarkupSafe==1.1.0
matplotlib-inline==0.1.3
mistune==0.8.4
ml-wrappers==0.2.0
mlflow-skinny==1.27.0
mock==3.0.5
more-itertools==4.2.0
msal==1.18.0
msal-extensions==1.0.0
msgpack==1.0.4
msrest==0.6.21
msrestazure==0.6.4
multidict==4.7.3
nbconvert==5.6.1
nbformat==5.4.0
ndg-httpsclient==0.5.1
nest-asyncio==1.5.5
netifaces==0.10.4
nimbusml==1.8.0
notebook==6.4.12
numba==0.53.1
numpy==1.23.1
oauthlib==3.1.0
onnx==1.7.0
onnxconverter-common==1.6.0
onnxmltools==1.4.1
onnxruntime==1.8.1
opencensus==0.9.0
opencensus-context==0.1.2
opencensus-ext-azure==1.1.4
packaging==21.3
pandas==1.1.5
pandocfilters==1.5.0
papermill==1.2.1
paramiko==2.6.0
parso==0.8.3
partd==1.2.0
pathspec==0.9.0
patsy==0.5.2
pbr==5.4.5
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.2.0
pkginfo==1.4.2
ply==3.11
pmdarima==1.7.1
portalocker==2.4.0
prometheus-client==0.14.1
prompt-toolkit==3.0.30
protobuf==3.20.1
psutil==5.9.1
ptyprocess==0.7.0
pure-eval==0.2.2
pyarrow==3.0.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycparser==2.19
Pygments==2.3.1
PyGObject==3.36.0
PyHamcrest==1.9.0
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyparsing==3.0.9
pyrsistent==0.15.5
pyserial==3.4
PySocks==1.7.1
python-apt==2.0.0
python-dateutil==2.8.2
python-debian===0.1.36ubuntu1
pytz==2019.3
PyYAML==5.3.1
pyzmq==23.2.0
requests==2.22.0
requests-oauthlib==1.3.1
requests-unixsocket==0.2.0
rsa==4.8
s3transfer==0.5.2
scikit-learn==0.22.2.post1
scipy==1.5.3
scp==0.13.0
SecretStorage==2.3.1
Send2Trash==1.8.0
service-identity==18.1.0
shap==0.39.0
simplejson==3.16.0
six==1.14.0
skl2onnx==1.4.9
sklearn-pandas==1.7.0
slicer==0.0.7
smart-open==1.9.0
smmap==5.0.0
sortedcontainers==2.4.0
ssh-import-id==5.10
sshtunnel==0.1.4
stack-data==0.3.0
statsmodels==0.11.1
systemd-python==234
tabulate==0.8.6
tblib==1.7.0
tenacity==8.0.1
termcolor==1.1.0
terminado==0.15.0
testpath==0.6.0
textwrap3==0.9.2
toolz==0.12.0
tornado==6.2
tqdm==4.64.0
traitlets==5.3.0
Twisted==18.9.0
typing-extensions==4.2.0
uamqp==1.2.6
ubuntu-advantage-tools==20.3
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
vsts-cd-manager==1.0.2
wadllib==1.3.3
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==0.53.0
Werkzeug==1.0.1
widgetsnbextension==3.6.1
wrapt==1.12.1
xmltodict==0.12.0
yarl==1.4.2
zict==2.2.0
zipp==1.0.0
zope.interface==4.7.1

**Comment by kamrapooja** [comment]
I am also facing the same issue. What i observed is when we install azure storage package from requirement.txt file the size of __init__.py file of blob package is different than the file we got while manually installaing the package.
PFA files.
[init_files.zip](https://github.com/Azure/azure-sdk-for-python/files/9476619/init_files.zip)
In this zip file, two files are available.
1. __init__.py gets generated when we manually install the azure-storage-blob package.
2. __init__1.py gets generated when we install the package using requirements.txt file.

Azure packages that are being installed from requirement.txt files are -
azure-ai-textanalytics==5.2.0b1
azure-common==1.1.28
azure-core==1.25.0
azure-nspkg==3.0.2
azure-storage==0.36.0
azure-storage-blob==12.12.0

Please help to resolve it.

**Comment by jalauzon-msft** [comment]
Hi @wtam and @kamrapooja, sorry for the delay, looks like this one was missed by us.

Import errors like this are typically an indication of some issue with environment setup or some unwanted interaction between dependencies. They normally need to be looked at on a case-by-case basis.

---
@wtam
Could you share what package you are trying to install and how you are doing it? Looking at your `pip freeze`, it looks like you have every Azure SDK package in there :). Looking at just your Storage packages:
```
azure-storage-blob==12.9.0
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-file-datalake==12.0.0b7
azure-storage-file-share==12.0.1
azure-storage-queue==12.4.0
```

You have a very early **beta** version of `azure-storage-file-datalake` (12.0.0b7) and a somewhat more recent version of `azure-storage-blob` (12.9.0). Datalake depends on blob, and this could be a case that your version of datalake is too old for your version of blob. I would try installing the most recent version of both of these. Be sure if you are using `pip install` that you are using `--upgrade` flag so your versions actually get updated.

Also of note but probably unrelated, is you have `azure-storage-file` and `azure-storage-common` which are both now deprecated and no longer supported. If you are not using these, I would recommend removing them.

---

@kamrapooja, looking at your `__init__` files, the one from the requirements file seems to be from an old, deprecated version of the blob SDK (probably something like 2.x.x) whereas the other file looks correct for the version of blob you are trying to install. I'm not entirely sure where this is coming from, but I think something in your requirements file must be pointing at an old version.

It could be `azure-storage==0.36.0`. That is an old deprecated meta-package that should not be installed anymore. The most recent version 0.37.0 will give an error when installed but 0.36.0 may be trying to install old packages. I would try removing that since it should not be needed.

If that does not fix the issue, please share your full requiremnets.txt file and/or the results of `pip freeze` after install (if possible).

**Comment by kamrapooja** [comment]
Issue got resolved after removing following packages - 
azure-common==1.1.28
azure-core==1.25.0
azure-nspkg==3.0.2
azure-storage==0.36.0
