### ISSUE TITLE
Cosmos DB async module can't run SQL queries containing the VALUE keyword

### ISSUE THREAD

**Issue by yuvalherziger** [Azure/azure-sdk-for-python#25405]
- **Package Name**: azure-cosmos
- **Package Version**: 4.3.0
- **Operating System**: macOS 12.4 (21F79)
- **Python Version**: 3.8.9

**Describe the bug**

Queries containing the `VALUE` keyword will fail when querying a Cosmos DB table with the asynchronous submodule (`azure.cosmos.aio`). The async iterator returned by `query_items()` method will break upon entrance, probably because an array of scalars is returned, as expected, instead of an array of dictionaries.  It is therefore impossible to use `container.query_items()` with a query like `SELECT VALUE COUNT(c.id) FROM c`.

**To Reproduce**

Please see the snippet and error trace below:

1. Instantiate an async CosmosDB client (instance of `azure.cosmos.aio.CosmosClient`).
2. Get the database client from the async Cosmos DB client.
3. Get the container client from the database client.
4. Use the container client's `query_items()` method with a query containing the `VALUE` keyword, e.g., `SELECT VALUE COUNT(c.id) FROM c`.
5. Expect an error along the following lines:

   ```
   TypeError: 'async for' received an object from __aiter__ that does not implement __anext__: coroutine
   ```

**Expected behavior**

Querying with the `VALUE` keyword should be possible and iterable using the `query_items()`.

**Code Sample**

```python
import json
import os

import asyncio
from azure.cosmos import exceptions
from azure.cosmos.aio import CosmosClient


async def get_row_count():
    client_creds = os.environ.get("COSMOS_ACCOUNT_KEY")
    account_uri = os.environ.get("ACCOUNT_URI")
    container_name = os.environ.get("CONTAINER_NAME")
    cosmos_db_name = os.environ.get("COSMOS_DB_NAME")
    sql_query = "SELECT VALUE COUNT(c.id) FROM c WHERE c.someAttr = 'someCondition'"
    async with CosmosClient(account_uri, credential=client_creds) as c:
        try:
            db = c.get_database_client(cosmos_db_name)
            co = db.get_container_client(container_name)
            res = []
            q = co.query_items(query=sql_query)
            # This breaks everything:
            async for a in q:
                res.append(a)
            return res
        except exceptions.CosmosHttpResponseError:
            raise


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(get_row_count())
```

Running this script (with the required env. variables) results in the following stack trace:

```
/Users/yherziger/Library/Caches/pypoetry/virtualenvs/az-python-sdk-bug-v0h8-23u-py3.8/lib/python3.8/site-packages/azure/cosmos/_execution_context/aio/endpoint_component.py:179: RuntimeWarning: coroutine '_QueryExecutionEndpointComponent.__aiter__' was never awaited
  async for res in self._execution_context:
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "async.py", line 55, in <module>
    loop.run_until_complete(get_row_count())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "async.py", line 46, in get_row_count
    async for a in q:
  File "/Users/yherziger/Library/Caches/pypoetry/virtualenvs/az-python-sdk-bug-v0h8-23u-py3.8/lib/python3.8/site-packages/azure/core/async_paging.py", line 154, in __anext__
    return await self.__anext__()
  File "/Users/yherziger/Library/Caches/pypoetry/virtualenvs/az-python-sdk-bug-v0h8-23u-py3.8/lib/python3.8/site-packages/azure/core/async_paging.py", line 157, in __anext__
    self._page = await self._page_iterator.__anext__()
  File "/Users/yherziger/Library/Caches/pypoetry/virtualenvs/az-python-sdk-bug-v0h8-23u-py3.8/lib/python3.8/site-packages/azure/core/async_paging.py", line 99, in __anext__
    self._response = await self._get_next(self.continuation_token)
  File "/Users/yherziger/Library/Caches/pypoetry/virtualenvs/az-python-sdk-bug-v0h8-23u-py3.8/lib/python3.8/site-packages/azure/cosmos/aio/_query_iterable_async.py", line 102, in _fetch_next
    block = await self._ex_context.fetch_next_block()
  File "/Users/yherziger/Library/Caches/pypoetry/virtualenvs/az-python-sdk-bug-v0h8-23u-py3.8/lib/python3.8/site-packages/azure/cosmos/_execution_context/aio/execution_dispatcher.py", line 99, in fetch_next_block
    return await self._execution_context.fetch_next_block()
  File "/Users/yherziger/Library/Caches/pypoetry/virtualenvs/az-python-sdk-bug-v0h8-23u-py3.8/lib/python3.8/site-packages/azure/cosmos/_execution_context/aio/execution_dispatcher.py", line 188, in fetch_next_block
    results.append(await self.__anext__())
  File "/Users/yherziger/Library/Caches/pypoetry/virtualenvs/az-python-sdk-bug-v0h8-23u-py3.8/lib/python3.8/site-packages/azure/cosmos/_execution_context/aio/execution_dispatcher.py", line 170, in __anext__
    return await self._endpoint.__anext__()
  File "/Users/yherziger/Library/Caches/pypoetry/virtualenvs/az-python-sdk-bug-v0h8-23u-py3.8/lib/python3.8/site-packages/azure/cosmos/_execution_context/aio/endpoint_component.py", line 179, in __anext__
    async for res in self._execution_context:
TypeError: 'async for' received an object from __aiter__ that does not implement __anext__: coroutine
```

**Screenshots**

N\A

**Additional context**

This issue is rather critical because cross-partitioned tables can't be queried with aggregate functions without the `VALUE` keyword.

The same functionality works as expected with the standard Cosmos DB client (not async).

**Comment by swathipil** [comment]
Hi @yuvalherziger - Thanks for opening an issue! We'll investigate asap!

**Comment by JericHunter** [comment]
Thank you very much for the detailed explanation as well as the code snippet, I have found the fix for this issue and it will be out asap. Thanks again!
