### ISSUE TITLE
speechsdk.transcription not appearing as an option

### ISSUE THREAD

**Issue by uriii3** [Azure/azure-sdk-for-python#25467]
- **Package Name**: azure-cognitiveservices-speech
- **Package Version**: 1.18 (I think)
- **Operating System**: macOs
- **Python Version**: 3.6.3

**Error**
Traceback (most recent call last):
  File "transcription_sample.py", line 99, in <module>
    conversation_transcription_differentiate_speakers()
  File "transcription_sample.py", line 59, in conversation_transcription_differentiate_speakers
    conversation = speechsdk.transcription.Conversation(speech_config, conversation_id)
AttributeError: module 'azure.cognitiveservices.speech' has no attribute 'transcription'

**Account from Azure**: Developer. I think that maybe this is the problem(?)

**Code that I'm using:**
[Transaction_sample from the axure documentation
](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/transcription_sample.py)

**Comment by swathipil** [comment]
@uriii3 - Thanks for your question! We'll investigate as soon as possible!

**Comment by kristapratico** [comment]
Hi @uriii3, it looks like the conversation transcription feature was added in version 1.21.0 of the client library: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/releasenotes?tabs=speech-sdk#speech-sdk-1210-april-2022-release

Can you try updating your package to this version and see if that works?
`pip install azure-cognitiveservices-speech --upgrade` should update you to the latest stable version of the package.

**Comment by kristapratico** [comment]
Hi @uriii3, hmm let's try to be more explicit then. Can you try specifying the exact version in your install command?

`pip install azure-cognitiveservices-speech==1.21.0`

**Comment by uriii3** [comment]
Hello,

I just resolved the issue today with another problem that i was having.
Turns out my python was outdated and then the version wasn't suited for the
one i had.

Thank you very much for everything!

El dt., 6 de set. 2022, 18:20, Krista Pratico ***@***.***> va
escriure:
