### ISSUE TITLE
Misleading warning when downloading empty blob

### ISSUE THREAD

**Issue by Stevenjin8** [Azure/azure-sdk-for-python#25780]
- **Azure Storage Blob**: 
- **12.13.0**: 
- **Ubuntu (WSL 2)**:
- **3.9.6**: 

**Describe the bug**

Downloading an empty blob logs an error including a traceback despite downloading successfully.

**To Reproduce**

```python
  service_client = BlobServiceClient(
      endpoint, key
  )
  container_client = service_client.get_container_client("mycontainer")
  blob_name = "empty"
  container_client.upload_blob(blob_name, data=BytesIO(), overwrite=True)

  blob = container_client.get_blob_client(blob_name)
  blob.download_blob()
```

**Expected behavior**

The code should run without any error or warnings.

**Screenshots**

Here is the output

```python
(.venv) LAPTOP-E0C4GD2A% python secret/storage.py
Ran into a deserialization error. Ignoring since this is failsafe deserialization
Traceback (most recent call last):
  File "/home/stevenjin8/code/azure-sdk-for-python/sdk/storage/azure-storage-blob/azure/storage/blob/_generated/_serialization.py", line 1506, in failsafe_deserialize
    return self(target_obj, data, content_type=content_type)
  File "/home/stevenjin8/code/azure-sdk-for-python/sdk/storage/azure-storage-blob/azure/storage/blob/_generated/_serialization.py", line 1377, in __call__
    data = self._unpack_content(response_data, content_type)
  File "/home/stevenjin8/code/azure-sdk-for-python/sdk/storage/azure-storage-blob/azure/storage/blob/_generated/_serialization.py", line 1535, in _unpack_content
    raise ValueError("This pipeline didn't have the RawDeserializer policy; can't deserialize")
ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize
```

If you miss the first line, it seems like an error occurred.

**Comment by jalauzon-msft** [comment]
Thanks @Stevenjin8! Closing this one and using customer-reported #25954 to track.
