### ISSUE TITLE
Issue with accessing secrets

### ISSUE THREAD

**Issue by JaakkoAhola** [Azure/azure-sdk-for-python#26328]
Hi!

I have been following [Azure machine learning studio tutorial](https://docs.microsoft.com/en-us/azure/machine-learning/tutorial-1st-experiment-hello-world) and expanding the tutorial by trying to access secrets from the keyvault.

My run script is
```python
# run-pytorch.py
from azure.ai.ml import MLClient, command, Input
from azure.identity import DefaultAzureCredential
from azure.ai.ml.entities import Environment
from azureml.core import Workspace
from datetime import datetime
import os
import sys

import logging

# ...

# Acquire the logger for a library (azure.mgmt.resource in this example)
logger = logging.getLogger('azure.mgmt.resource')

# Set the desired logging level
logger.setLevel(logging.DEBUG)

if __name__ == "__main__":
    # get details of the current Azure ML workspace
    ws = Workspace.from_config()

    # default authentication flow for Azure applications
    default_azure_credential = DefaultAzureCredential()
    subscription_id = ws.subscription_id
    resource_group = ws.resource_group
    workspace = ws.name
    
    # client class to interact with Azure ML services and resources, e.g. workspaces, jobs, models and so on.
    ml_client = MLClient(
        default_azure_credential,
        subscription_id,
        resource_group,
        workspace)

    env_name = "env"
    env_docker_image = Environment(
        image="pytorch/pytorch:latest",
        name=env_name,
        conda_file="pilvi_env.yml",
    )
    ml_client.environments.create_or_update(env_docker_image)
    
    # target name of compute where job will be executed
    date_stamp = datetime.now().strftime('%Y-%m-%d')
    try:
        day_name = date_stamp #f"-{sys.argv[1]}"
    except KeyError:
        day_name = ""

    print(f"day_name {day_name}")

    computeName="cpu-cluster"
    job = command(
        code="./src",
        command="python pilvi_hello_world.py",
        environment=f"{env_name}@latest",
        compute=computeName,
        display_name=f"experiment-pilvi-demo-day{day_name}",
    )

    returned_job = ml_client.create_or_update(job)
    aml_url = returned_job.studio_url
    keyvault = ws.get_default_keyvault()
    secret = keyvault.get_secret("testi")

    print(f"testi secret length: {len(secret)}")
    print()
    print("Monitor your job at", aml_url)

    
```

The run script itself accesses the "testi" secret **successfully**.
However, the job that the run script is actually running `command="python pilvi_hello_world.py"`
can't get access to the secret.
The script that the run script executes:
```python
from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient

import logging

# ...

# Acquire the logger for a library (azure.mgmt.resource in this example)
logger = logging.getLogger('azure.mgmt.resource')

# Set the desired logging level
logger.setLevel(logging.DEBUG)

credential = DefaultAzureCredential()


vault_url ="https://keyvaultname.vault.azure.net/"
secret_client = SecretClient(vault_url=vault_url, credential=credential)
retrieved_secret = secret_client.get_secret("testi")
print(f"testi avain: {len(retrieved_secret)}")
```
It produces the following error message:

```python
DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot.this issue.
	ManagedIdentityCredential: No connection adapters were found for 'identity-responder-not-enabled?api-version=2017-09-01&resource=https://vault.azure.net'
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
Traceback (most recent call last):
  File "pilvi_hello_world.py", line 21, in <module>
    retrieved_secret = secret_client.get_secret("testi")
  File "/azureml-envs/azureml_a5e86964f1312e3d9d3ff27fdd81339e/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/azureml-envs/azureml_a5e86964f1312e3d9d3ff27fdd81339e/lib/python3.8/site-packages/azure/keyvault/secrets/_client.py", line 68, in get_secret
    bundle = self._client.get_secret(
  File "/azureml-envs/azureml_a5e86964f1312e3d9d3ff27fdd81339e/lib/python3.8/site-packages/azure/keyvault/secrets/_generated/_operations_mixin.py", line 1574, in get_secret
    return mixin_instance.get_secret(vault_base_url, secret_name, secret_version, **kwargs)
  File "/azureml-envs/azureml_a5e86964f1312e3d9d3ff27fdd81339e/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/azureml-envs/azureml_a5e86964f1312e3d9d3ff27fdd81339e/lib/python3.8/site-packages/azure/keyvault/secrets/_generated/v7_3/operations/_key_vault_client_operations.py", line 694, in get_secret
    pipeline_response = self._client._pipeline.run(  # pylint: disable=protected-access
  File "/azureml-envs/azureml_a5e86964f1312e3d9d3ff27fdd81339e/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/azureml-envs/azureml_a5e86964f1312e3d9d3ff27fdd81339e/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/azureml-envs/azureml_a5e86964f1312e3d9d3ff27fdd81339e/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/azureml-envs/azureml_a5e86964f1312e3d9d3ff27fdd81339e/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/azureml-envs/azureml_a5e86964f1312e3d9d3ff27fdd81339e/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/azureml-envs/azureml_a5e86964f1312e3d9d3ff27fdd81339e/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry.py", line 446, in send
    response = self.next.send(request)
  File "/azureml-envs/azureml_a5e86964f1312e3d9d3ff27fdd81339e/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 127, in send
    request_authorized = self.on_challenge(request, response)
  File "/azureml-envs/azureml_a5e86964f1312e3d9d3ff27fdd81339e/lib/python3.8/site-packages/azure/keyvault/secrets/_shared/challenge_auth_policy.py", line 102, in on_challenge
    self.authorize_request(request, scope, tenant_id=challenge.tenant_id)
  File "/azureml-envs/azureml_a5e86964f1312e3d9d3ff27fdd81339e/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 106, in authorize_request
    self._token = self._credential.get_token(*scopes, **kwargs)
  File "/azureml-envs/azureml_a5e86964f1312e3d9d3ff27fdd81339e/lib/python3.8/site-packages/azure/identity/_credentials/default.py", line 175, in get_token
    return super(DefaultAzureCredential, self).get_token(*scopes, **kwargs)
  File "/azureml-envs/azureml_a5e86964f1312e3d9d3ff27fdd81339e/lib/python3.8/site-packages/azure/identity/_credentials/chained.py", line 108, in get_token
    raise ClientAuthenticationError(message=message)
azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot.this issue.
	ManagedIdentityCredential: No connection adapters were found for 'identity-responder-not-enabled?api-version=2017-09-01&resource=https://vault.azure.net'
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.


```

The error message leads to this section in this repository [Troubleshoot EnvironmentCredential Authentication Issues](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/TROUBLESHOOTING.md#troubleshoot-environmentcredential-authentication-issues) which says about storing the `AZURE_CLIENT_ID`, `AZURE_TENANT_ID` and `AZURE_CLIENT_SECRET` as environment variables. As these values are secrets (right?), it would be kinda clumsy to set secrets as environment variables to get access to secrets, as I am running these in the cloud in Azure ML studio terminal: [ml.azure.com](ml.azure.com).

 I've added explicit reader rights for the workspace as a managed identity. I've been searching for answers in the documentation for several days to no avail.

What am I missing or am I approaching the problem in wrong way altogether?

**Comment by l0lawrence** [comment]
Hi @JaakkoAhola thanks for the question, we'll get back to you asap.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

The job "python pilvi_hello_world.py" runs in Azure ML managed computer instance. It is different from the host that you run this script.

Please take https://learn.microsoft.com/en-us/azure/machine-learning/how-to-use-managed-identities?tabs=python as a reference how to configure MI for Azure ML computer instance.
