### ISSUE TITLE
EventHubProducerClient with custom_endpoint_address fails with: ErrorCodes.UnknownError: Connection in an unexpected error state.

### ISSUE THREAD

**Issue by cmendible** [Azure/azure-sdk-for-python#26447]
- **Package Name**:  azure.eventhub
- **Package Version**:  azure_eventhub-5.10.1.dist-info
- **Operating System**: Linux or Windows
- **Python Version**:  Python 3.10.7

**Describe the bug**

Running the following code sample:

``` python
from azure.eventhub import EventData, EventHubProducerClient, TransportType
from azure.identity import EnvironmentCredential

credential = EnvironmentCredential()

producer = EventHubProducerClient(
    fully_qualified_namespace="<evh namespace>", 
    eventhub_name="<evh name>",
    credential=credential,
    logging_enable=True,  # To enable network tracing log, set logging_enable to True.
    retry_total=0,  # Retry up to 3 times to re-do failed operations.
    custom_endpoint_address = "sb://<endpoint address>:5671")

with producer:
    event_data_batch = producer.create_batch()
    event_data_batch.add(EventData('Message inside EventBatchData'))
    producer.send_batch(event_data_batch)

print('Finished sending.')
```
Fails with the following message:

``` bash
ConnectionClose('ErrorCodes.UnknownError: Connection in an unexpected error state.')
Traceback (most recent call last):
  File "C:\Users\azureadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\eventhub\_client_base.py", line 567, in _do_retryable_operation
    return operation()
  File "C:\Users\azureadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\eventhub\_client_base.py", line 526, in _open
    while not self._handler.client_ready():
  File "C:\Users\azureadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\uamqp\client.py", line 385, in client_ready
    self._connection.work()
  File "C:\Users\azureadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\uamqp\connection.py", line 252, in work
    raise self._error
uamqp.errors.ConnectionClose: ErrorCodes.UnknownError: Connection in an unexpected error state.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\azureadmin\Desktop\pysample\send.py", line 15, in <module>
    event_data_batch = producer.create_batch()
  File "C:\Users\azureadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\eventhub\_producer_client.py", line 714, in create_batch
    self._get_max_message_size()
  File "C:\Users\azureadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\eventhub\_producer_client.py", line 321, in _get_max_message_size
    )._open_with_retry()
  File "C:\Users\azureadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\eventhub\_producer.py", line 152, in _open_with_retry
    return self._do_retryable_operation(self._open, operation_need_param=False)
  File "C:\Users\azureadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\eventhub\_client_base.py", line 583, in _do_retryable_operation
    raise last_exception
azure.eventhub.exceptions.ConnectionLostError: Connection in an unexpected error state.
ErrorCodes.UnknownError: Connection in an unexpected error state.
```

Same thing happens if the custom endpoint is changed to `https://<endpoint address>:443`

**Expected behavior**
Messages should flow to the Event Hub using a custom endpoint address for both AmqpWebSockets and AmqpTcp.

**Comment by kashifkhan** [comment]
Thank you for submitting this bug report @cmendible. We will take a look and get back to you asap.

**Comment by cmendible** [comment]
If you need we can schedule a quick call so I can show you the repro. 😉

**Comment by l0lawrence** [comment]
Hello @cmendible!  Would you be able to add a uamqp logger (as below) to your code snippet? 
`
logger = logging.getLogger('uamqp')`
`logger.setLevel(logging.DEBUG)`
`handler = logging.StreamHandler(stream=sys.stdout)`
`logger.addHandler(handler)
`

This will give you verbose logs, however it will let you see a more specific error message. For example, another parameter [connection_verify](https://github.com/Azure/azure-sdk-for-python/blob/0fa791664228aeecf10752af72bf62892a075d40/sdk/eventhub/azure-eventhub/azure/eventhub/_producer_client.py#L121) may be required in order to authenticate the connection to the custom endpoint. That certificate error will show in the logs like this:

`b'CertVerifyCertificateChainPolicy sets certificateStatus = 0x800b0109' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\deps\\azure-c-shared-utility\\adapters\\x509_schannel.c':b'x509_verify_certificate_in_chain':600)
b'Failed to verify trusted certificate in chain' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\deps\\azure-c-shared-utility\\adapters\\tlsio_schannel.c':b'verify_custom_certificate_if_needed':451)
b'Unable to verify server certificate against custom server trusted certificate' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\deps\\azure-c-shared-utility\\adapters\\tlsio_schannel.c':b'on_underlying_io_bytes_received':710)
b'wsio_close when not open.' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\deps\\azure-c-shared-utility\\src\\wsio.c':b'internal_close':153)`

I am also free to chat tomorrow if this is easier to do over a call.

**Comment by cmendible** [comment]
Thanks for that one!

I used `print(certifi.where())` to check the `cacert.pem` file location and appended the root CA. This fixed the connection for AmqpWebSockets: `custom_endpoint_address = "https://<custom endpoint>:443")`

However we are still facing issues for AmqpTcp: `custom_endpoint_address = "sb://evh.contoso.corp:5671")`. This is the current output:

``` bash
C:\Users\azureadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\certifi\cacert.pem
Opening client connection.
Initializing platform.
Connection b'EHProducer-86c837ac-3659-4a03-b6bc-345a72b0f63e' state changed from <ConnectionState.START: 0> to <ConnectionState.START: 0>
Deallocating 'StringValue'
Destroying 'StringValue'
Deallocating 'StringValue'
Destroying 'StringValue'
Deallocating 'StringValue'
Destroying 'StringValue'
Deallocating 'StringValue'
Destroying 'StringValue'
Deallocating 'StringValue'
Destroying 'StringValue'
Deallocating 'DictValue'
Destroying 'DictValue'
Connection b'EHProducer-86c837ac-3659-4a03-b6bc-345a72b0f63e' state changed from <ConnectionState.START: 0> to <ConnectionState.START: 0>
b'[0x90317] The context has expired and can no longer be used.\r\n' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\deps\\azure-c-shared-utility\\adapters\\tlsio_schannel.c':b'on_underlying_io_bytes_received':991)
b'wsio_close when not open.' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\deps\\azure-c-shared-utility\\src\\wsio.c':b'internal_close':153)
Connection b'EHProducer-86c837ac-3659-4a03-b6bc-345a72b0f63e' state changed from <ConnectionState.START: 0> to <ConnectionState.END: 13>
Connection with ID b'EHProducer-86c837ac-3659-4a03-b6bc-345a72b0f63e' unexpectedly in an error state. Closing: False, Error: None
b'AMQP management instance not open' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\src\\amqp_management.c':b'amqp_management_close':1061)
CBS for connection b'EHProducer-86c837ac-3659-4a03-b6bc-345a72b0f63e' completed opening with status: 2
Wrapping value type: <AMQPType.CompositeType: 23>
Wrapping value type: <AMQPType.CompositeType: 23>
Deallocating 'DictValue'
Destroying 'DictValue'
Message sender b'sender-link-8d03e2e6-12a6-4bf4-b006-6ae08c6f41ac' state changed from <MessageSenderState.Idle: 1> to <MessageSenderState.Opening: 2> on connection: b'EHProducer-86c837ac-3659-4a03-b6bc-345a72b0f63e'
Sender link failed to open - expecting to receive DETACH frame.
ConnectionClose('ErrorCodes.UnknownError: Connection in an unexpected error state.')
Destroying cMessageSender
Destroying cLink
Deallocating 'CompositeValue'
Destroying 'CompositeValue'
Deallocating 'CompositeValue'
Destroying 'CompositeValue'
Deallocating cLink
Deallocating cMessageSender
CBS session pending.
Closing exclusive connection.
Unlocked connection b'EHProducer-86c837ac-3659-4a03-b6bc-345a72b0f63e' to close.
Shutting down connection b'EHProducer-86c837ac-3659-4a03-b6bc-345a72b0f63e'.
Shutting down CBS session on connection: b'EHProducer-86c837ac-3659-4a03-b6bc-345a72b0f63e'.
Unlocked CBS to close on connection: b'EHProducer-86c837ac-3659-4a03-b6bc-345a72b0f63e'.
Destroying CBSTokenAuth for connection b'EHProducer-86c837ac-3659-4a03-b6bc-345a72b0f63e'
Token put complete with result: 2, status: 0, description: b'CBS Session closed.', connection: b'EHProducer-86c837ac-3659-4a03-b6bc-345a72b0f63e'
Auth closed, destroying session on connection: b'EHProducer-86c837ac-3659-4a03-b6bc-345a72b0f63e'.
Destroying cSession
Finished shutting down CBS session on connection: b'EHProducer-86c837ac-3659-4a03-b6bc-345a72b0f63e'.
Destroying Connection
b'send called while not open' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\src\\saslclientio.c':b'saslclientio_send_async':1181)
b'Cannot send encoded bytes' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\src\\connection.c':b'on_bytes_encoded':268)
b'saslclientio_close called while not open' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\src\\saslclientio.c':b'saslclientio_close_async':1130)
b'xio_close failed' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\src\\connection.c':b'on_bytes_encoded':272)
Connection b'EHProducer-86c837ac-3659-4a03-b6bc-345a72b0f63e' state changed from <ConnectionState.END: 13> to <ConnectionState.END: 13>
b'-> [CLOSE]* {}'
Connection b'EHProducer-86c837ac-3659-4a03-b6bc-345a72b0f63e' state changed from <ConnectionState.END: 13> to <ConnectionState.END: 13>
b'saslclientio_close called while not open' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\src\\saslclientio.c':b'saslclientio_close_async':1130)
b'xio_close failed' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\src\\connection.c':b'connection_close':1437)
Destroying XIO
Destroying XIO
Destroying SASLMechanism
Connection shutdown complete b'EHProducer-86c837ac-3659-4a03-b6bc-345a72b0f63e'.
Deinitializing platform.
Traceback (most recent call last):
  File "C:\Users\azureadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\eventhub\_client_base.py", line 567, in _do_retryable_operation
    return operation()
  File "C:\Users\azureadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\eventhub\_client_base.py", line 526, in _open
    while not self._handler.client_ready():
  File "C:\Users\azureadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\uamqp\client.py", line 385, in client_ready
    self._connection.work()
  File "C:\Users\azureadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\uamqp\connection.py", line 252, in work
    raise self._error
uamqp.errors.ConnectionClose: ErrorCodes.UnknownError: Connection in an unexpected error state.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\azureadmin\Desktop\pysample\send.py", line 25, in <module>
    event_data_batch = producer.create_batch()
  File "C:\Users\azureadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\eventhub\_producer_client.py", line 714, in create_batch
    self._get_max_message_size()
  File "C:\Users\azureadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\eventhub\_producer_client.py", line 321, in _get_max_message_size
    )._open_with_retry()
  File "C:\Users\azureadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\eventhub\_producer.py", line 152, in _open_with_retry
    return self._do_retryable_operation(self._open, operation_need_param=False)
  File "C:\Users\azureadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\eventhub\_client_base.py", line 583, in _do_retryable_operation
    raise last_exception
azure.eventhub.exceptions.ConnectionLostError: Connection in an unexpected error state.
ErrorCodes.UnknownError: Connection in an unexpected error state.
Deallocating cTarget
Destroying cTarget
Deallocating 'StringValue'
Destroying 'StringValue'
Deallocating 'SymbolValue'
Destroying 'SymbolValue'
Deallocating 'LongValue'
Destroying 'LongValue'
Deallocating SASLMechanism
Deallocating XIO
Deallocating XIO
Deallocating Connection
Deallocating cSession
Deallocating CBSTokenAuth
```

**Comment by l0lawrence** [comment]
Awesome!

> Question: is there anything we can do to bubble up the cert validation exception without the need of the logger?
        Yes, we can look into making this error message more descriptive! Thank you for the feedback. #26485 

With regards to your current error message, that is not one I have seen before so I will need to investigate and get back to you. Currently however, custom endpoint support for the python eventhub sdk is only supported over [websocket ](https://github.com/Azure/azure-sdk-for-python/blob/b37efe5deb6aaa096f039a565e7222201257f0f8/sdk/eventhub/azure-eventhub/azure/eventhub/_configuration.py#L54)connection. Setting the custom_endpoint_address will default the transportType to be AMQPWebsocket. I realize this is not explained explicitly in our documentation, I will add this in.

**Comment by cmendible** [comment]
Will AmqpTcp be supported as other SDK's such as .NET do?
