### ISSUE TITLE
Azure ML SDK is unable to self resolve dependencies

### ISSUE THREAD

**Issue by edgBR** [Azure/azure-sdk-for-python#26477]
- **Package Name**: azureml-core
- **Package Version**: 1.44.0
- **Operating System**: ubuntu20.04
- **Python Version**: 3.8.10

**Describe the bug**
Dear Azure colleagues we are unable to launch a job that was working perfectly fine a week ago.

**To Reproduce**
1. Create an environment with the following specifications:

```conda
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8.10
  - pip=20.1.1=py38_1
  - pip:
     # azureml
    - azureml-core==1.44.0
    - stringcase==1.2.0
    - numpy==1.19.5
    - pandas==1.4.4
    - scikit-learn==1.1.1
    - matplotlib==3.2.1

```

Use the following base image:

mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04

Dockerfile:

```docker
FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
RUN echo "source /opt/miniconda/etc/profile.d/conda.sh &&             conda activate" >> ~/.bashrc
 RUN echo  $'channels:\n\
  - anaconda\n\
  - conda-forge\n\
  - defaults\n\
dependencies:\n\
  - python=3.8.10\n\
  - pip=20.1.1=py38_1\n\
  - pip:\n\
     # azureml\n\
    - azureml-core==1.44.0\n\
    - stringcase==1.2.0\n\
    - numpy==1.19.5\n\
    - pandas==1.4.4\n\
    - scikit-learn==1.1.1\n\
    - matplotlib==3.2.1' > conda_env.yml
RUN source /opt/miniconda/etc/profile.d/conda.sh &&            
 conda activate &&            
 conda install conda &&             
 pip install cmake &&             
 conda env update -f conda_env.yml
```

**Expected behavior**

**Screenshots**
We are getting the following error:

```python
Traceback (most recent call last):
  File "Preprocess/Pipeline/custom_pipeline.py", line 7, in <module>
    from Preprocess.DataLoader.azure import AzureConnector
  File "/mnt/azureml/cr/j/7055b421af8246c3b3caf6787d74d992/exe/wd/Preprocess/DataLoader/__init__.py", line 11, in <module>
    from .azure import AzureConnector
  File "/mnt/azureml/cr/j/7055b421af8246c3b3caf6787d74d992/exe/wd/Preprocess/DataLoader/azure.py", line 1, in <module>
    from azureml.core import Datastore, Dataset, Run, Workspace
  File "/opt/miniconda/lib/python3.8/site-packages/azureml/core/__init__.py", line 13, in <module>
    from .workspace import Workspace
  File "/opt/miniconda/lib/python3.8/site-packages/azureml/core/workspace.py", line 22, in <module>
    from azureml._project import _commands
  File "/opt/miniconda/lib/python3.8/site-packages/azureml/_project/_commands.py", line 8, in <module>
    from azureml._restclient.clientbase import ClientBase
  File "/opt/miniconda/lib/python3.8/site-packages/azureml/_restclient/__init__.py", line 7, in <module>
    from .rest_client import RestClient
  File "/opt/miniconda/lib/python3.8/site-packages/azureml/_restclient/rest_client.py", line 12, in <module>
    from msrest.service_client import ServiceClient
  File "/opt/miniconda/lib/python3.8/site-packages/msrest/__init__.py", line 28, in <module>
    from .configuration import Configuration
  File "/opt/miniconda/lib/python3.8/site-packages/msrest/configuration.py", line 38, in <module>
    from .universal_http.requests import (
  File "/opt/miniconda/lib/python3.8/site-packages/msrest/universal_http/__init__.py", line 53, in <module>
    from ..exceptions import ClientRequestError, raise_with_traceback
  File "/opt/miniconda/lib/python3.8/site-packages/msrest/exceptions.py", line 31, in <module>
    from azure.core.exceptions import SerializationError, DeserializationError
ImportError: cannot import name 'SerializationError' from 'azure.core.exceptions' (/opt/miniconda/lib/python3.8/site-packages/azure/core/exceptions.py)
```

We have been facing this issue already multiple times but we are never able to debug why this is happening. We believe this is because you are changing things in the backend of your API or you updated a depedency of azureml-core that breaks everything.

Honestly this is extremely annoying. Also there is no documentation about this issue.

BR
E

**Comment by mccoyp** [comment]
Hi @edgBR, thank you for opening an issue! I'll get this routed to the appropriate folks so we can look into this as soon as possible. Tagging @azureml-github for awareness.

**Comment by lmazuel** [comment]
Hi @edgBR 

The underlying issue is that your `azure-core` is too old, update it to at least 1.24.0 and your problem would go away. As our `azure-core` is backward compatible guarantee, you can update without any risks.

That being said, why is the dependency system unable to understand that it needs to update azure-core is unclear to me, so I'll leave this issue opened until the ML team could clarify the dependencies.

**Comment by loomlike** [comment]
@lmazuel I'm getting the same issue and due to #23697, cannot just update the package to newer version...

**Comment by luigiw** [comment]
@xiangyan99 I'm wondering if this is caused by azureml-core not on Conda forge? What do you think?

**Comment by xiangyan99** [comment]
@luigiw Let's take offline.

**Comment by luigiw** [comment]
Hello @edgBR , are you still having this problem. Can you run a `pip freeze` in your environment and share the results?
