### ISSUE TITLE
azure.communication.email bad namespace

### ISSUE THREAD

**Issue by toantran-8451** [Azure/azure-sdk-for-python#26784]
- **Package Name**: azure-communication-email
- **Package Version**: 1.0.0b1
- **Operating System**: MacOS
- **Python Version**: 3.7.9

**Describe the bug**
Install azure-communication-email version 1.0.0b1.  Simple import statement throws error:
ModuleNotFoundError: No module named 'email.utils'; 'email' is not a package

**To Reproduce**
1. pip install azure-communication-email==1.0.0b1
2. import azure.communication.email

Detail errors:
Traceback (most recent call last):
  File "email.py", line 1, in <module>
    import azure.communication.email
  File "~/.pyenv/versions/3.7.9/lib/python3.7/site-packages/azure/communication/email/__init__.py", line 7, in <module>
    from ._email_client import EmailClient
  File "~/.pyenv/versions/3.7.9/lib/python3.7/site-packages/azure/communication/email/_email_client.py", line 9, in <module>
    from azure.core.credentials import AzureKeyCredential
  File "~/.pyenv/versions/3.7.9/lib/python3.7/site-packages/azure/core/__init__.py", line 30, in <module>
    from ._pipeline_client import PipelineClient
  File "~/.pyenv/versions/3.7.9/lib/python3.7/site-packages/azure/core/_pipeline_client.py", line 30, in <module>
    from .pipeline import Pipeline
  File "~/.pyenv/versions/3.7.9/lib/python3.7/site-packages/azure/core/pipeline/__init__.py", line 178, in <module>
    from ._base import Pipeline  # pylint: disable=wrong-import-position
  File "~/.pyenv/versions/3.7.9/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 35, in <module>
    from azure.core.pipeline.policies import HTTPPolicy, SansIOHTTPPolicy
  File "~/.pyenv/versions/3.7.9/lib/python3.7/site-packages/azure/core/pipeline/policies/__init__.py", line 31, in <module>
    from ._retry import RetryPolicy, RetryMode
  File "~/.pyenv/versions/3.7.9/lib/python3.7/site-packages/azure/core/pipeline/policies/_retry.py", line 47, in <module>
    from . import _utils
  File "~/.pyenv/versions/3.7.9/lib/python3.7/site-packages/azure/core/pipeline/policies/_utils.py", line 27, in <module>
    import email.utils
ModuleNotFoundError: No module named 'email.utils'; 'email' is not a package

**Expected behavior**
No error when import azure.communication.email package in Python code.

**Screenshots**

**Additional context**
I think there's a namespace collision between azure.communication.email and Python standard package email.utils.

**Comment by tjprescott** [comment]
Thank you for the report. @turalf  could you please take a look.

**Comment by lmazuel** [comment]
Hi @toantran-8451 

Your file is called `email.py`, which is discovered as a package by Python, and therefore is hiding the `email` package from the standard library:
https://docs.python.org/3/library/email.html?highlight=email#module-email

Rename your file and you will be good :)
