### ISSUE TITLE
CloudError: Azure Error: OperationNotAllowed Message: Operation 'Update VM' is not allowed on VM 'xxxxx' since the VM is marked for deletion

### ISSUE THREAD

**Issue by ajaytho** [Azure/azure-sdk-for-python#2702]
### Error 
====
``
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/createvms", line 349, in createinstance
    create_vm_result = create_linux_vm(network_client, compute_client, studentNum, spec, buildtype)
  File "/createvms", line 1167, in create_linux_vm
    vm_parameters
  File "/usr/local/lib/python2.7/dist-packages/azure/mgmt/compute/v2017_03_30/operations/virtual_machines_operations.py", line 232, in create_or_update
    get_long_running_status, long_running_operation_timeout)
  File "/usr/local/lib/python2.7/dist-packages/msrestazure/azure_operation.py", line 360, in __init__
    raise CloudError(self._response)
CloudError: Azure Error: OperationNotAllowed
Message: Operation 'Update VM' is not allowed on VM 'vmno-4' since the VM is marked for deletion. You can only retry the Delete operation (or wait for an ongoing one to complete).

Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/createvms", line 349, in createinstance
    create_vm_result = create_linux_vm(network_client, compute_client, studentNum, spec, buildtype)
  File "/createvms", line 1167, in create_linux_vm
    vm_parameters
  File "/usr/local/lib/python2.7/dist-packages/azure/mgmt/compute/v2017_03_30/operations/virtual_machines_operations.py", line 232, in create_or_update
    get_long_running_status, long_running_operation_timeout)
  File "/usr/local/lib/python2.7/dist-packages/msrestazure/azure_operation.py", line 360, in __init__
    raise CloudError(self._response)
CloudError: Azure Error: OperationNotAllowed
Message: Operation 'Update VM' is not allowed on VM 'vmno-5' since the VM is marked for deletion. You can only retry the Delete operation (or wait for an ongoing one to complete).

Traceback (most recent call last):
  File "/createvms", line 1328, in 
    getattr(sys.modules[__name__], args.command)()
  File "/createvms", line 226, in build
    ret = vmresultlist[j]
KeyError: 4
``
Please advice

**Comment by lmazuel** [comment]
Hi @ajaytho 
I don't see any reason, unless you execute your scripts really fast one behind another, and your script are deleting the VM. If so, the second call of the script will not be able to create the VM if the deletion of the first script is done yet. Since all of this is asynchronous, this might be possible. I can't tell for sure without seeing your script.
Thank you,

**Comment by lmazuel** [comment]
Closing for inactivity, feel free to still comment or create a new issue if necessary.
Thanks!
