### ISSUE TITLE
azure.cognitiveservices.search.newssearch SDK - what is the correct endpoint?

### ISSUE THREAD

**Issue by diberry** [Azure/azure-sdk-for-python#27309]
- **Package Name**:  azure.cognitiveservices.search.newssearch
- **Package Version**: 
- **Operating System**: windows
- **Python Version**:  3.9

**Describe the bug**

I _believe_ my issue the how to find and use the correct endpoint to use the SDK. 

* REST API works
    * Getting the search news via [REST with Python](https://github.com/diberry/azure-samples/blob/main/bing-news/py/search_via_rest.py)
    * Using the key found in the [.env file](https://github.com/diberry/azure-samples/blob/main/bing-news/py/.env.samples) 
    * And the key for the found on the Azure portal for the Bing Search resource on the Keys and Endpoints page.

    ```
    import os
    
    import requests
    from dotenv import load_dotenv
    
    load_dotenv()
    
    # Bing Search v7
    bing_news_search_url_default = "https://api.bing.microsoft.com/v7.0/news/search"
    
    subscription_key = os.environ.get("BING_SEARCH_KEY")
    endpoint = os.environ.get("BING_SEARCH_URL", bing_news_search_url_default)
    
    search_term = "Quantum Computing"
    
    print(f"Retrieving Bing News Search results for '{search_term}'.")
    
    try:
        # Submit GET request to Bing News Search endpoint with defined parameters and header with parameters.
        headers = {"Ocp-Apim-Subscription-Key": subscription_key}
        params = {
            "q": search_term,
            "count": 10,
            "textDecorations": True,
            "textFormat": "HTML",
        }
        response = requests.get(endpoint, headers=headers, params=params)
        response.raise_for_status()
    
        print(f"Successfully retrieved the Bing News Search results for '{search_term}'.")
    
        # Returns response JSON for GET request.
        result = response.json()
        print(result)
        print(result.keys())
    
    except Exception as e:
        print(e)
    ```

* SDK doesn't work - 
    * Same key, same endpoint, just using SDK 

    ```
    import os
    
    from azure.cognitiveservices.search.newssearch import NewsSearchClient
    from dotenv import load_dotenv
    from msrest.authentication import CognitiveServicesCredentials
    
    load_dotenv()
    
    # Bing Search v7 with SDK
    bing_news_search_url_default = "https://api.bing.microsoft.com/v7.0/news/search"
    subscription_key = os.environ.get("BING_SEARCH_KEY")
    endpoint = os.environ.get("BING_SEARCH_URL", bing_news_search_url_default)
    
    search_term = "Quantum Computing"
    
    client = NewsSearchClient(
        endpoint=endpoint, credentials=CognitiveServicesCredentials(subscription_key)
    )
    
    news_result = client.news.search(query=search_term, market="en-us", count=10)
    
    if news_result.value:
        first_news_result = news_result.value[0]
        print(
            "Total estimated matches value: {}".format(news_result.total_estimated_matches)
        )
        print("News result count: {}".format(len(news_result.value)))
        print("First news name: {}".format(first_news_result.name))
        print("First news url: {}".format(first_news_result.url))
        print("First news description: {}".format(first_news_result.description))
        print("First published time: {}".format(first_news_result.date_published))
        print("First news provider: {}".format(first_news_result.provider[0].name))
    else:
        print("Didn't see any news result data..")
    ```

**To Reproduce**

Use devcontainer in VSCode if you don't have Python 3.9. I doubt 3.9 is the issue though.

1. Create Bing search resource

    ![image](https://user-images.githubusercontent.com/41597107/200068356-dff56836-4825-4d0d-a0b6-0d91e8f6f082.png)

2.  `pip install -r requirements.txt`
3. `python search_via_rest.py` and console lists a dictionary
4. `python search_via_sdk.py` and console returns error of resource not found - I assume the endpoint URL is not correct

    ```
    $ python search_via_sdk.py
    Traceback (most recent call last):
      File "C:\repos\code\diberry\azure-samples\bing-news\py\search_via_sdk.py", line 20, in <module>
        news_result = client.news.search(query=search_term, market="en-us", count=10)
      File "C:\Python39\lib\site-packages\azure\cognitiveservices\search\newssearch\operations\_news_operations.py", line 379, in search
        raise models.ErrorResponseException(self._deserialize, response)
    azure.cognitiveservices.search.newssearch.models._models_py3.ErrorResponseException: Operation returned an invalid status code 'Resource Not Found'
    ```

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by lmazuel** [comment]
This package is no longer supported as an Azure product, and has been replaced by this repo:
https://github.com/microsoft/bing-search-sdk-for-python

My apologies that the Readm of this package doesn't have a clear deprecation notice, I'm taking a note to do them now.
