### ISSUE TITLE
[Service Bus] Session is not closeable

### ISSUE THREAD

**Issue by sefouber** [Azure/azure-sdk-for-python#27579]
**Describe the bug**
Setting a Service Bus session state to `None` causes an exception

***Exception or Stack Trace***
```
Traceback (most recent call last):
  File "C:/Users/test.py", line 74, in sample_session_send_receive_with_pool
    message_processing(client, queue_name, [])
  File "C:/Users/test.py", line 42, in message_processing
    receiver.session.set_state(None)
  File "C:\Users\venv\lib\site-packages\azure\servicebus\_servicebus_session.py", line 154, in set_state
    MGMT_REQUEST_SESSION_STATE: bytearray(state),
TypeError: cannot convert 'NoneType' object to bytearray
```

**To Reproduce**

 receiver.session.set_state(None)

***Code Snippet***
Add the code snippet that causes the issue.

```
with sb_client.get_queue_receiver(queue_name, max_wait_time=None,
                                              session_id=NEXT_AVAILABLE_SESSION) as receiver:
    renewer = AutoLockRenewer()
    renewer.register(receiver, receiver.session)
    receiver.session.set_state("OPEN")
    for message in receiver.receive_messages(max_message_count=1):
        print(message)
        receiver.complete_message(message)
    receiver.session.set_state(None)
```

**Expected behavior**

Being able to set the state to `None` based on the documentation [Session state remains as long as it isn't cleared up (returning null), even if all messages in a session are consumed.](https://learn.microsoft.com/en-us/azure/service-bus-messaging/message-sessions#message-session-state)

**Screenshots**

**Setup (please complete the following information):**
 - Python Version: Python 3.10
 - SDK Version: azure-servicebus 7.8.1

**Additional context**

Is there another way to close the session because the intended behavior is to close the session and then the receiver fetches another `NEXT_AVAILABLE_SESSION`

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X ] Setup information Added

**Comment by sefouber** [comment]
Submitted from right account
