### ISSUE TITLE
AADTokenCredentials raises TokenExpiredError at first, but then token is immediately refreshed

### ISSUE THREAD

**Issue by mjcaley** [Azure/azure-sdk-for-python#2779]
When using AADTokenCredentials and the token expires the client ends up raising a TokenExpiredError, but the token looks like it's refreshed.  After that, doing the same calls to the client is successful.  I wrote an example script to try to illustrate it:

```
from datetime import datetime, timedelta

from adal import AuthenticationContext
from msrestazure.azure_active_directory import AADTokenCredentials
from azure.mgmt.subscription import SubscriptionClient


def expire_token(token):
    expiry = (datetime.now() - timedelta(seconds=creds.token['expires_in'])).timestamp()
    token['expires_at'] = token['expires_on'] = expiry
    token['expires_in'] = 0

def create_auth():
    context = AuthenticationContext(authority='https://login.microsoftonline.com/canadagoose.onmicrosoft.com')
    code = context.acquire_user_code(resource='https://management.core.windows.net', client_id='04b07795-8ddb-461a-bbee-02f9e1bf7b46')
    print(code['message'])
    token = context.acquire_token_with_device_code('https://management.core.windows.net', user_code_info=code, client_id='04b07795-8ddb-461a-bbee-02f9e1bf7b46')
    creds = AADTokenCredentials(token=token, client_id='04b07795-8ddb-461a-bbee-02f9e1bf7b46')

    return creds

creds = create_auth()
sub_client = SubscriptionClient(creds)

for sub in sub_client.subscriptions.list():
    print(sub.display_name)

expire_token(creds.token)

# Raises msrest.exceptions.TokenExpiredError, but token is refreshed
print('Token expiry before', datetime.fromtimestamp(creds.token['expires_at']))
for sub in sub_client.subscriptions.list():
    print(sub.display_name)
print('Token expiry after', datetime.fromtimestamp(creds.token['expires_at']))

# Token was refreshed and now works
for sub in sub_client.subscriptions.list():
    print(sub.display_name)
```

Here's the traceback that I end up getting:

```
Token expired or is invalid. Attempting to refresh.
Traceback (most recent call last):
  File "C:\Users\mcaley\.virtualenvs\datadogmetrics-SCFaE2Ya\lib\site-packages\msrest\service_client.py", line 359, in send
    response = http_driver.send(request, **kwargs)
  File "C:\Users\mcaley\.virtualenvs\datadogmetrics-SCFaE2Ya\lib\site-packages\msrest\service_client.py", line 187, in send
    **kwargs)
  File "C:\Users\mcaley\.virtualenvs\datadogmetrics-SCFaE2Ya\lib\site-packages\requests\sessions.py", line 498, in request
    prep = self.prepare_request(req)
  File "C:\Users\mcaley\.virtualenvs\datadogmetrics-SCFaE2Ya\lib\site-packages\requests\sessions.py", line 441, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\mcaley\.virtualenvs\datadogmetrics-SCFaE2Ya\lib\site-packages\requests\models.py", line 313, in prepare
    self.prepare_auth(auth, url)
  File "C:\Users\mcaley\.virtualenvs\datadogmetrics-SCFaE2Ya\lib\site-packages\requests\models.py", line 544, in prepare_auth
    r = auth(self)
  File "C:\Users\mcaley\.virtualenvs\datadogmetrics-SCFaE2Ya\lib\site-packages\requests_oauthlib\oauth2_auth.py", line 35, in __call__
    http_method=r.method, body=r.body, headers=r.headers)
  File "C:\Users\mcaley\.virtualenvs\datadogmetrics-SCFaE2Ya\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 196, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) 
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\mcaley\.virtualenvs\datadogmetrics-SCFaE2Ya\lib\site-packages\msrest\paging.py", line 131, in __next__
    self.advance_page()
  File "C:\Users\mcaley\.virtualenvs\datadogmetrics-SCFaE2Ya\lib\site-packages\msrest\paging.py", line 117, in advance_page
    self._response = self._get_next(self.next_link)
  File "C:\Users\mcaley\.virtualenvs\datadogmetrics-SCFaE2Ya\lib\site-packages\azure\mgmt\subscription\operations\subscriptions_operations.py", line 208, in internal_paging
    request, header_parameters, **operation_config)
  File "C:\Users\mcaley\.virtualenvs\datadogmetrics-SCFaE2Ya\lib\site-packages\msrest\service_client.py", line 364, in send
    raise_with_traceback(TokenExpiredError, msg, err)
  File "C:\Users\mcaley\.virtualenvs\datadogmetrics-SCFaE2Ya\lib\site-packages\msrest\exceptions.py", line 54, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "C:\Users\mcaley\.virtualenvs\datadogmetrics-SCFaE2Ya\lib\site-packages\msrest\service_client.py", line 359, in send
    response = http_driver.send(request, **kwargs)
  File "C:\Users\mcaley\.virtualenvs\datadogmetrics-SCFaE2Ya\lib\site-packages\msrest\service_client.py", line 187, in send
    **kwargs)
  File "C:\Users\mcaley\.virtualenvs\datadogmetrics-SCFaE2Ya\lib\site-packages\requests\sessions.py", line 498, in request
    prep = self.prepare_request(req)
  File "C:\Users\mcaley\.virtualenvs\datadogmetrics-SCFaE2Ya\lib\site-packages\requests\sessions.py", line 441, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\mcaley\.virtualenvs\datadogmetrics-SCFaE2Ya\lib\site-packages\requests\models.py", line 313, in prepare
    self.prepare_auth(auth, url)
  File "C:\Users\mcaley\.virtualenvs\datadogmetrics-SCFaE2Ya\lib\site-packages\requests\models.py", line 544, in prepare_auth
    r = auth(self)
  File "C:\Users\mcaley\.virtualenvs\datadogmetrics-SCFaE2Ya\lib\site-packages\requests_oauthlib\oauth2_auth.py", line 35, in __call__
    http_method=r.method, body=r.body, headers=r.headers)
  File "C:\Users\mcaley\.virtualenvs\datadogmetrics-SCFaE2Ya\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 196, in add_token
    raise TokenExpiredError()
msrest.exceptions.TokenExpiredError: Token expired or is invalid., TokenExpiredError: (token_expired)
```

I've tried it with both the azure.mgmt.SubscriptionClient and azure.mgmt.ServiceBusManagementClient with the same results.

Should the client be refreshing the token or is that my responsibility?

**Comment by mjcaley** [comment]
Closing, fixed in https://github.com/Azure/msrestazure-for-python/pull/103
