### ISSUE TITLE
Fail to authenticate

### ISSUE THREAD

**Issue by kaoutaar** [Azure/azure-sdk-for-python#27860]
i am trying to submit a ml pipeline from mlstudio using the python sdk, but i get this error

`MSI: Failed to retrieve a token from 'identity-responder-not-enabled/?resource=https://management.core.windows.net/&api-version=2017-09-01' with an error of 'No connection adapters were found for 'identity-responder-not-enabled/?resource=https://management.core.windows.net/&api-version=2017-09-01''.
Performing interactive authentication. Please follow the instructions on the terminal.
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code R7KKRDSEF to authenticate.
Cleaning up all outstanding Run operations, waiting 300.0 seconds
0 items cleaning up...
Cleanup took 1.9073486328125e-06 seconds
Traceback (most recent call last):
  File "prepdata.py", line 9, in <module>
    ws = Workspace.from_config()
  File "/azureml-envs/azureml_74b1397863eab2fcab5584fd174ce6eb/lib/python3.8/site-packages/azureml/core/workspace.py", line 292, in from_config
    return Workspace.get(
  File "/azureml-envs/azureml_74b1397863eab2fcab5584fd174ce6eb/lib/python3.8/site-packages/azureml/core/workspace.py", line 605, in get
    auth = InteractiveLoginAuthentication()
  File "/azureml-envs/azureml_74b1397863eab2fcab5584fd174ce6eb/lib/python3.8/site-packages/azureml/core/authentication.py", line 571, in __init__
    perform_interactive_login(tenant=tenant_id, cloud_type=self._cloud_type)
  File "/azureml-envs/azureml_74b1397863eab2fcab5584fd174ce6eb/lib/python3.8/site-packages/azureml/_base_sdk_common/common.py", line 573, in perform_interactive_login
    subscriptions = profile.login(
  File "/azureml-envs/azureml_74b1397863eab2fcab5584fd174ce6eb/lib/python3.8/site-packages/azureml/_vendor/azure_cli_core/_profile.py", line 153, in login
    user_identity = identity.login_with_device_code(scopes=scopes, **kwargs)
  File "/azureml-envs/azureml_74b1397863eab2fcab5584fd174ce6eb/lib/python3.8/site-packages/azureml/_vendor/azure_cli_core/auth/identity.py", line 133, in login_with_device_code
    return check_result(result)
  File "/azureml-envs/azureml_74b1397863eab2fcab5584fd174ce6eb/lib/python3.8/site-packages/azureml/_vendor/azure_cli_core/auth/util.py", line 125, in check_result
    aad_error_handler(result, **kwargs)
  File "/azureml-envs/azureml_74b1397863eab2fcab5584fd174ce6eb/lib/python3.8/site-packages/azureml/_vendor/azure_cli_core/auth/util.py", line 30, in aad_error_handler
    raise AuthenticationError(msg, recommendation=login_message)
azureml._vendor.azure_cli_core.azclierror.AuthenticationError: AuthenticationError:
	Message: AADSTS70016: OAuth 2.0 device flow error. Authorization is pending. Continue polling.
Trace ID: ac1a1ea7-7463-4143-b16a-67a3705a1301
Correlation ID: 62d40fa0-0dc4-477b-804f-8a120ccb314e
Timestamp: 2022-12-08 14:14:25Z
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "AADSTS70016: OAuth 2.0 device flow error. Authorization is pending. Continue polling.\r\nTrace ID: ac1a1ea7-7463-4143-b16a-67a3705a1301\r\nCorrelation ID: 62d40fa0-0dc4-477b-804f-8a120ccb314e\r\nTimestamp: 2022-12-08 14:14:25Z"
    }
}`

**Comment by kashifkhan** [comment]
Thanks for the feedback @kaoutaar . We will investigate asap

cc @azureml-github

**Comment by dingoyal** [comment]
Is there any update on this issue? I am also facing same issue while submitting job through Azure-ml.
  raise AuthenticationError(msg, recommendation=login_message)
azureml._vendor.azure_cli_core.azclierror.AuthenticationError: AuthenticationError:
	Message: AADSTS70016: OAuth 2.0 device flow error. Authorization is pending. Continue polling.
	
Thanks in advance.

**Comment by tianyic** [comment]
Hi I am facing the same issue. 

Any update?

**Comment by achauhan-scc** [comment]
closing as obsolete
