### ISSUE TITLE
'Access Denied' - when accessing the custom vision - microsoft azure

### ISSUE THREAD

**Issue by abhishekkumar123090** [Azure/azure-sdk-for-python#2800]
Hello all,

I got the following error while creating a custom model using the python (given on https://docs.microsoft.com/en-us/azure/cognitive-services/Custom-Vision-Service/python-tutorial) and is getting the below error. So why is the access denied? Is it because of the API-key or something else?

Traceback (most recent call last):
File "train_cm.py", line 12, in 
project = trainer.create_project("PneumoniaNormal")
File "C:\Users\Asus\AppData\Local\Programs\Python\Python36\lib\site-packages\azure\cognitiveservices\vision\customvision\training\training_api.py", line 1537, in create_project
raise HttpOperationError(self._deserialize, response)
msrest.exceptions.HttpOperationError: Operation returned an invalid status code 'Access Denied'

**Comment by lmazuel** [comment]
@areddish to the rescue please :)

**Comment by areddish** [comment]
Hello @abhishekkumar123090,

There are two was to get this type of error:
1) You could be missing the API key - make sure to get your training key off the portal settings page from customvision.ai and putting that value into training_key.
2) You could be hitting the limit to the number of projects you are able to create. To check this, log into the customvision.ai portal and click on the setting (gear icon) on the upper right. Then you'll see the number of projects you have created vs the number you are able to create.

**Comment by lmazuel** [comment]
Closing for inactivity, and since I believe the answer is accurate. Feel free to still comment or create new issue if necessary.
