### ISSUE TITLE
Azure Storage Management cannot parse post request data for StorageManagementClient

### ISSUE THREAD

**Issue by mawarren642** [Azure/azure-sdk-for-python#28028]
- **Package Name**: azure-mgmt-storage
- **Package Version**: 21.0.0
- **Operating System**: Azure Functions 4 Linux
- **Python Version**: 3.8.6

**Describe the bug**
StorageManagementClient fails on initialization when created with a service principal's DefaultAzureCredential, ClientSecretCredential, or ManagedIdentityCredential. The Credentials used only produce this error with the storage management object.

**To Reproduce**
1. Imports:
  - os
  - logging
  - azure.identity
  - azure.functions
  - from azure.mgmt.storage import StorageManagementClient
  - from azure.mgmt.resource import ResourceManagementClient
  - from azure.mgmt.storage.models import (
      - StorageAccountCreateParameters,
      - StorageAccountUpdateParameters,
      - Sku,
      - SkuName,
      - Kind
  )
2. Create credential from azure.identity (use DefaultAzureCredential with client ID for App Service Principal or otherwise)
```
credential = ClientSecretCredential(tenant_id=os.environ['AZURE_TENANT_ID'], client_id=os.environ['AZURE_CLIENT_ID'], client_secret=os.environ['AZURE_CLIENT_SECRET'])
```
or 
```
credential = DefaultAzureCredential(os.environ['AZURE_CLIENT_ID'])
```
3. establish sub id: `subscription_id = os.environ['AZURE_SUBSCRIPTION_ID']`
4. Create StorageManagementClient
```
storage_client = StorageManagementClient(credential=credential, subscription_id=subscription_id)
        storage_keys = storage_client.storage_accounts.regenerate_key(
            resource_group_name="contoso-rg",
            account_name="contosotestsa",
            regenerate_key='key1'
        )
        storage_keys = {v.key_name: v.value for v in storage_keys.keys}
        print('\tNew key 1: {}'.format(storage_keys['key1']))
```

**Expected behavior**
This should generate new storage keys and return their values.

**Screenshots**
```python
For detailed output, run func with --verbose flag.
[2022-12-21T20:21:55.080Z] Worker process started and initialized.
[2022-12-21T20:21:58.908Z] Host lock lease acquired by instance ID '000000000000000000000000CB70CC1F'.
[2022-12-21T20:22:13.180Z] Executing 'Functions.TestFunction' (Reason='This function was programmatically called via the host APIs.', Id=6371bc08-13ac-4604-aaba-0894fed621af)
[2022-12-21T20:22:13.230Z] Python HTTP trigger function processed a request.
[2022-12-21T20:22:13.232Z] **{'_authority': 'https://login.microsoftonline.com', '_regional_authority': None, '_tenant_id': '72f988bf-86f1-41af-91ab-2d7cd011db47', '_client': <azure.identity._internal.msal_client.MsalClient object at 0x000001797BADE8E0>, '_client_applications': {}, '_client_credential': '***', '_client_id': '46620c29-9e6e-4bcd-b210-a8470974c74f', '_additionally_allowed_tenants': [], '_cache': <msal.token_cache.TokenCache object at 0x000001797BADE910>, '_last_request_time': 0}**  
[2022-12-21T20:22:13.257Z] ### Failed to regenerate key: **(', DeserializationError: (", AttributeError: \'str\' object has no attribute \'get\'", \'Unable to deserialize to object: type\', AttributeError("\'str\' object has no attribute \'get\'"))', 'Unable to build a model: (", AttributeError: \'str\' object has no attribute \'get\'", \'Unable to deserialize to object: type\', AttributeError("\'str\' object has no attribute \'get\'"))', DeserializationError(", AttributeError: 'str' object has no attribute 'get'", 'Unable to deserialize to object: type', AttributeError("'str' object has no attribute 'get'")))**
Traceback (most recent call last):
  File "C:\repos\contosov1-3\.venv\azure_functions\lib\site-packages\azure\mgmt\storage\_serialization.py", line 1452, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "C:\repos\contosov1-3\.venv\azure_functions\lib\site-packages\azure\mgmt\storage\_serialization.py", line 1217, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "C:\repos\contosov1-3\.venv\azure_functions\lib\site-packages\azure\mgmt\storage\_serialization.py", line 1246, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\repos\contosov1-3\.venv\azure_functions\lib\site-packages\azure\mgmt\storage\_serialization.py", line 680, in body
    data = deserializer._deserialize(data_type, data)
  File "C:\repos\contosov1-3\.venv\azure_functions\lib\site-packages\azure\mgmt\storage\_serialization.py", line 1470, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "C:\repos\contosov1-3\.venv\azure_functions\lib\site-packages\azure\core\exceptions.py", line 78, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "C:\repos\contosov1-3\.venv\azure_functions\lib\site-packages\azure\mgmt\storage\_serialization.py", line 1452, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "C:\repos\contosov1-3\.venv\azure_functions\lib\site-packages\azure\mgmt\storage\_serialization.py", line 1217, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "C:\repos\contosov1-3\.venv\azure_functions\lib\site-packages\azure\mgmt\storage\_serialization.py", line 1246, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
  File "C:\repos\contosov1-3\.venv\azure_functions\lib\site-packages\azure\core\exceptions.py", line 78, in raise_with_traceback    raise error.with_traceback(exc_traceback)
  File "C:\repos\contosov1-3\.venv\azure_functions\lib\site-packages\azure\mgmt\storage\_serialization.py", line 1452, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "C:\repos\contosov1-3\.venv\azure_functions\lib\site-packages\azure\mgmt\storage\_serialization.py", line 1217, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "C:\repos\contosov1-3\.venv\azure_functions\lib\site-packages\azure\mgmt\storage\_serialization.py", line 1246, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
azure.core.exceptions.SerializationError: **(', DeserializationError: (", AttributeError: \'str\' object has no attribute \'get\'", \'Unable to deserialize to object: type\', AttributeError("\'str\' object has no attribute \'get\'"))', 'Unable to build a model: (", AttributeError: \'str\' object has no attribute \'get\'", \'Unable to deserialize to object: type\', AttributeError("\'str\' object has no attribute \'get\'"))', DeserializationError(", AttributeError: 'str' object has no attribute 'get'", 'Unable to deserialize to object: type', AttributeError("'str' object has no attribute 'get'")))**
[2022-12-21T20:22:13.308Z] Executed 'Functions.TestFunction' (Succeeded, Id=6371bc08-13ac-4604-aaba-0894fed621af, Duration=144ms)
```

**Additional context**
Related to #28017 
To be clear, this fails when run from command line / ipython, when run in the function app locally in debugging, and when run from the production function app. I'm creating credentials following the [most recent azure-identity documentation](https://learn.microsoft.com/en-us/python/api/overview/azure/identity-readme?view=azure-python#authenticate-with-defaultazurecredential) using the following strategies:
- DefaultAzureCredential
  - called without args in function app host with system assigned identity enabled
  - called with args specifying AZURE_CLIENT_ID using:
    - Object ID provided for function app system assigned identity
    - Application ID from App registration enabled as service principal
    - With and without tenant specified
    - With keyword args
- ClientSecretSharedCredential
  - specifying tenant, client ID (application ID), and client secret of app registration enabled as service principal

Both service principals have been given specific access as Storage Key Operators and Subscription level Owners

**Comment by navba-MSFT** [comment]
@mawarren642  Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Could you please try the below sample and check if that helps ?

```
# Import the required libraries
import azure.common
import azure.mgmt.storage

# Set the subscription ID and resource group for the storage account
subscription_id = 'your-subscription-id'
resource_group = 'your-resource-group'

# Set the name of the storage account
storage_account_name = 'your-storage-account'

# Create a client for interacting with the storage management API
client = azure.mgmt.storage.StorageManagementClient(
    azure.common.credentials.ServicePrincipalCredentials(
        client_id='your-client-id',
        secret='your-client-secret',
        tenant='your-tenant-id'
    ),
    subscription_id
)

# Get the storage account
storage_account = client.storage_accounts.get_properties(
    resource_group,
    storage_account_name
)

# Regenerate the storage access key
key = client.storage_accounts.regenerate_key(
    resource_group,
    storage_account_name,
    'key1'
)

# Print the regenerated storage access key
print(key.value)

```

This code uses the Azure Storage Management API to regenerate the first storage access key (key1) for the specified storage account. The regenerated key is printed to the console.

You will need to replace 'your-subscription-id', 'your-resource-group', 'your-storage-account', 'your-client-id', 'your-client-secret', and 'your-tenant-id' with the appropriate values for your environment.

**Comment by mawarren642** [comment]
This fails the same way. I am certain my credentials are correct (I can get an incorrect client secret message when I provide the wrong information to the ServicePrincipalCredentials constructor), but when using them to instantiate a StorageManagementClient I get the same error as before. Here is my exact script so you can reproduce:

```python
import os
import azure.common.credentials
import azure.mgmt.storage

credential = azure.common.credentials.ServicePrincipalCredentials(
    client_id=os.environ['AZURE_CLIENT_ID'],
    secret=os.environ['AZURE_CLIENT_SECRET'],
    tenant=os.environ['AZURE_TENANT_ID']
)
subscription_id = os.environ['AZURE_SUBSCRIPTION_ID']
storage_client = azure.mgmt.storage.StorageManagementClient(credential, subscription_id)
storage_keys = storage_client.storage_accounts.regenerate_key(
    "contoso-rg",
    "contosotestsa",
    "key1"
)
```

The error output reads something like this:
Traceback (most recent call last):
```
  File "C:\repos\contosov1-3\.venv\azure_functions\lib\site-packages\azure\mgmt\storage\_serialization.py", line 680, in body
    data = deserializer._deserialize(data_type, data)
  File "C:\repos\contosov1-3\.venv\azure_functions\lib\site-packages\azure\mgmt\storage\_serialization.py", line 1470, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "C:\repos\contosov1-3\.venv\azure_functions\lib\site-packages\azure\core\exceptions.py", line 78, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "C:\repos\contosov1-3\.venv\azure_functions\lib\site-packages\azure\mgmt\storage\_serialization.py", line 1452, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "C:\repos\contosov1-3\.venv\azure_functions\lib\site-packages\azure\mgmt\storage\_serialization.py", line 1217, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "C:\repos\contosov1-3\.venv\azure_functions\lib\site-packages\azure\mgmt\storage\_serialization.py", line 1246, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
azure.core.exceptions.DeserializationError: (", AttributeError: 'str' object has no attribute 'get'", 'Unable to deserialize to object: type', AttributeError("'str' object has no attribute 'get'"))
```

**Comment by msyyc** [comment]
Hi @mawarren642 
(1) azure-common is abandoned by azure-mgmt-storage>=16.0.0 and your authentication is right, so the problem is not in authentication
(2) `regenerate_key` is model not str:
https://github.com/Azure/azure-sdk-for-python/blob/c45589ebb4e26d5d2fdd9be3961656dacc5aa927/sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2022_09_01/operations/_storage_accounts_operations.py#L1549
you can try:
```
        storage_keys = storage_client.storage_accounts.regenerate_key(
            resource_group_name="contoso-rg",
            account_name="contosotestsa",
            regenerate_key=StorageAccountRegenerateKeyParameters(key_name="key1")
        )
```

**Comment by mawarren642** [comment]
@msyyc your example works, however I had to use EXACTLY the syntax you provided:
```
storage_keys = storage_client.storage_accounts.regenerate_key(
      resource_group_name="repodespot-rg",
      account_name="repodespotstaging",
      regenerate_key=StorageAccountRegenerateKeyParameters(key_name="key1")
    )
```

I see that recent release notes specify using key word arguments instead of positional parameters, and so that makes sense, but I want to point out that the first example that comes up in bing is this documentation:
https://learn.microsoft.com/en-us/samples/azure-samples/storage-python-manage/storage-python-manage/#regenerate-keys

If you navigate to the more current documentation, there are no samples available and very frustrating to navigate references to the ever changing models:
https://learn.microsoft.com/en-us/python/api/azure-mgmt-storage/azure.mgmt.storage.storagemanagementclient?view=azure-python

And the way these examples are written in the second link would actually suggest at first glance that you would call something like
`storage_client.regenerate_keys(...)` instead of `storage_client.storage_accounts.regenerate_keys(...)`

I see that you added this recently:
https://github.com/Azure-Samples/azure-samples-python-management/blob/main/samples/storage/manage_regenerate_key.py

And that is a huge win. Can you please try to ensure that the Learn.Microsoft documentation also highlights that example and help clean up the pages so that this page, which is essential:

https://learn.microsoft.com/en-us/python/api/azure-mgmt-storage/azure.mgmt.storage.storagemanagementclient?view=azure-python

Reads more like the style of this page:
https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob?view=azure-python

Thank you for all of your help.

**Comment by navba-MSFT** [comment]
@mawarren642 Thanks for the feedback. I have shared the feedback with the right stakeholders and we might remove this old repo entirely: https://learn.microsoft.com/en-us/samples/azure-samples/storage-python-manage/storage-python-manage/#regenerate-keys. 

The management samples has been moved [here ](https://github.com/azure-samples/azure-samples-python-management/tree/main/samples/storage) and the learn search is also pointing to it now.

![image](https://user-images.githubusercontent.com/57353862/210036553-69e877ce-82ee-419c-8560-90f8eaf93ab2.png)

The above PR has also been filed to add the Storage sample's repo link for reference.

**Comment by navba-MSFT** [comment]
@mawarren642 The samples storagemgmt repo link is specified in [this](https://pypi.org/project/azure-mgmt-storage/) and [this ](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-mgmt-storage/README.md).
