### ISSUE TITLE
Empty address field results in AttributeError when calling `AnalyzeResult.to_dict()`

### ISSUE THREAD

**Issue by WillemDeGroef** [Azure/azure-sdk-for-python#28282]
See line: https://github.com/Azure/azure-sdk-for-python/blob/a17fed25c68ed7d4cd588e7bcb597c83f1d3df8b/sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py#L2408

Traceback (most recent call last):
File "/XXX/site-packages/azure/ai/formrecognizer/_models.py", line 3599, in to_dict
    "documents": [f.to_dict() for f in self.documents]
File "/XXX//site-packages/azure/ai/formrecognizer/_models.py", line 3599, in <listcomp>
    "documents": [f.to_dict() for f in self.documents]
File "/XXX//site-packages/azure/ai/formrecognizer/_models.py", line 2297, in to_dict
    "fields": {k: v.to_dict() for k, v in self.fields.items()}
File "/XXX//site-packages/azure/ai/formrecognizer/_models.py", line 2297, in <dictcomp>
    "fields": {k: v.to_dict() for k, v in self.fields.items()}
File "/XXX//site-packages/azure/ai/formrecognizer/_models.py", line 2408, in to_dict
    value = self.value.to_dict()
AttributeError: 'NoneType' object has no attribute 'to_dict'

Fix:
```
value = self.value.to_dict() if self.value else {}
```

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by catalinaperalta** [comment]
@WillemDeGroef thanks for reporting this issue! I've merged a fix for it. Feel free to report any other issues you may find :)
