### ISSUE TITLE
The range specified is invalid for the current size of the resource file when file is not empty

### ISSUE THREAD

**Issue by centraal-g** [Azure/azure-sdk-for-python#28312]
- **Package Name**:  azure-storage-blob
- **Package Version**:  12.6.0
- **Operating System**:  Linux
- **Python Version**:  python 3.8

**Describe the bug**
When I tried to read a new blob that was recently updated the client answer with the error  the following error:

```
azure.core.exceptions.HttpResponseError: The range specified is invalid for the current size of the resource.
RequestId:b96a680e-b01e-00c7-7995-2610e0000000
Time:2023-01-12T14:53:36.8661161Z
ErrorCode:InvalidRange
Error:None
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidRange</Code><Message>The range specified is invalid for the current size of the resource.
RequestId:b96a680e-b01e-00c7-7995-2610e0000000
Time:2023-01-12T14:53:36.8661161Z</Message></Error>
```

**To Reproduce**
1. First I was not able to reproduce in a consistent way, but I notice the following
2. The blob that will be read needs to be written in less than 1 minute.
3.  The Write operation needs to be performed in a different client (or python session) than the read operation
4. In so many cases the above conditions are met, but the error is not triggered, but when is triggered the following stack is generated:
```
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/tracing/decorator_async.py", line 79, in wrapper_use_tracer
    return await func(*args, **kwargs)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/aio/_container_client_async.py", line 872, in download_blob
    return await blob_client.download_blob(
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/tracing/decorator_async.py", line 79, in wrapper_use_tracer
    return await func(*args, **kwargs)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/aio/_blob_client_async.py", line 361, in download_blob
    await downloader._setup()  # pylint: disable=protected-access
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/aio/_download_async.py", line 225, in _setup
    self._response = await self._initial_request()
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/aio/_download_async.py", line 306, in _initial_request
    process_storage_error(error)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/_shared/response_handlers.py", line 147, in process_storage_error
    raise error
azure.core.exceptions.HttpResponseError: The range specified is invalid for the current size of the resource.
RequestId:b96a680e-b01e-00c7-7995-2610e0000000
Time:2023-01-12T14:53:36.8661161Z
ErrorCode:InvalidRange
Error:None
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidRange</Code><Message>The range specified is invalid for the current size of the resource.
RequestId:b96a680e-b01e-00c7-7995-2610e0000000
Time:2023-01-12T14:53:36.8661161Z</Message></Error>
```

**Expected behavior**
The Blob needs to be downloaded without error

**Screenshots**
N/A

**Additional context**
I'm using the [adlfs](https://github.com/fsspec/adlfs), but in my understanding, the error is a consequence of some odd behavior on the  `azure-storage-blob` library. In the older library repository I found [this issue](https://github.com/Azure/azure-storage-python/issues/586), which suggested that the exception can be ignored, so not sure if the proper solution is to deal with the exception on `adlfs` library.

**Comment by navba-MSFT** [comment]
@jalauzon-msft @vincenttran-msft Could you please look into this once you get a chance ?

**Comment by jalauzon-msft** [comment]
Hi @centraal-g, thanks for reaching out. Just to be clear, you are seeing this error when attempting to download a **non-empty** blob? And this error is actually failing the request, not just being logged?

An error like this usually occurs when you attempt to download an empty blob using a ranged download. The `azure-storage-blob` SDK always tries to do a ranged download first but looks for this specific error and will retry the request without a range specified if the blob is empty. You can see that [here](https://github.com/Azure/azure-sdk-for-python/blob/bcc3364dd884e8e6e365cbfe682672f605b6eb60/sdk/storage/azure-storage-blob/azure/storage/blob/aio/_download_async.py#L370). In this case the error is expected and can be ignored as the request will finish correctly.

However, taking a closer look at the backend logs for the request your provided, the requested range on the download was not our typical range (0 - 32 MiB) but rather was 39720 - 39275. In that case, the other option is that the blob range is just not valid for the blob and is possibly over the end of the blob. Are you specifying a specific `offset` and `range` in your download request? Can you share the code used for downloading?

Like I said, there is a chance you are somehow requesting data that is over the end of the blob which would result in this error. If this is unexpected, my suspicion, based on your repro steps, is that there is some form of race condition between your write and your read, since you mentioned they are seperate processes. It is possible your download is running before your write is finished.,

**Comment by centraal-g** [comment]
@jalauzon-msft Thanks for taking the time to check this.

1. Yes,  the error is logged and the download fails
2. I understand your commentary about the not typical value range, however, I did not configure that range specifically. For example, a workaround that we have is to restart the python kernel, and after that, the process finishes without errors.
3. I'm using another third library to make the download request,  (We are using `pandas` with [`adlfs`](https://github.com/fsspec/adlfs) , btw I edited my issue I realized that I referenced the wrong library:
```
read_csv df = pd.read_csv('az://{path/to/file.csv, storage_options={'account_name': datalake_name, 'account_key': account_key})

```

taking a closer look, the part of the code that downloads the file in the  `adlfs`, [is in this piece of code](https://github.com/fsspec/adlfs/blob/2022.11.2/adlfs/spec.py#L1914), where I can see the library is expecting a range, but I do not have control on how that range is computed, so not sure if something related with `adlfs`.


Here is my complete traceback

```
Traceback (most recent call last): File "/home/site/wwwroot/.python_packages/lib/site-packages/azure_datalake_utils/azure_datalake_utils.py",
line 91, in read_csv df = pd.read_csv(f"az://{path}", storage_options=self.storage_options, **kwargs) 
File "/home/site/wwwroot/.python_packages/lib/site-packages/pandas/util/_decorators.py", line 311, in wrapper return func(*args, **kwargs) 
File "/home/site/wwwroot/.python_packages/lib/site-packages/pandas/io/parsers/readers.py", line 678, in read_csv return _read(filepath_or_buffer, kwds) File "/home/site/wwwroot/.python_packages/lib/site-packages/pandas/io/parsers/readers.py", line 581, in _read return parser.read(nrows) File "/home/site/wwwroot/.python_packages/lib/site-packages/pandas/io/parsers/readers.py", line 1253, in read index, columns, col_dict = self._engine.read(nrows) File "/home/site/wwwroot/.python_packages/lib/site-packages/pandas/io/parsers/python_parser.py", line 238, in read content = self._get_lines(rows) File "/home/site/wwwroot/.python_packages/lib/site-packages/pandas/io/parsers/python_parser.py", line 1091, in _get_lines new_row = self._next_iter_line(row_num=self.pos + rows + 1) File "/home/site/wwwroot/.python_packages/lib/site-packages/pandas/io/parsers/python_parser.py", line 760, in _next_iter_line line = next(self.data) File "/home/site/wwwroot/.python_packages/lib/site-packages/fsspec/spec.py", line 1533, in read out = self.cache._fetch(self.loc, self.loc + length) File "/home/site/wwwroot/.python_packages/lib/site-packages/fsspec/caching.py", line 153, in _fetch self.cache = self.fetcher(start, end) # new block replaces old File "/home/site/wwwroot/.python_packages/lib/site-packages/fsspec/asyn.py", line 91, in wrapper return sync(self.loop, func, *args, **kwargs) File "/home/site/wwwroot/.python_packages/lib/site-packages/fsspec/asyn.py", line 71, in sync raise return_result File "/home/site/wwwroot/.python_packages/lib/site-packages/fsspec/asyn.py", line 25, in _runner result[0] = await coro File "/home/site/wwwroot/.python_packages/lib/site-packages/adlfs/spec.py", line 1914, in _async_fetch_range stream = await self.container_client.download_blob( File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/tracing/decorator_async.py", line 79, in wrapper_use_tracer return await func(*args, **kwargs) File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/aio/_container_client_async.py", line 872, in download_blob return await blob_client.download_blob( File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/tracing/decorator_async.py", line 79, in wrapper_use_tracer return await func(*args, **kwargs) File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/aio/_blob_client_async.py", line 361, in download_blob await downloader._setup() # pylint: disable=protected-access File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/aio/_download_async.py", line 225, in _setup self._response = await self._initial_request() File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/aio/_download_async.py", line 306, in _initial_request process_storage_error(error) File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/_shared/response_handlers.py", line 147, in process_storage_error raise error azure.core.exceptions.HttpResponseError: The range specified is invalid for the current size of the resource. RequestId:cbb1291a-801e-00cf-4810-2c0b93000000 Time:2023-01-19T14:12:43.0383978Z ErrorCode:InvalidRange Error:None Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidRange</Code><Message>The range specified is invalid for the current size of the resource. RequestId:cbb1291a-801e-00cf-4810-2c0b93000000 Time:2023-01-19T14:12:43.0383978Z</Message></Error>
```

5.  Yes I was expecting the two processes to compete, but we have ensured that the writing process completes finishes before trying to read the blob. After some changes in our process to ensure that, We have seen less frequent the error, however now and then the error is raised again.

**Comment by jalauzon-msft** [comment]
Hi @centraal-g, thanks for the additional info. I don't think this would be caused by an issue in the `azure-storage-blob` SDK. In this case the SDK seems to be correctly performing download with the specific `offset` and `length` that `adlfs` is sending and that range is just not valid for the blob. It seems that somewhere along the line, `adlfs`, for whatever reason, may think the blob is bigger than it actually is. When you restart the process, `adlfs` somehow is able to get the correct size and download the blob correctly. To be honest, this does still seem like it could be an issue with the timing of the upload and the download process, but it also could be something internal to the `adlfs` library (I'm not very familiar with it).

Are you using `azure-storage-blob` directly to perform the upload? We could take a look at that to make sure you are performing the upload as we would expect.

The one other thing I could try from my side is we could try and correlate an error with the exact size of the blob and see if the invalid range is actually invalid for the final blob size or the only happening because not all the blob has been uploaded. That may help to narrow down the cause. We could do that if you were able to provide me a recent error "RequestId" as well as going into your Storage account and looking at the exact size of the blob and sharing. You don't need to publicly share the blob name but just the size of the blob that you were trying to download. Then I can look things up in the backend for you and see.

**Comment by centraal-g** [comment]
@jalauzon-msft thanks for the feedback. No, I'm not using `azure-storage-blob`, in a similar way We used `adlfs` and `pandas` to write the file.

Yes, the backend I think is very useful, here is a requestID that failed today: `RequestId:9991bd03-501e-0067-14d5-2cdf86000000 Time:2023-01-20T13:47:57.4951360Z ErrorCode:InvalidRange`

and here the size of the blob `3627478`

![image](https://user-images.githubusercontent.com/57504681/213718009-ae134206-50b4-4c1b-9ad4-8945a96aba9f.png)

thanks!

**Comment by jalauzon-msft** [comment]
Hi again @centraal-g, looking at the backend logs for that failed request, we do see the same InvalidRange error where the request was past the end of the blob and the range requested is actually greater than the final blob size that you shared. The range requested was `bytes=3627478-3627485` which weirdly starts at the end of the blob and only requests an additional 7 bytes.

Possibly there is some corner case somewhere where the blob size is being checked and it's an "off by one" comparison. Or it is using a `>` when it should be using a `>=`. Ultimately though, I don't think this is an issue in the SDK but rather some other dependency.

**Comment by centraal-g** [comment]
@jalauzon-msft thanks again for the feedback, We will check your suggestions to find a better to handle it. And I agree,  all this point out that the root cause of the error is not `azure-storage-blob`.
