### ISSUE TITLE
Could not using this SDK in China

### ISSUE THREAD

**Issue by jiasir** [Azure/azure-sdk-for-python#284]
I am using the China version Microsoft Azure. the website is https://manage.windowsazure.cn, This is my test code(I had set the environment: `AZURE_STORAGE_ACCOUNT` and `AZURE_STORAGE_ACCESS_KEY`):
```
from azure.storage import TableService

ts = TableService()

ts.create_table('spimage')
```
When I execute my script, the error is:
``
Traceback (most recent call last):
  File "storage.py", line 7, in <module>
    ts.create_table('testtable')
  File "/Library/Python/2.7/site-packages/azure/storage/tableservice.py", line 174, in create_table
    self._perform_request(request)
  File "/Library/Python/2.7/site-packages/azure/storage/storageclient.py", line 143, in _perform_request
    resp = self._filter(request)
  File "/Library/Python/2.7/site-packages/azure/storage/tableservice.py", line 491, in _perform_request_worker
    return self._httpclient.perform_request(request)
  File "/Library/Python/2.7/site-packages/azure/http/httpclient.py", line 205, in perform_request
    self.send_request_headers(connection, request.headers)
  File "/Library/Python/2.7/site-packages/azure/http/httpclient.py", line 184, in send_request_headers
    connection.endheaders()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1172, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 60] Operation timed out
``
So, the SDK whether can support the Chinese version?

**Comment by huguesv** [comment]
You'll need to specify a value for the host_base parameter:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure/storage/tableservice.py#L55

It defaults to:
'.table.core.windows.net'

I'm not sure what you need to use, it might be:
'.table.core.windows.cn'

ts = TableService(host_base='.table.core.windows.cn')

**Comment by jiasir** [comment]
@huguesv It might not be `.table.core.windows.cn`
This is my test code:
```
from azure.storage import TableService
ts = TableService(host_base='.table.core.windows.cn')
ts.create_table('shangpinimages')
```

This is my error output:
```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    ts.create_table('shangpinimages')
  File "/Users/Taio/Documents/GitHub/jiasir/azure-sdk-for-python/azure/storage/tableservice.py", line 174, in create_table
    self._perform_request(request)
  File "/Users/Taio/Documents/GitHub/jiasir/azure-sdk-for-python/azure/storage/storageclient.py", line 143, in _perform_request
    resp = self._filter(request)
  File "/Users/Taio/Documents/GitHub/jiasir/azure-sdk-for-python/azure/storage/tableservice.py", line 491, in _perform_request_worker
    return self._httpclient.perform_request(request)
  File "/Users/Taio/Documents/GitHub/jiasir/azure-sdk-for-python/azure/http/httpclient.py", line 205, in perform_request
    self.send_request_headers(connection, request.headers)
  File "/Users/Taio/Documents/GitHub/jiasir/azure-sdk-for-python/azure/http/httpclient.py", line 184, in send_request_headers
    connection.endheaders()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 772, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 61] Connection refused
```

And what host_base should I choose in Microsoft Azure China version hosted by 21vianet(manage.windowsazure.cn)?

**Comment by huguesv** [comment]
This has all the base URLs for Microsoft Azure China:
https://msdn.microsoft.com/en-us/library/azure/dn578439.aspx

**Comment by huguesv** [comment]
In case the page isn't accessible/disappears in the future, I'll paste it here.

Windows Azure - General
*.ch *.chinacloudapi.cn

Windows Azure Compute
*.chinacloudapp.cn

Windows Azure Storage
*.blob.core.chinacloudapi.cn
*.queue.core.chinacloudapi.cn
*.table.core.chinacloudapi.cn

Windows Azure Service Management
https://management.core.chinacloudapi.cn/

SQL Database
*.database.chinacloudapi.cn

Windows Azure Management Portal
http://manage.windowsazure.cn

SQL Azure Database Management API
https://management.database.chinacloudapi.cn

Service Bus
*.servicebus.chinacloudapi.cn

SQL Database Import/Export service mapping endpoints
China East: https://sh1prod-dacsvc.chinacloudapp.cn/dacwebservice.svc
China North: https://bj1prod-dacsvc.chinacloudapp.cn/dacwebservice.svc

**Comment by jiasir** [comment]
@huguesv Many thanks!
