### ISSUE TITLE
azure-ai-ml 1.3.0 import results in No module named '_cffi_backend'

### ISSUE THREAD

**Issue by elesel** [Azure/azure-sdk-for-python#28451]
- **Package Name**: azure-ai-ml
- **Package Version**: 1.3.0
- **Operating System**: Ubuntu
- **Python Version**: 3.8

**Describe the bug**
This import leads to a `ModuleNotFoundError`: `from azure.ai.ml.entities._load_functions import load_model`

**To Reproduce**
1. Install the module and dependencies
2. Execute `from azure.ai.ml.entities._load_functions import load_model`

**Expected behavior**
No exceptions (was the case with version 1.2.0).

**Screenshots**

**Additional context**
Here's the traceback:

```
2023-01-23 17:24:23.056644: Traceback (most recent call last):
2023-01-23 17:24:23.056819: File "azureml-assets/scripts/release/asset_publish.py", line 25, in
2023-01-23 17:24:23.057172: from azure.ai.ml.entities._load_functions import load_model
2023-01-23 17:24:23.057269: File "/usr/local/lib/python3.8/dist-packages/azure/ai/ml/__init__.py", line 10, in
2023-01-23 17:24:23.057523: from azure.ai.ml.entities._inputs_outputs import Input, Output
2023-01-23 17:24:23.058197: File "/usr/local/lib/python3.8/dist-packages/azure/ai/ml/entities/__init__.py", line 14, in
2023-01-23 17:24:23.058531: from ._assets._artifacts.data import Data
2023-01-23 17:24:23.058747: File "/usr/local/lib/python3.8/dist-packages/azure/ai/ml/entities/_assets/__init__.py", line 9, in
2023-01-23 17:24:23.059028: from ._artifacts.code import Code
2023-01-23 17:24:23.059219: File "/usr/local/lib/python3.8/dist-packages/azure/ai/ml/entities/_assets/_artifacts/code.py", line 16, in
2023-01-23 17:24:23.059540: from azure.ai.ml.entities._util import load_from_dict
2023-01-23 17:24:23.059630: File "/usr/local/lib/python3.8/dist-packages/azure/ai/ml/entities/_util.py", line 23, in
2023-01-23 17:24:23.059823: from azure.ai.ml._schema._deployment.online.online_deployment import (
2023-01-23 17:24:23.059912: File "/usr/local/lib/python3.8/dist-packages/azure/ai/ml/_schema/_deployment/online/online_deployment.py", line 19, in
2023-01-23 17:24:23.060104: from .data_collector_schema import DataCollectorSchema
2023-01-23 17:24:23.060193: File "/usr/local/lib/python3.8/dist-packages/azure/ai/ml/_schema/_deployment/online/data_collector_schema.py", line 13, in
2023-01-23 17:24:23.060378: from azure.ai.ml._schema._deployment.online.destination_schema import DestinationSchema
2023-01-23 17:24:23.060438: File "/usr/local/lib/python3.8/dist-packages/azure/ai/ml/_schema/_deployment/online/destination_schema.py", line 11, in
2023-01-23 17:24:23.060627: from azure.ai.ml._schema._deployment.online.event_hub_schema import EventHubSchema
2023-01-23 17:24:23.060714: File "/usr/local/lib/python3.8/dist-packages/azure/ai/ml/_schema/_deployment/online/event_hub_schema.py", line 13, in
2023-01-23 17:24:23.060899: from azure.ai.ml._schema._deployment.online.oversize_data_config_schema import OversizeDataConfigSchema
2023-01-23 17:24:23.060984: File "/usr/local/lib/python3.8/dist-packages/azure/ai/ml/_schema/_deployment/online/oversize_data_config_schema.py", line 11, in
2023-01-23 17:24:23.061164: from azure.ai.ml._utils._storage_utils import AzureMLDatastorePathUri
2023-01-23 17:24:23.061256: File "/usr/local/lib/python3.8/dist-packages/azure/ai/ml/_utils/_storage_utils.py", line 9, in
2023-01-23 17:24:23.061511: from azure.ai.ml._artifacts._blob_storage_helper import BlobStorageClient
2023-01-23 17:24:23.062569: File "/usr/local/lib/python3.8/dist-packages/azure/ai/ml/_artifacts/_blob_storage_helper.py", line 37, in
2023-01-23 17:24:23.063633: from azure.storage.blob import BlobServiceClient, ContainerClient
2023-01-23 17:24:23.063745: File "/usr/local/lib/python3.8/dist-packages/azure/storage/blob/__init__.py", line 10, in
2023-01-23 17:24:23.064604: from ._blob_client import BlobClient
2023-01-23 17:24:23.064714: File "/usr/local/lib/python3.8/dist-packages/azure/storage/blob/_blob_client.py", line 55, in
2023-01-23 17:24:23.065815: from ._download import StorageStreamDownloader
2023-01-23 17:24:23.067257: File "/usr/local/lib/python3.8/dist-packages/azure/storage/blob/_download.py", line 20, in
2023-01-23 17:24:23.067441: from ._encryption import (
2023-01-23 17:24:23.067583: File "/usr/local/lib/python3.8/dist-packages/azure/storage/blob/_encryption.py", line 21, in
2023-01-23 17:24:23.067714: from cryptography.hazmat.primitives.ciphers.aead import AESGCM
2023-01-23 17:24:23.067744: File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/ciphers/aead.py", line 10, in
2023-01-23 17:24:23.067861: from cryptography.hazmat.backends.openssl import aead
2023-01-23 17:24:23.067889: File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in
2023-01-23 17:24:23.067994: from cryptography.hazmat.backends.openssl.backend import backend
2023-01-23 17:24:23.068021: File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 16, in
2023-01-23 17:24:23.068141: from cryptography import utils, x509
2023-01-23 17:24:23.068170: File "/usr/lib/python3/dist-packages/cryptography/x509/__init__.py", line 8, in
2023-01-23 17:24:23.068276: from cryptography.x509.base import (
2023-01-23 17:24:23.068302: File "/usr/lib/python3/dist-packages/cryptography/x509/base.py", line 16, in
2023-01-23 17:24:23.068434: from cryptography.x509.extensions import Extension, ExtensionType
2023-01-23 17:24:23.068551: File "/usr/lib/python3/dist-packages/cryptography/x509/extensions.py", line 18, in
2023-01-23 17:24:23.068770: from cryptography.hazmat.primitives import constant_time, serialization
2023-01-23 17:24:23.068856: File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/constant_time.py", line 9, in
2023-01-23 17:24:23.069031: from cryptography.hazmat.bindings._constant_time import lib
2023-01-23 17:24:23.069190: ModuleNotFoundError: No module named '_cffi_backend'
```

**Comment by navba-MSFT** [comment]
@elesel Thanks for reaching out to us and reporting this issue. Could you please run the below command and check if that helps ?

> **python3 -m pip install cffi**

**Comment by elesel** [comment]
Thanks for asking me to dig further into this. It looks like the agent that had the error had cryptography 2.1.4 installed, which has a cffi>=1.7 dependency, but cffi wasn't installed. Here are the full logs from the `pip install` and `pip list`:

```
2023-01-23 16:51:03.635714: Collecting azure-ai-ml>=1.2.0
2023-01-23 16:51:03.663817: Downloading azure_ai_ml-1.3.0-py3-none-any.whl (3.4 MB)
2023-01-23 16:51:04.054144: Collecting scikit-image==0.19.3
2023-01-23 16:51:04.065571: Downloading scikit_image-0.19.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.0 MB)
2023-01-23 16:51:04.684831: Collecting simplification==0.6.2
2023-01-23 16:51:04.695090: Downloading simplification-0.6.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (727 kB)
2023-01-23 16:51:05.288290: Collecting pillow==9.0.0
2023-01-23 16:51:05.301635: Downloading Pillow-9.0.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.3 MB)
2023-01-23 16:51:05.830178: Collecting scipy>=1.4.1
2023-01-23 16:51:05.841729: Downloading scipy-1.10.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.5 MB)
2023-01-23 16:51:08.158787: Collecting networkx>=2.2
2023-01-23 16:51:08.168170: Downloading networkx-3.0-py3-none-any.whl (2.0 MB)
2023-01-23 16:51:08.734539: Collecting numpy>=1.17.0
2023-01-23 16:51:08.746873: Downloading numpy-1.24.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
2023-01-23 16:51:09.397390: Collecting imageio>=2.4.1
2023-01-23 16:51:09.413357: Downloading imageio-2.25.0-py3-none-any.whl (3.4 MB)
2023-01-23 16:51:09.613606: Collecting packaging>=20.0
2023-01-23 16:51:09.619668: Downloading packaging-23.0-py3-none-any.whl (42 kB)
2023-01-23 16:51:09.756801: Collecting tifffile>=2019.7.26
2023-01-23 16:51:09.765509: Downloading tifffile-2023.1.23.1-py3-none-any.whl (214 kB)
2023-01-23 16:51:09.938664: Collecting PyWavelets>=1.1.1
2023-01-23 16:51:09.958648: Downloading PyWavelets-1.4.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.9 MB)
2023-01-23 16:51:10.311774: Collecting msrest>=0.6.18
2023-01-23 16:51:10.320180: Downloading msrest-0.7.1-py3-none-any.whl (85 kB)
2023-01-23 16:51:10.441429: Collecting azure-storage-blob =12.10.0
2023-01-23 16:51:10.448721: Downloading azure_storage_blob-12.14.1-py3-none-any.whl (383 kB)
2023-01-23 16:51:10.537727: Collecting azure-mgmt-core =1.3.0
2023-01-23 16:51:10.543893: Downloading azure_mgmt_core-1.3.2-py3-none-any.whl (26 kB)
2023-01-23 16:51:10.644490: Collecting strictyaml =3.5
2023-01-23 16:51:11.336904: Downloading marshmallow-3.19.0-py3-none-any.whl (49 kB)
2023-01-23 16:51:11.444591: Collecting azure-core!=1.22.0, =1.8.0
2023-01-23 16:51:11.471079: Downloading azure_core-1.26.2-py3-none-any.whl (173 kB)
2023-01-23 16:51:11.576586: Collecting azure-common =1.1
2023-01-23 16:51:11.580022: Using cached azure_common-1.1.28-py2.py3-none-any.whl (14 kB)
2023-01-23 16:51:11.676511: Collecting jsonschema =4.0.0
2023-01-23 16:51:11.686518: Downloading jsonschema-4.17.3-py3-none-any.whl (90 kB)
2023-01-23 16:51:11.827716: Collecting pydash =5.1.0 in /usr/local/lib/python3.8/dist-packages (from azure-ai-ml>=1.2.0->-r azureml-assets/scripts/release/requirements.txt (line 2)) (6.0)
2023-01-23 16:51:12.384834: Collecting azure-storage-file-share =1.11.0 in /usr/lib/python3/dist-packages (from azure-core!=1.22.0, =1.8.0->azure-ai-ml>=1.2.0->-r azureml-assets/scripts/release/requirements.txt (line 2)) (1.11.0)
2023-01-23 16:51:13.764441: Collecting requests>=2.18.4
2023-01-23 16:51:13.784427: Downloading requests-2.28.2-py3-none-any.whl (62 kB)
2023-01-23 16:51:13.844951: Requirement already satisfied: cryptography>=2.1.4 in /usr/lib/python3/dist-packages (from azure-storage-blob =12.10.0->azure-ai-ml>=1.2.0->-r azureml-assets/scripts/release/requirements.txt (line 2)) (2.1.4)
2023-01-23 16:51:14.105699: Collecting importlib-resources>=1.4.0
2023-01-23 16:51:14.111895: Downloading importlib_resources-5.10.2-py3-none-any.whl (34 kB)
2023-01-23 16:51:14.209111: Collecting attrs>=17.4.0
2023-01-23 16:51:14.217558: Downloading attrs-22.2.0-py3-none-any.whl (60 kB)
2023-01-23 16:51:14.369933: Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
2023-01-23 16:51:14.381804: Downloading pyrsistent-0.19.3-py3-none-any.whl (57 kB)
2023-01-23 16:51:14.489652: Collecting pkgutil-resolve-name>=1.3.10
2023-01-23 16:51:14.496244: Downloading pkgutil_resolve_name-1.3.10-py3-none-any.whl (4.7 kB)
2023-01-23 16:51:14.639833: Collecting requests-oauthlib>=0.5.0
2023-01-23 16:51:14.647551: Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
2023-01-23 16:51:14.756153: Collecting certifi>=2017.4.17
2023-01-23 16:51:14.762283: Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
2023-01-23 16:51:15.193552: Collecting python-dateutil>=2.6.0
2023-01-23 16:51:15.201054: Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
2023-01-23 16:51:15.411076: Collecting zipp>=3.1.0
2023-01-23 16:51:15.417268: Downloading zipp-3.11.0-py3-none-any.whl (6.6 kB)
2023-01-23 16:51:15.615740: Collecting charset-normalizer =2
2023-01-23 16:51:15.624443: Downloading charset_normalizer-3.0.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (195 kB)
2023-01-23 16:51:15.664944: Requirement already satisfied: idna =2.5 in /usr/lib/python3/dist-packages (from requests>=2.18.4->azure-core!=1.22.0, =1.8.0->azure-ai-ml>=1.2.0->-r azureml-assets/scripts/release/requirements.txt (line 2)) (2.6)
2023-01-23 16:51:15.759541: Collecting urllib3 =1.21.1
2023-01-23 16:51:15.766501: Downloading urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
2023-01-23 16:51:15.906733: Collecting oauthlib>=3.0.0
2023-01-23 16:51:15.915175: Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
2023-01-23 16:51:16.079689: Building wheels for collected packages: strictyaml
2023-01-23 16:51:16.084992: Building wheel for strictyaml (setup.py): started
2023-01-23 16:51:16.537491: Building wheel for strictyaml (setup.py): finished with status 'done'
2023-01-23 16:51:16.539975: Created wheel for strictyaml: filename=strictyaml-1.6.2-py3-none-any.whl size=127219 sha256=667b690577490161e0b9611398acbcd2c192b0973953b73731cada8122189833
2023-01-23 16:51:16.541411: Stored in directory: /root/.cache/pip/wheels/f8/13/da/1800d5079cf7d0123b61536fc8106cb9343d0675986406b2d5
2023-01-23 16:51:16.547676: Successfully built strictyaml
2023-01-23 16:51:17.117933: Installing collected packages: charset-normalizer, azure-common, zipp, urllib3, typing-extensions, tqdm, simplification, python-dateutil, pyrsistent, pyjwt, pydash, pkgutil-resolve-name, pillow, packaging, oauthlib, numpy, networkx, isodate, colorama, certifi, attrs, tifffile, strictyaml, scipy, requests, PyWavelets, marshmallow, importlib-resources, imageio, scikit-image, requests-oauthlib, jsonschema, azure-core, msrest, azure-mgmt-core, azure-storage-file-share, azure-storage-blob, azure-storage-file-datalake, azure-ai-ml
2023-01-23 16:51:38.138881: Successfully installed PyWavelets-1.4.1 attrs-22.2.0 azure-ai-ml-1.3.0 azure-common-1.1.28 azure-core-1.26.2 azure-mgmt-core-1.3.2 azure-storage-blob-12.14.1 azure-storage-file-datalake-12.9.1 azure-storage-file-share-12.10.1 certifi-2022.12.7 charset-normalizer-3.0.1 colorama-0.4.6 imageio-2.25.0 importlib-resources-5.10.2 isodate-0.6.1 jsonschema-4.17.3 marshmallow-3.19.0 msrest-0.7.1 networkx-3.0 numpy-1.24.1 oauthlib-3.2.2 packaging-23.0 pillow-9.0.0 pkgutil-resolve-name-1.3.10 pydash-5.1.2 pyjwt-2.6.0 pyrsistent-0.19.3 python-dateutil-2.8.2 requests-2.28.2 requests-oauthlib-1.3.1 scikit-image-0.19.3 scipy-1.10.0 simplification-0.6.2 strictyaml-1.6.2 tifffile-2023.1.23.1 tqdm-4.64.1 typing-extensions-4.4.0 urllib3-1.26.14 zipp-3.11.0
2023-01-23 16:51:38.140404: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2023-01-23 16:51:38.509605: Installed packages:
2023-01-23 16:51:39.167030: Package Version Editable project location
2023-01-23 16:51:39.168455: --------------------------- --------------- --------------------------------------------------------
2023-01-23 16:51:39.169440: asn1crypto 0.24.0
2023-01-23 16:51:39.170384: attrs 22.2.0
2023-01-23 16:51:39.175029: azure-ai-ml 1.3.0
2023-01-23 16:51:39.178579: azure-common 1.1.28
2023-01-23 16:51:39.179933: azure-core 1.26.2
2023-01-23 16:51:39.180972: azure-mgmt-core 1.3.2
2023-01-23 16:51:39.182076: azure-storage-blob 12.14.1
2023-01-23 16:51:39.182876: azure-storage-file-datalake 12.9.1
2023-01-23 16:51:39.183645: azure-storage-file-share 12.10.1
2023-01-23 16:51:39.184646: azureml-assets 0.0.1 /package/unarchive/azureml-assets/scripts/azureml-assets
2023-01-23 16:51:39.193245: certifi 2022.12.7
2023-01-23 16:51:39.194356: charset-normalizer 3.0.1
2023-01-23 16:51:39.195322: colorama 0.4.6
2023-01-23 16:51:39.203415: cryptography 2.1.4
2023-01-23 16:51:39.204241: gitdb 4.0.10
2023-01-23 16:51:39.204826: GitPython 3.1.30
2023-01-23 16:51:39.205426: idna 2.6
2023-01-23 16:51:39.205883: imageio 2.25.0
2023-01-23 16:51:39.206363: importlib-resources 5.10.2
2023-01-23 16:51:39.206784: isodate 0.6.1
2023-01-23 16:51:39.207239: jsonschema 4.17.3
2023-01-23 16:51:39.207713: keyring 10.6.0
2023-01-23 16:51:39.208278: keyrings.alt 3.0
2023-01-23 16:51:39.210159: marshmallow 3.19.0
2023-01-23 16:51:39.210676: msrest 0.7.1
2023-01-23 16:51:39.211169: networkx 3.0
2023-01-23 16:51:39.211696: numpy 1.24.1
2023-01-23 16:51:39.212166: oauthlib 3.2.2
2023-01-23 16:51:39.212611: packaging 23.0
2023-01-23 16:51:39.213006: Pillow 9.0.0
2023-01-23 16:51:39.213444: pip 22.3.1
2023-01-23 16:51:39.213850: pkgutil_resolve_name 1.3.10
2023-01-23 16:51:39.214280: pycrypto 2.6.1
2023-01-23 16:51:39.214663: pydash 5.1.2
2023-01-23 16:51:39.215649: PyGObject 3.26.1
2023-01-23 16:51:39.220648: PyJWT 2.6.0
2023-01-23 16:51:39.225229: pyrsistent 0.19.3
2023-01-23 16:51:39.225406: python-apt 1.6.5+ubuntu0.7
2023-01-23 16:51:39.226724: python-dateutil 2.8.2
2023-01-23 16:51:39.226882: PyWavelets 1.4.1
2023-01-23 16:51:39.226916: pyxdg 0.25
2023-01-23 16:51:39.226976: PyYAML 6.0
2023-01-23 16:51:39.227026: requests 2.28.2
2023-01-23 16:51:39.227373: requests-oauthlib 1.3.1
2023-01-23 16:51:39.227815: scikit-image 0.19.3
2023-01-23 16:51:39.228424: scipy 1.10.0
2023-01-23 16:51:39.228839: SecretStorage 2.3.1
2023-01-23 16:51:39.229284: setuptools 39.0.1
2023-01-23 16:51:39.229706: simplification 0.6.2
2023-01-23 16:51:39.230098: six 1.11.0
2023-01-23 16:51:39.230475: smmap 5.0.0
2023-01-23 16:51:39.230979: strictyaml 1.6.2
2023-01-23 16:51:39.231565: tifffile 2023.1.23.1
2023-01-23 16:51:39.234722: tqdm 4.64.1
2023-01-23 16:51:39.243402: typing_extensions 4.4.0
2023-01-23 16:51:39.245767: unattended-upgrades 0.1
2023-01-23 16:51:39.247133: urllib3 1.26.14
2023-01-23 16:51:39.249905: wheel 0.30.0
2023-01-23 16:51:39.252500: zipp 3.11.0
```

A clean install of azure-ai-ml 1.3.0 installs cryptography 39.0.0 and cffi 1.15.1, so this is not an issue with azure-ai-ml.
