### ISSUE TITLE
fails to deploy model to webservice by a job

### ISSUE THREAD

**Issue by yhtprime** [Azure/azure-sdk-for-python#28567]
- **azureml_inference_server_http**: 
- **azmlinfsrv/0.7.7**: 
- **Azure Machine Learning**:
- **Python 3.7**: 

**Describe the bug**
I submitted a Job using bicep File to deploy the model to the webService(AKS). 
But after the deployment I found that It is failed.
If I submit it manually, it will work fine.

Error Message:
_AttributeError: module 'service_driver' has no attribute 'run'_

Error log:
```
2023-02-01T03:56:56,241428925+00:00 - iot-server/run 
2023-02-01T03:56:56,244417882+00:00 - rsyslog/run 
2023-02-01T03:56:56,254907281+00:00 - nginx/run 
2023-02-01T03:56:56,266311497+00:00 - gunicorn/run 
2023-02-01T03:56:56,269279153+00:00 | gunicorn/run | 
2023-02-01T03:56:56,274724056+00:00 | gunicorn/run | ###############################################
2023-02-01T03:56:56,283368520+00:00 | gunicorn/run | AzureML Container Runtime Information
2023-02-01T03:56:56,284717946+00:00 | gunicorn/run | ###############################################
2023-02-01T03:56:56,285949469+00:00 | gunicorn/run | 
2023-02-01T03:56:56,287311095+00:00 | gunicorn/run | 
2023-02-01T03:56:56,289753341+00:00 | gunicorn/run | AzureML image information: openmpi3.1.2-ubuntu18.04, Materializaton Build:20230103.v4
2023-02-01T03:56:56,290965564+00:00 | gunicorn/run | 
2023-02-01T03:56:56,292227588+00:00 | gunicorn/run | 
2023-02-01T03:56:56,293450211+00:00 | gunicorn/run | PATH environment variable: /azureml-envs/sklearn-0.24.1/bin:/opt/miniconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2023-02-01T03:56:56,294676235+00:00 | gunicorn/run | PYTHONPATH environment variable: 
2023-02-01T03:56:56,295896758+00:00 | gunicorn/run | 
2023-02-01T03:56:56,297254584+00:00 | gunicorn/run | Pip Dependencies (before dynamic installation)

EdgeHubConnectionString and IOTEDGE_IOTHUBHOSTNAME are not set. Exiting...
2023-02-01T03:56:56,322741067+00:00 - iot-server/finish 1 0
2023-02-01T03:56:56,324067192+00:00 - Exit code 1 is normal. Not restarting iot-server.
adal==1.2.7
applicationinsights==0.11.10
argcomplete==2.0.0
attrs==22.2.0
azure-common==1.1.28
azure-core==1.26.2
azure-graphrbac==0.61.1
azure-identity==1.12.0
azure-mgmt-authorization==3.0.0
azure-mgmt-containerregistry==10.0.0
azure-mgmt-core==1.3.2
azure-mgmt-keyvault==10.1.0
azure-mgmt-resource==21.2.1
azure-mgmt-storage==20.1.0
azure-storage-blob==12.13.0
azureml-core==1.48.0
azureml-dataprep==4.8.4
azureml-dataprep-native==38.0.0
azureml-dataprep-rslex==2.15.2
azureml-dataset-runtime==1.48.0
azureml-defaults==1.48.0
azureml-inference-server-http==0.7.7
azureml-mlflow==1.48.0
azureml-telemetry==1.48.0
backcall==0.2.0
backports.tempfile==1.0
backports.weakref==1.0.post1
bcrypt==4.0.1
cachetools==5.2.1
certifi @ file:///croot/certifi_1671487769961/work/certifi
cffi==1.15.1
charset-normalizer==3.0.1
click==8.1.3
cloudpickle==2.2.0
contextlib2==21.6.0
cryptography==39.0.0
cycler==0.11.0
databricks-cli==0.17.4
debugpy==1.6.5
decorator==5.1.1
distro==1.8.0
docker==6.0.1
dotnetcore2==3.1.23
entrypoints==0.4
Flask==2.2.2
Flask-Cors==3.0.10
fusepy==3.0.1
gitdb==4.0.10
GitPython==3.1.30
google-api-core==2.11.0
google-auth==2.16.0
googleapis-common-protos==1.58.0
gunicorn==20.1.0
humanfriendly==10.0
idna==3.4
importlib-metadata==6.0.0
importlib-resources==5.10.2
inference-schema==1.5.1
ipykernel==6.16.2
ipython==7.34.0
isodate==0.6.1
itsdangerous==2.1.2
jedi==0.18.2
jeepney==0.8.0
Jinja2==3.1.2
jmespath==1.0.1
joblib==1.2.0
jsonpickle==2.2.0
jsonschema==4.17.3
jupyter-client==7.4.9
jupyter-core==4.12.0
kiwisolver==1.4.4
knack==0.10.1
MarkupSafe==2.1.1
matplotlib==3.3.4
matplotlib-inline==0.1.6
mlflow-skinny==1.30.0
msal==1.20.0
msal-extensions==1.0.0
msrest==0.7.1
msrestazure==0.6.4
ndg-httpsclient==0.5.1
nest-asyncio==1.5.6
numpy==1.19.5
oauthlib==3.2.2
opencensus==0.11.0
opencensus-context==0.1.3
opencensus-ext-azure==1.1.7
packaging==23.0
pandas==1.1.5
paramiko==2.12.0
parso==0.8.3
pathspec==0.10.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.4.0
pkginfo==1.9.6
pkgutil-resolve-name==1.3.10
portalocker==2.6.0
prompt-toolkit==3.0.36
protobuf==4.21.12
psutil==5.8.0
ptyprocess==0.7.0
pyarrow==9.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
Pygments==2.14.0
PyJWT==2.6.0
PyNaCl==1.5.0
pyOpenSSL==22.1.0
pyparsing==3.0.9
pyrsistent==0.19.3
PySocks==1.7.1
python-dateutil==2.8.2
pytz==2022.7
PyYAML==6.0
pyzmq==25.0.0
requests==2.28.2
requests-oauthlib==1.3.1
rsa==4.9
scikit-learn==0.24.1
scipy==1.5.4
SecretStorage==3.3.3
six==1.16.0
smmap==5.0.0
sqlparse==0.4.3
tabulate==0.9.0
threadpoolctl==3.1.0
tornado==6.2
tqdm==4.59.0
traitlets==5.8.1
typing-extensions==4.4.0
urllib3==1.26.14
wcwidth==0.2.5
websocket-client==1.4.2
Werkzeug==2.2.2
wrapt==1.12.1
zipp==3.11.0

2023-02-01T03:56:56,637118325+00:00 | gunicorn/run | 
2023-02-01T03:56:56,638609353+00:00 | gunicorn/run | ###############################################
2023-02-01T03:56:56,640066181+00:00 | gunicorn/run | AzureML Inference Server
2023-02-01T03:56:56,641419207+00:00 | gunicorn/run | ###############################################
2023-02-01T03:56:56,642808133+00:00 | gunicorn/run | 
2023-02-01T03:56:57,426863094+00:00 | gunicorn/run | Starting AzureML Inference Server HTTP.

Azure ML Inferencing HTTP server v0.7.7


Server Settings
---------------
Entry Script Name: /structure/azureml-app/main.py
Model Directory: /var/azureml-app/azureml-models/wine/1
Worker Count: 1
Worker Timeout (seconds): 300
Server Port: 31311
Application Insights Enabled: false
Application Insights Key: AppInsights key provided
Inferencing HTTP server version: azmlinfsrv/0.7.7
CORS for the specified origins: None


Server Routes
---------------
Liveness Probe: GET   127.0.0.1:31311/
Score:          POST  127.0.0.1:31311/score

Starting gunicorn 20.1.0
Listening at: http://0.0.0.0:31311 (15)
Using worker: sync
Booting worker with pid: 66
Initializing logger
2023-02-01 03:56:57,940 | root | INFO | Starting up app insights client
logging socket was found. logging is available.
logging socket was found. logging is available.
2023-02-01 03:56:57,941 | root | INFO | Starting up app insight hooks
2023-02-01 03:56:57,941 | root | INFO | Found user script at /structure/azureml-app/main.py
2023-02-01 03:56:57,941 | root | INFO | run() is not decorated. Server will invoke it with the input in JSON string.
2023-02-01 03:56:57,941 | root | INFO | Invoking user's init function
2023-02-01 03:56:57,941 | root | ERROR | User's init function failed
2023-02-01 03:56:57,942 | root | ERROR | Encountered Exception Traceback (most recent call last):
  File "/azureml-envs/sklearn-0.24.1/lib/python3.7/site-packages/azureml_inference_server_http/server/user_script.py", line 116, in invoke_init
    self._user_init()
  File "/structure/azureml-app/main.py", line 30, in init
    run_args = inspect.signature(driver_module.run).parameters.keys()
AttributeError: module 'service_driver' has no attribute 'run'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/azureml-envs/sklearn-0.24.1/lib/python3.7/site-packages/azureml_inference_server_http/server/aml_blueprint.py", line 145, in setup
    self.user_script.invoke_init()
  File "/azureml-envs/sklearn-0.24.1/lib/python3.7/site-packages/azureml_inference_server_http/server/user_script.py", line 118, in invoke_init
    raise UserScriptException(ex) from ex
azureml_inference_server_http.server.user_script.UserScriptException: Caught an unhandled exception from the user script

2023-02-01 03:56:57,942 | root | INFO | Model Directory Contents:
2023-02-01 03:56:57,942 | root | INFO | 1/
2023-02-01 03:56:57,942 | root | INFO |     model.pickle
Worker exiting (pid: 66)
Shutting down: Master
Reason: Worker failed to boot.
2023-02-01T03:56:58,062150635+00:00 - gunicorn/finish 3 0
2023-02-01T03:56:58,063750265+00:00 - Exit code 3 is not normal. Killing image.
```

deploy file(deploy.py):
```
from azureml.core.webservice import AksWebservice, Webservice
from azureml.core.model import Model
from azureml.core.compute import AksCompute
from azureml.core import Workspace
from azureml.core import Environment
from azureml.core import Model
from azureml.core.model import InferenceConfig 

import sys

ws = Workspace(sys.argv[1], sys.argv[2], sys.argv[3])
aks_target = AksCompute(ws,sys.argv[4])

deployment_config = AksWebservice.deploy_configuration()

model = Model(
    workspace=ws,
    name=sys.argv[5], # $model_name
    version=1 # $model_version
)
environment = Environment.get(
    workspace=ws,
    name='AzureML-sklearn-0.24-ubuntu18.04-py37-cpu', # $environment_name
)
inference_config = InferenceConfig(entry_script='./score.py', environment=environment)
service = Model.deploy(ws, sys.argv[5], [model], inference_config, deployment_config, aks_target)
try:
    service.wait_for_deployment(show_output = True)
except:
    print(service.get_logs())
```

score.py:
```
import json
import os
import pathlib
import pickle

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

model = None  # type: GridSearchCV

def init():

    print(f'[ init ]')

    global model

    AZUREML_MODEL_DIR = os.getenv('AZUREML_MODEL_DIR')
    print(f'[ init ] AZUREML_MODEL_DIR: {AZUREML_MODEL_DIR}')

    azuremlModelDirPath = pathlib.Path(AZUREML_MODEL_DIR).resolve()
    print(f'[ init ] azuremlModelDirPath: {azuremlModelDirPath}')

    modelPath = azuremlModelDirPath / 'model.pickle'
    print(f'[ init ] modelPath: {modelPath}')

    model = pickle.loads(modelPath.read_bytes())
    print(f'[ init ] model: {model}')

def run(inputData):

    print(f'[ run ] inputData: {inputData}')

    input = json.loads(inputData)
    print(f'[ run ] input: {input}')

    output = model.predict(input)
    print(f'[ run ] output: {output}')

    output = list([ float(_) for _ in output ])

    return output
```

**Comment by jaga-work** [comment]
Hi @yhtprime, we are no longer supporting python 3.7, Could you please try to replicate with python 3.8 or 3.8 or 3.10. or 3.11
