### ISSUE TITLE
Key Vault Secret Set attempt with too long name results in inappropriate error

### ISSUE THREAD

**Issue by sashaCher** [Azure/azure-sdk-for-python#28698]
- **Package Name**: azure-keyvault-secrets
- **Package Version**: 4.6.0
- **Operating System**: macOS 13.2 (22D49)
- **Python Version**: Python 3.9.16

**Describe the bug**
When calling `set_secret` method with secret name that's length is beyond allowed the next exception and error message appear:
```
Traceback (most recent call last):
  File "/Users/dev/wip/azure/try_it.py", line 51, in <module>
    do_write()
  File "/Users/dev/wip/azure/try_it.py", line 46, in do_write
    secret: KeyVaultSecret = client.set_secret(**set_secret_kwarg)
  File "/Users/dev/wip/azure/.venv/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/Users/dev/wip/azure/.venv/lib/python3.9/site-packages/azure/keyvault/secrets/_client.py", line 126, in set_secret
    bundle = self._client.set_secret(
  File "/Users/dev/wip/azure/.venv/lib/python3.9/site-packages/azure/keyvault/secrets/_generated/_operations_mixin.py", line 2550, in set_secret
    return mixin_instance.set_secret(vault_base_url, secret_name, parameters, **kwargs)
  File "/Users/dev/wip/azure/.venv/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/Users/dev/wip/azure/.venv/lib/python3.9/site-packages/azure/keyvault/secrets/_generated/v7_3/operations/_key_vault_client_operations.py", line 493, in set_secret
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/Users/dev/wip/azure/.venv/lib/python3.9/site-packages/azure/core/exceptions.py", line 108, in map_error
    error = error_type(response=response)
  File "/Users/dev/wip/azure/.venv/lib/python3.9/site-packages/azure/keyvault/secrets/_shared/exceptions.py", line 24, in _get_exception_for_key_vault_error
    message = "({}) {}".format(body["error"]["code"], body["error"]["message"])  # type: Optional[str]
TypeError: string indices must be integers
```

**To Reproduce**
1. call `set_secret` api with `name` parameter value that's length is greater than 127 symbols

**Expected behavior**
Meaningful exception allows to troubleshoot the issue.
Like: Bad Request secret name is too long

**Additional context**
From [debug](https://github.com/Azure/azure-sdk-for-python/blob/6ae53f78777dd9b41d0475d1b54c149faea34721/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/exceptions.py#L22) I can see that response body is an HTML string so that dictionary indices are not applicable to it

**Comment by kashifkhan** [comment]
Thanks for the feedback @sashaCher . We will investigate and get back to you asap.

**Comment by mccoyp** [comment]
Apologies for the delayed response; this was resolved last month by https://github.com/Azure/azure-sdk-for-python/pull/30277. Thank you again for making us aware of this!
