### ISSUE TITLE
InvalidHeaderValue on BlobService example

### ISSUE THREAD

**Issue by rhaps0dy** [Azure/azure-sdk-for-python#288]
Hello,
I have installed this SDK from PyPI and from GitHub, and I get the same error. I'm trying to run the SDK examples:
```python
from azure.storage import BlobService
blob_service = BlobService(account_name, account_key)
blob_service.create_container('images')
```

And I get this error:

```
Traceback (most recent call last):
  File "/home/adria/Programacio/azure-sdk-for-python/azure/storage/storageclient.py", line 143, in _perform_request
    resp = self._filter(request)
  File "/home/adria/Programacio/azure-sdk-for-python/azure/storage/storageclient.py", line 132, in _perform_request_worker
    return self._httpclient.perform_request(request)
  File "/home/adria/Programacio/azure-sdk-for-python/azure/http/httpclient.py", line 247, in perform_request
    self.respheader, respbody)
azure.http.HTTPError: The value for one of the HTTP headers is not in the correct format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adria/Programacio/azure-sdk-for-python/azure/storage/blobservice.py", line 192, in create_container
    _dont_fail_on_exist(ex)
  File "/home/adria/Programacio/azure-sdk-for-python/azure/__init__.py", line 907, in _dont_fail_on_exist
    raise error
  File "/home/adria/Programacio/azure-sdk-for-python/azure/storage/blobservice.py", line 189, in create_container
    self._perform_request(request)
  File "/home/adria/Programacio/azure-sdk-for-python/azure/storage/storageclient.py", line 150, in _perform_request
    _storage_error_handler(ex)
  File "/home/adria/Programacio/azure-sdk-for-python/azure/storage/__init__.py", line 890, in _storage_error_handler
    return _general_error_handler(http_error)
  File "/home/adria/Programacio/azure-sdk-for-python/azure/__init__.py", line 931, in _general_error_handler
    http_error.respbody.decode('utf-8'))
azure.WindowsAzureError: Unknown error (The value for one of the HTTP headers is not in the correct format.)
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format.
RequestId:7f2b44b7-0001-0040-3e64-9b5b6c000000
Time:2015-02-14T20:07:43.3300628Z</Message><HeaderName>x-ms-version</HeaderName><HeaderValue>2012-02-12</HeaderValue></Error>
```
This happens with all the methods of BlobService I've tried. I've printed the actual request headers and the signature string and I could not spot any errors:
```
'PUT\n\n\n0\n\napplication/octet-stream Charset=UTF-8\n\n\n\n\n\n\nx-ms-date:Sat, 14 Feb 2015 20:17:52 GMT\nx-ms-version:2012-02-12\n/monkingme/images\nrestype:container'
[('x-ms-meta-name-values', None), ('x-ms-blob-public-access', None), ('Content-Length', '0'), ('x-ms-version', '2012-02-12'), ('x-ms-date', 'Sat, 14 Feb 2015 20:17:52 GMT'), ('Content-Type', 'application/octet-stream Charset=UTF-8'), ('Authorization', 'SharedKey monkingme:4Y+0+imrSOdvDcV+R23bDLyVG4K9C+jnWC1R3CXM3BY=')]
```

Help would be much appreciated,
Adrià

**Comment by rhaps0dy** [comment]
I solved it.

Removed ` Charset=UTF-8` `from azure/storage/__init__.py` and it works.
We can add some more lines to make it accept UTF-8; I'll make a pull request.

**Comment by rhaps0dy** [comment]
Hey,

The "x-ms-version" header was actually wrong. Setting it to "2014-02-14", like the Java SDK is, did the trick.

I am submitting a pull request.

**Comment by huguesv** [comment]
The upcoming 0.10 release is targeting 2014-02-14.
