### ISSUE TITLE
[Resources] The error message of the managedapp show method is not returned

### ISSUE THREAD

**Issue by wu5bocheng** [Azure/azure-sdk-for-python#28897]
- **Package Name**: mgmt-resource
- **Package Version**: azure-mgmt-resource_22.1.0b1
- **Operating System**: windows 11
- **Python Version**: 3.10.7

**Describe the bug**

Reported from Azure CLI
The error message of the managedapp show method is not returned by parsing

**To Reproduce**
```
from azure.cli.core.commands.client_factory import get_mgmt_service_client
from azure.mgmt.resource.managedapplications import ApplicationClient
racf = get_mgmt_service_client(cli_ctx, ApplicationClient)
    return racf.applications.get(resource_group_name, application_name)
```
if error happens, such as the resource_group couldn't be found. It should terminate the process and call error instead of showing SuccessfulExecute.

**Suggested Solutions**

[Breaking Changes] Modify the way error messages are parsed for all 4 functions in azure/mgmt/resource/managedapplications/operations/_operations.py

class ApplicationsOperations()
...
**if response.status_code not in [200, 404]: --> if response.status_code not in [200]:**

...
**Expected behavior**

if error happens, such as the resource_group couldn't be found. It should terminate the process and call error instead of showing SuccessfulExecute.

**Screenshots**

**Additional context**
**current debug message**
```
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/v-bocheng-test/providers/Microsoft.Solutions/applications/testapp?api-version=2018-06-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '8d1538bc-b0d4-11ed-92b9-3c6aa71998cf'
cli.azure.cli.core.sdk.policies:     'CommandName': 'managedapp show'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name -g --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.45.0 azsdk-python-mgmt-resource/21.1.0b1 Python/3.10.8 (Windows-10-10.0.22623-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/v-bocheng-test/providers/Microsoft.Solutions/applications/testapp?api-version=2018-06-01 HTTP/1.1" 404 106
cli.azure.cli.core.sdk.policies: Response status: 404
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'gateway'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '52c4d0e7-beb3-4ad9-812f-77ba81e3ece4'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '52c4d0e7-beb3-4ad9-812f-77ba81e3ece4'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'EASTASIA:20230220T041059Z:52c4d0e7-beb3-4ad9-812f-77ba81e3ece4'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 20 Feb 2023 04:10:59 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '106'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"ResourceGroupNotFound","message":"Resource group 'v-bocheng-test' could not be found."}}
cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x000001D1F545DF30>, <function _x509_from_base64_to_hex_transform at 0x000001D1F545DFC0>]
cli.knack.cli: Event: CommandInvoker.OnFilterResult []
cli.knack.cli: Event: Cli.SuccessfulExecute []
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x000001D1F54020E0>]
```

**error message can be printed after modification:**
```
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ApplicationClient
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\v-bochengwu\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\v-bochengwu\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/54826b22-38d6-4fb2-bad9-b7b93a3e9c5a/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/54826b22-38d6-4fb2-bad9-b7b93a3e9c5a/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/54826b22-38d6-4fb2-bad9-b7b93a3e9c5a/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/54826b22-38d6-4fb2-bad9-b7b93a3e9c5a/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/54826b22-38d6-4fb2-bad9-b7b93a3e9c5a/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/54826b22-38d6-4fb2-bad9-b7b93a3e9c5a/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/54826b22-38d6-4fb2-bad9-b7b93a3e9c5a/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 173b3b3b-0bb9-4007-86f5-5cccbf46666f
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/v-bocheng-test/providers/Microsoft.Solutions/applications/testapp?api-version=2018-06-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '8aa96ea8-b0c2-11ed-924f-3c6aa71998cf'
cli.azure.cli.core.sdk.policies:     'CommandName': 'managedapp show'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name -g --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.45.0 azsdk-python-mgmt-resource/21.1.0b1 Python/3.10.8 (Windows-10-10.0.22623-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/v-bocheng-test/providers/Microsoft.Solutions/applications/testapp?api-version=2018-06-01 HTTP/1.1" 404 106
cli.azure.cli.core.sdk.policies: Response status: 404
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'gateway'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '623b9a67-d18a-4cc7-a79a-1801c5695eb3'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '623b9a67-d18a-4cc7-a79a-1801c5695eb3'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'EASTASIA:20230220T020205Z:623b9a67-d18a-4cc7-a79a-1801c5695eb3'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 20 Feb 2023 02:02:04 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '106'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"ResourceGroupNotFound","message":"Resource group 'v-bocheng-test' could not be found."}}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "C:\Users\v-bochengwu\Workspace\azure-cli\src\azure-cli-core\azure\cli\core\commands\command_operation.py", line 361, in handler
    return op(**command_args)
  File "C:\Users\v-bochengwu\Workspace\azure-cli\src\azure-cli\azure\cli\command_modules\resource\custom.py", line 1423, in show_application
    return racf.applications.get(resource_group_name, application_name)
  File "C:\Users\v-bochengwu\Workspace\env\lib\site-packages\azure\core\tracing\decorator.py", line 73, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "C:\Users\v-bochengwu\Workspace\env\lib\site-packages\azure\mgmt\resource\managedapplications\operations\_operations.py", line 831, in get
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "C:\Users\v-bochengwu\Workspace\env\lib\site-packages\azure\core\exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: (ResourceGroupNotFound) Resource group 'v-bocheng-test' could not be found.
Code: ResourceGroupNotFound
Message: Resource group 'v-bocheng-test' could not be found.

cli.azure.cli.core.azclierror: (ResourceGroupNotFound) Resource group 'v-bocheng-test' could not be found.
Code: ResourceGroupNotFound
Message: Resource group 'v-bocheng-test' could not be found.
az_command_data_logger: (ResourceGroupNotFound) Resource group 'v-bocheng-test' could not be found.
Code: ResourceGroupNotFound
Message: Resource group 'v-bocheng-test' could not be found.
```

**Comment by msyyc** [comment]
@wu5bocheng `ApplicationClient` of `azure-mgmt-resource_22.1.0b1` is generated with [2018-06-01/managedapplications.json](https://github.com/Azure/azure-rest-api-specs/blob/db38bff6ab588858ee1df6f86ae1d0ec4d2d5781/specification/resources/resource-manager/Microsoft.Solutions/stable/2018-06-01/managedapplications.json#L106-L123) which defines `404` as normal status code. And in [2019-07-01/managedapplications.json](https://github.com/Azure/azure-rest-api-specs/blob/db38bff6ab588858ee1df6f86ae1d0ec4d2d5781/specification/resources/resource-manager/Microsoft.Solutions/stable/2019-07-01/managedapplications.json#L106-L120), it removes `404`.
We will publish a new version to fix it. Thanks!
