### ISSUE TITLE
Errors with AzureML MlFlow logging: azure.core.exceptions.ServiceResponseError and .ServiceRequestError

### ISSUE THREAD

**Issue by achatrian** [Azure/azure-sdk-for-python#29024]
- **Package Name**: 
- azureml-mlflow
- **Package Version**: 
-1.49.0, 1.43.0.post1
- **Operating System**:
- NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
- **Python Version**: 
Python 3.9.0
**Describe the bug**
Script run on AzureML Studio GPU compute throws azure.core.exceptions.ServiceResponseError: HTTPSConnectionPool(host='northeurope.api.azureml.ms', port=443): Read timed out. (read timeout=300) when attempting to log images to mlflow.
This behaviour only started a few days ago, no package changes were made in the meantime and before then mlflow worked just fine.
The mlflow environment is set up as follows:
`python
    ws = Workspace.get(name=data_config['workspace_name'],
                       subscription_id=data_config['subscription_id'],
                       resource_group=data_config['resource_group'])
    mlflow.set_tracking_uri(ws.get_mlflow_tracking_uri())
    mlflow.create_experiment('exp0')
    mlflow.set_experiment('exp0')
    with mlflow.start_run(run_name=make_run_name()):
`
! The script runs for several epochs before crashing. The epoch at which it crashes changes from run to run

Besides the error in the title at times another error is thrown:
azure.core.exceptions.ServiceResponseError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

NB: when running the script in a debugger that catches the exception, the same line can be run again without producing any error. The type of call that results in the error is unpredictable.

**To Reproduce**
1. set up mlflow experiment and run
2. set up script that periodically logs images, figures and metrics to mlflow
3. run the script

**Expected behavior**
azureml-mlflow should log artifacts metrics etc. to mlflow and azureml studio with no errors.

**Screenshots**
![Screenshot 2023-02-27 133159](https://user-images.githubusercontent.com/8679977/221565833-f688363b-c94c-4592-92b9-31a6c05bb6f8.png)

**Additional context**
Traceback:
File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/andreagpu1/code/Users/user0/exp0/reconstruction/train.py", line 77, in <module>                                                              
    trainer.fit(module,                                                                                                                                                                                          
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 740, in fit                                                                                                
    self._call_and_handle_interrupt(                                                                                                                                                                             
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt                                                                         
    return trainer_fn(*args, **kwargs)                                                                                                                                                                           
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl                                                                                          
    self._run(model, ckpt_path=ckpt_path)                                                                                                                                                                        
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run                                                                                              
    self._dispatch()                                                                                                                                                                                             
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in _dispatch                                                                                         
    self.training_type_plugin.start_training(self)                                                                                                                                                               
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training                                                          
    self._results = trainer.run_stage()                                                                                                                                                                          
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1289, in run_stage                                                                                         
    return self._run_train()                                                                                                                                                                                     
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1319, in _run_train                                                                                        
    self.fit_loop.run()                                                                                                                                                                                          
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run                                                                                                     
    self.advance(*args, **kwargs)                                                                                                                                                                                
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance                                                                                             
    self.epoch_loop.run(data_fetcher)                                                                                                                                                                            
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 146, in run                                                                                                     
    self.on_advance_end()                                                                                                                                                                                        
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 242, in on_advance_end                                                                     
    self._run_validation()                                                                                                                                                                                       
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 337, in _run_validation                                                                    
    self.val_loop.run()                                                                                                                                                                                          
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run                                                                                                     
    self.advance(*args, **kwargs)                                                                                                                                                                                
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)                                                                                                           
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 122, in advance
    output = self._evaluation_step(batch, batch_idx, dataloader_idx)                                                                                                                                             
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 217, in _evaluation_step
    output = self.trainer.accelerator.validation_step(step_kwargs)                                                                                                                                               
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 239, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())                                                                                                                                      
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 219, in validation_step
    return self.model.validation_step(*args, **kwargs)                                                                                                                                                           
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/andreagpu1/code/Users/user0/exp0/reconstruction/model.py", line 91, in validation_step
    self.logger.experiment.log_image(self.logger.run_id, im_a, f"{self.trainer.current_epoch}/val_low_res_{batch_idx}_{i}.png")
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/mlflow/tracking/client.py", line 1424, in log_image
    raise TypeError("Unsupported image object type: '{}'".format(type(image)))                                                                                                                                   
  File "/anaconda/envs/myenv0/lib/python3.9/contextlib.py", line 124, in __exit__                                                                                                                                
    next(self.gen)
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/mlflow/tracking/client.py", line 1129, in _log_artifact_helper
    self.log_artifact(run_id, tmp_path, artifact_dir)
File "/anaconda/envs/myenv0/lib/python3.9/site-packages/mlflow/tracking/client.py", line 1129, in _log_artifact_helper
    self.log_artifact(run_id, tmp_path, artifact_dir)                                                                                                                                                            
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/mlflow/tracking/client.py", line 1064, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)                                                                                                                                        
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 422, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)                                                                                                                                                        
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/azureml/mlflow/_store/artifact/artifact_repo.py", line 65, in log_artifact
    self.artifacts.upload_artifact(local_file, dest_path)                                                                                                                                                        
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/azureml/mlflow/_client/artifact/run_artifact_client.py", line 56, in upload_artifact
    return self._upload_artifact_from_stream(file, remote_path, self._run_id)                                                                                                                                    
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/azureml/mlflow/_client/artifact/run_artifact_client.py", line 117, in _upload_artifact_from_stream
    empty_artifact_res = self._create_empty_artifacts(paths=name, run_id=run_id)                                                                                                                                 
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/azureml/mlflow/_client/artifact/run_artifact_client.py", line 128, in _create_empty_artifacts
    response = self._client.run_artifacts.batch_create_empty_artifacts(                                                                                                                                          
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/azureml/mlflow/_restclient/run_artifact/operations/_run_artifacts_operations.py", line 1116, in batch_create_empty_artifacts
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)                                                                                                                              
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore                                                                                                                                                     
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/azure/core/pipeline/policies/_retry.py", line 467, in send
    raise err
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/azure/core/pipeline/policies/_retry.py", line 445, in send
    response = self.next.send(request)
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/azure/core/pipeline/policies/_authentication.py", line 119, in send
    response = self.next.send(request)
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 103, in send
    self._sender.send(request.http_request, **request.context.options),                                                                                                                                          
  File "/anaconda/envs/myenv0/lib/python3.9/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 361, in send
    raise error
azure.core.exceptions.ServiceResponseError: HTTPSConnectionPool(host='northeurope.api.azureml.ms', port=443): Read timed out. (read timeout=300)

**Comment by kashifkhan** [comment]
Thanks for the feedback @achatrian . We will investigate and get back to you asap. 

cc @azureml-github

**Comment by achatrian** [comment]
Thank you. Yesterday I got a new type of error, a ServiceRequestError from the same script after catching the ServiceResponseErrors and training a model for 200 epochs:
azure.core.exceptions.ServiceRequestError: [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2621)

Here is the full traceback for reference:
Traceback (most recent call last):
  File "/home/cluster_user/user0/Repositories/exp0/exp0/train.py", line 88, in <module>
    trainer.fit(module,
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 603, in fit
    call._call_and_handle_interrupt(
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 645, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1098, in _run
    results = self._run_stage()
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1177, in _run_stage
    self._run_train()
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1200, in _run_train
    self.fit_loop.run()
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.on_advance_end()
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 251, in on_advance_end
    self._run_validation()
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 310, in _run_validation
    self.val_loop.run()
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 137, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 234, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1480, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 390, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/cluster_user/user0/Repositories/exp0/exp0/model.py", line 114, in validation_step
    mlflow.log_figure(pca_plot_figure, f"{self.trainer.current_epoch}/pca_plot_{batch_idx}_{i}.png")
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 917, in log_figure
    MlflowClient().log_figure(run_id, figure, artifact_file)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/mlflow/tracking/client.py", line 1217, in log_figure
    raise TypeError("Unsupported figure object type: '{}'".format(type(figure)))
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/mlflow/tracking/client.py", line 1067, in _log_artifact_helper
    self.log_artifact(run_id, tmp_path, artifact_dir)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/mlflow/tracking/client.py", line 1002, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 439, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/azureml/mlflow/_store/artifact/artifact_repo.py", line 65, in log_artifact
    self.artifacts.upload_file(local_file, dest_path)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/azureml/mlflow/_client/artifact/run_artifact_client.py", line 64, in upload_file
    empty_artifact_res = self._create_empty_artifacts(paths=artifact_path, run_id=self._run_id)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/azureml/mlflow/_client/artifact/run_artifact_client.py", line 146, in _create_empty_artifacts
    response = self._client.run_artifacts.batch_create_empty_artifacts(
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/azureml/mlflow/_restclient/run_artifact/operations/_run_artifacts_operations.py", line 1116, in batch_create_empty_artifacts
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/azure/core/pipeline/policies/_redirect.py", line 153, in send
    response = self.next.send(request)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/azure/core/pipeline/policies/_retry.py", line 467, in send
    raise err
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/azure/core/pipeline/policies/_retry.py", line 445, in send
    response = self.next.send(request)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/azure/core/pipeline/policies/_authentication.py", line 113, in send
    response = self.next.send(request)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 103, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 360, in send
    raise error
azure.core.exceptions.ServiceRequestError: [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2621)

**Comment by tomas-gajarsky** [comment]
Try increasing the timeout by changing the values of `MLFLOW_ARTIFACT_UPLOAD_DOWNLOAD_TIMEOUT` and/or `MLFLOW_HTTP_REQUEST_TIMEOUT` environment variables.

**Comment by tomas-gajarsky** [comment]
I am also getting the ConnectionResetError in the same context of logging an artifact using MLflow.
`azure.core.exceptions.ServiceResponseError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`

**Comment by yawnzh** [comment]
Same issue here. I'm trying to log a dictionary as json, got ServiceResponseError. The json file is around 40~60KB. Increase AZUREML_ARTIFACTS_DEFAULT_VALUE to 3000 doesn't help.

**Comment by tomas-gajarsky** [comment]
**Workaround**

Retrying to log the artifact with MLflow helps me with this issue and serves as a workaround, but it isn't a proper solution. That should probably still come from the Azure employees. 

Simple example of retrying to log an image:
```
import time, logging, mlflow

max_retries = 5
retry_delay = 2

retries = 0
while retries < max_retries:
    try:
        ml_flow.log_image(image, "test.png")
        break
    except Exception as e:
        logging.warning(
            f"Failed to log image to MLflow. Retrying in {retry_delay} seconds. Error: {e}"
        )
        time.sleep(retry_delay)
        retries += 1
```

**Comment by achatrian** [comment]
I got a new error on the server side:
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'InternalServerError'
Content: {
  "error": {
    "code": "ServiceError",
    "severity": null,
    "message": "InternalServerError",
    "messageFormat": null,
    "messageParameters": null,
    "referenceCode": null,
    "detailsUri": null,
    "target": null,
    "details": [],
    "innerError": null,
    "debugInfo": null,
    "additionalInfo": null
  },
  "correlation": {
    "operation": "a7ee9b26df9a84caa0e389f539393316",
    "request": "4f1fe44dd73df5ec"
  },
  "environment": "northeurope",
  "location": "northeurope",
  "time": "2023-03-14T18:57:55.0609117+00:00",
  "componentName": "run-history"
}

I hope these get attention at some point

Here is the full traceback:
Traceback (most recent call last):
  File "/home/cluster_user/user0/Repositories/exp1/./train.py", line 91, in <module>
    trainer.fit(module,
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 603, in fit
    call._call_and_handle_interrupt(
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 645, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1098, in _run
    results = self._run_stage()
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1177, in _run_stage
    self._run_train()
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1200, in _run_train
    self.fit_loop.run()
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.on_advance_end()
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 251, in on_advance_end
    self._run_validation()
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 310, in _run_validation
    self.val_loop.run()
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 137, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 234, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1480, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 390, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/cluster_user/user0/Repositories/exp1/model.py", line 105, in validation_step
    mlflow.log_image(im, f"{self.trainer.current_epoch}/val_input_{self.epoch_batch:.2f}_{batch_idx}_{i}.png")
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 980, in log_image
    MlflowClient().log_image(run_id, image, artifact_file)
File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/mlflow/tracking/client.py", line 1361, in log_image
    raise TypeError("Unsupported image object type: '{}'".format(type(image)))
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/mlflow/tracking/client.py", line 1067, in _log_artifact_helper
    self.log_artifact(run_id, tmp_path, artifact_dir)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/mlflow/tracking/client.py", line 1002, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 439, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/azureml/mlflow/_store/artifact/artifact_repo.py", line 65, in log_artifact
    self.artifacts.upload_file(local_file, dest_path)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/azureml/mlflow/_client/artifact/run_artifact_client.py", line 64, in upload_file
    empty_artifact_res = self._create_empty_artifacts(paths=artifact_path, run_id=self._run_id)
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/azureml/mlflow/_client/artifact/run_artifact_client.py", line 146, in _create_empty_artifacts
    response = self._client.run_artifacts.batch_create_empty_artifacts(
  File "/home/cluster_user/user0/miniconda3/envs/pyenv3.9/lib/python3.9/site-packages/azureml/mlflow/_restclient/run_artifact/operations/_run_artifacts_operations.py", line 1122, in batch_create_empty_artifacts
    raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'InternalServerError'
Content: {
  "error": {
    "code": "ServiceError",
    "severity": null,
    "message": "InternalServerError",
    "messageFormat": null,
    "messageParameters": null,
    "referenceCode": null,
    "detailsUri": null,
    "target": null,
    "details": [],
    "innerError": null,
    "debugInfo": null,
    "additionalInfo": null
  },
  "correlation": {
    "operation": "a7ee9b26df9a84caa0e389f539393316",
    "request": "4f1fe44dd73df5ec"
  },
  "environment": "northeurope",
  "location": "northeurope",
  "time": "2023-03-14T18:57:55.0609117+00:00",
  "componentName": "run-history"
}

**Comment by singankit** [comment]
@achatrian @tomas-gajarsky Thanks for the sharing the details. Fix is in progress and should be out in next release. Will update once the release is out.

**Comment by xiangyan99** [comment]
@singankit is the fix released?

**Comment by RobbertVKH** [comment]
> @achatrian @tomas-gajarsky Thanks for the sharing the details. Fix is in progress and should be out in next release. Will update once the release is out.

Any news on when this update can be expected to be released?
