### ISSUE TITLE
docker container with python azure-storage-blob sdk cannot connect to azure storage.

### ISSUE THREAD

**Issue by Srfigie** [Azure/azure-sdk-for-python#29522]
- **azure-blob-storage**: 
- **12.12.0**: 
- **Windows 11 (running ubuntu WSL2)**:
- **python 3.8**: 

**Describe the bug**
In a project where I am containerizing some of our organization's python code, I am running into an issue whenever the python scripts attempt to connect to azure storage, I am faced with this error.
````  
. . .
File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 376, in send
    raise error
azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPSConnection object at 0x7f1354bd0eb0>: Failed to establish a new connection: [Errno -2] Name or service not known
````
An interesting fact, is we also have a .net console application running in the same container which uses the .net azure storage SDK and that application is able to connect to Azure storage without issue using the same connection string.  The issue only occurs in the python code and only when running in the container.  Running the code locally outside of the docker container does not produce this issue.

I was able to reproduce this issue in a separate docker container using only the azure storage library details below.

**To Reproduce**
1.  Create a directory structure to hold a dockerfile and python script code
<img width="187" alt="image" src="https://user-images.githubusercontent.com/5711826/227030424-6f978c4f-5812-463d-9abd-c7c41157ba94.png">

2.  Create a python script (py-console-az-storage/apps/main.py) with the following code
```` python
from azure.storage.blob import BlobServiceClient
import json
import os

def get_blob(container: str, blob:str):
    global blobServiceClient

    containerClient = blobServiceClient.get_container_client(container)
    blobstr = containerClient.download_blob(blob).readall()
    
    return json.loads(blobstr)

blobServiceClient: BlobServiceClient = BlobServiceClient.from_connection_string(os.getenv("AZURE_CONNECTION_STRING"))
container: str = os.getenv("container")
blob: str = os.getenv("blob")

print("Downloading BLOB method")
print(get_blob(container, blob))
````

3. Create a Dockerfile (py-console-az-storage/Dockerfile) to containerize the script
```` dockerfile
FROM ubuntu:20.04

RUN mkdir -p /root/code/
WORKDIR /root/

RUN DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y python3.8 python3.8-dev python3.8-venv python3.8-distutils 

COPY . /root/code/

RUN echo "Setting Up Python environment.."
RUN python3.8 -m venv /root/env
ENV PATH=/root/env/bin:$PATH
RUN pip install pip==21.3.1 

RUN pip install --no-cache-dir --upgrade -r /root/code/requirements.txt
````

4.  Create a requirements.txt file (py-console-az-storage/requirements.txt)
````
azure-storage-blob==12.12.0
````

5.  Build the Dockerfile (navigate to the py-console-az-storage root folder) by running
`docker image build --file ./Dockerfile --tag py-storage-console:1`

6.  Create an environment file with the following settings (py-console-az-storage/test.env)
```` env
AZURE_CONNECTION_STRING='[ Insert your storage account connection string here]'
container='[Name of a container that exists]'
blob='[path to json file within that contianer]'
````

7. Run the Docker container using this environment file
`docker run -it --env-file ./test.env --entrypoint "python /root/code/app/main.py" py-storage-console:1 `

8.  You will see thethe following output
````
PS C:\code\aks-volume-mount-example\apps\py-console-az-storage> docker run -it --env-file ./test.env py-storage-console:1
root@5891a613e549:~# python /root/code/app/main.py
Downloading BLOB method 1:
Traceback (most recent call last):
  File "/root/code/app/main.py", line 33, in <module>
    print(get_blob(container, blob))
  File "/root/code/app/main.py", line 9, in get_blob
    blobstr = containerClient.download_blob(blob).readall()
  File "/root/env/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/root/env/lib/python3.8/site-packages/azure/storage/blob/_container_client.py", line 1151, in download_blob
    return blob_client.download_blob(offset=offset, length=length, **kwargs)
  File "/root/env/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/root/env/lib/python3.8/site-packages/azure/storage/blob/_blob_client.py", line 868, in download_blob
    return StorageStreamDownloader(**options)
  File "/root/env/lib/python3.8/site-packages/azure/storage/blob/_download.py", line 355, in __init__
    self._response = self._initial_request()
  File "/root/env/lib/python3.8/site-packages/azure/storage/blob/_download.py", line 392, in _initial_request
    location_mode, response = self._clients.blob.download(
  File "/root/env/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/root/env/lib/python3.8/site-packages/azure/storage/blob/_generated/operations/_blob_operations.py", line 1669, in download
    pipeline_response = self._client._pipeline.run(  # pylint: disable=protected-access
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 205, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 160, in send
    response = self.next.send(request)
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/root/env/lib/python3.8/site-packages/azure/storage/blob/_shared/policies.py", line 543, in send
    raise err
  File "/root/env/lib/python3.8/site-packages/azure/storage/blob/_shared/policies.py", line 517, in send
    response = self.next.send(request)
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/root/env/lib/python3.8/site-packages/azure/storage/blob/_shared/policies.py", line 313, in send
    response = self.next.send(request)
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 100, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/root/env/lib/python3.8/site-packages/azure/storage/blob/_shared/base_client.py", line 333, in send
    return self._transport.send(request, **kwargs)
  File "/root/env/lib/python3.8/site-packages/azure/storage/blob/_shared/base_client.py", line 333, in send
    return self._transport.send(request, **kwargs)
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 376, in send
    raise error
azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPSConnection object at 0x7f1354bd0eb0>: Failed to establish a new connection: [Errno -2] Name or service not known
````
**Expected behavior**
This error should not be happening as the connection string, storage container name and blob path are valid.  The code should download the file and output it to the terminal like it does when running this script locally outside of the docker image.

**Additional context**
I've seen other users having similar issues on this forum but I have not found a working solution.

**Comment by jalauzon-msft** [comment]
@lmazuel/@xiangyan99 do we have any general advice for getting our libraries to work in Docker containers? We get a lot of issues like this one where folks are having SSL cert issues within Docker containers. I don't think this would be specific to Storage and is more likely related to our use of `requests`.

**Comment by jalauzon-msft** [comment]
Hi @Srfigie could you please try what Xiang suggested above? Or something similar. Ultimately this does look like a Docker configuration/network problem since you are not able to resolve the hostname.

**Comment by Srfigie** [comment]
Hi @jalauzon-msft @xiangyan99   The suggested configuration is for Ubuntu.  I am running Docker on Windows, I'm not sure I have this set correctly in my daemon config

here is my daemon.json
```` json
{
	"builder": { "gc": { "defaultKeepStorage": "20GB", "enabled": true } },
	"experimental": false,
	"features": { "buildkit": true },
	"dns" : ["8.8.8.8", "8.8.4.4", "10.252.252.252", "10.253.253.253"]
}
````

One thing that doesn't make sense to me, as noted in the issue description, we also have a .net core application running in this same container, and that application uses the .net storage SDK and is able to connect to the same storage account without issue.  Why is it only when trying to connect with the python storage library in this container I see this issue?

**Comment by xiangyan99** [comment]
@Srfigie A possible explanation that .net app worked fine is it might have default DNS settings and if there is no DNS found, it uses a default one (I am not 100% sure). 

Does configuring DNS works? Another try could be using IP instead of DNS name to validate the hypothesis (it fails due to the DNS failure).

**Comment by xiangyan99** [comment]
Did using IP address directly work?

I want to narrow down the issue by DNS failure or something else. :)

**Comment by Srfigie** [comment]
I'm not sure what you mean by direct IP addresses?  Is this something to add to my docker daemon config? Or do you mean try to access the azure storage account from within the container via IP instead of the [AccountName].blob.core.windows.net domain?

Could you please elaborate?

**Comment by xiangyan99** [comment]
@jalauzon-msft instead of using [AccountName].blob.core.windows.net, is there a way we can use IP directly and skip the DNS resolution?

**Comment by jalauzon-msft** [comment]
@xiangyan99 / @Srfigie you may be able to use the direct IP address, but it is probably dynamic and may change. Probably ok to try temporarily though. You can use `nslookup [AccountName].blob.core.windows.net` (or similar) to get the IP address.

**Comment by Srfigie** [comment]
@xiangyan99 @jalauzon-msft 
I was able to verify the DNS in the container by another means..

So interestingly enough, when I create an integrated terminal session in this container, I am able to download my test BLOB directly via URL ex `https://[AccountName].blob.core.windows.net/container/blob.json?SASKEY`  using wget.   It is only when I run the python script which uses the storage library in this container where the connection fails.  This would lead me to believe my container can correctly resolve the DNS name for the storage account, EXCEPT when the python storage library is trying to connect to the account.

Based on this finding would this indicate an issue with the library running in this container and not the container network setup?
This also would explain why the .net application running in the container does not have an issue connecting to the storage account.

**Comment by xiangyan99** [comment]
To make sure I understand correctly, you mean if you run the Python script in interactive mode of the docker instance, you still fail to connect to Azure storage?

Thanks.

**Comment by Srfigie** [comment]
That is correct.  The container can connect to the storage account via wget, and with the .net core application, but not with the python script.

**Comment by xiangyan99** [comment]
This is interesting.

Could you add more logging information by adding

import logging
logging.basicConfig(filename='<your log file>', level=logging.DEBUG)

?

**Comment by Srfigie** [comment]
@xiangyan99  Yes, with the added logging see the output below
(Note I redacted the storage account name)

```` bash
PS C:\code\aks-volume-mount-example\apps\py-console-az-storage> docker run -it --env-file ./test.env py-storage-console:2
Downloading BLOB method
INFO:azure.core.pipeline.policies.http_logging_policy:Request URL: 'https://REDACTED.blob.core.windows.net'/%27video-data%27/%27a2bd8220-6aef-4ca3-bf8e-4e5d62be506f/datasetuploadmanifest.json%27'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.12.0 Python/3.8.16 (Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.2.5)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '23dcc4b2-c9cf-11ed-b38f-0242ac110005'
    'Authorization': 'REDACTED'
No body was attached to the request
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): REDACTED.blob.core.windows.net':443
INFO:azure.core.pipeline.policies.http_logging_policy:Request URL: 'https://REDACTED.blob.core.windows.net'/%27video-data%27/%27a2bd8220-6aef-4ca3-bf8e-4e5d62be506f/datasetuploadmanifest.json%27'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.12.0 Python/3.8.16 (Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.2.5)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '2fb26c10-c9cf-11ed-b38f-0242ac110005'
    'Authorization': 'REDACTED'
No body was attached to the request
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (2): REDACTED.blob.core.windows.net':443
INFO:azure.core.pipeline.policies.http_logging_policy:Request URL: 'https://REDACTED.blob.core.windows.net'/%27video-data%27/%27a2bd8220-6aef-4ca3-bf8e-4e5d62be506f/datasetuploadmanifest.json%27'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.12.0 Python/3.8.16 (Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.2.5)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '3dd6a43c-c9cf-11ed-b38f-0242ac110005'
    'Authorization': 'REDACTED'
No body was attached to the request
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (3): REDACTED.blob.core.windows.net':443
INFO:azure.core.pipeline.policies.http_logging_policy:Request URL: 'https://REDACTED.blob.core.windows.net'/%27video-data%27/%27a2bd8220-6aef-4ca3-bf8e-4e5d62be506f/datasetuploadmanifest.json%27'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.12.0 Python/3.8.16 (Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.2.5)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '554dcdca-c9cf-11ed-b38f-0242ac110005'
    'Authorization': 'REDACTED'
No body was attached to the request
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (4): REDACTED.blob.core.windows.net':443
Traceback (most recent call last):
  File "/root/code/app/main.py", line 35, in <module>
    print(get_blob(container, blob))
  File "/root/code/app/main.py", line 11, in get_blob
    blobstr = containerClient.download_blob(blob).readall()
  File "/root/env/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/root/env/lib/python3.8/site-packages/azure/storage/blob/_container_client.py", line 1151, in download_blob
    return blob_client.download_blob(offset=offset, length=length, **kwargs)
  File "/root/env/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/root/env/lib/python3.8/site-packages/azure/storage/blob/_blob_client.py", line 868, in download_blob
    return StorageStreamDownloader(**options)
  File "/root/env/lib/python3.8/site-packages/azure/storage/blob/_download.py", line 355, in __init__
    self._response = self._initial_request()
  File "/root/env/lib/python3.8/site-packages/azure/storage/blob/_download.py", line 392, in _initial_request
    location_mode, response = self._clients.blob.download(
  File "/root/env/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/root/env/lib/python3.8/site-packages/azure/storage/blob/_generated/operations/_blob_operations.py", line 1669, in download
    pipeline_response = self._client._pipeline.run(  # pylint: disable=protected-access
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 205, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 160, in send
    response = self.next.send(request)
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/root/env/lib/python3.8/site-packages/azure/storage/blob/_shared/policies.py", line 543, in send
    raise err
  File "/root/env/lib/python3.8/site-packages/azure/storage/blob/_shared/policies.py", line 517, in send
    response = self.next.send(request)
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/root/env/lib/python3.8/site-packages/azure/storage/blob/_shared/policies.py", line 313, in send
    response = self.next.send(request)
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 100, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/root/env/lib/python3.8/site-packages/azure/storage/blob/_shared/base_client.py", line 333, in send
    return self._transport.send(request, **kwargs)
  File "/root/env/lib/python3.8/site-packages/azure/storage/blob/_shared/base_client.py", line 333, in send
    return self._transport.send(request, **kwargs)
  File "/root/env/lib/python3.8/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 376, in send
    raise error
azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPSConnection object at 0x7f41f8c5e670>: Failed to establish a new connection: [Errno -2] Name or service not known
````

**Comment by xiangyan99** [comment]
Do you use/configure proxies?

**Comment by Srfigie** [comment]
No. I have not configured any proxies, I have a very standard network setup on my machine.

**Comment by xiangyan99** [comment]
Btw, did you try use IP directly in Python script? Can you share the results?

We wanted to use it to validate the hypothesis that the failure was due to the DNS name resolution.

**Comment by Srfigie** [comment]
I'm not sure how that would be accomplished with the SDK,  the connection string format is `DefaultEndpointsProtocol=https;AccountName=[REDACTED];AccountKey=[REDACTED];EndpointSuffix=core.windows.net`
How would I add the the IP instead of the account name and storage domain in this string format?

**Comment by Srfigie** [comment]
@xiangyan99 
Another experiment I tried to further verify that the script is able to connect to the storage account via the domain name, is I imported the requests library and downloaded a json file from the storage account with a fully qualified URL with a SAS token.

You can see below in my script, the call after the lines "Testing web connection" with the requests library is successful and downloads the blob from storage.

When I try to connect to the storage account with the python storage client library I get the error previously mentioned at the beginning of this thread. 

This further narrows down the issue is happening in the library and only when running in this Docker container.

```` python
from azure.storage.blob import BlobServiceClient
import json
import os
import logging
logging.basicConfig(filename='', level=logging.DEBUG)
import requests

def get_blob(container: str, blob:str):
    global blobServiceClient

    containerClient = blobServiceClient.get_container_client(container)
    blobstr = containerClient.download_blob(blob).readall()
    
    return json.loads(blobstr)

def get_blob_method2(container: str, blob:str):
    global blobServiceClient
    manifest_blob_client = (
        blobServiceClient.get_blob_client(
            container=container, 
            blob=blob
        )
    )

    json_manifest = json.loads(
        manifest_blob_client.download_blob(connection_verify=False).readall()
    )

    return json_manifest

blobServiceClient: BlobServiceClient = BlobServiceClient.from_connection_string(os.getenv("AZURE_CONNECTION_STRING"))
container: str = os.getenv("container")
blob: str = os.getenv("blob")

print("testing web connection...")
url = os.getenv("BLOB_PATH_WITH_SAS")
r = requests.get(url, allow_redirects=True)
print(r.json())
print("                                                                          ")
print("                                                                          ")
print("==========================================================================")
print("                                                                          ")
print("                                                                          ")
print("Downloading BLOB..")
print(get_blob(container, blob))
````

**Comment by xiangyan99** [comment]
@Srfigie Thanks for the investigation. This is very helpful.

@jalauzon-msft I think next step we can try is to disable pipeline policies and only keep transport. Could you give some snippets how we can achieve this in Storage SDK?

Thanks.

**Comment by jalauzon-msft** [comment]
@xiangyan99, I'm not actually sure how we could do this? Is there is a way to do this through keyword configuration? Also, we probably need certain policies for the request to actually work.

**Comment by xiangyan99** [comment]
If storage does not change the default behavior of azure-core, we can specify policies=[non-None list] to stop pipeline from creating the default policies. https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md#pipeline-client-configurations

I guess we can only have storage-auth policy?

**Comment by jalauzon-msft** [comment]
@xiangyan99, not sure Storage supports that type of configuration? It seems we only support adding additional policies.

https://github.com/Azure/azure-sdk-for-python/blob/bc99ec81288e222de8837fbf1e83975d53d7e456/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client.py#L237-L256

**Comment by xiangyan99** [comment]
I see you honor "_pipeline" parameter. Can user create a pipeline without policy/w/ only auth policy? @jalauzon-msft

**Comment by Srfigie** [comment]
I figured out what was going on..  In my env file, I have the values formatted like this

```` env
AZURE_CONNECTION_STRING='[ Insert your storage account connection string here]'
container='[Name of a container that exists]'
blob='[path to json file within that container]'
````
If I remove the single quotes from each environment variable the connection works.  I did not realize having these values encapsulated in quote marks passes the literal value of the quote character as the variable's value.

Removing the quotes works when running the container with an environment file.
````` env
AZURE_CONNECTION_STRING=[ Insert your storage account connection string here]
container=[Name of a container that exists]
blob=[path to json file within that container]
````

@xiangyan99 @jalauzon-msft Thank you for your assistance in troubleshooting this issue with me
