### ISSUE TITLE
Azure Key Vault Connectivity issues

### ISSUE THREAD

**Issue by dipesh747** [Azure/azure-sdk-for-python#29650]
I am connecting to Azure Key Vault locally & on a web app in python. The webapp connectivity is via Managed ID and it can pull secrets. The local connectivity is via service principal (and I have tried interactive browser with the same result) and this is unable to fetch the secrets and just hangs. If I cancel the process I get the stacktrace.

OS: 
Windows 10 using WSL 2 Ubuntu 20.04 
Python 3.8.10 (
[GCC 9.4.0] on linux

Relevant versioning: 
azure-common           1.1.28     
azure-core             1.26.3     
azure-identity         1.12.0     
azure-keyvault-secrets 4.6.0   
Code: 

import os
from azure.keyvault.secrets import SecretClient
from azure.identity import DefaultAzureCredential
from dotenv import load_dotenv
import logging
import sys
logger = logging.getLogger('azure.identity')
logger.setLevel(logging.INFO)
handler = logging.StreamHandler(stream=sys.stdout)
formatter = logging.Formatter('[%(levelname)s %(name)s] %(message)s')
handler.setFormatter(formatter)
logger.addHandler(handler)

load_dotenv()

"""this loads:
AKV_NAME
AZURE_TENANT_ID
AZURE_CLIENT_ID
AZURE_CLIENT_SECRET""" 

akv_name = os.getenv('AKV_NAME')

KVUri = f"https://{akv_name}.vault.azure.net"

credential = DefaultAzureCredential()

client = SecretClient(vault_url=KVUri, credential=credential)
test = client.get_secret('testsecret').value

[INFO azure.identity._credentials.managed_identity] ManagedIdentityCredential will use IMDS
[INFO azure.identity._credentials.chained] DefaultAzureCredential acquired a token from EnvironmentCredential
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/VSO/code/kapstream/Automated_Hedging_Solution/env/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/mnt/c/VSO/code/kapstream/Automated_Hedging_Solution/env/lib/python3.8/site-packages/azure/keyvault/secrets/_client.py", line 72, in get_secret
    bundle = self._client.get_secret(
  File "/mnt/c/VSO/code/kapstream/Automated_Hedging_Solution/env/lib/python3.8/site-packages/azure/keyvault/secrets/_generated/_operations_mixin.py", line 1574, in get_secret
    return mixin_instance.get_secret(vault_base_url, secret_name, secret_version, **kwargs)
  File "/mnt/c/VSO/code/kapstream/Automated_Hedging_Solution/env/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/mnt/c/VSO/code/kapstream/Automated_Hedging_Solution/env/lib/python3.8/site-packages/azure/keyvault/secrets/_generated/v7_3/operations/_key_vault_client_operations.py", line 694, in get_secret
    pipeline_response = self._client._pipeline.run(  # pylint: disable=protected-access
  File "/mnt/c/VSO/code/kapstream/Automated_Hedging_Solution/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 205, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/mnt/c/VSO/code/kapstream/Automated_Hedging_Solution/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/mnt/c/VSO/code/kapstream/Automated_Hedging_Solution/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/mnt/c/VSO/code/kapstream/Automated_Hedging_Solution/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/mnt/c/VSO/code/kapstream/Automated_Hedging_Solution/env/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 160, in send
    response = self.next.send(request)
  File "/mnt/c/VSO/code/kapstream/Automated_Hedging_Solution/env/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry.py", line 474, in send
    response = self.next.send(request)
  File "/mnt/c/VSO/code/kapstream/Automated_Hedging_Solution/env/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 117, in send
    response = self.next.send(request)
  File "/mnt/c/VSO/code/kapstream/Automated_Hedging_Solution/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/mnt/c/VSO/code/kapstream/Automated_Hedging_Solution/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/mnt/c/VSO/code/kapstream/Automated_Hedging_Solution/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/mnt/c/VSO/code/kapstream/Automated_Hedging_Solution/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 100, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/mnt/c/VSO/code/kapstream/Automated_Hedging_Solution/env/lib/python3.8/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 338, in send
    response = self.session.request(  # type: ignore
  File "/mnt/c/VSO/code/kapstream/Automated_Hedging_Solution/env/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/c/VSO/code/kapstream/Automated_Hedging_Solution/env/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/c/VSO/code/kapstream/Automated_Hedging_Solution/env/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/mnt/c/VSO/code/kapstream/Automated_Hedging_Solution/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/mnt/c/VSO/code/kapstream/Automated_Hedging_Solution/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/mnt/c/VSO/code/kapstream/Automated_Hedging_Solution/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

**Comment by dipesh747** [comment]
It seems WSL has been blocking the AZ login. When I moved to a different os this worked ok.
