### ISSUE TITLE
Issues with authentication in Azure-containerregistry 

### ISSUE THREAD

**Issue by Captain-0415** [Azure/azure-sdk-for-python#29665]
- **Package Name**: azure-containerregistry
- **Package Version**: 1.0.0
- **Operating System**:Ubuntu
- **Python Version**: 3.8

**Describe the bug**
unable to get data for azure container registry because AzureIdentityCredentialAdapter has no attribute 'get_token()' in "_exchange_client.py"

**To Reproduce**
1. create a python script and using some credentials to get a client object.
2. Iterate over to look for repositories.
3. Iterate over repositories to look for tags.

**Expected behavior**
To get the repo name , tag count, manifest count and other data associated.

**Screenshots**
Traceback (most recent call last):
  File "azure_container_registry.py", line 16, in <module>
    for repository_name in client.list_repository_names():
  File "myproject/venv_py3/lib/python3.8/site-packages/azure/core/paging.py", line 132, in __next__
    return next(self._page_iterator)
  File "myproject/cloudpoint/venv_py3/lib/python3.8/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "myproject/venv_py3/lib/python3.8/site-packages/azure/containerregistry/_container_registry_client.py", li
    pipeline_response = self._client._client._pipeline.run(  # pylint: disable=protected-access
  File "myproject/venv_py3/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "myproject/venv_py3/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "myproject/venv_py3/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "myproject//venv_py3/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "myproject/venv_py3/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 160, in s
    response = self.next.send(request)
  File "myproject/venv_py3/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry.py", line 484, in send
    response = self.next.send(request)
  File "myproject/venv_py3/lib/python3.8/site-packages/azure/containerregistry/_authentication_policy.py", line 5
    if challenge and self.on_challenge(request, response, challenge):
  File "myproject/venv_py3/lib/python3.8/site-packages/azure/containerregistry/_authentication_policy.py", line 7
    access_token = self._exchange_client.get_acr_access_token(challenge)
  File "myproject/venv_py3/lib/python3.8/site-packages/azure/containerregistry/_exchange_client.py", line 62, in
    refresh_token = self.get_refresh_token(parsed_challenge["service"], **kwargs)
  File "myproject/venv_py3/lib/python3.8/site-packages/azure/containerregistry/_exchange_client.py", line 70, in
    self._refresh_token = self.exchange_aad_token_for_refresh_token(service, **kwargs)
  File "myproject/venv_py3/lib/python3.8/site-packages/azure/containerregistry/_exchange_client.py", line 79, in
    access_token=self._credential.get_token(*self.credential_scopes).token,

**Additional context**
Method used to get credentials:
```
credentials= ClientSecretCredential(
tenant_id='example',
client_id='example',
client_secret='example'
)
credentials=AzureIdentityCredentialAdapter(credentials)
```

**Comment by pvaneck** [comment]
Hey @Captain-0415, where is the `AzureIdentityCredentialAdapter` from? I'm not familiar with it, but you should be able to pass in the ClientSecretCredential client directly to the `ContainerRegistryClient` without the use of an adapter.

```python
credential = ClientSecretCredential(
    tenant_id='example',
    client_id='example',
    client_secret='example'
)

client = ContainerRegistryClient(endpoint, credential)
```

Does something like the above work?

**Comment by Captain-0415** [comment]
Actually I am trying to use a wrapper for credentials because then I was getting issue:
```AttributeError: 'ClientSecretCredential' object has no attribute 'signed_session'```

But in this case, it worked like you suggested, but still for other  scripts I have to use that Adapter

**Comment by devfinwiz** [comment]
I have a similar issue actually. 
AttributeError: 'ClientSecretCredential' object has no attribute 'signed_session'. I got rid of this by using the AzureIdentityCredentialAdapter to wrap the azure credentials. I found this solution in one these issues here itself. 
https://github.com/jongio/azidext/blob/master/python/azure_identity_credential_adapter.py.

**Comment by xiangyan99** [comment]
@Captain-0415 @devfinwiz 

If you see errors like

AttributeError: 'ClientSecretCredential' object has no attribute 'signed_session'.

This usually implies you were using a track 1 library which was not compatible with azure-identity.

Here is the guideline for those scenarios. https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/migration_guide.md
