### ISSUE TITLE
Service Bus SDK fails when run inside Azure Container Instances

### ISSUE THREAD

**Issue by khilscher** [Azure/azure-sdk-for-python#2979]
Using the latest Service Bus Python SDK inside a Windows docker container to send and receive messages from a Service Bus queue works fine. But take the exact same docker container and host it in Azure Container Instances (ACI) and the following exception occurs:

```
C:\Users\kehilsch\Source\Repos\PythonServiceBus>az container logs --resource-group pythonservicebus --name pythonservicebus
Sending message... Message 0
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Python\lib\site-packages\urllib3\util\connection.py", line 56, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Python\lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "C:\Python\lib\site-packages\urllib3\connection.py", line 314, in connect
    conn = self._new_conn()
  File "C:\Python\lib\site-packages\urllib3\connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000001CD2D41BDA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='khtest1.servicebus.windows.net', port=443): Max retries exceeded with url: /khqueue1/messages (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001CD2D41BDA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\solver\sender.py", line 17, in <module>
    bus_service.send_queue_message('khqueue1', msg)
  File "C:\Python\lib\site-packages\azure\servicebus\servicebusservice.py", line 890, in send_queue_message
    self._perform_request(request)
  File "C:\Python\lib\site-packages\azure\servicebus\servicebusservice.py", line 1228, in _perform_request
    resp = self._filter(request)
  File "C:\Python\lib\site-packages\azure\servicebus\_http\httpclient.py", line 181, in perform_request
    self.send_request_body(connection, request.body)
  File "C:\Python\lib\site-packages\azure\servicebus\_http\httpclient.py", line 143, in send_request_body
    connection.send(request_body)
  File "C:\Python\lib\site-packages\azure\servicebus\_http\requestsclient.py", line 81, in send
    self.response = self.session.request(self.method, self.uri, data=request_body, headers=self.headers, timeout=self.timeout)
  File "C:\Python\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python\lib\site-packages\requests\adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='khtest1.servicebus.windows.net', port=443): Max retries exceeded with url: /khqueue1/messages (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001CD2D41BDA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
```

I tried creating the ACI with and without a public IP and DNS label, but it did not resolve the exception. 

https://docs.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest#az-container-create

Here's the sending code...

```
from azure.servicebus import ServiceBusService, Message, Queue
import time

if __name__ == '__main__':

    bus_service = ServiceBusService(
        service_namespace='mytestnamespace',
        shared_access_key_name='RootManageSharedAccessKey',
        shared_access_key_value='blahblahfakekey')

    i = 0

    while True:
        message = f'Message {i}'
        print(f'Sending message... {message}')
        msg = Message(message)
        bus_service.send_queue_message('khqueue1', msg)
        i += 1
        time.sleep(5)
```

**Comment by khilscher** [comment]
I decided to not use the Service Bus Python SDK and simply go against the Service Bus HTTP REST API. Same problem, same error. Seems to be pointing to some issue between urllib and ACI...perhaps because there are some gateways in front of ACI. 

```
Sending message... Message 0
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Python\lib\site-packages\urllib3\util\connection.py", line 56, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Python\lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "C:\Python\lib\site-packages\urllib3\connection.py", line 314, in connect
    conn = self._new_conn()
  File "C:\Python\lib\site-packages\urllib3\connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0000016EE7732A90>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='somename.servicebus.windows.net', port=443): Max retries exceeded with url: /somequeuename/messages?timeout=60%20HTTP/1.1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000016EE7732A90>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\solver\http_sender.py", line 45, in <module>
    r = send_message(sb_name, queue_name, sas_name, sas_value, message)
  File "c:\solver\http_sender.py", line 30, in send_message
    r = requests.post(url, headers = headers, data = message)
  File "C:\Python\lib\site-packages\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python\lib\site-packages\requests\adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='somename.servicebus.windows.net', port=443): Max retries exceeded with url: /somequeuename/messages?timeout=60%20HTTP/1.1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000016EE7732A90>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed',))
```

Here's the code I used:

```
import time
#import urllib
import urllib.parse
import requests
import hmac
import hashlib
import base64
import time

def send_message(sb_name, queue_name, sas_name, sas_value, message):
    """
    Send a message to Azure Service Bus 
    queue using the REST API.
    """
    
    #Generate the SAS token
    uri = urllib.parse.quote_plus('https://{}.servicebus.windows.net/{}' \
                                  .format(sb_name, queue_name))
    sas = sas_value.encode('utf-8')
    expiry = str(int(time.time() + 10000))
    string_to_sign = (uri + '\n' + expiry).encode('utf-8')
    signed_hmac_sha256 = hmac.HMAC(sas, string_to_sign, hashlib.sha256)
    signature = urllib.parse.quote(base64.b64encode(signed_hmac_sha256.digest()))
    sas='SharedAccessSignature sr={}&sig={}&se={}&skn={}'.format(uri, signature, expiry, sas_name)

    #Create and send HTTP POST message
    url = f'https://{sb_name}.servicebus.windows.net/{queue_name}' + '/messages?timeout=60 HTTP/1.1'
    headers={'Authorization': sas, 'Content-Type': 'application/atom+xml;type=entry;charset=utf-8'}
    message=message
    r = requests.post(url, headers = headers, data = message)
    return r

if __name__ == '__main__':

    sb_name='somename'
    queue_name='somequeuename'
    sas_name='RootManageSharedAccessKey'
    sas_value='somefakekey'
    
    i = 0

    while True:
        message = f'Message {i}'
        print(f'Sending message... {message}')
        r = send_message(sb_name, queue_name, sas_name, sas_value, message)
        print(r.status_code, r.reason)
        i += 1
        time.sleep(5)
```

**Comment by khilscher** [comment]
Thanks to @lmazuel I was connected to the ACI team. They have confirmed that with Windows containers on ACI, ACI networking is not immediately available when ACI starts the container. I tested putting a sleep timer ```time.sleep(60)``` in *before* connecting to Service Bus and that resolved the issue.
