### ISSUE TITLE
Facing Error in Azure cognitiveservices speech

### ISSUE THREAD

**Issue by shaheer-haider** [Azure/azure-sdk-for-python#29805]
- **Package Name**: azure-cognitiveservices-speech
- **Package Version**: 1.21.0
- **Operating System**:Ubuntu(with KDE) 22.04
- **Python Version**: 3.10.6

**Description**
It is working fine on every machine I have setup before but it is not working on new ones, it throws an error which is mentioned below.

**Error**
```
./tts-media/audios/test/[00:00:00,00:00:08] .mp3
Traceback (most recent call last):
  File "/home/shaheer/Desktop/azure-tts-tool/src/new_main_app.py", line 86, in <module>
    subtitleToClips(folderName) # text to video clips
  File "/home/shaheer/Desktop/azure-tts-tool/src/new_main_app.py", line 78, in subtitleToClips
    lineToClip(line, audioOutputFolder, videOutputFolder)
  File "/home/shaheer/Desktop/azure-tts-tool/src/new_main_app.py", line 39, in lineToClip
    textToMp3(text, audioFilePath)
  File "/home/shaheer/Desktop/azure-tts-tool/src/textToAudio.py", line 16, in textToMp3
    speech_synthesizer = speechsdk.SpeechSynthesizer(
  File "/home/shaheer/Desktop/azure-tts-tool/venv/lib/python3.10/site-packages/azure/cognitiveservices/speech/speech.py", line 1563, in __init__
    self._impl = self._get_impl(impl.SpeechSynthesizer, speech_config, audio_config, auto_detect_source_language_config)
  File "/home/shaheer/Desktop/azure-tts-tool/venv/lib/python3.10/site-packages/azure/cognitiveservices/speech/speech.py", line 1667, in _get_impl
    _impl = synth_type._from_config(speech_config._impl, None if audio_config is None else audio_config._impl)
RuntimeError: Runtime error: Failed to initialize platform (azure-c-shared). Error: 2153
[CALL STACK BEGIN]

/home/shaheer/Desktop/azure-tts-tool/venv/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1a7253) [0x7fb3b43a7253]
/home/shaheer/Desktop/azure-tts-tool/venv/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1c108f) [0x7fb3b43c108f]
/lib/x86_64-linux-gnu/libc.so.6(+0x99f68) [0x7fb3b66d1f68]
/home/shaheer/Desktop/azure-tts-tool/venv/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1c21dc) [0x7fb3b43c21dc]
/home/shaheer/Desktop/azure-tts-tool/venv/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x19f12f) [0x7fb3b439f12f]
/home/shaheer/Desktop/azure-tts-tool/venv/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x19d039) [0x7fb3b439d039]
/home/shaheer/Desktop/azure-tts-tool/venv/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1abb5f) [0x7fb3b43abb5f]
/home/shaheer/Desktop/azure-tts-tool/venv/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x189c46) [0x7fb3b4389c46]
/home/shaheer/Desktop/azure-tts-tool/venv/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1843cc) [0x7fb3b43843cc]
/home/shaheer/Desktop/azure-tts-tool/venv/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0xc3bfd) [0x7fb3b42c3bfd]
/home/shaheer/Desktop/azure-tts-tool/venv/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1abb5f) [0x7fb3b43abb5f]
/home/shaheer/Desktop/azure-tts-tool/venv/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x17c3dd) [0x7fb3b437c3dd]
/home/shaheer/Desktop/azure-tts-tool/venv/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1e0840) [0x7fb3b43e0840]
/home/shaheer/Desktop/azure-tts-tool/venv/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(synthesizer_create_speech_synthesizer_from_config+0xf3) [0x7fb3b42ab6ac]
/home/shaheer/Desktop/azure-tts-tool/venv/lib/python3.10/site-packages/azure/cognitiveservices/speech/_speech_py_impl.so(+0xde414) [0x7fb3b4ade414]
/home/shaheer/Desktop/azure-tts-tool/venv/lib/python3.10/site-packages/azure/cognitiveservices/speech/_speech_py_impl.so(+0xd2573) [0x7fb3b4ad2573]
python(+0x15c9c8) [0x56300cccc9c8]
[CALL STACK END]
```

**Comment by shaheer-haider** [comment]
### The issue was resolved by installing "libssl1.1"
I was facing an issue in installing it and Ubuntu 22 has the latest version of it so I skipped it and then faced this issue.

I followed the answer to this question.
https://askubuntu.com/questions/1403619/mongodb-install-fails-on-ubuntu-22-04-depends-on-libssl1-1-but-it-is-not-insta

**Comment by OwaisAzad** [comment]
@shaheer-haider I cannot express enough gratitude for your solution that helped me get past a difficult issue that I was stuck on. Your efforts and expertise saved me a lot of time and enabled me to work with ease and confidence. I am immensely thankful to you for your contribution, and your kindness and generosity are truly appreciated. Thank you once again for your invaluable help!❤️ @shaheer-haider 😊
