### ISSUE TITLE
Default 300 seconds read timeout affects CosmosClient

### ISSUE THREAD

**Issue by matszewczyk-t** [Azure/azure-sdk-for-python#29879]
**Is your feature request related to a problem? Please describe.**
The default read timeout set for the HTTP requests ([link](https://github.com/Azure/azure-sdk-for-python/blob/a37ea5aaf68a532cbf18fd09a549282dbfcbf722/sdk/core/azure-core/azure/core/configuration.py#L121)) is affecting the [CosmosClient](https://github.com/Azure/azure-sdk-for-python/blob/04aa7e9021907f05a60db967bc4727c62a3ce53e/sdk/cosmos/azure-cosmos/azure/cosmos/cosmos_client.py#L133). However, it is not possible to amend it while interacting with the CosmosClient itself. 

**Describe the solution you'd like**
I'd like to be able to amend this timeout from the CosmosClient level. Unfortunately the _request_timeout_/_timeout_ settings in CosmosClient don't work in this case. It seems that _timeout_ is not picked up at all.

**Comment by navba-MSFT** [comment]
@matszewczyk-t Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Could you please check if the below sample helps ? In the below sample, a new `requests.Session` object named cosmos_session is created and its read timeout is set to 10 minutes. This session object is then passed to the `CosmosClient` constructor using the connection parameter. The `CosmosClient` will use this custom session object for all of its HTTP requests, which will have the modified read timeout.

```
import requests
from azure.cosmos import CosmosClient

cosmos_session = requests.Session()
cosmos_session.timeout = 600  # set the timeout to 10 minutes for CosmosClient requests

# create the CosmosClient with the custom session object
cosmos_client = CosmosClient(
    "https://your-cosmos-account.documents.azure.com:443/",
    credential={"masterKey": "your-account-key"},
    connection=cosmos_session
)

# use the CosmosClient as usual
container = cosmos_client.get_container("your-database", "your-container")
items = container.query_items("SELECT * FROM c", enable_cross_partition_query=True)
for item in items:
    print(item)

```

**Comment by matszewczyk-t** [comment]
@navba-MSFT thanks for your response. Which version of azure-cosmos SDK are you using? In the latest one (4.3.1) CosmosClient does not have the connection parameter. 
Tried it anyway:
`client = CosmosClient(url=endpoint, credential=key, connection=cosmos_session)`
And got: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/optimus/.venv/lib/python3.7/site-packages/azure/cosmos/cosmos_client.py", line 185, in __init__
    url, auth=auth, consistency_level=consistency_level, connection_policy=connection_policy, **kwargs
  File "/optimus/.venv/lib/python3.7/site-packages/azure/cosmos/_cosmos_client_connection.py", line 210, in __init__
    database_account = self._global_endpoint_manager._GetDatabaseAccount(**kwargs)
  File "/optimus/.venv/lib/python3.7/site-packages/azure/cosmos/_global_endpoint_manager.py", line 124, in _GetDatabaseAccount
    database_account = self._GetDatabaseAccountStub(self.DefaultEndpoint, **kwargs)
  File "/optimus/.venv/lib/python3.7/site-packages/azure/cosmos/_global_endpoint_manager.py", line 148, in _GetDatabaseAccountStub
    return self.Client.GetDatabaseAccount(endpoint, **kwargs)
  File "/optimus/.venv/lib/python3.7/site-packages/azure/cosmos/_cosmos_client_connection.py", line 2055, in GetDatabaseAccount
    result, self.last_response_headers = self.__Get("", request_params, headers, **kwargs)
  File "/optimus/.venv/lib/python3.7/site-packages/azure/cosmos/_cosmos_client_connection.py", line 2257, in __Get
    **kwargs
  File "/optimus/.venv/lib/python3.7/site-packages/azure/cosmos/_synchronized_request.py", line 214, in SynchronizedRequest
    **kwargs
  File "/optimus/.venv/lib/python3.7/site-packages/azure/cosmos/_retry_utility.py", line 83, in Execute
    result = ExecuteFunction(function, global_endpoint_manager, *args, **kwargs)
  File "/optimus/.venv/lib/python3.7/site-packages/azure/cosmos/_retry_utility.py", line 144, in ExecuteFunction
    return function(*args, **kwargs)
  File "/optimus/.venv/lib/python3.7/site-packages/azure/cosmos/_synchronized_request.py", line 137, in _Request
    **kwargs
  File "/optimus/.venv/lib/python3.7/site-packages/azure/cosmos/_synchronized_request.py", line 172, in _PipelineRunFunction
    return pipeline_client._pipeline.run(request, **kwargs)
  File "/optimus/.venv/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 205, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/optimus/.venv/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/optimus/.venv/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/optimus/.venv/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/optimus/.venv/lib/python3.7/site-packages/azure/cosmos/_retry_utility.py", line 192, in send
    response = self.next.send(request)
  File "/optimus/.venv/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/optimus/.venv/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/optimus/.venv/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/optimus/.venv/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 100, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/optimus/.venv/lib/python3.7/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 348, in send
    **kwargs
TypeError: request() got an unexpected keyword argument 'connection'
```

**Comment by simorenoh** [comment]
Hi @matszewczyk-t, thanks for using our SDK. I am wondering, what types of requests are you doing that you are timing out by the 300 seconds? Or is the issue here that you'd like to reduce that number to a lower one?

In case of the second one, I believe the argument you're looking for is called `connection_timeout` - do let me know if this works for you.

**Comment by matszewczyk-t** [comment]
Hi @simorenoh, I started with using `connection_timeout`/`request_timeout`, but it seems that they don't work under certain circumstances. It's hard to reproduce, because it happens in ~1-2% of the requests. So even though I'm using these settings:
```
...
request_timeout=20_000,
retry_total=3,
retry_backoff_max=10,
consistency_level="Eventual",
...
```
I still end up getting this 300 seconds read timeout:
```
    self._sender.send(request.http_request, **request.context.options),
    response = self.next.send(request)
    return self._fetch_next_block()
  File "/usr/local/lib/python3.7/site-packages/my_package/io/cosmosdb/CosmosDBClient.py", line 227, in get_container_metadata
  File "/usr/local/lib/python3.7/site-packages/azure/cosmos/_synchronized_request.py", line 137, in _Request
    return first_node.send(pipeline_request)
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/azure/cosmos/_retry_utility.py", line 85, in Execute
  File "/usr/local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 70, in send
  File "/usr/local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 70, in send
  File "/usr/local/lib/python3.7/site-packages/azure/cosmos/_retry_utility.py", line 144, in ExecuteFunction
    return function(*args, **kwargs)
    block = self._ex_context.fetch_next_block()
    return self._fetch_items_helper_with_retries(self._fetch_function)
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/azure/core/paging.py", line 124, in __next__
  File "/usr/local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 70, in send
  File "/usr/local/lib/python3.7/site-packages/azure/cosmos/_execution_context/base_execution_context.py", line 80, in fetch_next_block
  File "/usr/local/lib/python3.7/site-packages/azure/cosmos/_retry_utility.py", line 215, in send
  File "/usr/local/lib/python3.7/site-packages/azure/cosmos/_execution_context/base_execution_context.py", line 170, in _fetch_next_block
  File "/usr/local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 70, in send
  File "/usr/local/lib/python3.7/site-packages/azure/cosmos/_execution_context/base_execution_context.py", line 142, in _fetch_items_helper_with_retries
  File "/usr/local/lib/python3.7/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 364, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
    tables = self._find_table(table_name)
    raise exc
  File "/usr/local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 101, in send
  File "/usr/local/lib/python3.7/site-packages/azure/cosmos/_cosmos_client_connection.py", line 431, in fetch_fn
    lambda _, body: body, query, options, **kwargs
  File "/usr/local/lib/python3.7/site-packages/azure/cosmos/_retry_utility.py", line 192, in send
    response = self.next.send(request)
    (fetched_items, response_headers) = fetch_function(new_options)
  File "/usr/local/lib/python3.7/site-packages/azure/cosmos/_retry_utility.py", line 83, in Execute
    result = ExecuteFunction(function, global_endpoint_manager, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/azure/cosmos/_retry_utility.py", line 144, in ExecuteFunction
  File "/usr/local/lib/python3.7/site-packages/azure/cosmos/_synchronized_request.py", line 172, in _PipelineRunFunction
  File "/usr/local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 202, in run
  File "/usr/local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
    response = self.next.send(request)
  [Previous line repeated 1 more time]
    raise err
    response = self.next.send(request)
  File "/usr/local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 70, in send
    return self._execution_context.fetch_next_block()
    response = self.next.send(request)
  File "/usr/local/lib/python3.7/site-packages/azure/cosmos/_execution_context/execution_dispatcher.py", line 102, in fetch_next_block
    self._response = self._get_next(self.continuation_token)
    raise error
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/azure/cosmos/_execution_context/base_execution_context.py", line 140, in callback
    return next(self._page_iterator)
azure.core.exceptions.ServiceResponseError: HTTPSConnectionPool(host='<HOST_NAME>', port=443): Read timed out. (read timeout=300)
```
the initial get_container_metadata method (highest in the stack trace) does something like this:
`
return <DatabaseProxyObject>.query_containers(query=f"SELECT * FROM r WHERE r.id='<container_name>'")
`

I can see that the `connection_timeout`/`request_timeout` work, as setting them to some unreasonably low number times out the request immediately. However, it looks like there is a scenario where the logic bypasses this setting. 


And coming back to your question, yes - I would like to make it lower (10-15 seconds tops), as I'm fine with implementing the retry mechanism in the upper level. I just don't want to be forced to wait for 5 minutes, as the time-related requirements I have are really tight. 

Thanks!

**Comment by matszewczyk-t** [comment]
Hi @simorenoh, thanks for the tip with get_container_client() method. But unfortunately it happens also when the insert_item() method is called. Traceback:
```
...
  File "/usr/local/lib/python3.7/site-packages/package/io/cosmosdb.py", line 233, in save
   <ContainerProxyInstance>.create_item(body=item)
  File "/usr/local/lib/python3.7/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/azure/cosmos/container.py", line 567, in create_item
    database_or_container_link=self.container_link, document=body, options=request_options, **kwargs
  File "/usr/local/lib/python3.7/site-packages/azure/cosmos/_cosmos_client_connection.py", line 1127, in CreateItem
    return self.Create(document, path, "docs", collection_id, None, options, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/azure/cosmos/_cosmos_client_connection.py", line 2109, in Create
    result, self.last_response_headers = self.__Post(path, request_params, body, headers, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/azure/cosmos/_cosmos_client_connection.py", line 2283, in __Post
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/azure/cosmos/_synchronized_request.py", line 214, in SynchronizedRequest
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/azure/cosmos/_retry_utility.py", line 83, in Execute
    result = ExecuteFunction(function, global_endpoint_manager, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/azure/cosmos/_retry_utility.py", line 144, in ExecuteFunction
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/azure/cosmos/_synchronized_request.py", line 137, in _Request
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/azure/cosmos/_synchronized_request.py", line 172, in _PipelineRunFunction
    return pipeline_client._pipeline.run(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 202, in run
    return first_node.send(pipeline_request)
  File "/usr/local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.7/site-packages/azure/cosmos/_retry_utility.py", line 215, in send
    raise err
  File "/usr/local/lib/python3.7/site-packages/azure/cosmos/_retry_utility.py", line 192, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 101, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/usr/local/lib/python3.7/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 364, in send
    raise error
azure.core.exceptions.ServiceResponseError: HTTPSConnectionPool(...): Read timed out. (read timeout=300)
```

I was trying to debug it, but the issue resulting in this long timeout happens only when the solution is deployed and in ~1% of the writes only. So it makes it really tricky to track. Not sure if these tracebacks are helpful at all from your perspective.

**Comment by simorenoh** [comment]
@matszewczyk-t I see - yeah the stack traces and lack of reproducibility for sure make it harder to look into. One thing that could help is collecting diagnostics for the requests that fail using our CosmosHttpLoggingPolicy diagnostics tool, since that bit does give us some additional information. This would mean some code changes though, so I understand if implementing them is not ideal: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/cosmos/azure-cosmos#logging

Do let me know if the issue resolves itself or if you do find some workaround or additional information we can use to help, thank you!

**Comment by simorenoh** [comment]
@matszewczyk-t Just realized this now looking at the stacks you provided, but have you tried changing the `read_timeout` variable as well? That may be the last thing you're missing to force the lower times you're looking for.

I'm currently working on some documents for our SDK to make this information more easy to find - hopefully that will help you and other users in the future as well.
