### ISSUE TITLE
Error while creating component via CLI

### ISSUE THREAD

**Issue by vikasagrawal-ms** [Azure/azure-sdk-for-python#29941]
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**
While creating a component in registry, error is being thrown. This was working previously

**To Reproduce**
1. az ml component create -f "filepath" -g myresourcegroup --subscription mysub --registry-name myRegistry

**Expected behavior**
component should get created.

**Screenshots**
The command failed with an unexpected error. Here is the traceback:
type object 'YAMLRefDocLinks' has no attribute 'SCHEDULE'
Traceback (most recent call last):
  File "C:\Users\vikasagrawal\repos\azure-sdk-for-python\env\lib\site-packages\knack\cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\vikasagrawal\repos\azure-sdk-for-python\env\lib\site-packages\azure\cli\core\commands\__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "C:\Users\vikasagrawal\repos\azure-sdk-for-python\env\lib\site-packages\azure\cli\core\__init__.py", line 508, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "c:\users\vikasagrawal\repos\sdk-cli-v2\src\cli\src\machinelearningservices\azext_mlv2\__init__.py", line 50, in load_arguments
    load_arguments_manual(self, command)
  File "c:\users\vikasagrawal\repos\sdk-cli-v2\src\cli\src\machinelearningservices\azext_mlv2\manual\_params\__init__.py", line 36, in load_arguments
    load_schedule_params(self)
  File "c:\users\vikasagrawal\repos\sdk-cli-v2\src\cli\src\machinelearningservices\azext_mlv2\manual\_params\_schedule_params.py", line 50, in load_schedule_params
    add_file_param(c, "schedule", YAMLRefDocLinks.SCHEDULE)
AttributeError: type object 'YAMLRefDocLinks' has no attribute 'SCHEDULE'

**Additional context**

**Comment by kashifkhan** [comment]
Thank you for the feedback @vikasagrawal-ms . We will investigate and get back to you asap. 

cc @azureml-github

**Comment by zhengfeiwang** [comment]
Hi @vikasagrawal-ms, this is a known issue and there is a PR fixing that.

BTW, could you please share the ML extension version you are using?

**Comment by vikasagrawal-ms** [comment]
Hi,
Thanks for intimating me.
Ml extension version is 2.15.1

Could you please provide an estimate when will PR get merge?

Thanks and Regards,

Vikas Agrawal
Senior Software Engineer
Azure Machine Learning Training

**Comment by zhengfeiwang** [comment]
tagging the PR owner @needuv for the ETA

**Comment by needuv** [comment]
The PR addressing this failure should be merged today. I will close the issue for now as it will be addressed imminently
