### ISSUE TITLE
Bad file descriptor error with azure-storage-file-datalake version 12.11.0

### ISSUE THREAD

**Issue by antonia-adler** [Azure/azure-sdk-for-python#30107]
With an update to version 12.11.0 (from version 12.10.1) we get the following error:

```
ERROR    asyncio:base_events.py:1752 Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x11a051000>
ERROR    asyncio:base_events.py:1752 Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x11a091c00>, 248276.456461875)]']
connector: <aiohttp.connector.TCPConnector object at 0x11a052920>
ERROR    asyncio:base_events.py:1752 Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x118a636a0>
transport: <_SelectorSocketTransport closing fd=26>
Traceback (most recent call last):
  File "<path>/.pyenv/versions/3.10.9/lib/python3.10/asyncio/selector_events.py", line 924, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<path>.pyenv/versions/3.10.9/lib/python3.10/asyncio/sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "<path>/.pyenv/versions/3.10.9/lib/python3.10/asyncio/selector_events.py", line 930, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "<path>/.pyenv/versions/3.10.9/lib/python3.10/asyncio/selector_events.py", line 725, in _fatal_error
    self._force_close(exc)
  File "<path>/.pyenv/versions/3.10.9/lib/python3.10/asyncio/selector_events.py", line 737, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "<path>/.pyenv/versions/3.10.9/lib/python3.10/asyncio/base_events.py", line 753, in call_soon
    self._check_closed()
  File "<path>/.pyenv/versions/3.10.9/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

We use Python 3.10.10 and we use the async Datalake clients.
`from azure.storage.filedatalake.aio import DataLakeFileClient, DataLakeServiceClient, FileSystemClient`
Is there anything that has changed from version 12.10.1 to version 12.11.0?

**Comment by kashifkhan** [comment]
Thanks for the feedback @antonia-adler . We will investigate and get back to you asap.

**Comment by vincenttran-msft** [comment]
Hi @antonia-adler , I just wanted to round back to see if you are still experiencing this issue? If so, could you please provide a code sample to help us better understand where in the codebase you may be experiencing this? Thanks!

**Comment by antonia-adler** [comment]
Hi @vincenttran-msft, thanks for reaching out! :) 
Yes, we are still facing this problem. This is an example snippet:
```
from azure.storage.filedatalake.aio import DataLakeFileClient, DataLakeServiceClient, FileSystemClient
from pathlib import Path

async def main(directory: Path):
    service_client = DataLakeServiceClient(
        account_url="<account_url>",
        credential="<sas_token>",
    )
    fs_client = service_client.get_file_system_client(file_system="<container name>")
    file_client = fs_client.get_file_client(directory.name)
    if await file_client.exists():
        with open(directory, "rb") as data:
            await file_client.upload_data(data=data, overwrite=True)
    await file_client.close()
    await fs_client.close()
    await service_client.close()


if __name__ == "__main__":
    asyncio.run(main(Path('put here the path to the file which you want to upload')))

```

As mentioned above: This code works fine with version `12.10.1`, but outputs an error with version `12.11.0`.


I experimented a little bit with the code and debugged the azure library. I think there is an unclosed `AsyncPipelineClient` somewhere. The problem is fixed when additionally calling 
```
await service_client._client.close()
```

**Comment by vincenttran-msft** [comment]
Hi @antonia-adler, thanks again for your inquiry. After taking a closer look at our async client code, I did notice that some clients were not being closed properly. I have been working on resolving this and will attach the pull-request here. 

With that being said, I believe this will correct your issue and the proper client closure changes will be included in our upcoming release. And so, I will close this issue alongside the successful merge of the pull-request containing the fix!

Thanks!

**Comment by antonia-adler** [comment]
Thanks for the fast resolution!
