### ISSUE TITLE
azure-ai-ml: Submitting 2 jobs at exactly the same time fails with error "Blob already exists"

### ISSUE THREAD

**Issue by ant0nsc** [Azure/azure-sdk-for-python#30155]
- **Package Name**: azure-ai-ml
- **Package Version**: 1.5.0
- **Operating System**: Ubuntu
- **Python Version**: 3.7

**Describe the bug**
When attempting to submit 2 jobs to a workspace at the same time, job submission fails saying `The specified blob already exists`.
This frequently breaks our unit test pipelines that submit several jobs in parallel.

**To Reproduce**
Start two consoles, submit a job via the SDK at exactly the same time.

**Expected behavior**
I would expect that each job works with a unique ID for uploading the snapshot in the back-end, and hence that submitting at the same time is permitted.

**Screenshots**
Example from our CI pipeline: 2 legs of the pipeline submit jobs at 2023-04-28T18:49:12Z:
[job 1](https://github.com/microsoft/hi-ml/actions/runs/4833782799/jobs/8614211801) and [job 2](https://github.com/microsoft/hi-ml/actions/runs/4833782799/jobs/8614211590)

Stack trace:
```
Uploading *** (8.78 MBs):   0%|          | 0/8778337 [00:00<?, ?it/s]
Uploading *** (8.78 MBs):   0%|          | 3941/8778337 [00:00<06:53, 21203.33it/s]
Uploading *** (8.78 MBs):   0%|          | 4973/8778337 [00:00<10:42, 13653.22it/s]
Traceback (most recent call last):
  File "src/health_ml/runner.py", line 407, in <module>
    main()
  File "src/health_ml/runner.py", line 403, in main
    run_with_logging(project_root)
  File "src/health_ml/runner.py", line 398, in run_with_logging
    return run(project_root)
  File "src/health_ml/runner.py", line 350, in run
    return Runner(project_root).run()
  File "src/health_ml/runner.py", line 205, in run
    azure_run_info = self.submit_to_azureml_if_needed()
  File "src/health_ml/runner.py", line 278, in submit_to_azureml_if_needed
    identity_based_auth=self.experiment_config.identity_based_auth,
  File "/home/runner/work/***/***/***-azure/src/health_azure/himl.py", line 994, in submit_to_azure_if_needed
    pytorch_processes_per_node=pytorch_processes_per_node_v2,
  File "/home/runner/work/***/***/***-azure/src/health_azure/himl.py", line 573, in submit_run_v2
    returned_job = ml_client.jobs.create_or_update(job_to_submit)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/ai/ml/_telemetry/activity.py", line 337, in wrapper
    return_value = f(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/ai/ml/operations/_job_operations.py", line 593, in create_or_update
    raise ex
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/ai/ml/operations/_job_operations.py", line 529, in create_or_update
    self._resolve_arm_id_or_upload_dependencies(job)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/ai/ml/operations/_job_operations.py", line 874, in _resolve_arm_id_or_upload_dependencies
    self._resolve_arm_id_or_azureml_id(job, self._orchestrators.get_asset_arm_id)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/ai/ml/operations/_job_operations.py", line 1087, in _resolve_arm_id_or_azureml_id
    job = self._resolve_arm_id_for_command_job(job, resolver)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/ai/ml/operations/_job_operations.py", line 1126, in _resolve_arm_id_for_command_job
    azureml_type=AzureMLResourceType.CODE,
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/ai/ml/operations/_operation_orchestrator.py", line 218, in get_asset_arm_id
    result = self._get_code_asset_arm_id(asset, register_asset=register_asset)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/ai/ml/operations/_operation_orchestrator.py", line 275, in _get_code_asset_arm_id
    raise e
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/ai/ml/operations/_operation_orchestrator.py", line 259, in _get_code_asset_arm_id
    code_asset = self._code_assets.create_or_update(code_asset)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/ai/ml/_telemetry/activity.py", line 263, in wrapper
    return f(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/ai/ml/operations/_code_operations.py", line 142, in create_or_update
    raise ex
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/ai/ml/operations/_code_operations.py", line 96, in create_or_update
    artifact=code, asset_operations=self, sas_uri=sas_uri, artifact_type=ErrorTarget.CODE
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/ai/ml/_artifacts/_artifact_utilities.py", line 409, in _check_and_upload_path
    ignore_file=getattr(artifact, "_ignore_file", None),
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/ai/ml/_artifacts/_artifact_utilities.py", line 307, in _upload_to_datastore
    sas_uri=sas_uri,
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/ai/ml/_artifacts/_artifact_utilities.py", line 184, in upload_artifact
    ignore_file=ignore_file,
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/ai/ml/_artifacts/_blob_storage_helper.py", line 109, in upload
    ignore_file=ignore_file,
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/ai/ml/_utils/_asset_utils.py", line 636, in upload_directory
    future.result()  # access result to propagate any exceptions
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/ai/ml/_utils/_asset_utils.py", line 534, in upload_file
    connection_timeout=DEFAULT_CONNECTION_TIMEOUT,
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/storage/blob/_container_client.py", line 985, in upload_blob
    **kwargs
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/storage/blob/_blob_client.py", line 716, in upload_blob
    return upload_block_blob(**options)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/storage/blob/_upload_helpers.py", line 168, in upload_block_blob
    process_storage_error(error)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/storage/blob/_shared/response_handlers.py", line 181, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/storage/blob/_upload_helpers.py", line 113, in upload_block_blob
    **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 245, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/azure/core/exceptions.py", line 109, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:d8bd2f94-201e-0057-0b02-7acedb000000
Time:2023-04-28T18:49:15.10[47](https://github.com/microsoft/hi-ml/actions/runs/4833782799/jobs/8614211590#step:4:48)344Z
ErrorCode:BlobAlreadyExists
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:d8bd2f94-201e-0057-0b02-7acedb000000
Time:2023-04-28T18:[49](https://github.com/microsoft/hi-ml/actions/runs/4833782799/jobs/8614211590#step:4:50):15.104[73](https://github.com/microsoft/hi-ml/actions/runs/4833782799/jobs/8614211590#step:4:74)44Z</Message></Error>
```

**Comment by thierryherrmann** [comment]
we exactly have the same problem. We can't parallelize our unit tests in our pipeline because of this, and it takes 5x more time than with parallelization. Would be nice to fix.

**Comment by ant0nsc** [comment]
@thierryherrmann , I've gotten a message from @luigiw that setting the job name could maybe solve the problem. When your job submission code calls the `command` function from the API, are you supplying the `name` argument? If not, can you try setting that to a GUID or some other random ID?
I've tried the same on my codebase, but since the problem does not always occur in my test suite, I'm not sure if that has made any difference.

**Comment by thierryherrmann** [comment]
@ant0nsc thanks for the suggestion. Just like you, it never failed when using a uuid as the job name, but without this fix failures are not frequent enough to conclude that the fix is effective. I'll keep the fix and if the error reappears, I'll mention it here. Thanks.

**Comment by thierryherrmann** [comment]
@ant0nsc, @luigiw today the workaround failed. I had used this:
```python
job_name = str(uuid.uuid4())
from azure.ai.ml.entities._job.job_name_generator import generate_job_name
display_name = generate_job_name() # the human-friendly name
```
but it failed at least one. I'll remove the workaround as the human-friendly name is friendlier to use with `az ml` commands than a uuid... Thank you both for the suggestions/support.
I hope this issue will be addressed.

**Comment by thierryherrmann** [comment]
@ant0nsc yes. In the attempted workaround (that doesn't work), I just give `job_name` to the `command()` method. Continuing from my previous snippet:
```python
cmd = command(
    name=job_name,
    display_name=display_name,
    environment=environment,
    #...etc...
)
job = ml_client.jobs.create_or_update(cmd)  
```

**Comment by achauhan-scc** [comment]
closing as obsolete
