### ISSUE TITLE
az keyvault list breaking change for 2016-10-01 API version

### ISSUE THREAD

**Issue by TheOnlyWei** [Azure/azure-sdk-for-python#30393]
- **Package Name**: 
azure-mgmt-keyvault
- **Package Version**: 
Latest (10.2.1). See code below.
- **Operating System**:
Windows server 2019 datacenter
- **Python Version**: 
Using Azure CLI:
```
azure-cli                         2.48.1
core                              2.48.1
telemetry                          1.0.8
Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\Administrator.S31R2401-DVM\.azure\cliextensions'
Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]
```

**Describe the bug**

Seems to be a breaking change with `az keyvault list` command which goes into the code below.
https://github.com/Azure/azure-sdk-for-python/blob/555f71d4cacde0f4baf8daaf28dbf3099b058f7d/sdk/keyvault/azure-mgmt-keyvault/azure/mgmt/keyvault/v2016_10_01/operations/_vaults_operations.py#L1437

I did not get this error in Azure CLI 2.29.2 which doesn't pass filter or api-version parameter:
https://github.com/Azure/azure-cli/blob/0a1edd5b0960f02162c89abaa97d9ab063d202ba/src/azure-cli/azure/cli/command_modules/keyvault/custom.py#L302
The latest Azure CLI 2.48.1 also doesn't pass those parameters but does throw the error:
https://github.com/Azure/azure-cli/blob/0473e47aadd59e208e2772650967bba9e514ed7b/src/azure-cli/azure/cli/command_modules/keyvault/custom.py#L302

In the old code it sets filter to `resourceType eq 'Microsoft.KeyVault/vaults'` by default:
https://github.com/Azure/azure-sdk-for-python/blob/3844924ef1c79c0ee1361d5d495fbeb0a54631f9/sdk/keyvault/azure-mgmt-keyvault/azure/mgmt/keyvault/v2016_10_01/operations/_vaults_operations.py#L783
and api-version to `2015-11-01`:
https://github.com/Azure/azure-sdk-for-python/blob/3844924ef1c79c0ee1361d5d495fbeb0a54631f9/sdk/keyvault/azure-mgmt-keyvault/azure/mgmt/keyvault/v2016_10_01/operations/_vaults_operations.py#L784

**Question**
So, it looks like a breaking change to me. Is this an intended breaking change for such an old API version (still used by Azure Stack Hub customers)? This could easily be fixed be bringing back the default values for filter and api-version from the code linked above. If it is an intended breaking change, I will create a bug for Azure CLI.

**Error**
Here is the debug error from Azure CLI:
```
[DBG]: PS C:\test\Workloads\DeveloperExperience\CLI>> az keyvault list --debug
az : DEBUG: cli.knack.log: File logging enabled - writing logs to 'C:\CloudDeployment\BVTs\Output\AZSDKTOOLSCTQ\CLITestLogs'.
At line:1 char:1
+ az keyvault list --debug
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (DEBUG: cli.knac...Q\CLITestLogs'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
DEBUG: cli.knack.cli: Command arguments: ['keyvault', 'list', '--debug']
DEBUG: cli.knack.cli: __init__ debug log:
Cannot enable color.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x00A0A4A8>, <function OutputProducer.on_global_arguments 
at 0x00AD7C40>, <function CLIQuery.on_global_arguments at 0x00AF88E0>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Modules found from index for 'keyvault': ['azure.cli.command_modules.keyvault']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: keyvault                  0.016        11        69
DEBUG: cli.azure.cli.core: Total (1)                 0.016        11        69
DEBUG: cli.azure.cli.core: Loaded 11 groups, 69 commands.
DEBUG: cli.azure.cli.core: Found a match in the command table.
DEBUG: cli.azure.cli.core: Raw command  : keyvault list
DEBUG: cli.azure.cli.core: Command table: keyvault list
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x0392A4A8>]
DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 
'C:\Users\Administrator.S31R2401-DVM\.azure\commands\2023-05-13.07-20-30.keyvault_list.8800.log'.
INFO: az_command_data_logger: command args: keyvault list --debug
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x0395FA00>]
DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 641, in _get_attr
AttributeError: module 'azure.keyvault.v2016_10_01.models' has no attribute 'SasTokenType'

DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 641, in _get_attr
AttributeError: module 'azure.mgmt.keyvault.v2016_10_01.models' has no attribute 'NetworkRuleBypassOptions'

DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 641, in _get_attr
AttributeError: module 'azure.mgmt.keyvault.v2016_10_01.models' has no attribute 'NetworkRuleAction'

DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 641, in _get_attr
AttributeError: module 'azure.mgmt.keyvault.v2016_10_01.models' has no attribute 'PublicNetworkAccess'

DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x0395FA48>, <function 
register_cache_arguments.<locals>.add_cache_arguments at 0x0395FAD8>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x00AD7C88>, <function CLIQuery.handle_query_parameter at 
0x00AF8928>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x0395FA90>]
DEBUG: cli.azure.cli.core.commands.client_factory: Getting management service client client_type=KeyVaultManagementClient
DEBUG: cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\Administrator.S31R2401-DVM\\.azure\\msal_token_cache.bin', encrypt=True
DEBUG: cli.azure.cli.core.auth.binary_cache: load: C:\Users\Administrator.S31R2401-DVM\.azure\msal_http_cache.bin
DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
DEBUG: msal.authority: openid_config = {'issuer': 'https://adfs.redmond.ext-s31r2401.masd.stbtest.microsoft.com/adfs/1594f18f-751c-4526-a37a-721aeefbdd56/', 
'authorization_endpoint': 'https://adfs.redmond.ext-s31r2401.masd.stbtest.microsoft.com/adfs/oauth2/authorize/', 'token_endpoint': 
'https://adfs.redmond.ext-s31r2401.masd.stbtest.microsoft.com/adfs/oauth2/token/', 'jwks_uri': 
'https://adfs.redmond.ext-s31r2401.masd.stbtest.microsoft.com/adfs/discovery/keys', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'client_secret_basic', 
'private_key_jwt', 'windows_client_authentication'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token', 'code token', 'code id_token 
token'], 'response_modes_supported': ['query', 'fragment', 'form_post'], 'grant_types_supported': ['authorization_code', 'refresh_token', 'client_credentials', 
'urn:ietf:params:oauth:grant-type:jwt-bearer', 'implicit', 'password', 'srv_challenge', 'urn:ietf:params:oauth:grant-type:device_code', 'device_code'], 
'subject_types_supported': ['pairwise'], 'scopes_supported': ['logon_cert', 'user_impersonation', 'email', '.default', 'winhello_cert', 'profile', 'openid', 'aza', 
'allatclaims', 'vpn_cert'], 'id_token_signing_alg_values_supported': ['RS256'], 'token_endpoint_auth_signing_alg_values_supported': ['RS256'], 'access_token_issuer': 
'https://adfs.redmond.ext-s31r2401.masd.stbtest.microsoft.com/adfs/1594f18f-751c-4526-a37a-721aeefbdd56/', 'claims_supported': ['aud', 'iss', 'iat', 'exp', 'auth_time', 
'nonce', 'at_hash', 'c_hash', 'sub', 'upn', 'unique_name', 'pwd_url', 'pwd_exp', 'mfa_auth_time', 'sid', 'nbf'], 'microsoft_multi_refresh_token': True, 
'userinfo_endpoint': 'https://adfs.redmond.ext-s31r2401.masd.stbtest.microsoft.com/adfs/userinfo', 'capabilities': ['kdf_ver2'], 'end_session_endpoint': 
'https://adfs.redmond.ext-s31r2401.masd.stbtest.microsoft.com/adfs/oauth2/logout', 'as_access_token_token_binding_supported': False, 
'as_refresh_token_token_binding_supported': False, 'resource_access_token_token_binding_supported': False, 'op_id_token_token_binding_supported': False, 
'rp_id_token_token_binding_supported': False, 'frontchannel_logout_supported': True, 'frontchannel_logout_session_supported': True, 'device_authorization_endpoint': 
'https://adfs.redmond.ext-s31r2401.masd.stbtest.microsoft.com/adfs/oauth2/devicecode'}
DEBUG: msal.application: Broker enabled? False
DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/custom.py", line 271, in list_vault_or_hsm
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/custom.py", line 302, in list_vault
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
TypeError: VaultsOperations.list() missing 2 required positional arguments: 'filter' and 'api_version'

ERROR: cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
ERROR: az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
ERROR: cli.azure.cli.core.azclierror: VaultsOperations.list() missing 2 required positional arguments: 'filter' and 'api_version'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/custom.py", line 271, in list_vault_or_hsm
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/custom.py", line 302, in list_vault
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
TypeError: VaultsOperations.list() missing 2 required positional arguments: 'filter' and 'api_version'
ERROR: az_command_data_logger: VaultsOperations.list() missing 2 required positional arguments: 'filter' and 'api_version'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/custom.py", line 271, in list_vault_or_hsm
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/custom.py", line 302, in list_vault
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
TypeError: VaultsOperations.list() missing 2 required positional arguments: 'filter' and 'api_version'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x0392A5C8>]
INFO: az_command_data_logger: exit code: 1
INFO: cli.__main__: Command ran in 1.232 seconds (init: 0.505, invoke: 0.727)
INFO: telemetry.main: Begin splitting cli events and extra events, total events: 1
INFO: telemetry.client: Accumulated 0 events. Flush the clients.
INFO: telemetry.main: Finish splitting cli events and extra events, cli events: 1
INFO: telemetry.save: Save telemetry record of length 7021 in cache
WARNING: telemetry.check: Negative: The C:\Users\Administrator.S31R2401-DVM\.azure\telemetry.txt was modified at 2023-05-13 07:11:26.157388, which in less than 600.000000 s
```

**To Reproduce**
1. Install Azure CLI 2.48.1.
2. Register Azure CLI cloud for Azure Stack Hub using 2020-09-01-hybrid profile.
3. Run `az keyvault list`.

**Expected behavior**
Should not throw error. There were default values for these if user doesn't pass them in the old code.
```
TypeError: VaultsOperations.list() missing 2 required positional arguments: 'filter' and 'api_version'
```

**Comment by msyyc** [comment]
@TheOnlyWei  It is related with CLI so could you open an issue in https://github.com/Azure/azure-cli/issues?

**Comment by evelyn-ys** [comment]
@msyyc This issue is opened in SDK repo because it's SDK breaking change that causing CLI code not working. CLI doesn't change anything but bumping `azure-mgmt-keyvault` from `10.1.0` to `10.2.0`. And in `10.2.0`, there're a lot of breaking changes for API version `2016-10-01`, including what @TheOnlyWei says, `vaults_operations.list()` has added two required arguments `fileter` and `api_version`.

@calvinhzy Can you keep following this issue?

**Comment by calvinhzy** [comment]
Will update the SDK dependency to the latest version in our next sprint, which should fix the breaking changes.

**Comment by msyyc** [comment]
@evelyn-ys @calvinhzy After upgrading to https://pypi.org/project/azure-mgmt-keyvault/10.2.1/, the issue shall be fixed.

**Comment by TheOnlyWei** [comment]
Hi @calvinhzy, is there an issue or PR tracking this fix on the Azure CLI side?
