### ISSUE TITLE
Tracking issue for `DefaultAzureCredential` (azure-identity) support in `azure-batch`

### ISSUE THREAD

**Issue by bluenote10** [Azure/azure-sdk-for-python#30468]
**Is your feature request related to a problem? Please describe.**

In the past the Azure library ecosystem was fragmented in terms of credential handling. An infamous error when trying to work with the alleged standard `DefaultAzureCredential` is:

```
AttributeError: 'DefaultAzureCredential' object has no attribute 'signed_session'
```

According to [this](https://stackoverflow.com/q/63384092/1804173) StackOverflow question, the goal is to clean up the credentials handling:

> As of May 2022, all SDKs have been re-released with native support for azure-identity. If you still encounter this error with a given SDK on its latest version, please open an issue asking for a re-release of that SDK here: https://github.com/Azure/azure-sdk-for-python/issues

`azure-batch` as of its latest version 13.0.0 (released on Nov 9th 2022) still does not support `DefaultAzureCredential`.

This issue has been raised a few times before:
- https://github.com/Azure/azure-sdk-for-python/issues/23583
- https://github.com/Azure/azure-sdk-for-python/issues/28739

The issues vaguely mention that this feature will come eventually ([one comment](https://github.com/Azure/azure-sdk-for-python/issues/23583#issuecomment-1079098388) suggesting by the end of 2022, which apparently hasn't happened), but the tickets have been closed, without actually being resolved.

It would be great we can have a proper "tracking issue" that actually gets closed, once the feature really is there. This way, users can really react to the change. Closing the issues without really having resolved the issue only leads to confusion (implying that it might work already), and misses an opportunity to use the issue ticket as an "announcement" to its watchers via the closing action.

**Describe the solution you'd like**

Re-release `azure-batch` with `DefaultAzureCredential` support and keep this issue open until that point.

**Comment by iscai-msft** [comment]
thank you for opening this issue @bluenote10 we will take a look at this. Also tagging @xiangyan99 to make sure this isn't an identity issue

**Comment by bluenote10** [comment]
What makes this issue worst is that originally the necessary work-around with the credentials wrapper was documented on this page: 

https://learn.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?tabs=cmd

But the documentation of the work-around has now been removed, which is fine for the majority of the Azure ecosystem, but just not Azure batch, i.e., currently even the work-around is undocumented.

Also note that this is creating confusion even for Microsoft engineers. For instance, the original author was under the impressions [that](https://gist.github.com/lmazuel/cc683d82ea1d7b40208de7c9fc8de59d?permalink_comment_id=4134202#gistcomment-4134202)

> 100% of Python SDKs have now support for azure-identity natively, this snippet is not recommended nor necessary anymore as of today

But later corrected that it isn't really 100% due to Azure batch.

**Comment by drjwelch** [comment]
Arrived here researching a potential use-case for Batch after reading that, although DefaultAzureCredential() could be used in Automation runbook, such runbook cannot traverse other Azure service firewalls to persist data.  Since Batch can't use DefaultAzureCredential() looks like I'm stuck with expensive databricks solution, unless anyone can advise different.

**Comment by Raphtor** [comment]
Not sure if this was the previously-provided workaround, but this worked for me:

```python
from azure.identity import DefaultAzureCredential
from msrest.authentication import BasicTokenAuthentication
from azure.batch import BatchServiceClient

token = {'access_token':DefaultAzureCredential().get_token('https://batch.core.windows.net/.default').token}
credentials = BasicTokenAuthentication(token)
batch_client = BatchServiceClient(
    credentials,
    batch_url=batch_url)
```

**Comment by jabbera** [comment]
If anyone stumbles across this in the future, the example from Raphtor will stop working after the access token expires. This uses the pipeline to provide credentials as opposed to a static token.

```
class __TokenProvider(HTTPPolicy):
    def send(self, request, **kwargs):
        credentials = DefaultAzureCredential()
        token = credentials.get_token('https://batch.core.windows.net/.default')
        request.http_request.headers['Authorization'] = 'Bearer ' + token.token
        return self.next.send(request, **kwargs)
```

**Comment by dpwatrous** [comment]
The workaround above looks reasonable to me, but FYI we are working on releasing a beta version of the `azure-batch` package which supports DefaultAzureCredential natively. Hoping to have the first version out in June. (Work is ongoing under [this PR](https://github.com/Azure/azure-sdk-for-python/pull/32383))

**Comment by philipguin** [comment]
I'm still seeing this issue, using `BatchServiceClient` with a `DefaultAzureCredential` in a locally running Azure function (`func start`).

```
[2024-10-15T20:19:17.439Z] An error occurred in "render_begin": 'DefaultAzureCredential' object has no attribute 'signed_session'
Traceback (most recent call last):
  File "C:\Dev\Mozaik\MozaikAzureRender\function_app.py", line 284, in render_begin
    batch_client.job.add(job_params) # returns None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dev\Python\Python311\Lib\site-packages\azure\batch\operations\_job_operations.py", line 903, in add
    response = self._client.send(request, stream=False, **operation_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dev\Python\Python311\Lib\site-packages\msrest\service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dev\Python\Python311\Lib\site-packages\msrest\pipeline\__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dev\Python\Python311\Lib\site-packages\msrest\pipeline\__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dev\Python\Python311\Lib\site-packages\msrest\pipeline\requests.py", line 65, in send
    self._creds.signed_session(session)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DefaultAzureCredential' object has no attribute 'signed_session'
```

```bash
$ az --version
azure-cli                         2.65.0

core                              2.65.0
telemetry                          1.1.0

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1
```

Running `pip install -U --force msrest` didn't seem to help either.

**Comment by udit-rathod** [comment]
> Not sure if this was the previously-provided workaround, but this worked for me:
> 
> from azure.identity import DefaultAzureCredential
> from msrest.authentication import BasicTokenAuthentication
> from azure.batch import BatchServiceClient
> 
> token = {'access_token':DefaultAzureCredential().get_token('https://batch.core.windows.net/.default').token}
> credentials = BasicTokenAuthentication(token)
> batch_client = BatchServiceClient(
>     credentials,
>     batch_url=batch_url)

Works like a charm! Thank you!
