### ISSUE TITLE
azure-ai-formrecognizer: ModuleNotFoundError: No module named 'azure.core.polling.base_polling'

### ISSUE THREAD

**Issue by lambdaofgod** [Azure/azure-sdk-for-python#30582]
- **Package Name**: azure-ai-formrecognizer
- **Package Version**: azure-ai-formrecognizer>=3.0.0, azure-core==1.26.4
- **Operating System**: Linux
- **Python Version**: 3.10

**Describe the bug**
```
Traceback (most recent call last):
  File "qa_pipeline.py", line 5, in <module>
    import azure.ai.formrecognizer
  File "$HOME/.local/lib/python3.8/site-packages/azure/ai/formrecognizer/__init__.py", line 8, in <module>
    from ._form_recognizer_client import FormRecognizerClient
  File "$HOME/.local/lib/python3.8/site-packages/azure/ai/formrecognizer/_form_recognizer_client.py", line 18, in <module>
    from azure.core.polling.base_polling import LROBasePolling
ModuleNotFoundError: No module named 'azure.core.polling.base_polling'

```

**To Reproduce**
Install azure-ai-formrecognizer

```
import azure.ai 
```

**Comment by lambdaofgod** [comment]
Ok, so I tried uninstalling azure-core and azure-ai-formrecognizer. Now I get

```
ImportError: cannot import name 'AzureKeyCredential' from 'azure.core.credentials' (/usr/lib/python3/dist-packages/azure/core/credentials.py)
```

**Comment by kashifkhan** [comment]
Thank you for the feedback @lambdaofgod. Ill be assigning this to my colleague who can better assist you. 

In the meantime, I tried installing this on a WSL instance with py 3.10 

```shell
python3.10 -m venv formrecog
source formrecog/bin/activate
pip install azure-ai-formrecognizer==3.3.0b1
```
which gives me the following on `pip freeze`

```shell
azure-ai-formrecognizer==3.3.0b1
azure-common==1.1.28
azure-core==1.26.4
certifi==2023.5.7
charset-normalizer==3.1.0
idna==3.4
isodate==0.6.1
msrest==0.7.1
oauthlib==3.2.2
requests==2.31.0
requests-oauthlib==1.3.1
six==1.16.0
typing_extensions==4.6.2
urllib3==2.0.2
```

I then made a simple hello_world.py, which ran successfully
```python
import azure.ai
print("Hello world")
```
Would you be able to test in a new venv please ?

**Comment by lambdaofgod** [comment]
I tested this in a fresh 3.10 anaconda env and it indeed works.
