### ISSUE TITLE
Listing databricks workspaces from a subscription doesnt work: list_by_subscription() in azure-mgmt-databricks crashes whereas list_dy_resource_group works.

### ISSUE THREAD

**Issue by anogues** [Azure/azure-sdk-for-python#30704]
- azure-mgmt-databricks
- 1.0.0 but it happens also with the beta versions (also msrest 0.7.1 but tried with 0.6.9 as well and same issue)
- Windows
- 3.11

**Describe the bug**
When trying to list workspaces by subscription it returns the iterator but upon iterating the results it crashes with the following error:

>>> dbr_client.workspaces.list_by_subscription()
<iterator object azure.core.paging.ItemPaged at 0x1bef2f4aa10>
>>> for i, r in enumerate(dbr_client.workspaces.list_by_subscription()):
...     print(r)
...
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\msrest\serialization.py", line 1436, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\msrest\serialization.py", line 1180, in rest_key_extractor
    return working_data.get(key)
           ^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'

  File "C:\Python\Lib\site-packages\azure\core\paging.py", line 128, in __next__
    return next(self._page_iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\azure\core\paging.py", line 84, in __next__
    self.continuation_token, self._current_page = self._extract_data(self._response)
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\azure\mgmt\databricks\operations\_workspaces_operations.py", line 597, in extract_data
    deserialized = self._deserialize('WorkspaceListResult', pipeline_response)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\msrest\serialization.py", line 1376, in __call__
    return self._deserialize(target_obj, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\msrest\serialization.py", line 1454, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "C:\Python\Lib\site-packages\msrest\exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "C:\Python\Lib\site-packages\msrest\serialization.py", line 1436, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\msrest\serialization.py", line 1180, in rest_key_extractor
    return working_data.get(key)
           ^^^^^^^^^^^^^^^^
azure.core.exceptions.DeserializationError: ("Unable to deserialize to object: type, AttributeError: 'list' object has no attribute 'get'", AttributeError("'list' object has no attribute 'get'"))

**To Reproduce**
1. Create a piece of code with the folowing:
credential = DefaultAzureCredential(exclude_shared_token_cache_credential=True, exclude_interactive_browser_credential=False, exclude_visual_studio_code_credential=True)
 dbr_client = DatabricksClient(credential, yourSubscriptionIdHere)
 dbr_client.workspaces.list_by_subscription()

The function to return by resource group works fine:

 dbr_client.workspaces.list_by_resource_group("XXXXXXXXXXX")
<iterator object azure.core.paging.ItemPaged at 0x23919f1ff90>
>>> dbr_client.workspaces.list_by_resource_group("XXXXXXXXXXXXXX").__dict__
{'_args': (<function WorkspacesOperations.list_by_resource_group.<locals>.get_next at 0x000002391AD627A0>, <function WorkspacesOperations.list_by_resource_group.<locals>.extract_data at 0x000002391AD62840>), '_kwargs': {}, '_page_iterator': None, '_page_iterator_class': <class 'azure.core.paging.PageIterator'>}

but the subscription altough it returns the iterator something doesnt work well when you iterate over it
>>> dbr_client.workspaces.list_by_subscription().__dict__
{'_args': (<function WorkspacesOperations.list_by_subscription.<locals>.get_next at 0x000002391AD62840>, <function WorkspacesOperations.list_by_subscription.<locals>.extract_data at 0x000002391AD62980>), '_kwargs': {}, '_page_iterator': None, '_page_iterator_class': <class 'azure.core.paging.PageIterator'>}

**Expected behavior**
In the past (like 6 months ago) it worked and returned an object with all the databricks workspaces in a subscription

**Additional context**
Since its not working you need to resort to the api. The api call returns the data fine so i assue its a problem on how its handled the return of the api call. Currently y had to switch to the following:

    url = 'https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Databricks/workspaces?api-version=2023-02-01'.format(subscriptionId=subscriptions[subscription])
    headers = {'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + tokenDefault
        }
    response = requests.get(url=url,headers = headers)    
    d = json.loads(response.text)
    for wks in d:
        print(wks['properties']['workspaceUrl'])

**Comment by anogues** [comment]
Also It seems your unittests are not testing that function

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/databricks/azure-mgmt-databricks/tests/test_cli_mgmt_databricks.py

I see two calls for the list_by_resource_group() but none for list_by_subscription() Maybe you should fix that too.

BR,
Albert

**Comment by Wzb123456789** [comment]
@anogues Please try to use this example to solve your problem: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/databricks/azure-mgmt-databricks/generated_samples/workspaces_list_by_subscription.py

**Comment by anogues** [comment]
@Wzb123456789 Hello.

I've already tried this version and same error. Just tried it again:


C:\Users\Albert>pip install azure-mgmt-databricks==1.1.0b2
Requirement already satisfied: azure-mgmt-databricks==1.1.0b2 in c:\python\lib\site-packages (1.1.0b2)
Requirement already satisfied: msrest>=0.7.1 in c:\python\lib\site-packages (from azure-mgmt-databricks==1.1.0b2) (0.7.1)
Requirement already satisfied: azure-common~=1.1 in c:\python\lib\site-packages (from azure-mgmt-databricks==1.1.0b2) (1.1.28)
Requirement already satisfied: typing-extensions>=4.3.0 in c:\python\lib\site-packages (from azure-core<2.0.0,>=1.24.0->azure-mgmt-core<2.0.0,>=1.3.2->azure-mgmt-databricks==1.1.0b2) (4.4.0)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\python\lib\site-packages (from requests~=2.16->msrest>=0.7.1->azure-mgmt-databricks==1.1.0b2) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in c:\python\lib\site-packages (from requests~=2.16->msrest>=0.7.1->azure-mgmt-databricks==1.1.0b2) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python\lib\site-packages (from requests~=2.16->msrest>=0.7.1->azure-mgmt-databricks==1.1.0b2) (1.26.13)



C:\Users\Albert>python
Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from azure.identity import DefaultAzureCredential
>>> from azure.mgmt.databricks import AzureDatabricksManagementClient
>>>
>>> client = AzureDatabricksManagementClient(credential=DefaultAzureCredential(exclude_shared_token_cache_credential=True, exclude_interactive_browser_credential=False, exclude_visual_studio_code_credential=True),subscription_id="XXXXXXXXXXXXXXX")
>>>
>>> response = client.workspaces.list_by_subscription()
>>> for item in response:
...     print(item)
...
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\azure\mgmt\databricks\_serialization.py", line 1430, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\azure\mgmt\databricks\_serialization.py", line 1177, in rest_key_extractor
    return working_data.get(key)
           ^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\Lib\site-packages\azure\core\paging.py", line 124, in __next__
    return next(self._page_iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\azure\core\paging.py", line 84, in __next__
    self.continuation_token, self._current_page = self._extract_data(self._response)
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\azure\mgmt\databricks\operations\_workspaces_operations.py", line 1034, in extract_data
    deserialized = self._deserialize("WorkspaceListResult", pipeline_response)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\azure\mgmt\databricks\_serialization.py", line 1375, in __call__
    return self._deserialize(target_obj, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\azure\mgmt\databricks\_serialization.py", line 1445, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "C:\Python\Lib\site-packages\azure\core\exceptions.py", line 77, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "C:\Python\Lib\site-packages\azure\mgmt\databricks\_serialization.py", line 1430, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\azure\mgmt\databricks\_serialization.py", line 1177, in rest_key_extractor
    return working_data.get(key)
           ^^^^^^^^^^^^^^^^
azure.core.exceptions.DeserializationError: (", AttributeError: 'list' object has no attribute 'get'", 'Unable to deserialize to object: type', AttributeError("'list' object has no attribute 'get'"))
>>>

**Comment by msyyc** [comment]
Hi @anogues I can't reproduce the error since I don't have that much resource to trigger pageable operation. Could you follow the following step to record the detailed log?
(1) add `logging_enable` in client like : 
```python
 DatabricksClient(..., logging_enable=True)
```
(2) follow https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/debug_guide.md to enable `debug` logging
nit: please remember to conceal the sensitive info in log.

**Comment by msyyc** [comment]
After debugging, I find the root cause is that service doesn't follow [pageable pattern](http://azure.github.io/autorest/extensions/#x-ms-pageable)
(1) list_by_resoure_group works and its related swagger definition is : https://github.com/Azure/azure-rest-api-specs/blob/ac98588da3cf3c3e043568adc8a6cc122ad8d6a7/specification/databricks/resource-manager/Microsoft.Databricks/preview/2022-04-01-preview/databricks.json#L256
response from server:
![image](https://github.com/Azure/azure-sdk-for-python/assets/70930885/54f97d69-9235-47c1-b38b-9fb29fcbd41c)
(2) list_by_subscription doesn't work and its swagger definition: https://github.com/Azure/azure-rest-api-specs/blob/ac98588da3cf3c3e043568adc8a6cc122ad8d6a7/specification/databricks/resource-manager/Microsoft.Databricks/preview/2022-04-01-preview/databricks.json#L37

response from server:

![image](https://github.com/Azure/azure-sdk-for-python/assets/70930885/ffdd3352-1832-4bb6-a82a-101fee5d3ab9)

We can see that (2) doesn't follow pageable pattern.
