### ISSUE TITLE
azure-cosmos async ContainerClient enable_cross_partition_query fails on 4.4.0 but works on 4.3.1

### ISSUE THREAD

**Issue by erewokMF** [Azure/azure-sdk-for-python#30735]
- **Package Name**: `azure-cosmos`
- **Package Version**:  `4.4.0.`
- **Operating System**: OSX & Debian Container
- **Python Version**:  3.11.3

**Describe the bug**
Async Cosmos ContainerClient `query_items` method no longer successfully accepts the kwarg `enable_cross_partition_query=True`. It actually raises an exception _inside_ the library `aiohttp` so it looks like this parameter is getting erroneously passed into requests made by that library instead. 

**To Reproduce**
Consider the following script [adapted from async samples](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cosmos/azure-cosmos/samples/examples_async.py):

```python

import asyncio
import os

from azure.cosmos import exceptions, CosmosClient
from azure.cosmos.aio import CosmosClient
from azure.identity.aio import DefaultAzureCredential

endpoint = os.environ["COSMOS_ENDPOINT"]
dbname = os.environ["COSMOS_DBNAME"]
container_name = os.environ["COSMOS_CONTAINER"]

async def examples_async():
    credential = DefaultAzureCredential(exclude_managed_identity_credential=True)
    async with CosmosClient(endpoint, credential=credential) as client:
        database = client.get_database_client(dbname)
        try:
            container = database.get_container_client(container_name)
        except exceptions.CosmosHttpResponseError:
            raise ValueError("Container client cannot be constructed")

        async for item in container.query_items(
                query='SELECT * from applications c where c.metadata.response_id = "1234"',
                enable_cross_partition_query=True,
        ):
            pass
        print("No exception")


if __name__ == "__main__":
    asyncio.run(examples_async())
```

When run with `4.4.0` I see the following:

```sh
❯ poetry update
Updating dependencies
Resolving dependencies... (89.5s)

Writing lock file

Package operations: 0 installs, 1 update, 0 removals

  • Updating azure-cosmos (4.3.1 -> 4.4.0)

❯ poetry run python ~/workspace/cosmos_cross_partition_fail.py
Traceback (most recent call last):
  File "~/workspace/cosmos_cross_partition_fail.py", line 32, in <module>
    asyncio.run(examples_async())
  File "~/.pyenv/versions/3.11.1/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/3.11.1/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/3.11.1/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "~/workspace/cosmos_cross_partition_fail.py", line 24, in examples_async
    async for item in container.query_items(
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/core/async_paging.py", line 141, in __anext__
    return await self.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/core/async_paging.py", line 144, in __anext__
    self._page = await self._page_iterator.__anext__()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/core/async_paging.py", line 94, in __anext__
    self._response = await self._get_next(self.continuation_token)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/cosmos/aio/_query_iterable_async.py", line 102, in _fetch_next
    block = await self._ex_context.fetch_next_block()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/cosmos/_execution_context/aio/execution_dispatcher.py", line 89, in fetch_next_block
    return await self._execution_context.fetch_next_block()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/cosmos/_execution_context/aio/base_execution_context.py", line 82, in fetch_next_block
    return await self._fetch_next_block()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/cosmos/_execution_context/aio/base_execution_context.py", line 170, in _fetch_next_block
    return await self._fetch_items_helper_with_retries(self._fetch_function)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/cosmos/_execution_context/aio/base_execution_context.py", line 144, in _fetch_items_helper_with_retries
    return await _retry_utility_async.ExecuteAsync(self._client, self._client._global_endpoint_manager, callback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/cosmos/aio/_retry_utility_async.py", line 85, in ExecuteAsync
    result = await ExecuteFunctionAsync(function, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/cosmos/aio/_retry_utility_async.py", line 144, in ExecuteFunctionAsync
    return await function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/cosmos/_execution_context/aio/base_execution_context.py", line 142, in callback
    return await self._fetch_items_helper_no_retries(fetch_function)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/cosmos/_execution_context/aio/base_execution_context.py", line 125, in _fetch_items_helper_no_retries
    (fetched_items, response_headers) = await fetch_function(new_options)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/cosmos/aio/_cosmos_client_connection_async.py", line 1783, in fetch_fn
    await self.__QueryFeed(
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/cosmos/aio/_cosmos_client_connection_async.py", line 2352, in __QueryFeed
    result, self.last_response_headers = await self.__Post(path, request_params, query, req_headers, **kwargs)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/cosmos/aio/_cosmos_client_connection_async.py", line 752, in __Post
    return await asynchronous_request.AsynchronousRequest(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/cosmos/aio/_asynchronous_request.py", line 175, in AsynchronousRequest
    return await _retry_utility_async.ExecuteAsync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/cosmos/aio/_retry_utility_async.py", line 83, in ExecuteAsync
    result = await ExecuteFunctionAsync(function, global_endpoint_manager, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/cosmos/aio/_retry_utility_async.py", line 144, in ExecuteFunctionAsync
    return await function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/cosmos/aio/_asynchronous_request.py", line 100, in _Request
    response = await _PipelineRunFunction(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/cosmos/aio/_asynchronous_request.py", line 141, in _PipelineRunFunction
    return await pipeline_client._pipeline.run(request, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/core/pipeline/_base_async.py", line 201, in run
    return await first_node.send(pipeline_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/core/pipeline/_base_async.py", line 67, in send
    response = await self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/core/pipeline/_base_async.py", line 67, in send
    response = await self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/core/pipeline/_base_async.py", line 67, in send
    response = await self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 1 more time]
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/cosmos/aio/_retry_utility_async.py", line 177, in send
    response = await self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/cosmos/aio/_auth_policy_async.py", line 123, in send
    response = await self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/core/pipeline/_base_async.py", line 67, in send
    response = await self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/core/pipeline/_base_async.py", line 67, in send
    response = await self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/core/pipeline/_base_async.py", line 67, in send
    response = await self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 1 more time]
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/core/pipeline/_base_async.py", line 102, in send
    await self._sender.send(request.http_request, **request.context.options),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/azure/core/pipeline/transport/_aiohttp.py", line 238, in send
    result = await self.session.request(  # type: ignore
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/workspace/web/direct-app/.venv/lib/python3.11/site-packages/aiohttp/client.py", line 354, in request
    return _RequestContextManager(self._request(method, url, **kwargs))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ClientSession._request() got an unexpected keyword argument 'enable_cross_partition_query'
```

When I downgrade to `4.3.1` I see the following:

```sh
❯ poetry update
Updating dependencies
Resolving dependencies... (101.7s)
Writing lock file
Package operations: 0 installs, 1 update, 0 removals
  • Updating azure-cosmos (4.4.0 -> 4.3.1)
❯ poetry run python ~/workspace/cosmos_cross_partition_fail.py
No exception
```

**Expected behavior**
No exception

**Comment by kashifkhan** [comment]
Thank you for the feedback @erewokMF . We will investigate and get back to you asap.

**Comment by simorenoh** [comment]
Hi @erewokMF thank you for pointing this out. We have actually never supported the option for the async client, the fact it even worked before is not ideal. The logic we have had in place since the inception of the async container has been that we only require a partition key to be passed, and if it isn't passed we do a cross partition query - users do not need to pass `enable_cross_partition_query`. That's why we also don't have the kwarg in the method description: 
<img width="359" alt="image" src="https://github.com/Azure/azure-sdk-for-python/assets/30335873/f9424ae9-b4d0-4079-8107-f8e8ffdcad83">
I'll go ahead and update the samples to reflect this.

**Comment by erewokMF** [comment]
Ah, that makes sense actually. I read the `ContainerProxy` definition and noticed that the kwarg isn't among those listed there, so at first I thought "I'll just pull this out." However, when I looked at the example it was in there and so I figured, "it's probably important to keep." At any rate, when I tested it yesterday my code appeared to perform the same without the kwarg, but I didn't have enough context to know if that was reliable.

**Comment by erewokMF** [comment]
I have amended our app using your comments. Thanks for your help. I would be fine with closing this ticket (unless you want to leave it open to track the examples fix).
