### ISSUE TITLE
Fail to run AML jobs locally on macos

### ISSUE THREAD

**Issue by waqassiddiqi** [Azure/azure-sdk-for-python#31180]
- **Package Name**: azure-ai-ml
- **Package Version**: 1.8.0
- **Operating System**: macos
- **Python Version**: 3.9.17

**Describe the bug**
Fail to run AML jobs locally, works fine when remote machine is selected. The error I am getting is:
`RuntimeError: Login to Docker registry 'mcr.microsoft.com' failed. See error message: 'username'
`

**To Reproduce**
1. Submit a job of type `command` with `compute` set to `local`
```
job = command(
        experiment_name=args.job_name,
        inputs=job_inputs,
        code="./Model/code/train",
        command="python train_script_v2.py --data ${{inputs.data}}",
        environment=f"{training_env_name}@latest",
        compute="local"
    )
``` 

**Expected behavior**
Submitted job to run locally and logs and other related stuff can be viewed via AML workspace under jobs.

**Complete stack trace**
```
Traceback (most recent call last):
  File "/Users/waqas/opt/miniconda3/envs/env_v1/lib/python3.9/site-packages/azure/ai/ml/operations/_local_job_invoker.py", line 230, in get_docker_client
    username=registry["username"],
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/train/build_v2.py", line 85, in <module>
    run(args=args)
  File "/train/build_v2.py", line 69, in run
    submitted_job = ml_client.create_or_update(job)
  File "/Users/waqas/opt/miniconda3/envs/env_v1/lib/python3.9/site-packages/azure/ai/ml/_ml_client.py", line 903, in create_or_update
    return _create_or_update(entity, self._operation_container.all_operations, **kwargs)
  File "/Users/waqas/opt/miniconda3/envs/env_v1/lib/python3.9/functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/waqas/opt/miniconda3/envs/env_v1/lib/python3.9/site-packages/azure/ai/ml/_ml_client.py", line 961, in _
    return operations[AzureMLResourceType.JOB].create_or_update(entity, **kwargs)
  File "/Users/waqas/opt/miniconda3/envs/env_v1/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/Users/waqas/opt/miniconda3/envs/env_v1/lib/python3.9/site-packages/azure/ai/ml/_telemetry/activity.py", line 337, in wrapper
    return_value = f(*args, **kwargs)
  File "/Users/waqas/opt/miniconda3/envs/env_v1/lib/python3.9/site-packages/azure/ai/ml/operations/_job_operations.py", line 609, in create_or_update
    raise ex
  File "/Users/waqas/opt/miniconda3/envs/env_v1/lib/python3.9/site-packages/azure/ai/ml/operations/_job_operations.py", line 573, in create_or_update
    snapshot_id = start_run_if_local(
  File "/Users/waqas/opt/miniconda3/envs/env_v1/lib/python3.9/site-packages/azure/ai/ml/operations/_local_job_invoker.py", line 403, in start_run_if_local
    cr_helper.get_bootstrapper_binary(bootstrapper_info)
  File "/Users/waqas/opt/miniconda3/envs/env_v1/lib/python3.9/site-packages/azure/ai/ml/operations/_local_job_invoker.py", line 298, in get_bootstrapper_binary
    docker_client = self.get_docker_client(registry)
  File "/Users/waqas/opt/miniconda3/envs/env_v1/lib/python3.9/site-packages/azure/ai/ml/operations/_local_job_invoker.py", line 235, in get_docker_client
    raise RuntimeError(self.DOCKER_LOGIN_FAILURE_MSG.format(registry["url"], e))
RuntimeError: Login to Docker registry 'mcr.microsoft.com' failed. See error message: 'username'
```

**Comment by waqassiddiqi** [comment]
@kashifkhan any update of this please?

**Comment by diondrapeck** [comment]
@waqassiddiqi Thanks for bringing this to our attention. I have linked a PR to fix this issue.
