### ISSUE TITLE
Batch scoring for object detection only working for YOLOv5 but not RetinaNet or Faster R-CNN

### ISSUE THREAD

**Issue by jesstytam** [Azure/azure-sdk-for-python#31361]
- **Package Name**: Python sdk v.2
- **Package Version**: 2
- **Operating System**: MLstudio notebook
- **Python Version**: notebook is 3.10, but environment is 3.7

**Describe the bug**

I am deploying my trained object detectors for testing but have run into the problem that the only my YOLOv5 detectors are running successfully. I tried using the GUI instead of coding in the notebook, but the same problem is still persisting. 

Here is the error from the `job_error.txt` file:

```
2023-07-27T05:57:40.285984 The process001 on node 0 failed on mini batch 784 with error: Traceback (most recent call last): 
  File "/mnt/azureml/cr/j/ece1e14b5be44a2c9d568468d9fc7182/exe/wd/driver/azureml_user/parallel_run/payload_thread.py", line 294, in process_task
    self.process_mini_batch(task) 
  File "/mnt/azureml/cr/j/ece1e14b5be44a2c9d568468d9fc7182/exe/wd/driver/azureml_user/parallel_run/payload_thread.py", line 121, in process_mini_batch
    score_output = processor.process_mini_batch(*args)
  File "/mnt/azureml/cr/j/ece1e14b5be44a2c9d568468d9fc7182/exe/wd/driver/azureml_user/parallel_run/task_processor.py", line 245, in process_mini_batch
    score_output = score_module.call_run(inputs, mini_batch_context)
  File "/mnt/azureml/cr/j/ece1e14b5be44a2c9d568468d9fc7182/exe/wd/driver/azureml_common/parallel_run/stderr_converter.py", line 29, in wrapper
    res = method(self, *args, **kwargs)
  File "/mnt/azureml/cr/j/ece1e14b5be44a2c9d568468d9fc7182/exe/wd/driver/azureml_user/parallel_run/score_module.py", line 239, in call_run
    return self.run(*args)
  File "/mnt/azureml/cr/j/ece1e14b5be44a2c9d568468d9fc7182/exe/wd/batch_scoring.py", line 55, in run
    result = run_inference_batch(model, mini_batch, _score_with_model, batch_size)
  File "/azureml-envs/azureml_599e3a532f47e0b00ca7870f50b0a575/lib/python3.7/site-packages/azureml/automl/dnn/vision/common/model_export_utils.py", line 440, in run_inference_batch
    **kwargs)
  File "/azureml-envs/azureml_599e3a532f47e0b00ca7870f50b0a575/lib/python3.7/site-packages/azureml/automl/dnn/vision/object_detection_yolo/writers/score.py", line 77, in _score_with_model
    img_size = model_wrapper.specs[YoloLiterals.IMG_SIZE]
TypeError: 'NoneType' object is not subscriptable
```

**To Reproduce**
Steps to reproduce the behavior: (using the GUI so that hopefully it's easier to reproduce)
1. create environment from the `conda_env_v_1_0_0.yml` file:

```
channels:
  - conda-forge
  - cerebis
  - pytorch
dependencies:
  - python=3.7
  - pip=21.3.1
  - numpy~=1.21.6
  - libffi=3.3
  - pycocotools=2.0.2
  - shap=0.39.0
  - recordclass=0.14.3
  - llvmlite=0.36.0
  - pip:
      - azureml-core==1.48.0
      - azureml-mlflow==1.48.0
      - azureml-dataset-runtime==1.48.0
      - azureml-telemetry==1.48.0
      - azureml-responsibleai==1.48.0
      - azureml-automl-core==1.48.0
      - azureml-automl-runtime==1.48.0.post1
      - azureml-train-automl-client==1.48.0
      - azureml-defaults==1.48.0
      - azureml-interpret==1.48.0
      - azureml-train-automl-runtime==1.48.0
      - azureml-automl-dnn-vision==1.48.0
      - azureml-dataprep>=2.24.4
name: project_environment
```

2. deploy trained model to batch endpoint
3. create job from the batch endpoint using a folder with images from the datastore

**Expected behavior**
Inferencing would run to completion.

**Screenshots**
Here is my scoring script:
![image](https://github.com/Azure/azure-sdk-for-python/assets/51732676/c7e46d24-b164-4414-af86-ac2cf7dec13f)

**Comment by kashifkhan** [comment]
Thank you for the feedback @jesstytam . We will investigate and get back to you asap. 

cc @azureml-github

**Comment by jesstytam** [comment]
Any updates on this? :)

**Comment by jesstytam** [comment]
Hi! just wondering if there are any solutions to this issue?

**Comment by hswang-wang** [comment]
Hi @jesstytam thank you for your feedback. In line 16 in your scoring script, could you please change `from azureml.automl.dnn.vision.object_detection_yolo.writers.score` to `from azureml.automl.dnn.vision.object_detection.writers.score` and try again?

**Comment by jesstytam** [comment]
That worked, thanks!
