### ISSUE TITLE
Async AutoLockRenewer doesn't renew locks and throws azure.servicebus.exceptions.MessageLockLostError

### ISSUE THREAD

**Issue by morwithp** [Azure/azure-sdk-for-python#31427]
- **Package Name**: azure-servicebus
- **Package Version**: 7.11.1
- **Operating System**: Linux
- **Python Version**: 3.10

**Describe the bug**
I have an async application that listens to messages in a topic and runs some heavy CPU operations on each message.
In my application I'm using `azure.servicebus.aio.ServiceBusClient` to create the servicebus client, `azure.servicebus.aio.AutoLockRenewer` to automatically renew the lock on the messages and `azure.servicebus.aio.ServiceBusReceiver` to register to the topic and receive the messages.

In some of the cases, although setting an heigh value for the `AutoLockRenewer`'s `max_lock_renewal_duration` param and completing the message handle before it passes, I get the error `azure.servicebus.exceptions.MessageLockLostError: The lock on the message lock has expired.` when calling `ServiceBusReceiver`'s `complete_message()`.

Handling each message consumes lots of CPU - it includes processing big file from storage, and uploading data asynchronously back to the storage.  
My assumption was that the default 10 seconds for the renewer's `_renew_period` was too small and the lock renewal was not able to happen before the lock expires. So as a workaround I overwritten this value with an higher value which reduced the amount of times the exception is throws, but unfortunately it still happens sometimes.

**To Reproduce**
The following code snippet describes my usage in the async client and message handling - 

```
import asyncio
from typing import Callable, Awaitable

from azure.identity.aio import DefaultAzureCredential as AsyncDefaultAzureCredential
from azure.servicebus import ServiceBusMessage
from azure.servicebus.aio import ServiceBusClient as AsyncServiceBusClient, \
    AutoLockRenewer as AsyncAutoLockRenewer


async def async_listen_to_queue(callback: Callable[[ServiceBusMessage], Awaitable[None]], topic_name: str,
                                subscription_name: str,
                                message_batch_size: int, handle_timeout_min: int,
                                listen_timeout_min: int, session_id: str = None) -> None:
    async with AsyncServiceBusClient(
            fully_qualified_namespace=f"my_sb.servicebus.windows.net",
            credential=AsyncDefaultAzureCredential()) as async_client:
        async with AsyncAutoLockRenewer(max_lock_renewal_duration=handle_timeout_min * 60) as auto_lock_renewer:
            async with async_client.get_subscription_receiver(topic_name=topic_name,
                                                                           subscription_name=subscription_name,
                                                                           auto_lock_renewer=auto_lock_renewer,
                                                                           max_wait_time=listen_timeout_min * 60,
                                                                           session_id=session_id) as receiver:
                should_keep_listening = True
                while should_keep_listening:
                    received_msgs = await receiver.receive_messages(max_message_count=message_batch_size)
                    for msg in received_msgs:
                        msg_handling_succeeded = False
                        try:
                            await callback(msg)
                            msg_handling_succeeded = True
                        except Exception as e:
                            print(f"Failed to handle ServiceBus message. msg={msg}. error={e}")
                        finally:
                            if msg_handling_succeeded:
                                await receiver.complete_message(msg)
                            else:
                                await receiver.abandon_message(msg)


async def callback_example(msg: ServiceBusMessage):
    print(msg)
    await asyncio.sleep(10)


async def run_async_receiver():
    await async_listen_to_queue(
        callback=callback_example,
        topic_name="my_topic",
        subscription_name="my_subscription",
        message_batch_size=3,
        handle_timeout_min=15,
        listen_timeout_min=2
    )


if __name__ == '__main__':
    asyncio.run(run_async_receiver())
```

**Expected behavior**
Messages are being consumed, handled and completed as long as they handled in the defined `max_lock_renewal_duration` of the `AutoLockRenewer`. `azure.servicebus.exceptions.MessageLockLostError` error is thrown if message handling too longer.

**Comment by kashifkhan** [comment]
Thank you for the feedback @morwithp . We will investigate and get back to you asap.

**Comment by timgabrhel** [comment]
I am running in to this exact same issue with v7.11.1. Are there any updates?

**Comment by kashifkhan** [comment]
We will be working on this issue during this sprint. Ill update this issue with a linked PR once we have a solution. 

Can yall also share any debug level logs that can help us understand the flow of activity behind the scenes ?

**Comment by timgabrhel** [comment]
I was just able to resolve this. My issue was that the core code that was being worked on was a synchronous method and presumably blocking the main thread from doing any processing. I would only ever see the `DEBUG:azure.servicebus.aio._async_auto_lock_renewer:Running async lock auto-renew for XXX seconds` (from the `_async_auto_lock_renewer.py` in the logs _after_ processing completed. 

My solution was to run my code on the `ThreadPoolExecutor`.
```
_executor = ThreadPoolExecutor()
...
loop = asyncio.get_event_loop()
ingest_outputs = await loop.run_in_executor(_executor, doWork, doWorkParam1)           
```

**Comment by kashifkhan** [comment]
Thanks for the update @timgabrhel. Is this the case for you as well @morwithp where somewhere else in the flow there is sync code that is blocking the main thread ?

**Comment by morwithp** [comment]
@kashifkhan 
According to @timgabrhel's comment, do I need to run my callback each time in a separate thread? My code snippet is quite similar to the usage sample you publish [here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/servicebus/azure-servicebus/samples/async_samples/auto_lock_renew_async.py#L26) and in both of them the message is registered in the lock_renewer and then processed in the same thread.

AFAIK the synchronized version of `AutoLockRenewer` runs in a separate threads so this issue can't happen there.

Maybe I'm missing something regarding the async flow

**Comment by timgabrhel** [comment]
@morwithp I would try enabling debug logging and see if you're seeing this debug log statement as the renewer enters the while loop to monitor the renewable. If you're not seeing it until after your callback completes, then the host thread is being blocked.

https://github.com/Azure/azure-sdk-for-python/blob/1727c7aa8268fa4bdc88aef462e7106845900b79/sdk/servicebus/azure-servicebus/azure/servicebus/aio/_async_auto_lock_renewer.py#L119

**Comment by morwithp** [comment]
```
INFO:azure.identity.aio._credentials.environment:No environment configuration found.
INFO:azure.identity.aio._credentials.managed_identity:ManagedIdentityCredential will use IMDS
INFO:azure.servicebus._pyamqp.aio._connection_async:Connection state changed: None -> <ConnectionState.START: 0>
INFO:azure.servicebus._pyamqp.aio._connection_async:Connection state changed: <ConnectionState.START: 0> -> <ConnectionState.HDR_SENT: 2>
INFO:azure.servicebus._pyamqp.aio._connection_async:Connection state changed: <ConnectionState.HDR_SENT: 2> -> <ConnectionState.HDR_SENT: 2>
INFO:azure.servicebus._pyamqp.aio._connection_async:Connection state changed: <ConnectionState.HDR_SENT: 2> -> <ConnectionState.OPEN_PIPE: 4>
INFO:azure.servicebus._pyamqp.aio._session_async:Session state changed: <SessionState.UNMAPPED: 0> -> <SessionState.BEGIN_SENT: 1>
INFO:azure.servicebus._pyamqp.aio._link_async:Link state changed: <LinkState.DETACHED: 0> -> <LinkState.ATTACH_SENT: 1>
INFO:azure.servicebus._pyamqp.aio._management_link_async:Management link receiver state changed: <LinkState.DETACHED: 0> -> <LinkState.ATTACH_SENT: 1>
INFO:azure.servicebus._pyamqp.aio._link_async:Link state changed: <LinkState.DETACHED: 0> -> <LinkState.ATTACH_SENT: 1>
INFO:azure.servicebus._pyamqp.aio._management_link_async:Management link sender state changed: <LinkState.DETACHED: 0> -> <LinkState.ATTACH_SENT: 1>
INFO:azure.servicebus._pyamqp.aio._connection_async:Connection state changed: <ConnectionState.OPEN_PIPE: 4> -> <ConnectionState.OPEN_SENT: 7>
INFO:azure.servicebus._pyamqp.aio._connection_async:Connection state changed: <ConnectionState.OPEN_SENT: 7> -> <ConnectionState.OPENED: 9>
INFO:azure.servicebus._pyamqp.aio._session_async:Session state changed: <SessionState.BEGIN_SENT: 1> -> <SessionState.MAPPED: 3>
INFO:azure.servicebus._pyamqp.aio._link_async:Link state changed: <LinkState.ATTACH_SENT: 1> -> <LinkState.ATTACHED: 3>
INFO:azure.servicebus._pyamqp.aio._management_link_async:Management link receiver state changed: <LinkState.ATTACH_SENT: 1> -> <LinkState.ATTACHED: 3>
INFO:azure.servicebus._pyamqp.aio._link_async:Link state changed: <LinkState.ATTACH_SENT: 1> -> <LinkState.ATTACHED: 3>
INFO:azure.servicebus._pyamqp.aio._management_link_async:Management link sender state changed: <LinkState.ATTACH_SENT: 1> -> <LinkState.ATTACHED: 3>
INFO:azure.servicebus._pyamqp.aio._cbs_async:CBS completed opening with status: <ManagementOpenResult.OK: 1>
INFO:azure.core.pipeline.policies.http_logging_policy:Request URL: 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=REDACTED&resource=REDACTED'
Request method: 'GET'
Request headers:
    'User-Agent': 'azsdk-python-identity/1.13.0 Python/3.10.9 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31)'
No body was attached to the request
INFO:azure.identity.aio._credentials.chained:DefaultAzureCredential acquired a token from AzureCliCredential
INFO:azure.servicebus._pyamqp.aio._link_async:Link state changed: <LinkState.DETACHED: 0> -> <LinkState.ATTACH_SENT: 1>
INFO:azure.servicebus._pyamqp.aio._link_async:Link state changed: <LinkState.ATTACH_SENT: 1> -> <LinkState.ATTACHED: 3>
Got message, sleeping for 6 minutes
DEBUG:azure.servicebus.aio._async_auto_lock_renewer:Running async lock auto-renew for 900 seconds
DEBUG:azure.servicebus.aio._async_auto_lock_renewer:10 seconds or less until lock expires - auto renewing.
INFO:azure.servicebus._pyamqp.aio._link_async:Link state changed: <LinkState.DETACHED: 0> -> <LinkState.ATTACH_SENT: 1>
INFO:azure.servicebus._pyamqp.aio._management_link_async:Management link receiver state changed: <LinkState.DETACHED: 0> -> <LinkState.ATTACH_SENT: 1>
INFO:azure.servicebus._pyamqp.aio._link_async:Link state changed: <LinkState.DETACHED: 0> -> <LinkState.ATTACH_SENT: 1>
INFO:azure.servicebus._pyamqp.aio._management_link_async:Management link sender state changed: <LinkState.DETACHED: 0> -> <LinkState.ATTACH_SENT: 1>
INFO:azure.servicebus._pyamqp.aio._link_async:Link state changed: <LinkState.ATTACH_SENT: 1> -> <LinkState.ATTACHED: 3>
INFO:azure.servicebus._pyamqp.aio._management_link_async:Management link receiver state changed: <LinkState.ATTACH_SENT: 1> -> <LinkState.ATTACHED: 3>
INFO:azure.servicebus._pyamqp.aio._link_async:Link state changed: <LinkState.ATTACH_SENT: 1> -> <LinkState.ATTACHED: 3>
INFO:azure.servicebus._pyamqp.aio._management_link_async:Management link sender state changed: <LinkState.ATTACH_SENT: 1> -> <LinkState.ATTACHED: 3>
DEBUG:azure.servicebus.aio._async_auto_lock_renewer:10 seconds or less until lock expires - auto renewing.
DEBUG:azure.servicebus.aio._async_auto_lock_renewer:10 seconds or less until lock expires - auto renewing.
DEBUG:azure.servicebus.aio._async_auto_lock_renewer:10 seconds or less until lock expires - auto renewing.
DEBUG:azure.servicebus.aio._async_auto_lock_renewer:10 seconds or less until lock expires - auto renewing.
DEBUG:azure.servicebus.aio._async_auto_lock_renewer:10 seconds or less until lock expires - auto renewing.
DEBUG:azure.servicebus.aio._async_auto_lock_renewer:10 seconds or less until lock expires - auto renewing.
Done handling
INFO:azure.servicebus._pyamqp.aio._link_async:Link state changed: <LinkState.ATTACHED: 3> -> <LinkState.DETACH_SENT: 4>
INFO:azure.servicebus._pyamqp.aio._link_async:Link state changed: <LinkState.ATTACHED: 3> -> <LinkState.DETACH_SENT: 4>
INFO:azure.servicebus._pyamqp.aio._management_link_async:Management link receiver state changed: <LinkState.ATTACHED: 3> -> <LinkState.DETACH_SENT: 4>
INFO:azure.servicebus._pyamqp.aio._link_async:Link state changed: <LinkState.ATTACHED: 3> -> <LinkState.DETACH_SENT: 4>
INFO:azure.servicebus._pyamqp.aio._management_link_async:Management link sender state changed: <LinkState.ATTACHED: 3> -> <LinkState.DETACH_SENT: 4>
INFO:azure.servicebus._pyamqp.aio._link_async:Link state changed: <LinkState.ATTACHED: 3> -> <LinkState.DETACH_SENT: 4>
INFO:azure.servicebus._pyamqp.aio._management_link_async:Management link sender state changed: <LinkState.ATTACHED: 3> -> <LinkState.DETACH_SENT: 4>
INFO:azure.servicebus._pyamqp.aio._link_async:Link state changed: <LinkState.ATTACHED: 3> -> <LinkState.DETACH_SENT: 4>
INFO:azure.servicebus._pyamqp.aio._management_link_async:Management link receiver state changed: <LinkState.ATTACHED: 3> -> <LinkState.DETACH_SENT: 4>
INFO:azure.servicebus._pyamqp.aio._session_async:Session state changed: <SessionState.MAPPED: 3> -> <SessionState.END_SENT: 4>
INFO:azure.servicebus._pyamqp.aio._connection_async:Connection state changed: <ConnectionState.OPENED: 9> -> <ConnectionState.CLOSE_SENT: 11>
INFO:azure.servicebus._pyamqp.aio._connection_async:Connection state changed: <ConnectionState.CLOSE_SENT: 11> -> <ConnectionState.END: 13>
INFO:azure.servicebus._pyamqp.aio._session_async:Session state changed: <SessionState.END_SENT: 4> -> <SessionState.DISCARDING: 6>
INFO:azure.servicebus._pyamqp.aio._link_async:Link state changed: <LinkState.DETACH_SENT: 4> -> <LinkState.DETACHED: 0>
INFO:azure.servicebus._pyamqp.aio._management_link_async:Management link sender state changed: <LinkState.DETACH_SENT: 4> -> <LinkState.DETACHED: 0>
INFO:azure.servicebus._pyamqp.aio._link_async:Link state changed: <LinkState.DETACH_SENT: 4> -> <LinkState.DETACHED: 0>
INFO:azure.servicebus._pyamqp.aio._management_link_async:Management link receiver state changed: <LinkState.DETACH_SENT: 4> -> <LinkState.DETACHED: 0>
INFO:azure.servicebus._pyamqp.aio._link_async:Link state changed: <LinkState.DETACH_SENT: 4> -> <LinkState.DETACHED: 0>
INFO:azure.servicebus._pyamqp.aio._link_async:Link state changed: <LinkState.DETACH_SENT: 4> -> <LinkState.DETACHED: 0>
INFO:azure.servicebus._pyamqp.aio._management_link_async:Management link sender state changed: <LinkState.DETACH_SENT: 4> -> <LinkState.DETACHED: 0>
INFO:azure.servicebus._pyamqp.aio._link_async:Link state changed: <LinkState.DETACH_SENT: 4> -> <LinkState.DETACHED: 0>
INFO:azure.servicebus._pyamqp.aio._management_link_async:Management l
```

The logs are attached, you can see my log `Got message, sleeping for 6 minutes` when start handling the message and the second log `Done handling` before completing the message. 

It does seems that the autolock_renewer works in parallel to the message handling

**Comment by l0lawrence** [comment]
Hi @morwithp, as we are trying to reproduce what you are seeing -- a couple questions:

Just curious since it seems that the error has been less frequent since bumping the `max_lock_renewal_duration`. Is it possible that when you see the MessageLockLostError now your callback has taken a longer amount of time than what you have set on `max_lock_renewal_duration` or does the callback take the same amount of time always (like the `callback_example` you provided)?

For us to reproduce:
- Would you be able to provide debug level logs of when you are seeing this error?
- Have you changed the message lock duration on your messages to a different value (default is 30 seconds)?
- Were you previously running this program on another version of ServiceBus where you were not seeing any errors?

**Comment by morwithp** [comment]
Hi @l0lawrence 
The processing time doesn't take always the same amount of time, but it does always takes less than the configured `max_lock_renewal_duration`. In my original post, I said that the error became less frequent since I bumped the value of `_renew_period` (inside `azure.servicebus.aio._async_auto_lock_renewer.AutoLockRenewer`) and not the value of `max_lock_renewal_duration`.

My configured `max_lock_renewal_duration` is 900 seconds (15 minutes), also for the execution of the attached DEBUG logs.
This is the first time I try using the SB async client.

Debug logs - there are 2 messages handled here, I deducted our internal logs but you can see the 'start handling' logs each time we start working on a new message. The first messages completed successfully but the second failed with this error.
(sorry for attaching the logs like this, is there a better way?)
The aio errors at the end are not related I think, they are part of the azure-storage's async client
```
[37m[2023-08-20 10:54:27,_connection_async:184] - INFO: Connection state changed: None -> <ConnectionState.START: 0>[0m
[37m[2023-08-20 10:54:27,_connection_async:184] - INFO: Connection state changed: <ConnectionState.START: 0> -> <ConnectionState.HDR_SENT: 2>[0m
[37m[2023-08-20 10:54:27,_connection_async:184] - INFO: Connection state changed: <ConnectionState.HDR_SENT: 2> -> <ConnectionState.HDR_SENT: 2>[0m
[37m[2023-08-20 10:54:27,_connection_async:184] - INFO: Connection state changed: <ConnectionState.HDR_SENT: 2> -> <ConnectionState.OPEN_PIPE: 4>[0m
[37m[2023-08-20 10:54:27,_session_async:92] - INFO: Session state changed: <SessionState.UNMAPPED: 0> -> <SessionState.BEGIN_SENT: 1>[0m
[37m[2023-08-20 10:54:27,_link_async:127] - INFO: Link state changed: <LinkState.DETACHED: 0> -> <LinkState.ATTACH_SENT: 1>[0m
[37m[2023-08-20 10:54:27,_management_link_async:106] - INFO: Management link receiver state changed: <LinkState.DETACHED: 0> -> <LinkState.ATTACH_SENT: 1>[0m
[37m[2023-08-20 10:54:27,_link_async:127] - INFO: Link state changed: <LinkState.DETACHED: 0> -> <LinkState.ATTACH_SENT: 1>[0m
[37m[2023-08-20 10:54:27,_management_link_async:76] - INFO: Management link sender state changed: <LinkState.DETACHED: 0> -> <LinkState.ATTACH_SENT: 1>[0m
[37m[2023-08-20 10:54:27,_connection_async:184] - INFO: Connection state changed: <ConnectionState.OPEN_PIPE: 4> -> <ConnectionState.OPEN_SENT: 7>[0m
[37m[2023-08-20 10:54:28,_connection_async:184] - INFO: Connection state changed: <ConnectionState.OPEN_SENT: 7> -> <ConnectionState.OPENED: 9>[0m
[37m[2023-08-20 10:54:28,_session_async:92] - INFO: Session state changed: <SessionState.BEGIN_SENT: 1> -> <SessionState.MAPPED: 3>[0m
[37m[2023-08-20 10:54:28,_link_async:127] - INFO: Link state changed: <LinkState.ATTACH_SENT: 1> -> <LinkState.ATTACHED: 3>[0m
[37m[2023-08-20 10:54:28,_management_link_async:106] - INFO: Management link receiver state changed: <LinkState.ATTACH_SENT: 1> -> <LinkState.ATTACHED: 3>[0m
[37m[2023-08-20 10:54:28,_link_async:127] - INFO: Link state changed: <LinkState.ATTACH_SENT: 1> -> <LinkState.ATTACHED: 3>[0m
[37m[2023-08-20 10:54:28,_management_link_async:76] - INFO: Management link sender state changed: <LinkState.ATTACH_SENT: 1> -> <LinkState.ATTACHED: 3>[0m
[37m[2023-08-20 10:54:28,_cbs_async:102] - INFO: CBS completed opening with status: <ManagementOpenResult.OK: 1>[0m
[32m[2023-08-20 10:54:28,_cbs_async:171] - DEBUG: CBS update in progress. Token put time: 1692528868[0m
[32m[2023-08-20 10:54:28,_cbs_async:171] - DEBUG: CBS update in progress. Token put time: 1692528868[0m
[32m[2023-08-20 10:54:28,_cbs_async:134] - DEBUG: CBS Put token result (<ManagementExecuteOperationResult.OK: 0>), status code: 202, status_description: b'Accepted'.[0m
[32m[2023-08-20 10:54:28,_cbs_async:159] - DEBUG: CBS status check: state == <CbsAuthState.OK: 0>, expired == False, refresh required == False[0m
[37m[2023-08-20 10:54:28,_link_async:127] - INFO: Link state changed: <LinkState.DETACHED: 0> -> <LinkState.ATTACH_SENT: 1>[0m
[37m[2023-08-20 10:54:28,_link_async:127] - INFO: Link state changed: <LinkState.ATTACH_SENT: 1> -> <LinkState.ATTACHED: 3>[0m
[32m[2023-08-20 10:54:28,_cbs_async:159] - DEBUG: CBS status check: state == <CbsAuthState.OK: 0>, expired == False, refresh required == False[0m
[32m[2023-08-20 10:54:28,_cbs_async:159] - DEBUG: CBS status check: state == <CbsAuthState.OK: 0>, expired == False, refresh required == False[0m
[32m[2023-08-20 10:54:28,_cbs_async:159] - DEBUG: CBS status check: state == <CbsAuthState.OK: 0>, expired == False, refresh required == False[0m
[32m[2023-08-20 10:54:28,_cbs_async:159] - DEBUG: CBS status check: state == <CbsAuthState.OK: 0>, expired == False, refresh required == False[0m
[2023-08-20 10:54:28,878, service:30] <MainThread> :: INFO :: Start handling DEDUCTED
[2023-08-20 10:54:28,878, DEDUCTED
[2023-08-20 10:54:30,826, DEDUCTED
[2023-08-20 10:54:30,827, DEDUCTED
[2023-08-20 10:55:09,066, DEDUCTED
[2023-08-20 10:55:12,720, DEDUCTED
[2023-08-20 10:55:12,916, DEDUCTED
[2023-08-20 10:55:12,916, DEDUCTED
[2023-08-20 10:55:12,916, DEDUCTED
[2023-08-20 10:55:12,916, DEDUCTED
[32m[2023-08-20 10:55:12,_async_auto_lock_renewer:118] - DEBUG: Running async lock auto-renew for 900 seconds[0m
[32m[2023-08-20 10:55:12,_async_auto_lock_renewer:118] - DEBUG: Running async lock auto-renew for 900 seconds[0m
[32m[2023-08-20 10:55:12,_async_auto_lock_renewer:118] - DEBUG: Running async lock auto-renew for 900 seconds[0m
[32m[2023-08-20 10:55:12,_client_async:154] - DEBUG: Keeping 'ReceiveClientAsync' connection alive.[0m
[2023-08-20 10:55:14,525, DEDUCTED
[2023-08-20 10:55:14,525, DEDUCTED
[2023-08-20 10:55:15,097, service:30] <MainThread> :: INFO :: Start handling DEDUCTED
[2023-08-20 10:55:15,098, DEDUCTED
[2023-08-20 10:55:16,980, DEDUCTED
[2023-08-20 10:55:16,980, DEDUCTED
[2023-08-20 10:55:42,165, DEDUCTED
[2023-08-20 10:55:48,973, DEDUCTED
[2023-08-20 10:55:51,872, DEDUCTED
[2023-08-20 10:55:51,873, DEDUCTED
[2023-08-20 10:55:51,873, DEDUCTED
[2023-08-20 10:55:51,873, DEDUCTED
[32m[2023-08-20 10:55:51,_client_async:154] - DEBUG: Keeping 'ReceiveClientAsync' connection alive.[0m
[2023-08-20 10:55:52,694, DEDUCTED
[2023-08-20 10:55:52,694, DEDUCTED
[37m[2023-08-20 10:55:53,_link_async:127] - INFO: Link state changed: <LinkState.ATTACHED: 3> -> <LinkState.DETACH_SENT: 4>[0m
[37m[2023-08-20 10:55:53,_link_async:127] - INFO: Link state changed: <LinkState.ATTACHED: 3> -> <LinkState.DETACH_SENT: 4>[0m
[37m[2023-08-20 10:55:53,_management_link_async:106] - INFO: Management link receiver state changed: <LinkState.ATTACHED: 3> -> <LinkState.DETACH_SENT: 4>[0m
[37m[2023-08-20 10:55:53,_link_async:127] - INFO: Link state changed: <LinkState.ATTACHED: 3> -> <LinkState.DETACH_SENT: 4>[0m
[37m[2023-08-20 10:55:53,_management_link_async:76] - INFO: Management link sender state changed: <LinkState.ATTACHED: 3> -> <LinkState.DETACH_SENT: 4>[0m
[37m[2023-08-20 10:55:53,_session_async:92] - INFO: Session state changed: <SessionState.MAPPED: 3> -> <SessionState.END_SENT: 4>[0m
[37m[2023-08-20 10:55:53,_connection_async:184] - INFO: Connection state changed: <ConnectionState.OPENED: 9> -> <ConnectionState.CLOSE_SENT: 11>[0m
[37m[2023-08-20 10:55:53,_connection_async:184] - INFO: Connection state changed: <ConnectionState.CLOSE_SENT: 11> -> <ConnectionState.END: 13>[0m
[37m[2023-08-20 10:55:53,_session_async:92] - INFO: Session state changed: <SessionState.END_SENT: 4> -> <SessionState.DISCARDING: 6>[0m
[37m[2023-08-20 10:55:53,_link_async:127] - INFO: Link state changed: <LinkState.DETACH_SENT: 4> -> <LinkState.DETACHED: 0>[0m
[37m[2023-08-20 10:55:53,_management_link_async:76] - INFO: Management link sender state changed: <LinkState.DETACH_SENT: 4> -> <LinkState.DETACHED: 0>[0m
[37m[2023-08-20 10:55:53,_link_async:127] - INFO: Link state changed: <LinkState.DETACH_SENT: 4> -> <LinkState.DETACHED: 0>[0m
[37m[2023-08-20 10:55:53,_management_link_async:106] - INFO: Management link receiver state changed: <LinkState.DETACH_SENT: 4> -> <LinkState.DETACHED: 0>[0m
[37m[2023-08-20 10:55:53,_link_async:127] - INFO: Link state changed: <LinkState.DETACH_SENT: 4> -> <LinkState.DETACHED: 0>[0m
Traceback (most recent call last):
  File "/var/operation-records-handler/run.py", line 13, in <module>
    asyncio.run(listener.listen())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/.local/lib/python3.10/site-packages/messaging_client/async_client/listener/async_topic_listener.py", line 53, in listen
    await self.provider.async_listen_to_topic(callback=self.handle_message, topic_name=self.topic_name,
  File "/root/.local/lib/python3.10/site-packages/messaging_client/provider/azure/azure_provider.py", line 128, in async_listen_to_topic
    await self.__async_handle_messages(receiver, message_batch_size, callback, listen_strategy)
  File "/root/.local/lib/python3.10/site-packages/messaging_client/provider/azure/azure_provider.py", line 219, in __async_handle_messages
    await receiver.complete_message(msg)
  File "/root/.local/lib/python3.10/site-packages/azure/servicebus/aio/_servicebus_receiver_async.py", line 806, in complete_message
    await self._settle_message_with_retry(message, MESSAGE_COMPLETE)
  File "/root/.local/lib/python3.10/site-packages/azure/servicebus/aio/_servicebus_receiver_async.py", line 453, in _settle_message_with_retry
    raise MessageLockLostError(
azure.servicebus.exceptions.MessageLockLostError: The lock on the message lock has expired.
[31m[2023-08-20 10:55:53,base_events:1758] - ERROR: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f55865e4a30>[0m
/root/.local/lib/python3.10/site-packages/storage_client/client_async.py:21: RuntimeWarning: coroutine 'AsyncStorageAccountHostsMixin.close' was never awaited
[31m[2023-08-20 10:55:53,base_events:1758] - ERROR: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5586131cf0>[0m
[31m[2023-08-20 10:55:53,base_events:1758] - ERROR: Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f55865b30a0>, 1208933.048346278)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f55861329b0>[0m
```

**Comment by l0lawrence** [comment]
Hi @morwithp, from the above logs it seems like your callback is blocking the renewer from renewing the lock which is causing that second message to fail to complete. There are no `10 seconds or less until lock expires - auto renewing` logs that would indicate the renewer is running. Are there any sync blocking calls that would block threads from running in the background?

If you haven't already could you try using the ThreadPoolExecutor like @timgabrhel showed when running your code?

**Comment by morwithp** [comment]
Hi,
As you can see in my example, the callback is called with `await` so it will wait for the callback to complete. So I assume that if the LockRenewer doesn't run in a separate thread it will be blocked by my callback.
I can try using ThreadPoolExecutor but if it does work - does it mean I need to run my callback code in a separate thread? why?
Thanks

**Comment by l0lawrence** [comment]
With the threadPoolExecutor you would be using `run_in_executor` to run the callback in a separate thread. If your callback is blocking the autolockrenewer, `run_in_executor` will run it on a separate thread to avoid blocking the OS thread.

**Comment by morwithp** [comment]
Hi @l0lawrence,
I'm aware of what `run_in_executor` is doing, and I understand how this will solve my issue. My questions are - 
1. Why do I need to run my callback code in a separate thread? is this a requirement when using the async client? where is it specified? why your [code samples](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/servicebus/azure-servicebus/samples/async_samples/auto_lock_renew_async.py#L26) doesn't show it?
2. Why is it different from the sync client, there you don't need to run your callback in a separate thread and still the LockRenewer doesn't get blocked?

I feel like I'm missing something crucial here with the async implementation
Thanks you

**Comment by l0lawrence** [comment]
I'm glad this has solved your issue! 

1) It seems that your callback has blocking code in it, running the callback in a separate thread will prevent the event loop from being blocked so that it can run the autolock renewer. It is not a requirement to use a [ThreadPoolExecutor](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor) when running the async client, unless you have code that blocks the event loop. 

You bring up a good point, this is not specified anywhere. We are currently working on adding documentation that discusses thread safety and threading using the SDK. We also do have plans to add a sample that shows this scenario (we will link it here when completed). 

The code sample you specified does not show the use of a ThreadPoolExecutor because it is not running code that blocks the event loop. The CPU heavy operations that your callback is running are most likely taking over the entire event loop and preventing the autolock renewer from running. 

2) This is different from the sync client, which is running the autolock renewer using Threading. The async client is using asyncio.create_task() coroutines.
