### ISSUE TITLE
UnboundLocalError: local variable 'resp' referenced before assignment

### ISSUE THREAD

**Issue by GarimaAgrawalAccenture** [Azure/azure-sdk-for-python#31450]
I am trying to run a pipeline using vscode and getting below error, can you help me to fix is? is there something I need to set in aml workspace settings?

Traceback (most recent call last):
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\urllib3\connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Python\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\Python\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='graph.windows.net', port=443): Max retries exceeded with url: //8cb6142b-0f98-4eab-80a8-a54dd2681ccc/users/d112ad98-0f0b-43e4-b020-aec674848726?api-version=1.6 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\azureml\core\compute\computeinstance.py", line 958, in _get_user_display_name
    resp = ClientBase._execute_func(get_requests_session().get, endpoint, params=params, headers=headers)
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\azureml\_restclient\clientbase.py", line 375, in _execute_func
    return cls._execute_func_internal(
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\azureml\_restclient\clientbase.py", line 368, in _execute_func_internal
    left_retry = cls._handle_retry(back_off, left_retry, total_retry, error, logger, func)
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\azureml\_restclient\clientbase.py", line 400, in _handle_retry
    raise error
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\azureml\_restclient\clientbase.py", line 359, in _execute_func_internal
    response = func(*args, **kwargs)
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='graph.windows.net', port=443): Max retries exceeded with url: //8cb6142b-0f98-4eab-80a8-a54dd2681ccc/users/d112ad98-0f0b-43e4-b020-aec674848726?api-version=1.6 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\main.py", line 170, in <module>
    main()
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\main.py", line 156, in main
    train_pipeline = Pipeline(workspace=ws, steps=step_sequence)
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\azureml\core\_experiment_method.py", line 104, in wrapper    
    return init_func(self, *args, **kwargs)
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\azureml\pipeline\core\pipeline.py", line 180, in __init__    
    self._graph = self._graph_builder.build(self._name, steps, finalize=False)
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\azureml\pipeline\core\builder.py", line 1497, in build       
    graph = self.construct(name, steps)
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\azureml\pipeline\core\builder.py", line 1519, in construct   
    self.process_collection(steps)
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\azureml\pipeline\core\builder.py", line 1555, in process_collection
    builder.process_collection(collection)
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\azureml\pipeline\core\builder.py", line 1809, in process_collection
    nodes = self._base_builder.process_collection(item)
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\azureml\pipeline\core\builder.py", line 1549, in process_collection
    return self.process_step(collection)
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\azureml\pipeline\core\builder.py", line 1593, in process_step
    node = step.create_node(self._graph, self._default_datastore, self._context)
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\azureml\pipeline\steps\python_script_step.py", line 243, in create_node
    return super(PythonScriptStep, self).create_node(
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\azureml\pipeline\core\_python_script_step_base.py", line 151, in create_node
    _extract_compute_target_params(context, self._compute_target)
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\azureml\pipeline\core\_python_script_step_base.py", line 214, in _extract_compute_target_params
    compute_target_object = context.get_target(compute_target_name)
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\azureml\pipeline\core\_graph_context.py", line 60, in get_target
    self._targets = self._workspace.compute_targets
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\azureml\core\workspace.py", line 1069, in compute_targets    
    compute_target.name: compute_target for compute_target in ComputeTarget.list(self)}
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\azureml\core\compute\compute.py", line 546, in list
    env_obj = child.deserialize(workspace, env)
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\azureml\core\compute\computeinstance.py", line 643, in deserialize
    target._initialize(workspace, object_dict)
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\azureml\core\compute\computeinstance.py", line 131, in _initialize
    status.created_by_user_name = ComputeInstance._get_user_display_name(
  File "C:\Users\garima.g.agrawal\Documents\Standard ML Solution\.venv\lib\site-packages\azureml\core\compute\computeinstance.py", line 973, in _get_user_display_name
    if resp.status_code in [401, 403]:
UnboundLocalError: local variable 'resp' referenced before assignment

**Comment by GarimaAgrawalAccenture** [comment]
solved by other post solution by installing pip install pip-system-certs
