### ISSUE TITLE
Adding App Insights Exporter for Open Telemetry crashes Paged query in Azure Search SDK

### ISSUE THREAD

**Issue by tonybaloney** [Azure/azure-sdk-for-python#31470]
- **Package Name**:
```
azure-monitor-opentelemetry --pre
# opentelemetry-exporter-richconsole
opentelemetry-instrumentation-flask
opentelemetry-instrumentation-requests
opentelemetry-instrumentation-aiohttp-client
```

- **Package Version**: azure-monitor-opentelemetry
- **Operating System**: Linux
- **Python Version**: 3.10

**Describe the bug**

I'm trying to add Open Telemetry with the Azure App Insights exporter to a Flask application that calls out to Cognitive Search. I want to see traces to the backend calls in App Insights.

After adding App Insights, the app stops working because of an injected decorator (see trace)

I enabled the App Insights exporter like this:

```python
    provider = TracerProvider()
    trace.set_tracer_provider(provider)
    aiexporter = AzureMonitorTraceExporter(
        connection_string=os.environ["APPLICATIONINSIGHTS_CONNECTION_STRING"]
    )
    provider.add_span_processor(BatchSpanProcessor(aiexporter))
    # provider.add_span_processor(BatchSpanProcessor(RichConsoleSpanExporter()))

    FlaskInstrumentor().instrument_app(app, tracer_provider=provider)
    RequestsInstrumentor().instrument(tracer_provider=provider)
    AioHttpClientInstrumentor().instrument(tracer_provider=provider)
```

The crash log is: 
```
ERROR:root:Exception in /chat
Traceback (most recent call last):
  File "/tmp/8db94ab5bb43eb9/app.py", line 115, in chat
    r = impl.run(request.json["history"], request.json.get("overrides") or {})
  File "/tmp/8db94ab5bb43eb9/approaches/chatreadretrieveread.py", line 127, in run
    results = [doc[self.sourcepage_field] + ": " + nonewlines(doc[self.content_field]) for doc in r]
  File "/tmp/8db94ab5bb43eb9/approaches/chatreadretrieveread.py", line 127, in <listcomp>
    results = [doc[self.sourcepage_field] + ": " + nonewlines(doc[self.content_field]) for doc in r]
  File "/tmp/8db94ab5bb43eb9/antenv/lib/python3.10/site-packages/azure/search/documents/_paging.py", line 54, in __next__
    return next(self._page_iterator)
  File "/tmp/8db94ab5bb43eb9/antenv/lib/python3.10/site-packages/azure/core/paging.py", line 75, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/tmp/8db94ab5bb43eb9/antenv/lib/python3.10/site-packages/azure/search/documents/_paging.py", line 124, in _get_next_cb
    return self._client.documents.search_post(search_request=self._initial_query.request, **self._kwargs)
  File "/tmp/8db94ab5bb43eb9/antenv/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 87, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/tmp/8db94ab5bb43eb9/antenv/lib/python3.10/site-packages/azure/search/documents/_generated/operations/_documents_operations.py", line 793, in search_post
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: () Unknown field 'embedding' in vector field list.
Parameter name: vectorFields
Code:
Message: Unknown field 'embedding' in vector field list.
Parameter name: vectorFields
```

The installed packages with versions are

```default
[05:27:04+0000] Collecting azure-identity==1.13.0
[05:27:04+0000]   Using cached azure_identity-1.13.0-py3-none-any.whl (151 kB)
[05:27:04+0000] Collecting Flask==2.2.5
[05:27:04+0000]   Using cached Flask-2.2.5-py3-none-any.whl (101 kB)
[05:27:05+0000] Collecting langchain==0.0.187
[05:27:05+0000]   Using cached langchain-0.0.187-py3-none-any.whl (960 kB)
[05:27:05+0000] Collecting openai[datalib]==0.27.8
[05:27:05+0000]   Using cached openai-0.27.8-py3-none-any.whl (73 kB)
[05:27:05+0000] Collecting tiktoken==0.4.0
[05:27:05+0000]   Using cached tiktoken-0.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.7 MB)
[05:27:05+0000] Collecting azure-search-documents==11.4.0b6
[05:27:05+0000]   Using cached azure_search_documents-11.4.0b6-py3-none-any.whl (306 kB)
[05:27:06+0000] Collecting azure-storage-blob==12.14.1
[05:27:06+0000]   Using cached azure_storage_blob-12.14.1-py3-none-any.whl (383 kB)
[05:27:06+0000] Collecting azure-monitor-opentelemetry
[05:27:06+0000]   Using cached azure_monitor_opentelemetry-1.0.0b15-py2.py3-none-any.whl (97 kB)
[05:27:06+0000] Collecting opentelemetry-instrumentation-flask
[05:27:06+0000]   Using cached opentelemetry_instrumentation_flask-0.40b0-py3-none-any.whl (13 kB)
[05:27:06+0000] Collecting opentelemetry-instrumentation-requests
[05:27:06+0000]   Using cached opentelemetry_instrumentation_requests-0.40b0-py3-none-any.whl (11 kB)
[05:27:06+0000] Collecting opentelemetry-instrumentation-aiohttp-client
[05:27:06+0000]   Using cached opentelemetry_instrumentation_aiohttp_client-0.40b0-py3-none-any.whl (11 kB)
[05:27:06+0000] Collecting msal-extensions<2.0.0,>=0.3.0
[05:27:06+0000]   Using cached msal_extensions-1.0.0-py2.py3-none-any.whl (19 kB)
[05:27:06+0000] Collecting six>=1.12.0
[05:27:06+0000]   Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
[05:27:07+0000] Collecting azure-core<2.0.0,>=1.11.0
[05:27:07+0000]   Using cached azure_core-1.28.0-py3-none-any.whl (185 kB)
[05:27:07+0000] Collecting msal<2.0.0,>=1.20.0
[05:27:07+0000]   Using cached msal-1.23.0-py2.py3-none-any.whl (90 kB)
[05:27:09+0000] Collecting cryptography>=2.5
[05:27:09+0000]   Using cached cryptography-41.0.3-cp37-abi3-manylinux_2_28_x86_64.whl (4.3 MB)
[05:27:10+0000] Collecting Werkzeug>=2.2.2
[05:27:10+0000]   Using cached Werkzeug-2.3.6-py3-none-any.whl (242 kB)
[05:27:10+0000] Collecting click>=8.0
[05:27:10+0000]   Using cached click-8.1.6-py3-none-any.whl (97 kB)
[05:27:10+0000] Collecting Jinja2>=3.0
[05:27:10+0000]   Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
[05:27:11+0000] Collecting itsdangerous>=2.0
[05:27:11+0000]   Using cached itsdangerous-2.1.2-py3-none-any.whl (15 kB)
[05:27:12+0000] Collecting PyYAML>=5.4.1
[05:27:12+0000]   Using cached PyYAML-6.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (705 kB)
[05:27:13+0000] Collecting pydantic<2,>=1
[05:27:13+0000]   Using cached pydantic-1.10.12-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
[05:27:14+0000] Collecting dataclasses-json<0.6.0,>=0.5.7
[05:27:14+0000]   Using cached dataclasses_json-0.5.14-py3-none-any.whl (26 kB)
[05:27:16+0000] Collecting numpy<2,>=1
[05:27:16+0000]   Using cached numpy-1.25.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
[05:27:17+0000] Collecting openapi-schema-pydantic<2.0,>=1.2
[05:27:17+0000]   Using cached openapi_schema_pydantic-1.2.4-py3-none-any.whl (90 kB)
[05:27:24+0000] Collecting SQLAlchemy<3,>=1.4
[05:27:24+0000]   Using cached SQLAlchemy-2.0.19-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.7 MB)
[05:27:26+0000] Collecting requests<3,>=2
[05:27:26+0000]   Using cached requests-2.31.0-py3-none-any.whl (62 kB)
[05:27:26+0000] Collecting tenacity<9.0.0,>=8.1.0
[05:27:26+0000]   Using cached tenacity-8.2.2-py3-none-any.whl (24 kB)
[05:27:28+0000] Collecting numexpr<3.0.0,>=2.8.4
[05:27:28+0000]   Using cached numexpr-2.8.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (381 kB)
[05:27:29+0000] Collecting async-timeout<5.0.0,>=4.0.0
[05:27:29+0000]   Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
[05:27:33+0000] Collecting aiohttp<4.0.0,>=3.8.3
[05:27:33+0000]   Using cached aiohttp-3.8.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
[05:27:34+0000] Collecting tqdm
[05:27:34+0000]   Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
[05:27:34+0000] Collecting openpyxl>=3.0.7
[05:27:34+0000]   Using cached openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
[05:27:35+0000] Collecting pandas>=1.2.3
[05:27:35+0000]   Using cached pandas-2.0.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.3 MB)
[05:27:36+0000] Collecting pandas-stubs>=1.1.0.11
[05:27:36+0000]   Using cached pandas_stubs-2.0.2.230605-py3-none-any.whl (151 kB)
[05:27:39+0000] Collecting regex>=2022.1.18
[05:27:39+0000]   Using cached regex-2023.6.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (770 kB)
[05:27:40+0000] Collecting azure-common~=1.1
[05:27:40+0000]   Using cached azure_common-1.1.28-py2.py3-none-any.whl (14 kB)
[05:27:40+0000] Collecting isodate>=0.6.0
[05:27:40+0000]   Using cached isodate-0.6.1-py2.py3-none-any.whl (41 kB)
[05:27:40+0000] Collecting msrest>=0.7.1
[05:27:40+0000]   Using cached msrest-0.7.1-py3-none-any.whl (85 kB)
[05:27:40+0000] Collecting opentelemetry-api==1.19.0
[05:27:40+0000]   Using cached opentelemetry_api-1.19.0-py3-none-any.whl (57 kB)
[05:27:41+0000] Collecting wrapt<2.0.0,>=1.0.0
[05:27:41+0000]   Using cached wrapt-1.15.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (78 kB)
[05:27:41+0000] Collecting opentelemetry-sdk==1.19.0
[05:27:41+0000]   Using cached opentelemetry_sdk-1.19.0-py3-none-any.whl (103 kB)
[05:27:41+0000] Collecting azure-monitor-opentelemetry-exporter>=1.0.0b15
[05:27:41+0000]   Using cached azure_monitor_opentelemetry_exporter-1.0.0b15-py2.py3-none-any.whl (75 kB)
[05:27:41+0000] Collecting azure-core-tracing-opentelemetry~=1.0.0b10
[05:27:41+0000]   Using cached azure_core_tracing_opentelemetry-1.0.0b10-py3-none-any.whl (10 kB)
[05:27:42+0000] Collecting deprecated>=1.2.6
[05:27:42+0000]   Using cached Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)
[05:27:42+0000] Collecting importlib-metadata~=6.0
[05:27:42+0000]   Using cached importlib_metadata-6.8.0-py3-none-any.whl (22 kB)
[05:27:42+0000] Collecting typing-extensions>=3.7.4
[05:27:42+0000]   Using cached typing_extensions-4.7.1-py3-none-any.whl (33 kB)
[05:27:42+0000] Collecting opentelemetry-semantic-conventions==0.40b0
[05:27:42+0000]   Using cached opentelemetry_semantic_conventions-0.40b0-py3-none-any.whl (26 kB)
[05:27:43+0000] Collecting opentelemetry-instrumentation==0.40b0
[05:27:43+0000]   Using cached opentelemetry_instrumentation-0.40b0-py3-none-any.whl (25 kB)
[05:27:43+0000] Collecting opentelemetry-util-http==0.40b0
[05:27:43+0000]   Using cached opentelemetry_util_http-0.40b0-py3-none-any.whl (6.7 kB)
[05:27:43+0000] Collecting opentelemetry-instrumentation-wsgi==0.40b0
[05:27:43+0000]   Using cached opentelemetry_instrumentation_wsgi-0.40b0-py3-none-any.whl (12 kB)
[05:27:43+0000] Collecting packaging>=21.0
[05:27:43+0000]   Using cached packaging-23.1-py3-none-any.whl (48 kB)
[05:27:43+0000] Requirement already satisfied: setuptools>=16.0 in ./antenv/lib/python3.10/site-packages (from opentelemetry-instrumentation==0.40b0->opentelemetry-instrumentation-flask->-r requirements.txt (line 11)) (63.2.0)
[05:27:44+0000] Collecting frozenlist>=1.1.1
[05:27:44+0000]   Using cached frozenlist-1.4.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (225 kB)
[05:27:45+0000] Collecting yarl<2.0,>=1.0
[05:27:45+0000]   Using cached yarl-1.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (268 kB)
[05:27:45+0000] Collecting attrs>=17.3.0
[05:27:45+0000]   Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
[05:27:45+0000] Collecting aiosignal>=1.1.2
[05:27:45+0000]   Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
[05:27:47+0000] Collecting multidict<7.0,>=4.5
[05:27:47+0000]   Using cached multidict-6.0.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
[05:27:48+0000] Collecting charset-normalizer<4.0,>=2.0
[05:27:48+0000]   Using cached charset_normalizer-3.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (201 kB)
[05:27:48+0000] Collecting fixedint==0.1.6
[05:27:48+0000]   Using cached fixedint-0.1.6-py3-none-any.whl (12 kB)
[05:27:49+0000] Collecting cffi>=1.12
[05:27:50+0000]   Using cached cffi-1.15.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)
[05:27:50+0000] Collecting typing-inspect<1,>=0.4.0
[05:27:50+0000]   Using cached typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
[05:27:51+0000] Collecting marshmallow<4.0.0,>=3.18.0
[05:27:51+0000]   Using cached marshmallow-3.20.1-py3-none-any.whl (49 kB)
[05:27:52+0000] Collecting MarkupSafe>=2.0
[05:27:52+0000]   Using cached MarkupSafe-2.1.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
[05:27:53+0000] Collecting PyJWT[crypto]<3,>=1.0.0
[05:27:53+0000]   Using cached PyJWT-2.8.0-py3-none-any.whl (22 kB)
[05:27:54+0000] Collecting portalocker<3,>=1.0
[05:27:54+0000]   Using cached portalocker-2.7.0-py2.py3-none-any.whl (15 kB)
[05:27:54+0000] Collecting certifi>=2017.4.17
[05:27:54+0000]   Using cached certifi-2023.7.22-py3-none-any.whl (158 kB)
[05:27:54+0000] Collecting requests-oauthlib>=0.5.0
[05:27:54+0000]   Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
[05:27:55+0000] Collecting et-xmlfile
[05:27:55+0000]   Using cached et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
[05:27:56+0000] Collecting python-dateutil>=2.8.2
[05:27:56+0000]   Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
[05:27:56+0000] Collecting tzdata>=2022.1
[05:27:56+0000]   Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
[05:27:57+0000] Collecting pytz>=2020.1
[05:27:57+0000]   Using cached pytz-2023.3-py2.py3-none-any.whl (502 kB)
[05:27:57+0000] Collecting types-pytz>=2022.1.1
[05:27:57+0000]   Using cached types_pytz-2023.3.0.0-py3-none-any.whl (4.7 kB)
[05:27:58+0000] Collecting urllib3<3,>=1.21.1
[05:27:58+0000]   Using cached urllib3-2.0.4-py3-none-any.whl (123 kB)
[05:27:58+0000] Collecting idna<4,>=2.5
[05:27:58+0000]   Using cached idna-3.4-py3-none-any.whl (61 kB)
[05:28:00+0000] Collecting greenlet!=0.4.17
[05:28:00+0000]   Using cached greenlet-2.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (613 kB)
[05:28:00+0000] Collecting pycparser
[05:28:00+0000]   Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
[05:28:01+0000] Collecting zipp>=0.5
[05:28:01+0000]   Using cached zipp-3.16.2-py3-none-any.whl (7.2 kB)
[05:28:02+0000] Collecting oauthlib>=3.0.0
[05:28:02+0000]   Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
[05:28:02+0000] Collecting mypy-extensions>=0.3.0
[05:28:02+0000]   Using cached mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
[05:28:07+0000] Installing collected packages: types-pytz, pytz, fixedint, azure-common, zipp, wrapt, urllib3, tzdata, typing-extensions, tqdm, tenacity, six, regex, PyYAML, PyJWT, pycparser, portalocker, packaging, opentelemetry-util-http, opentelemetry-semantic-conventions, oauthlib, numpy, mypy-extensions, multidict, MarkupSafe, itsdangerous, idna, greenlet, frozenlist, et-xmlfile, click, charset-normalizer, certifi, attrs, async-timeout, yarl, Werkzeug, typing-inspect, SQLAlchemy, requests, python-dateutil, pydantic, pandas-stubs, openpyxl, numexpr, marshmallow, Jinja2, isodate, importlib-metadata, deprecated, cffi, aiosignal, tiktoken, requests-oauthlib, pandas, opentelemetry-api, openapi-schema-pydantic, Flask, dataclasses-json, cryptography, azure-core, aiohttp, opentelemetry-sdk, opentelemetry-instrumentation, openai, msrest, langchain, azure-search-documents, azure-core-tracing-opentelemetry, opentelemetry-instrumentation-wsgi, opentelemetry-instrumentation-requests, opentelemetry-instrumentation-aiohttp-client, msal, azure-storage-blob, azure-monitor-opentelemetry-exporter, opentelemetry-instrumentation-flask, msal-extensions, azure-monitor-opentelemetry, azure-identity
[05:29:11+0000] Successfully installed Flask-2.2.5 Jinja2-3.1.2 MarkupSafe-2.1.3 PyJWT-2.8.0 PyYAML-6.0.1 SQLAlchemy-2.0.19 Werkzeug-2.3.6 aiohttp-3.8.5 aiosignal-1.3.1 async-timeout-4.0.2 attrs-23.1.0 azure-common-1.1.28 azure-core-1.28.0 azure-core-tracing-opentelemetry-1.0.0b10 azure-identity-1.13.0 azure-monitor-opentelemetry-1.0.0b15 azure-monitor-opentelemetry-exporter-1.0.0b15 azure-search-documents-11.4.0b6 azure-storage-blob-12.14.1 certifi-2023.7.22 cffi-1.15.1 charset-normalizer-3.2.0 click-8.1.6 cryptography-41.0.3 dataclasses-json-0.5.14 deprecated-1.2.14 et-xmlfile-1.1.0 fixedint-0.1.6 frozenlist-1.4.0 greenlet-2.0.2 idna-3.4 importlib-metadata-6.8.0 isodate-0.6.1 itsdangerous-2.1.2 langchain-0.0.187 marshmallow-3.20.1 msal-1.23.0 msal-extensions-1.0.0 msrest-0.7.1 multidict-6.0.4 mypy-extensions-1.0.0 numexpr-2.8.4 numpy-1.25.2 oauthlib-3.2.2 openai-0.27.8 openapi-schema-pydantic-1.2.4 openpyxl-3.1.2 opentelemetry-api-1.19.0 opentelemetry-instrumentation-0.40b0 opentelemetry-instrumentation-aiohttp-client-0.40b0 opentelemetry-instrumentation-flask-0.40b0 opentelemetry-instrumentation-requests-0.40b0 opentelemetry-instrumentation-wsgi-0.40b0 opentelemetry-sdk-1.19.0 opentelemetry-semantic-conventions-0.40b0 opentelemetry-util-http-0.40b0 packaging-23.1 pandas-2.0.3 pandas-stubs-2.0.2.230605 portalocker-2.7.0 pycparser-2.21 pydantic-1.10.12 python-dateutil-2.8.2 pytz-2023.3 regex-2023.6.3 requests-2.31.0 requests-oauthlib-1.3.1 six-1.16.0 tenacity-8.2.2 tiktoken-0.4.0 tqdm-4.65.0 types-pytz-2023.3.0.0 typing-extensions-4.7.1 typing-inspect-0.9.0 tzdata-2023.3 urllib3-2.0.4 wrapt-1.15.0 yarl-1.9.2 zipp-3.16.2

```

**Comment by tonybaloney** [comment]
This is the change to the original app to add monitoring https://github.com/Azure-Samples/azure-search-openai-demo/compare/main...tonybaloney:azure-search-openai-demo:tracing_otel?expand=1#diff-5f1d71f916fd982ef5a7ab0b78e419d64d02a77c7422911db11911a74f3a8ee6
