### ISSUE TITLE
[azure-key-vault] ModuleNotFoundError: No module named '_cffi_backend'

### ISSUE THREAD

**Issue by akshaybabloo** [Azure/azure-sdk-for-python#3157]
I am getting an for cryptography module as 

```
Traceback (most recent call last):
  File "C:/Users/aksha/Documents/GitHub/neucube-cloud-api/temp.py", line 2, in <module>
    from azure.keyvault import KeyVaultClient, KeyVaultAuthentication
  File "C:\Users\aksha\Miniconda3\envs\neucube\lib\site-packages\azure\keyvault\__init__.py", line 15, in <module>
    from .key_vault_authentication import KeyVaultAuthentication, KeyVaultAuthBase, AccessToken
  File "C:\Users\aksha\Miniconda3\envs\neucube\lib\site-packages\azure\keyvault\key_vault_authentication.py", line 13, in <module>
    from azure.keyvault.http_message_security import HttpMessageSecurity
  File "C:\Users\aksha\Miniconda3\envs\neucube\lib\site-packages\azure\keyvault\http_message_security.py", line 9, in <module>
    from ._internal import _a128cbc_hs256_encrypt, _a128cbc_hs256_decrypt, _JwsHeader, _JwsObject, \
  File "C:\Users\aksha\Miniconda3\envs\neucube\lib\site-packages\azure\keyvault\_internal.py", line 16, in <module>
    from cryptography.hazmat.primitives import hashes, constant_time, padding, hmac
  File "C:\Users\aksha\Miniconda3\envs\neucube\lib\site-packages\cryptography\hazmat\primitives\constant_time.py", line 11, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ModuleNotFoundError: No module named '_cffi_backend'

Process finished with exit code 1
```

I have `cryptography` installed on Python 3.7. Submitted a bug report to https://github.com/pyca/cryptography/issues/4403

**Comment by akshaybabloo** [comment]
My bad. Seems to be a problem when upgrading python 3.6 to 3.7.
