### ISSUE TITLE
Azure authentication issue when using system-assigned or user-assigned managed identity

### ISSUE THREAD

**Issue by corticalstack** [Azure/azure-sdk-for-python#31876]
Hi,

Trying to use both either a System Assigned Managed Identity (SAMI), or User Assigned Managed Identity (UAMI) to authenticate to a key vault from within a Azure Machine Learning online endpoint.

Going beyond our own solution, replicated the Azure ML online endpoints key vault example found here:
https://github.com/Azure/azureml-examples/blob/main/sdk/python/endpoints/online/managed/online-endpoints-keyvault.ipynb

Online endpoint deployment fails with error further below, when code executing a secrets retrieval fails (code below, example using SAMI which has policy for secrets get on kv). Seems closely related to [this issue](https://github.com/Azure/azure-sdk-for-python/issues/24282) 

Grateful for any support.

```
from azure.identity import ManagedIdentityCredential
from azure.keyvault.secrets import SecretClient
import os
import json
multiplier: int = None


def load_secrets():
"""
Replaces the values of environment variables with names containing "KV_SECRET" and values of the form "<SECRET_NAME>@<VAULT_URL>" with the actual secret values

Uses the ManagedIdentityCredential to create a SecretClient for each <VAULT_URL>. The endpoint's Managed Identity should have the get permission for secrets.

Example:
    KV_SECRET_FOO: foo@https://keyvault123.vault.azure.net

    Will be replaced with the actual vaule of the secret named foo in keyvault123.
"""
secret_clients = {}
credential = ManagedIdentityCredential()

for k, v in os.environ.items():
    if "KV_SECRET" in k:
        try:
            secret_name, vault_url = v.split("@")
        except ValueError:
            raise ValueError(
                f"Wrong value format for env var {k} with value {v}. Should be of the form <SECRET_NAME>@<VAULT_URL>"
            )

        if vault_url in secret_clients:
            secret_client = secret_clients[vault_url]
        else:
            secret_client = SecretClient(vault_url=vault_url, credential=credential)
            secret_clients[vault_url] = secret_client

        secret_value = secret_client.get_secret(secret_name).value
        os.environ[k] = secret_value
def init():
load_secrets()

global multiplier
multiplier = int(os.getenv("KV_SECRET_MULTIPLIER"))
def run(data):
data = json.loads(data)
input = data["input"]
output = input * multiplier

return {"output": output}
```

2023-08-29 14:48:20,103 E [69] azmlinfsrv - User's init function failed
2023-08-29 14:48:20,107 E [69] azmlinfsrv - Encountered Exception Traceback (most recent call last):
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azureml_inference_server_http/server/user_script.py", line 119, in invoke_init
self._user_init()
File "/var/azureml-app/test_deploy_endpoint_verbatim/score.py", line 43, in init
load_secrets()
File "/var/azureml-app/test_deploy_endpoint_verbatim/score.py", line 38, in load_secrets
secret_value = secret_client.get_secret(secret_name).value
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
return func(*args, **kwargs)
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/keyvault/secrets/_client.py", line 72, in get_secret
bundle = self._client.get_secret(
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/keyvault/secrets/_generated/_operations_mixin.py", line 1640, in get_secret
return mixin_instance.get_secret(vault_base_url, secret_name, secret_version, **kwargs)
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
return func(*args, **kwargs)
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/keyvault/secrets/_generated/v7_4/operations/_key_vault_client_operations.py", line 760, in get_secret
pipeline_response: PipelineResponse = self._client._pipeline.run( # pylint: disable=protected-access
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 230, in run
return first_node.send(pipeline_request)
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
response = self.next.send(request)
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
response = self.next.send(request)
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
response = self.next.send(request)
[Previous line repeated 2 more times]
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/pipeline/policies/_redirect.py", line 197, in send
response = self.next.send(request)
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/pipeline/policies/_retry.py", line 531, in send
response = self.next.send(request)
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/pipeline/policies/_authentication.py", line 126, in send
response = self.next.send(request)
2023-08-29 14:48:20,107 I [69] gunicorn.error - Worker exiting (pid: 69)
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
response = self.next.send(request)
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
response = self.next.send(request)
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
response = self.next.send(request)
[Previous line repeated 2 more times]
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 119, in send
self._sender.send(request.http_request, **request.context.options),
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 339, in send
response = self.session.request( # type: ignore
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
resp = self.send(prep, **send_kwargs)
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
r = adapter.send(request, **kwargs)
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
resp = conn.urlopen(
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
httplib_response = self._make_request(
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/urllib3/connectionpool.py", line 403, in _make_request
self._validate_conn(conn)
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
conn.connect()
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
self.sock = conn = self._new_conn()
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
conn = connection.create_connection(
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
sock.connect(sa)
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
sys.exit(1)
SystemExit: 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azureml_inference_server_http/server/aml_blueprint.py", line 109, in setup
self.user_script.invoke_init()
File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azureml_inference_server_http/server/user_script.py", line 121, in invoke_init
raise UserScriptException(ex) from ex
azureml_inference_server_http.server.user_script.UserScriptException: Caught an unhandled exception from the user script

**Comment by kashifkhan** [comment]
Thank you for your feedback @corticalstack . We will investigate and get back to you asap.

**Comment by pvaneck** [comment]
Hey, from what I can tell, the logs don't seem to convey what the specific error is. 🤔 Do you explicitly encounter any permission errors?

I know that there have been reports of ManagedIdentity not working as expected within Azure ML with some workarounds described here: https://github.com/Azure/azure-sdk-for-python/issues/31032#issuecomment-1680907338

**Comment by binaryPUNCH** [comment]
This is a major issue for my team as well. Using Docker WSL. Whenever we configure a Function to input trigger using managed identity, e.g. service bus, everything blows up.
```
[2023-09-15T13:23:50.705Z] Status: 403 (connecting to 169.254.169.254:80: connecting to 169.254.169.254:80: dial tcp 169.254.169.254:80: connectex: A socket operation was attempted to an unreachable network.)
[2023-09-15T13:23:50.707Z] See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot. Azure.Identity: Managed Identity response was not in the expected format. See the inner exception for details.
[2023-09-15T13:23:50.705Z] Status: 403 (connecting to 169.254.169.254:80: connecting to 169.254.169.254:80: dial tcp 169.254.169.254:80: connectex: A socket operation was attempted to an unreachable network.)
[2023-09-15T13:23:50.705Z] . System.Text.Json: 'c' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
[2023-09-15T13:23:50.705Z] See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot. Azure.Identity: Managed Identity response was not in the expected format. See the inner exception for details.
[2023-09-15T13:23:50.705Z] 
[2023-09-15T13:23:50.705Z] . System.Text.Json: 'c' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
[2023-09-15T13:23:50.648Z] 
[2023-09-15T13:23:50.651Z] See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot. Azure.Identity: Managed Identity response was not in the expected format. See the inner exception for details.
[2023-09-15T13:23:50.705Z] Connection: close
[2023-09-15T13:23:50.708Z] . System.Text.Json: 'c' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
[2023-09-15T13:23:50.706Z] 
[2023-09-15T13:23:50.706Z] Connection: close
[2023-09-15T13:23:50.651Z] Status: 403 (connecting to 169.254.169.254:80: connecting to 169.254.169.254:80: dial tcp 169.254.169.254:80: connectex: A socket operation was attempted to an unreachable network.)
```

**Comment by pvaneck** [comment]
@binaryPUNCH  - There was an issue for that https://github.com/Azure/azure-sdk-for-python/issues/31759

If possible, try [`azure-identity==1.15.0b1` ](https://pypi.org/project/azure-identity/1.15.0b1/) which should have a fix.

**Comment by binaryPUNCH** [comment]
Thanks, but unfortunately that did not help.

**Comment by binaryPUNCH** [comment]
Any updates on this?

**Comment by pvaneck** [comment]
Hey, @binaryPUNCH, do you mind opening a separate issue with more details (i.e. code snippet, package versions, etc)? 

Just now noticing that the error you printed came from the .NET Identity SDK. Is the .NET SDK being used to authenticate? And are you specifically using `ManagedIdentityCredential`?
