### ISSUE TITLE
Connection gets reset while calling apis

### ISSUE THREAD

**Issue by vmksuw** [Azure/azure-sdk-for-python#319]
Hi , I use the sdk to create storage account, container, cloud service, to upload file to blob storage, create os disk and create instance in cloud service. I always noticed that connection gets reset in any api call. Using new python sdk (master branch) solved the problem in uploading large file to blob but still get connection reset error while calling remaining apis.

for example i got following error while launching instance in cloud service-
2015-03-09 17:15:38,432 -ERROR - [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "old_opo.py", line 863, in migrate_to_azure
    str(xml_format),async=True,x_ms_version='2014-06-01')
  File "/root/opo/opo_code/azure/servicemanagement/servicemanagementclient.py", line 244, in _perform_post
    response = self.perform_post(path, body, x_ms_version)
  File "/root/opo/opo_code/azure/servicemanagement/servicemanagementclient.py", line 171, in perform_post
    response = self._perform_request(request)
  File "/root/opo/opo_code/azure/servicemanagement/servicemanagementclient.py", line 199, in _perform_request

Thanks

**Comment by vmksuw** [comment]
Hi, I also get connection reset error on creating storage account(used new sdk)-
2015-03-09 17:34:34,458 -INFO - Executing /forklift_to_azure...
2015-03-09 17:35:19,285 -ERROR - [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "old_opo.py", line 698, in migrate_to_azure
    sms = ServiceManagementService(subscription_id, pem_file)
  File "/root/opo/opo_code/azure/servicemanagement/servicemanagementservice.py", line 229, in create_storage_account
    async=True)

**Comment by athatte** [comment]
Any thoughts on this bug Hugues / Christopher?

**Comment by Priyanka-Ambekar** [comment]
Hi,

Even I see a similar issue of Connection being reset by peer while invoking Delete Storage Service Python API

Error:
return self._sslobj.read(len)
socket.error: [Errno 104] Connection reset by peer

Thanks !

**Comment by lmazuel** [comment]
I think this is the same as https://github.com/Azure/azure-sdk-for-python/issues/336

Could you check if the problem is still there using the latest version of the library and the latest contribution libraries (like requests 2.9.1)?
Thank you,

**Comment by lmazuel** [comment]
Close this issue due to inactivity. Please feel free to open a new issue if you still experiencing the problem with the latest version.
Thanks!
