### ISSUE TITLE
None value in displayName cause a bad request error

### ISSUE THREAD

**Issue by aaravind100** [Azure/azure-sdk-for-python#31935]
- **Package Name**: azure-communication-email
- **Package Version**: 1.0.0
- **Operating System**: Ubuntu 22.04.3 LTS (WSL)
- **Python Version**: 3.9.5

**Describe the bug**

Based on the schema provided [here](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/email/send-email?tabs=windows%2Cconnection-string&pivots=programming-language-python#understanding-the-email-object-model), the displayName in recipients is optional. If `None` is passed explicitly, it gives a bad request error with the below trace.

```sh
Traceback (most recent call last):
  File "/home/aravia1/scraps/azure_email.py", line 31, in <module>
    poller = client.begin_send(message=message)
  File "/home/aravia1/scraps/venv/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/aravia1/scraps/venv/lib/python3.9/site-packages/azure/communication/email/_email_client.py", line 179, in begin_send
    return self._generated_client.email.begin_send(message=message, **kwargs)
  File "/home/aravia1/scraps/venv/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/aravia1/scraps/venv/lib/python3.9/site-packages/azure/communication/email/_generated/operations/_operations.py", line 503, in begin_send
    raw_result = self._send_initial(  # type: ignore
  File "/home/aravia1/scraps/venv/lib/python3.9/site-packages/azure/communication/email/_generated/operations/_operations.py", line 240, in _send_initial
    raise HttpResponseError(response=response)
azure.core.exceptions.HttpResponseError: (BadRequest) Email body validation error. See property 'recipients.to[0].displayName'
Code: BadRequest
Message: Email body validation error. See property 'recipients.to[0].displayName'
```

**To Reproduce**

1. Create a virtual environment and activate it.

    ```sh
    $ python -m venv venv
    $ source activate venv/bin/activate
    ```

2. Install azure communication email sdk.

    ```sh
    $ pip install azure-communication-email
    ```

3. Create a script azure_email.py with the below snippet, modify the connection string, to and sender address appropriately.

    ```py
    from azure.communication.email import EmailClient


    conn_str = "<connection string>"  # <-- modify this


    client = EmailClient.from_connection_string(conn_str=conn_str)


    message = {
        "content": {
            "subject": "This is a test email",
            "plainText": "This is the body",
        },
        "recipients": {
            "to": [
                {
                    "address": "<bob@mail.com>",  # <-- modify this
                    "displayName": None,  # <-- this causes an error
                }
            ]
        },
        "senderAddress": "<donotreply@mail.com>",  # <-- modify this
    }


    poller = client.begin_send(message=message)
    print(poller.status())
    print(poller.result())
    ```

4. Execute the script.

    ```sh
    $ python azure_email.py
    ```

**Expected behavior**

None values are sanitized properly and the email is sent successfully.

**Additional context**

Output of pip freeze.

```sh
azure-common==1.1.28
azure-communication-email==1.0.0
azure-core==1.29.3
azure-mgmt-core==1.4.0
certifi==2023.7.22
charset-normalizer==3.2.0
idna==3.4
isodate==0.6.1
msrest==0.7.1
oauthlib==3.2.2
requests==2.31.0
requests-oauthlib==1.3.1
six==1.16.0
typing_extensions==4.7.1
urllib3==2.0.4
```

**Comment by mccoyp** [comment]
Hi @aaravind100, thank you for opening an issue! I'm tagging folks who should be able to help; we'll get back to you as soon as possible. cc @turalf
