### ISSUE TITLE
Do this SDK support Azure stack anymore ? 

### ISSUE THREAD

**Issue by mysiki** [Azure/azure-sdk-for-python#31974]
Hi,

We using Ansible for manage Azure and Azure stack environment (VM, network, NSG etc...). Since the new ansible collection, than use update in azure SDK (like azure-identity) our code do not work on Azure stack anymore.

I find many issue, about the authentication (some in Azure collection like ADFS authority not pass) and about the authentication scope *<URL Management>/.default* instead of *<URL Management>/tenant*. 

After debug and 'fix' the authentication par (than is a Azure ansible collection problem) I got many error about the API version present accept in Stack and the API version available in python package. 

So, I want to ask, does this SDK Azure continu to support Azure stack or only work in Azure public ?

**Comment by lmazuel** [comment]
Hi @mysiki 
We do support Azure Stack still, please clarify the exact issues you are getting, and we'll investigate with the Ansible and the Azure Stack team where is the gap.

**Comment by mysiki** [comment]
Hey,

you can find some details in Ansible collection issue, Specially my last post https://github.com/ansible-collections/azure/issues/1143

I think it have some bug in the collection (authority not pass, default scope to '.default' ? ). But after manually change some value (for testing)  I got module version error (than I think it like to this sdk) 

Not all the module, for example azure_rm_ressourcegroup_info work. But virtual machine, publicIp dosen't. 

Running : 
```
ansible all -i a, -c local -m azure.azcollection.azure_rm_virtualmachine_info -a "profile='XXX' resource_group='rgr-YYY'" 

The full traceback is:
Traceback (most recent call last):
  File "/home/skt/.ansible/tmp/ansible-tmp-1694388055.14966-178-130303759926085/AnsiballZ_azure_rm_virtualmachine_info.py", line 107, in <module>
    _ansiballz_main()
  File "/home/skt/.ansible/tmp/ansible-tmp-1694388055.14966-178-130303759926085/AnsiballZ_azure_rm_virtualmachine_info.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/skt/.ansible/tmp/ansible-tmp-1694388055.14966-178-130303759926085/AnsiballZ_azure_rm_virtualmachine_info.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_virtualmachine_info', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_virtualmachine_info', _modlib_path=modlib_path),
  File "/usr/local/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_36jfzl0y/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py", line 548, in <module>
  File "/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_36jfzl0y/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py", line 544, in main
  File "/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_36jfzl0y/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py", line 350, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_36jfzl0y/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 472, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_36jfzl0y/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py", line 368, in exec_module
  File "/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_36jfzl0y/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py", line 394, in list_items_by_resourcegroup
  File "/venv/.venv/lib/python3.10/site-packages/azure/core/paging.py", line 123, in __next__
    return next(self._page_iterator)
  File "/venv/.venv/lib/python3.10/site-packages/azure/core/paging.py", line 75, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/venv/.venv/lib/python3.10/site-packages/azure/mgmt/compute/v2021_04_01/operations/_virtual_machines_operations.py", line 1876, in get_next
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/venv/.venv/lib/python3.10/site-packages/azure/core/exceptions.py", line 164, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: (InvalidResourceType) The resource type 'virtualMachines' could not be found in the namespace 'Microsoft.Compute' for api version '2021-04-01'. The supported api-versions are '2015-06-15,2015-11-01,2016-03-30,2016-08-30,2017-03-30,2017-12-01,2018-04-01,2018-06-01,2018-10-01,2019-03-01,2019-07-01,2019-12-01,2020-06-01,2021-11-01'.
Code: InvalidResourceType
Message: The resource type 'virtualMachines' could not be found in the namespace 'Microsoft.Compute' for api version '2021-04-01'. The supported api-versions are '2015-06-15,2015-11-01,2016-03-30,2016-08-30,2017-03-30,2017-12-01,2018-04-01,2018-06-01,2018-10-01,2019-03-01,2019-07-01,2019-12-01,2020-06-01,2021-11-01'.
a | FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/skt/.ansible/tmp/ansible-tmp-1694388055.14966-178-130303759926085/AnsiballZ_azure_rm_virtualmachine_info.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/skt/.ansible/tmp/ansible-tmp-1694388055.14966-178-130303759926085/AnsiballZ_azure_rm_virtualmachine_info.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/skt/.ansible/tmp/ansible-tmp-1694388055.14966-178-130303759926085/AnsiballZ_azure_rm_virtualmachine_info.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_virtualmachine_info', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_virtualmachine_info', _modlib_path=modlib_path),\n  File \"/usr/local/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_36jfzl0y/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py\", line 548, in <module>\n  File \"/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_36jfzl0y/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py\", line 544, in main\n  File \"/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_36jfzl0y/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py\", line 350, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_36jfzl0y/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 472, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_36jfzl0y/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py\", line 368, in exec_module\n  File \"/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_36jfzl0y/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py\", line 394, in list_items_by_resourcegroup\n  File \"/venv/.venv/lib/python3.10/site-packages/azure/core/paging.py\", line 123, in __next__\n    return next(self._page_iterator)\n  File \"/venv/.venv/lib/python3.10/site-packages/azure/core/paging.py\", line 75, in __next__\n    self._response = self._get_next(self.continuation_token)\n  File \"/venv/.venv/lib/python3.10/site-packages/azure/mgmt/compute/v2021_04_01/operations/_virtual_machines_operations.py\", line 1876, in get_next\n    map_error(status_code=response.status_code, response=response, error_map=error_map)\n  File \"/venv/.venv/lib/python3.10/site-packages/azure/core/exceptions.py\", line 164, in map_error\n    raise error\nazure.core.exceptions.ResourceNotFoundError: (InvalidResourceType) The resource type 'virtualMachines' could not be found in the namespace 'Microsoft.Compute' for api version '2021-04-01'. The supported api-versions are '2015-06-15,2015-11-01,2016-03-30,2016-08-30,2017-03-30,2017-12-01,2018-04-01,2018-06-01,2018-10-01,2019-03-01,2019-07-01,2019-12-01,2020-06-01,2021-11-01'.\nCode: InvalidResourceType\nMessage: The resource type 'virtualMachines' could not be found in the namespace 'Microsoft.Compute' for api version '2021-04-01'. The supported api-versions are '2015-06-15,2015-11-01,2016-03-30,2016-08-30,2017-03-30,2017-12-01,2018-04-01,2018-06-01,2018-10-01,2019-03-01,2019-07-01,2019-12-01,2020-06-01,2021-11-01'.\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

Trying to force the api_profile to 2020-06-01 
```
The full traceback is:
Traceback (most recent call last):
  File "/home/skt/.ansible/tmp/ansible-tmp-1694388416.244173-250-134188608006263/AnsiballZ_azure_rm_virtualmachine_info.py", line 107, in <module>
    _ansiballz_main()
  File "/home/skt/.ansible/tmp/ansible-tmp-1694388416.244173-250-134188608006263/AnsiballZ_azure_rm_virtualmachine_info.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/skt/.ansible/tmp/ansible-tmp-1694388416.244173-250-134188608006263/AnsiballZ_azure_rm_virtualmachine_info.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_virtualmachine_info', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_virtualmachine_info', _modlib_path=modlib_path),
  File "/usr/local/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_u8sa5m9u/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py", line 548, in <module>
  File "/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_u8sa5m9u/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py", line 544, in main
  File "/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_u8sa5m9u/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py", line 350, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_u8sa5m9u/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 472, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_u8sa5m9u/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py", line 368, in exec_module
  File "/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_u8sa5m9u/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py", line 389, in list_items_by_resourcegroup
  File "/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_u8sa5m9u/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 1132, in compute_client
  File "/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_u8sa5m9u/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 933, in get_mgmt_svc_client
  File "/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_u8sa5m9u/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 875, in get_api_profile
KeyError: 'unknown Azure API profile: 2020-06-01'
a | FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/skt/.ansible/tmp/ansible-tmp-1694388416.244173-250-134188608006263/AnsiballZ_azure_rm_virtualmachine_info.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/skt/.ansible/tmp/ansible-tmp-1694388416.244173-250-134188608006263/AnsiballZ_azure_rm_virtualmachine_info.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/skt/.ansible/tmp/ansible-tmp-1694388416.244173-250-134188608006263/AnsiballZ_azure_rm_virtualmachine_info.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_virtualmachine_info', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_virtualmachine_info', _modlib_path=modlib_path),\n  File \"/usr/local/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_u8sa5m9u/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py\", line 548, in <module>\n  File \"/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_u8sa5m9u/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py\", line 544, in main\n  File \"/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_u8sa5m9u/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py\", line 350, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_u8sa5m9u/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 472, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_u8sa5m9u/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py\", line 368, in exec_module\n  File \"/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_u8sa5m9u/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine_info.py\", line 389, in list_items_by_resourcegroup\n  File \"/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_u8sa5m9u/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 1132, in compute_client\n  File \"/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_u8sa5m9u/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 933, in get_mgmt_svc_client\n  File \"/tmp/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload_u8sa5m9u/ansible_azure.azcollection.azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 875, in get_api_profile\nKeyError: 'unknown Azure API profile: 2020-06-01'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

My stack admin say they use the last Azure stack verison (1.2301.0.60). I don't know if it's a SDK issue or a ansible collection issue ... (but both are maintien by Azure :D)

**Comment by xuzhang3** [comment]
#1299  will fix the issue  cannot use the custom ADFS endpoint

**Comment by TheOnlyWei** [comment]
> #1299 will fix the issue cannot use the custom ADFS endpoint

Hi @xuzhang3, how does another Github Issue (https://github.com/Azure/azure-sdk-for-python/issues/1299) fix this current issue? Did you intend to link a PR? In the issue you linked, it discusses a separate issue that doesn't seem related to this one.

**Comment by xuzhang3** [comment]
@TheOnlyWei Sorry for my mistake. I'm comment on the wrong issue.

**Comment by lmazuel** [comment]
This is being followed upon by the Ansible team at Microsoft as an Ansible issue, so closing here. The SDK itself is fine, and doesn't requires any updates from our team, it's the Ansible integration that needs adjustements
