### ISSUE TITLE
Redis operations: export

### ISSUE THREAD

**Issue by nuclear0wl** [Azure/azure-sdk-for-python#3198]
When I try to execute Azure CLI command `az redis export` I got that error: 
```
ERROR: 'RedisOperations' object has no attribute 'export'
Traceback (most recent call last):
File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke cmd_result = self.invocation.execute(args)
File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute six.reraise(*sys.exc_info())
File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise raise value
File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute result = cmd(params)
File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__ return self.handler(*args, **kwargs)
File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler result = op(**command_args)
File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/redis/custom.py", line 33, in cli_redis_export return client.export(resource_group_name, name, parameters)
AttributeError: 'RedisOperations' object has no attribute 'export'
```

I think that source of an error might be here:
[Redis Operations](https://github.com/Azure/azure-sdk-for-python/blob/66b4ec24f07c78fe3de0bd5d995557c43f46ec96/azure-mgmt-redis/azure/mgmt/redis/operations/redis_operations.py#L880)

**Comment by nuclear0wl** [comment]
I changed source code on my local machine in `/opt/az/lib/python3.6/site-packages/azure/mgmt/redis/operations/redis_operations.py` and now `export` operation works correctly for me. Made pull request for that bug: #3211

**Comment by lmazuel** [comment]
Hi @nuclear0wl 
This is a CLI issue, not a SDK one. The correct fix is not to solve the SDK, but the CLI (so I will close your PR and issue). Please open a CLI bug here:
https://github.com/Azure/azure-cli/issues

I appreciate the contribution and I don't deny you have an issue though, it's just it's not the right fix :)
Thanks!

FYI @tjprescott

**Comment by nuclear0wl** [comment]
Hi @lmazuel
Thank you for the prompt response and indication of the right way to solve the problem :)
