### ISSUE TITLE
access denied custom vision

### ISSUE THREAD

**Issue by AhmadManzoor** [Azure/azure-sdk-for-python#32015]
- **Package Name**: 
azure-cognitiveservices-vision-customvision
- **Package Version**: 
3.1.0
- **Operating System**:
- linux mint 21
- **Python Version**: 
- 3.9.0

**Describe the bug**
Tryiong to use custom model using python and getting following error
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/ahmad/.pyenv/versions/3.9.0/lib/python3.9/site-packages/azure/cognitiveservices/vision/customvision/prediction/operations/_custom_vision_prediction_client_operations.py", line 358, in detect_image
    raise models.CustomVisionErrorException(self._deserialize, response)
azure.cognitiveservices.vision.customvision.prediction.models._models_py3.CustomVisionErrorException: Operation returned an invalid status code 'Access Denied'

**To Reproduce**
prediction_key = "3XXXXXXXXXXXXXXXXXXXXXXXX8"
        project_id = "XXXX-XXX-XXX-XXX-XXXXX"
        published_name = "Iteration2"
        endpoint = "https://<modelname>.cognitiveservices.azure.com/"
 image_data = req.files["image"]

        if not image_data:
            return func.HttpResponse("Please provide an image file in the request body.", status_code=400)
        # Create a Computer Vision client
        prediction_credentials = ApiKeyCredentials(in_headers={"Prediction-key": prediction_key , "Content-Type": "application/octet-stream"})
        predictor = CustomVisionPredictionClient(endpoint, prediction_credentials)
        results = predictor.detect_image(project_id, published_name, req.files["image"].read())
        
 This is how i am sending file
files =  {'image': <_io.BufferedReader name='/home/ahmad/Downloads/test.jpg'>}
 res = requests.post(furl , files=files)

**Expected behavior**
 clear and concise description of what you expected to happen.
**Screenshots**

**Additional context**

**Comment by pvaneck** [comment]
Thanks for the feedback, As far as I am aware, the package `azure-cognitiveservices-vision-customvision` is no longer maintained.

@kristapratico, would you happen to have any pointers to who could better assist?

In any case, I think some things that are worth checking are:

- Ensure that you are using the prediction endpoint and not the training endpoint and make sure that the prediction key corresponds to that endpoint.
- Double check that the project_id is referencing the correct project. 
- Try without `"Content-Type": "application/octet-stream"` in the ApiKeyCredentials. Not sure if that's causing an issue?

**Comment by AhmadManzoor** [comment]
thank you for your quick response
ensure the endpoint : i am getting this from settings page under key and endpoint
getting the project id from same page
also tried without "Content-Type": "application/octet-stream
getting same error

**Comment by pj-ms** [comment]
Your endpoint is wrong. Please go to Azure portal and find your custom vision resource and retrieve the right endpoint url

**Comment by swathipil** [comment]
Hi @AhmadManzoor - We will be officially deprecating the azure-cognitiveservices-vision-customvision package and are no longer maintaining it. We will not be unpublishing the packages from PyPI so they will still be installable.
