### ISSUE TITLE
[Errno -2] Name or service not known on  blob_client.upload_blob(data)

### ISSUE THREAD

**Issue by khayamgondal** [Azure/azure-sdk-for-python#32023]
azure-core==1.29.4
azure-identity==1.14.0
azure-storage-blob==12.17.0

I am uploading multiple files in a folder to blob storage however its hangs on blob_client.upload_blob call and throws exception 
My upload method
```
for _, _, files in os.walk(exp_name):        
            for i, file in enumerate(files):
                folder_name = os.path.basename(exp_name)
                blob_name = os.path.join(folder_name, file)
                blob_path = os.path.join(exp_name, file)
                blob_client = container_client.get_blob_client(blob_name)
                with open(blob_path, "rb") as data:
                    blob_client.upload_blob(data)
                print("Uploaded {} of {} files to azure".format(i+1, len(files)))  
```
Exception
```
Traceback (most recent call last):
  File "/home/khayam/scanning-research/capture_scripts/./frame_capture.py", line 133, in <module>
    azure_upload(EXP_NAME)
  File "/home/khayam/scanning-research/capture_scripts/./frame_capture.py", line 116, in azure_upload
    blob_client.upload_blob(data, overwrite=True)
  File "/home/khayam/.local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/khayam/.local/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 737, in upload_blob
    return upload_block_blob(**options)
  File "/home/khayam/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 105, in upload_block_blob
    response = client.upload(
  File "/home/khayam/.local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/khayam/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 845, in upload
    pipeline_response = self._client._pipeline.run(  # type: ignore # pylint: disable=protected-access
  File "/home/khayam/.local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 230, in run
    return first_node.send(pipeline_request)
  File "/home/khayam/.local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/home/khayam/.local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/home/khayam/.local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/home/khayam/.local/lib/python3.10/site-packages/azure/core/pipeline/policies/_redirect.py", line 197, in send
    response = self.next.send(request)
  File "/home/khayam/.local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/home/khayam/.local/lib/python3.10/site-packages/azure/storage/blob/_shared/policies.py", line 546, in send
    raise err
  File "/home/khayam/.local/lib/python3.10/site-packages/azure/storage/blob/_shared/policies.py", line 520, in send
    response = self.next.send(request)
  File "/home/khayam/.local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/home/khayam/.local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/home/khayam/.local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/home/khayam/.local/lib/python3.10/site-packages/azure/storage/blob/_shared/policies.py", line 313, in send
    response = self.next.send(request)
  File "/home/khayam/.local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/home/khayam/.local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/home/khayam/.local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 119, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/home/khayam/.local/lib/python3.10/site-packages/azure/storage/blob/_shared/base_client.py", line 329, in send
    return self._transport.send(request, **kwargs)
  File "/home/khayam/.local/lib/python3.10/site-packages/azure/storage/blob/_shared/base_client.py", line 329, in send
    return self._transport.send(request, **kwargs)
  File "/home/khayam/.local/lib/python3.10/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 381, in send
    raise error
azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPSConnection object at 0x7fa7b6c5c880>: Failed to establish a new connection: [Errno -2] Name or service not known
```

**Comment by pvaneck** [comment]
Hey, sorry you're hitting an issue uploading blobs. I will route this to the storage team who can hopefully provide more assistance. 

For starters, are you able to run `container_client.list_blobs()` without an issue? Wondering if something is up with the endpoint/connection string.

**Comment by khayamgondal** [comment]
This indeed was a problem with the connection string and container name. I defined both in separate configuration files in double-quotes. Looks like azure doesn't like the quotes so when I changed container_name from 'capture' to capture, everything started working
