### ISSUE TITLE
Bug: ContainerClient.download_blob works once but not twice in windows 

### ISSUE THREAD

**Issue by PabloRuizCuevas** [Azure/azure-sdk-for-python#32458]
- **azure.storage.blob.aio**: 
- **18.3.1**: 
- **Windows**:
- **3.11**: 

**Describe the bug**

The code aio download_blob of the azure blob works once but not twice when run with asyncio.run, this looks like a bug related to aiohttp, but could not figure out how to solve it. (Windows)

The code i have to reproduce it is almost a copy from their original example at: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/samples/blob_samples_hello_world_async.py

**To Reproduce**

```python
from azure.storage.blob.aio import ContainerClient
from azure.identity import DefaultAzureCredential
credentials = DefaultAzureCredential()

async def test(conn_client):
    async with conn_client as client_conn:
        stream = await client_conn.download_blob(my_path)
        data = await stream.readall()
    return data

if __name__ == "__main__":
    my_container_name = "Container name"
    my_client = ContainerClient.from_container_url(container_url=my_container_name, credential=credentials)
    my_path = 'test_path'

    data = asyncio.run(test(my_client)) # works and returns the file from blob storage
    data2 = asyncio.run(test(my_client)) # doesn't work

```

error:

```
DEBUG - asyncio: Using proactor: IocpProactor
...
    await self.open()
  File "C...\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\azure\core\pipeline\transport\_aiohttp.py", line 127, in open
    await self.session.__aenter__()
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '__aenter__'. Did you mean: '__delattr__'?

Process finished with exit code 1
```

**Comment by PabloRuizCuevas** [comment]
For what I see the issue seems related to the not closing of TCP connection, but is not so straight forward as i can come up with a code that close the session, but still doesn't work :

```
async def test4(my_client):
    async with my_client as client:
        # this at least closes the session
        stream = await client.download_blob(my_path)
        data = await stream.readall()
        session = my_client._client._client._pipeline._transport.session
    return data, session

data, s = asyncio.run(test(my_client))
print(session.closed)
```

will return that the session is closed


the best work around i found is instantiate the class as many times as needed:

    my_client = ContainerClient.from_container_url(container_url=my_container_name, credential=credentials)
    data = asyncio.run(test(my_client))
    my_client = ContainerClient.from_container_url(container_url=my_container_name, credential=credentials)
    data2 = asyncio.run(test(my_client))
    
   
  or even in the dowload blob:
  
```
  async def test():
    # best working alternative so far
    async with DefaultAzureCredential() as credential:
        async with ContainerClient.from_container_url(container_url=my_container_name, credential=credential) as client:
            stream = await client.download_blob(my_path)
            data = await stream.readall()
    return data
```

but honestly this is not a great solution for this bug.

**Comment by annatisch** [comment]
Thanks for the report @PabloRuizCuevas 
I believe the reason you're seeing this is due to using the client within the context manager - which will close the client/session/connection on exiting the context - and which is then not re-openable.
You should be able to resolve this by either changing where you open the context, or manually closing the client when you have finished with it. For example:
```python
from azure.storage.blob.aio import ContainerClient
from azure.identity import DefaultAzureCredential
credentials = DefaultAzureCredential()

async def test(conn_client):
    stream = await conn_client.download_blob(my_path)
    data = await stream.readall()
    return data

if __name__ == "__main__":
    my_container_name = "Container name"
    my_client = ContainerClient.from_container_url(container_url=my_container_name, credential=credentials)
    my_path = 'test_path'

    try:
        data = asyncio.run(test(my_client))
        data2 = asyncio.run(test(my_client))
    finally:
        asyncio.run(my_client.close())
        asyncio.run(credentials.close())
```

Let me know if this helps, or whether the problem is persisting :)

**Comment by PabloRuizCuevas** [comment]
hi, many thanks for the reply!

IT didn't solve the issue though, in fact is one of the many things i tried, the only work around currently is to create new instances of the class every time you use it, i tried with context manager, without context manager etc, also for the credentials and also with aio credentials.

I tried these (among many others)

```python
from azure.identity.aio import DefaultAzureCredential  # this import or the next one, but not at same time
from azure.identity import DefaultAzureCredential


# these two works but are terrible as we make new instances every time are called

async def test0():
    async with DefaultAzureCredential() as credential:
        async with ContainerClient.from_container_url(container_url=my_container_name, credential=credential) as client:
                stream = await client.download_blob(my_path)
                data = await stream.readall()
    return data

async def test1():    credential = DefaultAzureCredential()
    async with ContainerClient.from_container_url(container_url=my_container_name, credential=credential) as client:
        stream = await client.download_blob(my_path)
        data = await stream.readall()
    return data

# from here nothing works unless new instances are passed every time.

async def test2(my_client):
    async with my_client as client:
        stream = await client.download_blob(my_path)
        data = await stream.readall()
    return data

async def test3(my_client):
    stream = await my_client.download_blob(my_path)
    data = await stream.readall()
    session = my_client._client._client._pipeline._transport.session
    return data, session  # wthi 

async def test4(conn_client):
    stream = await conn_client.download_blob(my_path)
    data = await stream.readall()
    return data

```

In any case in the official example it is used within a context manager : https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/samples/blob_samples_hello_world_async.py

you can use:  session = my_client._client._client._pipeline._transport.session  # .closed   for seeing the stated of an underlying connection, but it is also not helping much, if you use with will be close ... but at the end is not helping much.


### Error log 

<details>

<summary>Your specific code gave me this error log:</summary>

> Traceback (most recent call last):
>   File "C:\Users\PabloRuiz\PycharmProjects\PlatformPythonProject\connections\blob_manager.py", line 307, in <module>
>     data2 = asyncio.run(test5(my_client))
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\PycharmProjects\PlatformPythonProject\connections\blob_manager.py", line 290, in test5
>     stream = await conn_client.download_blob(my_path)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\azure\core\tracing\decorator_async.py", line 77, in wrapper_use_tracer
>     return await func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\azure\storage\blob\aio\_container_client_async.py", line 1154, in download_blob
>     return await blob_client.download_blob(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\azure\core\tracing\decorator_async.py", line 77, in wrapper_use_tracer
>     return await func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\azure\storage\blob\aio\_blob_client_async.py", line 541, in download_blob
>     await downloader._setup()  # pylint: disable=protected-access
>     ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\azure\storage\blob\aio\_download_async.py", line 288, in _setup
>     self._response = await self._initial_request()
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\azure\storage\blob\aio\_download_async.py", line 337, in _initial_request
>     location_mode, response = await self._clients.blob.download(
>                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\azure\core\tracing\decorator_async.py", line 77, in wrapper_use_tracer
>     return await func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\azure\storage\blob\_generated\aio\operations\_blob_operations.py", line 203, in download
>     pipeline_response: PipelineResponse = await self._client._pipeline.run(  # pylint: disable=protected-access
>                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\azure\core\pipeline\_base_async.py", line 221, in run
>     return await first_node.send(pipeline_request)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\azure\core\pipeline\_base_async.py", line 69, in send
>     response = await self.next.send(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\azure\core\pipeline\_base_async.py", line 69, in send
>     response = await self.next.send(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\azure\core\pipeline\_base_async.py", line 69, in send
>     response = await self.next.send(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   [Previous line repeated 3 more times]
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\azure\core\pipeline\policies\_authentication_async.py", line 94, in send
>     response = await self.next.send(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\azure\core\pipeline\_base_async.py", line 69, in send
>     response = await self.next.send(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\azure\core\pipeline\policies\_redirect_async.py", line 73, in send
>     response = await self.next.send(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\azure\core\pipeline\_base_async.py", line 69, in send
>     response = await self.next.send(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\azure\storage\blob\_shared\policies_async.py", line 111, in send
>     response = await self.next.send(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\azure\core\pipeline\_base_async.py", line 69, in send
>     response = await self.next.send(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\azure\storage\blob\_shared\policies_async.py", line 64, in send
>     response = await self.next.send(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\azure\core\pipeline\_base_async.py", line 69, in send
>     response = await self.next.send(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\azure\core\pipeline\_base_async.py", line 69, in send
>     response = await self.next.send(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\azure\core\pipeline\_base_async.py", line 106, in send
>     await self._sender.send(request.http_request, **request.context.options),
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\azure\storage\blob\_shared\base_client_async.py", line 175, in send
>     return await self._transport.send(request, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\azure\core\pipeline\transport\_aiohttp.py", line 263, in send
>     result = await self.session.request(  # type: ignore
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\aiohttp\client.py", line 573, in _request
>     conn.protocol.set_response_params(
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\aiohttp\client_proto.py", line 150, in set_response_params
>     self._reschedule_timeout()
>   File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\aiohttp\client_proto.py", line 178, in _reschedule_timeout
>     self._read_timeout_handle = self._loop.call_later(
>                                 ^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 727, in call_later
>     timer = self.call_at(self.time() + delay, callback, *args,
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 740, in call_at
>     self._check_closed()
>   File "C:\Users\PabloRuiz\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 519, in _check_closed
>     raise RuntimeError('Event loop is closed')
> RuntimeError: Event loop is closed
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\PabloRuiz\PycharmProjects\PlatformPythonProject\connections\blob_manager.py", line 310, in <module>
>     asyncio.run(credentials.close())
>   File "C:\Users\PabloRuiz\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "C:\Users\PabloRuiz\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 89, in run
>     raise ValueError("a coroutine was expected, got {!r}".format(coro))
> ValueError: a coroutine was expected, got None
> 
> Process finished with exit code 1
> 

</details>

**Comment by PabloRuizCuevas** [comment]
The intention of this is being able to asyncio.gather request or getting multiple files at once, if anyone have any workaround for that would be enough.

For now i found a workaround, but is not very performant: using: asyncio.to_thread.

```python
    # something similar to this:
    def read_blob_stream(client, path: str , encoding=None) -> BytesIO:
        """Reads the blob and returns a BytesIO (file) object"""
          data_stream = BytesIO()
          super().download_blob(path, encoding=encoding).readinto(data_stream)
          data_stream.seek(0)
        return data_stream

    def aio_read_blob(client, path: str , encoding=None) -> Awaitable[BytesIO]:
        # cause there is no real aio support this convert basically everything in truly aio with a bit of overhead
        path = str(path) if isinstance(path, PurePath) else path
        return asyncio.to_thread(read_blob_stream, path, encoding)
```
with this you can gather the tasks and run them, but is not the greatest solution as creating threads has overhead

**Comment by weirongw23-msft** [comment]
Hi @PabloRuizCuevas Pablo, thanks for your patience and sorry for the late reply.

The reason you're seeing this is due to passing `my_client` (which is a `ContainerClient`) to the `test()` function. The context manager inside the `test()` function will automatically call `__aenter__()` and `__aexit__()`. Once `__aexit__()` has been invoked, the connection cannot be reopened.

You should be able to resolve this by making an async `main()` function and directly calling `asyncio.run(main())` in `if __name__ == "__main__"` check. Within the async `main()` function, create a context manager that constructs a `ContainerClient`, and use that same `ContainerClient` to pass into your `test()` function. This will work regardless of the authentication method you choose.

Here's the sample code that successfully downloaded the blob 100 times. Note that I changed the name from `test()` to `download()` and instead used `ContainerClient.from_connection_string()` to construct the client, but it's the same idea :)
```python3
import asyncio

from azure.storage.blob.aio import ContainerClient


async def download(cc: ContainerClient, path: str) -> bytes:
    stream = await cc.download_blob(path)
    data = await stream.readall()
    return data


async def main():
    print("Testing download many times...")

    path = "blob"  # replace with your blob path
    async with ContainerClient.from_connection_string(
        conn_str="",  # replace with your connection string
        container_name="container"  # replace with your container
    ) as cc:
        first_data = await download(cc, path)
        assert first_data

        for _ in range(100):
            data = await download(cc, path)
            assert data == first_data

    print("Passed!")


if __name__ == "__main__":
    asyncio.run(main())

```

If you'd like to leverage `asyncio.gather()`, here's a sample that successfully downloaded the blob 100 times (but faster!):

```python3
import asyncio

from azure.storage.blob.aio import ContainerClient


async def download(cc: ContainerClient, path: str) -> bytes:
    stream = await cc.download_blob(path)
    data = await stream.readall()
    return data


async def main():
    print("Testing download many times...")

    path = "blob"  # replace with your blob path
    async with ContainerClient.from_connection_string(
        conn_str="",  # replace with your connection string
        container_name="container"  # replace with your container
    ) as cc:
        coroutines = [download(cc, path) for _ in range(100)]
        await asyncio.gather(*coroutines)

    print("Passed!")


if __name__ == "__main__":
    asyncio.run(main())

```

Thanks!
