### ISSUE TITLE
DefaultCredential() expires after 55 minutes in Azure Devops

### ISSUE THREAD

**Issue by ToxicGLaDOS** [Azure/azure-sdk-for-python#32555]
- **Package Name**: azure-mgmt-authorization
- **Package Version**: 4.0.0
- **Operating System**: linux
- **Python Version**: Python 3.8.10

**Describe the bug**
After 55 minutes (+/- 30 seconds) of running my script it suddenly fails with this error, only making through about 430/14785 containers in the storage account (+/- 5 containers).
```
Traceback (most recent call last):
  File "//azp/agent/_work/_tool/env/lib/python3.8/site-packages/azure/identity/_credentials/azure_cli.py", line 195, in _run_command
    return subprocess.check_output(args, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/bin/sh', '-c', 'az account get-access-token --output json --resource [https://management.azure.com']'](https://management.azure.com%27]%27/) returned non-zero exit status 1.

The above exception was the direct cause of the following exception:
 Traceback (most recent call last):
  File "test.py", line 26, in <module>
    role_definition = role_definition = authorization_management_client.role_definitions.get_by_id(role_assignment.role_definition_id)
  File "//azp/agent/_work/_tool/env/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "//azp/agent/_work/_tool/env/lib/python3.8/site-packages/azure/mgmt/authorization/v2022_04_01/operations/_role_definitions_operations.py", line 569, in get_by_id
    pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
  File "//azp/agent/_work/_tool/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 230, in run
    return first_node.send(pipeline_request)
  File "//azp/agent/_work/_tool/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "//azp/agent/_work/_tool/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "//azp/agent/_work/_tool/env/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "//azp/agent/_work/_tool/env/lib/python3.8/site-packages/azure/mgmt/core/policies/_base.py", line 46, in send
    response = self.next.send(request)
  File "//azp/agent/_work/_tool/env/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 197, in send
    response = self.next.send(request)
  File "//azp/agent/_work/_tool/env/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry.py", line 531, in send
    response = self.next.send(request)
  File "//azp/agent/_work/_tool/env/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 124, in send
    self.on_request(request)
  File "//azp/agent/_work/_tool/env/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 99, in on_request
    self._token = self._credential.get_token(*self._scopes)
  File "//azp/agent/_work/_tool/env/lib/python3.8/site-packages/azure/identity/_credentials/default.py", line 219, in get_token
    token = self._successful_credential.get_token(*scopes, claims=claims, tenant_id=tenant_id, **kwargs)
  File "//azp/agent/_work/_tool/env/lib/python3.8/site-packages/azure/identity/_internal/decorators.py", line 33, in wrapper
    token = fn(*args, **kwargs)
  File "//azp/agent/_work/_tool/env/lib/python3.8/site-packages/azure/identity/_credentials/azure_cli.py", line 108, in get_token
    output = _run_command(command, self._process_timeout)
  File "//azp/agent/_work/_tool/env/lib/python3.8/site-packages/azure/identity/_credentials/azure_cli.py", line 202, in _run_command
    raise CredentialUnavailableError(message=NOT_LOGGED_IN) from ex
azure.identity._exceptions.CredentialUnavailableError: Please run 'az login' to set up an account
```

**To Reproduce**
Run this script:
```
#!/usr/bin/env python

from azure.mgmt.authorization import AuthorizationManagementClient
from azure.identity import DefaultAzureCredential
from azure.storage.blob import BlobServiceClient

subscription_id = "<my-subscription-id>"
storage_account_name = "<my-storage-account-with-many-containers>"
resource_group_name = "<storage-account-resource-group>"

blob_endpoint = f"https://{storage_account_name}.blob.core.windows.net"
storage_account_id = f"/subscriptions/{subscription_id}/resourceGroups/{resource_group_name}/providers/Microsoft.Storage/storageAccounts/{storage_account_name}"

blob_service_client = BlobServiceClient(blob_endpoint, DefaultAzureCredential())
containers = blob_service_client.list_containers()

authorization_management_client = AuthorizationManagementClient(DefaultAzureCredential(), subscription_id)

containers = list(containers)
total_containers = len(containers)
for index, container in enumerate(containers):
    role_assignments = authorization_management_client.role_assignments.list_for_scope(storage_account_id + f"/path/{container.name}")

    print(f"Getting rbac for {storage_account_name}/{container.name} {index}/{total_containers}", flush=True)
    for role_assignment in role_assignments:
        role_definition = role_definition = authorization_management_client.role_definitions.get_by_id(role_assignment.role_definition_id)
```

**Expected behavior**
The script should run through all containers in the storage account

**Additional context**
This script seems to run fine when I run it on my machine. I believe that the issue might have something to do with how Azure Devops auths: `/usr/bin/az login --service-principal -u *** --tenant *** --allow-no-subscriptions --federated-token ***`

**Comment by xiangyan99** [comment]
Unfortunately, this is not something SDK can help. Please open a service ticket for the feedback.
