### ISSUE TITLE
Error when reverse_search_address in azure-maps-search

### ISSUE THREAD

**Issue by zhongshuai-cao** [Azure/azure-sdk-for-python#32565]
- **Package Name**: azure-maps-search
- **Package Version**: 1.0.0b2
- **Package Name**: msrest
- **Package Version**: 0.7.1 
- **Operating System**:MacOS 14
- **Python Version**: 3.9.12 

**Describe the bug**
I am not able to search a specific coordinates, but the code works for other coordinates (13.475227, 144.712342)

**To Reproduce**
1. change the coordinates in the sample code  to (13.475227, 144.712342) and run the sample script from the example repo. ref: https://github.com/Azure/azure-sdk-for-python/blob/azure-maps-search_1.0.0b2/sdk/maps/azure-maps-search/samples/sample_reverse_search_address.py
2. get below error
```
Traceback
/Users/zhongshuaicao/opt/anaconda3/envs/myenv/bin/python /Users/zhongshuaicao/Projects/mapsDemo/sample_reverse_search_address.py 
Traceback (most recent call last):
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1613, in deserialize_data
    return self.deserialize_basic(data, data_type)
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1756, in deserialize_basic
    return eval(data_type)(attr)
ValueError: invalid literal for int() with base 10: 'GU-1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1626, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1657, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1657, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1637, in deserialize_data
    raise_with_traceback(DeserializationError, msg, err)
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1613, in deserialize_data
    return self.deserialize_basic(data, data_type)
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1756, in deserialize_basic
    return eval(data_type)(attr)
azure.core.exceptions.DeserializationError: ("Unable to deserialize response data. Data: GU-1, int, ValueError: invalid literal for int() with base 10: 'GU-1'", ValueError("invalid literal for int() with base 10: 'GU-1'"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1626, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1657, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1657, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1639, in deserialize_data
    return self._deserialize(obj_type, data)
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1450, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1639, in deserialize_data
    return self._deserialize(obj_type, data)
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1450, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1637, in deserialize_data
    raise_with_traceback(DeserializationError, msg, err)
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1626, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1657, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1657, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1637, in deserialize_data
    raise_with_traceback(DeserializationError, msg, err)
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1613, in deserialize_data
    return self.deserialize_basic(data, data_type)
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1756, in deserialize_basic
    return eval(data_type)(attr)
azure.core.exceptions.DeserializationError: ('Unable to deserialize response data. Data: [\'GU-1\'], [int], DeserializationError: ("Unable to deserialize response data. Data: GU-1, int, ValueError: invalid literal for int() with base 10: \'GU-1\'", ValueError("invalid literal for int() with base 10: \'GU-1\'"))', DeserializationError("Unable to deserialize response data. Data: GU-1, int, ValueError: invalid literal for int() with base 10: 'GU-1'", ValueError("invalid literal for int() with base 10: 'GU-1'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhongshuaicao/Projects/mapsDemo/sample_reverse_search_address.py", line 38, in <module>
    reverse_search_address()
  File "/Users/zhongshuaicao/Projects/mapsDemo/sample_reverse_search_address.py", line 32, in reverse_search_address
    result = maps_search_client.reverse_search_address(coordinates=(13.475227, 144.712342), language="en")
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/azure/maps/search/_search_client.py", line 315, in reverse_search_address
    result = self._search_client.reverse_search_address(
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/azure/maps/search/_generated/operations/_search_operations.py", line 1706, in reverse_search_address
    deserialized = self._deserialize('ReverseSearchAddressResult', pipeline_response)
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1376, in __call__
    return self._deserialize(target_obj, data)
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1450, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1637, in deserialize_data
    raise_with_traceback(DeserializationError, msg, err)
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1626, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1657, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1657, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1639, in deserialize_data
    return self._deserialize(obj_type, data)
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1450, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1639, in deserialize_data
    return self._deserialize(obj_type, data)
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1450, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1637, in deserialize_data
    raise_with_traceback(DeserializationError, msg, err)
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1626, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1657, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1657, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1637, in deserialize_data
    raise_with_traceback(DeserializationError, msg, err)
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1613, in deserialize_data
    return self.deserialize_basic(data, data_type)
  File "/Users/zhongshuaicao/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/msrest/serialization.py", line 1756, in deserialize_basic
    return eval(data_type)(attr)
azure.core.exceptions.DeserializationError: ('Unable to deserialize response data. Data: [{\'address\': {\'buildingNumber\': \'405\', \'streetNumber\': \'405\', \'routeNumbers\': [\'GU-1\'], \'street\': \'Asan Ocean View Drive\', \'streetName\': \'Asan Ocean View Drive\', \'streetNameAndNumber\': \'405 Asan Ocean View Drive\', \'countryCode\': \'GU\', \'countrySubdivision\': \'GU\', \'countrySecondarySubdivision\': \'Guam\', \'municipality\': \'Santa Rita\', \'postalCode\': \'96915\', \'country\': \'Guam\', \'countryCodeISO3\': \'GUM\', \'freeformAddress\': \'405 Asan Ocean View Drive, Santa Rita, Guam 96915\', \'boundingBox\': {\'northEast\': \'13.472760,144.713220\', \'southWest\': \'13.472370,144.711680\', \'entity\': \'position\'}, \'countrySubdivisionName\': \'Guam\', \'countrySubdivisionCode\': \'GU\', \'localName\': \'Santa Rita\'}, \'position\': \'13.472711,144.713028\', \'id\': \'EUPDgaCquPKXlXncDett_w\'}], [ReverseSearchAddressResultItem], DeserializationError: (\'Unable to deserialize response data. Data: [\\\'GU-1\\\'], [int], DeserializationError: ("Unable to deserialize response data. Data: GU-1, int, ValueError: invalid literal for int() with base 10: \\\'GU-1\\\'", ValueError("invalid literal for int() with base 10: \\\'GU-1\\\'"))\', DeserializationError("Unable to deserialize response data. Data: GU-1, int, ValueError: invalid literal for int() with base 10: \'GU-1\'", ValueError("invalid literal for int() with base 10: \'GU-1\'")))', DeserializationError('Unable to deserialize response data. Data: [\'GU-1\'], [int], DeserializationError: ("Unable to deserialize response data. Data: GU-1, int, ValueError: invalid literal for int() with base 10: \'GU-1\'", ValueError("invalid literal for int() with base 10: \'GU-1\'"))', DeserializationError("Unable to deserialize response data. Data: GU-1, int, ValueError: invalid literal for int() with base 10: 'GU-1'", ValueError("invalid literal for int() with base 10: 'GU-1'"))))

```

**Expected behavior**
With the default or other coordinates I tried, such as (47.61010, -122.34255)
the return is normal
```bash
Get Search Address Reverse:
{'additional_properties': {'countrySubdivisionCode': 'WA'}, 'building_number': '1914', 'street': 'Pike Place', 'cross_street': None, 'street_number': '1914', 'route_numbers': [], 'street_name': 'Pike Place', 'street_name_and_number': '1914 Pike Place', 'municipality': 'Seattle', 'municipality_subdivision': 'Downtown Seattle', 'country_tertiary_subdivision': None, 'country_secondary_subdivision': 'King', 'country_subdivision': 'WA', 'postal_code': '98101', 'extended_postal_code': '98101-1013', 'country_code': 'US', 'country': 'United States', 'country_code_iso3': 'USA', 'freeform_address': '1914 Pike Place, Seattle, WA 98101', 'country_subdivision_name': 'Washington', 'local_name': 'Seattle', 'bounding_box': {'northEast': '47.610415,-122.342147', 'southWest': '47.609627,-122.343472', 'entity': 'position'}}

Process finished with exit code 0
```

**Screenshots**
<img width="1600" alt="image" src="https://github.com/Azure/azure-sdk-for-python/assets/110563203/0d6e3f1c-f3dc-400a-938d-bb088d3d5924">

**Additional context**
I was able to get the pipeline_response, so it could either be the serverside, msrest side or the azure map api?

```bash
pipeline_response
Python 3.9.12 (main, Jun  1 2022, 06:36:29) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 8.4.0
Out[1]: <azure.core.pipeline.PipelineResponse at 0x7f97f817df40>
pipeline_response.context
Out[2]: 
{'logging_enable': False,
 'logger': <Logger azure.core.pipeline.policies.http_logging_policy (WARNING)>,
 'deserialized_data': {'summary': {'queryTime': 11, 'numResults': 1},
  'addresses': [{'address': {'buildingNumber': '405',
     'streetNumber': '405',
     'routeNumbers': ['GU-1'],
     'street': 'Asan Ocean View Drive',
     'streetName': 'Asan Ocean View Drive',
     'streetNameAndNumber': '405 Asan Ocean View Drive',
     'countryCode': 'GU',
     'countrySubdivision': 'GU',
     'countrySecondarySubdivision': 'Guam',
     'municipality': 'Santa Rita',
     'postalCode': '96915',
     'country': 'Guam',
     'countryCodeISO3': 'GUM',
     'freeformAddress': '405 Asan Ocean View Drive, Santa Rita, Guam 96915',
     'boundingBox': {'northEast': '13.472760,144.713220',
      'southWest': '13.472370,144.711680',
      'entity': 'position'},
     'countrySubdivisionName': 'Guam',
     'countrySubdivisionCode': 'GU',
     'localName': 'Santa Rita'},
    'position': '13.472711,144.713028',
    'id': 'EUPDgaCquPKXlXncDett_w'}]}}
```

**Comment by catalinaperalta** [comment]
Thanks for reaching out @zhongshuai-cao! Looping in @dubiety to take a look
