### ISSUE TITLE
Unable to retrieve ManagedIdentity credentials from within a serverless job in Azure ML Workspace

### ISSUE THREAD

**Issue by mauibar** [Azure/azure-sdk-for-python#32921]
Package Name: azure.identity-1.14.1, azure-keyvault-secrets-4.7.0
Operating System: Linux
Python Version: 3.8

**Describe the bug**
I am trying to get the ManagedIdentity credentials in order to access some secrets within a KeyVault in a serverless jobs in the Azure ML workspace

Here is the full trace error:

```
2023/11/02 15:03:34 INFO ManagedIdentityCredential will use Azure ML managed identity
2023-11-02 15:03:34.367 | WARNING  | trainer.run_manager:_get_token:60 - <azure.identity._credentials.managed_identity.ManagedIdentityCredential object at 0x15032c7a4c10>
2023/11/02 15:03:34 WARNING AzureMLCredential.get_token failed: Unexpected content type "text/plain; charset=utf-8"
Content: InternalError - :{
Info: Request failure status code: 404

}
2023/11/02 15:03:34 WARNING ManagedIdentityCredential.get_token failed: Unexpected content type "text/plain; charset=utf-8"
Content: InternalError - :{
Info: Request failure status code: 404

}
Traceback (most recent call last):
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/core/pipeline/policies/_universal.py", line 614, in deserialize_from_text
    return json.loads(data_as_str)
  File "/opt/conda/envs/ptca/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/envs/ptca/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/envs/ptca/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/identity/_internal/managed_identity_client.py", line 41, in _process_response
    content = ContentDecodePolicy.deserialize_from_text(
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/core/pipeline/policies/_universal.py", line 616, in deserialize_from_text
    raise DecodeError(
azure.core.exceptions.DecodeError: JSON is invalid: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/ptca/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/ptca/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/azureml/cr/j/60811a0967a64dae83ca1768599fd992/exe/wd/trainer/run_executor.py", line 25, in <module>
    run_manager: RunManager = RunOptionManager.from_dictionary(vars(run_args))
  File "/mnt/azureml/cr/j/60811a0967a64dae83ca1768599fd992/exe/wd/trainer/option_manager.py", line 60, in from_dictionary
    return cls.managed_class(**args)
  File "/mnt/azureml/cr/j/60811a0967a64dae83ca1768599fd992/exe/wd/trainer/run_manager.py", line 31, in __init__
    access_token = self._get_token()
  File "/mnt/azureml/cr/j/60811a0967a64dae83ca1768599fd992/exe/wd/trainer/run_manager.py", line 63, in _get_token
    app_id = client.get_secret("sp-client-id-dev")
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/keyvault/secrets/_client.py", line 72, in get_secret
    bundle = self._client.get_secret(
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/keyvault/secrets/_generated/_operations_mixin.py", line 1640, in get_secret
    return mixin_instance.get_secret(vault_base_url, secret_name, secret_version, **kwargs)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/keyvault/secrets/_generated/v7_4/operations/_key_vault_client_operations.py", line 760, in get_secret
    pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 230, in run
    return first_node.send(pipeline_request)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 197, in send
    response = self.next.send(request)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry.py", line 531, in send
    response = self.next.send(request)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 135, in send
    request_authorized = self.on_challenge(request, response)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/keyvault/secrets/_shared/challenge_auth_policy.py", line 112, in on_challenge
    self.authorize_request(request, scope, tenant_id=challenge.tenant_id)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 113, in authorize_request
    self._token = self._credential.get_token(*scopes, **kwargs)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/identity/_internal/decorators.py", line 33, in wrapper
    token = fn(*args, **kwargs)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/identity/_credentials/managed_identity.py", line 137, in get_token
    return self._credential.get_token(*scopes, claims=claims, tenant_id=tenant_id, **kwargs)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/identity/_internal/managed_identity_base.py", line 47, in get_token
    return super(ManagedIdentityBase, self).get_token(*scopes, claims=claims, tenant_id=tenant_id, **kwargs)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/identity/_internal/get_token_mixin.py", line 86, in get_token
    token = self._request_token(*scopes, claims=claims, tenant_id=tenant_id, **kwargs)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/identity/_internal/managed_identity_base.py", line 55, in _request_token
    return cast(ManagedIdentityClient, self._client).request_token(*scopes, **kwargs)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/identity/_internal/managed_identity_client.py", line 113, in request_token
    token = self._process_response(response, request_time)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/identity/_internal/managed_identity_client.py", line 49, in _process_response
    raise ClientAuthenticationError(message=message, response=response.http_response) from ex
azure.core.exceptions.ClientAuthenticationError: Unexpected content type "text/plain; charset=utf-8"
Content: InternalError - :{
Info: Request failure status code: 404

}
```

**To Reproduce**
I am creating the job using the Python sdk as described in the documentation [here](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-use-serverless-compute?view=azureml-api-2&tabs=python)  
The workspace don't have a user assigned identity therefore I have used **UserIdentityConfiguration()**, as **ManagedIdentityConfiguration()** would prevent me from creating the job.
The job then fails at the following:

```
key_vault = "key_vault_id"
kv_uri = f"https://{key_vault}.vault.azure.net"

credential = ManagedIdentityCredential()
client = SecretClient(vault_url=kv_uri, credential=credential)

secret = client.get_secret("secret_id")
```

The same code to retrieve a secret works correctly on a VM inside the Azure ML Workspace

**Expected behavior**
I would expect to be able to use the system managed identity of the ML workspace to retrieve secrets in a serverless job

**Comment by iscai-msft** [comment]
Thanks for opening this issue @mauibar, tagging @azureml-github to take a look

**Comment by mh-hassan18** [comment]
I am also getting the same issue:

ManagedIdentityCredential: Unexpected content type "text/plain; charset=utf-8"
Content: InternalError - :{
Info: Request failure status code: 404

}

I've built the pipeline using azureml sdk v2 and one of my pipeline component is accessing a secret from keyvault. I have already assigned a user assigned managed identity to my compute cluster and my managed identity also has necessary accesses as described in this link: [Use authentication credential secrets in Azure Machine Learning jobs](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-use-secrets-in-runs?view=azureml-api-2)

**Comment by SterlingJS** [comment]
I am receiving the same error when attempted to use Microsoft's provided Azure ML ManagedIdentityCredential authentication:

[Set up authentication for Azure Machine Learning resources and workflows](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-setup-authentication?view=azureml-api-2&tabs=sdk#use-managed-identity-authentication)

I am running an AML pipeline on a compute cluster that has a User Assigned Identity assigned to it. This compute cluster is unable to fetch a token:

`Traceback (most recent call last):
  File "register.py", line 116, in <module>
    main(args)
  File "register.py", line 52, in main
    try_register(os.path.join(args.model_path, "model.pkl"), args)
  File "register.py", line 62, in try_register
    credential.get_token("https://management.azure.com/.default")
  File "/azureml-envs/azureml_d35e7bb4d44667adda25c9adec17f1ab/lib/python3.8/site-packages/azure/identity/_credentials/default.py", line 225, in get_token
    token = super().get_token(*scopes, claims=claims, tenant_id=tenant_id, **kwargs)
  File "/azureml-envs/azureml_d35e7bb4d44667adda25c9adec17f1ab/lib/python3.8/site-packages/azure/identity/_credentials/chained.py", line 123, in get_token
    raise ClientAuthenticationError(message=message)
azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
	ManagedIdentityCredential: Unexpected content type "text/plain; charset=utf-8"
Content: InternalError - :{
Info: Request failure status code: 404`

This does appear to be a real issue with the Python SDK, we need this resolved urgently since it is impacting a production use case

**Comment by xiangyan99** [comment]
Can you get the value of environment variables:

MSI_ENDPOINT
MSI_SECRET
?

**Comment by xiangyan99** [comment]
And to make sure we are on same page, you have followed the steps of

https://learn.microsoft.com/en-us/azure/machine-learning/how-to-identity-based-service-authentication?view=azureml-api-2&tabs=python

right?

**Comment by SterlingJS** [comment]
Hello,

We have a UAI set up for our Compute Cluster. The following steps taken
from the documentation fail:

client_id = os.environ.get('DEFAULT_IDENTITY_CLIENT_ID') credential =
ManagedIdentityCredential(client_id=client_id) token =
credential.get_token('https://storage.azure.com/')


The call to credential.get_token gives me the error.

Since I can successfully assign the UAI to the compute cluster, I’m
assuming I should be able to fetch a token, right? Is there a known
limitation with the SDKv2 regarding the get_token function?

I can get on a debug session Monday or Tuesday to walk through the issue we
are having.

Thanks,
James

**Comment by xiaoyu-work** [comment]
@xiangyan99 I was able to get MSI_ENDPOINT and MSI_SECRET but still got this same error.

**Comment by mauibar** [comment]
Hi,

Apologies for the late reply but this is still a pending issue.

I have tried and like @xiaoyu-work MSI_ENDPOINT and MSI_SECRET are set.

I now have colleagues that have the same exact error on a VM created within Azure ML Workspace..

**Comment by xiaoyu-work** [comment]
Hi @mauibar , in my case, I need to configure MSI for the compute or VM in AML workspace by following this guide: https://learn.microsoft.com/en-us/azure/machine-learning/how-to-setup-authentication?view=azureml-api-2&amp%3Btabs=sdk&tabs=sdk#configure-a-managed-identity. Did you try this?

**Comment by mauibar** [comment]
Yes I tried but it didn't work for that user. We have 5 people having a VM in Azure ML with the same configuration right now, it works fine for the others but for this user it doesn't work.

We tried getting a token manually with this code:

```
import os
import requests
msi_endpoint = os.environ.get("MSI_ENDPOINT", None)
msi_secret = os.environ.get("MSI_SECRET", None)
client_id = os.environ.get("UAI_CLIENT_ID", None)

print(msi_endpoint)
print(msi_secret)
print(client_id)

token_url = msi_endpoint + "?resource=https://management.azure.com"
headers = {"secret": msi_secret, "Metadata": "true"}
resp = requests.get(token_url, headers=headers)
resp.raise_for_status()
access_token = resp.json()["access_token"]

print(access_token)
```
 He gets a 404 error, values for MSI_ENDPOINT is `http://127.0.0.1:46808/MSI/auth` and MSI_SECRET is correctly set.
 
 Do you have any idea what could be the issue ?

**Comment by PranshuBansalDev** [comment]
@mauibar - ManagedIdentityCredential needs client_id passed to it, which you need to verify is available on your cluster

Try this:

```
key_vault = "key_vault_id"
kv_uri = f"https://{key_vault}.vault.azure.net"

credential = ManagedIdentityCredential(client_id=os.environ.get('DEFAULT_IDENTITY_CLIENT_ID'))
client = SecretClient(vault_url=kv_uri, credential=credential)

secret = client.get_secret("secret_id")
```

This resolved the issue for me (thank you @xiangyan99 for helping me identify it)

**Comment by matleve98** [comment]
The issue for me was that my compute cluster were in a different region than the managed identity assigned to it.
After creating and assigning a managed identity with the region which the compute has, it worked well.

**Comment by korommatyi** [comment]
We have the same error, however it is location dependent. Our managed identity is in westeurope and getting the token on any VMs in westeurope works like a charm. However anything outside of westeurope gives us 404.

**Comment by mauibar** [comment]
Indeed @PranshuBansalDev your solution worked !!!
The var `DEFAULT_IDENTITY_CLIENT_ID` is not set, but when I hardcode the ID I was able to use ManagedIdentity for the first time.
@xiangyan99 any idea why the var is not set ?

Anyway thanks it will improve our flow !! This definitely need to be documented somewhere !!!

**Comment by EliiseS** [comment]
If you set the `AZURE_CLIENT_ID` env var instead of `DEFAULT_IDENTITY_CLIENT_ID` the `ManagedIdentityCredential` object will pick it up without having to pass it in directly. You can also use the `DefaultAzureCredential()` when the `AZURE_CLIENT_ID` env var is set.
