### ISSUE TITLE
'Connection reset by peer' while calling using API

### ISSUE THREAD

**Issue by avinash-keshri** [Azure/azure-sdk-for-python#336]
Hi folks,

We are often getting this ''Connection reset by peer' error while using various functions. Below is an example of the error while using the 'list_disks()'. Kindly look into this.

Traceback (most recent call last):
  File "resources/azureMgr.py", line 426, in <module>
    print "--->",obj.get_disk_name_list()
  File "resources/azureMgr.py", line 49, in get_disk_name_list
    disks = self.sms.list_disks()
  File "/usr/local/lib/python2.7/dist-packages/azure/servicemanagement/servicemanagementservice.py", line 2287, in list_disks
    Disks)
  File "/usr/local/lib/python2.7/dist-packages/azure/servicemanagement/servicemanagementclient.py", line 322, in _perform_get
    response = self.perform_get(path, x_ms_version)
  File "/usr/local/lib/python2.7/dist-packages/azure/servicemanagement/servicemanagementclient.py", line 136, in perform_get
    response = self._perform_request(request)
  File "/usr/local/lib/python2.7/dist-packages/azure/servicemanagement/servicemanagementclient.py", line 294, in _perform_request
    resp = self._filter(request)
  File "/usr/local/lib/python2.7/dist-packages/azure/http/httpclient.py", line 231, in perform_request
    resp = connection.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1030, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline()
  File "/usr/lib/python2.7/socket.py", line 430, in readline
    data = recv(1)
  File "/usr/lib/python2.7/ssl.py", line 241, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 160, in read
    return self._sslobj.read(len)
socket.error: [Errno 104] Connection reset by peer

**Comment by themaxx75** [comment]
We also get it all the time when listing blobs in containers. 
Ended up wrapping every uses in try except for socket and httplib

**Comment by lmazuel** [comment]
Hello,

Sorry for this late answer. Is the problem already there using the latest version of the library and the latest contribution library (like `requests` 2.9.1)?
Thank you,

**Comment by lmazuel** [comment]
Closing this issue due to inactivity. Please feel free to open a new issue if the problem still persists using the latest version.
Thanks!
