### ISSUE TITLE
Passing `{}` to `_format_url_section` causes unhandled `IndexError`

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-sdk-for-python#33641]
- **Package Name**: azure-core
- **Package Version**: 1.29.6
- **Operating System**: All
- **Python Version**: All

**Describe the bug**

Even though the infinite loop is fixed by https://github.com/Azure/azure-sdk-for-python/pull/31718, `azure.core.pipeline.transport._base._format_url_section` still doesn't handle `IndexError`. Passing `{}`, `{[]}` or `{.y}` triggers unhandled `IndexError`.

**To Reproduce**
```py
from azure.core.pipeline.transport._base import _format_url_section
_format_url_section('{}')
# _format_url_section('{[]}')
# _format_url_section('{.y}')
```

Output:

```
Traceback (most recent call last):
  File "D:\cli\testproj\main.py", line 2, in <module>
    _format_url_section('{}')
  File "D:\cli\py311\Lib\site-packages\azure\core\pipeline\transport\_base.py", line 101, in _format_url_section
    return template.format(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Replacement index 0 out of range for positional args tuple
```

**Expected behavior**
`IndexError` should be handled.

**Additional context**
Originally reported to Azure CLI: https://github.com/Azure/azure-cli/issues/28077

**Comment by xiangyan99** [comment]
@jiasli could you give more details about this?

We asked this because we are deprecating the method _format_url_section.

**Comment by jiasli** [comment]
@xiangyan99, https://github.com/Azure/azure-cli/issues/28077 contains details about the original issue.
