### ISSUE TITLE
ManagedIdentity with client_id on ACA: An unexpected error occured while fetching the AAD Token.

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-sdk-for-python#33858]
- **Package Name**: azure-identity
- **Package Version**: 1.15.0
- **Operating System**: Linux (from python:3.11 Docker image)
- **Python Version**: 3.11

**Describe the bug**

I am trying to authenticate using a user-assigned identity on Azure Container Apps. I see that the identity is assigned in the Portal, but I keep getting an error when trying to retrieve a token:

```
# python3
Python 3.11.7 (main, Jan 11 2024, 10:33:01) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from azure.identity import ManagedIdentityCredential
>>> cred = ManagedIdentityCredential(client_id="ec1710f6-2363-4fdd-aae5-3e9a26ccf6fb")
>>> token = cred.get_token("https://api.openai.com/.default")
AppServiceCredential.get_token failed: (None) An unexpected error occured while fetching the AAD Token.
Code: None
Message: An unexpected error occured while fetching the AAD Token.
ManagedIdentityCredential.get_token failed: (None) An unexpected error occured while fetching the AAD Token.
Code: None
Message: An unexpected error occured while fetching the AAD Token.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/azure/identity/_internal/decorators.py", line 33, in wrapper
    token = fn(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/identity/_credentials/managed_identity.py", line 137, in get_token
    return self._credential.get_token(*scopes, claims=claims, tenant_id=tenant_id, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/identity/_internal/managed_identity_base.py", line 47, in get_token
    return super(ManagedIdentityBase, self).get_token(*scopes, claims=claims, tenant_id=tenant_id, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/identity/_internal/get_token_mixin.py", line 86, in get_token
    token = self._request_token(*scopes, claims=claims, tenant_id=tenant_id, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/identity/_internal/managed_identity_base.py", line 55, in _request_token
    return cast(ManagedIdentityClient, self._client).request_token(*scopes, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/identity/_internal/managed_identity_client.py", line 113, in request_token
    token = self._process_response(response, request_time)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/identity/_internal/managed_identity_client.py", line 57, in _process_response
    raise ClientAuthenticationError(
azure.core.exceptions.ClientAuthenticationError: (None) An unexpected error occured while fetching the AAD Token.
Code: None
Message: An unexpected error occured while fetching the AAD Token.
>>> 
```

**To Reproduce**

1. Checkout this branch: https://github.com/Azure-Samples/chatgpt-quickstart/pull/60
2. Run `azd up`
3. Try to use app.

**Expected behavior**

It should be able to get a token.

**Screenshots**

Identity setup:

Access control screen:
<img width="1192" alt="Screenshot 2024-01-16 at 10 22 12 AM" src="https://github.com/Azure/azure-sdk-for-python/assets/297042/fc4925db-ac38-4159-94b6-4e2f73552b70">

ACA Identity screen:
<img width="702" alt="Screenshot 2024-01-16 at 10 21 55 AM" src="https://github.com/Azure/azure-sdk-for-python/assets/297042/3fda7b89-ab4d-4c9c-8594-b3ffe0d90af9">

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by pamelafox** [comment]
Thanks for @xiangyan99 for looking into my logs and pointing out that my scope is nonsense. 

The correct scope is "https://cognitiveservices.azure.com/.default"

If anyone gets a similar error, check your scope!
