### ISSUE TITLE
Python Azure Monitor OpenTelemetry Package Sending Data to Wrong Cloud

### ISSUE THREAD

**Issue by seanmcgettrick** [Azure/azure-sdk-for-python#33895]
- **Package Name**: azure-monitor-opentelemetry 
- **Package Version**: 1.1.1
- **Operating System**: Linux
- **Python Version**: 3.11

**Describe the bug**
I am trying to instrument a Django application with azure-monitor-opentelemetry.  This application is hosted in AzureGov.  At first the application seems to be exporting data to the correct endpoint, but eventually errors out.  Based on console logs, it appears that the exporter is trying to send metrics data to a West US public cloud endpoint (the public Internet is not reachable from where this application is being run), and I am unsure as to why this is happening or where the endpoint value is even coming from to begin with.

**To Reproduce**

1. Create a Django application
2. Create an Application Insights instance hosted in AzureGov
3. Instrument the application with azure-monitor-opentelemetry
4. Run application

**Expected behavior**
Traces/Logs/Metrics show in Application Insights.

**Screenshots**

**Successful Request:**

```bash
INFO:azure.core.pipeline.policies.http_logging_policy:Request URL: 'https://usgovvirginia-1.in.applicationinsights.azure.us//v2.1/track'
Request method: 'POST'
Request headers:
    'Content-Type': 'application/json'
    'Content-Length': '1743'
    'Accept': 'application/json'
    'x-ms-client-request-id': '3e7c466e-b590-11ee-9e68-857fb722316d'
    'User-Agent': 'azsdk-python-azuremonitorclient/unknown Python/3.11.5 (Linux-5.15.0-1052-azure-x86_64-with-glibc2.31)'
A body is sent with the request
INFO:azure.core.pipeline.policies.http_logging_policy:Response status: 200
```

**Failed Request:**

```bash
ERROR:opentelemetry.sdk.metrics._internal.export:Exception while exporting metrics invalid literal for int() with base 10: 'None'
Traceback (most recent call last):
  File "/home/sean/test_django_otel/.venv/lib/python3.11/site-packages/opentelemetry/sdk/metrics/_internal/export/__init__.py", line 526, in _receive_metrics
    self._exporter.export(
  File "/home/sean/test_django_otel/.venv/lib/python3.11/site-packages/azure/monitor/opentelemetry/exporter/export/metrics/_exporter.py", line 93, in export
    envelope = self._point_to_envelope(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/test_django_otel/.venv/lib/python3.11/site-packages/azure/monitor/opentelemetry/exporter/export/metrics/_exporter.py", line 139, in _point_to_envelope
    envelope = _handle_std_metric_envelope(envelope, name, point.attributes) # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/test_django_otel/.venv/lib/python3.11/site-packages/azure/monitor/opentelemetry/exporter/export/metrics/_exporter.py", line 224, in _handle_std_metric_envelope
    properties["Dependency.Success"] = str(_is_status_code_success(status_code, 400)) # type: ignore
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/test_django_otel/.venv/lib/python3.11/site-packages/azure/monitor/opentelemetry/exporter/export/metrics/_exporter.py", line 265, in _is_status_code_success
    return status_code is not None and int(status_code) < threshold
                                       ^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'None'
INFO:azure.core.pipeline.policies.http_logging_policy:Request URL: 'https://westus-0.in.applicationinsights.azure.com//v2.1/track'
```

**Comment by kashifkhan** [comment]
Thank you for the feedback @seanmcgettrick . We will investigate and get back to you asap. 

Are you able to provide some snippet of code from your application with the set up etc. that can help with debugging please ?

**Comment by seanmcgettrick** [comment]
@kashifkhan Thank you for the quick response.  Here is the code snippet from the settings.py file for the Django application I am testing with:

```python
# Setup Observability
LOGGER_NAME = 'test-django-otel'

logging.basicConfig(level=logging.INFO)
                    
instrumentation_options = {
    "azure_sdk": {"enabled": True}, 
    "django": {"enabled": True},
    "flask": {"enabled": False},
    "fastapi": {"enabled": False}, 
    "psycopg2": {"enabled": False},
}

app_insights_connection_string = os.getenv('APPLICATION_INSIGHTS_CONNECTION_STRING')
configure_azure_monitor(
    connection_string=app_insights_connection_string, 
    disable_offline_storage=True, 
    logger_name=LOGGER_NAME, 
    instrumentation_options=instrumentation_options
)

DjangoInstrumentor().instrument()
```

**Comment by seanmcgettrick** [comment]
@lzchen 

I am no longer seeing the WestUS collector endpoint showing up in the logs after setting the environment variable, but I am still getting the error below which I thought was being caused by the exporter trying to send metrics to the wrong endpoint, but apparently not.  Would it be more appropriate to close this issue and open a new one?

Thank you.

```bash
ERROR:opentelemetry.sdk.metrics._internal.export:Exception while exporting metrics invalid literal for int() with base 10: 'None'
Traceback (most recent call last):
  File "/home/sean/test_django_otel/.venv/lib/python3.11/site-packages/opentelemetry/sdk/metrics/_internal/export/__init__.py", line 526, in _receive_metrics
    self._exporter.export(
  File "/home/sean/test_django_otel/.venv/lib/python3.11/site-packages/azure/monitor/opentelemetry/exporter/export/metrics/_exporter.py", line 93, in export
    envelope = self._point_to_envelope(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/test_django_otel/.venv/lib/python3.11/site-packages/azure/monitor/opentelemetry/exporter/export/metrics/_exporter.py", line 139, in _point_to_envelope
    envelope = _handle_std_metric_envelope(envelope, name, point.attributes) # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/test_django_otel/.venv/lib/python3.11/site-packages/azure/monitor/opentelemetry/exporter/export/metrics/_exporter.py", line 224, in _handle_std_metric_envelope
    properties["Dependency.Success"] = str(_is_status_code_success(status_code, 400)) # type: ignore
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/test_django_otel/.venv/lib/python3.11/site-packages/azure/monitor/opentelemetry/exporter/export/metrics/_exporter.py", line 265, in _is_status_code_success
    return status_code is not None and int(status_code) < threshold
                                       ^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'None'
```

**Comment by lzchen** [comment]
@seanmcgettrick 

Yup, feel free to close this issue and open a new one :) If you could include the code snippet as well that you provided that would be most helpful
