### ISSUE TITLE
[eng][typespec] log is not clear when fail to generate Python SDK

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-for-python#34171]
The following log can't show what error happens, so we need more detailed information.
```
06:21:58.59 cmdout 	[automation_generate.sh] Command succeeded (00:00:17.4322081)
06:21:58.60 cmdout 	[automation_generate.sh] npx tsp compile /mnt/vss/_work/1/s/azure-sdk-for-python/sdk/face/azure-ai-face/TempTypeSpecFiles/Face/main.tsp --emit @azure-tools/typespec-python --option @azure-tools/typespec-python.emitter-output-dir=/mnt/vss/_work/1/s/azure-sdk-for-python/sdk/face/azure-ai-face/
06:22:01.33 cmdout 	[automation_generate.sh] [31;1mWrite-Error: [31;1mFailed to generate sdk project at /mnt/vss/_work/1/s/azure-sdk-for-python/sdk/face/azure-ai-face[0m
06:22:01.39 cmdout 	[automation_generate.sh] Traceback (most recent call last):
06:22:01.39 cmdout 	[automation_generate.sh]   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/runpy.py", line 196, in _run_module_as_main
06:22:01.43 cmdout 	[automation_generate.sh]     return _run_code(code, main_globals, None,
06:22:01.44 cmdout 	[automation_generate.sh]   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/runpy.py", line 86, in _run_code
06:22:01.44 cmdout 	[automation_generate.sh]     exec(code, run_globals)
06:22:01.44 cmdout 	[automation_generate.sh]   File "/mnt/vss/_work/1/s/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/sdk_generator.py", line 391, in <module>
06:22:01.44 cmdout 	[automation_generate.sh]     generate_main()
06:22:01.44 cmdout 	[automation_generate.sh]   File "/mnt/vss/_work/1/s/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/sdk_generator.py", line 387, in generate_main
06:22:01.44 cmdout 	[automation_generate.sh]     main(args.generate_input, args.generate_output)
06:22:01.44 cmdout 	[automation_generate.sh]   File "/mnt/vss/_work/1/s/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/sdk_generator.py", line 288, in main
06:22:01.44 cmdout 	[automation_generate.sh]     config = gen_typespec(input_readme, spec_folder, data["headSha"], data["repoHttpsUrl"])
06:22:01.44 cmdout 	[automation_generate.sh]   File "/mnt/vss/_work/1/s/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/generate_utils.py", line 388, in gen_typespec
06:22:01.44 cmdout 	[automation_generate.sh]     check_call(f'pwsh {Path("eng/common/scripts/TypeSpec-Project-Process.ps1")} {(Path(spec_folder) / typespec_relative_path).resolve()} {head_sha} {rest_repo_url}', shell=True)
06:22:01.44 cmdout 	[automation_generate.sh]   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/subprocess.py", line 369, in check_call
06:22:01.46 cmdout 	[automation_generate.sh]     raise CalledProcessError(retcode, cmd)
06:22:01.46 cmdout 	[automation_generate.sh] subprocess.CalledProcessError: Command 'pwsh eng/common/scripts/TypeSpec-Project-Process.ps1 /mnt/vss/_work/1/s/azure-rest-api-specs/specification/ai/Face e04d52a0a945c258a0034be6cd9e2bc578cab404 https://github.com/Azure/azure-rest-api-specs' returned non-zero exit status 1.
06:22:01.50 cmdout 	[automation_generate.sh] [Generate] codegen done!!!
06:22:01.50 cmdout 	[automation_generate.sh] [Autorest]/mnt/vss/_work/1/s/azure-sdk-for-python_tmp/venv-sdk/auto_temp.json does not exist!!!Error happened during codegen
06:22:01.50 error C 	Script return with result [failed] code [1] signal [null] cwd [azure-sdk-for-python]: sh scripts/automation_generate.sh
06:22:01.50 warn 	Skip package processing as generation is failed
```

**Comment by msyyc** [comment]
https://github.com/Azure/azure-sdk-for-python/pull/34172
