### ISSUE TITLE
DataLakeFileClient file_system_client_async  Too many open files

### ISSUE THREAD

**Issue by liabozarth** [Azure/azure-sdk-for-python#34457]
- **Package Name**: azure-storage-file-datalake
- **Package Version**: 12.14.0
- **Operating System**: azure container instance
- **Python Version**: 3.10

**Describe the bug**
We are using the async DataLakeServiceClient to download and upload lots of file asyncrohonously. We closed all directory and file clients after each upload, but still  Too many open files error.

`
azure.core.exceptions.ServiceRequestError: Cannot connect to host uwcipdatalake.blob.core.windows.net:443 ssl:default [Too many open files]
2024-02-26 17:35:39 | ERROR | telegram-capturer | stream.py:_produce_event() | unexpected error when produce event: Cannot connect to host uwcipdatalake.blob.core.windows.net:443 ssl:default [Too many open files]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1173, in _create_direct_connection
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 884, in _resolve_host
  File "/usr/local/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
OSError: [Errno 24] Too many open files

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/transport/_aiohttp.py", line 294, in send
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 574, in _request
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 544, in connect
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 911, in _create_connection
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1187, in _create_direct_connection
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host uwcipdatalake.blob.core.windows.net:443 ssl:default [Too many open files]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/projects/platform-capturer/platform_capturer/telegram/stream.py", line 55, in _produce_event
    await self.download_media(message)
  File "/code/projects/platform-capturer/platform_capturer/telegram/clientutils.py", line 153, in download_media
  File "/code/projects/platform-capturer/platform_capturer/telegram/clientutils.py", line 109, in _media_file_exists
  File "/code/projects/platform-capturer/platform_capturer/base/storage.py", line 207, in file_exists
  File "/usr/local/lib/python3.10/site-packages/azure/core/tracing/decorator_async.py", line 77, in wrapper_use_tracer
  File "/usr/local/lib/python3.10/site-packages/azure/storage/filedatalake/aio/_data_lake_file_client_async.py", line 196, in exists
  File "/usr/local/lib/python3.10/site-packages/azure/storage/filedatalake/aio/_path_client_async.py", line 735, in _exists
  File "/usr/local/lib/python3.10/site-packages/azure/core/tracing/decorator_async.py", line 77, in wrapper_use_tracer
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/aio/_blob_client_async.py", line 680, in exists
  File "/usr/local/lib/python3.10/site-packages/azure/core/tracing/decorator_async.py", line 77, in wrapper_use_tracer
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/_generated/aio/operations/_blob_operations.py", line 491, in get_properties
  File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/_base_async.py", line 221, in run
  File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/_base_async.py", line 69, in send
  File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/_base_async.py", line 69, in send
  File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/_base_async.py", line 69, in send
  [Previous line repeated 5 more times]
  File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/policies/_redirect_async.py", line 73, in send
  File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/_base_async.py", line 69, in send
  File "/usr/local/lib/python3.10/site-packages/azure/storage/filedatalake/_shared/policies_async.py", line 137, in send
  File "/usr/local/lib/python3.10/site-packages/azure/storage/filedatalake/_shared/policies_async.py", line 111, in send
  File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/_base_async.py", line 69, in send
  File "/usr/local/lib/python3.10/site-packages/azure/storage/filedatalake/_shared/policies_async.py", line 64, in send
  File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/_base_async.py", line 69, in send
  File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/_base_async.py", line 69, in send
  File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/_base_async.py", line 106, in send
  File "/usr/local/lib/python3.10/site-packages/azure/storage/filedatalake/_shared/base_client_async.py", line 180, in send
  File "/usr/local/lib/python3.10/site-packages/azure/storage/filedatalake/_shared/base_client_async.py", line 180, in send
  File "/usr/local/lib/python3.10/site-packages/azure/storage/filedatalake/_shared/base_client_async.py", line 180, in send
  File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/transport/_aiohttp.py", line 332, in send
azure.core.exceptions.ServiceRequestError: Cannot connect to host uwcipdatalake.blob.core.windows.net:443 ssl:default [Too many open files]
2024-02-26 17:35:42 | ERROR | telegram-capturer | stream.py:_produce_event() | unexpected error when produce event: Cannot connect to host uwcipdatalake.blob.core.windows.net:443 ssl:default [Too many open files]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1173, in _create_direct_connection
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 884, in _resolve_host
  File "/usr/local/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
OSError: [Errno 24] Too many open files

`

**To Reproduce**
1. See our code block below

**Expected behavior**
It shouldn't through too many open files error

**Screenshots**
code
![image](https://github.com/Azure/azure-sdk-for-python/assets/111392243/c3453893-5bb0-4d96-8d14-9455a74fa1cd)
![image](https://github.com/Azure/azure-sdk-for-python/assets/111392243/a6d01137-3302-42ea-9ee2-1b19138090c2)
![image](https://github.com/Azure/azure-sdk-for-python/assets/111392243/33b6fc34-f133-4a11-a70e-1c70eafe47cf)

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by jalauzon-msft** [comment]
Hi @liabozarth, here are a couple of things to consider:

- How often are you running that first `__init__` method you shared? Is that running once for the application or more frequently? It is best to keep one top level client alive for the lifetime of the app and spawn sub-clients from that to take advantage of connection pooling. It seems like you are doing this, just wanted to be sure.
- How many file system clients are you creating? If you are creating a lot, this could be an issue since you are keeping them in memory.
- I would suggest refactoring your other methods to use context managers to manage the lifetime of clients rather than closing them manually. This would just make sure they get closed in the event of an exception or something as well. For example, `file_exists` could look like below.

```py
async def file_exists(...):
  async with self.file_system_clients[file_system].get_directory_client(directory_name) as directory_client:
    async with directory_client.get_file_client(file_name) as file_client:
      return await file_client.exists()
```

All the being said, overall, your code looks like it may be mostly fine so you may just be hitting OS limits on open files assuming you are doing a lot of operations in parallel. You can try increasing the limit for your environment. On Linux you would likely use the [ulimit -n](https://ss64.com/bash/ulimit.html) command for that but I'm not sure how to go about this in Azure Container.

**Comment by liabozarth** [comment]
Hi, I changed over to synchronous client instead and the issue went away.

**Comment by jalauzon-msft** [comment]
Thanks for the update! Interesting that switching to sync helped in this scenario but glad it worked out. I'll close this issue for now but keep an eye on this type of issue.
