### ISSUE TITLE
Unable to get datastore data or create a new one using SDK v2

### ISSUE THREAD

**Issue by paudan** [Azure/azure-sdk-for-python#34534]
- **Package Name**: azure-ai-ml
- **Package Version**: 1.13.0
- **Operating System**: Windows. Linux
- **Python Version**: 3.9

**Describe the bug**
When I try to run the following sample code for retrieving datastore object (adopted from [Machine Learning reference):](https://learn.microsoft.com/en-us/azure/machine-learning/migrate-to-v2-resource-datastore?view=azureml-api-2)

```python
import os
from dotenv import load_dotenv
load_dotenv(".env")
from azure.ai.ml import MLClient
from azure.identity import DefaultAzureCredential

subscription_id = os.environ['SUBSCRIPTION_ID']
resource_group = os.environ['RESOURCE_GROUP']
workspace_name = os.environ['WORKSPACE_NAME']

ml_client = MLClient(credential=DefaultAzureCredential(),
                     subscription_id=subscription_id, 
                     resource_group_name=resource_group)

datastore = ml_client.datastores.get(name='workspaceartifactstore')
```

I get the following error:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\python\azure-mltable\lib\site-packages\azure\ai\ml\_telemetry\activity.py", line 275, in wrapper
  File "D:\python\azure-mltable\lib\site-packages\azure\ai\ml\operations\_datastore_operations.py", line 140, in get
    datastore_resource = self._operation.get(
  File "D:\python\azure-mltable\lib\site-packages\azure\core\tracing\decorator.py", line 76, in wrapper_use_tracer
  File "D:\python\azure-mltable\lib\site-packages\azure\ai\ml\_restclient\v2023_04_01_preview\operations\_datastores_operations.py", line 493, in get
  File "D:\python\azure-mltable\lib\site-packages\azure\ai\ml\_restclient\v2023_04_01_preview\operations\_datastores_operations.py", line 147, in build_get_request
    "workspaceName": _SERIALIZER.url("workspace_name", workspace_name, 'str', pattern=r'^[a-zA-Z0-9][a-zA-Z0-9_-]{2,32}$'),
  File "D:\python\azure-mltable\lib\site-packages\msrest\serialization.py", line 652, in url
    output = self.serialize_data(data, data_type, **kwargs)
  File "D:\python\azure-mltable\lib\site-packages\msrest\serialization.py", line 760, in serialize_data
    raise ValueError("No value for given attribute")
ValueError: No value for given attribute
```
I can verify that the datastore is present in Azure ML Studio. It seems that the workspace name is not passed to msrest client for making the request

**Comment by banibrata-de** [comment]
Looks like you are missing the workspace_name parameter to your ml_client?

**Comment by paudan** [comment]
OK, setting workspace_name seems to have done the job. Would it be possible to update the [aforementioned example](https://learn.microsoft.com/en-us/azure/machine-learning/migrate-to-v2-resource-datastore?view=azureml-api-2) example for SDK v2 in reference docs which seem to be missing this parameter? Also, other examples also do not specify that MLClient should be created with this param which is a bit confusing for the developers

Otherwise, consider this issue closed
