### ISSUE TITLE
Ability to publish/deploy piplines without submitting  -  AzureML Python SDKV2

### ISSUE THREAD

**Issue by obiii** [Azure/azure-sdk-for-python#34745]
Hi,

With SDKv1, we used to submit the pipeline and then in CI we could just publish the pipeline to test or prod. Now, we migrate to SDKv2, and with PipelineComponentBatchDeployment there doesn't seems to be a way to deploy without submitting the job. The pipelines we have are massive, takes lot of time to complete.

We are using command component as can be seen below in **`custom_ppl`** function. The function **`PipelineComponentBatchDeployment`** accepts either job_definition (which works if I have submitted the pipeline first) or component (if the component is loaded, but we don't register components and therefore cant use this)

Here is the code we are using:

```
@pipeline()
def custom_ppl(arg1, arg2):
	logging.info("Getting registry client.")
	ml_client_registry = someFunction1()´

    pipeline_job_env = someFunctToGetEnv3()

	# Creating command component
	preprocess_component = command(
		name="Prerocessing",
		display_name="Preprocessing",
		description="Performs ts preprocessing.",
		inputs={
			"someInputs": Input(type="string"),
			"someInputs2": Input(type="string")
		},
		code=e.sources_directory,
		command="python -m preprocess.preprocessor_ts",
		environment=pipeline_job_env,
	).component(
		someInputs=arg1,
		someInputs2=arg2
	)
	return


def main(args):
	logging.info("Getting workspace client.")
	ml_client_workspace = someFunction2()
	someFunctToSetupCOmpute()
	
	pipeline_job = custom_ppl(
		arg1 = args.userInput1,
		arg2 = args.userInput2
	)
	pipeline_job.settings.default_datastore = e.default_datastore
	pipeline_job.settings.default_compute = e.compute_name_train_ts
	pipeline_job.settings.force_rerun = args.rerun
	
	if args.submit:
        logging.info(f"Submitting pipeline: {pipeline_job}")
        try:
            pipeline_run_job = ml_client.jobs.create_or_update(
                pipeline_job, experiment_name=e.experiment_name_preprocess_ts
            )
            ml_client.jobs.stream(name=pipeline_run_job.name)
        except Exception as excp:
            logging.error("Unable to complete the pipeline")
            raise excp
			
	if args.deploy:
		endpoint = create_endpoint(
			ml_client, e.endpoint_name_preprocess, "Preprocessing end point."
		)
		
		logging.info("Creating deployment profile.")
		deployment = PipelineComponentBatchDeployment(
			name=e.deployment_name_preprocess,
			description="bb preprocessing pipeline."
			"This deployment is created from a pipeline job.",
			endpoint_name=endpoint.name,
			job_definition=pipeline_run_job,  # type: ignore
			settings={
				"default_compute": e.compute_name_train_ts,  # type: ignore
				"default_datastore": e.default_datastore,
				"continue_on_step_failure": False,
			},
		)
		
		ml_client.batch_deployments.begin_create_or_update(deployment).result()
		logging.info(f"Deployment succeeded: {deployment}")

		logging.info("Updating default endpoint deployment.")
		endpoint = ml_client.batch_endpoints.get(endpoint.name)
		endpoint.defaults.deployment_name = deployment.name
		ml_client.batch_endpoints.begin_create_or_update(endpoint).result()
		
		#How do we deploy without submit the pipeline first.
		
		
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
	parser.add_argument(
        "--userInput1""
    )
	parser.add_argument(
        "--userInput2"
    )
	parser.add_argument(
        "--submit", action="store_true", help="use to submit the pipeline experiment."
    )
	parser.add_argument(
        "--deploy", action="store_true", help="use to submit the pipeline experiment."
    )
	args = parser.parse_args()
    main(args)
	

```

Question is: in **`if args.deploy`**, how do we deploy the pipeline without submitting it first, as our pipelines are massive and take lot of time to complete. We now have to submit it everytime when deploying to dev, deploying to test and deploying to prod. Previously, with sdkv1, we used to submit once and then publish to dev test and prod without resubmitting.

Related post on Micrisoft: https://learn.microsoft.com/en-us/answers/questions/1159059/publishing-pipeline-endpoints-with-sdk-v2

**Comment by annatisch** [comment]
Thanks for the report @obiii!
I have looped in the ML team to take a closer look at your scenario.

**Comment by edgBR** [comment]
Hi,

I am actually having the same problem.

Is there are way to find a work around?

BR
E

**Comment by banibrata-de** [comment]
@santiagxf  would you be able to help here!

**Comment by santiagxf** [comment]
Hi @edgBR and @obiii. You don't need to run the job to be able to deploy it. This is completely supported. Instead of indicating `job_definition` indicate the parameter `component`. [This example](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-use-batch-pipeline-deployments?view=azureml-api-2&tabs=python) shows how to do it.

**Comment by obiii** [comment]
Hi @santiagxf 

Thanks for clarification. Yes, we managed to deploy the job without submitting. There was a slight confusion with command argument in `commad()`. Seems it needed all inputs mentioned in the command like 

`command = "python -m train --argumentA ${{inputs.argumentA}}" `

Without mentioning the input, it complains that input must be provided. All sorted now. Thanks!

**Comment by obiii** [comment]
Hi,

There is slight confusion still. So this happened when we try to deploy to test environment. We use 
`python -m ml_service.pipelines_v2.pipeline_ts_preprocess_v2 --deploy` in a CD pipeline.

This is the code we have for **pipeline_ts_preprocess_v2**:

```
import argparse

from azure.ai.ml import Input, command
from azure.ai.ml.dsl import pipeline
from azure.ai.ml.entities import PipelineComponentBatchDeployment

from ml_service.utils.attach_compute import get_compute
from ml_service.utils.env_variables import Env
from ml_service.utils.logger import Logger
from ml_service.utils.ml_utils import (
    create_endpoint,
    get_chained_credentials,
    get_client_workspace,
    get_environment,
)

e = Env()
logging = Logger().getLogger(__name__)

#  getting latest environment
credentials = get_chained_credentials(e.cluster_identity_id)
preprocess_env = get_environment(
    credentials,
    e.registry_name,
    e.registry_region,
    e.aml_env_name_train_ts,
    e.target_env_tag,
)

#  creating command component
preprocess_component = command(
    name="Prerocessing",
    display_name="Preprocessing",
    description="Performs ts preprocessing.",
    inputs={
        "arg1": Input(type="string"),
        "arg2": Input(type="string")
    },
    code=e.sources_directory,
    command="python -m preprocess.preprocessor_ts \
        --arg1 ${{inputs.arg1}} \
        --arg2  ${{inputs.arg2}},
    environment=preprocess_env,
)


#  creating pipeline from components
@pipeline()
def my_ppl(arg1, arg2):
	logging.info("Creating command component")
	preprocess_component(
		arg1=arg1,
		arg2=arg2
	)

def main(args):  # noqa: PLR0912 PLR0915
    """Responsible for creating pipeline and endpoint for deployment."""
   
	ml_client = get_client_workspace(
		get_chained_credentials(e.cluster_identity_id),
		e.subscription_id,
		e.resource_group,
		e.workspace_name,
   
	# Setting up the compute
	setup_compute()
	
    try:
        logging.info("Creating pipeline component.")
        pipeline_job = my_ppl(  # type: ignore
            arg1=args.arg1,
            arg2=args.arg2
        )
        pipeline_job.settings.default_datastore = e.default_datastore
        pipeline_job.settings.default_compute = e.compute_name_train_ts
        pipeline_job.settings.force_rerun = args.rerun
    except Exception as excp:
        logging.error("Unable to create pipeline.")
        raise excp

    if args.submit:
        logging.info(f"Submitting pipeline: {pipeline_job}")
        try:
            pipeline_run_job = ml_client.jobs.create_or_update(
                pipeline_job, experiment_name=e.experiment_name_preprocess_ts
            )
            ml_client.jobs.stream(name=pipeline_run_job.name)
        except Exception as excp:
            logging.error("Unable to complete the pipeline")
            raise excp

    if args.deploy:
        logging.info("Deploying the pipeline.")
        try:
            ## creating endpoint
            logging.info("Creating endpoint.")
            endpoint = create_endpoint(
                ml_client,
                e.endpoint_name_preprocess + "-" + e.env,
                "Preprocessing end point.",
            )

            logging.info("Creating deployment profile.")
            deployment_params = {
                "name": e.deployment_name_preprocess,
                "description": "Backbook preprocessing pipeline. This deployment is created from a pipeline job.",
                "endpoint_name": endpoint.name,
                "settings": {
                    "default_compute": e.compute_name_train_ts,
                    "default_datastore": e.default_datastore,
                    "continue_on_step_failure": False,
                },
            }
            if args.submit:
                logging.info("Creating deployment with pipeline job run.")
                job_type_params = {"job_definition": pipeline_run_job}  # type: ignore
            else:
                logging.info("Creating deployment with component")
                job_type_params = {
                    "component": my_ppl().component  # type: ignore
                }
            deployment_params = {**deployment_params, **job_type_params}
            deployment = PipelineComponentBatchDeployment(**deployment_params)
            ml_client.batch_deployments.begin_create_or_update(deployment).result()
            logging.info(f"Deployment succeeded: {deployment}")

            logging.info("Updating default endpoint deployment.")
            endpoint = ml_client.batch_endpoints.get(endpoint.name)
            endpoint.defaults.deployment_name = deployment.name
            ml_client.batch_endpoints.begin_create_or_update(endpoint).result()
        except Exception as excp:
            logging.error("Error in deployment")
            raise excp


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--arg1",
        type=str,
        default="data.parquet",
    )
    parser.add_argument(
        "--arg2",
        type=str,
        default="Y",
    )
    
    parser.add_argument(
        "--submit", action="store_true", help="use to submit the pipeline experiment."
    )
    parser.add_argument(
        "--rerun", action="store_true", help="Force rerunning the whole pipeline."
    )
    parser.add_argument(
        "--deploy", action="store_true", help="use to publish the pipeline."
    )
    args = parser.parse_args()

    main(args)

```
If the **--submit** is not provided, the deployment profile has a component argument: `component: my_ppl().component` Unlike when **--submit** is given, the deployment profile has **job_definition** argument which is set to **pipeline_run_job** created my **ml_client**.


This is the error trace we get:

> 
> 2024-03-20T15:40:12.8569865Z ERROR:__main__:Error in deployment
> 2024-03-20T15:40:12.8570094Z Traceback (most recent call last):
> 2024-03-20T15:40:12.8570607Z   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/azure/ai/ml/operations/_batch_deployment_operations.py", line 338, in _validate_component
> 2024-03-20T15:40:12.8573764Z     registered_component = self._all_operations.all_operations[AzureMLResourceType.COMPONENT].get(
> 2024-03-20T15:40:12.8574624Z   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/azure/ai/ml/_telemetry/activity.py", line 350, in wrapper
> 2024-03-20T15:40:12.8578479Z     return_value = f(*args, **kwargs)
> 2024-03-20T15:40:12.8623646Z   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/azure/ai/ml/operations/_component_operations.py", line 254, in get
> 2024-03-20T15:40:12.8623949Z     return self._get(name=name, version=version, label=label)
> 2024-03-20T15:40:12.8624347Z   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/azure/ai/ml/operations/_component_operations.py", line 350, in _get
> 2024-03-20T15:40:12.8624619Z     result = self._get_component_version(name, version)
> 2024-03-20T15:40:12.8625011Z   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/azure/ai/ml/_telemetry/activity.py", line 350, in wrapper
> 2024-03-20T15:40:12.8625257Z     return_value = f(*args, **kwargs)
> 2024-03-20T15:40:12.8626132Z   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/azure/ai/ml/operations/_component_operations.py", line 220, in _get_component_version
> 2024-03-20T15:40:12.8626411Z     else self._version_operation.get(
> 2024-03-20T15:40:12.8626786Z   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
> 2024-03-20T15:40:12.8627029Z     return func(*args, **kwargs)
> 2024-03-20T15:40:12.8627455Z   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/azure/ai/ml/_restclient/v2022_10_01/operations/_component_versions_operations.py", line 467, in get
> 2024-03-20T15:40:12.8627765Z     map_error(status_code=response.status_code, response=response, error_map=error_map)
> 2024-03-20T15:40:12.8628425Z   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/azure/core/exceptions.py", line 164, in map_error
> 2024-03-20T15:40:12.8628647Z     raise error
> 2024-03-20T15:40:12.8628868Z azure.core.exceptions.ResourceNotFoundError: (UserError) Not found component my_ppl.
> 2024-03-20T15:40:12.8629089Z Code: UserError
> 2024-03-20T15:40:12.8629272Z Message: Not found component my_ppl

Thanks!

**Comment by santiagxf** [comment]
Hi @obiii. sorry for the confusion. The error is indicating the component (pipeline component) doesn't exist. Batch Endpoints allows you to manage the lifecycle of the deployments and for that pipeline components are versioned as assets you can manage. Pipeline components are reusable, and you can streamline your MLOps practice by using [shared registries](https://learn.microsoft.com/en-us/azure/machine-learning/concept-machine-learning-registries-mlops?view=azureml-api-2) to move these components from one workspace to another.

You need to create the component before deploying it:

```python
pipeline_component = ml_client.components.create_or_update(
    my_ppl().component
)
```

Then on your arguments, you can change it as follows:

```python
job_type_params = {
    "component": pipeline_component  # type: ignore
}
```

Hope it helps.

**Comment by obiii** [comment]
> Hi @obiii. sorry for the confusion. The error is indicating the component (pipeline component) doesn't exist. Batch Endpoints allows you to manage the lifecycle of the deployments and for that pipeline components are versioned as assets you can manage. Pipeline components are reusable, and you can streamline your MLOps practice by using [shared registries](https://learn.microsoft.com/en-us/azure/machine-learning/concept-machine-learning-registries-mlops?view=azureml-api-2) to move these components from one workspace to another.
> 
> You need to create the component before deploying it:
> 
> ```python
> pipeline_component = ml_client.components.create_or_update(
>     my_ppl().component
> )
> ```
> 
> Then on your arguments, you can change it as follows:
> 
> ```python
> job_type_params = {
>     "component": pipeline_component  # type: ignore
> }
> ```
> 
> Here you have a [full notebook showing the scenario](https://github.com/Azure/azureml-examples/blob/main/sdk/python/endpoints/batch/deploy-pipelines/batch-scoring-with-preprocessing/sdk-deploy-and-test.ipynb).

Thanks @santiagxf , the confusion raised from the dev workspace where we don't have any components and we were wondering why does this work in dev. Found out that, we once registered the component during development phase and archived it (because there is no unregister or deleted option). So in dev, it was not complaining because it was picking the component from archived components (not very intuitive).

Thanks for the support :)

**Comment by obiii** [comment]
> Hi @obiii. sorry for the confusion. The error is indicating the component (pipeline component) doesn't exist. Batch Endpoints allows you to manage the lifecycle of the deployments and for that pipeline components are versioned as assets you can manage. Pipeline components are reusable, and you can streamline your MLOps practice by using [shared registries](https://learn.microsoft.com/en-us/azure/machine-learning/concept-machine-learning-registries-mlops?view=azureml-api-2) to move these components from one workspace to another.
> 
> You need to create the component before deploying it:
> 
> ```python
> pipeline_component = ml_client.components.create_or_update(
>     my_ppl().component
> )
> ```
> 
> Then on your arguments, you can change it as follows:
> 
> ```python
> job_type_params = {
>     "component": pipeline_component  # type: ignore
> }
> ```
> 
> Here you have a [full notebook showing the scenario](https://github.com/Azure/azureml-examples/blob/main/sdk/python/endpoints/batch/deploy-pipelines/batch-scoring-with-preprocessing/sdk-deploy-and-test.ipynb).

Hi @santiagxf,

We are now creating the component first in the shared registry and then deploying that component. The problem is:

While registering the component, it gives the error:

> Creating/updating registry component Processing with version 1 ..Done (0m 6s)
**Trace:**
![image](https://github.com/Azure/azure-sdk-for-python/assets/17766651/340b67e2-3bbf-4fe7-bb91-dd2b22518c33)



but even after failure we see the component in the registry, but the version is autogenerated and not 1.
![image](https://github.com/Azure/azure-sdk-for-python/assets/17766651/550305a2-582d-4ac9-a996-67cc90e0a79e)

**Comment by obiii** [comment]
### **More Details:**

When doing
```
pipeline_component  = ml_client_registry.components.create_or_update(
     my_ppl().component
)
```

It should create a pipeline component and should also create the underlying command component:
![image](https://github.com/Azure/azure-sdk-for-python/assets/17766651/f3f34692-16a5-469a-b7fd-4c500aa9aed8)

> Creating/updating registry component cmp_preprocessing_swe_backbook with version 2024-03-21-11-57-43-6185689 ..Done (0m 6s)

It does create the command component but the name is azureml_anonymous. Also the version is different than what stated above in vscode terminal. i.e 2024-03-21-11-57-43-6185689  vs 833da19b-fc93-a5cf-ebfb-cabb0c0bb5db.
![image](https://github.com/Azure/azure-sdk-for-python/assets/17766651/a576a2f1-e118-4a6a-a447-005cfc7978a0)

I believe then it proceeds to create pipeline component, and tries to find the command component, which it cant and raises error:  **Could not find asset with assetId azureml://registries/dna-ce-registry/components/cmp_preprocessing_swe_backbook/versions/2024-03-21-11-57-43-6185689**

However, it works okay, if I explicitly register the command component first:
`ml_client_registry.components.create_or_update(preprocess_component().component)`

and then register the pipeline component:
```
pipeline_component  = ml_client_registry.components.create_or_update(
     my_ppl().component
)
```

but then in the shared registry I see the command component registered twice. Once with proper name and once with azureml_anonymous.

Can you please shed some light here?

**Comment by obiii** [comment]
> Hi @obiii. sorry for the confusion. The error is indicating the component (pipeline component) doesn't exist. Batch Endpoints allows you to manage the lifecycle of the deployments and for that pipeline components are versioned as assets you can manage. Pipeline components are reusable, and you can streamline your MLOps practice by using [shared registries](https://learn.microsoft.com/en-us/azure/machine-learning/concept-machine-learning-registries-mlops?view=azureml-api-2) to move these components from one workspace to another.
> 
> You need to create the component before deploying it:
> 
> ```python
> pipeline_component = ml_client.components.create_or_update(
>     my_ppl().component
> )
> ```
> 
> Then on your arguments, you can change it as follows:
> 
> ```python
> job_type_params = {
>     "component": pipeline_component  # type: ignore
> }
> ```
> 
> Here you have a [full notebook showing the scenario](https://github.com/Azure/azureml-examples/blob/main/sdk/python/endpoints/batch/deploy-pipelines/batch-scoring-with-preprocessing/sdk-deploy-and-test.ipynb).

Hi @santiagxf,

```
preprocess_component = command(
    name="cmp_preprocessing_sweden_backbook",
    display_name="PreprocessingComponent",
    description="Performs ts preprocessing.",
    inputs={
        "arg1": Input(type="string")
    },
    code=e.sources_directory,
    command="python -m preprocess.preprocessor_ts --arg1${{inputs.arg1}},
    environment=preprocess_env,
    tags={'build': e.target_env_tag}
)

@pipeline()
def my_ppl(arg1: str):
    preprocess_component(arg1=arg1)

ml_client_registry = get_client_registry(
    credentials, e.registry_name, e.registry_region
)
ppl_component = ml_client_registry.components.create_or_update(
    my_ppl().component
)
```

This results in:

> Creating/updating registry component cmp_preprocessing_sweden_backbook with version 1 ..Done (0m 6s)
> azure.core.exceptions.ResourceNotFoundError: (UserError) Could not find asset with assetId azureml://registries/my-ml-registry/components/cmp_preprocessing_sweden_backbook/versions/1 in registry my-ml-registry in region westeurope.There is no pending update on this registry.
> Code: UserError
> Message: Could not find asset with assetId azureml://registries/my-ml-registry/components/cmp_preprocessing_sweden_backbook/versions/1 in registry my-ml-registry in region westeurope.There is no pending update on this registry.

And with this, I see a new command component registration in the shared ML registry but with name = azureml_anonymous and version number that was a different format i.e **4da46664-682e-1749-1930-22c41c527154**. SO, it seems like it registers the component but with different version and tries to look for a different one? I am not sure.

However, it works fine if I use workspace client instead. Can you please help? Thanks!

**Comment by obiii** [comment]
Hi,

is there any update on this please :) ?
Thanks

**Comment by santiagxf** [comment]
Hi @obiii. Thanks for reporting this issue with registries and components. I'm creating a new issue for this as it looks it's not related with the original problem. It's easier for us to plug the right people in. Give us some time to route it to the pipeline components team.

#34891

**Comment by achauhan-scc** [comment]
a different issue is created for registries marking this one addressed.

**Comment by obiii** [comment]
The SDKV2 does support the ability to deploy wihtout submitting the whole pipeline. 

deployment = PipelineComponentBatchDeployment(
			name=e.deployment_name_preprocess,
			description="bb preprocessing pipeline."
			endpoint_name=endpoint.name,
                       "This will create a component out of your pipeline definition"
			component=custom_ppl().component,
			settings={
				"default_compute": e.compute_name_train_ts,  # type: ignore
				"default_datastore": e.default_datastore,
				"continue_on_step_failure": False,
			},
		)

The issue in comments has been transferred to:
https://github.com/Azure/azure-sdk-for-python/issues/34891
https://github.com/Azure/azure-sdk-for-python/issues/34876

**Comment by santiagxf** [comment]
Closing this item as the original issue has been addressed. The comments are related with https://github.com/Azure/azure-sdk-for-python/issues/34891.
