### ISSUE TITLE
configure_azure_monitor cannot find a module azure.core.tracing.ext.opentelemetry_span

### ISSUE THREAD

**Issue by yooontheearth** [Azure/azure-sdk-for-python#34763]
- **Package Name**: azure-monitor-opentelemetry 
- **Package Version**: 1.3.0
- **Operating System**:Ubuntu 22.04.2 LTS
- **Python Version**: 3.11.3

**Describe the bug**
```
from azure.monitor.opentelemetry import configure_azure_monitor 
configure_azure_monitor(
   connection_string="<Connection string>"
)
```

Running this code on my machine gives me the following error.

```
Traceback (most recent call last):
  File "/app/application.py", line 1, in <module>
    from azure.monitor.opentelemetry import configure_azure_monitor 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/g6552/.local/lib/python3.11/site-packages/azure/monitor/opentelemetry/__init__.py", line 7, in <module>
    from azure.monitor.opentelemetry._configure import configure_azure_monitor
  File "/home/g6552/.local/lib/python3.11/site-packages/azure/monitor/opentelemetry/_configure.py", line 28, in <module>
    from azure.core.tracing.ext.opentelemetry_span import OpenTelemetrySpan
ModuleNotFoundError: No module named 'azure.core.tracing.ext.opentelemetry_span'
```

I also installed azure-core-tracing-opentelemetry@1.0.0b11 but I cannot find azure.core.tracing.ext.opentelemetry_span either.

**Comment by annatisch** [comment]
Thanks for the report @yooontheearth!
Could you please show us the output of `pip list` so we can confirm the environment?

**Comment by yooontheearth** [comment]
@annatisch 
Hello, here is the list!

 ```
pip list
Package                                Version
-------------------------------------- ----------
aiohttp                                3.9.3
aiosignal                              1.3.1
annotated-types                        0.6.0
anyio                                  4.3.0
asgiref                                3.7.2
attrs                                  23.2.0
azure-common                           1.1.28
azure-core                             1.30.1
azure-core-tracing-opentelemetry       1.0.0b11
azure-identity                         1.15.0
azure-monitor-opentelemetry            1.3.0
azure-monitor-opentelemetry-exporter   1.0.0b23
azure-search-documents                 11.4.0
azure-storage-blob                     12.19.0
backoff                                2.2.1
beautifulsoup4                         4.12.3
blinker                                1.7.0
certifi                                2024.2.2
cffi                                   1.16.0
chardet                                5.2.0
charset-normalizer                     3.3.2
click                                  8.1.7
cryptography                           42.0.5
dataclasses-json                       0.6.4
dataclasses-json-speakeasy             0.5.11
Deprecated                             1.2.14
distro                                 1.9.0
docx2txt                               0.8
emoji                                  2.10.1
filetype                               1.2.0
fixedint                               0.1.6
Flask                                  3.0.2
frozenlist                             1.4.1
greenlet                               3.0.3
gunicorn                               21.2.0
h11                                    0.14.0
httpcore                               1.0.4
httpx                                  0.27.0
idna                                   3.6
importlib-metadata                     6.11.0
isodate                                0.6.1
itsdangerous                           2.1.2
Jinja2                                 3.1.3
joblib                                 1.3.2
jsonpatch                              1.33
jsonpath-python                        1.0.6
jsonpointer                            2.4
jsonschema                             4.21.1
jsonschema-specifications              2023.12.1
langchain                              0.1.5
langchain-community                    0.0.20
langchain-core                         0.1.23
langdetect                             1.0.9
langsmith                              0.0.87
lxml                                   5.1.0
MarkupSafe                             2.1.5
marshmallow                            3.21.0
msal                                   1.27.0
msal-extensions                        1.1.0
msrest                                 0.7.1
multidict                              6.0.5
mypy-extensions                        1.0.0
nltk                                   3.8.1
numpy                                  1.26.4
oauthlib                               3.2.2
openai                                 1.11.1
opentelemetry-api                      1.23.0
opentelemetry-instrumentation          0.44b0
opentelemetry-instrumentation-asgi     0.44b0
opentelemetry-instrumentation-dbapi    0.44b0
opentelemetry-instrumentation-django   0.44b0
opentelemetry-instrumentation-fastapi  0.44b0
opentelemetry-instrumentation-flask    0.44b0
opentelemetry-instrumentation-psycopg2 0.44b0
opentelemetry-instrumentation-requests 0.44b0
opentelemetry-instrumentation-urllib   0.44b0
opentelemetry-instrumentation-urllib3  0.44b0
opentelemetry-instrumentation-wsgi     0.44b0
opentelemetry-resource-detector-azure  0.1.3
opentelemetry-sdk                      1.23.0
opentelemetry-semantic-conventions     0.44b0
opentelemetry-util-http                0.44b0
packaging                              23.2
pillow                                 10.2.0
pip                                    22.3.1
portalocker                            2.8.2
pycparser                              2.21
pydantic                               2.6.3
pydantic_core                          2.16.3
PyJWT                                  2.8.0
PyMuPDF                                1.23.21
PyMuPDFb                               1.23.9
python-dateutil                        2.9.0
python-dotenv                          1.0.1
python-iso639                          2024.2.7
python-magic                           0.4.27
python-pptx                            0.6.23
PyYAML                                 6.0.1
rapidfuzz                              3.6.1
referencing                            0.33.0
regex                                  2023.12.25
requests                               2.31.0
requests-oauthlib                      1.4.0
rpds-py                                0.18.0
setuptools                             65.5.1
six                                    1.16.0
sniffio                                1.3.1
soupsieve                              2.5
SQLAlchemy                             2.0.27
synclect-vector-embedding-generator    0.2.1
tabulate                               0.9.0
tenacity                               8.2.3
tiktoken                               0.5.2
tqdm                                   4.66.2
typing_extensions                      4.10.0
typing-inspect                         0.9.0
unstructured                           0.12.3
unstructured-client                    0.18.0
urllib3                                2.2.1
Werkzeug                               3.0.1
wheel                                  0.40.0
wrapt                                  1.16.0
XlsxWriter                             3.2.0
yarl                                   1.9.4
zipp                                   3.17.0
```

**Comment by jeremydvoss** [comment]
Looks like the Azure Core Tracing Extension library may have had a breaking change. I will look into this and talk to the maintainer.

**Comment by jeremydvoss** [comment]
I am not able to reproduce this with those versions of the azure monitor distro and azure core tracing. I have also confirm that the [opentelemetry_span](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span) remains in the same location. So, there was no breaking change. Therefore, this is likely an issue with your installed packages. I would check whether your python packages are spread across multiple site-packages folders and find where python is expecting to see the azure.core.tracing.ext.opentelemetry_span module.

**Comment by yooontheearth** [comment]
@jeremydvoss 
Thank you for your investigation. I will try to make a minimal environment with docker to check whether it is only in my environment or not.

**Comment by yooontheearth** [comment]
@jeremydvoss 
Although I made an environment with docker, other error started showing. 

```
python main.py
Failed to receive Azure VM metadata: timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/opentelemetry/resource/detector/azure/vm.py", line 74, in get_azure_vm_metadata
    with urlopen(request, timeout=4) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/local/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: timed out
```

It seems like it is because of our VNet on Azure refusing the request, am I right? Somehow **ModuleNotFoundError** has gone. Maybe my installed packages were somewhat not good as you guessed. Let me explain the environment I made. I use DevContainer on WSL, which is **Ubuntu 22.04.2 LTS**, on Windows 11. 

/.devcontainer/devcontainer.json
```
{
	"name": "python-ot",
	"build": { "dockerfile": "Dockerfile" },
	"workspaceFolder": "/app",
	"postStartCommand": "bash",
	"customizations": {
		"vscode": {
			"extensions": [
				"ms-python.python",
				"ms-azuretools.vscode-docker"
			]
		}
	},
	"mounts": [
		"source=/home/yoo/python-ot,target=/app,type=bind"
	]
}
```

/.devcontainer/Dockerfile
```
FROM python:3.11.3
WORKDIR /app

# We need to copy a certificate due to our VPN
COPY Cato_Networks.crt /usr/local/share/ca-certificates

# We need a proxy setting
ENV HTTP_PROXY=http://xxxxx
ENV HTTPS_PROXY=http://xxxxx

RUN apt-get update && apt-get install -y \
    ca-certificates \
    && update-ca-certificates

RUN pip install azure-monitor-opentelemetry==1.3.0
```

Then I run the following code, this gives me the error above.
```
from azure.monitor.opentelemetry import configure_azure_monitor 
configure_azure_monitor(
   connection_string="<Connection string>"
)
```

**Comment by yooontheearth** [comment]
@jeremydvoss 
I took a look at `/usr/local/lib/python3.11/site-packages/opentelemetry/resource/detector/azure/vm.py` which emits the error above, and found that it requests  to `_AZURE_VM_METADATA_ENDPOINT = "http://169.254.169.254/metadata/instance/compute?api-version=2021-12-13&format=json"`.

I accessed the address via Chrome, but I can't reach it.

Any ideas?

**Comment by yooontheearth** [comment]
I just realized that even after throwing the error above, the code is still running and logging works as expected. I'll close this issue.

**Comment by seanbcau** [comment]
I encountered the ModuleNotFoundError: No module named 'azure.core.tracing.ext.opentelemetry_span' issue also.

I found this was caused by installing some packages globally (e.g. azure-core) and others locally (azure-core-tracing-opentelemetry).

When you do this the local directories end up missing __init__.py files in some directories.

Installing everything globally solved the problem for me.

**Comment by green-sh** [comment]
I encountered this problem in Databricks. It occurred because when azure-core was already installed by default in an old version, installing azure-telemetry afterwards didn't throw an error, even when the versions were incompatible. The solution for me was to update **azure-core** using:

    pip install -U azure-core

**Comment by greatvovan** [comment]
Nice research @green-sh. This issue is still happening as of today inside Databricks clusters. In my case adding azure-core==1.31.0
 to cluster libraries fixed the issue. Alternatively, if notebook-scoped libraries work for you, install nothing in the cluster scope and use `%pip` to install the lib in the notebook scope. This will create a virtual environment that is independent from the cluster's library set.
