### ISSUE TITLE
Microsoft.RelInfra.Common.Exceptions.ErrorResponseException - Failed to submit job, when invoking batch endpoint from ADF

### ISSUE THREAD

**Issue by obiii** [Azure/azure-sdk-for-python#34783]
- **Package Name**: Azureml
- **Package Version**: SDKv2
- **Python Version**: 3.11

**Describe the bug**
AML pipelines published to batch endpoints. The pipelines brings/loads/gets the environment from shared registry. Works fine when run from code, when triggered manually from AML UI. Gives "**Microsoft.RelInfra.Common.Exceptions.ErrorResponseException: User/tenant/subscription is not allowed to access registry some-shared-ml-registry.**" error when triggered from ADF using webactivity to trigger batch endpoint.

Complete trace:

> [2024-03-15 08:21:49Z] ReuseHash: <someLongHashHere>/G4bmTp/+6aQ=, JobDefinitionToHash: {"Configuration":{"Command":"python -m preprocess.preprocessor_ts","UseAbsolutePath":false,"Framework":"Python","Communicator":"None","Target":"My256RAM-gral","NodeCount":1,"CredentialPassthrough":false,"Environment":{"Name":"azureml://registries/some-shared-ml-registry/environments/myProj-train-ts-cpu/versions/1","Version":"1"},"History":{"OutputCollection":true,"DirectoriesToWatch":["logs"],"EnableMLflowTracking":false},"Spark":{},"ParallelTask":{"MaxRetriesPerWorker":0,"WorkerCountPerNode":1},"BatchAi":{"NodeCount":0},"AmlCompute":{"RetainCluster":false,"ClusterMaxNodeCount":1},"AISuperComputer":{"InstanceType":"D2","ImageVersion":"pytorch-1.7.0","Interactive":false,"EnableAzmlInt":true,"SLATier":"Standard"},"KubernetesCompute":{},"Tensorflow":{"WorkerCount":0,"ParameterServerCount":0},"Mpi":{"ProcessCountPerNode":1},"PyTorch":{},"Hdi":{"YarnDeployMode":"None"},"ContainerInstance":{"CpuCores":2.0,"MemoryGb":3.5},"Docker":{"UseDocker":true,"SharedVolumes":true,"ShmSize":"2g"},"Cmk8sCompute":{},"GlobalJobDispatcher":{"MyResourceOnly":false,"LowPriorityVMTolerant":true},"CommandReturnCodeConfig":{"ReturnCode":"Zero"},"EnvironmentVariables":{"AZUREML_PARAMETER_Node_Count":"1","someVariables":"tahtIwontShare"},"DataBricks":{"Workers":0,"MinimumWorkerCount":0,"MaxMumWorkerCount":0,"SparkVersion":"4.0.x-scala2.11","NodeTypeId":"Standard_D3_v2","TimeoutSeconds":0}},"SnapshotId":"someId"}
> [2024-03-15 08:21:49Z] Starting run in Execution Service
> [2024-03-15 08:21:49Z] Failed to start the job for runid: long_run_id_here because of exception_type: ServiceInvocationException, error: Failure in StartSnapshotRun while calling service Execution; HttpMethod: POST; Response StatusCode: Forbidden; Exception type: Microsoft.RelInfra.Extensions.HttpRequestDetailException|-Microsoft.RelInfra.Common.Exceptions.ErrorResponseException, stack trace:    at Microsoft.Aether.EsCloud.Common.Client.ExecutionServiceClient.StartSnapshotRunAsync(String jobId, RunDefinition runDefinition, String runId, WorkspaceIdentity workspaceIdentity, String experimentName, CreatedBy createdBy) in D:\a\_work\1\s\src\aether\platform\backendV2\Clouds\ESCloud\ESCloudCommon\Client\ExecutionServiceClient.cs:line 162
>    at Microsoft.Aether.EsCloud.Common.JobProcessor.StartRunAsync(EsCloudJobMetadata job) in D:\a\_work\1\s\src\aether\platform\backendV2\Clouds\ESCloud\ESCloudCommon\JobProcessor.cs:line 714
> [2024-03-15 08:21:49Z] The latency of ESCloud submitting an ES job returning 'Failed' status : 2499.8607ms

**To Reproduce**
1. Create a simple pipeline that gets environment from a shared registry: Sample code here: https://github.com/Azure/azure-sdk-for-python/issues/34745
2. Deploy the endpoint with default deployment using PipelineComponentBatchDeployment
![image](https://github.com/Azure/azure-sdk-for-python/assets/17766651/94f69f81-a997-4f62-bb2b-49726005e7ee)

4. Trigger the batch endpoint using ADF web activity: follow this link: https://learn.microsoft.com/en-us/azure/machine-learning/how-to-use-batch-azure-data-factory?view=azureml-api-2&tabs=mi

**Expected behavior**
When triggered from adf, the batch endpoint triggers and shouldn't complain about 'Microsoft.RelInfra.Common.Exceptions.ErrorResponseException: User/tenant/subscription is not allowed to access registry dna-centralized-ml-registry.'

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-python/assets/17766651/738455bc-08c1-4f4a-99fb-c02a5053b0fe)

**Additional context**

**Comment by obiii** [comment]
It appears ADF needed a custom role of ML Registry Asset Manager (containing registries/read, registries/assets/read,write, delete).
