### ISSUE TITLE
Unclosed client session when using Azure Eventhub with BlobCheckpointStore

### ISSUE THREAD

**Issue by rameshvenk** [Azure/azure-sdk-for-python#35144]
- **Package Name and versions**: 
```
azure-common                           1.1.28
azure-core                             1.30.1
azure-eventhub                         5.11.6
azure-eventhub-checkpointstoreblob-aio 1.1.4
azure-identity                         1.15.0
azure-storage-blob                     12.19.1
azure-storage-queue                    12.9.0
```
- **Operating System**:
Ubuntu 22.04.4 LTS under WSL2
- **Python Version**: 
Python 3.11.0rc1

**Describe the bug**
Sending a `KeyboardInterrupt` produces this stacktrace 
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/runners.py", line 120, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/XXXXX/az-eventhub-consumer-ckpt.py", line 59, in main
    await asyncio.gather(event_hub_listener())
  File "/home/XXXXX/az-eventhub-consumer-ckpt.py", line 52, in event_hub_listener
    await client.receive(on_event=on_event, starting_position="-1", prefetch=1)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXXXX/opt/pydev/venv/lib/python3.11/site-packages/azure/eventhub/aio/_consumer_client_async.py", line 541, in receive
    await self._receive(
  File "/home/XXXXX/opt/pydev/venv/lib/python3.11/site-packages/azure/eventhub/aio/_consumer_client_async.py", line 435, in _receive
    await event_processor.start()
  File "/home/XXXXX/opt/pydev/venv/lib/python3.11/site-packages/azure/eventhub/aio/_eventprocessor/event_processor.py", line 416, in start
    await asyncio.sleep(load_balancing_interval, **self._internal_kwargs)
  File "/usr/lib/python3.11/asyncio/tasks.py", line 644, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/XXXXX/az-eventhub-consumer-ckpt.py", line 63, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 188, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 125, in run
    raise KeyboardInterrupt()
KeyboardInterrupt
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fc94624fc10>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fc945062190>, 14075.935085746), (<aiohttp.client_proto.ResponseHandler object at 0x7fc945062430>, 14075.93792451), (<aiohttp.client_proto.ResponseHandler object at 0x7fc945061a20>, 14075.943236621)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fc94624ff10>

```
**To Reproduce**
Sample code:

```python
import asyncio
import os

from azure.eventhub import EventData
from azure.eventhub.aio import EventHubConsumerClient, PartitionContext
from azure.eventhub.extensions.checkpointstoreblobaio import (
    BlobCheckpointStore,
)  # type: ignore
from azure.identity.aio import EnvironmentCredential
from dotenv import load_dotenv

load_dotenv(".env")
namespace = os.environ["EVENT_HUB_NAMESPACE"]
event_hub = os.environ["EVENT_HUB"]
consumer_group = os.environ["EVENT_HUB_CONSUMER_GROUP"]
blob_account_url = os.environ["EVENT_HUB_STORAGE_ACCOUNT_URL"]
container_name = os.environ["EVENT_HUB_BLOB_CONTAINER"]


async def on_event(partition_context: PartitionContext, event: EventData):
    print(
        "Received event: [{}] from partition with ID: {}".format(
            event.body_as_str(encoding="UTF-8"), partition_context.partition_id
        )
    )
    await partition_context.update_checkpoint(event)


async def event_hub_listener():
    async with EnvironmentCredential() as token_credential:
        checkpoint_store = BlobCheckpointStore(
            blob_account_url=blob_account_url,
            container_name=container_name,
            credential=token_credential,
        )
        async with EventHubConsumerClient(
            fully_qualified_namespace=namespace,
            eventhub_name=event_hub,
            credential=token_credential,
            consumer_group=consumer_group,
            checkpoint_store=checkpoint_store,
        ) as client:
            print(await client.get_eventhub_properties())
            try:
                await client.receive(on_event=on_event, starting_position="-1", prefetch=1)  # type: ignore
            except Exception as e:
                print(f"EXCEPTION: {e}")


async def main():
    await asyncio.gather(event_hub_listener())


if __name__ == "__main__":
    asyncio.run(main())

```

**Expected behavior**
Most if not all the code is running under a context manager, and the connections should close without having this stacktrace produced. I tried putting the `BlobCheckpointStore` under a context manager and got different errors, and I can produce that here as needed.

**Comment by l0lawrence** [comment]
Hi @rameshvenk, could you please share the other errors you are seeing when using BlobCheckpointStore under a context manager?

**Comment by rameshvenk** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/runners.py", line 120, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/XXXXXX/az-eventhub-consumer-ckpt.py", line 59, in main
    await asyncio.gather(event_hub_listener())
  File "/home/XXXXXX/az-eventhub-consumer-ckpt.py", line 52, in event_hub_listener
    await client.receive(on_event=on_event, starting_position="-1", prefetch=1)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXXXXX/opt/pydev/venv/lib/python3.11/site-packages/azure/eventhub/aio/_consumer_client_async.py", line 541, in receive
    await self._receive(
  File "/home/XXXXXX/opt/pydev/venv/lib/python3.11/site-packages/azure/eventhub/aio/_consumer_client_async.py", line 435, in _receive
    await event_processor.start()
  File "/home/XXXXXX/opt/pydev/venv/lib/python3.11/site-packages/azure/eventhub/aio/_eventprocessor/event_processor.py", line 416, in start
    await asyncio.sleep(load_balancing_interval, **self._internal_kwargs)
  File "/usr/lib/python3.11/asyncio/tasks.py", line 644, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/XXXXXX/az-eventhub-consumer-ckpt.py", line 63, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 188, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 125, in run
    raise KeyboardInterrupt()
KeyboardInterrupt
```

Sample code to repro
```
# https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-python-get-started-send?tabs=passwordless%2Croles-azure-portal

import asyncio
import os

from azure.eventhub import EventData
from azure.eventhub.aio import EventHubConsumerClient, PartitionContext
from azure.eventhub.extensions.checkpointstoreblobaio import (
    BlobCheckpointStore,
)  # type: ignore
from azure.identity.aio import EnvironmentCredential
from dotenv import load_dotenv

load_dotenv(".ehub-env")
namespace = os.environ["EVENT_HUB_NAMESPACE"]
event_hub = os.environ["EVENT_HUB"]
consumer_group = os.environ["EVENT_HUB_CONSUMER_GROUP"]
blob_account_url = os.environ["EVENT_HUB_STORAGE_ACCOUNT_URL"]
container_name = os.environ["EVENT_HUB_BLOB_CONTAINER"]


async def on_event(partition_context: PartitionContext, event: EventData):
    print(
        "Received event: [{}] from partition with ID: {}".format(
            event.body_as_str(encoding="UTF-8"), partition_context.partition_id
        )
    )
    await partition_context.update_checkpoint(event)


async def event_hub_listener():
    async with EnvironmentCredential() as token_credential:
        async with BlobCheckpointStore(
            blob_account_url=blob_account_url,
            container_name=container_name,
            credential=token_credential,
        ) as checkpoint_store:
            async with EventHubConsumerClient(
                fully_qualified_namespace=namespace,
                eventhub_name=event_hub,
                credential=token_credential,
                consumer_group=consumer_group,
                checkpoint_store=checkpoint_store,
            ) as client:
                try:
                    await client.receive(on_event=on_event, starting_position="-1", prefetch=1)  # type: ignore
                except Exception as e:
                    # Do something here if needed
                    print(f"EXCEPTION: {e}")


async def main():
    await asyncio.gather(event_hub_listener())


if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by rameshvenk** [comment]
A follow up: 
Catching `asyncio.exceptions.CancelledError` in `main()` seems to help. It definitely looks like we need to run the `BlobCheckpointStore` under a context manager and handle the error when the coroutine is cancelled. 
```
async def main():
    try:
        await asyncio.gather(event_hub_listener())
    except asyncio.exceptions.CancelledError as e:
        print(e)
```
