### ISSUE TITLE
Refactor appears to have broken retries for azure-core pipelines - take two

### ISSUE THREAD

**Issue by marseel** [Azure/azure-sdk-for-python#35314]
- **Package Name**:  azure-core
- **Package Version**:  Not sure - we use azure/login github action that uses 2.49.0 azure-cli 
- **Operating System**: Linux
- **Python Version**:  3.11

**Describe the bug**
```
ERROR: Invalid HTTP date
Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/policies/_utils.py", line 57, in parse_retry_after
    delay = int(retry_after)
            ^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '81,120'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 701, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 334, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/command_modules/acs/custom.py", line 666, in aks_create
    return aks_create_decorator.create_mc(mc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/command_modules/acs/managed_cluster_decorator.py", line 6818, in create_mc
    cluster = self.put_mc(mc)
              ^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/command_modules/acs/managed_cluster_decorator.py", line 6796, in put_mc
    cluster = sdk_no_wait(
              ^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/util.py", line 710, in sdk_no_wait
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/mgmt/containerservice/v2024_01_01/operations/_managed_clusters_operations.py", line 2038, in begin_create_or_update
    raw_result = self._create_or_update_initial(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/mgmt/containerservice/v2024_01_01/operations/_managed_clusters_operations.py", line 1892, in _create_or_update_initial
    pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/_base.py", line 213, in run
    return first_node.send(pipeline_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "/opt/az/lib/python3.11/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/policies/_redirect.py", line 181, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/policies/_retry.py", line 471, in send
    self.sleep(retry_settings, request.context.transport, response=response)
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/policies/_retry.py", line 440, in sleep
    slept = self._sleep_for_retry(response, transport)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/policies/_retry.py", line 407, in _sleep_for_retry
    retry_after = self.get_retry_after(response)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/policies/_retry.py", line 141, in get_retry_after
    return _utils.get_retry_after(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/policies/_utils.py", line 76, in get_retry_after
    return parse_retry_after(retry_after)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/policies/_utils.py", line [60](https://github.com/cilium/cilium/actions/runs/8795635664/job/24137055064#step:12:61), in parse_retry_after
    retry_date = _parse_http_date(retry_after)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/policies/_utils.py", line 43, in _parse_http_date
    raise ValueError("Invalid HTTP date")
ValueError: Invalid HTTP date
```

**To Reproduce**

We are constantly hitting this issue in our CI pipeline. 
Apparently, API returns retry-after in the format of `81,120` sometimes.

**Expected behavior**
Either gracefully skip retry-after or handle floats with commas.
The root cause seems to be exactly the same refactor as in https://github.com/Azure/azure-sdk-for-python/issues/34203
Before, `email.utils.parsedate` was used that does not throw an exception, but returns None in case it can't be parsed. 
Now what happens:
- int throws exception for retry-after `81,120` - but after recent change to float, it will still throw error as it contains comma
- _parse_http_date throws another exception that is not handled

**Screenshots**
Example CI run if you want to take a look:
https://github.com/cilium/cilium/actions/runs/8795635664/job/24137055064

**Additional context**
I think it would make sense to handle retry-after with comma, but also handle exceptions from `_parse_http_date` just in case.

**Comment by marseel** [comment]
@xiangyan99 pinging just for visibility if you would be interested in fixing a similar issue, also related to refactoring of retry-after mentioned in the original issue: https://github.com/Azure/azure-sdk-for-python/issues/34203

Seems like the change to float makes sense, but API sometimes returns float with a comma :shrug:

**Comment by kashifkhan** [comment]
Hi @marseel, 

Thank you for posting your issue about retry headers coming from the Azure Mgmt Container Service. Digging in a bit, this is a bug with the service that needs to be addressed as the value coming back seems to be localized, which shouldn't be the case. As per the [HTTP spec](https://datatracker.ietf.org/doc/html/rfc7231#section-7.1.3) the retry after value should only be digits or a datetime. 

With that format, today none of the other languages would handle this and would raise a similar error and this should not be fixed in Azure Core. As such the solution for this is to be fixed on the service side and not client side. 

I have the following asks that will help you to move forward

* Please create an IcM / Support Ticket with the Azure Management Container Service team, providing them with the info in this issue so they can resolve this on their end using this [link](https://azure.microsoft.com/en-us/support/create-ticket)
* In the meantime, an issue needs to be opened with [Azure CLI](https://github.com/Azure/azure-cli) so they can patch things on their end. Here is the sample code they would need to accomplish this. This code is only a temporary workaround for this service and should be used only for this service and should be removed from the client as soon as its fixed on the service. . There is an assumption here that there will only be one comma and its used as a decimal point. 

```python

from azure.mgmt.containerservice import ContainerServiceClient
from azure.core.pipeline.policies import RetryPolicy


class CustomRetryPolicy(RetryPolicy):
    def parse_retry_after(self, retry_after: str) -> float:
        """Helper to parse Retry-After and get value in seconds.

        :param str retry_after: Retry-After header
        :rtype: float
        :return: Value of Retry-After in seconds.
        """
        if ',' in retry_after:
            retry_after = retry_after.replace(',', '.', 1)
        return super().parse_retry_after(retry_after)
    

def main():
    # Create a ContainerServiceClient
    custom_retry_policy = CustomRetryPolicy()
    client = ContainerServiceClient(credential, subscription_id, policies=[custom_retry_policy])
```

**Comment by marseel** [comment]
Thanks.
