### ISSUE TITLE
When register custom models with python sdk in the pipeline, '#' in the path caused error: "Signature did not match"

### ISSUE THREAD

**Issue by jianawu** [Azure/azure-sdk-for-python#35513]
- **Package Name** azureml.core.model
- **Package Version**: 1.55.0.post2
- **Operating System**: Linux
- **Python Version**: 3.9

**Describe the bug**
When I try to register custom model with code like:
```
ws = Run.get_context().experiment.workspace
model = Model.register(workspace=ws, model_path=model_output_path, model_name=MODEL_COLLECTION_NAME)
```
there are several pkl files under dir: model_output_path

I found that when the file name contains '#', I will get error like:
![image](https://github.com/Azure/azure-sdk-for-python/assets/82713607/db0f76e1-4bb0-43ca-bf99-b5404730fd5e)

After replacing all the '#' with '-', issue resolved.
1. the error message is confused
2. I know '#' is strange, but '#' not allowed?

**Comment by swathipil** [comment]
Hi @jianawu - Thanks for opening an issue! We'll take a look asap!

**Comment by isaudagar** [comment]
Hi @jianawu , Thanks for opening an issue. 
Could you please provide proper code to replicate same issue and more details information,

**Comment by jianawu** [comment]
The issue can be easily recurrent by the information I provided above.

Here are some additional code pated:
```
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
import os
import argparse
import datetime
from pathlib import Path

from azure.identity import DefaultAzureCredential
from azure.ai.ml import MLClient

from azure.ai.ml.dsl import pipeline
from azure.ai.ml import Input, Output, command
from azure.ai.ml.entities import JobSchedule, CronTrigger
from azure.ai.ml.constants import TimeZone

SUBSCRIPTION=""
RESOURCE_GROUP=""
WS_NAME=""

credential = DefaultAzureCredential()
# Get a handle to the workspace
ml_client = MLClient(
    credential=credential,
    subscription_id=SUBSCRIPTION,
    resource_group_name=RESOURCE_GROUP,
    workspace_name=WS_NAME,
)

register_model = command(
    name="register_model",
    display_name="register-model",
    command="python register.py",
    code='test/pipeline',
    environment="peakload-train-env@latest"
)

# 2. Construct pipeline
@pipeline(
    description="Sample Training Pipeline",
)
def taxi_training_pipeline(raw_data, table_name):
    register = register_model()


pipeline_job = taxi_training_pipeline()

pipeline_job.settings.default_compute = "serverless"

pipeline_job = ml_client.jobs.create_or_update(
    pipeline_job, experiment_name='debug-environment'
)

```



register.py:
```
from azureml.core import Run
from azureml.core.model import Model
from pathlib import Path

model_output_path = Path('models')
Path.mkdir(model_output_path, exist_ok=True, parents=True)
f = open("./models/testmo#del.pkl", "w+")
f.write("test!")
f.close()
ws = Run.get_context().experiment.workspace
model = Model.register(workspace=ws, model_path='./models', model_name='test-model')
```

Here is the error:
```
Traceback (most recent call last):
  File "register.py", line 11, in <module>
    model = Model.register(workspace=ws, model_path='./models', model_name='test-model')
  File "/opt/miniconda/envs/amlenv/lib/python3.8/site-packages/azureml/core/model.py", line 582, in register
    asset = Model._create_asset(workspace.service_context, model_path, model_name, child_paths)
  File "/opt/miniconda/envs/amlenv/lib/python3.8/site-packages/azureml/core/model.py", line 625, in _create_asset
    artifacts_path = Model._create_artifacts(workspace_service_context, model_path, model_name, child_paths)
  File "/opt/miniconda/envs/amlenv/lib/python3.8/site-packages/azureml/core/model.py", line 615, in _create_artifacts
    artifact_client.upload_files(file_names, origin, container, names=artifact_names,
  File "/opt/miniconda/envs/amlenv/lib/python3.8/site-packages/azureml/_restclient/artifacts_client.py", line 172, in upload_files
    results.append(task)
  File "/opt/miniconda/envs/amlenv/lib/python3.8/site-packages/azureml/_common/async_utils/task_queue.py", line 55, in __exit__
    self.flush(self.identity)
  File "/opt/miniconda/envs/amlenv/lib/python3.8/site-packages/azureml/_common/async_utils/task_queue.py", line 118, in flush
    self._results.extend((task.wait(awaiter_name=self.identity) for task in completed_tasks))
  File "/opt/miniconda/envs/amlenv/lib/python3.8/site-packages/azureml/_common/async_utils/task_queue.py", line 118, in <genexpr>
    self._results.extend((task.wait(awaiter_name=self.identity) for task in completed_tasks))
  File "/opt/miniconda/envs/amlenv/lib/python3.8/site-packages/azureml/_common/async_utils/async_task.py", line 58, in wait
    res = self._handler(self._future, self._logger)
  File "/opt/miniconda/envs/amlenv/lib/python3.8/site-packages/azureml/_common/async_utils/async_task.py", line 16, in basic_handler
    return future.result()
  File "/opt/miniconda/envs/amlenv/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/opt/miniconda/envs/amlenv/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/opt/miniconda/envs/amlenv/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/miniconda/envs/amlenv/lib/python3.8/site-packages/azureml/_restclient/artifacts_client.py", line 165, in perform_upload
    return self.upload_stream_to_existing_artifact(stream, artifact, artifact_content_info,
  File "/opt/miniconda/envs/amlenv/lib/python3.8/site-packages/azureml/_restclient/artifacts_client.py", line 87, in upload_stream_to_existing_artifact
    res = upload_blob_from_stream(stream, artifact_uri, content_type=content_type, session=session,
  File "/opt/miniconda/envs/amlenv/lib/python3.8/site-packages/azureml/_file_utils/upload.py", line 62, in upload_blob_from_stream
    execute_func_with_reset(
  File "/opt/miniconda/envs/amlenv/lib/python3.8/site-packages/azureml/_restclient/clientbase.py", line 93, in execute_func_with_reset
    return ClientBase._execute_func_internal(backoff, retries, module_logger, func, reset_func, *args, **kwargs)
  File "/opt/miniconda/envs/amlenv/lib/python3.8/site-packages/azureml/_restclient/clientbase.py", line 368, in _execute_func_internal
    left_retry = cls._handle_retry(back_off, left_retry, total_retry, error, logger, func)
  File "/opt/miniconda/envs/amlenv/lib/python3.8/site-packages/azureml/_restclient/clientbase.py", line 434, in _handle_retry
    raise error
  File "/opt/miniconda/envs/amlenv/lib/python3.8/site-packages/azureml/_restclient/clientbase.py", line 359, in _execute_func_internal
    response = func(*args, **kwargs)
  File "/opt/miniconda/envs/amlenv/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/miniconda/envs/amlenv/lib/python3.8/site-packages/azureml/_vendor/azure_storage/blob/_blob_client.py", line 731, in upload_blob
    return upload_block_blob(**options)
  File "/opt/miniconda/envs/amlenv/lib/python3.8/site-packages/azureml/_vendor/azure_storage/blob/_upload_helpers.py", line 197, in upload_block_blob
    process_storage_error(error)
  File "/opt/miniconda/envs/amlenv/lib/python3.8/site-packages/azureml/_vendor/azure_storage/blob/_shared/response_handlers.py", line 181, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
azure.core.exceptions.ClientAuthenticationError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:c8eabecc-501e-0054-3139-bd87c8000000
Time:2024-06-13T02:28:30.5399692Z
ErrorCode:AuthenticationFailed
authenticationerrordetail:Signature did not match. String to sign used was rcw
2024-06-13T02:18:30Z
2024-06-14T02:28:30Z
/blob/stwcxmasmlopsinfradev/azureml/LocalUpload/240613T022830-51e6f943/models/testmo%23del.pkl
d6a81ad9-5254-42d8-a1b3-d5e79d61f200
72f988bf-86f1-41af-91ab-2d7cd011db47
2024-06-13T02:18:30Z
2024-06-14T10:28:30Z
b
2019-07-07


2019-07-07
b

```


after deleting the '#' in register.py, everything goes well.

**Comment by isaudagar** [comment]
@jianawu, Thanks for notify this issue. But in current code design there no validation to verify name and this is runtime error. it is not formatted error from custom error list.
