### ISSUE TITLE
z:mssparkutils.credentials.getToken on Azure China (Mooncake) cloud

### ISSUE THREAD

**Issue by abhbhatt** [Azure/azure-sdk-for-python#35709]
- **Package Name**: Microsoft Spark Utilities (MSSparkUtils)
- **Package Version**: 
- **Operating System**: 
- **Python Version**: Azure Synapse Spark Pool (PySpark 3.3 / Python 3.10)

**Describe the bug**
We are using mssparkutils with linked service to authenticate into Azure SQL using System Assigned Managed Identity (Synapse Workspace) on Azure China (Mooncake) cloud. However, when we call gettoken with the audience type AzureOSSDB as described [here](https://learn.microsoft.com/en-us/azure/synapse-analytics/spark/apache-spark-secure-credentials-with-tokenlibrary?pivots=programming-language-python#mssparkutilscredentialsgettoken), the function looks for the endpoint **https://ossrdbms-aad.database.windows.net/** as per Azure Public Cloud (CORP tenant) which is incorrect. The correct endpoint to look for on Mooncake cloud is ***.database.chinacloudapi.cn** as described [here](https://learn.microsoft.com/en-us/azure/china/resources-developer-guide#check-endpoints-in-azure). Please advise how can we set the correct cloud environment or override default endpoints in mssparkutils.

**To Reproduce**
1. Called mssparkutils.credentials.getToken('AzureOSSDB') on a Synapse Notebook on Azure China (Mooncake) cloud.

**Expected behavior**
The function call should return a bearer token to be used for SQL authentication as described [here](https://learn.microsoft.com/en-us/azure/synapse-analytics/spark/apache-spark-secure-credentials-with-tokenlibrary?pivots=programming-language-python#mssparkutilscredentialsgettoken).

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-python/assets/133139127/cfb0adac-01b0-4515-9616-199d525f848f)

**Additional context**
As per security guidelines, we are dependent on mssparkutils for authenticating using managed identities (credential-free), since Azure identity library does not work in Synapse workspace. Please refer this discussion for more details: https://github.com/Azure/azure-sdk-for-python/issues/35452

Exception Traceback:
`---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
Cell In [31], line 1
----> 1 mssparkutils.credentials.getToken('AzureOSSDB')

File ~/cluster-env/clonedenv/lib/python3.10/site-packages/notebookutils/mssparkutils/credentials.py:8, in getToken(audience, name)
      7 def getToken(audience, name=''):
----> 8     return creds.getToken(audience, name)

File ~/cluster-env/clonedenv/lib/python3.10/site-packages/py4j/java_gateway.py:1321, in JavaMember.__call__(self, *args)
   1315 command = proto.CALL_COMMAND_NAME +\
   1316     self.command_header +\
   1317     args_command +\
   1318     proto.END_COMMAND_PART
   1320 answer = self.gateway_client.send_command(command)
-> 1321 return_value = get_return_value(
   1322     answer, self.gateway_client, self.target_id, self.name)
   1324 for temp_arg in temp_args:
   1325     temp_arg._detach()

File /opt/spark/python/lib/pyspark.zip/pyspark/sql/utils.py:190, in capture_sql_exception.<locals>.deco(*a, **kw)
    188 def deco(*a: Any, **kw: Any) -> Any:
    189     try:
--> 190         return f(*a, **kw)
    191     except Py4JJavaError as e:
    192         converted = convert_exception(e.java_exception)

File ~/cluster-env/clonedenv/lib/python3.10/site-packages/py4j/protocol.py:326, in get_return_value(answer, gateway_client, target_id, name)
    324 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325 if answer[1] == REFERENCE_TYPE:
--> 326     raise Py4JJavaError(
    327         "An error occurred while calling {0}{1}{2}.\n".
    328         format(target_id, ".", name), value)
    329 else:
    330     raise Py4JError(
    331         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332         format(target_id, ".", name, value))

Py4JJavaError: An error occurred while calling z:mssparkutils.credentials.getToken.
: com.microsoft.azure.synapse.tokenlibrary.TokenLibrary$NonRetryableStatusException$1: POST failed with 'Bad Request' (400) and message: {"result":"DependencyError","errorId":"BadRequest","errorMessage":"[Code=LSROBOTokenFailure, Target=AzureOSSDB, Message=AADSTS500011: The resource principal named https://ossrdbms-aad.database.windows.net/ was not found in the tenant named [REDACTED]. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant. Trace ID: 72437143-d655-4076-8601-bc8779210400 Correlation ID: 6b7719e6-1904-402b-9863-7f31f11696df Timestamp: 2024-05-16 23:04:48Z]. TraceId : 8de16b79-1360-4d75-8deb-8e5e4098d614 | client-request-id : 475bac6d-c5e1-4a85-93f6-4386977aa66f. Error Component : LSR"}
	at com.microsoft.azure.synapse.tokenlibrary.TokenLibrary.$anonfun$invokeTokenService$7(TokenLibrary.scala:511)
	at com.twitter.util.Future.$anonfun$flatMap$1(Future.scala:1808)
	at com.twitter.util.Promise$FutureTransformer.liftedTree1$1(Promise.scala:240)
	at com.twitter.util.Promise$FutureTransformer.k(Promise.scala:240)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:215)
	at com.twitter.util.Promise$WaitQueue.com$twitter$util$Promise$WaitQueue$$run(Promise.scala:91)
	at com.twitter.util.Promise$WaitQueue$$anon$1.run(Promise.scala:86)
	at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:198)
	at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:157)
	at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:274)
	at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:109)
	at com.twitter.util.Promise$WaitQueue.runInScheduler(Promise.scala:86)
	at com.twitter.util.Promise.updateIfEmpty(Promise.scala:778)
	at com.twitter.util.Promise.update(Promise.scala:750)
	at com.twitter.util.Promise.setValue(Promise.scala:726)
	at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:123)
	at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$2.channelRead(ChannelTransport.scala:168)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at shadenetty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at com.twitter.finagle.netty4.http.handler.UnpoolHttpHandler$.channelRead(UnpoolHttpHandler.scala:32)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at shadenetty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at com.twitter.finagle.netty4.http.handler.ClientExceptionMapper$.channelRead(ClientExceptionMapper.scala:35)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at shadenetty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at com.twitter.finagle.netty4.http.handler.HeaderValidatorHandler$.channelRead(HeaderValidatorHandler.scala:51)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at shadenetty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at shadenetty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at shadenetty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at shadenetty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at shadenetty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at shadenetty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at shadenetty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at shadenetty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at shadenetty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at shadenetty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at shadenetty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at shadenetty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at shadenetty.handler.ssl.SslHandler.unwrap(SslHandler.java:1432)
	at shadenetty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1199)
	at shadenetty.handler.ssl.SslHandler.decode(SslHandler.java:1243)
	at shadenetty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at shadenetty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at shadenetty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at shadenetty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at shadenetty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at shadenetty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at shadenetty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at shadenetty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at shadenetty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at shadenetty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at shadenetty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at shadenetty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at shadenetty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:23)
	at shadenetty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)`

**Comment by pvaneck** [comment]
This probably isn't the best repo to post this issue as we don't maintain `mssparkutils`. Might have better luck posting your query [here](https://learn.microsoft.com/answers/questions/). 

I'm not sure what the guidance is for Synapse in sovereign clouds, but Is it possible to pass in the URI to `getToken` (i.e. `mssparkutils.credentials.getToken("https://ossrdbms-aad.database.chinacloudapi.cn")`?

/cc @xiangyan99 in case he knows more.

**Comment by abhbhatt** [comment]
UPDATE: Passing in the audience URI as mssparkutils.credentials.getToken("https://ossrdbms-aad.database.chinacloudapi.cn") also doesn't work and returns this exception.
![image](https://github.com/Azure/azure-sdk-for-python/assets/133139127/ccd8ea1a-71ef-4922-a011-d08c6a55a01d)

**Comment by xiangyan99** [comment]
Thanks for reaching out.

mssparkutils is not monitored in this repo. Please open a service ticket for help. https://azure.microsoft.com/support/create-ticket
