### ISSUE TITLE
Bing News Search missing argument error

### ISSUE THREAD

**Issue by davecom** [Azure/azure-sdk-for-python#35747]
- **Package Name**: azure.cognitiveservices.search.newssearch aka azure-cognitiveservices-search-newssearch
- **Package Version**:  2.0.0
- **Operating System**: Ubuntu 22.04.1
- **Python Version**: 3.11

**Describe the bug**
Internal error in library about missing keyword argument "errors"
```
  File "/home/ubuntu/.local/lib/python3.11/site-packages/azure/cognitiveservices/search/newssearch/operations/_news_operations.py", line 379, in search
    raise models.ErrorResponseException(self._deserialize, response)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/lib/python3.11/site-packages/azure/cognitiveservices/search/newssearch/models/_models_py3.py", line 529, in __init__
    super(ErrorResponseException, self).__init__(deserialize, response, 'ErrorResponse', *args)
  File "/home/ubuntu/.local/lib/python3.11/site-packages/msrest/exceptions.py", line 163, in __init__
    self.error = deserialize.dependencies[resp_type]()
TypeError: ErrorResponse.__init__() missing 1 required keyword-only argument: 'errors'
```

**To Reproduce**
```
from azure.cognitiveservices.search.newssearch import NewsSearchClient
from msrest.authentication import CognitiveServicesCredentials
subscription_key = "censored_key"
client = NewsSearchClient("https://api.bing.microsoft.com/", CognitiveServicesCredentials(subscription_key))
client.config.base_url = "{Endpoint}/v7.0"
news_result = client.news.search(query="myquery", market="en-us", count=10, freshness="Day")
```
**Expected behavior**
News results—these same lines of code have worked for me for years with no library upgrades or changes. Perhaps it is related to the widespread Microsoft outage this morning.

**Screenshots**
Censored:
```
Traceback (most recent call last):
  File "myfile.py", line 84, in <module>
    news_result = client.news.search(query="myquery", market="en-us", count=10, freshness="Day")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/lib/python3.11/site-packages/azure/cognitiveservices/search/newssearch/operations/_news_operations.py", line 379, in search
    raise models.ErrorResponseException(self._deserialize, response)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/lib/python3.11/site-packages/azure/cognitiveservices/search/newssearch/models/_models_py3.py", line 529, in __init__
    super(ErrorResponseException, self).__init__(deserialize, response, 'ErrorResponse', *args)
  File "/home/ubuntu/.local/lib/python3.11/site-packages/msrest/exceptions.py", line 163, in __init__
    self.error = deserialize.dependencies[resp_type]()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ErrorResponse.__init__() missing 1 required keyword-only argument: 'errors'
```
**Additional context**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.
