### ISSUE TITLE
AttributeError: 'StorageManagementClientConfiguration' object has no attribute 'api_version'

### ISSUE THREAD

**Issue by yfairweather** [Azure/azure-sdk-for-python#35821]
- **Package Name**: azure-mgmt-storage
- **Package Version**:  21.1.0
- **Operating System**: Ubuntu
- **Python Version**: 3.8

**Describe the bug**
When running `StorageManagementClient.storage_accounts.list()`, sometimes we run into this error but other times it just works

**To Reproduce**
1. Run `StorageManagementClient.storage_accounts.list()` and if you get lucky you will hit this backtrace:
```
Traceback (most recent call last):
  File "/opt/qumulo/env/202404241446/lib/python3.8/site-packages/azure/core/paging.py", line 124, in __next__
    return next(self._page_iterator)
  File "/opt/qumulo/env/202404241446/lib/python3.8/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/opt/qumulo/env/202404241446/lib/python3.8/site-packages/azure/mgmt/storage/v2023_01_01/operations/_storage_accounts_operations.py", line 1434, in get_next
    request = prepare_request(next_link)
  File "/opt/qumulo/env/202404241446/lib/python3.8/site-packages/azure/mgmt/storage/v2023_01_01/operations/_storage_accounts_operations.py", line 1417, in prepare_request
    _next_request_params["api-version"] = self._config.api_version
AttributeError: 'StorageManagementClientConfiguration' object has no attribute 'api_version'

```

**Expected behavior**
The API call should work 100% of the time

**Screenshots**

**Additional context**

**Comment by msyyc** [comment]
We will make an investigation ASAP.

**Comment by msyyc** [comment]
Hi @yfairweather Could you show the complete code screenshot? I can't reproduce the error locally.
