### ISSUE TITLE
LROPoller.result() cannot occasionally locate the requested message

### ISSUE THREAD

**Issue by DavideIntisoRulex** [Azure/azure-sdk-for-python#35849]
- **Package Name**: azure-communication-email
- **Package Version**: 1.0.0
- **Operating System**: Linux Ubuntu
- **Python Version**: 3.12.1

**Describe the bug**
Randomly, the result() function invoked on the LROPoller returned by the begin_send() will throw an exception. From the traceback, it can be inferred that the message was not found by the poller. However, the ID of the message is provided returned in the traceback, and from the logs of the communication service the same message with that ID is in fact delivered correctly.

This is the piece of code contained in a FastAPI application:

```python
try:
    log.info(f"Sending new email from {email.model_dump().get("senderAddress")}")
    poller = client.begin_send(email.model_dump(exclude_unset=True))
except HttpResponseError as error:
    log.error(error.response.json()["error"]["message"])
    raise HTTPException(status_code= error.status_code, detail= error.response.json()["error"]["message"])
result = poller.result(timeout=self.settings.settings.azure_comm_system.sending_timeout)
log.info(result)
return result
``` 

**To Reproduce**
1. The issue seems to occur randomly and sporadically, and no specific pattern for replication was found so far.

**Expected behavior**
The LROPoller.result() function can consistently return the information related to the sent message, in particular including those messages that are actually sent, as observed from the Azure Communication Services logs by associating the message ID returned in the traceback.

**Additional context**
Sensitive information has been oscured in the following logs, but the messageID reported in the traceback is identical to the correlationId of the Azure Communication Services logs.

Full traceback: 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/azure/core/polling/base_polling.py", line 757, in run
    self._poll()
  File "/usr/local/lib/python3.12/site-packages/azure/core/polling/base_polling.py", line 783, in _poll
    self.update_status()
  File "/usr/local/lib/python3.12/site-packages/azure/core/polling/base_polling.py", line 809, in update_status
    _raise_if_bad_http_status_and_method(self._pipeline_response.http_response)
  File "/usr/local/lib/python3.12/site-packages/azure/core/polling/base_polling.py", line 156, in _raise_if_bad_http_status_and_method
    raise BadStatus("Invalid return status {!r} for {!r} operation".format(code, response.request.method))
azure.core.polling.base_polling.BadStatus: Invalid return status 404 for 'GET' operation
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.12/site-packages/Secweb/ContentSecurityPolicy/ContentSecurityPolicyMiddleware.py", line 152, in __call__
    await self.app(scope, receive, set_Content_Security_Policy)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/asgi_correlation_id/middleware.py", line 90, in __call__
    await self.app(scope, receive, handle_outgoing_request)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/functions/communication_system/communication_system.py", line 20, in send_email
    res = agent.send_email(email_message)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/functions/communication_system/utilities/azure_communication.py", line 38, in send_email
    result = poller.result(timeout=self.settings.settings.azure_comm_system.sending_timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/azure/core/polling/_poller.py", line 251, in result
    self.wait(timeout)
  File "/usr/local/lib/python3.12/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/azure/core/polling/_poller.py", line 270, in wait
    raise self._exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/azure/core/polling/_poller.py", line 185, in _start
    self._polling_method.run()
  File "/usr/local/lib/python3.12/site-packages/azure/core/polling/base_polling.py", line 761, in run
    raise HttpResponseError(response=self._pipeline_response.http_response, error=err) from err
azure.core.exceptions.HttpResponseError: (MessageNotFound) Requested message could not be located. Couldn't find a record with the messageID: AAA-BBB-CCC-DDD-EEE
Code: MessageNotFound
Message: Requested message could not be located. Couldn't find a record with the messageID: AAA-BBB-CCC-DDD-EEE
``` 

Azure Communication Services logs:

```
{
   category: EmailSendMailOperational
   correlationId: AAA-BBB-CCC-DDD-EEE
   location: North Europe
   operationName: SendMail
   operationVersion: 2023-03-31
   properties: {
     AttachmentsCount: 1
     BccRecipientsCount: 0
     CcRecipientsCount: 0
     OperationCategory: EmailSendMailOperational
     OperationType: SendMail
     Size: 0.001611
     ToRecipientsCount: 1
     TrafficSource: Linux
     UniqueRecipientsCount: 1
   }
   resourceGroup: comm-service
   resourceId: /SUBSCRIPTIONS/XXXXXXXXXXX/RESOURCEGROUPS/COMM-SERVICE/PROVIDERS/MICROSOFT.COMMUNICATION/COMMUNICATIONSERVICES/YYYYYYY
   resourceName: yyyyyyy
   resourceType: communicationservices
   subscriptionId: XXXXXXXXXXX
   time: 2024-05-08T07:48:47.4508694+00:00
},
{
   category: EmailStatusUpdateOperational
   correlationId: AAA-BBB-CCC-DDD-EEE
   location: North Europe
   operationName: DeliveryStatusUpdate
   operationVersion: 2023-03-31
   properties: {
     DeliveryStatus: OutForDelivery
     FailureReason:
     IsHardBounce: false
     OperationCategory: EmailStatusUpdateOperational
     OperationType: DeliveryStatusUpdate
     SenderDomain: zzzzzz.com
     SenderUsername: wwwwww
   }
   resourceGroup: comm-service
   resourceId: /SUBSCRIPTIONS/XXXXXXXXXXX/RESOURCEGROUPS/COMM-SERVICE/PROVIDERS/MICROSOFT.COMMUNICATION/COMMUNICATIONSERVICES/YYYYYYY
   resourceName: yyyyyyy
   resourceType: communicationservices
   subscriptionId: XXXXXXXXXXX
   time: 2024-05-08T07:48:49.9017762+00:00
},
{
   category: EmailStatusUpdateOperational
   correlationId: AAA-BBB-CCC-DDD-EEE
   location: West Europe
   operationName: DeliveryStatusUpdate
   operationVersion: 2023-03-31
   properties: {
     DeliveryStatus: Delivered
     EnhancedSmtpStatusCode:
     FailureMessage:
     IsHardBounce: false
     OperationCategory: EmailStatusUpdateOperational
     OperationType: DeliveryStatusUpdate
     RecipientId: email@address.com
     SenderDomain: zzzzzz.com
     SenderUsername: wwwwww
     SmtpStatusCode:
   }
   resourceGroup: comm-service
   resourceId: /SUBSCRIPTIONS/XXXXXXXXXXX/RESOURCEGROUPS/COMM-SERVICE/PROVIDERS/MICROSOFT.COMMUNICATION/COMMUNICATIONSERVICES/YYYYYYY
   resourceName: yyyyyyy
   resourceType: communicationservices
   subscriptionId: XXXXXXXXXXX
   time: 2024-05-08T07:48:53.1960000+00:00
}
```

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by DavideIntisoRulex** [comment]
Hello @xiangyan99 and Team.

Are there any updates on this issue from your side? We confirm that it is re-occurring on our side.

Thank you.

**Comment by DavideIntisoRulex** [comment]
Hello @xiangyan99 and Team.

Are there any updates on this issue from your side? We confirm that it is re-occurring on our side.

Thank you.

**Comment by DavideIntisoRulex** [comment]
Hello @xiangyan99 and Team.

Are there any updates on this issue from your side? We confirm that it is re-occurring on our side.

Thank you.

**Comment by DavideIntisoRulex** [comment]
Hello @xiangyan99 , @kristapratico and Team.

Are there any updates on this issue from your side?

Thank you.

**Comment by kagbakpem** [comment]
Hello @DavideIntisoRulex, thanks for reporting this and apologies for the delay in responding thus far. We have not been able to reproduce this issue thus far. Are you able to provide further details into your scenarios and repro steps?

Thanks

**Comment by kagbakpem** [comment]
Unable to reproduce the issue.

**Comment by kagbakpem** [comment]
Unable to reproduce the issue.
