### ISSUE TITLE
SecurityCenter().security_contacts list bug

### ISSUE THREAD

**Issue by odgrso** [Azure/azure-sdk-for-python#35996]
- **Package Name**: 
azure-mgmt-security

- **Package Version**: 
6.0.0

- **Operating System**:
Darwin usernoMacBook-Pro-3.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:27 PDT 2023; root:xnu-10002.41.9~6/RELEASE_X86_64 x86_64

- **Python Version**: 
Python 3.9.18

**To Reproduce**

```python:
from azure.mgmt.security import SecurityCenter
from azure.identity import DefaultAzureCredential

credential = DefaultAzureCredential()
client = SecurityCenter(credential, subscription_id)
for security_contact in client.security_contacts.list():
    print(security_contact)
```

```text:output
Traceback (most recent call last):
  File "/Users/user/.local/share/virtualenvs/src-tEfj-4ON/lib/python3.9/site-packages/azure/mgmt/security/_serialization.py", line 1475, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/Users/user/.local/share/virtualenvs/src-tEfj-4ON/lib/python3.9/site-packages/azure/mgmt/security/_serialization.py", line 1222, in rest_key_extractor
    return working_data.get(key)
AttributeError: 'list' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/development/karte-cloud-service-scanner-engine/src/tests/Azure/tmp.py", line 6, in <module>
    for security_contact in client.security_contacts.list():
  File "/Users/user/.local/share/virtualenvs/src-tEfj-4ON/lib/python3.9/site-packages/azure/core/paging.py", line 123, in __next__
    return next(self._page_iterator)
  File "/Users/user/.local/share/virtualenvs/src-tEfj-4ON/lib/python3.9/site-packages/azure/core/paging.py", line 83, in __next__
    self.continuation_token, self._current_page = self._extract_data(self._response)
  File "/Users/user/.local/share/virtualenvs/src-tEfj-4ON/lib/python3.9/site-packages/azure/mgmt/security/v2020_01_01_preview/operations/_security_contacts_operations.py", line 237, in extract_data
    deserialized = self._deserialize("SecurityContactList", pipeline_response)
  File "/Users/user/.local/share/virtualenvs/src-tEfj-4ON/lib/python3.9/site-packages/azure/mgmt/security/_serialization.py", line 1420, in __call__
    return self._deserialize(target_obj, data)
  File "/Users/user/.local/share/virtualenvs/src-tEfj-4ON/lib/python3.9/site-packages/azure/mgmt/security/_serialization.py", line 1490, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/Users/user/.local/share/virtualenvs/src-tEfj-4ON/lib/python3.9/site-packages/azure/core/exceptions.py", line 100, in raise_with_traceback
    raise error.with_traceback(exc_traceback)  # pylint: disable=raise-missing-from
  File "/Users/user/.local/share/virtualenvs/src-tEfj-4ON/lib/python3.9/site-packages/azure/mgmt/security/_serialization.py", line 1475, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/Users/user/.local/share/virtualenvs/src-tEfj-4ON/lib/python3.9/site-packages/azure/mgmt/security/_serialization.py", line 1222, in rest_key_extractor
    return working_data.get(key)
azure.core.exceptions.DeserializationError: (", AttributeError: 'list' object has no attribute 'get'", 'Unable to deserialize to object: type', AttributeError("'list' object has no attribute 'get'"))
```

**Comment by ChenxiJiang333** [comment]
Hi @odgrso, seems there's something wrong with the old service, please try update code to
```
for security_contact in client.security_contacts.list(api_version="2023-12-01-preview"):
    print(security_contact)
```
