### ISSUE TITLE
ValueError: Management Operation error occurred. When a task exceeds 240s with 5min lock out period

### ISSUE THREAD

**Issue by cabal-daniel** [Azure/azure-sdk-for-python#36203]
- **Package Name**: azure-servicebus==7.12.2
- **Package Version**:  azure-servicebus==7.12.2
- **Operating System**: MacOS and Ubuntu
- **Python Version**:  3.9.12

**Describe the bug**
When a worker takes 240s to consume a message (the duration between read and complete message), we are hit with the following error. The lock period is set to 5mins.

```
2024-06-21 15:55:30 ERROR    Unexpected error occurred (ValueError('Management Operation error occurred.')). Handler shutting down.
Traceback (most recent call last):
  File "/Users/hudan/fileread/sandbox/sbs_problems_20240528/.venv/lib/python3.10/site-packages/azure/servicebus/aio/_base_handler_async.py", line 260, in _do_retryable_operation
    return await operation(**kwargs)
  File "/Users/hudan/fileread/sandbox/sbs_problems_20240528/.venv/lib/python3.10/site-packages/azure/servicebus/aio/_base_handler_async.py", line 374, in _mgmt_request_response
    return await self._amqp_transport.mgmt_client_request_async(
  File "/Users/hudan/fileread/sandbox/sbs_problems_20240528/.venv/lib/python3.10/site-packages/azure/servicebus/aio/_transport/_pyamqp_transport_async.py", line 437, in mgmt_client_request_async
    status, description, response = await mgmt_client.mgmt_request_async(
  File "/Users/hudan/fileread/sandbox/sbs_problems_20240528/.venv/lib/python3.10/site-packages/azure/servicebus/_pyamqp/aio/_client_async.py", line 395, in mgmt_request_async
    status, description, response = await mgmt_link.execute(
  File "/Users/hudan/fileread/sandbox/sbs_problems_20240528/.venv/lib/python3.10/site-packages/azure/servicebus/_pyamqp/aio/_management_operation_async.py", line 112, in execute
    raise self._mgmt_error  # pylint: disable=raising-bad-type
ValueError: Management Operation error occurred.
2024-06-21 15:55:31 WARNING  connection dropped for queue: dev-andrew-coordinator-embedding - exception: Handler failed: Management Operation error occurred..
```

**To Reproduce**
1. Send a message to a SB queue with a lock period of 5mins
2. Create a worker to read from the queue, then just `time.sleep(240)` then complete the message
3. The errors above happen

**Expected behavior**
The message should be consumed without problems

**Screenshots**

**Additional context**

**Comment by kashifkhan** [comment]
Thank you for the feedback @cabal-daniel . Can you also share the repro code or close to what yall are running as well please, itll help when we repro on our side.

**Comment by cabal-daniel** [comment]
We are not using AutoLockRenewer this is our code. I'll try to share as much code as I can but we have some abstractions in our implementation -- I honestly think if you can set any consumer to time.sleep(240), this will show up.

**Comment by kashifkhan** [comment]
@cabal-daniel I just ran this snippet and was not able to reproduce that

I set up a queue with a lock time of 5 mins, I received it, slept for 4 mins and then was able to complete it with no errors. 

```python

async with servicebus_client:
        sender = servicebus_client.get_queue_sender(queue_name=QUEUE_NAME)
        receiver = servicebus_client.get_queue_receiver(queue_name=QUEUE_NAME)
        async with sender, receiver:
            await send_single_message(sender)
            messages = await receiver.receive_messages(max_message_count=1, max_wait_time=5)
            print("sleeping for 240 seconds")
            await asyncio.sleep(240)
            for message in messages:
                print("completing message")
                await receiver.complete_message(message)

    print("Send message is done.")
```

**Comment by cabal-daniel** [comment]
Hi @kashifkhan I was able to reproduce it with standard code. Here are my steps

1. I create a queue on the service bus UI with the following configurations. Everything is default except it's a 5min lock down period

![Screenshot 2024-06-24 at 6 01 11 PM](https://github.com/Azure/azure-sdk-for-python/assets/65152299/bf1081a1-a228-4de9-8996-86fd4a9e734f)


2. Assert the number of messages is 0

![Screenshot 2024-06-24 at 6 02 24 PM](https://github.com/Azure/azure-sdk-for-python/assets/65152299/c81f5be6-d3ae-4af1-a2e3-3dcb78956732)


3. I run the following code

```

import time
import asyncio

namespace = ''
queue_name = 'servicebus-test-2'

async def push():
    from azure.identity import DefaultAzureCredential
    from azure.servicebus import ServiceBusClient, ServiceBusMessage
    sb_client = ServiceBusClient(
        fully_qualified_namespace=namespace,
        credential=DefaultAzureCredential(logging_enable=True),
    )

    with sb_client.get_queue_sender(queue_name=queue_name) as sender:
        sender.send_messages(ServiceBusMessage('foobar'))

async def consume():
    from azure.identity.aio import DefaultAzureCredential
    from azure.servicebus.aio import ServiceBusClient
    sb_client = ServiceBusClient(
        fully_qualified_namespace=namespace,
        credential=DefaultAzureCredential(logging_enable=True),
    )
    async with sb_client.get_queue_receiver(queue_name=queue_name, socket_timeout=1.5) as receiver:
        messages = await receiver.peek_messages(
            max_message_count=1,
        )
        print(f'[1] peeked {len(messages)} messages')
        messages = await receiver.receive_messages(
            max_message_count=1,
            max_wait_time=15,
        )
        print('received', messages[0])
        time.sleep(250)
        print('completing...')
        await receiver.complete_message(messages[0])
        print('message is complete')
        messages = await receiver.peek_messages(
            max_message_count=1,
        )
        print(f'[2] peeked {len(messages)} messages')
        messages = await receiver.receive_messages(
            max_message_count=1,
            max_wait_time=15,
        )
        print('received', messages[0])
        print('completing...')
        await receiver.complete_message(messages[0])

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(push())
    asyncio.get_event_loop().run_until_complete(consume())

```

4. Before the 250s mark you should see 

```
[1] peeked 1 messages
received foobar
```

5. Assert the number of messages is now 1

![Screenshot 2024-06-24 at 6 04 49 PM](https://github.com/Azure/azure-sdk-for-python/assets/65152299/15a4875a-ef8d-44c2-acd6-db359b1d2cb0)

6. Error reproduced -- you should now see this

```
[1] peeked 1 messages
received foobar
completing...
message is complete
Unexpected error occurred (ValueError('Management Operation error occurred.')). Handler shutting down.
Traceback (most recent call last):
  File "/Users/hudan/fileread/cabal/.venv/lib/python3.9/site-packages/azure/servicebus/aio/_base_handler_async.py", line 260, in _do_retryable_operation
    return await operation(**kwargs)
  File "/Users/hudan/fileread/cabal/.venv/lib/python3.9/site-packages/azure/servicebus/aio/_base_handler_async.py", line 374, in _mgmt_request_response
    return await self._amqp_transport.mgmt_client_request_async(
  File "/Users/hudan/fileread/cabal/.venv/lib/python3.9/site-packages/azure/servicebus/aio/_transport/_pyamqp_transport_async.py", line 437, in mgmt_client_request_async
    status, description, response = await mgmt_client.mgmt_request_async(
  File "/Users/hudan/fileread/cabal/.venv/lib/python3.9/site-packages/azure/servicebus/_pyamqp/aio/_client_async.py", line 395, in mgmt_request_async
    status, description, response = await mgmt_link.execute(
  File "/Users/hudan/fileread/cabal/.venv/lib/python3.9/site-packages/azure/servicebus/_pyamqp/aio/_management_operation_async.py", line 112, in execute
    raise self._mgmt_error  # pylint: disable=raising-bad-type
ValueError: Management Operation error occurred.
Traceback (most recent call last):
  File "/Users/hudan/fileread/cabal/.venv/lib/python3.9/site-packages/azure/servicebus/aio/_base_handler_async.py", line 260, in _do_retryable_operation
    return await operation(**kwargs)
  File "/Users/hudan/fileread/cabal/.venv/lib/python3.9/site-packages/azure/servicebus/aio/_base_handler_async.py", line 374, in _mgmt_request_response
    return await self._amqp_transport.mgmt_client_request_async(
  File "/Users/hudan/fileread/cabal/.venv/lib/python3.9/site-packages/azure/servicebus/aio/_transport/_pyamqp_transport_async.py", line 437, in mgmt_client_request_async
    status, description, response = await mgmt_client.mgmt_request_async(
  File "/Users/hudan/fileread/cabal/.venv/lib/python3.9/site-packages/azure/servicebus/_pyamqp/aio/_client_async.py", line 395, in mgmt_request_async
    status, description, response = await mgmt_link.execute(
  File "/Users/hudan/fileread/cabal/.venv/lib/python3.9/site-packages/azure/servicebus/_pyamqp/aio/_management_operation_async.py", line 112, in execute
    raise self._mgmt_error  # pylint: disable=raising-bad-type
ValueError: Management Operation error occurred.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hudan/fileread/sandbox/sbs_problems_20240528/debugging_shit/publish_raw.py", line 54, in <module>
    asyncio.get_event_loop().run_until_complete(consume())
  File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/hudan/fileread/sandbox/sbs_problems_20240528/debugging_shit/publish_raw.py", line 40, in consume
    messages = await receiver.peek_messages(
  File "/Users/hudan/fileread/cabal/.venv/lib/python3.9/site-packages/azure/servicebus/aio/_servicebus_receiver_async.py", line 821, in peek_messages
    messages = await self._mgmt_request_response_with_retry(
  File "/Users/hudan/fileread/cabal/.venv/lib/python3.9/site-packages/azure/servicebus/aio/_base_handler_async.py", line 396, in _mgmt_request_response_with_retry
    return await self._do_retryable_operation(
  File "/Users/hudan/fileread/cabal/.venv/lib/python3.9/site-packages/azure/servicebus/aio/_base_handler_async.py", line 267, in _do_retryable_operation
    last_exception = await self._handle_exception(exception)
  File "/Users/hudan/fileread/cabal/.venv/lib/python3.9/site-packages/azure/servicebus/aio/_base_handler_async.py", line 208, in _handle_exception
    raise error
azure.servicebus.exceptions.ServiceBusError: Handler failed: Management Operation error occurred..
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x109b1edf0>
```

Moreover the message count is still 1 even though the "complete_message" should have succeeded. Thus this message is actually not marked as complete.

![Screenshot 2024-06-24 at 6 14 46 PM](https://github.com/Azure/azure-sdk-for-python/assets/65152299/9bc58ed7-8012-4fe9-9c1f-0b43ae77a18e)

**Comment by kashifkhan** [comment]
Hi @cabal-daniel, can you please update and try with asyncio.sleep(250) vs time.sleep(250) in your sample please? time.sleep() will prevent the keep alive from running in the background

**Comment by cabal-daniel** [comment]
@kashifkhan I used `time.sleep` here but a lot of our tasks are synchronous and demand heavy resources and I'm not sure how we can make sure the keep alive is called at the right times.

**Comment by kashifkhan** [comment]
@cabal-daniel unfortunately `time.sleep` is blocking the running of the keep alive from running which is causing the issues you are seeing. Is there a way for you to use the sync version of the client ?

**Comment by cabal-daniel** [comment]
@kashifkhan thank you -- switching to non async worked -- we'll figure out how to make it work without async. Very appreciative of your help! :)

**Comment by kashifkhan** [comment]
@cabal-daniel Glad I could help.
