### ISSUE TITLE
Using the LANGUAGES add-on breaks Document Intelligence

### ISSUE THREAD

**Issue by gcompagnoni** [Azure/azure-sdk-for-python#36265]
- **Package Name**: azure-ai-documentintelligence
- **Package Version**:  1.0.0b3
- **Operating System**: Windows
- **Python Version**: Python 3.11.5

**Describe the bug**
Requesting the usage of the LANGUAGES add-on in Document Intelligence returns a server error:

```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\azure\core\polling\base_polling.py", line 757, in run
    self._poll()
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\azure\core\polling\base_polling.py", line 789, in _poll
    raise OperationFailed("Operation failed or canceled")
azure.core.polling.base_polling.OperationFailed: Operation failed or canceled

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\Documents\prova.py", line 138, in <module>
    analyze_languages()
  File "C:\Users\user\Documents\prova.py", line 114, in analyze_languages
    result: AnalyzeResult = poller.result()
                            ^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\azure\core\polling\_poller.py", line 251, in result
    self.wait(timeout)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\azure\core\tracing\decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\azure\core\polling\_poller.py", line 270, in wait
    raise self._exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\azure\core\polling\_poller.py", line 185, in _start
    self._polling_method.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\azure\core\polling\base_polling.py", line 772, in run
    raise HttpResponseError(response=self._pipeline_response.http_response, error=err) from err
azure.core.exceptions.HttpResponseError: (InternalServerError) An unexpected error occurred.
Code: InternalServerError
Message: An unexpected error occurred.
Exception Details:      (InternalServerError) An unexpected error occurred.
        Code: InternalServerError
        Message: An unexpected error occurred.
        Target: 0
```

**To Reproduce**
1. Run the sample code in [https://github.com/Azure-Samples/document-intelligence-code-samples/blob/main/Python(v4.0)/Add-on_capabilities/sample_analyze_addon_languages.py](https://github.com/Azure-Samples/document-intelligence-code-samples/blob/main/Python(v4.0)/Add-on_capabilities/sample_analyze_addon_languages.py
)

**Expected behavior**
A successful response from polling.

**Additional context**
Yesterday the feature worked correctly. Other add-ons seem to work correctly.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by YalinLi0312** [comment]
Hi @gcompagnoni , can you share your testing file so that we can investigate further?
