### ISSUE TITLE
Dataset monitors is broken

### ISSUE THREAD

**Issue by martheveldhuis** [Azure/azure-sdk-for-python#36320]
- N/A
- N/A
- N/A
- N/A 

**Describe the bug**
In the AzureML Studio, when creating a dataset monitor, an error occurs

**To Reproduce**
1. Go to the Data tab in the AzureML Studio
2. Click Dataset Monitors
3. Click Create

**Expected behavior**
You can create a dataset monitor

**Screenshots**
Instead this happens
![image](https://github.com/Azure/azure-sdk-for-python/assets/14073603/27481c69-a7c6-447f-92f8-e53a8602492c)

**Additional context**
Full trace:

>     
    at Ha (https://ml.azure.com/assets/DatasetDriftCreatePanel-c8bb169f.js:1:57262)
    at t (https://ml.azure.com/assets/index-3fcafd84.js:331:101810)
    at t (https://ml.azure.com/assets/index-3fcafd84.js:331:35346)
    at t (https://ml.azure.com/assets/index-3fcafd84.js:331:101582)
    at t (https://ml.azure.com/assets/withExpContext-bf37f65e.js:1:286)
    at https://ml.azure.com/assets/Wizard-1e593c92.js:1:22921
    at div
    at div
    at i (https://ml.azure.com/assets/index-3fcafd84.js:62:8662)
    at div
    at i (https://ml.azure.com/assets/index-3fcafd84.js:62:8662)
    at je (https://ml.azure.com/assets/Wizard-1e593c92.js:1:1829)
    at div
    at i (https://ml.azure.com/assets/index-3fcafd84.js:62:8662)
    at div
    at i (https://ml.azure.com/assets/index-3fcafd84.js:62:8662)
    at div
    at i (https://ml.azure.com/assets/index-3fcafd84.js:62:8662)
    at div
    at i (https://ml.azure.com/assets/index-3fcafd84.js:62:8662)
    at div
    at At (https://ml.azure.com/assets/Wizard-1e593c92.js:1:16262)
    at div
    at Ya (https://ml.azure.com/assets/DatasetDriftCreatePanel-c8bb169f.js:1:59328)
    at div
    at i (https://ml.azure.com/assets/withEngagementTracking-24a0a2c9.js:1:300)
    at t (https://ml.azure.com/assets/index-3fcafd84.js:331:35346)
    at t (https://ml.azure.com/assets/withRouteContext-dec10665.js:1:286)
    at t (https://ml.azure.com/assets/index-3fcafd84.js:331:101582)
    at t (https://ml.azure.com/assets/withExpContext-bf37f65e.js:1:286)
    at div
    at div
    at div
    at div
    at https://ml.azure.com/assets/index-3fcafd84.js:48:25146
    at div
    at div
    at https://ml.azure.com/assets/index-3fcafd84.js:26:42149
    at div
    at https://ml.azure.com/assets/index-3fcafd84.js:48:21158
    at https://ml.azure.com/assets/index-3fcafd84.js:25:53506
    at span
    at https://ml.azure.com/assets/index-3fcafd84.js:48:22624
    at https://ml.azure.com/assets/index-3fcafd84.js:25:53506
    at t (https://ml.azure.com/assets/index-3fcafd84.js:48:220527)
    at https://ml.azure.com/assets/index-3fcafd84.js:25:53506
    at OMt (https://ml.azure.com/assets/index-3fcafd84.js:331:19959)
    at l1e (https://ml.azure.com/assets/index-3fcafd84.js:331:19508)
    at q_e (https://ml.azure.com/assets/index-3fcafd84.js:284:63459)
    at Hj (https://ml.azure.com/assets/index-3fcafd84.js:331:20990)
    at Ka (https://ml.azure.com/assets/DatasetDriftCreatePanel-c8bb169f.js:1:66479)
    at t (https://ml.azure.com/assets/index-3fcafd84.js:331:29309)
    at Qa (https://ml.azure.com/assets/DatasetListPage-7205eb0b.js:1:7769)
    at https://ml.azure.com/assets/index-3fcafd84.js:129:5228
    at tQe (https://ml.azure.com/assets/index-3fcafd84.js:129:2957)
    at div
    at i (https://ml.azure.com/assets/withEngagementTracking-24a0a2c9.js:1:300)
    at F (https://ml.azure.com/assets/Pivot-22156d26.js:1:4090)
    at div
    at a (https://ml.azure.com/assets/Pivot-8a3dbf0a.js:1:2153)
    at div
    at div
    at https://ml.azure.com/assets/Pivot-8a3dbf0a.js:1:2982
    at https://ml.azure.com/assets/index-3fcafd84.js:25:53506
    at div
    at je (https://ml.azure.com/assets/Pivot-22156d26.js:1:6338)
    at p (https://ml.azure.com/assets/Pivot-22156d26.js:1:4586)
    at Me (https://ml.azure.com/assets/Pivot-22156d26.js:1:8574)
    at div
    at div
    at i (https://ml.azure.com/assets/index-3fcafd84.js:62:8662)
    at div
    at i (https://ml.azure.com/assets/index-3fcafd84.js:62:8662)
    at k (https://ml.azure.com/assets/Page-8b83a251.js:1:3228)
    at se (https://ml.azure.com/assets/Page-8b83a251.js:1:4724)
    at ms (https://ml.azure.com/assets/DatasetListPage-7205eb0b.js:1:46954)
    at https://ml.azure.com/assets/index-3fcafd84.js:129:5228
    at tQe (https://ml.azure.com/assets/index-3fcafd84.js:129:2957)
    at div
    at i (https://ml.azure.com/assets/withEngagementTracking-24a0a2c9.js:1:300)
    at t (https://ml.azure.com/assets/index-3fcafd84.js:331:35346)
    at t (https://ml.azure.com/assets/withRouteContext-dec10665.js:1:286)
    at t (https://ml.azure.com/assets/withAuthorizationContext-af50f14c.js:1:287)
    at t (https://ml.azure.com/assets/withExpContext-bf37f65e.js:1:286)
    at t (https://ml.azure.com/assets/index-3fcafd84.js:331:101582)
    at r (https://ml.azure.com/assets/index-3fcafd84.js:196:93183)
    at Check (https://ml.azure.com/assets/index-3fcafd84.js:353:106340)
    at _d (https://ml.azure.com/assets/App-ccf11586.js:20:203287)
    at t (https://ml.azure.com/assets/index-3fcafd84.js:125:8709)
    at Jnt (https://ml.azure.com/assets/index-3fcafd84.js:129:51840)
    at https://ml.azure.com/assets/index-3fcafd84.js:129:5228
    at Md (https://ml.azure.com/assets/App-ccf11586.js:20:203525)
    at t (https://ml.azure.com/assets/index-3fcafd84.js:125:9680)
    at Rd (https://ml.azure.com/assets/App-ccf11586.js:20:203726)
    at Dd (https://ml.azure.com/assets/App-ccf11586.js:20:204076)
    at Suspense
    at Jnt (https://ml.azure.com/assets/index-3fcafd84.js:129:51840)
    at https://ml.azure.com/assets/index-3fcafd84.js:129:5228
    at ahr (https://ml.azure.com/assets/index-3fcafd84.js:196:16047)
    at main
    at i (https://ml.azure.com/assets/index-3fcafd84.js:62:8662)
    at div
    at i (https://ml.azure.com/assets/index-3fcafd84.js:62:8662)
    at lu (https://ml.azure.com/assets/App-ccf11586.js:20:218065)
    at div
    at hu (https://ml.azure.com/assets/App-ccf11586.js:20:222305)
    at div
    at i (https://ml.azure.com/assets/index-3fcafd84.js:62:8662)
    at gu (https://ml.azure.com/assets/App-ccf11586.js:20:220810)
    at ahr (https://ml.azure.com/assets/index-3fcafd84.js:196:16047)
    at xu (https://ml.azure.com/assets/App-ccf11586.js:20:223318)
    at amr (https://ml.azure.com/assets/index-3fcafd84.js:284:65617)
    at hr (https://ml.azure.com/assets/App-ccf11586.js:1:6578)
    at Rl (https://ml.azure.com/assets/App-ccf11586.js:20:30867)
    at yr (https://ml.azure.com/assets/App-ccf11586.js:1:9368)
    at ahr (https://ml.azure.com/assets/index-3fcafd84.js:196:16047)
    at p (https://ml.azure.com/assets/PortalCompatProvider-d9143084.js:1:325)
    at div
    at tar (https://ml.azure.com/assets/index-3fcafd84.js:131:8879)
    at https://ml.azure.com/assets/FluentProvider-0c53269c.js:1:3496
    at er (https://ml.azure.com/assets/FluentProvider-d55a4270.js:1:8999)
    at div
    at https://ml.azure.com/assets/index-3fcafd84.js:48:21158
    at https://ml.azure.com/assets/index-3fcafd84.js:25:53506
    at vr (https://ml.azure.com/assets/App-ccf11586.js:7:2184)
    at _r (https://ml.azure.com/assets/App-ccf11586.js:7:11922)
    at Nr (https://ml.azure.com/assets/App-ccf11586.js:7:2728)
    at wr (https://ml.azure.com/assets/App-ccf11586.js:7:5054)
    at Lr (https://ml.azure.com/assets/App-ccf11586.js:7:11512)
    at Rr (https://ml.azure.com/assets/App-ccf11586.js:7:12196)
    at kr (https://ml.azure.com/assets/App-ccf11586.js:7:455)
    at Il (https://ml.azure.com/assets/App-ccf11586.js:20:32685)
    at Tr (https://ml.azure.com/assets/App-ccf11586.js:7:5298)
    at yu (https://ml.azure.com/assets/App-ccf11586.js:20:223708)
    at t (https://ml.azure.com/assets/index-3fcafd84.js:353:89610)
    at r (https://ml.azure.com/assets/index-3fcafd84.js:196:93183)
    at f2t (https://ml.azure.com/assets/index-3fcafd84.js:255:36070)
    at Zyt (https://ml.azure.com/assets/index-3fcafd84.js:228:170947)
    at Gyt (https://ml.azure.com/assets/index-3fcafd84.js:228:170818)
    at Fne (https://ml.azure.com/assets/index-3fcafd84.js:246:11982)
    at ybt (https://ml.azure.com/assets/index-3fcafd84.js:244:51805)
    at W2t (https://ml.azure.com/assets/index-3fcafd84.js:258:36864)
    at R1t (https://ml.azure.com/assets/index-3fcafd84.js:228:149568)
    at qFt (https://ml.azure.com/assets/index-3fcafd84.js:284:49552)
    at gbt (https://ml.azure.com/assets/index-3fcafd84.js:244:49797)
    at TOt (https://ml.azure.com/assets/index-3fcafd84.js:348:28632)
    at Fne (https://ml.azure.com/assets/index-3fcafd84.js:246:11982)
    at _2t (https://ml.azure.com/assets/index-3fcafd84.js:258:2038)
    at g2t (https://ml.azure.com/assets/index-3fcafd84.js:258:1753)
    at G7t (https://ml.azure.com/assets/index-3fcafd84.js:353:96963)
    at Suspense
    at Bre (https://ml.azure.com/assets/index-3fcafd84.js:226:240862)
    at Jor (https://ml.azure.com/assets/index-3fcafd84.js:377:78530)
    at Jnt (https://ml.azure.com/assets/index-3fcafd84.js:129:51840)
    at https://ml.azure.com/assets/index-3fcafd84.js:129:5228
    at nir (https://ml.azure.com/assets/index-3fcafd84.js:377:86595)
    at vmt (https://ml.azure.com/assets/index-3fcafd84.js:196:79107)
    at Yor (https://ml.azure.com/assets/index-3fcafd84.js:377:78147)
    at r (https://ml.azure.com/assets/index-3fcafd84.js:125:10208)
    at U_t (https://ml.azure.com/assets/index-3fcafd84.js:228:87923)
    at t (https://ml.azure.com/assets/index-3fcafd84.js:125:5506)

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Your question does not appear to be related to the SDK.

Please open a service ticket for AzureML Studio. https://azure.microsoft.com/support/create-ticket
