### ISSUE TITLE
Concurrent send_messages with async ServiceBusSender fails

### ISSUE THREAD

**Issue by iangoldby** [Azure/azure-sdk-for-python#36334]
- **Package Name**: azure-servicebus
- **Package Version**: 7.12.2
- **Operating System**: Windows 11 Enterprise 22H2
- **Python Version**: 3.12.4

**Describe the bug**
Sending multiple messages on the Service Bus concurrently using the same asyncio sender results in the handler shutting down, leading ultimately to `ServiceBusError: Handler failed: 'NoneType' object has no attribute 'create_sender_link'.`

**To Reproduce**

```
import asyncio

from azure.servicebus import ServiceBusMessage
from azure.servicebus.aio import ServiceBusClient

CONN_STR = <service bus connection string>
QUEUE_NAME = <queue name>

async def main():

    async with ServiceBusClient.from_connection_string(conn_str=CONN_STR) as client:
        async with client.get_queue_sender(QUEUE_NAME) as sender:
            await asyncio.gather(*(sender.send_messages(ServiceBusMessage("hello")) for _ in range(10)))


if __name__ == "__main__":
    asyncio.run(main())
```

This results in (usually) two messages being successfully queued, and the following traceback:

```
Unexpected error occurred (AttributeError("'NoneType' object has no attribute 'create_sender_link'")). Handler shutting down.
Traceback (most recent call last):
  File "<REDACTED>\site-packages\azure\servicebus\aio\_base_handler_async.py", line 260, in _do_retryable_operation
    return await operation(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>\site-packages\azure\servicebus\aio\_servicebus_sender_async.py", line 239, in _send
    await self._amqp_transport.send_messages_async(
  File "<REDACTED>\site-packages\azure\servicebus\aio\_transport\_pyamqp_transport_async.py", line 141, in send_messages_async
    await sender._open()
  File "<REDACTED>\site-packages\azure\servicebus\aio\_servicebus_sender_async.py", line 222, in _open
    while not await self._handler.client_ready_async():
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>\site-packages\azure\servicebus\_pyamqp\aio\_client_async.py", line 329, in client_ready_async
    if not await self._client_ready_async():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>\site-packages\azure\servicebus\_pyamqp\aio\_client_async.py", line 510, in _client_ready_async
    self._link = self._session.create_sender_link(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'create_sender_link'
Unexpected error occurred (AttributeError("'NoneType' object has no attribute 'client_ready_async'")). Handler shutting down.
Traceback (most recent call last):
  File "<REDACTED>\site-packages\azure\servicebus\aio\_base_handler_async.py", line 260, in _do_retryable_operation
    return await operation(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>\site-packages\azure\servicebus\aio\_servicebus_sender_async.py", line 239, in _send
    await self._amqp_transport.send_messages_async(
  File "<REDACTED>\site-packages\azure\servicebus\aio\_transport\_pyamqp_transport_async.py", line 141, in send_messages_async
    await sender._open()
  File "<REDACTED>\site-packages\azure\servicebus\aio\_servicebus_sender_async.py", line 222, in _open
    while not await self._handler.client_ready_async():
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'client_ready_async'
Unexpected error occurred (AttributeError("'NoneType' object has no attribute 'client_ready_async'")). Handler shutting down.
Traceback (most recent call last):
  File "<REDACTED>\site-packages\azure\servicebus\aio\_base_handler_async.py", line 260, in _do_retryable_operation
    return await operation(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>\site-packages\azure\servicebus\aio\_servicebus_sender_async.py", line 239, in _send
    await self._amqp_transport.send_messages_async(
  File "<REDACTED>\site-packages\azure\servicebus\aio\_transport\_pyamqp_transport_async.py", line 141, in send_messages_async
    await sender._open()
  File "<REDACTED>\site-packages\azure\servicebus\aio\_servicebus_sender_async.py", line 222, in _open
    while not await self._handler.client_ready_async():
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'client_ready_async'
Unexpected error occurred (AttributeError("'NoneType' object has no attribute 'client_ready_async'")). Handler shutting down.
Traceback (most recent call last):
  File "<REDACTED>\site-packages\azure\servicebus\aio\_base_handler_async.py", line 260, in _do_retryable_operation
    return await operation(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>\site-packages\azure\servicebus\aio\_servicebus_sender_async.py", line 239, in _send
    await self._amqp_transport.send_messages_async(
  File "<REDACTED>\site-packages\azure\servicebus\aio\_transport\_pyamqp_transport_async.py", line 141, in send_messages_async
    await sender._open()
  File "<REDACTED>\site-packages\azure\servicebus\aio\_servicebus_sender_async.py", line 222, in _open
    while not await self._handler.client_ready_async():
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'client_ready_async'
Unexpected error occurred (AttributeError("'NoneType' object has no attribute 'client_ready_async'")). Handler shutting down.
Traceback (most recent call last):
  File "<REDACTED>\site-packages\azure\servicebus\aio\_base_handler_async.py", line 260, in _do_retryable_operation
    return await operation(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>\site-packages\azure\servicebus\aio\_servicebus_sender_async.py", line 239, in _send
    await self._amqp_transport.send_messages_async(
  File "<REDACTED>\site-packages\azure\servicebus\aio\_transport\_pyamqp_transport_async.py", line 141, in send_messages_async
    await sender._open()
  File "<REDACTED>\site-packages\azure\servicebus\aio\_servicebus_sender_async.py", line 222, in _open
    while not await self._handler.client_ready_async():
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'client_ready_async'
Unexpected error occurred (AttributeError("'NoneType' object has no attribute 'client_ready_async'")). Handler shutting down.
Traceback (most recent call last):
  File "<REDACTED>\site-packages\azure\servicebus\aio\_base_handler_async.py", line 260, in _do_retryable_operation
    return await operation(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>\site-packages\azure\servicebus\aio\_servicebus_sender_async.py", line 239, in _send
    await self._amqp_transport.send_messages_async(
  File "<REDACTED>\site-packages\azure\servicebus\aio\_transport\_pyamqp_transport_async.py", line 141, in send_messages_async
    await sender._open()
  File "<REDACTED>\site-packages\azure\servicebus\aio\_servicebus_sender_async.py", line 222, in _open
    while not await self._handler.client_ready_async():
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'client_ready_async'
Unexpected error occurred (AttributeError("'NoneType' object has no attribute 'client_ready_async'")). Handler shutting down.
Traceback (most recent call last):
  File "<REDACTED>\site-packages\azure\servicebus\aio\_base_handler_async.py", line 260, in _do_retryable_operation
    return await operation(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>\site-packages\azure\servicebus\aio\_servicebus_sender_async.py", line 239, in _send
    await self._amqp_transport.send_messages_async(
  File "<REDACTED>\site-packages\azure\servicebus\aio\_transport\_pyamqp_transport_async.py", line 141, in send_messages_async
    await sender._open()
  File "<REDACTED>\site-packages\azure\servicebus\aio\_servicebus_sender_async.py", line 222, in _open
    while not await self._handler.client_ready_async():
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'client_ready_async'
Unexpected error occurred (AttributeError("'NoneType' object has no attribute 'client_ready_async'")). Handler shutting down.
Traceback (most recent call last):
  File "<REDACTED>\site-packages\azure\servicebus\aio\_base_handler_async.py", line 260, in _do_retryable_operation
    return await operation(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>\site-packages\azure\servicebus\aio\_servicebus_sender_async.py", line 239, in _send
    await self._amqp_transport.send_messages_async(
  File "<REDACTED>\site-packages\azure\servicebus\aio\_transport\_pyamqp_transport_async.py", line 141, in send_messages_async
    await sender._open()
  File "<REDACTED>\site-packages\azure\servicebus\aio\_servicebus_sender_async.py", line 222, in _open
    while not await self._handler.client_ready_async():
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'client_ready_async'
Traceback (most recent call last):
  File "<REDACTED>\site-packages\azure\servicebus\aio\_base_handler_async.py", line 260, in _do_retryable_operation
    return await operation(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>\site-packages\azure\servicebus\aio\_servicebus_sender_async.py", line 239, in _send
    await self._amqp_transport.send_messages_async(
  File "<REDACTED>\site-packages\azure\servicebus\aio\_transport\_pyamqp_transport_async.py", line 141, in send_messages_async
    await sender._open()
  File "<REDACTED>\site-packages\azure\servicebus\aio\_servicebus_sender_async.py", line 222, in _open
    while not await self._handler.client_ready_async():
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>\site-packages\azure\servicebus\_pyamqp\aio\_client_async.py", line 329, in client_ready_async
    if not await self._client_ready_async():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>\site-packages\azure\servicebus\_pyamqp\aio\_client_async.py", line 510, in _client_ready_async
    self._link = self._session.create_sender_link(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'create_sender_link'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\I0892\source\coode-test\test_servicebus_gather.py", line 17, in <module>
    asyncio.run(main())
  File "<REDACTED>\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "<REDACTED>\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\Users\I0892\source\coode-test\test_servicebus_gather.py", line 13, in main
    await asyncio.gather(*(sender.send_messages(ServiceBusMessage("hello")) for _ in range(10)))
  File "<REDACTED>\site-packages\azure\servicebus\aio\_servicebus_sender_async.py", line 447, in send_messages
    await self._do_retryable_operation(
  File "<REDACTED>\site-packages\azure\servicebus\aio\_base_handler_async.py", line 267, in _do_retryable_operation
    last_exception = await self._handle_exception(exception)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>\site-packages\azure\servicebus\aio\_base_handler_async.py", line 208, in _handle_exception
    raise error
azure.servicebus.exceptions.ServiceBusError: Handler failed: 'NoneType' object has no attribute 'create_sender_link'.
```

**Expected behavior**
Ten messages sent to the queue and no errors.

**Additional context**
Note that this is just a minimal example to reproduce the issue. The real application where I needed to make concurrent requests with asyncio.gather() was an RPC application with session_id.

I have also noticed that if I use an asyncio.Lock() to prevent the sender.send_messages() requests running concurrently then the problem is not exhibited.

**Comment by iangoldby** [comment]
As a side-note, if you are not _supposed_ to be able to use the same ServiceBusSender concurrently in different tasks then it would be helpful if that were made unmissable in the documentation.

**Comment by iangoldby** [comment]
@kashifkhan Thanks for your response and I'm glad you agree that the documentation would benefit from improving. In particular, I think it is fair to say that most developers would not expect a warning about thread safety also to apply to async code. A lot of developers would regard the async world as an escape from thread concurrency problems :-).

**Comment by cabal-daniel** [comment]
Also dealing with this issue but not with the aio implementation. If the non-aio `send_messages` are called from async UWSGI server, it seems to cause this exact exception as well.

**Comment by cabal-daniel** [comment]
@kashifkhan can we re-open this issue? https://github.com/Azure/azure-sdk-for-python/issues/32967 I think it was improperly closed

**Comment by cabal-daniel** [comment]
It's been six months and this still hasn't been resolved. I can't believe that a pub-sub message queue library doesn't have basic thread safety. This is a service that charges orgs $10k/month.

**Comment by MihailV1989** [comment]
The proper doc page that has to be fixed is here:
https://learn.microsoft.com/en-us/python/api/overview/azure/servicebus-readme?view=azure-python#thread-safety

And more important - "thread-safe" is incorrect. Actually it is not even "Coroutine-Safe", see terminology explanation here:
https://superfastpython.com/asyncio-coroutine-safe/

Also this doc page has to be corrected as well, as it recommends using singleton for service bus messaging, but without warning, that in Python you have use asyncio.Lock():
https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements?tabs=net-standard-sdk-2#reusing-factories-and-clients

**Comment by EldertGrootenboer** [comment]
Confirming this is by design: the async Service Bus sender and receiver aren't coroutine-safe, so sharing one sender across concurrent tasks (the `asyncio.gather` pattern here) is an unsupported scenario. Wrapping the sender in an `asyncio.Lock`, as you found, is the right approach. A sender per task also works.

You were right that the thread-safety note wasn't obvious for async code. We've since made it explicit:
- The [Python README thread-safety section](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/servicebus/azure-servicebus#thread-safety) now covers coroutine-safety and includes an `asyncio.Lock` example.
- The [performance guidance](https://learn.microsoft.com/azure/service-bus-messaging/service-bus-performance-improvements#reusing-factories-and-clients) now calls out that the Python client needs locks where the other SDKs don't.

Closing this out. Reopen if anything's still unclear.

**Comment by iangoldby** [comment]
I do wish that in the README the heading "Thread safety" had been amended to "Thread _and coroutine_ safety" for the benefit of developers who might quickly scan the headings and not necessarily read the detail. But a welcome improvement nevertheless. Thanks for the updates.
