### ISSUE TITLE
`JSONDecodeError: Unterminated string` when handling response from paginated endpoint

### ISSUE THREAD

**Issue by ntabris** [Azure/azure-sdk-for-python#36496]
- **Package Name**: azure-core
- **Package Version**: 1.29.6
- **Operating System**: Linux
- **Python Version**: 3.11

**Describe the bug**

Based on the traceback I suspect that the pagination is trying to decode JSON for each page (of the text results), rather than concating all the text and then decoding as JSON.

Our code (in `/usr/src/app/declarative/backend_interface/azure`) is doing this:

```python
    vms = compute_client.virtual_machines.list(
        rg_name,
        filter=vmss_filter,
        expand="instanceView",
    )
    return list(vms)  # in traceback below, this is line 261, in get_vmss_vms
```

Here's the traceback we get:

```python
Traceback (most recent call last):
  File "/opt/coiled/env/lib/python3.11/site-packages/azure/core/pipeline/policies/_universal.py", line 614, in deserialize_from_text
    return json.loads(data_as_str)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/coiled/env/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/coiled/env/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/coiled/env/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Unterminated string starting at: line 523 column 45 (char 23815)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/app/declarative/backend_interface/azure/describe_instances_state.py", line 67, in describe_instance_state
    instance_results = get_vmss_vms(
                       ^^^^^^^^^^^^^
  File "/usr/src/app/declarative/backend_interface/azure/start_instances.py", line 261, in get_vmss_vms
    return list(vms)
           ^^^^^^^^^
  File "/opt/coiled/env/lib/python3.11/site-packages/azure/core/paging.py", line 123, in __next__
    return next(self._page_iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/coiled/env/lib/python3.11/site-packages/azure/core/paging.py", line 75, in __next__
    self._response = self._get_next(self.continuation_token)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/coiled/env/lib/python3.11/site-packages/azure/mgmt/compute/v2024_03_01/operations/_operations.py", line 16115, in get_next
    pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/coiled/env/lib/python3.11/site-packages/azure/core/pipeline/_base.py", line 230, in run
    return first_node.send(pipeline_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/coiled/env/lib/python3.11/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/coiled/env/lib/python3.11/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/coiled/env/lib/python3.11/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 1 more time]
  File "/opt/coiled/env/lib/python3.11/site-packages/azure/core/pipeline/_base.py", line 91, in send
    _await_result(self._policy.on_response, request, response)
  File "/opt/coiled/env/lib/python3.11/site-packages/azure/core/pipeline/_tools.py", line 49, in await_result
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/coiled/env/lib/python3.11/site-packages/azure/core/pipeline/policies/_universal.py", line 719, in on_response
    response.context[self.CONTEXT_NAME] = self.deserialize_from_http_generics(
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/coiled/env/lib/python3.11/site-packages/azure/core/pipeline/policies/_universal.py", line 686, in deserialize_from_http_generics
    return cls.deserialize_from_text(response.text(encoding), mime_type, response=response)
```

**To Reproduce**

I think this is caused by `compute_client.virtual_machines.list` with a very large response, in our case, lots of VMs and `expand="instanceView"`.

**Comment by pvaneck** [comment]
Hey, thanks for the feedback. I'm wondering if something is erroneous with the response being sent to core. I can't tell from the stack trace, but Is `azure.core.exceptions.DecodeError` ultimately being raised? That error has the response attached to it, and inspecting this might help us determine what's causing the issue.

**Comment by ntabris** [comment]
Unfortunately I haven't reproduced this myself locally and what I have in our logs is truncated.

**Comment by xiangyan99** [comment]
Thanks for the information.

I am closing the issue and please feel free to open a new one if it repros again.
