### ISSUE TITLE
Engine error while executing route request: MAP_MATCHING_FAILURE: Origin (11.4374, 49.3405)

### ISSUE THREAD

**Issue by heiko86** [Azure/azure-sdk-for-python#36530]
- **Package Name**: azure-maps-route
- **Package Version**: 1.0.0b1
- **Operating System**: MacOS 14.5
- **Python Version**: 3.11

**Describe the bug**
When running the code the error message mentioned above in the title appears.
The Code:
```
from azure.core.credentials import AzureKeyCredential
from azure.maps.route import MapsRouteClient
import os

credential = AzureKeyCredential(os.environ.get("AZURE_SUBSCRIPTION_KEY"))

route_client = MapsRouteClient(
    credential=credential,
)

def main():
    request_obj = {
        "origins": {
            "type": "MultiPoint",
            "coordinates": [
                [49.340518951416016, 11.437410354614258]
                # [
                #     4.85106,
                #     52.36006
                # ],
                # [
                #     4.85056,
                #     52.36187
                # ]
            ]
        },
        "destinations": {
            "type": "MultiPoint",
            "coordinates": [
                [49.51652526855469, 11.435355186462402]
                # [
                #     4.85003,
                #     52.36241
                # ],
                # [
                #     13.42937,
                #     52.50931
                # ]
            ]
        }
    }

    result = route_client.get_route_matrix(query=request_obj)

    print("Get Route Matrix with given request object:")
    print(result.matrix)
    for i in result.matrix:
        for j in i:
            print(j.as_dict())
```

Run the code above and the error appears. If you replace the coordinates with the coordinates in the comments the code works.

**Error**
```
Traceback (most recent call last):
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1433, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1180, in rest_key_extractor
    return working_data.get(key)
           ^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1608, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1636, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1636, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1621, in deserialize_data
    return self._deserialize(obj_type, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1444, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc["type"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1621, in deserialize_data
    return self._deserialize(obj_type, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1448, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/core/exceptions.py", line 100, in raise_with_traceback
    raise error.with_traceback(exc_traceback)  # pylint: disable=raise-missing-from
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1433, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1180, in rest_key_extractor
    return working_data.get(key)
           ^^^^^^^^^^^^^^^^
azure.core.exceptions.DeserializationError: (", AttributeError: 'str' object has no attribute 'get'", 'Unable to deserialize to object: type', AttributeError("'str' object has no attribute 'get'"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1608, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1636, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1636, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1619, in deserialize_data
    raise_with_traceback(DeserializationError, msg, err)
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/core/exceptions.py", line 100, in raise_with_traceback
    raise error.with_traceback(exc_traceback)  # pylint: disable=raise-missing-from
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1608, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1636, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1636, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1621, in deserialize_data
    return self._deserialize(obj_type, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1444, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc["type"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1621, in deserialize_data
    return self._deserialize(obj_type, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1448, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/core/exceptions.py", line 100, in raise_with_traceback
    raise error.with_traceback(exc_traceback)  # pylint: disable=raise-missing-from
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1433, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1180, in rest_key_extractor
    return working_data.get(key)
           ^^^^^^^^^^^^^^^^
azure.core.exceptions.DeserializationError: (', DeserializationError: (", AttributeError: \'str\' object has no attribute \'get\'", \'Unable to deserialize to object: type\', AttributeError("\'str\' object has no attribute \'get\'"))', "Unable to deserialize response data. Data: [{'statusCode': 400, 'response': 'Engine error while executing route request: MAP_MATCHING_FAILURE: Origin (11.4374, 49.3405)', 'detailedError': {'message': 'Engine error while executing route request: MAP_MATCHING_FAILURE: Origin (11.4374, 49.3405)', 'code': 'MAP_MATCHING_FAILURE'}}], [RouteMatrix]", DeserializationError(", AttributeError: 'str' object has no attribute 'get'", 'Unable to deserialize to object: type', AttributeError("'str' object has no attribute 'get'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/name/gits/betterlogistix/azure_auth.py", line 55, in <module>
    main()
  File "/Users/name/gits/betterlogistix/azure_auth.py", line 43, in main
    result = route_client.get_route_matrix(query=request_obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 94, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_route_client.py", line 682, in get_route_matrix
    return self._route_client.request_route_matrix_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 94, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/operations/_operations.py", line 2810, in request_route_matrix_sync
    deserialized = self._deserialize("RouteMatrixResult", pipeline_response)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1378, in __call__
    return self._deserialize(target_obj, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1444, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc["type"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1619, in deserialize_data
    raise_with_traceback(DeserializationError, msg, err)
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/core/exceptions.py", line 100, in raise_with_traceback
    raise error.with_traceback(exc_traceback)  # pylint: disable=raise-missing-from
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1608, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1636, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1636, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1619, in deserialize_data
    raise_with_traceback(DeserializationError, msg, err)
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/core/exceptions.py", line 100, in raise_with_traceback
    raise error.with_traceback(exc_traceback)  # pylint: disable=raise-missing-from
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1608, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1636, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1636, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1621, in deserialize_data
    return self._deserialize(obj_type, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1444, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc["type"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1621, in deserialize_data
    return self._deserialize(obj_type, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1448, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/core/exceptions.py", line 100, in raise_with_traceback
    raise error.with_traceback(exc_traceback)  # pylint: disable=raise-missing-from
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1433, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/betterlogistix/lib/python3.11/site-packages/azure/maps/route/_generated/_serialization.py", line 1180, in rest_key_extractor
    return working_data.get(key)
           ^^^^^^^^^^^^^^^^
azure.core.exceptions.DeserializationError: (', DeserializationError: (\', DeserializationError: (", AttributeError: \\\'str\\\' object has no attribute \\\'get\\\'", \\\'Unable to deserialize to object: type\\\', AttributeError("\\\'str\\\' object has no attribute \\\'get\\\'"))\', "Unable to deserialize response data. Data: [{\'statusCode\': 400, \'response\': \'Engine error while executing route request: MAP_MATCHING_FAILURE: Origin (11.4374, 49.3405)\', \'detailedError\': {\'message\': \'Engine error while executing route request: MAP_MATCHING_FAILURE: Origin (11.4374, 49.3405)\', \'code\': \'MAP_MATCHING_FAILURE\'}}], [RouteMatrix]", DeserializationError(", AttributeError: \'str\' object has no attribute \'get\'", \'Unable to deserialize to object: type\', AttributeError("\'str\' object has no attribute \'get\'")))', "Unable to deserialize response data. Data: [[{'statusCode': 400, 'response': 'Engine error while executing route request: MAP_MATCHING_FAILURE: Origin (11.4374, 49.3405)', 'detailedError': {'message': 'Engine error while executing route request: MAP_MATCHING_FAILURE: Origin (11.4374, 49.3405)', 'code': 'MAP_MATCHING_FAILURE'}}]], [[RouteMatrix]]", DeserializationError(', DeserializationError: (", AttributeError: \'str\' object has no attribute \'get\'", \'Unable to deserialize to object: type\', AttributeError("\'str\' object has no attribute \'get\'"))', "Unable to deserialize response data. Data: [{'statusCode': 400, 'response': 'Engine error while executing route request: MAP_MATCHING_FAILURE: Origin (11.4374, 49.3405)', 'detailedError': {'message': 'Engine error while executing route request: MAP_MATCHING_FAILURE: Origin (11.4374, 49.3405)', 'code': 'MAP_MATCHING_FAILURE'}}], [RouteMatrix]", DeserializationError(", AttributeError: 'str' object has no attribute 'get'", 'Unable to deserialize to object: type', AttributeError("'str' object has no attribute 'get'"))))

```

**Comment by pvaneck** [comment]
Thanks for the feedback, I'll tag some folks who can hopefully help out.

**Comment by dubiety** [comment]
Hi @heiko86 , thank you for reporting this issue. We're looking into the issue and will get to you soon!

**Comment by dubiety** [comment]
Hi @heiko86 ,
The coordinates should be `[longititude, latitude]`, if you swap the 2 numbers, the code can run as expected:
```
request_obj = {
    "origins": {
        "type": "MultiPoint",
        "coordinates": [
            [11.437410354614258, 49.340518951416016]
        ]
    },
    "destinations": {
        "type": "MultiPoint",
        "coordinates": [
            [11.435355186462402, 49.51652526855469]
        ]
    }
}
```

**Comment by heiko86** [comment]
Hello @dubiety ,

thank you for your help. Honestly, I could swear that I've rechecked the correct order at least twice... 
Sorry and thanks again !
