### ISSUE TITLE
azure.core.exceptions.SerializationError: Unable to serialize value: <azure.search.documents._generated.models._models_py3.VectorizedQuery object at 0x0000019AD37731D0> as type: '[VectorQuery]'.

### ISSUE THREAD

**Issue by BIGdeadLock** [Azure/azure-sdk-for-python#36633]
- **Package Name**: azure-search-documents
- **Package Version**: 11.4.0
- **Operating System**: WIndows
- **Python Version**:  #.12

**Describe the bug**
I'm getting an error when using the vector search:

Traceback (most recent call last):
  File "C:\Users\eden.yavin\AppData\Local\JetBrains\PyCharm 2024.1.4\plugins\python\helpers-pro\pydevd_asyncio\pydevd_asyncio_utils.py", line 117, in _exec_async_code
    result = func()
             ^^^^^^
  File "<input>", line 1, in <module>
  File "C:\Users\eden.yavin\Projects\llm-service\venv\Lib\site-packages\azure\search\documents\_paging.py", line 54, in __next__
    return next(self._page_iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eden.yavin\Projects\llm-service\venv\Lib\site-packages\azure\core\paging.py", line 75, in __next__
    self._response = self._get_next(self.continuation_token)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eden.yavin\Projects\llm-service\venv\Lib\site-packages\azure\search\documents\_paging.py", line 124, in _get_next_cb
    return self._client.documents.search_post(search_request=self._initial_query.request, **self._kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eden.yavin\Projects\llm-service\venv\Lib\site-packages\azure\core\tracing\decorator.py", line 94, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eden.yavin\Projects\llm-service\venv\Lib\site-packages\azure\search\documents\_generated\operations\_documents_operations.py", line 728, in search_post
    _json = self._serialize.body(search_request, "SearchRequest")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eden.yavin\Projects\llm-service\venv\Lib\site-packages\azure\search\documents\_generated\_serialization.py", line 715, in body
    return self._serialize(data, data_type, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eden.yavin\Projects\llm-service\venv\Lib\site-packages\azure\search\documents\_generated\_serialization.py", line 585, in _serialize
    return self.serialize_data(target_obj, data_type, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eden.yavin\Projects\llm-service\venv\Lib\site-packages\azure\search\documents\_generated\_serialization.py", line 831, in serialize_data
    return self._serialize(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eden.yavin\Projects\llm-service\venv\Lib\site-packages\azure\search\documents\_generated\_serialization.py", line 622, in _serialize
    new_attr = self.serialize_data(orig_attr, attr_desc["type"], **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eden.yavin\Projects\llm-service\venv\Lib\site-packages\azure\search\documents\_generated\_serialization.py", line 829, in serialize_data
    raise SerializationError(msg.format(data, data_type)) from err
azure.core.exceptions.SerializationError: Unable to serialize value: <azure.search.documents._generated.models._models_py3.VectorizedQuery object at 0x0000019AD37731D0> as type: '[VectorQuery]'.

**Additional context**

When I'm using the Async version this error is not raised (other error is raised which does not seem connected to it - "None type object has no attribute update")

Code snippet:

```

def _embedding_query(self, query: str) -> VectorizedQuery:
    return VectorizedQuery(vector=self.embedding_model.embed_query(query), k_nearest_neighbors=3,
                           fields=self.vector_field_name)



vector_query = ([self._embedding_query(query)] if (self.search_type != SPARSE_RETRIEVE_METHOD_TOKEN)
                else None
                )
search_text = (query
               if self.search_type != DENSE_RETRIEVE_METHOD_TOKEN  # For vector only search, only the embedding is needed
               else None)

 search_client = SearchClient(...)


  result = search_client.search(
        search_text=search_text,
        select=select_fields,
        vector_queries=vector_query,
        top=self.k,
        filter=self.metadata.get(FILTER_METADATA_FIELD, None) if self.metadata else None
    )

docs = [doc for doc in results]

```

**Comment by kashifkhan** [comment]
Thank you for the feedback @BIGdeadLock . We will investigate and get back to you asap.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

We fixed some serialization issues in last release.

Did you have a chance to try 11.5.0?

**Comment by BIGdeadLock** [comment]
@xiangyan99 I uninstall 11.4.0 version and reinstall it with version 11.5.0 as you mention. Still getting an issue due it is a different one now:

("'NoneType' object has no attribute 'update'",)

I'm getting it on the line:

`docs = [doc async for doc in result]`


For more contexts:


```
        async with search_client:
            result = await search_client.search(
                search_text=search_text,
                select=select_fields,
                vector_queries=vector_query,
                top=self.k,
                filter=self.metadata.get(FILTER_METADATA_FIELD, None) if self.metadata else None
            )

            docs = [doc async for doc in result]
```
