### ISSUE TITLE
Azure CLI identity via DefaultAzureCredential doesn't work

### ISSUE THREAD

**Issue by CaishenNefri** [Azure/azure-sdk-for-python#36777]
- **Package Name**: azure-identity
- **Package Version**: 1.17.1
- **Operating System**: 20.04.6 LTS (Focal Fossa)
- **Python Version**:  3.11.9

**Describe the bug**
I am trying to get token credential via DefaultAzurecredential. When I am calling it via 
```bash
token_credential = DefaultAzureCredential(exclude_environment_credential=True,  exclude_managed_identity_credential=True, exclude_cli_credential=False)`
I am getting following error:
`Traceback (most recent call last):
  File "main.py", line 16, in <module>
    token_credential = DefaultAzureCredential(exclude_environment_credential=True,  exclude_managed_identity_credential=True, exclude_cli_credential=False)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/azure/identity/_credentials/default.py", line 92, in __init__
    super(DefaultAzureCredential, self).__init__(*credentials)
  File "/usr/lib/python3/dist-packages/azure/identity/_credentials/chained.py", line 44, in __init__
    raise ValueError("at least one credential is required")
ValueError: at least one credential is required
```

**To Reproduce**
Create main.py file. Insert following code and try to run it `python3.11 main.py`
```python
from azure.identity import DefaultAzureCredential
token_credential = DefaultAzureCredential(exclude_environment_credential=True,  exclude_managed_identity_credential=True, exclude_cli_credential=False)
```

**Expected behavior**
Package should be able to authenticate via active Azure CLI session.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Unfortunately, I cannot repro the issue.

Have you tried creating a new virtual environment and install azure-identity?

**Comment by CaishenNefri** [comment]
You are right. Sorry for such a nooby problem.
