### ISSUE TITLE
What are the best practices for instantiating SearchClient? 

### ISSUE THREAD

**Issue by abdomohamed** [Azure/azure-sdk-for-python#36821]
### Type of issue

Other (describe below)

### Description

I want to get some guidance on how to manage the SearchClient in an API application? For e.g:

- What should be the life-cycle of the SearchClient?
- Is it thread-safe? Can it be shared a cross different requests? 
- Is it a heavy object, that needs to be instantiated once at the startup of the application? 

Please don't hesitate to share any docs around the topics. 

### Page URL

None

### Content source URL

None

### Document Version Independent Id

None

### Article author

None

**Comment by kashifkhan** [comment]
Thanks @abdomohamed, my colleague on the search sdk will get back to you.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

SearchClient is nothing special. You can manage its lifecycle like other types.

It is thread safe. Depends on your design, you can share the SearchClient  instance or share the transport in the instance. You can get more details in https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/samples/example_shared_transport.py.

Sharing the object or not depends on your scenario and your performance goals.

Thanks.

**Comment by abdomohamed** [comment]
Thanks for sharing the above examples. Really helpful. 

I’ve more questions to this:
- Is the http connection pooling enabled by default? If yes, how many connection are allocated at the initiation of the object. 
- I’m getting the below exception at the moment, I was trying to understand what could be the cause of it:
 
Stack trace:
  Traceback (most recent call last):   File "/opt/python/3.11.8/lib/python3.11/site-packages/urllib3/connectionpool.py", line 536, in _make_request     response = conn.getresponse()                ^^^^^^^^^^^^^^^^^^   File "/opt/python/3.11.8/lib/python3.11/site-packages/urllib3/connection.py", line 464, in getresponse     httplib_response = super().getresponse()                        ^^^^^^^^^^^^^^^^^^^^^   File "/opt/python/3.11.8/lib/python3.11/http/client.py", line 1390, in getresponse     response.begin()   File "/opt/python/3.11.8/lib/python3.11/http/client.py", line 325, in begin     version, status, reason = self._read_status()                               ^^^^^^^^^^^^^^^^^^^   File "/opt/python/3.11.8/lib/python3.11/http/client.py", line 286, in _read_status     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/opt/python/3.11.8/lib/python3.11/socket.py", line 706, in readinto     return self._sock.recv_into(b)            ^^^^^^^^^^^^^^^^^^^^^^^   File "/opt/python/3.11.8/lib/python3.11/ssl.py", line 1314, in recv_into     return self.read(nbytes, buffer)            ^^^^^^^^^^^^^^^^^^^^^^^^^   File "/opt/python/3.11.8/lib/python3.11/ssl.py", line 1166, in read     return self._sslobj.read(len, buffer)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TimeoutError: The read operation timed out
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):   File "/opt/python/3.11.8/lib/python3.11/site-packages/requests/adapters.py", line 667, in send     resp = conn.urlopen(            ^^^^^^^^^^^^^   File "/opt/python/3.11.8/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen     retries = retries.increment(               ^^^^^^^^^^^^^^^^^^   File "/opt/python/3.11.8/lib/python3.11/site-packages/urllib3/util/retry.py", line 449, in increment     raise reraise(type(error), error, _stacktrace)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/opt/python/3.11.8/lib/python3.11/site-packages/urllib3/util/util.py", line 39, in reraise     raise value   File "/opt/python/3.11.8/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen     response = self._make_request(                ^^^^^^^^^^^^^^^^^^^   File "/opt/python/3.11.8/lib/python3.11/site-packages/urllib3/connectionpool.py", line 538, in _make_request     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)   File "/opt/python/3.11.8/lib/python3.11/site-packages/urllib3/connectionpool.py", line 369, in _raise_timeout     raise ReadTimeoutError( urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='tcp0043aedcmluc00kdtcss.search.windows.net', port=443): Read timed out. (read timeout=300)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):   File "/opt/python/3.11.8/lib/python3.11/site-packages/opentelemetry/trace/__init__.py", line 570, in use_span     yield span   File "/opt/python/3.11.8/lib/python3.11/site-packages/opentelemetry/sdk/trace/__init__.py", line 1091, in start_as_current_span     yield span   File "/opt/python/3.11.8/lib/python3.11/site-packages/opentelemetry/instrumentation/requests/__init__.py", line 311, in instrumented_send     raise exception.with_traceback(exception.__traceback__)   File "/opt/python/3.11.8/lib/python3.11/site-packages/opentelemetry/instrumentation/requests/__init__.py", line 225, in instrumented_send     result = wrapped_send(              ^^^^^^^^^^^^^   File "/opt/python/3.11.8/lib/python3.11/site-packages/requests/sessions.py", line 703, in send     r = adapter.send(request, **kwargs)         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/opt/python/3.11.8/lib/python3.11/site-packages/requests/adapters.py", line 713, in send     raise ReadTimeout(e, request=request) requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='tcp0043aedcmluc00kdtcss.search.windows.net', port=443): Read timed out. (read timeout=300)

**Comment by xiangyan99** [comment]
Seems like you use sync client. Underneath, we use requests library.

Requests library enables connection pooling by default and the default count is 10.

Per the error message you shared, looks like there are some networking issues. Your app failed to read from the server.
