### ISSUE TITLE
Unable to archive a job with version 1.19.0 of azure-ai-ml

### ISSUE THREAD

**Issue by MrKriss** [Azure/azure-sdk-for-python#36905]
- **Package Name**:  azure-ai-ml
- **Package Version**: 1.19.0
- **Operating System**: Ubuntu (via WSL)
- **Python Version**: 3.11

**Describe the bug**
Unable to archive a job with version 1.19.0 of azure-ai-ml. Upon calling the `MlClient.jobs.archive()` instance method, a client side REST request validation error is thrown. From the traceback, it seems like an internal field: `queueSettings.jobTier` is not one of the allowed values: Spot,Basic,Standard,Premium.

Downgrading to azure-ai-ml 1.18.0 fixed this issue. 

**To Reproduce**
1. Train a model on Azure ML
2. Get the Job with: `model = mlclient.models.get(name=recipe_internal_name, version=model_aml_version)`
3. Attempt to archive the corresponding job that trained the model with: `mlclient.jobs.archive(model.job_name)`

**Expected behavior**
The job that trained the model is archived.

**Screenshots**
Traceback of the error is given below:
```
Traceback (most recent call last):
  File "/opt/python/packages/mlops/flows/flows/delete_model.py", line 43, in delete_model_aml_metadata
    mlclient.jobs.archive(model.job_name)
  File "/opt/python/packages/azure/core/tracing/decorator.py", line 94, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/python/packages/azure/ai/ml/_telemetry/activity.py", line 372, in wrapper
    return_value = f(*args, **kwargs)
  File "/opt/python/packages/azure/ai/ml/operations/_job_operations.py", line 771, in archive
    self._archive_or_restore(name=name, is_archived=True)
  File "/opt/python/packages/azure/ai/ml/operations/_job_operations.py", line 750, in _archive_or_restore
    self._create_or_update_with_different_version_api(rest_job_resource=job_object)
  File "/opt/python/packages/azure/ai/ml/operations/_job_operations.py", line 732, in _create_or_update_with_different_version_api
    result = service_client_operation.create_or_update(
  File "/opt/python/packages/azure/core/tracing/decorator.py", line 94, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/python/packages/azure/ai/ml/_restclient/v2023_04_01_preview/operations/_jobs_operations.py", line 760, in create_or_update
    raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (UserError) Request is invalid and/or missing fields.
Code: UserError
Message: Request is invalid and/or missing fields.
Exception Details:	(RequestInvalid) The value provided is not a valid enum value. Field: queueSettings.jobTier. Allowed values: Spot,Basic,Standard,Premium.
	Code: RequestInvalid
	Message: The value provided is not a valid enum value. Field: queueSettings.jobTier. Allowed values: Spot,Basic,Standard,Premium.
Additional Information:Type: ComponentName
Info: {
    "value": "managementfrontend"
}Type: Correlation
Info: {
    "value": {
        "operation": "88a2be1b576d68e2d7a8a235e0e2f6f7",
        "request": "001418328c627d30"
    }
}Type: Environment
Info: {
    "value": "westeurope"
}Type: Location
Info: {
    "value": "westeurope"
}Type: Time
Info: {
    "value": "2024-08-15T14:21:26.1645366+00:00"
}Type: InnerError
Info: {
    "value": {
        "code": "RequestInvalid",
        "innerError": null
    }
}Type: MessageFormat
Info: {
    "value": "Request is invalid and/or missing fields."
}
```

**Additional context**
From examining the traceback it seems to be using version `2023_04_01_preview` of the rest client in my case.

**Comment by MrKriss** [comment]
I just ran into this same error again using azure-ai-ml version 1.22.1.  There may have been a regression since the above changes, or those changes may not have fixed this issue originally.
