### ISSUE TITLE
Azure Service Bus Proxy Broken?

### ISSUE THREAD

**Issue by szklany** [Azure/azure-sdk-for-python#3692]
Hi,

i'm trying to use the Azure Service Bus SDK behind a Proxy, but no matter what i do i keep getting the exception below.

I know that I don't have any problems with my proxy service, since it works fine with other Azure services such as the Azure BlockBlobService.

I'm setting the proxy as follows
sb.set_proxy('corp.xxx', '8080', 'username', 'password')

But when I try to connect to the service i get this error.

Any help would be much appreciated.

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Program Files\Python37\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Program Files\Python37\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files\Python37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Program Files\Python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Python37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Python37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files\Python37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Program Files\Python37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\szklanym\git\converter-dsr-to-ulog\main.py", line 16, in parse_dsr
    send_to_sb(parser.device_id, parser.ulogs)
  File "C:\Users\szklanym\git\converter-dsr-to-ulog\main.py", line 45, in send_to_sb
    sb.send_ulog_batch(device_id, ulogs)
  File "C:\Program Files\Python37\lib\site-packages\draeger_ulog\azure.py", line 33, in send_ulog_batch
    self.create_topic(topic_name)
  File "C:\Program Files\Python37\lib\site-packages\azure\servicebus\servicebusservice.py", line 344, in create_topic
    self._perform_request(request)
  File "C:\Program Files\Python37\lib\site-packages\azure\servicebus\servicebusservice.py", line 1228, in _perform_request
    resp = self._filter(request)
  File "C:\Program Files\Python37\lib\site-packages\azure\servicebus\_http\httpclient.py", line 181, in perform_request
    self.send_request_body(connection, request.body)
  File "C:\Program Files\Python37\lib\site-packages\azure\servicebus\_http\httpclient.py", line 143, in send_request_body
    connection.send(request_body)
  File "C:\Program Files\Python37\lib\site-packages\azure\servicebus\_http\requestsclient.py", line 81, in send
    self.response = self.session.request(self.method, self.uri, data=request_body, headers=self.headers, timeout=self.timeout)
  File "C:\Program Files\Python37\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Python37\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\requests\adapters.py", line 507, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='ulogdispatcher.servicebus.windows.net', port=443): Max retries exceeded with url: /8400 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 authenticationrequired')))

**Comment by lmazuel** [comment]
@annatisch could AMQP help? Or do you know what's happening?

**Comment by annatisch** [comment]
Hi @szklany, @lmazuel 

Unfortunately this is not yet supported in the new preview SDK either, for two reasons:
- The HTTP control plane operation has not been changed - so the above error will still apply.
- For AMQP operations this is not supported until we have websocket support, which is open issue #4250.

Hopefully both of these will be resolved in the next preview release.

**Comment by BarakSilverfort** [comment]
Hey, @lmazuel, 
We are using version 0.2.11 of the service bus and we want to move to the AMQP implementation, but we need to use an http_proxy for all the operations, is this still an issue for version 0.50.2?

**Comment by yunhaoling** [comment]
Hello @szklany, @BarakSilverfort, apologize for the delayed response.

We will do a patch release for servicebus 0.50.2 which would bring in the amqp http proxy support.

Apart from that, we have released a brand-new version of servicebus -- [azure-servicebus 7.0.0b2](https://pypi.org/project/azure-servicebus/7.0.0b2/) which already integrates http proxy support. It would be great if you could take a try on our latest preview version which is of our efforts to create a  user friendly client library.
