### ISSUE TITLE
AuthorizationCodeCredential.get_token failed: Session.request() got an unexpected keyword argument 'client_secret'

### ISSUE THREAD

**Issue by guanteck** [Azure/azure-sdk-for-python#36942]
- **Package Name**:  azure-identity
- **Package Version**: 1.17.1
- **Operating System**: Linux
- **Python Version**:  3.10

**Describe the bug**
I'm establishing a connection using the GraphServiceClient from the msgraph sdk. After about an hour the client should automatically retrieve a new access token => it fails because AuthorizationCodeCredential.get_token has an unexpected keyword argument. The initial connection works and the app runs for an hour without any problems.

**To Reproduce**
1. Connect using GraphServiceClient (and, e.g., retrieve mails)
2. After about an hour, the error occurs.

**Additional context**
```python
AuthorizationCodeCredential.get_token failed: Session.request() got an unexpected keyword argument 'client_secret'
Job "fetch (trigger: interval[0:01:00], next run at: 2024-08-19 08:52:23 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/usr/src/app/app.py", line 23, in fetch 
    await graph.fetch()
  File "/usr/src/app/src/client/Graph.py", line 68, in fetch
    message_ids = await self.__get_message_ids(request_config=request_config_message_ids)
  File "/usr/src/app/src/client/Graph.py", line 217, in __get_message_ids
    message_ids = await self.graph_client.users.by_user_id(self.mailbox_id).mail_folders.by_mail_folder_id(self.inbox).messages.get(
  File "/usr/local/lib/python3.10/site-packages/msgraph/generated/users/item/mail_folders/item/messages/messages_request_builder.py", line 68, in get
    return await self.request_adapter.send_async(request_info, MessageCollectionResponse, error_mapping)
  File "/usr/local/lib/python3.10/site-packages/kiota_http/httpx_request_adapter.py", line 178, in send_async
    response = await self.get_http_response_message(request_info, parent_span)
  File "/usr/local/lib/python3.10/site-packages/kiota_http/httpx_request_adapter.py", line 523, in get_http_response_message
    await self._authentication_provider.authenticate_request(
  File "/usr/local/lib/python3.10/site-packages/kiota_abstractions/authentication/base_bearer_token_authentication_provider.py", line 50, in authenticate_request
    token = await self.access_token_provider.get_authorization_token(
  File "/usr/local/lib/python3.10/site-packages/kiota_authentication_azure/azure_identity_access_token_provider.py", line 103, in get_authorization_token
    result = self._credentials.get_token(*self._scopes, claims=decoded_claim)
  File "/usr/local/lib/python3.10/site-packages/azure/identity/_credentials/authorization_code.py", line 89, in get_token
    return super(AuthorizationCodeCredential, self).get_token(
  File "/usr/local/lib/python3.10/site-packages/azure/identity/_internal/get_token_mixin.py", line 93, in get_token
    token = self._request_token(
  File "/usr/local/lib/python3.10/site-packages/azure/identity/_credentials/authorization_code.py", line 107, in _request_token
    token = self._client.obtain_token_by_refresh_token(scopes, refresh_token["secret"], **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/identity/_internal/aad_client.py", line 51, in obtain_token_by_refresh_token
    return self._run_pipeline(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/identity/_internal/aad_client.py", line 73, in _run_pipeline
    response = self._pipeline.run(request, retry_on_methods=self._POST, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 229, in run
    return first_node.send(pipeline_request)
  File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/policies/_retry.py", line 532, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 118, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 355, in send
    response = self.session.request(  # type: ignore
TypeError: Session.request() got an unexpected keyword argument 'client_secret'
```

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you show some code snippet to show how you use the credential?

**Comment by guanteck** [comment]
First I retrieve the authorization_code using https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/authorize

Then I initialize the credential like so:
```python
self.credential = AuthorizationCodeCredential(tenant_id=tenant_id,
                                              client_id=client_id,
                                              authorization_code=authorization_code,
                                              redirect_uri=redirect_URI,
                                              client_secret=client_secret)
```


And the graph client:
```python
self.graph_client = GraphServiceClient(self.credential)
```

**Comment by xiangyan99** [comment]
Thanks for the information.

Could you tell me which library you used to import `GraphServiceClient`?

**Comment by guanteck** [comment]
I'm using msgraph from https://github.com/microsoftgraph/msgraph-sdk-python

```python
from msgraph import GraphServiceClient
```
