### ISSUE TITLE
cannot iterate over container registries

### ISSUE THREAD

**Issue by strimpak** [Azure/azure-sdk-for-python#3697]
>>> from azure.common.credentials import get_azure_cli_credentials
>>> from azure.mgmt.containerregistry import ContainerRegistryManagementClient

>>> creds=get_azure_cli_credentials(None, True)

>>> acrm = ContainerRegistryManagementClient(creds, 'xxxxxxxx')
>>> registries = acrm.registries.list()
>>> registries.next()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/msrest/paging.py", line 109, in __next__
    self.advance_page()
  File "/usr/local/lib/python2.7/site-packages/msrest/paging.py", line 95, in advance_page
    self._response = self._get_next(self.next_link)
  File "/usr/local/lib/python2.7/site-packages/azure/mgmt/containerregistry/operations/registries_operations.py", line 499, in internal_paging
    request, header_parameters, **operation_config)
  File "/usr/local/lib/python2.7/site-packages/msrest/service_client.py", line 187, in send
    session = self.creds.signed_session()
AttributeError: 'tuple' object has no attribute 'signed_session'

**Comment by lmazuel** [comment]
Hello,

get_azure_cli_credentials is returning a tuple credentials / default subscription ID. And since you put `True` as second parameter, there is actually a third element with the default tenant_id
https://docs.microsoft.com/en-us/python/api/azure-common/azure.common.credentials?view=azure-python#get-azure-cli-credentials

You could change to this:
```python
creds, _ =get_azure_cli_credentials(None, True)
```
or use the factory directly:
https://docs.microsoft.com/en-us/python/api/azure-common/azure.common.client_factory?view=azure-python#get-client-from-cli-profile
