### ISSUE TITLE
ClientAuthenticationError once Live Metrics is enabled in Azure Monitor OTEL

### ISSUE THREAD

**Issue by chrisjohnson00** [Azure/azure-sdk-for-python#37209]
- azure-monitor-opentelemetry
- 1.6.1
- Debian (python:3.12-slim container)
- 3.12

**Describe the bug**
In a pre-existing application, where I'm already using this package for tracing, I've attempted to onboard live metrics but get authentication issues.

```
    az_credential = az_identity.DefaultAzureCredential()

    configure_azure_monitor(credential=az_credential, enable_live_metrics=True)
```

Relevant env variables set:
`OTEL_SERVICE_NAME`
`APPLICATIONINSIGHTS_CONNECTION_STRING`

This is running in AKS, using a managed identity which is granted many roles, including `Monitoring Metrics Publisher`, scoped to my Application Insights instance.

In Application Insights I capture many of the same exceptions:

` Exception occurred while publishing live metrics. `

```
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/azure/monitor/opentelemetry/exporter/_quickpulse/_exporter.py", line 145, in export
    post_response = self._client.publish(  # type: ignore
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/azure/monitor/opentelemetry/exporter/_quickpulse/_generated/_operations/_operations.py", line 529, in publish
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/venv/lib/python3.12/site-packages/azure/core/exceptions.py", line 161, in map_error
    raise error
azure.core.exceptions.ClientAuthenticationError: Operation returned an invalid status 'Unauthorized'
Content: {"RequestId":"00000000-0000-0000-0000-000000000000","ResponseDateTime":"2024-09-04T22:42:28.2875874Z","Code":"InvalidOperation","Message":"The Agent/SDK does not have permissions to send telemetry to this resource.","Exception":""}

```

Interestingly enough, when I click on "Live metrics" in AI, I sometimes see my application listed in the roles, but upon selecting it, the graphs all stop reporting data.  I am able to see other applications, .net ones, in Live metrics.  Those applications are using a different managed identity, but shares the same `Monitoring Metrics Publisher` role assignment, also scoped to the same AI instance.

**To Reproduce**
1. Take a working application, add `enable_live_metrics=True` and see no Live metrics

**Expected behavior**
Live metrics to be collected ;)

**Comment by pvaneck** [comment]
Hey, @chrisjohnson00! In AKS environments, `DefaultAzureCredential` should automatically use [WorkloadIdentityCredential](https://learn.microsoft.com/en-us/python/api/azure-identity/azure.identity.workloadidentitycredential?view=azure-python) which relies on `AZURE_CLIENT_ID`, `AZURE_TENANT_ID`, and `AZURE_FEDERATED_TOKEN_FILE` env vars which are automatically set.

Are you able to check the value of the environment variable `AZURE_CLIENT_ID`  inside your AKS environment and ensure that the service principal that corresponds to that value has the "Monitoring Metrics Publisher" role assignment?

**Comment by chrisjohnson00** [comment]
> Hey, @chrisjohnson00! In AKS environments, `DefaultAzureCredential` should automatically use [WorkloadIdentityCredential](https://learn.microsoft.com/en-us/python/api/azure-identity/azure.identity.workloadidentitycredential?view=azure-python) which relies on `AZURE_CLIENT_ID`, `AZURE_TENANT_ID`, and `AZURE_FEDERATED_TOKEN_FILE` env vars which are automatically set.
> 
> Are you able to check the value of the environment variable `AZURE_CLIENT_ID` inside your AKS environment and ensure that the service principal that corresponds to that value has the "Monitoring Metrics Publisher" role assignment?

Yes, that is how it works.
Yes, it is working correct,y and the associated SP has the Monitoring Metrics Publisher role assigned.  As I mentioned in the original report, I get traces in Application Insights from this application already.  That is how I pulled the exception from the SDK's thread; my app doesn't crash.  It is just the live metrics that are not working.

**Comment by pvaneck** [comment]
@lzchen @jeremydvoss Any ideas what could be causing the publishing of live metrics to return unauthorized in this case?

**Comment by lzchen** [comment]
@chrisjohnson00 

Thanks for reporting this. Live metrics AAD auth should be available in the next release (some time next week).

**Comment by chrisjohnson00** [comment]
Thanks, please keep this open until it is deployed and can be verified

**Comment by lzchen** [comment]
@chrisjohnson00 

Could you try installing the latest [azure-monitor-opentelemetry-exporter](https://pypi.org/project/azure-monitor-opentelemetry-exporter/1.0.0b29/) with your project? We have implemented AAD for live metrics in that version. You shouldn't have to change any code.

**Comment by chrisjohnson00** [comment]
![image](https://github.com/user-attachments/assets/61ee14f6-0585-4022-8c80-08762ef20253)

Looks to be working!  Thanks!!
