### ISSUE TITLE
Azure service bus message renew_message_lock not working

### ISSUE THREAD

**Issue by ShirishGajera** [Azure/azure-sdk-for-python#37245]
- **Package Name**: 
- azure-servicebus
- **Package Version**: 
- 7.12.2
- **Operating System**:
- Ubuntu
- **Python Version**: 
- 3.8

**Describe the bug**
I have a python service which uses azure service bus topic for sending and receiving messages. I am using azure-servicebus==7.12.2.

Max timeout I can set on azure portal is 5 minute, but the processing for the message on topic take around 60 minutes. So, I am using renew_message_lock to renew the message lock time

Here is my code
```
async def receive_messages_from_topic(
    servicebus_client: ServiceBusClient,
    topic_name: str,
    executor: Any,  # type: ignore
):
    async with servicebus_client:
        # renewer = AutoLockRenewer(max_lock_renewal_duration=3600)
        async with servicebus_client.get_subscription_receiver(
            topic_name=topic_name,
            subscription_name=SUBSCRIPTION_NAME,
        ) as receiver:
            logger.info(f"Listening to topic: {topic_name} for subscription: {SUBSCRIPTION_NAME}")
            while True:
                try:
                    messages = await receiver.receive_messages()
                    for message in messages:
                        _ = await receiver.renew_message_lock(message=message, timeout=21600)

                    for message in messages:
                        # Process the message
                        logger.info(
                            f"Received message from topic: {topic_name}, msg: {str(message)} message.locked_until_utc: {message.locked_until_utc} utc_now: {datetime.datetime.now(datetime.timezone.utc)}"
                        )

                        with make_temp_directory() as temp_dir:
                            try:
                                bytes_str = str(message)
                                bytes = ast.literal_eval(bytes_str)
                                executor(topic_name, bytes, temp_dir)
                                await receiver.complete_message(message)
                            except Exception as e:
                                logger.exception(
                                    f"Error executing job for topic: {topic_name} message: {message.message_id}, {e}"
                                )
                                await receiver.dead_letter_message(message)

                    if len(messages) == 0:
                        # Small sleep to avoid busy looping
                        await asyncio.sleep(60)
                except Exception as e:
                    logger.exception(f"Error processing message for topic: {topic_name}, {e}")
```

Log
```
2024-09-07 13:39:16,292 - __main__ - INFO - Received message from topic: dataset_deploy, msg: b'\n\x08foo\x12\x05fig' message.locked_until_utc: 2024-09-07 20:44:16.268000+00:00 utc_now: 2024-09-07 20:39:16.292080+00:00
```

executor(topic_name, bytes, temp_dir) will complete the processing in 40 minutes, no issues or errors. But, when I try to mark the message as complete in the above loop it will throw below exception

```
Traceback (most recent call last):
  File "/home/vscode/.cache/bazel/_bazel_vscode/d9fd8dd9485b3d1d1994c3846baefa35/execroot/_main/bazel-out/k8-opt-release/bin/tools/service_bus/run/run.runfiles/_main/tools/service_bus/run/run.py", line 72, in receive_messages_from_topic
    await receiver.complete_message(message)
  File "/home/vscode/.local/lib/python3.10/site-packages/azure/servicebus/aio/_servicebus_receiver_async.py", line 852, in complete_message
    await self._settle_message_with_retry(message, MESSAGE_COMPLETE)
  File "/home/vscode/.local/lib/python3.10/site-packages/azure/servicebus/aio/_servicebus_receiver_async.py", line 494, in _settle_message_with_retry
    raise MessageLockLostError(
azure.servicebus.exceptions.MessageLockLostError: The lock on the message lock has expired.
```

**What I tried**

- I tried setting AutoLockRenewer on message and session still same result. https://azuresdkdocs.blob.core.windows.net/$web/python/azure-servicebus/latest/index.html#automatically-renew-message-or-session-locks

Not sure if I missing something or something is wrong with my implementation

**To Reproduce**
```
async def receive_messages_from_topic(
    servicebus_client: ServiceBusClient,
    topic_name: str,
    executor: Any,  # type: ignore
):
    async with servicebus_client:
        # renewer = AutoLockRenewer(max_lock_renewal_duration=3600)
        async with servicebus_client.get_subscription_receiver(
            topic_name=topic_name,
            subscription_name=SUBSCRIPTION_NAME,
        ) as receiver:
            logger.info(f"Listening to topic: {topic_name} for subscription: {SUBSCRIPTION_NAME}")
            while True:
                try:
                    messages = await receiver.receive_messages()
                    for message in messages:
                        _ = await receiver.renew_message_lock(message=message, timeout=600)

                    for message in messages:
                        # Process the message
                        logger.info(
                            f"Received message from topic: {topic_name}, msg: {str(message)} message.locked_until_utc: {message.locked_until_utc} utc_now: {datetime.datetime.now(datetime.timezone.utc)}"
                        )

                        with make_temp_directory() as temp_dir:
                            try:
                                bytes_str = str(message)
                                bytes = ast.literal_eval(bytes_str)
                                time.sleep(360)
                                await receiver.complete_message(message)
                            except Exception as e:
                                logger.exception(
                                    f"Error executing job for topic: {topic_name} message: {message.message_id}, {e}"
                                )
                                await receiver.dead_letter_message(message)

                    if len(messages) == 0:
                        # Small sleep to avoid busy looping
                        await asyncio.sleep(60)
                except Exception as e:
                    logger.exception(f"Error processing message for topic: {topic_name}, {e}")
```

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kashifkhan** [comment]
Hi @ShirishGajera , 

In this case simply calling `renew_message_lock` here is not going to work. It has to be called at some regular interval to make sure the lock is renewed before expiring. 


In the first example

```python
 messages = await receiver.receive_messages()
for message in messages:
    _ = await receiver.renew_message_lock(message=message, timeout=21600)
```

What happens here is that the messages are received and then iterated over one by one, renewing the lock on them exactly once. The timeout value here is not the timeout on the lock, its the timeout for the operation of renewing the lock. So at this point if your queue has a lock period of 5 mins, this call will extend it for another 5 mins. 

The `AutoLockRenewer` is the functionality that will work here.  I think the reason why `AutoLockRenewer` is not working is because the call to the `executor` is a blocking call, preventing it from running in the background. If you change `time.sleep(360)` to `await asyncio.sleep(360)` in the repro code, youll see it working.

**Comment by ShirishGajera** [comment]
@kashifkhan moving executor to async worked with AutoLockRenewer. Thanks!!
