### ISSUE TITLE
Azure service bus send heartbeat to keep connection alive

### ISSUE THREAD

**Issue by ShirishGajera** [Azure/azure-sdk-for-python#37298]
**Is your feature request related to a problem? Please describe.**
If I understand correctly if there are no activity for 4 minutes on Azure service bus connection client, connection will die and that what I am hitting. I am trying to complete the message and seeing this exception. 
```

Unexpected error occurred (ValueError('Link already closed.')). Handler shutting down.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/azure/servicebus/aio/_base_handler_async.py", line 260, in _do_retryable_operation
    return await operation(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/azure/servicebus/aio/_servicebus_receiver_async.py", line 522, in _settle_message
    await self._amqp_transport.settle_message_via_receiver_link_async(
  File "/usr/local/lib/python3.10/dist-packages/azure/servicebus/aio/_transport/_pyamqp_transport_async.py", line 320, in settle_message_via_receiver_link_async
    return await handler.settle_messages_async(message._delivery_id, 'accepted')
  File "/usr/local/lib/python3.10/dist-packages/azure/servicebus/_pyamqp/aio/_client_async.py", line 1004, in settle_messages_async
    await self._link.send_disposition(
  File "/usr/local/lib/python3.10/dist-packages/azure/servicebus/_pyamqp/aio/_receiver_async.py", line 129, in send_disposition
    raise ValueError("Link already closed.")
ValueError: Link already closed.

```
**Describe the solution you'd like**
I want to set heartbeat to keep the connection live when creating client using from_connection_string()

**Describe alternatives you've considered**
I am currently recreating client every 3 minutes as work around

If there is already existing solution please let me know

**Comment by kristapratico** [comment]
@ShirishGajera thanks for your question, the team will take a look and respond as soon as possible.

**Comment by l0lawrence** [comment]
@ShirishGajera can you share the code sample giving you this error to help us better understand your scenario?

**Comment by arpan-reconectai** [comment]
Even I am facing the same challenge. The python sdk doesn't have proper connection management / pooling feature for service bus. So I built my own asyncio based connection pooling based of a FIFO asyncio.Queue. However, the connection drops due to inactivity for some time, and for n requests, it takes 10 seconds each to refresh the connections, where n is the pool size.
