### ISSUE TITLE
keyVaultUri keyVaultKeyName parameters mismatch between SearchResourceEncryptionKey and SearchIndexerSkillset results `request is invalid` when creating skillset in azure-search-documents SDK (v11.6.0b5)

### ISSUE THREAD

**Issue by YVass1** [Azure/azure-sdk-for-python#37521]
- **Package Name**:   azure.search.documents
- **Package Version**:  11.6.0b5
- **Operating System**: OSX, version: 14.6.1
- **Python Version**:  3.11.10

**Describe the bug**
While creating a skillset for indexer for Azure AI Search, I encounter an error indicating missing parameters for the encryption key:

```python 
--- Logging error ---
  File "/Users/<redacted-project-path>/.venv/lib/python3.11/site-packages/azure/search/documents/indexes/_generated/aio/operations/_skillsets_operations.py", line 261, in create_or_update
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: () The request is invalid. Details: encryptionKey.keyVaultUri : The keyVaultUri field is required.
encryptionKey.keyVaultKeyName : The keyVaultKeyName field is required.
Code: 
Message: The request is invalid. Details: encryptionKey.keyVaultUri : The keyVaultUri field is required.
encryptionKey.keyVaultKeyName : The keyVaultKeyName field is required.
```

However, when defining parameters `keyVaultUri` and `keyVaultKeyName` from the error message in encryptionKey and removing parameters `key_name` and `vault_uri` which [Microsoft documentation](https://learn.microsoft.com/en-us/python/api/azure-search-documents/azure.search.documents.indexes.models.searchresourceencryptionkey?view=azure-python) specifies are the available properties of class `SearchResourceEncryptionKey` , I get the following error (as expected):
NB: Error persisted even when these parameter name variations were tried: `key_vault_uri` and `key_vault_key_name`

```python 
Traceback (most recent call last):
  File "/Users/<redacted-project-path>/<redacted-filename>.py", line 1352, in setup_clients
    encryption_key_test = SearchResourceEncryptionKey(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SearchResourceEncryptionKey.__init__() missing 2 required keyword-only arguments: 'key_name' and 'vault_uri'
```

I also tried defining all of these parameters in encryptionKey , however I get the following warning and my original error of missing parameters:

```python 
WARNING - azure.search.documents.indexes._generated._serialization - keyVaultUri is not a known attribute of class <class 'azure.search.documents.indexes.models._models.SearchResourceEncryptionKey'> and will be ignored
azure.search.documents.indexes._generated._serialization - keyVaultKeyName is not a known attribute of class <class 'azure.search.documents.indexes.models._models.SearchResourceEncryptionKey'> and will be ignored
```

**To Reproduce**
Steps to reproduce the behaviour:

Assuming Blob Storage Account , Azure OpenAI Instance, Azure AI Search, Index and indexer all already exist and managed identity enabled with storage blob data read role (or necessary perms).

1. Install the library azure-search-documents==11.6.0b5
2. Define SearchResourceEncryptionKey object for encryption.
3. Create Indexer client.
4. Define skills, projection and skillset passing SearchResourceEncryptionKey object defined earlier.
5. Attempt to create skillset for above indexer.
6. Observe the "missing parameters" error.

```python

from azure.search.documents.indexes import SearchIndexerClient
from azure.core.credentials import AzureKeyCredential
from azure.search.documents.indexes.models import (
    AzureOpenAIEmbeddingSkill,
    IndexProjectionMode,
    InputFieldMappingEntry,
    OutputFieldMappingEntry,
    SearchIndexer,
    SearchIndexerDataContainer,
    SearchIndexerDataSourceConnection,
    SearchIndexerIndexProjection,
    SearchIndexerIndexProjectionSelector,
    SearchIndexerIndexProjectionsParameters,
    SearchIndexerSkillset,
    SearchResourceEncryptionKey,
    SplitSkill,
)
# Initialize the client
indexer_client = SearchIndexerClient(endpoint="https://<your-search-service>.search.windows.net",
                             credential=AzureKeyCredential("<your-key>"))

# Define an encryption key
encryption_key_test = SearchResourceEncryptionKey(
    key_name="your-key-name",
    key_version="your-key-version",
    vault_uri="https://<your-keyvault-name>.vault.azure.net/",
    application_id="<your-client-app-id>",
    application_secret="<your-server-app-secret>",
)

# define skills, projection and skillset
split_skill = SplitSkill(
      description="Split skill to chunk documents",
      text_split_mode="pages",
      context="/document",
      maximum_page_length=2000,
      page_overlap_length=200,
      inputs=[
          InputFieldMappingEntry(name="text", source="/document/content"),
      ],
      outputs=[OutputFieldMappingEntry(name="textItems", target_name="pages")],
)

embedding_skill = AzureOpenAIEmbeddingSkill(
    description="Skill to generate embeddings via Azure OpenAI",
    context="/document/pages/*",
    resource_url="<azure_openai_url>", # resource uri for azure open ai instance
    deployment_name="<deployment-name>", # deployment name of embedding model deployed in azure open ai
    api_key="<azure_openai_key>", # key for azure open ai instance
    inputs=[
        InputFieldMappingEntry(name="text", source="/document/pages/*"),
    ],
    outputs=[OutputFieldMappingEntry(name="embedding", target_name="vectors")],
)

index_projection = SearchIndexerIndexProjection(
    selectors=[
        SearchIndexerIndexProjectionSelector(
            target_index_name="<index_name>",
            parent_key_field_name="parent_id",
            source_context="/document/pages/*",
            mappings=[
                InputFieldMappingEntry(name="content", source="/document/pages/*"),
                InputFieldMappingEntry(name="vector_embedding", source="/document/pages/*/vectors"),
            ],
        ),
    ],
    parameters=SearchIndexerIndexProjectionsParameters(
        projection_mode=IndexProjectionMode.SKIP_INDEXING_PARENT_DOCUMENTS
    ),
)

skillset = SearchIndexerSkillset(
        name="<skillset_name>",
        description="Skillset to chunk documents and generate embeddings",
        skills=[split_skill, embedding_skill],
        index_projection=index_projection,
        encryption_key=encryption_key_test,
)
            
# Attempt to create a skillset 
indexer_client.create_or_update_skillset(skillset)

```

**Additional context**
I use this encryption key in other places too i.e. when creating index, data source connection, indexer so it would be helpful if it can be checked this encryption key works for this version in the other places as i already found 1 bug while trying to create data source connection too. Thanks!

**Comment by YVass1** [comment]
I saw the same error when using encryption key with `SearchIndexer`

Here is the code snippet to add on 
```python
indexer = SearchIndexer(
      name="indexer-name-example",
      description="Indexer to index documents and generate embeddings",
      # TODO Bug in creating skillset so commented out for now 
      # skillset_name="<skillset-name>",
      target_index_name="<index-name>",
      data_source_name="<data-source-connection>",
      encryption_key=encryption_key_test,
      schedule=IndexingSchedule(
          interval="PT1H", start_time="2024-09-12T22:04:02Z"
      ),
  )
  
indexer_client.create_or_update_indexer(indexer)

```

**Comment by YVass1** [comment]
Hi, is there an update ? Is there a new package release with the fix included now ?

**Comment by xiangyan99** [comment]
A fixed is merged. It will be available in next release in about 2 weeks.

**Comment by YVass1** [comment]
Thanks, will that be a beta release or it is possible to release the fix earlier in a beta release ?

**Comment by xiangyan99** [comment]
That will be a beta release and if everything goes well, we will ship it on 8th.

**Comment by xiangyan99** [comment]
FYI. azure-search-documents 11.6.0b6 is shipped. https://pypi.org/project/azure-search-documents/11.6.0b6/
