### ISSUE TITLE
azure.cognitiveservices.speech load error on Debian

### ISSUE THREAD

**Issue by xuanyuxin** [Azure/azure-sdk-for-python#38468]
Hi, I tried to compile a speechsdk program using [Nuitka ](https://github.com/Nuitka/Nuitka) and encountered an error loading libMicrosoft.CognitiveServices.Speech.core.so: cannot open shared object file: No such file or directory. 

The MRE is:
- OS version: Debian GNU/Linux 12 (bookworm)
- Nuitka version: 2.4.11

- Nuitka command that I used:
```
python -m nuitka --standalone speech_to_text.py
```
where 
speech_to_text.py:
```
import os, time, re
import azure.cognitiveservices.speech as speechsdk

def recognize_from_microphone():
    # This example requires environment variables named "SPEECH_KEY" and "SPEECH_REGION"
    speech_config = speechsdk.SpeechConfig(subscription='test', region='test')
    # speech_config.speech_recognition_language="en-US"

    # https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-recognize-speech?pivots=programming-language-csharp#change-how-silence-is-handled
    auto_detect_source_language_config = speechsdk.languageconfig.AutoDetectSourceLanguageConfig(languages=["en-US", "de-DE", "zh-CN"])
    # Set the initial silence timeout to 5 seconds
    speech_config.set_property(speechsdk.PropertyId.SpeechServiceConnection_InitialSilenceTimeoutMs, "5000")
    # Set the end silence timeout to 5 seconds
    speech_config.set_property(speechsdk.PropertyId.SpeechServiceConnection_EndSilenceTimeoutMs, "5000")
    # Set the segmentation silence timeout to 3 seconds
    speech_config.set_property(speechsdk.PropertyId.Speech_SegmentationSilenceTimeoutMs, "3000")

    audio_config = speechsdk.audio.AudioConfig(use_default_microphone=True)
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, 
                                                   auto_detect_source_language_config=auto_detect_source_language_config,
                                                   audio_config=audio_config)

    print("Speak into your microphone.")
    speech_recognition_result = speech_recognizer.recognize_once_async().get()

if __name__ == '__main__':
    text = recognize_from_microphone()
```

The error is:
```
Traceback (most recent call last):
  File "/tmp/onefile_575_1731322538_97239/speech_to_text.py", line 2, in <module>
    import azure.cognitiveservices.speech as speechsdk
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/tmp/onefile_575_1731322538_97239/azure/cognitiveservices/speech/__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/tmp/onefile_575_1731322538_97239/azure/cognitiveservices/speech/speech.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/tmp/onefile_575_1731322538_97239/azure/cognitiveservices/speech/interop.py", line 20, in <module>
  File "/tmp/onefile_575_1731322538_97239/ctypes/__init__.py", line 452, in LoadLibrary
  File "/tmp/onefile_575_1731322538_97239/ctypes/__init__.py", line 374, in __init__
OSError: /tmp/onefile_575_1731322538_97239/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so: cannot open shared object file: No such file or directory
```

Would like to have some advice on loading speechsdk shared object. Thank you very much!

**Comment by xuanyuxin** [comment]
Solved. For anyone interested in this issue:
`python -m nuitka --standalone --onefile --include-data-file=/usr/local/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so=azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so speech_to_text.py`
