### ISSUE TITLE
azure-mgmt-postgresqlflexibleservers 1.1.0b1 : Why is list_by_server for tuning options failing

### ISSUE THREAD

**Issue by nasc17** [Azure/azure-sdk-for-python#38477]
azure-mgmt-postgresqlflexibleservers 1.1.0b1
Windows 11
https://pypi.org/project/azure-mgmt-postgresqlflexibleservers/1.1.0b1/

**Describe the bug**
Want to understand why trying to use list_by_server for tuning options resources, generates error during deserialization 

The command failed with an unexpected error. Here is the traceback:
Unable to deserialize to object: type
Traceback (most recent call last):
  File "C:\Users\nasc\azureCLI\azure-cli\env\lib\site-packages\azure\mgmt\postgresqlflexibleservers\_serialization.py", line 1463, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "C:\Users\nasc\azureCLI\azure-cli\env\lib\site-packages\azure\mgmt\postgresqlflexibleservers\_serialization.py", line 1211, in rest_key_extractor
    return working_data.get(key)
AttributeError: 'list' object has no attribute 'get'
 

**To Reproduce**
Following sample from [file](https://github.com/Azure/azure-sdk-for-python/blob/e30c64036dd0249532d2b76a39720167452efd5f/sdk/postgresqlflexibleservers/azure-mgmt-postgresqlflexibleservers/generated_samples/tuning_list_tuning_options.py)

client = PostgreSQLManagementClient(
        credential=DefaultAzureCredential(),
        subscription_id="ffffffff-ffff-ffff-ffff-ffffffffffff",
    )

    response = client.tuning_options.list_by_server(
        resource_group_name="testrg",
        server_name="testserver",
    )

**Expected behavior**
Expected list to be deserialized and returned

**Screenshots**
The command failed with an unexpected error. Here is the traceback:
Unable to deserialize to object: type
Traceback (most recent call last):
  File "C:\Users\nasc\azureCLI\azure-cli\env\lib\site-packages\azure\mgmt\postgresqlflexibleservers\_serialization.py", line 1463, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "C:\Users\nasc\azureCLI\azure-cli\env\lib\site-packages\azure\mgmt\postgresqlflexibleservers\_serialization.py", line 1211, in rest_key_extractor
    return working_data.get(key)
AttributeError: 'list' object has no attribute 'get'
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "C:\Users\nasc\azureCLI\azure-cli\env\lib\site-packages\knack\cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "c:\users\nasc\azurecli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 666, in execute
  File "c:\users\nasc\azurecli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 666, in execute
    raise ex
  File "c:\users\nasc\azurecli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 733, in _run_jobs_serially 
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "c:\users\nasc\azurecli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 716, in _run_job
  File "c:\users\nasc\azurecli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 733, in _run_jobs_serially 
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "c:\users\nasc\azurecli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 716, in _run_job
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "c:\users\nasc\azurecli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 716, in _run_job
  File "c:\users\nasc\azurecli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 716, in _run_job
    result = list(result)
  File "C:\Users\nasc\azureCLI\azure-cli\env\lib\site-packages\azure\core\paging.py", line 123, in __next__
    result = list(result)
    result = list(result)
  File "C:\Users\nasc\azureCLI\azure-cli\env\lib\site-packages\azure\core\paging.py", line 123, in __next__
    return next(self._page_iterator)
    result = list(result)
  File "C:\Users\nasc\azureCLI\azure-cli\env\lib\site-packages\azure\core\paging.py", line 123, in __next__
    return next(self._page_iterator)
    return next(self._page_iterator)
  File "C:\Users\nasc\azureCLI\azure-cli\env\lib\site-packages\azure\core\paging.py", line 83, in __next__
    self.continuation_token, self._current_page = self._extract_data(self._response)
  File "C:\Users\nasc\azureCLI\azure-cli\env\lib\site-packages\azure\mgmt\postgresqlflexibleservers\operations\_tuning_options_operations.py", line 406, in extract_data
    deserialized = self._deserialize("TuningOptionsListResult", pipeline_response)
  File "C:\Users\nasc\azureCLI\azure-cli\env\lib\site-packages\azure\mgmt\postgresqlflexibleservers\_serialization.py", line 1408, in __call__
    return self._deserialize(target_obj, data)
  File "C:\Users\nasc\azureCLI\azure-cli\env\lib\site-packages\azure\mgmt\postgresqlflexibleservers\_serialization.py", line 1478, in _deserialize
    raise DeserializationError(msg) from err
azure.core.exceptions.DeserializationError: Unable to deserialize to object: type
 

**Additional context**
I want to make sure I understand the error, it is saying it cannot reserialize due to the tuning option resource not having a get call, but I see it part of the file?

Error in code
[deserialize("TuningOptionsListResult"](https://github.com/Azure/azure-sdk-for-python/blob/e30c64036dd0249532d2b76a39720167452efd5f/sdk/postgresqlflexibleservers/azure-mgmt-postgresqlflexibleservers/azure/mgmt/postgresqlflexibleservers/operations/_tuning_options_operations.py#L406)
 
Get call
[get call for tuning option](https://github.com/Azure/azure-sdk-for-python/blob/e30c64036dd0249532d2b76a39720167452efd5f/sdk/postgresqlflexibleservers/azure-mgmt-postgresqlflexibleservers/azure/mgmt/postgresqlflexibleservers/operations/_tuning_options_operations.py#L181)

**Comment by ChenxiJiang333** [comment]
got it

**Comment by ChenxiJiang333** [comment]
Hi @nasc17, in [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/preview/2024-11-01-preview/TuningOptions.json#L378), you defined the `TuningOptionsListResult` as an iterable object, which means the service would return an iterator instance as response.
For example, by run this [sample](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/postgresqlflexibleservers/azure-mgmt-postgresqlflexibleservers/generated_samples/server_list.py), the response is like:
```
{"value":[{"sku":{"name":"Standard_B1ms","tier":"Burstable"},"systemData":{"createdAt":"2024-11-13T03:19:37.3429536Z"},"properties":{"replica":{"role":"Primary","capacity":5},"storage":{"type":"","iops":120,"tier":"P4","storageSizeGB":32,"autoGrow":"Disabled"},"network":{"publicNetworkAccess":"Enabled"},"privateEndpointConnections":[],"dataEncryption":{"type":"SystemManaged"},"authConfig":{"activeDirectoryAuth":"Disabled","passwordAuth":"Enabled"},"fullyQualifiedDomainName":"chenxiserver.postgres.database.azure.com","version":"16","minorVersion":"4","administratorLogin":"root1","state":"Ready","availabilityZone":"1","backup":{"backupRetentionDays":7,"geoRedundantBackup":"Disabled","earliestRestoreDate":"2024-11-13T03:26:16.7958974+00:00"},"highAvailability":{"mode":"Disabled","state":"NotEnabled"},"maintenanceWindow":{"customWindow":"Disabled","dayOfWeek":0,"startHour":0,"startMinute":0},"replicationRole":"Primary","replicaCapacity":5},"location":"East US","tags":{},"id":"/subscriptions/subscription/resourceGroups/resourceGroup/providers/Microsoft.DBforPostgreSQL/flexibleServers/chenxiserver","name":"chenxiserver","type":"Microsoft.DBforPostgreSQL/flexibleServers"}]}

```

Yet by running the code you mentioned, the service actually gives a response as a list, which doesn't match the type of `TuningOptionsListResult`, so the deserialization error occurs:
```
[{"properties":{},"id":"/subscriptions/subscription/resourceGroups/resourceGroup/providers/Microsoft.DBforPostgreSQL/flexibleServers/chenxiserver/tuningOptions/index","name":"index","type":"Microsoft.DBforPostgreSQL/flexibleServers/tuningOptions"}]
```

**Comment by ChenxiJiang333** [comment]
And this error `AttributeError: 'list' object has no attribute 'get'` occurs just because we supposed to have an object but here we got a list. The get here is actually Object.get, not TuningOptionsOperations.get.

source code: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/postgresqlflexibleservers/azure-mgmt-postgresqlflexibleservers/azure/mgmt/postgresqlflexibleservers/_serialization.py#L1211

**Comment by nasc17** [comment]
Thank you for helping me to determine this was a type mismatch defined from swagger. Will work to update for new release
