### ISSUE TITLE
receiver.peek_messages() fails for some queues and works for others

### ISSUE THREAD

**Issue by amiket-srivastava** [Azure/azure-sdk-for-python#38717]
- **Package Name**: azure-servicebus
- **Package Version**: 7.13.0
- **Operating System**: Windows 11 Pro and Linux as well (tested on both OS)
- **Python Version**: 3.12.7

**Describe the bug**
I get an error when I try to peek messages on some of my Azure service bus queues. It works well with other queues but fails with some (I have same permissions to both). The only difference between the queues is that the one which fails has two additional custom properties and a bigger body (131B vs 921 B). I tried using with both uamqp_transport=True and False but got different errors both times for the failing queues: 

################ This is for uamqp_transport=False ####################

Unexpected error occurred (TypeError("'NoneType' object is not callable")). Handler shutting down.
Traceback (most recent call last):
  File "C:\Users\amiket.srivastava\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\azure\servicebus\_base_handler.py", line 378, in _do_retryable_operation
    return operation(**kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amiket.srivastava\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\azure\servicebus\_base_handler.py", line 501, in _mgmt_request_response
    return self._amqp_transport.mgmt_client_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amiket.srivastava\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\azure\servicebus\_transport\_pyamqp_transport.py", line 923, in mgmt_client_request
    return callback(status, response, description, amqp_transport=PyamqpTransport)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amiket.srivastava\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\azure\servicebus\_common\mgmt_handlers.py", line 55, in peek_op
    return amqp_transport.parse_received_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amiket.srivastava\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\azure\servicebus\_transport\_pyamqp_transport.py", line 824, in parse_received_message
    wrapped = decode_payload(memoryview(m[b"message"]))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amiket.srivastava\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\azure\servicebus\_pyamqp\_decode.py", line 235, in decode_payload
    buffer, value = _DECODE_BY_CONSTRUCTOR[buffer[3]](buffer[4:])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amiket.srivastava\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\azure\servicebus\_pyamqp\_decode.py", line 176, in _decode_map_small
    buffer, value = _DECODE_BY_CONSTRUCTOR[buffer[0]](buffer[1:])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

##############################################################

################ This is for uamqp_transport=True and also run on Linux machine ####################

Traceback (most recent call last):
  File "/tmp/8dd0e2cfbcafaa2/antenv/lib/python3.12/site-packages/azure/servicebus/_base_handler.py", line 411, in _do_retryable_operation
    return operation(**kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dd0e2cfbcafaa2/antenv/lib/python3.12/site-packages/azure/servicebus/_base_handler.py", line 530, in _mgmt_request_response
    return self._amqp_transport.mgmt_client_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dd0e2cfbcafaa2/antenv/lib/python3.12/site-packages/azure/servicebus/_transport/_uamqp_transport.py", line 1014, in mgmt_client_request
    return mgmt_client.mgmt_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dd0e2cfbcafaa2/antenv/lib/python3.12/site-packages/uamqp/client.py", line 343, in mgmt_request
    response = self._session.mgmt_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dd0e2cfbcafaa2/antenv/lib/python3.12/site-packages/uamqp/session.py", line 126, in mgmt_request
    return parse_response(status, response, description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dd0e2cfbcafaa2/antenv/lib/python3.12/site-packages/azure/servicebus/_common/mgmt_handlers.py", line 65, in peek_op
    return amqp_transport.parse_received_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dd0e2cfbcafaa2/antenv/lib/python3.12/site-packages/azure/servicebus/_transport/_uamqp_transport.py", line 917, in parse_received_message
    wrapped = Message.decode_from_bytes(bytearray(m[b"message"]))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dd0e2cfbcafaa2/antenv/lib/python3.12/site-packages/uamqp/message.py", line 283, in decode_from_bytes
    decoded_message = c_uamqp.decode_message(len(data), data)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./src/message.pyx", line 769, in uamqp.c_uamqp.decode_message
  File "./src/message.pyx", line 779, in uamqp.c_uamqp.decode_message
ValueError: Cannot decode bytes

###############################################################

**To Reproduce**
1. Create an Azure Service Bus Queue and provide permissions
2. Send the message I have attached to it.
3. Try to peek it using the following code:

##############
import os
from azure.servicebus import ServiceBusClient
from azure.identity import DefaultAzureCredential

FULLY_QUALIFIED_NAMESPACE = os.environ["SERVICEBUS_FULLY_QUALIFIED_NAMESPACE"]
QUEUE_NAME = os.environ["SERVICEBUS_QUEUE_NAME"]

credential = DefaultAzureCredential()
servicebus_client = ServiceBusClient(FULLY_QUALIFIED_NAMESPACE, credential)

with servicebus_client:
    receiver = servicebus_client.get_queue_receiver(queue_name=QUEUE_NAME)
    with receiver:
        received_msgs = receiver.peek_messages(max_message_count=2)
        for msg in received_msgs:
            print(str(msg))
#######################

**Expected behavior**
I expected to get the peeked the messaged in response instead of the error.

**Screenshots**

N/A as Already shared the errors encountered in text format.

**Additional context**

**Comment by l0lawrence** [comment]
Hi @amiket-srivastava, a few follow up questions to help us reproduce this issue:

>> The only difference between the queues is that the one which fails has two additional custom properties and a bigger body (131B vs 921 B). 

1) By the queue having a body of 921 B, are you referring to the message within the queue being 921 B? If so, if you try the same 921 B message without the custom properties do you see the same issue? 

2) Would you be able to share the custom properties you are setting and where you are setting them, as well as an example of the message you are sending?

**Comment by amiket-srivastava** [comment]
Hi @l0lawrence I have tested with messages that are greater than 1 KB and they work so it doesn't seem to be a case of size issue. Apologies about the sample message, I forgot to add the attachment yesterday, attaching now.

Also these are the custom properties on the message for which the request is failing:
[cid:435de70f-7828-415f-a380-ac937dc6b8d3]
These are the custom properties on the message for which the request is not failing:
[cid:981e0c8d-a0bc-499b-ac1f-c7b523ca8a8f]
Hope this helps. Let me know if you need anything else.

Best Regards,
Amiket Kumar Srivastava

________________________________

**Comment by kashifkhan** [comment]
@amiket-srivastava It doesnt look like the messages were attached as they were sent via email. On the issue side on github we are not able to see the messages.

**Comment by amiket-srivastava** [comment]
[message.xlsx](https://github.com/user-attachments/files/17991401/message.xlsx)
PFA, thank you.

-Amiket

**Comment by l0lawrence** [comment]
Hi @amiket-srivastava thank you for sharing the message I tested peeking it after setting the message body and message subject and sending it to the queue, and I was unable to repro.

```
message = 
ServiceBusMessage( 
body='{"testType":2,"retestlType":1,"retestPeriod":5,"runType":2,"testCheck":2,"demoStatus":1,"demoName":"test Demo Reminder 1","communicationId":"30633b96-0d22-63b4-e053-0420c1acb645","retestFrequency":12,"logTestFailures":false,"fromDate":"2024-10-20","testGroup":false,"testGroupSize":0.0,"testGroupExpiry":"2024-10-23T00:00:00+00:00","retests":[{"testType":3,"testPeriod":1,"testNumber":1,"testFrequency":30}],"assignments":[{"retestProgramId":"dcf2f044-7892-495e-b1dc-01316ae5d64a"}],"schedule":{"jobType":1,"periodType":2,"retest":2,"runTime":"2024-10-20T00:00:00+00:00","retestFrequency":1,"days":[{"testNumber":1,"testEnabled":true}]},"testParameters":[{"testgroups":[{"attributes":[{"type":"testDemoQueryBuilderAttribute","values":[{"value":"56a37578-f32d-4106-990a-be7eb9b3dd9c"}],"testType":2,"testCode":"Retest.DemoType"}]}]}]}',
subject='ce4062f6-n7b7-4541-b11e-a2s4e0e66acb:09134b96-2d1f-63a4-e053-0400c8acc645:testDemo_Example2',
 )
```

Is there anything else I am missing here in the setup?

**Comment by amiket-srivastava** [comment]
Here are two unaltered messages from the queue and also a screenshot of the custom properties on the messages[messages.xlsx](https://github.com/user-attachments/files/18029503/messages.xlsx)
![Image](https://github.com/user-attachments/assets/8992fd6f-0e62-4915-9159-974ce7196136)

**Comment by kashifkhan** [comment]
Hi @amiket-srivastava, looking at the screenshot and the excel file there seems to be a mismatch and have a few questions 

* We are not able to see the properties in the screenshot in the xlsx file. 
* What are the special characters in `callDuration` and `correlationId` ?

**Comment by amiket-srivastava** [comment]
The correlationId is a guid like 742ea186-37d5-4007-8177-03e4b9f7664e. I know this value cause I am able to retrieve it in messages from other queues which do not have the callDuration property. I don't have an example value for callDuration as I cannot retrieve it using the library and I am downloading the message from UI as shown in the screenshot (tried both download options) but it only provides the excel that I shared with you.
 [cid:20ce43c4-aa95-41ff-b7c9-afbc9b6345c6]

________________________________

**Comment by l0lawrence** [comment]
Hi @amiket-srivastava, thanks for sharing. Since we don't know what callDuration is I tried with just a guid:

![Image](https://github.com/user-attachments/assets/9e31d646-5241-48c1-bc6e-a056dc8a1f8a)

which I am able to see under custom properties. 




Would you be able to test peeking these messages with a different SDK (.[NET](https://www.nuget.org/packages/Azure.Messaging.ServiceBus), [Java](https://mvnrepository.com/artifact/com.azure/azure-messaging-servicebus), [JS](https://www.npmjs.com/package/@azure/service-bus), [Go](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus))?

This could answer 2 questions for us:
-  What the `callDuration` property is?
- If the other SDKs can handle this `callDuration` property as well

**Comment by amiket-srivastava** [comment]
Hi Sorry, I was away for a while due to personal reasons so I couldn't get back to you sooner. I peeked the messages using C# and the call duration property has a value of "33802.4489".

**Comment by amiket-srivastava** [comment]
I checked the value type using the .GetType() method and it says it is "System.Decimal"

**Comment by kashifkhan** [comment]
Hi @amiket-srivastava , Im going to close the new issue created #39315 and re-open this one, so that we have the full history. Just to confirm, you were able to peek that message using C# but using python for the same message ended in the error ? 

The cal duration property is stored as a string or a decimal in the portal view ?

**Comment by amiket-srivastava** [comment]
Yes, I confirm that I can peek the message through C# but get the Decode error with Python. And on the portal I am not sure what the property is stored as, it is under custom properties and shows up as a weird value as can be seen in the screenshot I uploaded on Dec 5.

**Comment by kashifkhan** [comment]
thank you for that @amiket-srivastava , will let you know if we are able to repro on our side or we need to do some more troubleshooting.

**Comment by amiket-srivastava** [comment]
Try using DECIMAL as the datatype

**Comment by kashifkhan** [comment]
@amiket-srivastava Im able to reproduce this now as the type is decimal being sent from .net I assume ? is there a reason for call duration to be a decimal instead of float/double

**Comment by amiket-srivastava** [comment]
@kashifkhan the decimal value is coming from the source code of a C# app. We cannot change the value from decimal to float or double as it could cause variances within the data from the app.

**Comment by kashifkhan** [comment]
@amiket-srivastava we will be releasing a fix for this issue in our next release. Ill update this thread when the new version is on pypi

**Comment by amiket-srivastava** [comment]
Thank you @kashifkhan 
I will wait for the new version.

**Comment by kashifkhan** [comment]
@amiket-srivastava the changes are in main, you can test them out by building a wheel before the changes are officially available on pypi.

**Comment by amiket-srivastava** [comment]
@kashifkhan I have tested the changes in dev and they seem to be working fine. Thank you very much. I will wait for the official release to update and fix the issue in production.

**Comment by kashifkhan** [comment]
@amiket-srivastava the new version with the fix is now on pypi
