### ISSUE TITLE
ManagedIdentityCredential authentication unavailable. The requested identity has not been assigned to this resource. Error: Unexpected response "{'error': 'invalid_request', 'error_description': 'Identity not found'}"

### ISSUE THREAD

**Issue by RajithaNelluru** [Azure/azure-sdk-for-python#38826]
When I try to authenticate via Federated Identity facing the issues.
The piece of code added was,
from azure.identity import DefaultAzureCredential
 auth = DefaultAzureCredential()
    os.environ["OPENAI_API_TYPE"] = "azure_ad"
    os.environ["OPENAI_API_KEY"] = auth.get_token("https://cognitiveservices.azure.com/.default").token
ws = Workspace.from_config(auth=auth, path=get_aml_config_path_env(pipeline_config_dict['aml_mode']))

The complete log is,
2024-12-11T04:38:09.6154221Z ##[section]Starting: Run Gatekeeper.py
2024-12-11T04:38:09.6163656Z ==============================================================================
2024-12-11T04:38:09.6163862Z Task         : Command line
2024-12-11T04:38:09.6163982Z Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
2024-12-11T04:38:09.6164151Z Version      : 2.246.1
2024-12-11T04:38:09.6164278Z Author       : Microsoft Corporation
2024-12-11T04:38:09.6164401Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
2024-12-11T04:38:09.6164563Z ==============================================================================
2024-12-11T04:38:10.8578538Z Generating script.
2024-12-11T04:38:10.8676320Z Script contents: shell
2024-12-11T04:38:10.8683931Z python build\gatekeeper.py --branch_source CICDTesting --branch_target UAT --models Workforce_tcrf_FTE_lgbm
2024-12-11T04:38:10.9031737Z ========================== Starting Command Output ===========================
2024-12-11T04:38:10.9342325Z ##[command]"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\fd1a9ed2-7146-487f-be61-282aad613c24.cmd""
2024-12-11T04:38:14.5805450Z build\gatekeeper.py:6: FutureWarning: azureml.core: AzureML support for Python 3.7 is deprecated and will be dropped in an upcoming release. At that point, existing Python 3.7 workflows that use AzureML will continue to work without modification, but Python 3.7 users will no longer get access to the latest AzureML features and bugfixes. We recommend that you upgrade to Python 3.8 or newer. To disable SDK V1 deprecation warning set the environment variable AZUREML_DEPRECATE_WARNING to 'False'
2024-12-11T04:38:14.5806673Z   from azureml.core import VERSION, Experiment, Workspace
2024-12-11T04:38:14.5807193Z INFO:azure.identity._credentials.environment:No environment configuration found.
2024-12-11T04:38:14.5816204Z INFO:azure.identity._credentials.managed_identity:ManagedIdentityCredential will use IMDS
2024-12-11T04:38:14.5827683Z DEBUG:azure.identity._internal.decorators:EnvironmentCredential.get_token failed: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
2024-12-11T04:38:14.5828319Z Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
2024-12-11T04:38:14.5828771Z Traceback (most recent call last):
2024-12-11T04:38:14.5829262Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_internal\decorators.py", line 33, in wrapper
2024-12-11T04:38:14.5829723Z     token = fn(*args, **kwargs)
2024-12-11T04:38:14.5830211Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_credentials\environment.py", line 150, in get_token
2024-12-11T04:38:14.5830716Z     raise CredentialUnavailableError(message=message)
2024-12-11T04:38:14.5831228Z azure.identity._exceptions.CredentialUnavailableError: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
2024-12-11T04:38:14.5831794Z Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
2024-12-11T04:38:14.5875017Z DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254:80
2024-12-11T04:38:14.5955023Z DEBUG:urllib3.connectionpool:http://169.254.169.254:80 "GET /metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://cognitiveservices.azure.com HTTP/1.1" 400 88
2024-12-11T04:38:14.6188103Z DEBUG:urllib3.connectionpool:http://169.254.169.254:80 "GET /metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://cognitiveservices.azure.com HTTP/1.1" 400 68
2024-12-11T04:38:14.6207445Z DEBUG:azure.identity._internal.get_token_mixin:ImdsCredential.get_token failed: ManagedIdentityCredential authentication unavailable. The requested identity has not been assigned to this resource. Error: Unexpected response "{'error': 'invalid_request', 'error_description': 'Identity not found'}"
2024-12-11T04:38:14.6265292Z Traceback (most recent call last):
2024-12-11T04:38:14.6266849Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_credentials\imds.py", line 100, in _request_token
2024-12-11T04:38:14.6268104Z     token = self._client.request_token(*scopes, headers={"Metadata": "true"})
2024-12-11T04:38:14.6272889Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_internal\managed_identity_client.py", line 113, in request_token
2024-12-11T04:38:14.6274257Z     token = self._process_response(response, request_time)
2024-12-11T04:38:14.6276364Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_internal\managed_identity_client.py", line 58, in _process_response
2024-12-11T04:38:14.6290260Z     message='Unexpected response "{}"'.format(content), response=response.http_response
2024-12-11T04:38:14.6291283Z azure.core.exceptions.ClientAuthenticationError: Unexpected response "{'error': 'invalid_request', 'error_description': 'Identity not found'}"
2024-12-11T04:38:14.6292104Z Content: {"error":"invalid_request","error_description":"Identity not found"}
2024-12-11T04:38:14.6292410Z 
2024-12-11T04:38:14.6292872Z The above exception was the direct cause of the following exception:
2024-12-11T04:38:14.6293130Z 
2024-12-11T04:38:14.6293578Z Traceback (most recent call last):
2024-12-11T04:38:14.6294122Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_internal\get_token_mixin.py", line 86, in get_token
2024-12-11T04:38:14.6294696Z     token = self._request_token(*scopes, claims=claims, tenant_id=tenant_id, **kwargs)
2024-12-11T04:38:14.6295282Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_credentials\imds.py", line 114, in _request_token
2024-12-11T04:38:14.6295829Z     raise CredentialUnavailableError(message=error_message) from ex
2024-12-11T04:38:14.6296530Z azure.identity._exceptions.CredentialUnavailableError: ManagedIdentityCredential authentication unavailable. The requested identity has not been assigned to this resource. Error: Unexpected response "{'error': 'invalid_request', 'error_description': 'Identity not found'}"
2024-12-11T04:38:14.6297543Z DEBUG:azure.identity._internal.decorators:ManagedIdentityCredential.get_token failed: ManagedIdentityCredential authentication unavailable. The requested identity has not been assigned to this resource. Error: Unexpected response "{'error': 'invalid_request', 'error_description': 'Identity not found'}"
2024-12-11T04:38:14.6298241Z Traceback (most recent call last):
2024-12-11T04:38:14.6298772Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_credentials\imds.py", line 100, in _request_token
2024-12-11T04:38:14.6299320Z     token = self._client.request_token(*scopes, headers={"Metadata": "true"})
2024-12-11T04:38:14.6299912Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_internal\managed_identity_client.py", line 113, in request_token
2024-12-11T04:38:14.6300475Z     token = self._process_response(response, request_time)
2024-12-11T04:38:14.6301031Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_internal\managed_identity_client.py", line 58, in _process_response
2024-12-11T04:38:14.6301628Z     message='Unexpected response "{}"'.format(content), response=response.http_response
2024-12-11T04:38:14.6302200Z azure.core.exceptions.ClientAuthenticationError: Unexpected response "{'error': 'invalid_request', 'error_description': 'Identity not found'}"
2024-12-11T04:38:14.6302790Z Content: {"error":"invalid_request","error_description":"Identity not found"}
2024-12-11T04:38:14.6303048Z 
2024-12-11T04:38:14.6303489Z The above exception was the direct cause of the following exception:
2024-12-11T04:38:14.6303769Z 
2024-12-11T04:38:14.6304193Z Traceback (most recent call last):
2024-12-11T04:38:14.6304703Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_internal\decorators.py", line 33, in wrapper
2024-12-11T04:38:14.6305881Z     token = fn(*args, **kwargs)
2024-12-11T04:38:14.6306416Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_credentials\managed_identity.py", line 137, in get_token
2024-12-11T04:38:14.6307012Z     return self._credential.get_token(*scopes, claims=claims, tenant_id=tenant_id, **kwargs)
2024-12-11T04:38:14.6307622Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_internal\get_token_mixin.py", line 86, in get_token
2024-12-11T04:38:14.6308311Z     token = self._request_token(*scopes, claims=claims, tenant_id=tenant_id, **kwargs)
2024-12-11T04:38:14.6308876Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_credentials\imds.py", line 114, in _request_token
2024-12-11T04:38:14.6309433Z     raise CredentialUnavailableError(message=error_message) from ex
2024-12-11T04:38:14.6310128Z azure.identity._exceptions.CredentialUnavailableError: ManagedIdentityCredential authentication unavailable. The requested identity has not been assigned to this resource. Error: Unexpected response "{'error': 'invalid_request', 'error_description': 'Identity not found'}"
2024-12-11T04:38:14.7748163Z DEBUG:azure.identity._internal.decorators:SharedTokenCacheCredential.get_token failed: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
2024-12-11T04:38:14.7749140Z Traceback (most recent call last):
2024-12-11T04:38:14.7749746Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_internal\decorators.py", line 33, in wrapper
2024-12-11T04:38:14.7750307Z     token = fn(*args, **kwargs)
2024-12-11T04:38:14.7750826Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_credentials\shared_cache.py", line 80, in get_token
2024-12-11T04:38:14.7751406Z     return self._credential.get_token(*scopes, claims=claims, tenant_id=tenant_id, **kwargs)
2024-12-11T04:38:14.7752002Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_credentials\shared_cache.py", line 124, in get_token
2024-12-11T04:38:14.7752553Z     account = self._get_account(self._username, self._tenant_id, is_cae=is_cae)
2024-12-11T04:38:14.7753100Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_internal\decorators.py", line 79, in wrapper
2024-12-11T04:38:14.7753602Z     return fn(*args, **kwargs)
2024-12-11T04:38:14.7754118Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_internal\shared_token_cache.py", line 205, in _get_account
2024-12-11T04:38:14.7754679Z     raise CredentialUnavailableError(message=NO_ACCOUNTS)
2024-12-11T04:38:14.7755248Z azure.identity._exceptions.CredentialUnavailableError: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
2024-12-11T04:38:48.1406407Z DEBUG:azure.identity._internal.decorators:AzureCliCredential.get_token failed: Failed to invoke the Azure CLI
2024-12-11T04:38:48.1407391Z Traceback (most recent call last):
2024-12-11T04:38:48.1407909Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_credentials\azure_cli.py", line 201, in _run_command
2024-12-11T04:38:48.1408613Z     return subprocess.check_output(args, **kwargs)
2024-12-11T04:38:48.1410094Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\subprocess.py", line 411, in check_output
2024-12-11T04:38:48.1410533Z     **kwargs).stdout
2024-12-11T04:38:48.1410934Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\subprocess.py", line 490, in run
2024-12-11T04:38:48.1411449Z     stdout, stderr = process.communicate(input, timeout=timeout)
2024-12-11T04:38:48.1411959Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\subprocess.py", line 964, in communicate
2024-12-11T04:38:48.1412965Z     stdout, stderr = self._communicate(input, endtime, timeout)
2024-12-11T04:38:48.1414006Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\subprocess.py", line 1298, in _communicate
2024-12-11T04:38:48.1414581Z     raise TimeoutExpired(self.args, orig_timeout)
2024-12-11T04:38:48.1415202Z subprocess.TimeoutExpired: Command '['cmd', '/c', 'az account get-access-token --output json --resource https://cognitiveservices.azure.com']' timed out after 10 seconds
2024-12-11T04:38:48.1415545Z 
2024-12-11T04:38:48.1416037Z The above exception was the direct cause of the following exception:
2024-12-11T04:38:48.1416280Z 
2024-12-11T04:38:48.1416695Z Traceback (most recent call last):
2024-12-11T04:38:48.1417379Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_internal\decorators.py", line 33, in wrapper
2024-12-11T04:38:48.1417928Z     token = fn(*args, **kwargs)
2024-12-11T04:38:48.1418480Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_credentials\azure_cli.py", line 113, in get_token
2024-12-11T04:38:48.1419067Z     output = _run_command(command, self._process_timeout)
2024-12-11T04:38:48.1419653Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_credentials\azure_cli.py", line 225, in _run_command
2024-12-11T04:38:48.1420195Z     raise error from ex
2024-12-11T04:38:48.1420716Z azure.identity._exceptions.CredentialUnavailableError: Failed to invoke the Azure CLI
2024-12-11T04:38:49.5436666Z DEBUG:azure.identity._internal.decorators:AzurePowerShellCredential.get_token failed: Az.Account module >= 2.2.0 is not installed
2024-12-11T04:38:49.5437552Z Traceback (most recent call last):
2024-12-11T04:38:49.5438196Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_internal\decorators.py", line 33, in wrapper
2024-12-11T04:38:49.5438731Z     token = fn(*args, **kwargs)
2024-12-11T04:38:49.5439265Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_credentials\azure_powershell.py", line 125, in get_token
2024-12-11T04:38:49.5439853Z     output = run_command_line(command_line, self._process_timeout)
2024-12-11T04:38:49.5440425Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_credentials\azure_powershell.py", line 156, in run_command_line
2024-12-11T04:38:49.5440972Z     raise_for_error(proc.returncode, stdout, stderr)
2024-12-11T04:38:49.5441532Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_credentials\azure_powershell.py", line 202, in raise_for_error
2024-12-11T04:38:49.5442088Z     raise CredentialUnavailableError(AZ_ACCOUNT_NOT_INSTALLED)
2024-12-11T04:38:49.5442629Z azure.identity._exceptions.CredentialUnavailableError: Az.Account module >= 2.2.0 is not installed
2024-12-11T04:38:49.5618840Z DEBUG:azure.identity._internal.decorators:AzureDeveloperCliCredential.get_token failed: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.
2024-12-11T04:38:49.5619945Z Traceback (most recent call last):
2024-12-11T04:38:49.5620313Z Azure ML SDK Version:  1.53.0
2024-12-11T04:38:49.5620968Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_internal\decorators.py", line 33, in wrapper
2024-12-11T04:38:49.5621358Z all args:
2024-12-11T04:38:49.5621886Z     token = fn(*args, **kwargs)
2024-12-11T04:38:49.5622227Z {'branch_source': 'CICDTesting',
2024-12-11T04:38:49.5622807Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_credentials\azd_cli.py", line 140, in get_token
2024-12-11T04:38:49.5623225Z  'branch_target': 'UAT',
2024-12-11T04:38:49.5623713Z     output = _run_command(command, self._process_timeout)
2024-12-11T04:38:49.5624092Z  'models': ['Workforce_tcrf_FTE_lgbm'],
2024-12-11T04:38:49.5624656Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_credentials\azd_cli.py", line 209, in _run_command
2024-12-11T04:38:49.5625299Z  'prefix': 'wrk-tcrf'}
2024-12-11T04:38:49.5625830Z     raise CredentialUnavailableError(message=CLI_NOT_FOUND)
2024-12-11T04:38:49.5626194Z branch_source:  CICDTesting
2024-12-11T04:38:49.5626854Z azure.identity._exceptions.CredentialUnavailableError: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.
2024-12-11T04:38:49.5627374Z branch_target:  UAT
2024-12-11T04:38:49.5628020Z WARNING:azure.identity._credentials.chained:DefaultAzureCredential failed to retrieve a token from the included credentials.
2024-12-11T04:38:49.5628578Z master_feature_diff() pipe.returncode=0
2024-12-11T04:38:49.5629083Z Attempted credentials:
2024-12-11T04:38:49.5629418Z master_feature_diff() stdout=b''
2024-12-11T04:38:49.5629993Z 	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
2024-12-11T04:38:49.5630415Z master_feature_diff() stderr=b''
2024-12-11T04:38:49.5630953Z Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
2024-12-11T04:38:49.5632731Z last commit datetime of branch-2024-12-11 04:28:51+00:00
2024-12-11T04:38:49.5634223Z 	ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable. The requested identity has not been assigned to this resource. Error: Unexpected response "{'error': 'invalid_request', 'error_description': 'Identity not found'}"
2024-12-11T04:38:49.5635038Z last_commit_time_featurebranch
2024-12-11T04:38:49.5635582Z 	SharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
2024-12-11T04:38:49.5636018Z 	AzureCliCredential: Failed to invoke the Azure CLI
2024-12-11T04:38:49.5636416Z 	AzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed
2024-12-11T04:38:49.5636946Z 	AzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.
2024-12-11T04:38:49.5637550Z To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
2024-12-11T04:38:49.5637978Z Traceback (most recent call last):
2024-12-11T04:38:49.5638350Z   File "build\gatekeeper.py", line 177, in <module>
2024-12-11T04:38:49.5638734Z     main(args.prefix, args.branch_source, args.branch_target, args.models)
2024-12-11T04:38:49.5639129Z   File "build\gatekeeper.py", line 77, in main
2024-12-11T04:38:49.5639538Z     os.environ["OPENAI_API_KEY"] = auth.get_token("https://cognitiveservices.azure.com/.default").token
2024-12-11T04:38:49.5640022Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_credentials\default.py", line 225, in get_token
2024-12-11T04:38:49.5640480Z     token = super().get_token(*scopes, claims=claims, tenant_id=tenant_id, **kwargs)
2024-12-11T04:38:49.5640948Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\identity\_credentials\chained.py", line 124, in get_token
2024-12-11T04:38:49.5641391Z     raise ClientAuthenticationError(message=message)
2024-12-11T04:38:49.5641820Z azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.
2024-12-11T04:38:49.5642221Z Attempted credentials:
2024-12-11T04:38:49.5642641Z 	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
2024-12-11T04:38:49.5643108Z Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
2024-12-11T04:38:49.5643679Z 	ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable. The requested identity has not been assigned to this resource. Error: Unexpected response "{'error': 'invalid_request', 'error_description': 'Identity not found'}"
2024-12-11T04:38:49.5645067Z 	SharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
2024-12-11T04:38:49.5645500Z 	AzureCliCredential: Failed to invoke the Azure CLI
2024-12-11T04:38:49.5645888Z 	AzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed
2024-12-11T04:38:49.5646437Z 	AzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.
2024-12-11T04:38:49.5647144Z To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
2024-12-11T04:38:49.5647601Z 2024-12-11 04:28:51+00:00
2024-12-11T04:38:50.0209733Z ##[error]Cmd.exe exited with code '1'.
2024-12-11T04:38:50.1142493Z ##[section]Finishing: Run Gatekeeper.py

**Comment by xiangyan99** [comment]
Thanks for reaching out.

I am not quite clear about your question.

Could you clarify a little bit?

e.g. which type of credential did you expect to work?

**Comment by RajithaNelluru** [comment]
Workload Federated Identity Credentials need to work.

**Comment by RajithaNelluru** [comment]
Currently doing authentication via ServicePrincipal. Need to modify the code to support Workload federated identity.

**Comment by RajithaNelluru** [comment]
While doing authentication in Azure Machine Learning SDK via Workload Federated Identity - Facing the issue and getting the clientAuthentication Error.

**Comment by xiangyan99** [comment]
Thanks for the information.

Could you clarify what is the host you wanted to run the app?

On Azure AKS? Or VMs managed in ML studio?

Thanks.
