### ISSUE TITLE
Unable to Create Management Group

### ISSUE THREAD

**Issue by praveenc** [Azure/azure-sdk-for-python#3923]
Hi,

Trying to create a management group (under the Root Tenant Group) via the Python SDK results in the following error:

```
azure.mgmt.managementgroups.models.error_response_py3.ErrorResponseException: (BadRequest) Name of the group doesn't match the group id.
```

**Traceback**

```
Traceback (most recent call last):
  File "/Users/xxxx/yyyy/src/managementgroups.py", line 70, in create_management_group
    self.group_id, CreateManagementGroupRequest())
  File "/Users/xxxx/yyyy/venv/lib/python3.7/site-packages/azure/mgmt/managementgroups/operations/management_groups_operations.py", line 277, in create_or_update
    **operation_config
  File "/Users/xxxx/yyyy/venv/lib/python3.7/site-packages/azure/mgmt/managementgroups/operations/management_groups_operations.py", line 229, in _create_or_update_initial
    raise models.ErrorResponseException(self._deserialize, response)
azure.mgmt.managementgroups.models.error_response_py3.ErrorResponseException: (BadRequest) Name of the group doesn't match the group id.
Traceback (most recent call last):
  File /Users/xxxx/yyyy/src/managementgroups.py", line 70, in create_management_group
    self.group_id, CreateManagementGroupRequest())
  File "/Users/xxxx/yyyy/venv/lib/python3.7/site-packages/azure/mgmt/managementgroups/operations/management_groups_operations.py", line 277, in create_or_update
    **operation_config
  File "/Users/xxxx/yyyy/venv/lib/python3.7/site-packages/azure/mgmt/managementgroups/operations/management_groups_operations.py", line 229, in _create_or_update_initial
    raise models.ErrorResponseException(self._deserialize, response)
azure.mgmt.managementgroups.models.error_response_py3.ErrorResponseException: (BadRequest) Name of the group doesn't match the group id.
```

**Implementation**

```
import logging
from azure.common.credentials import ServicePrincipalCredentials
from azure.mgmt.managementgroups import ManagementGroupsAPI
from azure.mgmt.managementgroups.models import CreateManagementGroupRequest

class ManagementGroup(object):

    def __init__(self, group_id, parent_id=None):
        """
        :param group_id: The friendly name of the management group.
        :type group_id: str
        :param parent_id: Name of the parent management group if
         this is a child management group.
        :type parent_id: str
        """

        if not parent_id:
            self.parent_id = 'Tenant Root Group'
        else:
            self.parent_id = parent_id
        self.group_id = group_id
        # self.group_id = '{}/{}/{}'.format(resource_type, self.parent_id,
        #                                       group_id)
        # self.group_id = '{}/{}'.format(self.parent_id, group_id)
        self.subscription_id = os.environ['AZURE_SUBSCRIPTION_ID']
        self.client_id = os.environ['AZURE_CLIENT_ID']
        self.client_secret = os.environ['AZURE_CLIENT_SECRET']
        self.tenant_id = os.environ['AZURE_TENANT_ID']

    def get_credentials(self):
        """Returns ServicePrincipal Credentials Object."""
        try:
            credentials = ServicePrincipalCredentials(
                client_id=self.client_id,
                secret=self.client_secret,
                tenant=self.tenant_id,
            )
            return credentials
        except Exception as e:
            logging.error('Credentials Error!!', exc_info=True)
            raise SystemExit("Error Creating Credentials!")

   def create_management_group(self, parent_id=None):
        """Creates a Management Group."""
        credentials = self.get_credentials()
        try:
            client = ManagementGroupsAPI(credentials)
            op_sync = client.management_groups.create_or_update(
                self.group_id, CreateManagementGroupRequest())
            op_sync.wait()
        except Exception:
            logging.error('Error creating mgmt_group: %s', self.group_id, exc_info=True)
            raise SystemExit("Management Group Creation Failed!")

## -- Caller ---
    ...
    # Initialize the deployer class
    deployer = ManagementGroup('test-mgmt-group')
    deployer.create_management_group()
    ...
```

_NOTE_ : I ensured that the Service Principal is assigned `Management Group Contributor` role - Here's the output

```
PS /Users/xxx> New-AzureRmRoleAssignment -ObjectId xxxxxxxxxxxx -RoleDefinitionId 5d58bcaf-24a5-4b20-bdb6-eed9f69fbe4c -Scope '/providers/Microsoft.Management/managementGroups/Tenant Root Group'


RoleAssignmentId   : /providers/Microsoft.Management/managementGroups/Tenant Root Group/providers/Microsoft.Authorization/roleAssignments/yyyyyy-xxxxx-yyyy
Scope              : /providers/Microsoft.Management/managementGroups/Tenant Root Group
DisplayName        : MGMSP
SignInName         :
RoleDefinitionName : Management Group Contributor
RoleDefinitionId   : 5d58bcaf-24a5-4b20-bdb6-eed9f69fbe4c
ObjectId           : 21a7d7b8-bd26-4e52-bea8-62be5af14585
ObjectType         : ServicePrincipal
CanDelegate        : False
```

Not sure, what I'm doing wrong here - appreciate any pointers.

Thanks in advance

**Comment by praveenc** [comment]
hi, Any idea what's going on with this?

**Comment by jorgecotillo** [comment]
In case you haven't found the solution, I think your issue is in this line:

op_sync = client.management_groups.create_or_update(
                self.group_id, CreateManagementGroupRequest())

You are passing an empty Management Group Request object, what you need to do is something like this:

management_group_request = CreateManagementGroupRequest()
management_group_request.name = self.group_id

op_sync = client.management_groups.create_or_update(
                self.group_id, management_group_request)

As the error refers, the name and the id properties don't match. 
Just so you know, name property is different than display_name, and these values can be different (actually the portal allows you to set different values).

Hope it helps.

**Comment by lmazuel** [comment]
Thanks @jorgecotillo !
Closing since I believe it solves the issue, but feel to comment on it if not.
Thanks!
