### ISSUE TITLE
InvalidApiVersionParameter while trying to fetch VNET Peerings

### ISSUE THREAD

**Issue by kmai** [Azure/azure-sdk-for-python#4091]
```
Traceback (most recent call last):
  File "test.py", line 126, in <module>
    for peering in list(vnet_peerings):
  File "/Users/kmai/.virtualenvs/transit-network-tools/lib/python3.7/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/Users/kmai/.virtualenvs/transit-network-tools/lib/python3.7/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/Users/kmai/.virtualenvs/transit-network-tools/lib/python3.7/site-packages/azure/mgmt/network/v2018_10_01/operations/virtual_network_peerings_operations.py", line 355, in internal_paging
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: InvalidApiVersionParameter
Message: The api-version '2018-10-01' is invalid. The supported versions are '2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
```

PIP Freeze:
```
adal==1.2.0
antlr4-python3-runtime==4.7.1
applicationinsights==0.11.7
appnope==0.1.0
argcomplete==1.9.4
asn1crypto==0.24.0
azure-cli-core==2.0.52
azure-cli-nspkg==3.0.3
azure-cli-telemetry==1.0.0
azure-common==1.1.16
azure-mgmt-network==2.4.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-resource==2.0.0
azure-nspkg==3.0.2
backcall==0.1.0
bcrypt==3.1.5
bokeh==1.0.2
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
colorama==0.4.1
cryptography==2.4.2
cycler==0.10.0
decorator==4.3.0
holoviews==1.10.9
humanfriendly==4.17
idna==2.8
ipython==7.2.0
ipython-genutils==0.2.0
isodate==0.6.0
jedi==0.13.2
Jinja2==2.10
jmespath==0.9.3
jsonschema==2.6.0
jupyter-core==4.4.0
kiwisolver==1.0.1
knack==0.5.1
MarkupSafe==1.1.0
matplotlib==3.0.2
msrest==0.6.2
msrestazure==0.6.0
nbformat==4.4.0
netaddr==0.7.19
networkx==2.2
numpy==1.15.4
oauthlib==2.1.0
packaging==18.0
pandas==0.23.4
param==1.8.1
paramiko==2.4.2
parso==0.3.1
pexpect==4.6.0
pickleshare==0.7.5
Pillow==5.3.0
plotly==3.4.2
portalocker==1.2.1
prompt-toolkit==2.0.7
ptyprocess==0.6.0
pyasn1==0.4.4
pycparser==2.19
Pygments==2.3.1
PyJWT==1.7.1
PyNaCl==1.3.0
pyOpenSSL==18.0.0
pyparsing==2.3.0
python-dateutil==2.7.5
pytz==2018.7
pyviz-comms==0.6.0
PyYAML==3.13
requests==2.21.0
requests-oauthlib==1.0.0
retrying==1.3.3
six==1.12.0
tabulate==0.8.2
tornado==5.1.1
traitlets==4.3.2
urllib3==1.24.1
wcwidth==0.1.7
```

**Comment by lmazuel** [comment]
Hi @kmai 
I'm sending an email to Network team right now to try to understand what's happening.
In the meantime, you can workaround it:
``` python
profile = {
    None: '2018-10-01',
    'virtual_network_peerings': '2018-08-01' 
}
client = NetworkManagementClient(credentials, subscription_id, profile=profile)
```

**Comment by fengzhou-msft** [comment]
Close due to inactivity. Please issue a new ticket if you have issues.
