### ISSUE TITLE
unable to swap osdisk with Azure Python SDK 3.0.0 version

### ISSUE THREAD

**Issue by dikadali** [Azure/azure-sdk-for-python#4150]
Hello,

we are getting below error while swaping the osdisk for a vm with Azure python SDK 3.0.0. But it is working in version 4.0.0. May know if this is supported or it can be fixed. 

thanks in advance.

**python code:** 
```
vm.storage_profile.os_disk.managed_disk.id = new_os_disk.id
vm.storage_profile.os_disk.name = new_os_disk.name
computeclient.virtual_machines.create_or_update(
		'rgname',
		vm.name,
		vm
)
we are able to retrieve object  values but can't update it
print(vm.storage_profile.os_disk.managed_disk.id)
print(vm.storage_profile.os_disk.name)
```

**Error :** 

Traceback (most recent call last):
  File "C:\Users\dikadali\AppData\Local\Programs\Python\Python37-32\lib\site-packages\msrestazure\azure_operation.py", line 354, in __init__
    self._operation.set_initial_status(self._response)
  File "C:\Users\dikadali\AppData\Local\Programs\Python\Python37-32\lib\site-packages\msrestazure\azure_operation.py", line 230, in set_initial_status
    self._raise_if_bad_http_status_and_method(response)
  File "C:\Users\dikadali\AppData\Local\Programs\Python\Python37-32\lib\site-packages\msrestazure\azure_operation.py", line 148, in _raise_if_bad_http_status_and_method
    "Invalid return status for {!r} operation".format(self.method))
msrestazure.azure_operation.BadStatus: Invalid return status for 'PUT' operation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "swap_method2.py", line 76, in <module>
    vm
  File "C:\Users\dikadali\AppData\Local\Programs\Python\Python37-32\lib\site-packages\azure\mgmt\compute\v2017_03_30\operations\virtual_machines_operations.py", line 232, in create_or_update
    get_long_running_status, long_running_operation_timeout)
  File "C:\Users\dikadali\AppData\Local\Programs\Python\Python37-32\lib\site-packages\msrestazure\azure_operation.py", line 357, in __init__
    raise CloudError(self._response)
msrestazure.azure_exceptions.CloudError: Azure Error: PropertyChangeNotAllowed
Message: Changing property 'osDisk.name' is not allowed.
Target: osDisk.name

**Comment by lmazuel** [comment]
@yugangw-msft any opinion here?

**Comment by yugangw-msft** [comment]
I believe this os_disk swap doesn't come with the older api-version likely the 3.0 has

**Comment by lmazuel** [comment]
Hi @dikadali 
Since @yugangw-msft confirmed, this was a feature introduced in recent api-version that we can't support for old one, and then we cannot lake it back to 3.x series. Sorry about the inconvenience it might cause.
Thank you

**Comment by dikadali** [comment]
@yugangw-msft -- Thanks for confirmation. 
May I know if any alternate procedure to do swap osdisk with python SDK 3.0?
