### ISSUE TITLE
Missing message in the thrown exception of service error 

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-python#423]
My `create_hosted_service` call is throwing exception:

```py
Traceback (most recent call last):
  File "./main.py", line 145, in <module>
    main()
  File "./main.py", line 30, in main
    deploy_test(client, TEST_HS_NAME)
  File "./main.py", line 50, in deploy_test
    location=TEST_LOCATION)
  File "/Users/alp/workspace/.virtualenvs/docker-ext/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementservice.py", line 379, in create_hosted_service
    async=True)
  File "/Users/alp/workspace/.virtualenvs/docker-ext/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementclient.py", line 343, in _perform_post
    response = self.perform_post(path, body, x_ms_version)
  File "/Users/alp/workspace/.virtualenvs/docker-ext/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementclient.py", line 185, in perform_post
    response = self._perform_request(request)
  File "/Users/alp/workspace/.virtualenvs/docker-ext/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementclient.py", line 300, in _perform_request
    return _management_error_handler(ex)
  File "/Users/alp/workspace/.virtualenvs/docker-ext/lib/python2.7/site-packages/azure/servicemanagement/__init__.py", line 2036, in _management_error_handler
    return _general_error_handler(http_error)
  File "/Users/alp/workspace/.virtualenvs/docker-ext/lib/python2.7/site-packages/azure/__init__.py", line 543, in _general_error_handler
    _ERROR_CONFLICT.format(str(http_error)))
azure.WindowsAzureConflictError: Conflict (Conflict)
```

I see that `Conflict` (ErrorCode) makes it to the exception but there is no `Message` here. If it was containing the message, I could have just used that as the output of my program.

When I `print e.message, e.args` it prints `Conflict (Conflict)`. It looks like there's a bug causing Message to not to flow to the output (instead it used ErrorCode). I cannot debug and see what is the actual failure just because of this and I'm blocked.

Can you please prioritize?

**Comment by ahmetalpbalkan** [comment]
More info about the stack that builds the error:

```
In [103]: sms.delete_hosted_service('dockerext-ci', True)

---------------------------------------------------------------------------
WindowsAzureConflictError                 Traceback (most recent call last)
<ipython-input-103-3b7254049e3a> in <module>()
----> 1 sms.delete_hosted_service('dockerext-ci', True)

/Users/alp/workspace/.virtualenvs/junk/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementservice.pyc in delete_hosted_service(self, service_name, complete)
    430             path = path +'?comp=media'
    431
--> 432         return self._perform_delete(path, async=True)
    433
    434     def get_deployment_by_slot(self, service_name, deployment_slot):

/Users/alp/workspace/.virtualenvs/junk/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementclient.pyc in _perform_delete(self, path, async, x_ms_version)
    352
    353     def _perform_delete(self, path, async=False, x_ms_version=None):
--> 354         response = self.perform_delete(path, x_ms_version)
    355
    356         if async:

/Users/alp/workspace/.virtualenvs/junk/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementclient.pyc in perform_delete(self, path, x_ms_version)
    204         request.path, request.query = _update_request_uri_query(request)
    205         request.headers = self._update_management_header(request, x_ms_version)
--> 206         response = self._perform_request(request)
    207
    208         return response

/Users/alp/workspace/.virtualenvs/junk/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementclient.pyc in _perform_request(self, request)
    298             resp = self._filter(request)
    299         except HTTPError as ex:
--> 300             return _management_error_handler(ex)
    301
    302         return resp

/Users/alp/workspace/.virtualenvs/junk/lib/python2.7/site-packages/azure/servicemanagement/__init__.pyc in _management_error_handler(http_error)
   2034 def _management_error_handler(http_error):
   2035     ''' Simple error handler for management service. '''
-> 2036     return _general_error_handler(http_error)
   2037
   2038

/Users/alp/workspace/.virtualenvs/junk/lib/python2.7/site-packages/azure/__init__.pyc in _general_error_handler(http_error)
    541     if http_error.status == 409:
    542         raise WindowsAzureConflictError(
--> 543             _ERROR_CONFLICT.format(str(http_error)))
    544     elif http_error.status == 404:
    545         raise WindowsAzureMissingResourceError(

WindowsAzureConflictError: Conflict (Conflict)
```

**Comment by lmazuel** [comment]
Hello,

Sorry for this late answer...
Have you still this problem? Could you update your code to the latest Azure version? Version 1.0 provides a big change in the SDK, and I would like to check if the problem is still visible before trying to reproduce it.

Thank you,

**Comment by ahmetalpbalkan** [comment]
Alright then.
