### ISSUE TITLE
ContainerServiceClient.managed_clusters.create causes too many 500 error responses

### ISSUE THREAD

**Issue by dbkegley** [Azure/azure-sdk-for-python#4370]
I'm trying to create a `ManagedCluster` using the python sdk and I'm getting the following errors when calling the azure apis using the `ContainerServiceClient`

error:
```
Traceback (most recent call last):
  File "./managed_cluster.py", line 53, in <module>
    parameters={'location': REGION}
  File ".../env/lib/python2.7/site-packages/azure/mgmt/containerservice/v2018_03_31/operations/managed_clusters_operations.py", line 599, in create_or_update
    **operation_config
  File ".../env/lib/python2.7/site-packages/azure/mgmt/containerservice/v2018_03_31/operations/managed_clusters_operations.py", line 545, in _create_or_update_initial
    response = self._client.send(request, stream=False, **operation_config)
  File ".../env/lib/python2.7/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File ".../env/lib/python2.7/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File ".../env/lib/python2.7/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File ".../env/lib/python2.7/site-packages/msrest/pipeline/requests.py", line 72, in send
    return self.next.send(request, **kwargs)
  File ".../env/lib/python2.7/site-packages/msrest/pipeline/requests.py", line 137, in send
    return self.next.send(request, **kwargs)
  File ".../env/lib/python2.7/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File ".../env/lib/python2.7/site-packages/msrest/pipeline/requests.py", line 193, in send
    self.driver.send(request.http_request, **kwargs)
  File ".../env/lib/python2.7/site-packages/msrest/universal_http/requests.py", line 328, in send
    return super(RequestsHTTPSender, self).send(request, **requests_kwargs)
  File ".../env/lib/python2.7/site-packages/msrest/universal_http/requests.py", line 140, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File ".../env/lib/python2.7/site-packages/msrest/exceptions.py", line 54, in raise_with_traceback
    raise error
msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/<redacted>/resourceGroups/kubernetes2/providers/Microsoft.ContainerService/managedClusters/kubernetes2?api-version=2018-03-31 (Caused by ResponseError('too many 500 error responses',))
```

code: 
```python
import json

from azure.mgmt.resource import ResourceManagementClient
from azure.mgmt.containerservice import ContainerServiceClient
from azure.common.credentials import ServicePrincipalCredentials
from msrestazure.azure_cloud import AZURE_PUBLIC_CLOUD

GROUP_NAME = 'kubernetes2' # cluster_name
REGION = 'eastus'
subscription_id = '<redacted>'

with open('./sp.json') as f:
        creds = json.loads(f.read())

credentials = ServicePrincipalCredentials(
        client_id=creds['appId'],
        secret=creds['password'],
        tenant=creds['tenant'],
        cloud_environment=AZURE_PUBLIC_CLOUD)

container_client = ContainerServiceClient(credentials, subscription_id)
resource_client = ResourceManagementClient(credentials, subscription_id)

resource_client.resource_groups.create_or_update(GROUP_NAME, {'location': REGION})
managed_cluster_create = container_client.managed_clusters.create_or_update(
  resource_group_name=GROUP_NAME,
  resource_name=GROUP_NAME,
  parameters={'location': REGION}
)
managed_cluster_create.wait()
```

env: 
```
$ pip freeze | grep azure
azure==4.0.0
azure-applicationinsights==0.1.0
azure-batch==4.1.3
azure-common==1.1.18
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.5
azure-datalake-store==0.0.41
azure-eventgrid==1.2.0
azure-graphrbac==0.40.0
azure-keyvault==1.1.0
azure-loganalytics==0.1.0
azure-mgmt==4.0.0
azure-mgmt-advisor==1.0.1
azure-mgmt-applicationinsights==0.1.1
azure-mgmt-authorization==0.50.0
azure-mgmt-batch==5.0.1
azure-mgmt-batchai==2.0.0
azure-mgmt-billing==0.2.0
azure-mgmt-cdn==3.0.0
azure-mgmt-cognitiveservices==3.0.0
azure-mgmt-commerce==1.0.1
azure-mgmt-compute==4.4.0
azure-mgmt-consumption==2.0.0
azure-mgmt-containerinstance==1.4.0
azure-mgmt-containerregistry==2.7.0
azure-mgmt-containerservice==4.4.0
azure-mgmt-cosmosdb==0.4.1
azure-mgmt-datafactory==0.6.0
azure-mgmt-datalake-analytics==0.6.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-datamigration==1.0.0
azure-mgmt-devspaces==0.1.0
azure-mgmt-devtestlabs==2.2.0
azure-mgmt-dns==2.1.0
azure-mgmt-eventgrid==1.0.0
azure-mgmt-eventhub==2.3.0
azure-mgmt-hanaonazure==0.1.1
azure-mgmt-iotcentral==0.1.0
azure-mgmt-iothub==0.5.0
azure-mgmt-iothubprovisioningservices==0.2.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-loganalytics==0.2.0
azure-mgmt-logic==3.0.0
azure-mgmt-machinelearningcompute==0.4.1
azure-mgmt-managementgroups==0.1.0
azure-mgmt-managementpartner==0.1.0
azure-mgmt-maps==0.1.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-media==1.0.0
azure-mgmt-monitor==0.5.2
azure-mgmt-msi==0.2.0
azure-mgmt-network==2.5.1
azure-mgmt-notificationhubs==2.0.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-policyinsights==0.1.0
azure-mgmt-powerbiembedded==2.0.0
azure-mgmt-rdbms==1.5.0
azure-mgmt-recoveryservices==0.3.0
azure-mgmt-recoveryservicesbackup==0.3.0
azure-mgmt-redis==5.0.0
azure-mgmt-relay==0.1.0
azure-mgmt-reservations==0.2.1
azure-mgmt-resource==2.1.0
azure-mgmt-scheduler==2.0.0
azure-mgmt-search==2.0.0
azure-mgmt-servicebus==0.5.3
azure-mgmt-servicefabric==0.2.0
azure-mgmt-signalr==0.1.1
azure-mgmt-sql==0.9.1
azure-mgmt-storage==2.0.0
azure-mgmt-subscription==0.2.0
azure-mgmt-trafficmanager==0.50.0
azure-mgmt-web==0.35.0
azure-nspkg==3.0.2
azure-servicebus==0.21.1
azure-servicefabric==6.3.0.0
azure-servicemanagement-legacy==0.20.6
azure-storage-blob==1.4.0
azure-storage-common==1.4.0
azure-storage-file==1.4.0
azure-storage-nspkg==3.1.0
azure-storage-queue==1.4.0
msrestazure==0.6.0
```

There's also an ActivityLog entry in the Azure console with a server-side stacktrace that I can send along if needed

**Comment by lmazuel** [comment]
@mboersma it seems we get a lot of 500 errors from the endpoint, any idea why? Anything that could be help to understand what's happening?

**Comment by mboersma** [comment]
I tried the above python script and I see the same result. I added:

```
import logging
logging.basicConfig(level=logging.DEBUG)
```

to the top of the script, but the debug output isn't very illuminating:

```
$ python sdktest.py 
INFO:keyring.backend:Loading KWallet
INFO:keyring.backend:Loading SecretService
INFO:keyring.backend:Loading Windows
INFO:keyring.backend:Loading chainer
INFO:keyring.backend:Loading macOS
DEBUG:requests_oauthlib.oauth2_session:Encoding `client_id` "<client_id>" with `client_secret` as Basic auth credentials.
DEBUG:requests_oauthlib.oauth2_session:Requesting url https://login.microsoftonline.com/<tenant_id>/oauth2/token using method POST.
DEBUG:requests_oauthlib.oauth2_session:Supplying headers {'Accept': 'application/json', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'} and data {'grant_type': 'client_credentials', 'resource': 'https://management.core.windows.net/', 'response_type': 'client_credentials'}
DEBUG:requests_oauthlib.oauth2_session:Passing through key word arguments {'json': None, 'timeout': None, 'auth': <requests.auth.HTTPBasicAuth object at 0x10fd63eb8>, 'verify': True, 'proxies': None}.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): login.microsoftonline.com:443
DEBUG:urllib3.connectionpool:https://login.microsoftonline.com:443 "POST /<tenant_id>/oauth2/token HTTP/1.1" 200 1354
DEBUG:requests_oauthlib.oauth2_session:Prepared fetch token request body grant_type=client_credentials&resource=https%3A%2F%2Fmanagement.core.windows.net%2F&response_type=client_credentials
DEBUG:requests_oauthlib.oauth2_session:Request to fetch token completed with status 200.
DEBUG:requests_oauthlib.oauth2_session:Request headers were {'User-Agent': 'python-requests/2.21.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8', 'Content-Length': '116', 'Authorization': 'Basic YTRlN<redacted>Q4Ng=='}
DEBUG:requests_oauthlib.oauth2_session:Request body was grant_type=client_credentials&resource=https%3A%2F%2Fmanagement.core.windows.net%2F&response_type=client_credentials
DEBUG:requests_oauthlib.oauth2_session:Response headers were {'Cache-Control': 'no-cache, no-store', 'Pragma': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'Expires': '-1', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'x-ms-request-id': '<request_id>', 'P3P': 'CP="DSP CUR OTPi IND OTRi ONL FIN"', 'Set-Cookie': 'fpc=AUxPJVdzLqxImoHM0fvjusXurE--AQDBhSFAgZPWCA; expires=Sun, 17-Mar-2019 20:07:45 GMT; path=/; secure; HttpOnly, x-ms-gateway-slice=prod; path=/; secure; HttpOnly, stsservicecookie=ests; path=/; secure; HttpOnly', 'Date': 'Fri, 15 Feb 2019 20:07:44 GMT', 'Content-Length': '1354'} and content {"token_type":"Bearer","expires_in":"3600","ext_expires_in":"3600","expires_on":"1550264865","not_before":"1550260965","resource":"https://management.core.windows.net/","access_token":"<token>"}.
DEBUG:requests_oauthlib.oauth2_session:Invoking 0 token response hooks.
DEBUG:requests_oauthlib.oauth2_session:Obtained token {'token_type': 'Bearer', 'expires_in': '3600', 'ext_expires_in': '3600', 'expires_on': '1550264865', 'not_before': '1550260965', 'resource': 'https://management.core.windows.net/', 'access_token': '<token>', 'expires_at': 1550264865.696496}.
DEBUG:msrest.universal_http.requests:Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
DEBUG:msrest.universal_http.requests:Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
DEBUG:msrest.universal_http:Configuring redirects: allow=True, max=30
DEBUG:msrest.universal_http:Configuring request: timeout=100, verify=True, cert=None
DEBUG:msrest.universal_http:Configuring proxies: ''
DEBUG:msrest.universal_http:Evaluate proxies against ENV settings: True
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): management.azure.com:443
DEBUG:urllib3.connectionpool:https://management.azure.com:443 "PUT /subscriptions/<subscription_id>/resourcegroups/kubernetes2?api-version=2018-05-01 HTTP/1.1" 201 175
DEBUG:msrest.universal_http:Configuring redirects: allow=True, max=30
DEBUG:msrest.universal_http:Configuring request: timeout=100, verify=True, cert=None
DEBUG:msrest.universal_http:Configuring proxies: ''
DEBUG:msrest.universal_http:Evaluate proxies against ENV settings: True
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): management.azure.com:443
DEBUG:urllib3.connectionpool:https://management.azure.com:443 "PUT /subscriptions/<subscription_id>/resourceGroups/kubernetes2/providers/Microsoft.ContainerService/managedClusters/kubernetes2?api-version=2018-03-31 HTTP/1.1" 500 4667
DEBUG:urllib3.util.retry:Incremented Retry for (url='/subscriptions/<subscription_id>/resourceGroups/kubernetes2/providers/Microsoft.ContainerService/managedClusters/kubernetes2?api-version=2018-03-31'): Retry(total=3, connect=4, read=4, redirect=None, status=None)
DEBUG:urllib3.connectionpool:Retry: /subscriptions/<subscription_id>/resourceGroups/kubernetes2/providers/Microsoft.ContainerService/managedClusters/kubernetes2?api-version=2018-03-31
DEBUG:urllib3.connectionpool:Resetting dropped connection: management.azure.com
DEBUG:urllib3.connectionpool:https://management.azure.com:443 "PUT /subscriptions/<subscription_id>/resourceGroups/kubernetes2/providers/Microsoft.ContainerService/managedClusters/kubernetes2?api-version=2018-03-31 HTTP/1.1" 500 4667
DEBUG:urllib3.util.retry:Incremented Retry for (url='/subscriptions/<subscription_id>/resourceGroups/kubernetes2/providers/Microsoft.ContainerService/managedClusters/kubernetes2?api-version=2018-03-31'): Retry(total=2, connect=4, read=4, redirect=None, status=None)
DEBUG:urllib3.connectionpool:Retry: /subscriptions/<subscription_id>/resourceGroups/kubernetes2/providers/Microsoft.ContainerService/managedClusters/kubernetes2?api-version=2018-03-31
DEBUG:urllib3.connectionpool:Resetting dropped connection: management.azure.com
DEBUG:urllib3.connectionpool:https://management.azure.com:443 "PUT /subscriptions/<subscription_id>/resourceGroups/kubernetes2/providers/Microsoft.ContainerService/managedClusters/kubernetes2?api-version=2018-03-31 HTTP/1.1" 500 4667
DEBUG:urllib3.util.retry:Incremented Retry for (url='/subscriptions/<subscription_id>/resourceGroups/kubernetes2/providers/Microsoft.ContainerService/managedClusters/kubernetes2?api-version=2018-03-31'): Retry(total=1, connect=4, read=4, redirect=None, status=None)
DEBUG:urllib3.connectionpool:Retry: /subscriptions/<subscription_id>/resourceGroups/kubernetes2/providers/Microsoft.ContainerService/managedClusters/kubernetes2?api-version=2018-03-31
DEBUG:urllib3.connectionpool:Resetting dropped connection: management.azure.com
DEBUG:urllib3.connectionpool:https://management.azure.com:443 "PUT /subscriptions/<subscription_id>/resourceGroups/kubernetes2/providers/Microsoft.ContainerService/managedClusters/kubernetes2?api-version=2018-03-31 HTTP/1.1" 500 4666
DEBUG:urllib3.util.retry:Incremented Retry for (url='/subscriptions/<subscription_id>/resourceGroups/kubernetes2/providers/Microsoft.ContainerService/managedClusters/kubernetes2?api-version=2018-03-31'): Retry(total=0, connect=4, read=4, redirect=None, status=None)
DEBUG:urllib3.connectionpool:Retry: /subscriptions/<subscription_id>/resourceGroups/kubernetes2/providers/Microsoft.ContainerService/managedClusters/kubernetes2?api-version=2018-03-31
DEBUG:urllib3.connectionpool:Resetting dropped connection: management.azure.com
DEBUG:urllib3.connectionpool:https://management.azure.com:443 "PUT /subscriptions/<subscription_id>/resourceGroups/kubernetes2/providers/Microsoft.ContainerService/managedClusters/kubernetes2?api-version=2018-03-31 HTTP/1.1" 500 4667
DEBUG:msrest.exceptions:Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/<subscription_id>/resourceGroups/kubernetes2/providers/Microsoft.ContainerService/managedClusters/kubernetes2?api-version=2018-03-31 (Caused by ResponseError('too many 500 error responses'))
Traceback (most recent call last):
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  [Previous line repeated 1 more time]
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/<subscription_id>/resourceGroups/kubernetes2/providers/Microsoft.ContainerService/managedClusters/kubernetes2?api-version=2018-03-31 (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/msrest/universal_http/requests.py", line 137, in send
    **kwargs)
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/<subscription_id>/resourceGroups/kubernetes2/providers/Microsoft.ContainerService/managedClusters/kubernetes2?api-version=2018-03-31 (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sdktest.py", line 31, in <module>
    parameters={'location': REGION}
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/azure/mgmt/containerservice/v2018_03_31/operations/managed_clusters_operations.py", line 599, in create_or_update
    **operation_config
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/azure/mgmt/containerservice/v2018_03_31/operations/managed_clusters_operations.py", line 545, in _create_or_update_initial
    response = self._client.send(request, stream=False, **operation_config)
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/msrest/pipeline/requests.py", line 72, in send
    return self.next.send(request, **kwargs)
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/msrest/pipeline/requests.py", line 137, in send
    return self.next.send(request, **kwargs)
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/msrest/pipeline/requests.py", line 193, in send
    self.driver.send(request.http_request, **kwargs)
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/msrest/universal_http/requests.py", line 328, in send
    return super(RequestsHTTPSender, self).send(request, **requests_kwargs)
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/msrest/universal_http/requests.py", line 140, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/msrest/universal_http/requests.py", line 137, in send
    **kwargs)
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/matt/Projects/azure-cli/env/lib/python3.7/site-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/<subscription_id>/resourceGroups/kubernetes2/providers/Microsoft.ContainerService/managedClusters/kubernetes2?api-version=2018-03-31 (Caused by ResponseError('too many 500 error responses'))
```

I'll dig deeper and see if I can locate the server-side error.

**Comment by mboersma** [comment]
This actually appears to be causing a panic on the server. (Nice find!) I assume there is something about the payload that's missing but not truly optional, but I don't yet see what that is.

**Comment by dbkegley** [comment]
@mboersma Thanks for taking a deeper look, any luck diagnosing this issue?

**Comment by dbkegley** [comment]
I was able to get this working with a request like the following:

```python
managed_cluster_create = container_client.managed_clusters.create_or_update(
  resource_group_name=GROUP_NAME,
  resource_name='{}-cluster'.format(GROUP_NAME),
  parameters={
    'location': REGION,
    'tags': {
      'b23_managed': 'True'
    },
    'kubernetes_version': '1.12.5',
    'dns_prefix': 'b23-aks-test-cluster',
    'enable_rbac': 'True',
    'agent_pool_profiles': [{ # azure.mgmt.containerservice.v2018_03_31.models.ManagedClusterAgentPoolProfile
      'name': 'defaultpool',
      'count': 1,
      'vm_size': 'Standard_A1', # azure.mgmt.containerservice.v2018_03_31.models.ContainerServiceVMSizeTypes
      'os_disk_size_gb': 0
    }],
    'service_principal_profile': { # azure.mgmt.containerservice.v2018_03_31.models.ManagedClusterServicePrincipalProfile
      'client_id': CLIENT_ID,
      'secret': CLIENT_SECRET
    }
  }
)
```

**Comment by lmazuel** [comment]
@mboersma should I close the Python issue and let you create a more server one? I think we agree that it's not a Python issue? Or maybe you think something that should be changed in the Swagger? Thoughts?

**Comment by mboersma** [comment]
@lmazuel I do think it could be a problem in the swagger, if we're allowing something invalid to pass through. Let's leave this open until I've determined that. Sorry for my slow response--I'll get after this today.

**Comment by lmazuel** [comment]
Thanks @mboersma ! I believe a regexp is what we need to check client side the name:
https://github.com/Azure/azure-rest-api-specs/blob/c8b825f5e12855c9b5ff29e144bf35a85f607e4a/specification/common-types/resource-management/v1/types.json#L296

**Comment by NabeelZaidi** [comment]
Any update on this?

**Comment by lilyjma** [comment]
@zikalino, @mboersma  do we have updates on this?

**Comment by xiangyan99** [comment]
@dbkegley  latest azure-mgmt-containerservice is 16.4.0. Does it work for you?

**Comment by xiangyan99** [comment]
@dbkegley Thank you for the response. We will close the issue and please feel free to reopen it if it is reproed again.
