### ISSUE TITLE
load_balancers.create_or_update failed with sku set

### ISSUE THREAD

**Issue by nergalex** [Azure/azure-sdk-for-python#4508]
Hi,

Do you have a fix for this problem described below ?

### Condition
load_balancers.create_or_update() operation failed when 'sku' parameter is set.
### Workaround
do not set 'sku'
### Impact
cannot use 'sku' with a 'Standard' value
### Symptom
LoadBalancer class testing value :
```json
{
    "backend_address_pools": [
        {
            "name": "pool-adc-external-vs01"
        }
    ],
    "frontend_ip_configurations": [
        {
            "name": "vip-vs-adc-external-01",
            "public_ip_address": {
                "id": "/subscriptions/XXX/resourceGroups/rg-hub/providers/Microsoft.Network/publicIPAddresses/vip-adc-external-01-cloudbuilder"
            }
        }
    ],
    "location": "francecentral",
    "probes": [
        {
            "interval_in_seconds": 5,
            "name": "monitor-vs-adc-external-01",
            "number_of_probes": 2,
            "port": 443,
            "protocol": "Tcp"
        }
    ],
    "sku": "Basic",
    "tags": {
        "Name": "vs-adc-external-01"
    }
}
```

```python
Traceback (most recent call last):
  File "C:\XXX\CloudBuilder\venv\lib\site-packages\msrest\serialization.py", line 1288, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "C:\XXX\CloudBuilder\venv\lib\site-packages\msrest\serialization.py", line 1078, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "C:\XXX\CloudBuilder\venv\lib\site-packages\msrest\serialization.py", line 1101, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\XXX\CloudBuilder\venv\lib\site-packages\msrest\serialization.py", line 571, in body
    data = deserializer._deserialize(data_type, data)
  File "C:\XXX\CloudBuilder\venv\lib\site-packages\msrest\serialization.py", line 1294, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "C:\XXX\CloudBuilder\venv\lib\site-packages\msrest\serialization.py", line 1460, in deserialize_data
    return self._deserialize(obj_type, data)
  File "C:\XXX\CloudBuilder\venv\lib\site-packages\msrest\serialization.py", line 1298, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "C:\XXX\CloudBuilder\venv\lib\site-packages\msrest\exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "C:\XXX\CloudBuilder\venv\lib\site-packages\msrest\serialization.py", line 1288, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "C:\XXX\CloudBuilder\venv\lib\site-packages\msrest\serialization.py", line 1078, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "C:\XXX\CloudBuilder\venv\lib\site-packages\msrest\serialization.py", line 1101, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/XXX/CloudBuilder/test_azure.txt.py", line 752, in <module>
    load_balancers.create_or_update()
  File "C:\XXX\CloudBuilder\PocAzure\azure_network.py", line 1181, in create_or_update
    parameters=parameters)
  File "C:\XXX\CloudBuilder\venv\lib\site-packages\azure\mgmt\network\v2018_11_01\operations\load_balancers_operations.py", line 269, in create_or_update
    **operation_config
  File "C:\XXX\CloudBuilder\venv\lib\site-packages\azure\mgmt\network\v2018_11_01\operations\load_balancers_operations.py", line 215, in _create_or_update_initial
    body_content = self._serialize.body(parameters, 'LoadBalancer')
  File "C:\XXX\CloudBuilder\venv\lib\site-packages\msrest\serialization.py", line 574, in body
    SerializationError, "Unable to build a model: "+str(err), err)
  File "C:\XXX\CloudBuilder\venv\lib\site-packages\msrest\exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "C:\XXX\CloudBuilder\venv\lib\site-packages\msrest\serialization.py", line 571, in body
    data = deserializer._deserialize(data_type, data)
  File "C:\XXX\CloudBuilder\venv\lib\site-packages\msrest\serialization.py", line 1294, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "C:\XXX\CloudBuilder\venv\lib\site-packages\msrest\serialization.py", line 1460, in deserialize_data
    return self._deserialize(obj_type, data)
  File "C:\XXX\CloudBuilder\venv\lib\site-packages\msrest\serialization.py", line 1298, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "C:\XXX\CloudBuilder\venv\lib\site-packages\msrest\exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "C:\XXX\CloudBuilder\venv\lib\site-packages\msrest\serialization.py", line 1288, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "C:\XXX\CloudBuilder\venv\lib\site-packages\msrest\serialization.py", line 1078, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "C:\XXX\CloudBuilder\venv\lib\site-packages\msrest\serialization.py", line 1101, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'

Process finished with exit code 1
```

**Comment by lmazuel** [comment]
Hi @nergalex ,
It's because Sku takes a more complex object that has a name:
https://docs.microsoft.com/python/api/azure-mgmt-network/azure.mgmt.network.v2018_12_01.models.loadbalancer

```python
    "sku": {
       "name": "Basic",
    }
```

Closing the issue, but feel free to open an another issue if you have more problems!
I also created an issue in the sample repo for update:
https://github.com/Azure-Samples/network-python-manage-loadbalancer/issues/3

Thanks!
