### ISSUE TITLE
Azure HDinsight create cluster

### ISSUE THREAD

**Issue by aszykm** [Azure/azure-sdk-for-python#4546]

**Comment by aszykm** [comment]
When I created new hdinsight cluster with the identity parameters:
https://gist.github.com/aszykm/bb0d2f33da36c7b1153cf36526b7182e

I got error:
`Traceback (most recent call last):
  File "main.py", line 126, in <module>
    identity=iden_params
  File "/usr/local/lib/python3.7/site-packages/azure/mgmt/hdinsight/operations/clusters_operations.py", line 122, in create
    **operation_config
  File "/usr/local/lib/python3.7/site-packages/azure/mgmt/hdinsight/operations/clusters_operations.py", line 75, in _create_initial
    response = self._client.send(request, stream=False, **operation_config)
  File "/usr/local/lib/python3.7/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/msrest/pipeline/requests.py", line 72, in send
    return self.next.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/msrest/pipeline/requests.py", line 137, in send
    return self.next.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/msrest/pipeline/requests.py", line 193, in send
    self.driver.send(request.http_request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/msrest/universal_http/requests.py", line 328, in send
    return super(RequestsHTTPSender, self).send(request, **requests_kwargs)
  File "/usr/local/lib/python3.7/site-packages/msrest/universal_http/requests.py", line 140, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "/usr/local/lib/python3.7/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/usr/local/lib/python3.7/site-packages/msrest/universal_http/requests.py", line 137, in send
    **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/[subs]/resourceGroups/[rgn]/providers/Microsoft.HDInsight/clusters/[cluster-name]?api-version=2018-06-01-preview (Caused by ResponseError('too many 500 error responses'))`

**Comment by aszykm** [comment]
Problem is only when cluster_version is 4.0. Cluster type is Spark.

**Comment by lmazuel** [comment]
@idear1203 @wawon-msft it's a server error 500, so likely something to investigate on the server side, any thougts? Thanks!

**Comment by aszykm** [comment]
I found message in Activity log:
Failed to find an image package version for the create request.

**Comment by idear1203** [comment]
@aszykm Terribly sorry for the late reply...Does the issue still exist? This looks like a server side issue. Please open a "New support request" via Azure portal if it still exists.

**Comment by tylerfox** [comment]
I was not able to reproduce this. Please file an Azure support request if the issue still exists.
