### ISSUE TITLE
ResourceGraphClient creating invalid endpoint

### ISSUE THREAD

**Issue by awhampton** [Azure/azure-sdk-for-python#4633]
I'm getting an exception when using the ResourceGraphClient. It seems like it's building an incorrect endpoint. Stack trace (edited to remove my subscription id):

```
Traceback (most recent call last):  
File "C:\Python27\lib\site-packages\azure\mgmt\resourcegraph\resource_graph_client.py", line 120, in resources    response = self._client.send(request, stream=False, **operation_config)  
File "C:\Python27\lib\site-packages\msrest\service_client.py", line 336, in send    pipeline_response = self.config.pipeline.run(request, **kwargs)  
File "C:\Python27\lib\site-packages\msrest\pipeline\__init__.py", line 197, in run    return first_node.send(pipeline_request, **kwargs)  # type: ignore  
File "C:\Python27\lib\site-packages\msrest\pipeline\__init__.py", line 150, in send    response = self.next.send(request, **kwargs)  
File "C:\Python27\lib\site-packages\msrest\pipeline\requests.py", line 72, in send    return self.next.send(request, **kwargs)  
File "C:\Python27\lib\site-packages\msrest\pipeline\requests.py", line 137, in send    return self.next.send(request, **kwargs)  
File "C:\Python27\lib\site-packages\msrest\pipeline\__init__.py", line 150, in send    response = self.next.send(request, **kwargs)  
File "C:\Python27\lib\site-packages\msrest\pipeline\requests.py", line 193, in send    self.driver.send(request.http_request, **kwargs)  
File "C:\Python27\lib\site-packages\msrest\universal_http\requests.py", line 328, in send    return super(RequestsHTTPSender, self).send(request, **requests_kwargs) 
File "C:\Python27\lib\site-packages\msrest\universal_http\requests.py", line 140, in send    raise_with_traceback(ClientRequestError, msg, err)  
File "C:\Python27\lib\site-packages\msrest\exceptions.py", line 54, in raise_with_traceback    raise errormsrest.exceptions.ClientRequestError: Error occurred in request., MissingSchema: Invalid URL '<my_subscription_id>/providers/Microsoft.ResourceGraph/resources?api-version=2018-09-01-preview': No schema supplied. Perhaps you meant http://<my_subscription_id>/providers/Microsoft.ResourceGraph/resources?api-version=2018-09-01-preview?
```

I'm running this on an Azure Automation Runbook worker, using the latest SDK version that's packaged on PyPi. Clients for other services (e.g., MonitorManagementClient) seem to work all right in this environment.

**Comment by lmazuel** [comment]
Hi @awhampton 
Could you share your calling code?
Also, does these unittests help?
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-resourcegraph/tests/test_mgmt_resourcegraph.py

Tagging @demyanenko as well.

Thanks!

**Comment by awhampton** [comment]
Here's the calling code:

```python
resourcegraph_client = ResourceGraphClient(azure_credential, subscription_id)
qr = QueryRequest(subscriptions=[subscription_id], query="where type =~ 'Microsoft.Compute/disks'")  # the particular query doesn't affect this behavior
response = resourcegraph_client.resources(qr)
```

The credential is being obtained through the Azure Automation RunAs principal ([example](https://docs.microsoft.com/en-us/azure/automation/automation-first-runbook-textual-python2)). I can successfully hit the Resource Graph REST API with the token obtained this way, so I don't think it's an auth issue.

If I get the chance, I'll try running the unit tests in this environment and try to dig into this a bit more. Thanks! :)

**Comment by demyanenko** [comment]
Constructor for ResourceGraphClient accepts credentials and optional base_uri:
```python
class ResourceGraphClient(SDKClient):
    def __init__(self, credentials, base_url=None):
```
Here the subscription id is getting passed as a base URI, resulting in malformed request URI.
Subscriptions list should be passed in query request, this way you can use the same client for different subs as needed.

**Comment by awhampton** [comment]
Ah, sorry! Not paying enough attention. Thanks :)
