### ISSUE TITLE
CloudError: Azure Error: OperationPreempted

### ISSUE THREAD

**Issue by vishleshpatel** [Azure/azure-sdk-for-python#5167]
I have a piece of code that uses API mentioned below to create VM. However, I see my automation intermittently failing
https://docs.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2017_12_01.operations.virtualmachinesoperations?view=azure-python#create-or-update-resource-group-name--vm-name--parameters--custom-headers-none--raw-false--polling-true----operation-config-

```
2019-05-08 18:31:11,751 -      as_actions:    spin_up_instance:  50 -    INFO - Spinning up --> autoscaling-group-3
2019-05-08 18:31:18,393 -      as_actions:    spin_up_instance:  70 -    INFO - elastic_ip is 40.115.142.219
2019-05-08 18:31:18,393 -        as_azure:         spin_up_csr:1246 -    INFO - Attempt # 0
2019-05-08 18:31:18,394 -        as_azure:         spin_up_csr:1250 -    INFO - Instance Number: 3
2019-05-08 18:31:18,396 -        as_azure:     get_storage_uri:1170 -    INFO - Storage Account URI is https://foodiag.blob.core.windows.net
2019-05-08 18:31:19,589 -        as_azure:create_vm_parameters:1096 -    INFO - boot diag enabled
2019-05-08 18:31:19,589 -        as_azure:create_vm_parameters:1159 -    INFO - vm create params: {'storage_profile': {'os_disk': {'caching': 'ReadWrite', 'managedDisk': {'storageAccountType': 'Standard_LRS'}, 'createOption': 'FromImage', 'name': u'foo'}, 'image_reference': {'sku': u'16_10-payg-ax', 'publisher': 'cisco', 'version': 'latest', 'offer': 'cisco-csr-1000v'}}, 'availability_set': {'id': u'/subscriptions/**/resourceGroups/foo-rg/providers/Microsoft.Compute/availabilitySets/foo-avSet'}, 'hardware_profile': {'vm_size': u'Standard_DS2_v2'}, 'network_profile': {'network_interfaces': [{'id': u'/subscriptions/**/resourceGroups/foo-rg/providers/Microsoft.Network/networkInterfaces/nic-0', 'primary': True}, {'id': u'/subscriptions/**/resourceGroups/foo-rg/providers/Microsoft.Network/networkInterfaces/nic-1', 'primary': False}]}, 'location': 'japaneast', 'plan': {'publisher': 'cisco', 'product': 'cisco-csr-1000v', 'name': u'16_10-payg-ax'}, 'os_profile': {'admin_username': u'azureuser', 'computer_name': u'foobar', 'linuxConfiguration': {'ssh': {'publicKeys': [{'path': '/home/azureuser/.ssh/authorized_keys', 'keyData': u'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDj3W00SmRGUW1qRRH96rOYJAhl5ORj4MyhsrZ44Q14QtCN8OA2dLdngYh2TD5Pmt1fIMg8KX7wE9Hz/TpOb8PnsAIGfjNS6YAxnjwUcfug+Ecf3s6K+KzJoMDdqMGFYAwPjKzTiQfuX512e4Vh5Fzva7uwB4YW6YrSaNHCHTBjVtcZS0n/cm5gi5b3CD6t3HHddMV+K3bIRFttgBg1vzvzviYpIBB1OzaxXMj0TOEqDak06jNMmCVbeLNOYS38RgdHnyg+e8wqVbX/f+gQkOIOghVzToUp2kgzd73FPJl5bj3+LVE6GLYbMFoPM5Iix6D4FHtGKAyfXKljtUxc3kUd'}]}, 'disablePasswordAuthentication': 'true'}}, 'diagnostics_profile': {'boot_diagnostics': {'enabled': u'true', 'storage_uri': u'https://foodiag.blob.core.windows.net'}}}
2019-05-08 18:35:05,508 -        as_azure:         spin_up_csr:1337 -   ERROR - Attempt # 0, EXCEPTION: Azure Error: OperationPreempted
Message: The operation has been preempted by a more recent operation.
Traceback (most recent call last):
  File "/autoscaler/csr_cloud/as_azure.py", line 1331, in spin_up_csr
    async_vm_creation.wait()
  File "/autoscaler/msrest/polling/poller.py", line 201, in wait
    raise self._exception  # type: ignore
CloudError: Azure Error: OperationPreempted
```

I do have retries and I see that next retry failing with below error, which shows that first try tried to create VM and atleast succeed osdisk.

```
Message: Changing property 'osDisk.name' is not allowed.
Target: osDisk.name
Traceback (most recent call last):
  File "/autoscaler/csr_cloud/as_azure.py", line 1329, in spin_up_csr
    self.customer_resource_group, name, vm_params
  File "/autoscaler/azure/mgmt/compute/v2018_10_01/operations/virtual_machines_operations.py", line 298, in create_or_update
    **operation_config
  File "/autoscaler/azure/mgmt/compute/v2018_10_01/operations/virtual_machines_operations.py", line 252, in _create_or_update_initial
    raise exp
CloudError: Azure Error: PropertyChangeNotAllowed
Message: Changing property 'osDisk.name' is not allowed.
```

And in third try, it succeeds. This 2 tracebacks are to provide more info but the first traceback shall be debugged and fixed.

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by vishleshpatel** [comment]
Sure. Thanks @kurtzeborn !

**Comment by Drewm3** [comment]
First, thank you for reaching out to the Microsoft VM team. The behavior above occurs when operations are being executed on a VM which end up being serialized into the underlying azure hardware controllers. In this example, are there other operations that are being executed against the VM being created or, if the VM being created is in an AvailabilitySet, are other VMs in the same AvailabilitySet being modified? 

If other changes are being made after making the request to create a VM, then you do need to retry the VM create action or you can wait until the VM is created before making a change on related VMs.

If neither of these apply to your issue, then we recommend leveraging either Azure Support through the Azure Portal or stackoverflow [https://stackoverflow.com](url) to get more support on this issue.
