### ISSUE TITLE
Table name validation

### ISSUE THREAD

**Issue by slyons** [Azure/azure-sdk-for-python#52]
It seems that you are unable to use punctuation in table names, although it isn't clear what is and isn't allowed. 

```python
>>> ts = TableService()
>>> ts.create_table("foo")
True
>>> ts.create_table("routing_table")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\azure\storage\tableservice.py", line 135, in create_table
    _dont_fail_on_exist(e)
  File "C:\Python27\lib\site-packages\azure\__init__.py", line 453, in _dont_fail_on_exist
    raise error
azure.WindowsAzureError: Unknown error (Bad Request)
>>> ts.create_table("routingtable")
True
```

It would be nice if some sort of client-side validation was done, if possible.

**Comment by crwilcox** [comment]
Issue Migrated to https://github.com/Azure/azure-storage-python/issues/20
