### ISSUE TITLE
Read Timeout when changing local IP address

### ISSUE THREAD

**Issue by yamspog** [Azure/azure-sdk-for-python#521]
In my application, I send a message to a topic based on a local event.  This works quite well until I run into a network issue.

On the network side, my device is going through an access point that provides primary/secondary connection to the internet.  The primary connection is through an ADSL line but if that fails, it switches over to an LTE network.  When the switch-over occurs, the IP address of my device stays unchanged (as that is on the local network and assigned through DHCP).

When this switch-over occurs, I find that there is an error with the send command.  I get my local event and try to send a message to the service bus.  The first send results in a 'ReadTimeout' but a subsequent send is fine.  I then get another local event and try another send and the process repeats itself.  If I reboot the device then everything works fine.

Here is the stack-trace:

```python
File "/usr/sbin/srvc/sb.py", line 420, in <module>
ReadTimeout: HTTPSConnectionPool(host='****.servicebus.windows.net', port=443): Read timed out. (read timeout=65)
Traceback (most recent call last):
  File "/usr/sbin/srvc/sb.py", line 420, in <module>
    peek_lock=False, timeout=sb_timeout)
  File "/usr/local/lib/python2.7/dist-packages/azure/servicebus/servicebusservice.py", line 976, in receive_subscription_message
    timeout)
  File "/usr/local/lib/python2.7/dist-packages/azure/servicebus/servicebusservice.py", line 762, in read_delete_subscription_message
    response = self._perform_request(request)
  File "/usr/local/lib/python2.7/dist-packages/azure/servicebus/servicebusservice.py", line 1109, in _perform_request
    resp = self._filter(request)
  File "/usr/local/lib/python2.7/dist-packages/azure/servicebus/_http/httpclient.py", line 181, in perform_request
    self.send_request_body(connection, request.body)
  File "/usr/local/lib/python2.7/dist-packages/azure/servicebus/_http/httpclient.py", line 145, in send_request_body
    connection.send(None)
  File "/usr/local/lib/python2.7/dist-packages/azure/servicebus/_http/requestsclient.py", line 81, in send
    self.response = self.session.request(self.method, self.uri, data=request_body, headers=self.headers, timeout=self.timeout)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 422, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='****.servicebus.windows.net', port=443): Read timed out. (read timeout=65)
```

**Comment by lmazuel** [comment]
We are using `requests.session` under the hood: http://docs.python-requests.org/en/latest/user/advanced/#session-objects

You can see that `session` uses a connection pool of TCP connection. I think in your situation you might be in trouble by this (just an hypothesis).

I suggest to try to re-create the `ServiceBusService` instance if you detect the change of connection. Our code does not provide the feature currently to change the `requests.session` without recreating the instance.

**Comment by lmazuel** [comment]
Hi,

Have any news about this issue? Did you try my suggestion?
Thank you!

**Comment by lmazuel** [comment]
Close this issue due to inactivity and since the suggestion could have solve it.
If you still have an issue, feel free to open a new issue here.
Thanks!
