### ISSUE TITLE
update_pr is failing when building a data plane PR

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#5257]
Examples:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=32016
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=31980

This is failing when attempting to get repository details. Specifically: 
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/8f38ea64-6f89-4349-b04c-67f3debb1ec4.sh
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.2/x64/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/hostedtoolcache/Python/3.7.2/x64/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vsts/work/1/s/src/azure-sdk-tools/azure-sdk-tools/packaging_tools/update_pr.py", line 100, in <module>
    update_pr_main()
  File "/home/vsts/work/1/s/src/azure-sdk-tools/azure-sdk-tools/packaging_tools/update_pr.py", line 96, in update_pr_main
    int(args.pr_number),
  File "/home/vsts/work/1/s/src/azure-sdk-tools/azure-sdk-tools/packaging_tools/update_pr.py", line 29, in update_pr
    repo = con.get_repo(repo_id)
  File "/opt/hostedtoolcache/Python/3.7.2/x64/lib/python3.7/site-packages/github/MainClass.py", line 296, in get_repo
    "%s%s" % (url_base, full_name_or_id)
  File "/opt/hostedtoolcache/Python/3.7.2/x64/lib/python3.7/site-packages/github/Requester.py", line 275, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/opt/hostedtoolcache/Python/3.7.2/x64/lib/python3.7/site-packages/github/Requester.py", line 286, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.BadCredentialsException: 401 {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}

**Comment by lmazuel** [comment]
@scbedd fixed by removing fork?
