### ISSUE TITLE
TokenExpiredError: Who's Responsible for Refreshing the Token

### ISSUE THREAD

**Issue by boumenot** [Azure/azure-sdk-for-python#619]
azure-sdk-for-python: v2.0.0rc3
Python v3.5.1 on Windows 10

I got the following exception in long running code.

```text
2016-06-01T16:03:27.482 Token expired or is invalid. Attempting to refresh.
Traceback (most recent call last):
  File "c:\Python35\lib\site-packages\msrest\service_client.py", line 196, in send
    **kwargs)
  File "c:\Python35\lib\site-packages\requests_oauthlib\oauth2_session.py", line 321, in request
    http_method=method, body=data, headers=headers)
  File "c:\Python35\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 194, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired)

During handling of the above exception, another exception 

  File "c:\Python35\lib\site-packages\azure\mgmt\compute\operations\virtual_machine_extension_images_operations.py", line 235, in list_versions
    response = self._client.send(request, header_parameters, **operation_config)
  File "c:\Python35\lib\site-packages\msrest\service_client.py", line 201, in send
    raise_with_traceback(TokenExpiredError, msg, err)
  File "c:\Python35\lib\site-packages\msrest\exceptions.py", line 47, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "c:\Python35\lib\site-packages\msrest\service_client.py", line 196, in send
    **kwargs)
  File "c:\Python35\lib\site-packages\requests_oauthlib\oauth2_session.py", line 321, in request
    http_method=method, body=data, headers=headers)
  File "c:\Python35\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 194, in add_token
    raise TokenExpiredError()
```

It isn't clear to me who owns refreshing the token.  I would have thought the SDK does this automatically and transparently.

Is this the correct way to refresh the token?

```python
creds = ServicePrincipalCredentials(...)
creds.refresh_session()
```

**Comment by lmazuel** [comment]
You should not have to refresh the token yourself, should be automatic. We got some problem with it and there is a fix in the RC4 for the refresh. Could you try the RC4? I know this does not solve the whole problem, but it will be interested to see if it solves yours.

Thank you

+ @annatisch

**Comment by boumenot** [comment]
Will do.  I did not realize RC4 was out.

**Comment by annatisch** [comment]
Hi @boumenot, did you find upgrading to RC4 resolved this issue? Let me know if you're still getting any errors with regards to token refresh :)

**Comment by boumenot** [comment]
Sorry, I've been OOF since I first reported the issue.  I've pulled RC4, and I'm trying it now.  I'll report back.

**Comment by boumenot** [comment]
I tried to upgrade to 2.0.0rc4 on Windows, and I keep getting the following error.

```text
  File "C:\dev\Compute-Runtime-Tux-Pipeline\dep\azuresdk.py", line 40, in <genexpr>
    storage = next(x for x in self._client.storage_accounts.list() if x.name == name)  # type: StorageAccount
  File "c:\Python35\lib\site-packages\msrest\paging.py", line 64, in __iter__
    for i in self.next():
  File "c:\Python35\lib\site-packages\msrest\paging.py", line 104, in next
    self._response = self._get_next(self.next_link)
  File "c:\Python35\lib\site-packages\azure\mgmt\storage\operations\storage_accounts_operations.py", line 533, in internal_paging
    request, header_parameters, **operation_config)
  File "c:\Python35\lib\site-packages\msrest\service_client.py", line 167, in send
    session = self.creds.signed_session()
AttributeError: 'StorageManagementClientConfiguration' object has no attribute 'signed_session'
```

I upgraded to 2.0.0rc4 with the following command.

```batch
c:\Python35\Scripts\pip.exe install -U azure==2.0.0rc4
```

When this failed, I tried deleting all pip packages, and reinstalling but the error is the same.

I **think** the issue is with me, but I am not able to determine what or where it is.

**Comment by lmazuel** [comment]
Hi @boumenot 

This specific error is because `StorageManagementClientConfiguration` does not exist anymore in RC4. See the ChangeLog of RC4 for details:
https://github.com/Azure/azure-sdk-for-python/releases/tag/v2.0.0rc4

**Comment by boumenot** [comment]
Thank you!  I like the changes.

**Comment by boumenot** [comment]
I finally have evidence that everything is working well.  I setup up a job to run over the weekend that was continually interacting with Azure.  I can see from the logs that the token was refreshed by the SDK, and no exceptions were raised.  I'm closing the issue.

Thanks!
