### ISSUE TITLE
[BUG][LUIS] apps.add_custom_prebuilt_domain throws because of missing tokenizerVersion

### ISSUE THREAD

**Issue by v-jaswel** [Azure/azure-sdk-for-python#6272]
- **Package Name**: azure-cognitiveservices-language-luis 
- **Package Version**: 2.0
- **Operating system**: Windows 10 Enterprise 1803
- **python ersion**: 3.7.3

**Describe the bug**
Calling apps.add_custom_prebuilt_domain gets a 400 response from the server because no tokenizer version is specified.

***Exception or Stack Trace***
```
{'error': {'code': 'BadArgument', 'message': 'The tokenizer version cannot be null or empty.'}}
Traceback (most recent call last):
  File "quickstart.py", line 26, in <module>
    app_id, app_version = create_app()
  File "quickstart.py", line 22, in create_app
    culture="en-us")
  File "C:\Program Files (x86)\Python\Lib\site-packages\azure\cognitiveservices\language\luis\authoring\operations\apps_operations.py", line 1111, in add_custom_prebuilt_domain
    raise models.ErrorResponseException(self._deserialize, response)
azure.cognitiveservices.language.luis.authoring.models.error_response_py3.ErrorResponseException: Operation returned an invalid status code 'Bad Request'
```

Note the first line of the error output was obtained by editing C:\Program Files (x86)\Python\Lib\site-packages\azure\cognitiveservices\language\luis\authoring\operations\apps_operations.py on my machine and changing the code starting at line 1103 from:
```
if response.status_code not in [201]:
	raise models.ErrorResponseException(self._deserialize, response)
```
to:
```
if response.status_code not in [201]:
	print(response.json())
	raise models.ErrorResponseException(self._deserialize, response)
```

This provides more detailed information about the "Bad Request" response from the server than I can obtain otherwise.

**To Reproduce**
1. Get a LUIS subscription key.
1. Set the environment variable LUIS_SUBSCRIPTION_KEY to your subscription key.
1. Set the environment variable LUIS_REGION to the region for your subscription key (example: westus).
1. Install Python 3.
1. Install the package azure-cognitiveservices-language-luis. 
1. Run the following code.

***Code Snippet***
```
from azure.cognitiveservices.language.luis.authoring import LUISAuthoringClient
from msrest.authentication import CognitiveServicesCredentials

import json, os, sys

key_var_name = 'LUIS_SUBSCRIPTION_KEY'
if not key_var_name in os.environ:
    raise Exception('Please set/export the environment variable: {}'.format(key_var_name))
subscription_key = os.environ[key_var_name]

region_var_name = 'LUIS_REGION'
if not region_var_name in os.environ:
    raise Exception('Please set/export the environment variable: {}'.format(region_var_name))
region = os.environ[region_var_name]
endpoint = "https://{}.api.cognitive.microsoft.com".format(region)

client = LUISAuthoringClient(endpoint, CognitiveServicesCredentials(subscription_key))

def create_app():
    app_version = "0.1"
    app_id = client.apps.add_custom_prebuilt_domain(domain_name="HomeAutomation",
        culture="en-us")
    print("Created LUIS app with ID {}".format(app_id))
    return app_id, app_version

app_id, app_version = create_app()
```

**Expected behavior**
Expected output:
```
Created LUIS app with ID <guid>.
```

**Additional context**
This seems to be the same issue as https://github.com/Azure/azure-sdk-for-java/issues/4300, https://github.com/Azure/azure-sdk-for-net/issues/6853, and https://github.com/Azure/azure-sdk-for-js/issues/4221.

The necessity of the tokenizerVersion property can also be seen from the API testing console.

If you go to "Get LUIS prebuilt domains list" (https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/59104cec5aca2f0b48c76be3) and use the console to send a request, you get back results such as:
```
{
  "name": "Calendar",
  "culture": "en-us",
  "tokenizerVersion": "1.0.0",
  "description": "The Calendar domain provides intent and entities for adding, deleting, or editing an appointment, checking participants availability, and finding information about a calendar event.",
  "examples": "-",
  "intents": [{
    "name": "AcceptEventEntry",
    "description": "-",
    "examples": "-"
  },
...
```

Note the `tokenizerVersion` field.

If you go to "Add prebuilt application" (https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/59104e515aca2f0b48c76be5) and use the console to send the default request body:
```
{
	"domainName": "Web", 
	"culture": "en-us"
}
```
you get back the same response as in the code snippet:
```
Response status

400 Bad Request
Response latency
111 ms
Response content

Pragma: no-cache
Apim-Request-Id: c0024d77-12bc-4063-8ec1-14ebae8a76a8
Request-Id: c0024d77-12bc-4063-8ec1-14ebae8a76a8
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Request-Context: appId=cid-v1:26a3540d-a02a-4998-a060-715488fd769b
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Cache-Control: no-store, proxy-revalidate, no-cache, max-age=0, private
Date: Mon, 08 Jul 2019 03:02:00 GMT
Content-Length: 116
Content-Type: application/json; charset=utf-8

{
  "error": {
    "code": "BadArgument",
    "message": "The tokenizer version cannot be null or empty."
  }
}
```

If you change the request body to:
```
{
	"domainName": "Web", 
	"culture": "en-us",
	"tokenizerVersion": "1.0.0"
}
```
and resend, you get back a successful response:
```
Response status

201 Created
Response latency
561 ms
Response content

Pragma: no-cache
Apim-Request-Id: 551b309f-5967-426b-bf98-cfff25895c59
Request-Id: 551b309f-5967-426b-bf98-cfff25895c59
Operation-Location: https://westus.api.cognitive.microsoft.com/luis/api/v2.0/apps/customprebuiltdomains/a9fb34c3-25be-4e92-9bc6-3370303803c2
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Request-Context: appId=cid-v1:26a3540d-a02a-4998-a060-715488fd769b
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Cache-Control: no-store, proxy-revalidate, no-cache, max-age=0, private
Date: Mon, 08 Jul 2019 03:14:09 GMT
Location: https://westus.api.cognitive.microsoft.com/luis/api/v2.0/apps/customprebuiltdomains/a9fb34c3-25be-4e92-9bc6-3370303803c2
Content-Length: 38
Content-Type: application/json; charset=utf-8

"a9fb34c3-25be-4e92-9bc6-3370303803c2"
```

I am able to resolve this issue by making the following changes on my machine.

1. In C:\Program Files (x86)\Python\Lib\site-packages\azure\cognitiveservices\language\luis\authoring\operations\apps_operations.py, change line 1078 from:
```
rebuilt_domain_create_object = models.PrebuiltDomainCreateObject(domain_name=domain_name, culture=culture)
```
to:
```
prebuilt_domain_create_object = models.PrebuiltDomainCreateObject(domain_name=domain_name, culture=culture, tokenizer_version="1.0.0")
```

1. In C:\Program Files (x86)\Python\Lib\site-packages\azure\cognitiveservices\language\luis\authoring\models\prebuilt_domain_create_object_py3.py, starting at line 25, change the attribute map from:
```
_attribute_map = {
	'domain_name': {'key': 'domainName', 'type': 'str'},
	'culture': {'key': 'culture', 'type': 'str'}
}
```
to:
```
_attribute_map = {
	'domain_name': {'key': 'domainName', 'type': 'str'},
	'culture': {'key': 'culture', 'type': 'str'},
	'tokenizer_version': {'key': 'tokenizerVersion', 'type': 'str'}
}
```

1. In C:\Program Files (x86)\Python\Lib\site-packages\azure\cognitiveservices\language\luis\authoring\models\prebuilt_domain_create_object_py3.py, starting at line 31, change the __init__ method from:
```
def __init__(self, *, domain_name: str=None, culture: str=None, tokenizer_version: str=None, **kwargs) -> None:
	super(PrebuiltDomainCreateObject, self).__init__(**kwargs)
	self.domain_name = domain_name
	self.culture = culture
```
to:
```
def __init__(self, *, domain_name: str=None, culture: str=None, tokenizer_version: str=None, **kwargs) -> None:
	super(PrebuiltDomainCreateObject, self).__init__(**kwargs)
	self.domain_name = domain_name
	self.culture = culture
	self.tokenizer_version = tokenizer_version
```

After this, my code runs without errors and produces the expected output:
```
Created LUIS app with ID 36fb74a8-4c63-4d30-b459-58904ed50a43
```

**Comment by maggiepint** [comment]
Thanks for the bug report. I have routed to the appropriate team for follow-up.
