### ISSUE TITLE
ServiceBus queue messages sent via azure-servicebus 0.20.2 can't be received by 0.20.1

### ISSUE THREAD

**Issue by ndenny** [Azure/azure-sdk-for-python#671]
I upgraded one half of my project to use 0.20.2 of azure-servicebus, but the other half of my project using 0.20.1 suddenly started failing:
```
Traceback (most recent call last):
  File "code.py", line 77, in main
    run(config_file=config_file)
  File "code.py", line 789, in run
    listener.wait_for_message()
  File "code.py" line 233, in wait_for_message
    msg = self.sbs.receive_queue_message(self.taskqueue_name, peek_lock=False)
  File "/usr/local/lib/python3.4/dist-packages/azure/servicebus/servicebusservice.py", line 952, in receive_queue_message
    return self.read_delete_queue_message(queue_name, timeout)
  File "/usr/local/lib/python3.4/dist-packages/azure/servicebus/servicebusservice.py", line 906, in read_delete_queue_message
    return _create_message(response, self)
  File "/usr/local/lib/python3.4/dist-packages/azure/servicebus/_serialization.py", line 100, in _create_message
    elif str(int(float(value))) == value:
ValueError: could not convert string to float: 'max-age=31536000'
```
It seems that the new package is not backwards compatible with the previous version.  Is this expected?

**Comment by lmazuel** [comment]
Hi,
There is a breaking change in the ServiceBus Rest API that unfortunately forces people to move to

**Comment by ndenny** [comment]
Is there some place that these kind of things are announced? I'd like to avoid further surprises.

**Comment by lmazuel** [comment]
With a fixed APIVersion, the API should not have break :(. I should have nothing to announce, we missed an opportunity to do a perfect integration testing between the RestAPI and the Python SDK. It's the first time it happens since 2012 we launched this SDK...
I'm still sorry, we will do our best for this situation to not happen again. We are not happy about that :(
