### ISSUE TITLE
[Python Track2] [azure-eventhubs] [5.0.0b2] Iot hub connection string raises exception with EventProcessor

### ISSUE THREAD

**Issue by digimaun** [Azure/azure-sdk-for-python#6738]
The following error is raised in v5.0.0b2 when using a vanilla iothubowner connection string similar to the way in [EventProcessor example](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhubs/examples/eventprocessor/event_processor_example.py)

```bash
uamqp.errors.AMQPConnectionError: Failed to open mgmt link: MgmtOpenStatus.Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\me\.venv37\lib\site-packages\azure\eventhub\eventprocessor\event_processor.py", line 98, in start
    partition_ids = await self._eventhub_client.get_partition_ids()
  File "c:\users\me\.venv37\lib\site-packages\azure\eventhub\aio\client_async.py", line 156, in get_partition_ids
    return (await self.get_properties())['partition_ids']
  File "c:\users\me\.venv37\lib\site-packages\azure\eventhub\aio\client_async.py", line 139, in get_properties
    response = await self._management_request(mgmt_msg, op_type=b'com.microsoft:eventhub')
  File "c:\users\me\.venv37\lib\site-packages\azure\eventhub\aio\client_async.py", line 120, in _management_request
    await self._handle_exception(exception, retry_count, max_retries)
  File "c:\users\me\.venv37\lib\site-packages\azure\eventhub\aio\client_async.py", line 98, in _handle_exception
    await _handle_exception(exception, retry_count, max_retries, self)
  File "c:\users\me\.venv37\lib\site-packages\azure\eventhub\aio\error_async.py", line 67, in _handle_exception
    raise error
azure.eventhub.error.ConnectError: Failed to open mgmt link: MgmtOpenStatus.Error
Failed to open mgmt link: MgmtOpenStatus.Error
```

**Comment by YijunXieMS** [comment]
Yes, currently could you use the EventHub-compatible endpoint connecting string for the IoT hubs before we resolve this issue?
We'll fix this issue.

**Comment by digimaun** [comment]
Yah...Will do. Thanks.
