### ISSUE TITLE
Unable to deploy uisng ARM template by passing the content of the json file.

### ISSUE THREAD

**Issue by rshirani** [Azure/azure-sdk-for-python#693]
Hi folks,

I am trying to do a deployment but rather than passing the TemplateLink and ParametersLink, I'd rather passing the content. When I do so however I get an error as follows. What I do right now is simply loading the content of my template file

        public static Object GetTemplate() {
            return File.ReadAllText( @"E:\OfficialTemp\tmplt.json" ); }

        public static Object GetParameters(){
            return File.ReadAllText( @"E:\OfficialTemp\params.json"); }

and then in my main:

            deployment.Properties = new DeploymentProperties
            {
                Mode = DeploymentMode.Incremental,
                Template = GetTemplate(),
                Parameters = GetParameters(),
            };

            var resourceManagementClient = new ResourceManagementClient( credential )
            { SubscriptionId = subscriptionId };

            return await resourceManagementClient.Deployments.CreateOrUpdateAsync(
              groupName,
              deploymentName,
              deployment );
 
I'd like to mention that my tmplt.json and params.json are exactly the file that I used to in my deployment using the URI so I do not think that is an issue. I tested with the values that are stated for the template and parameters in https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-windows-csharp-template/ and I get the same error.     

Error: System.AggregateException: One or more errors occurred. ---> Microsoft.Rest.Azure.CloudException: The request content was invalid and could not be deserialized: 'Error converting value "
************************************************************************************************************************
}" to type 'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Templates.Schema.Template'. Path 'properties.template', line 3, position 23171.'.
   at Microsoft.Azure.Management.ResourceManager.DeploymentsOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.DeploymentsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.DeploymentsOperationsExtensions.<CreateOrUpdateAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApplication1.Program.<CreateTemplateDeploymentAsync>d__3.MoveNext() in

**Comment by lmazuel** [comment]
Hi @rshirani 

I'm always glad to help, but unfortunately I can't answer a C# issue in the Python issue tracker :(
Please submit your issue in the C# Python tracker and the C# expert (who I'm not) will be able to help you:
https://github.com/Azure/azure-sdk-for-net/issues

Thanks and sorry about that,

**Comment by rshirani** [comment]
OOPS. I actually wanted to post it there. Sorry for the noise. For the record, here is the link: https://github.com/Azure/azure-sdk-for-net/issues/2190
