### ISSUE TITLE
Error: Face.detect_with_stream() with list of return_face_attributes=[]

### ISSUE THREAD

**Issue by xenogew** [Azure/azure-sdk-for-python#7038]
Here is my code.
What do I miss or wrong?
```
detected_faces = face_client.face.detect_with_stream(open(face_file_path, 'rb').read(),
                            return_face_id=True,
                            return_face_landmarks=True,
                            return_face_attributes=list([FaceAttributeType.age,
                                                    FaceAttributeType.gender,
                                                    FaceAttributeType.head_pose,
                                                    FaceAttributeType.smile,
                                                    FaceAttributeType.facial_hair,
                                                    FaceAttributeType.glasses,
                                                    FaceAttributeType.emotion,
                                                    FaceAttributeType.hair,
                                                    FaceAttributeType.makeup,
                                                    FaceAttributeType.occlusion,
                                                    FaceAttributeType.accessories,
                                                    FaceAttributeType.blur,
                                                    FaceAttributeType.exposure,
                                                    FaceAttributeType.noise]),
                            recognition_model='recognition_02')
```

Because the error that was raise is
```
Traceback (most recent call last):
  File "sample-appl\src\runbatch.py", line 42, in <module>
    _select_run_command(args.command)
  File "sample-appl\src\runbatch.py", line 36, in _select_run_command
    face_identify.perform(args.gid, args.face_csv)
  File "C:\workspace\faceapi-dev\sample-appl\src\batch\face_identify.py", line 67, in perform
    recognition_model='recognition_02')
  File "C:\tools\Anaconda3\envs\FaceCI\lib\site-packages\azure\cognitiveservices\vision\face\operations\_face_operations.py", line 785, in detect_with_stream
    request = self._client.post(url, query_parameters, header_parameters, body_content)
  File "C:\tools\Anaconda3\envs\FaceCI\lib\site-packages\msrest\service_client.py", line 193, in post
    request = self._request('POST', url, params, headers, content, form_content)
  File "C:\tools\Anaconda3\envs\FaceCI\lib\site-packages\msrest\service_client.py", line 108, in _request
    request = ClientRequest(method, self.format_url(url))
  File "C:\tools\Anaconda3\envs\FaceCI\lib\site-packages\msrest\service_client.py", line 155, in format_url
    base = self.config.base_url.format(**kwargs).rstrip('/')
KeyError: 'Endpoint'
```

**Comment by tamittal471** [comment]
You have to set Environment variable called Endpoint
Command on Windows:
setx FACE_ENDPOINT "your endpoint for AZure cognitive service"

And then from your IDE,
ENDPOINT = os.environ['FACE_ENDPOINT']
