### ISSUE TITLE
resources.create_or_update returns 'Bad Request'

### ISSUE THREAD

**Issue by vaibhavparnalia** [Azure/azure-sdk-for-python#749]
I hope I got the documentation right. I am trying to iterate though resources.list() and update the resource tags. However I am getting an error while using create_or_update method.

 ```python
resource_client = ResourceManagementClient(credentials, subscription_id)

for resource in resource_client.resources.list():
    #print(resource)
    if resource.id.split('/')[4] == 'Build':
        if resource.type == 'Microsoft.Web/sites':
            print('resource.id: ', resource.id)
            print('resource_group_name: ', resource.id.split('/')[4])
            print('resource_provider_namespace: ', resource.id.split('/')[6])
            print('parent_resource_path: ', '')
            print('resource_type: ', str(resource.type).split('/')[-1])
            print('resource_name: ', resource.name)
            print('api_version: ', '2015-08-01')
            resource.tags['test'] = 'test1'

            resource_client.resources.create_or_update(
                resource_group_name= resource.id.split('/')[4], # Extract from resource.id
                resource_provider_namespace=resource.id.split('/')[6], # Extract from resource.id
                parent_resource_path='', # Extract from resource.id
                resource_type=str(resource.type).split('/')[-1], # Extract from resource type
                resource_name=resource.name,
                api_version='2015-08-01',
                parameters=resource
                )
        print('-'*10)
```

Sample output:
```
resource.id:  /subscriptions/*****-*****-****-****-**********/resourceGroups/Build/providers/Microsoft.Web/sites/build-dev
resource_group_name:  Build
resource_provider_namespace:  Microsoft.Web
parent_resource_path:  
resource_type:  sites
resource_name:  build-dev
api_version:  2015-08-01
Traceback (most recent call last):
  File "C:\Python35-32\Scripts\Azure\temp.py", line 68, in <module>
    parameters=resource
  File "C:\Python35-32\lib\site-packages\azure\mgmt\resource\resources\operations\resources_operations.py", line 407, in create_or_update
    raise exp
msrestazure.azure_exceptions.CloudError: Operation failed with status: 'Bad Request'. Details: 400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/*****-****-****-*****-*******/resourcegroups/Build/providers/Microsoft.Web/sites/build-dev?api-version=2015-08-01
```

I put some print statements in resources_operations to debug.
`body_content`:  `{'tags': {'hidden-related:/subscriptions/****-***-****-****-********/resourcegroups/Build/providers/Microsoft.Web/serverfarms/Build-Dev': 'empty', 'test': 'test1'}, 'location': 'westus'}`
from `response.__dict__`: `"Code":"BadRequest","Message":"The parameter properties has an invalid value."`

**Comment by brettcannon** [comment]
The main developer is on vacation for the rest of the week, but I wanted to let you know this bug report has not gone unnoticed by the team.

**Comment by annatisch** [comment]
Hi @vaibhavparnalia,

I've just tried out your code on a couple of other resources (specifically storage account and batch account) and the code appears to run successfully (the new tag is added).
The body content also looks to be accurate to my knowledge....

This makes me wonder if it's some combination of resource type + api version.
I'll keep digging :)

Have you be able to perform successful operations on any other resources?

**Comment by vaibhavparnalia** [comment]
Hi annatisch,

I just solved the issue, there is a possible bug in the source.

I tried to pass the parameters like the document suggested, it works.

```
parameters=GenericResource(
        location='West US',
        properties={},
    )
```

But using parameters=resource does not work. Looking at the error from response.__dict__ in the azure\mgmt\resource\resources\operations\resources_operations.py create_or_update method, it throws "Message":"The parameter properties has an invalid value."

From the resource, the properties was None, which I assume should be fine. But it expects {}.

I fixed the code by adding 
```
if not resource.properties:
    resource.properties = {}
```


Full code(I am developing the script and have only tested with Microsoft.Web/sites type):

```
for resource in resource_client.resources.list():
    #print(resource)
    if resource.id.split('/')[4] == 'Build':
        if resource.type == 'Microsoft.Web/sites':
            print('resource.id: ', resource.id)
            print('resource_group_name: ', resource.id.split('/')[4])
            print('resource_provider_namespace: ', resource.id.split('/')[6])
            print('parent_resource_path: ', '')
            print('resource_type: ', str(resource.type).split('/')[-1])
            print('resource_name: ', resource.name)
            print('api_version: ', resolve_resource_api(resource_client, resource))
            if not resource.tags:
                resource.tags = {}
                resource.tags['test'] = 'test1'
            else:
                resource.tags['test'] = 'test1'
            if not resource.properties:
                resource.properties = {}

            resource_client.resources.create_or_update(
                resource_group_name= resource.id.split('/')[4], # Extract from resource.id
                resource_provider_namespace=resource.id.split('/')[6], # Extract from resource.id
                parent_resource_path='', # Extract from resource.id
                resource_type=str(resource.type).split('/')[-1], # Extract from resource type
                resource_name=resource.name,
                #api_version=resolve_resource_api(resource_client, resource),
                api_version='2015-08-01',
                parameters=resource,
                )
        print('-'*10)
```


Thanks,
Vaibhav

**Comment by annatisch** [comment]
@vaibhavparnalia,
Thanks so much for your perseverance here! And good to hear that a workaround was found. :)
"properties" is not marked as a "required" property, nor does the API specification provide a default value for it.
I will take a look as to whether this problem was caused because either a) this particular provider handles resources differently or b) all services should require the "properties" to be populated.

Thanks again!
