### ISSUE TITLE
resources.create_or_update returns 'Bad Request' for Microsoft.Web/serverFarms

### ISSUE THREAD

**Issue by vaibhavparnalia** [Azure/azure-sdk-for-python#751]
Hello,

I had created an issue https://github.com/Azure/azure-sdk-for-python/issues/749 and found a workaround with the snippet:
```
if not resource.properties:
            resource.properties = {}   
```

There is similar issue with the resource.type Microsoft.Web/serverFarms, which returns 

> Traceback (most recent call last):
>   File "C:\Python35-32\Scripts\Azure\temp.py", line 62, in <module>
>     parameters=resource,
>   File "C:\Python35-32\lib\site-packages\azure\mgmt\resource\resources\operations\resources_operations.py", line 409, in create_or_update
>     raise exp
> msrestazure.azure_exceptions.CloudError: Operation failed with status: 'Bad Request'. Details: 400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/****-******-****-****-******/resourcegroups/Build/providers/Microsoft.Web/serverFarms/Build-Dev?api-version=2016-03-01

The error message from response.___dict___ being: **"Message":"The parameter SKU cannot be null.**

Can you please suggest a similar workaround? The request does not accept 'sku': None and resource.sku={} does not work.

My Code:
```
for resource in resource_client.resources.list():
    #print(resource)
    if resource.id.split('/')[4] == 'Build':
        # Print for reference
        print('resource.id: ', resource.id)
        print('resource_group_name: ', resource.id.split('/')[4])
        print('resource_provider_namespace: ', resource.id.split('/')[6])
        print('parent_resource_path: ', '')
        print('resource_type: ', str(resource.type).split('/')[-1])
        print('resource_name: ', resource.name)
        print('api_version: ', resolve_resource_api(resource_client, resource))
        #if not resource.tags:
        #    resource.tags = {}
        #    resource.tags['test'] = 'test1'
        #else:
        #    resource.tags['test'] = 'test1'

        # Requests expects resource.properies to be {} instead of None
        # https://github.com/Azure/azure-sdk-for-python/issues/749
        if not resource.properties:
            resource.properties = {}      

        # Skipping serverFarms resources due to possible bug
        # https://github.com/Azure/azure-sdk-for-python/issues/751
        if resource.type == 'Microsoft.Web/serverFarms':
            continue
            
        resource_client.resources.create_or_update(
            resource_group_name= resource.id.split('/')[4], # Extract from resource.id
            resource_provider_namespace=resource.id.split('/')[6], # Extract from resource.id
            parent_resource_path='', # Extract from resource.id
            resource_type=str(resource.type).split('/')[-1], # Extract from resource type
            resource_name=resource.name,
            api_version=resolve_resource_api(resource_client, resource),
            #api_version='2016-03-01' for serverFarms
            parameters=resource,
            )
        print('-'*10)
```

**Comment by annatisch** [comment]
Thanks @vaibhavparnalia, I'll take a look.
I believe SKU is usually represented as a string, so you should try setting as an empty string as a quick workaround, however I think it usually needs to be one of a discreet set of values...

Does this mean that the serverFarms resource returned from the .list() command does not contain any SKU information?

**Comment by lmazuel** [comment]
Hi @vaibhavparnalia 

Did you try the [azure-mgmt-web client](https://pypi.python.org/pypi/azure-mgmt-web/0.30.0rc5)? It contains the server_farms create_or_update method, [as you can see in this unittest](https://github.com/Azure/azure-sdk-for-python/blob/dev/azure-mgmt/tests/test_mgmt_apps.py#L35).

Sku is a mandatory parameter for ServerFarm. But I agree that since there is no RestAPI documentation, it's complicated to figure out :(.

**Comment by lmazuel** [comment]
Hi @vaibhavparnalia 

Could we close this issue, or could you tell me how I can help you more?
Thanks!

**Comment by lmazuel** [comment]
Hi @vaibhavparnalia 
I'm closing this issue due to inactivity, feel free to comment on it again if you need more help or open a new issue for anything you encounter.
Thanks!

**Comment by Abhinavtuteja** [comment]
Hi @vaibhavparnalia @lmazuel **I'm facing the issue related creating a resource**

here below is my code when I try to run this It gives me following error image attached below :--

resource_client = get_client_from_cli_profile(ResourceManagementClient)
para = {
        'location':'West US',
        
    }

rg_result = resource_client.resources.create_or_update(
                resource_group_name= "LUIS-Resources",
                resource_provider_namespace ="Microsoft.CognitiveServices",
                parent_resource_path='', # Extract from resource.id
                resource_type='accounts',
                resource_name='sample',
                api_version='2016-02-01-preview',
                parameters=para
                )
print(rg_result)

**Error Image**
![image](https://user-images.githubusercontent.com/39007285/88715484-784fe900-d13b-11ea-9b02-3a7db327d136.png)
