### ISSUE TITLE
Bad error messages when creating Storage Service Client from connection string

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-for-python#8002]
Whilst creating samples, I ran into some issues working with the Storage blob client. The basic repro looks like:

```Python
from azure.storage.blob import BlobServiceClient

# Some connection string here
connection_string = ""
client = BlobServiceClient.from_connection_string(connection_string)
containers = client.list_containers()
for container in containers:
    print(container.name)
```

If I supply an empty string, I get this error:
```
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```
An error message like "Malformed connection string" would be more useful.

If I have typo in my BlobEndpoint in my connection string, the operation hangs for a couple minutes before returning:
```
azure.core.exceptions.ServiceRequestError: <urllib3.connection.VerifiedHTTPSConnection object at 0x10ae29890>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known
```

I tried to enable logging so I could see the request/response traffic for this call, but I couldn't find guidance on how to do this.

**Comment by faelnpaiva** [comment]
I'm having this problem with get_service_stats method : 

**azure.core.exceptions.ServiceRequestError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f6e32d5d240>: Failed to establish a new connection: [Errno -2] Name or service not known**

```
def geo(self):
        blob_service_client = BlobServiceClient.from_connection_string(self.access)
        acc = blob_service_client.get_service_stats()
        print(acc)
```
I could use the same object to connect , upload and download in a storage . I setup the storage as GRS ( geo-replication) , but I need to get the status of it ( Live , invalid , etc.. )

**Comment by faelnpaiva** [comment]
I put a logging in there , look : 
```
# python3 main.py 
Connected to Storage Account!
Request URL: 'https://rpaivatesting123-secondary.blob.core.windows.net/?restype=service&comp=stats'
Request method: 'GET'
Request headers:
    'Accept': 'application/xml'
    'x-ms-version': '2019-12-12'
    'x-ms-date': 'Wed, 11 Nov 2020 21:09:52 GMT'
    'x-ms-client-request-id': '3d73d876-2462-11eb-a223-7cb27d33114d'
    'User-Agent': 'azsdk-python-storage-blob/12.5.0 Python/3.6.9 (Linux-5.4.0-48-generic-x86_64-with-Ubuntu-18.04-bionic)'
    'Authorization': '*****'
Request body:
None
Request URL: 'https://rpaivatesting123-secondary.blob.core.windows.net/?restype=service&comp=stats'
Request method: 'GET'
Request headers:
    'Accept': 'application/xml'
    'x-ms-version': '2019-12-12'
    'x-ms-date': 'Wed, 11 Nov 2020 21:09:52 GMT'
    'x-ms-client-request-id': '3d73d876-2462-11eb-a223-7cb27d33114d'
    'User-Agent': 'azsdk-python-storage-blob/12.5.0 Python/3.6.9 (Linux-5.4.0-48-generic-x86_64-with-Ubuntu-18.04-bionic)'
    'Authorization': '*****'
Request body:
None
```

**Comment by faelnpaiva** [comment]
```
Request body:
None
Tuple timeout setting is deprecated
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    health_check.geo()
  File "/root/sarah/DR/devops-toolbox/azure-storage-health-check/scripts/azure_storage_operations.py", line 113, in geo
    acc = bloba.get_service_stats(logging_enable=True)
  File "/usr/local/lib/python3.6/dist-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/azure/storage/blob/_blob_service_client.py", line 257, in get_service_stats
    timeout=timeout, use_location=LocationMode.SECONDARY, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/azure/storage/blob/_generated/operations/_service_operations.py", line 229, in get_statistics
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/usr/local/lib/python3.6/dist-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.6/dist-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.6/dist-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 5 more times]
  File "/usr/local/lib/python3.6/dist-packages/azure/core/pipeline/policies/_redirect.py", line 157, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.6/dist-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.6/dist-packages/azure/storage/blob/_shared/policies.py", line 543, in send
    raise err
  File "/usr/local/lib/python3.6/dist-packages/azure/storage/blob/_shared/policies.py", line 517, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.6/dist-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.6/dist-packages/azure/storage/blob/_shared/policies.py", line 318, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.6/dist-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.6/dist-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.6/dist-packages/azure/core/pipeline/_base.py", line 103, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/usr/local/lib/python3.6/dist-packages/azure/core/pipeline/transport/_requests_basic.py", line 284, in send
    raise error
azure.core.exceptions.ServiceRequestError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f11404867b8>: Failed to establish a new connection: [Errno -2] Name or service not known
```

**Comment by achiaver** [comment]
Has this issue been solved?
In case positive, what is the outcome?

**Comment by xsqian** [comment]
I have the same issue doing `blob_service_client = BlobServiceClient.from_connection_string(connect_str)` the error is as below:
`azure.core.exceptions.ServiceRequestError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7ff02a0bd2b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known`

**Comment by urnal** [comment]
Hi guys, i have the same problem, any issue ?
I m trying to connect with cosmosDB like this:

client = CosmosClient(url=endpoint, credential=key, connection_verify=False)

Error: azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPSConnection object at 0x00000251A020AE90>: Failed to establish a new connection: [WinError 10061] nodename nor servname provided, or not known...
