### ISSUE TITLE
Can't Set network security group when creating nic

### ISSUE THREAD

**Issue by panda2k** [Azure/azure-sdk-for-python#8067]
Here is my current code for setting up a nic. 

```
nicParams = {
    'location': LOCATION,
    'ip_configurations': [{
        'name': VM_NAME + "-ipconfig",
        'public_ip_address': publicIP,
        'subnet': {
            'id': subnetInfo.id
        }
    }],
    'network_security_group': 'proxy-ports'
}
nicCreationResult = network_client.network_interfaces.create_or_update(GROUP_NAME, VM_NAME + "-nic", nicParams)
```
`
Having the network_security_group defined is causing these errors: 
```
[`Traceback](url) (most recent call last):
  File "C:\Users\Michael Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\msrest\serialization.py", line 1293, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "C:\Users\Michael Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\msrest\serialization.py", line 1080, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "C:\Users\Michael Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\msrest\serialization.py", line 1103, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Michael Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\msrest\serialization.py", line 570, in body
    data = deserializer._deserialize(data_type, data)
  File "C:\Users\Michael Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\msrest\serialization.py", line 1299, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "C:\Users\Michael Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\msrest\serialization.py", line 1468, in deserialize_data
    return self._deserialize(obj_type, data)
  File "C:\Users\Michael Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\msrest\serialization.py", line 1303, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "C:\Users\Michael Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\msrest\exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "C:\Users\Michael Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\msrest\serialization.py", line 1293, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "C:\Users\Michael Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\msrest\serialization.py", line 1080, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "C:\Users\Michael Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\msrest\serialization.py", line 1103, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "AzureProxyGen.py", line 53, in <module>
    nicCreationResult = network_client.network_interfaces.create_or_update(GROUP_NAME, VM_NAME + "-nic", nicParams)
  File "C:\Users\Michael Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\mgmt\network\v2018_12_01\operations\network_interfaces_operations.py", line 274, in create_or_update
    **operation_config
  File "C:\Users\Michael Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\mgmt\network\v2018_12_01\operations\network_interfaces_operations.py", line 219, in _create_or_update_initial
    body_content = self._serialize.body(parameters, 'NetworkInterface')
  File "C:\Users\Michael Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\msrest\serialization.py", line 573, in body
    SerializationError, "Unable to build a model: "+str(err), err)
  File "C:\Users\Michael Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\msrest\exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "C:\Users\Michael Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\msrest\serialization.py", line 570, in body
    data = deserializer._deserialize(data_type, data)
  File "C:\Users\Michael Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\msrest\serialization.py", line 1299, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "C:\Users\Michael Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\msrest\serialization.py", line 1468, in deserialize_data
    return self._deserialize(obj_type, data)
  File "C:\Users\Michael Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\msrest\serialization.py", line 1303, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "C:\Users\Michael Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\msrest\exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "C:\Users\Michael Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\msrest\serialization.py", line 1293, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "C:\Users\Michael Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\msrest\serialization.py", line 1080, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "C:\Users\Michael Wang\AppData\Local\Programs\Python\Python37\lib\site-packages\msrest\serialization.py", line 1103, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
```

How should I specify the network security group when creating the nic?

**Comment by panda2k** [comment]
Fixed
