### ISSUE TITLE
Python SDK Quickstart doesn't work due to library conflicts

### ISSUE THREAD

**Issue by griffinator76** [Azure/azure-sdk-for-python#8281]
I'm trying to follow this quickstart guide for the Python SDK: https://docs.microsoft.com/en-us/azure/python/python-sdk-azure-get-started

I'm using Windows 10 with python 3.8.0

I've installed the Azure CLI for Windows using the msi installer as per these instructions: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest

I've created a virtual environment and installed the Azure libraries using `pip install azure`

When I try to run any code, such as this from the first example:
```
from azure.common.client_factory import get_client_from_cli_profile
from azure.mgmt.compute import ComputeManagementClient

client = get_client_from_cli_profile(ComputeManagementClient)
```

I get an error that I'm missing `azure-cli-core`:
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    client = get_client_from_cli_profile(ComputeManagementClient)
  File "C:\users\Nathan\Documents\projects\venv\lib\site-packages\azure\common\client_factory.py", line 75, in get_client_from_cli_profile
    cloud = get_cli_active_cloud()
  File "C:\users\Nathan\Documents\projects\venv\lib\site-packages\azure\common\cloud.py", line 20, in get_cli_active_cloud
    raise ImportError("You need to install 'azure-cli-core' to load CLI active Cloud")
ImportError: You need to install 'azure-cli-core' to load CLI active Cloud
```
If I try and install this using `pip install azure-cli-core` it installs with an error and upgrades `azure-mgmt-resource` from 2.2.0 to 4.0.0:
```
ERROR: azure-mgmt 4.0.0 has requirement azure-mgmt-resource~=2.0, but you'll have azure-mgmt-resource 4.0.0 which is incompatible.
Installing collected packages: azure-mgmt-resource, azure-cli-core
  Found existing installation: azure-mgmt-resource 2.2.0
    Uninstalling azure-mgmt-resource-2.2.0:
      Successfully uninstalled azure-mgmt-resource-2.2.0
Successfully installed azure-cli-core-2.0.75 azure-mgmt-resource-4.0.0
```
Now if I try and run the code I get an AttributeError, presumably because of the library incompatibility:
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    client = get_client_from_cli_profile(ComputeManagementClient)
  File "C:\users\Nathan\Documents\projects\venv\lib\site-packages\azure\common\client_factory.py", line 75, in get_client_from_cli_profile
    cloud = get_cli_active_cloud()
  File "C:\users\Nathan\Documents\projects\venv\lib\site-packages\azure\common\cloud.py", line 21, in get_cli_active_cloud
    return get_active_cloud()
  File "C:\users\Nathan\Documents\projects\venv\lib\site-packages\azure\cli\core\cloud.py", line 324, in get_active_cloud
    cli_ctx = get_default_cli()
  File "C:\users\Nathan\Documents\projects\venv\lib\site-packages\azure\cli\core\__init__.py", line 546, in get_default_cli
    return AzCli(cli_name='az',
  File "C:\users\Nathan\Documents\projects\venv\lib\site-packages\azure\cli\core\__init__.py", line 55, in __init__
    SESSION.load(os.path.join(azure_folder, 'az.sess'), max_age=3600)
  File "C:\users\Nathan\Documents\projects\venv\lib\site-packages\azure\cli\core\_session.py", line 46, in load
    if st.st_mtime + max_age < time.clock():
AttributeError: module 'time' has no attribute 'clock'
```

How do I set up my environment so that this Python SDK quickstart will work?

**Comment by johanste** [comment]
This looks like an issue in the Azure CLI (time.clock() was deprecated since python 3.3 and removed in 3.8).
