### ISSUE TITLE
Python 3.8 win32: DefaultAzureCredential and SharedTokenCacheCredential raise ImportError

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#8292]
Initializers of `DefaultAzureCredential` and `SharedTokenCacheCredential` raise `ImportError` when running Python 3.8 on Windows:
```
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from azure.identity import DefaultAzureCredential
>>> DefaultAzureCredential()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\3.8\lib\site-packages\azure\identity\_credentials\default.py", line 39, in __init__
    SharedTokenCacheCredential(
  File "C:\3.8\lib\site-packages\azure\identity\_credentials\user.py", line 136, in __init__
    from msal_extensions.token_cache import WindowsTokenCache
  File "C:\3.8\lib\site-packages\msal_extensions\__init__.py", line 7, in <module>
    from .token_cache import WindowsTokenCache as TokenCache
  File "C:\3.8\lib\site-packages\msal_extensions\token_cache.py", line 8, in <module>
    from .cache_lock import CrossPlatLock
  File "C:\3.8\lib\site-packages\msal_extensions\cache_lock.py", line 5, in <module>
    import portalocker
  File "C:\3.8\lib\site-packages\portalocker\__init__.py", line 4, in <module>
    from . import portalocker
  File "C:\3.8\lib\site-packages\portalocker\portalocker.py", line 9, in <module>
    import win32file
ImportError: DLL load failed while importing win32file: The specified module could not be found.
```

No other credential is affected, so this can be worked around by substituting a specific component of `DefaultAzureCredential` such as `ClientSecretCredential` or `EnvironmentCredential`. `SharedTokenCacheCredential`, however, won't function on Python 3.8.

The cause of this is tracked at mhammond/pywin32#1431

**Comment by chlowell** [comment]
Update: with #8294, `DefaultAzureCredential` doesn't access the shared token cache on 3.8/win32 but otherwise functions normally. `SharedTokenCacheCredential` continues to raise `ImportError` on 3.8/win32.

**Comment by chlowell** [comment]
The most recent pywin32 package included a fix for the root cause of this. The shared cache should be accessible on 3.8 with pywin32 227 installed.

**Comment by swathipil** [comment]
Running the sample located at `sdk\eventhub\azure-eventhub\samples\sync_samples`, resulted in the following error log:
```
Traceback (most recent call last):
  File ".\client_identity_authentication.py", line 40, in <module>
    from azure.identity import EnvironmentCredential
  File "C:\Users\swathip\Documents\env37\lib\site-packages\azure\identity\__init__.py", line 10, in <module> 
    from ._credentials import (
  File "C:\Users\swathip\Documents\env37\lib\site-packages\azure\identity\_credentials\__init__.py", line 5, 
in <module>
    from .authorization_code import AuthorizationCodeCredential
  File "C:\Users\swathip\Documents\env37\lib\site-packages\azure\identity\_credentials\authorization_code.py", line 8, in <module>
    from .._internal.aad_client import AadClient
  File "C:\Users\swathip\Documents\env37\lib\site-packages\azure\identity\_internal\__init__.py", line 50, in <module>
ckages\msal_extensions\__init__.py", line 12, in <module>    from .cache_lock import CrossPlatLock
  File "C:\Users\swathip\Documents\env37\lib\site-packages\msal_extensions\cache_lock.py", line 5, in <module>
    import portalocker
  File "C:\Users\swathip\Documents\env37\lib\site-packages\portalocker\__init__.py", line 4, in <module>     
    from . import portalocker
  File "C:\Users\swathip\Documents\env37\lib\site-packages\portalocker\portalocker.py", line 9, in <module>  
    import win32file
ImportError: DLL load failed: The specified module could not be found.
```
The OS version, Python version, and package information are below.
* OS: Windows 10
* Python version: 3.7
* package information:
```
azure-core==1.9.0
azure-identity==1.5.1
certifi==2020.12.5
cffi==1.14.4
chardet==4.0.0
cryptography==3.3.1
idna==2.10
msal==1.8.0
msal-extensions==0.3.0
portalocker==1.7.1
pycparser==2.20
PyJWT==1.7.1
pywin32==300
requests==2.25.1
six==1.15.0
uamqp==1.2.12
urllib3==1.26.2
```
The sample runs as intended, without errors, with Python 3.6 and the following packages:
```
adal==1.2.5
azure-common==1.1.27
azure-core==1.9.0
azure-eventhub==5.2.1
azure-identity==1.5.1
certifi==2020.12.5
cffi==1.14.4
chardet==4.0.0
cryptography==3.3.1
msal==1.8.0
msal-extensions==0.3.0
msrest==0.6.19
msrestazure==0.6.4
oauthlib==3.1.0
portalocker==1.7.1
pycparser==2.20
PyJWT==1.7.1
python-dateutil==2.8.1
pywin32==300
requests==2.25.1
requests-oauthlib==1.3.0
six==1.15.0
uamqp==1.2.12
urllib3==1.26.2
```
