### ISSUE TITLE
Encountered error with "Automation for azure-sdk-for-python"

### ISSUE THREAD

**Issue by lagalbra** [Azure/azure-sdk-for-python#8300]
# Automation for azure-sdk-for-python
<details><summary>Encountered a Subprocess error: (azure-sdk-for-python)</summary><p>

Command: ['/usr/local/bin/autorest', '/tmp/tmpmljti920/rest/specification/hanaonazure/resource-manager/readme.md', '--perform-load=false', '--swagger-to-sdk', '--output-artifact=configuration.json', '--input-file=foo', '--output-folder=/tmp/tmpmn9bi7ue']
Finished with return code 7
and output:
```shell
AutoRest code generation utility [version: 2.0.4283; node: v8.12.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Failure:
Error: Unable to start AutoRest Core from /root/.autorest/@microsoft.azure_autorest-core@2.0.4405/node_modules/@microsoft.azure/autorest-core
Error: Unable to start AutoRest Core from /root/.autorest/@microsoft.azure_autorest-core@2.0.4405/node_modules/@microsoft.azure/autorest-core
    at main (/opt/node_modules/autorest/dist/app.js:232:19)
    at <anonymous>

/root/.autorest/@microsoft.azure_autorest-core@2.0.4405/node_modules/@microsoft.azure/autorest-core/dist/app.js:33
    autorest_core_1.Shutdown();
    ^
ReferenceError: autorest_core_1 is not defined
    at process.on (/root/.autorest/@microsoft.azure_autorest-core@2.0.4405/node_modules/@microsoft.azure/autorest-core/dist/app.js:33:5)
    at emitOne (events.js:121:20)
    at process.emit (events.js:211:7)
    at process.emit (/node_modules/source-map-support/source-map-support.js:439:21)
fs.js:612
  return binding.close(fd);
                 ^

Error: EBADF: bad file descriptor, close
    at Object.fs.closeSync (fs.js:612:18)
    at StaticVolumeFile.shutdown (/opt/node_modules/autorest/dist/static-loader.js:352:10)
    at StaticFilesystem.shutdown (/opt/node_modules/autorest/dist/static-loader.js:406:17)
    at process.exit.n [as exit] (/opt/node_modules/autorest/dist/static-loader.js:169:11)
    at printErrorAndExit (/node_modules/source-map-support/source-map-support.js:423:11)
    at process.emit (/node_modules/source-map-support/source-map-support.js:435:16)
    at process._fatalException (bootstrap_node.js:391:26)
```

</p></details>

_Originally posted by @AutorestCI in https://github.com/Azure/azure-rest-api-specs/pull/7670#issuecomment-548036736_

**Comment by lagalbra** [comment]
@zikalino @lmazuel This error prevented an AutoPR from being opened on https://github.com/Azure/azure-rest-api-specs/pull/7670 ; please resolve, or advise how I can open an AutoPR in a different way into azure-sdk-for-python

**Comment by lmazuel** [comment]
That's because of NodeJS8, I restarted the container with the latest image and checked that it's NodeJS 10 now

**Comment by lagalbra** [comment]
@lmazuel Can you please advise how I can open a new PR on azure-sdk-for-python with my changes from https://github.com/Azure/azure-rest-api-specs/pull/7670 ?
