### ISSUE TITLE
MSAL credentials send requests through Requests

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#8391]
There are code paths through MSAL which wrapping credentials (e.g. `InteractiveBrowserCredential`) don't intercept. For example, MSAL applications create a new HTTP client (via a private method) every time they redeem a refresh token rather than reuse the clients they create at construction (and which we replace with an adapter).

Some MSAL application code paths also directly call into `requests`. For example, a public application's `get_accounts` method may send instance discovery requests.

**Comment by chlowell** [comment]
[MSAL Python 1.3.0](https://github.com/AzureAD/microsoft-authentication-library-for-python/releases/tag/1.3.0) adds an `http_client` parameter to `ClientApplication`. This should enable channeling all MSAL's requests into our pipeline.

**Comment by jiasli** [comment]
I think the current patching logic is not enough:

https://github.com/Azure/azure-sdk-for-python/blob/b299320a619087c7c33e1041af4a89ef8cbf2400/sdk/identity/azure-identity/azure/identity/_internal/msal_transport_adapter.py#L69

MSAL still uses `requests` for this line:

https://github.com/Azure/azure-sdk-for-python/blob/b15cededb71a33d787ab30a1e676b798825d0d0d/sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py#L274

When creating a credential with `connection_verify=False` (https://github.com/Azure/azure-sdk-for-python/issues/11944), the callback shows that `requests` is still directly used by MSAL (without `RequestsTransport` in between), thus failing to apply `connection_verify`:

https://github.com/Azure/azure-sdk-for-python/blob/0e82fae6b881d39497f8eb6890a33969dd9eec31/sdk/core/azure-core/azure/core/pipeline/transport/_requests_basic.py#L166

```
Traceback (most recent call last):
  File "d:\cli\azure-sdk-for-python\sdk\identity\azure-identity\azure\identity\_internal\exception_wrapper.py", line 18, in wrapper
    return fn(*args, **kwargs)
  File "d:\cli\azure-sdk-for-python\sdk\identity\azure-identity\azure\identity\_internal\msal_credentials.py", line 274, in _acquire_token_silent
    result = app.acquire_token_silent_with_error(list(scopes), account=account, **kwargs)
  File "D:\cli\microsoft-authentication-library-for-python\msal\application.py", line 546, in acquire_token_silent_with_error
    result = self._acquire_token_silent_from_cache_and_possibly_refresh_it(
  File "D:\cli\microsoft-authentication-library-for-python\msal\application.py", line 608, in _acquire_token_silent_from_cache_and_possibly_refresh_it
    return self._acquire_token_silent_by_finding_rt_belongs_to_me_or_my_family(
  File "D:\cli\microsoft-authentication-library-for-python\msal\application.py", line 639, in _acquire_token_silent_by_finding_rt_belongs_to_me_or_my_family
    last_resp = at = self._acquire_token_silent_by_finding_specific_refresh_token(
  File "D:\cli\microsoft-authentication-library-for-python\msal\application.py", line 670, in _acquire_token_silent_by_finding_specific_refresh_token
    response = client.obtain_token_by_refresh_token(
  File "D:\cli\microsoft-authentication-library-for-python\msal\oauth2cli\oauth2.py", line 521, in obtain_token_by_refresh_token
    resp = super(Client, self).obtain_token_by_refresh_token(
  File "D:\cli\microsoft-authentication-library-for-python\msal\oauth2cli\oauth2.py", line 242, in obtain_token_by_refresh_token
    return self._obtain_token("refresh_token", data=data, **kwargs)
  File "D:\cli\microsoft-authentication-library-for-python\msal\oauth2cli\oidc.py", line 83, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
  File "D:\cli\microsoft-authentication-library-for-python\msal\oauth2cli\oauth2.py", line 462, in _obtain_token
    resp = super(Client, self)._obtain_token(
  File "D:\cli\microsoft-authentication-library-for-python\msal\oauth2cli\oauth2.py", line 214, in _obtain_token
    resp = (post or self._http_client.post)(
  File "D:\cli\env38\lib\site-packages\requests\sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "D:\cli\env38\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\cli\env38\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "D:\cli\env38\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/oauth2/v2.0/token (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```

**Comment by jiasli** [comment]
This is because the client created at [`msal.application.ClientApplication.__init__`](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/0f67285f0afc5072134cb01b496e3cb807558154/msal/application.py#L202)
```py
self.client = self._build_client(client_credential, self.authority)
```

is not reused at [`msal.application.ClientApplication._acquire_token_silent_by_finding_specific_refresh_token`](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/0f67285f0afc5072134cb01b496e3cb807558154/msal/application.py#L665)

```py
client = self._build_client(self.client_credential, authority)
```

So the monkey patch doesn't work for this `client`:

https://github.com/Azure/azure-sdk-for-python/blob/b15cededb71a33d787ab30a1e676b798825d0d0d/sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py#L136

This won't be an issue anymore since
