### ISSUE TITLE
[Docs] Track 1 azure-eventhub does not have EventProcessorHost properly populated 

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#8501]
So, start of this is that this URL is no longer present: https://docs.microsoft.com/en-us/python/api/azure-eventhub/azure.eventprocessorhost.eph.eventprocessorhost?view=azure-python

The azure-eventhub package is NOT one of the packages we GA-ed last week, so I was a bit confused as to why the content being generated changed. 

After doing some digging, I’m 99% certain it’s because of the following:

1)  azure-eventhub 1.3.1 (the GA version) requires azure-storage-blob~=1.3
2)  azure-core and the other newly GA-ed packages rely on azure-storage-blob>=12.0.0
3)  The doc generation build uses the same virtual environment for all packages being generated
4)  By the time execution gets to doc gen for azure-eventhub, azure-storage-blob 12.0.0 has already replaced the 1.3 that EventProcessorHost needs.
5)  This error occurs [1]
6)  The generated sphinx doesn’t have the EventProcessorHost landing page as a result (yml is not generated)
a.  The page “disappears” on the portal

I have contacted the documentation team for next steps.

[1]
```
2019-11-05T23:58:06.4410436Z <Matched Warning>: D:\a\1\s\source_code\68\azure_eventhub-1.3.2\doc\azure.eventprocessorhost.rst:12: WARNING: autodoc: failed to import module 'azure.eventprocessorhost.abstract_checkpoint_manager'; the following exception was raised:
2019-11-05T23:58:06.4410617Z Traceback (most recent call last):
2019-11-05T23:58:06.4410755Z   File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\azure\eventprocessorhost\__init__.py", line 11, in <module>
2019-11-05T23:58:06.4410921Z     from azure.eventprocessorhost.azure_storage_checkpoint_manager import AzureStorageCheckpointLeaseManager
2019-11-05T23:58:06.4411458Z   File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\azure\eventprocessorhost\azure_storage_checkpoint_manager.py", line 15, in <module>
2019-11-05T23:58:06.4411609Z     from azure.storage.blob import BlockBlobService
2019-11-05T23:58:06.4411718Z ImportError: cannot import name 'BlockBlobService'
```

**Comment by scbedd** [comment]
Latest update is that this is not possible. We cannot have two CI pipelines merge into a single ToC.yml right now. It is not a supported scenario.

As such, we will leave the current eventhub part of the eph mitigation, and flowing into the original `azure-python` moniker. That will fix _broken links_, but it will not appear on the ToC.

Meanwhile, I am adding `azure-eventhub` to the `legacy` moniker such that it WILL be populated. I am currently awaiting a doc build to complete. ETA a couple hours to check this.

**Comment by scbedd** [comment]
![image](https://user-images.githubusercontent.com/45376673/68977672-a3f99180-07ad-11ea-9b3f-cd9591ff8ded.png)

Resolved. Waiting for PR build validation, then merging.
