### ISSUE TITLE
AttributeError: module 'site' has no attribute 'getsitepackages'

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#8573]
```
$ python
Fatal Python error: initsite: Failed to import the site module
Traceback (most recent call last):
  File "C:\Users\chlowe\.virtualenvs\misc-37\lib\site.py", line 791, in <module>
    main()
  File "C:\Users\chlowe\.virtualenvs\misc-37\lib\site.py", line 768, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "C:\Users\chlowe\.virtualenvs\misc-37\lib\site.py", line 280, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "C:\Users\chlowe\.virtualenvs\misc-37\lib\site.py", line 211, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "C:\Users\chlowe\.virtualenvs\misc-37\lib\site.py", line 179, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "C:\Users\chlowe\.virtualenvs\misc-37\lib\site-packages\win32\lib\pywin32_bootstrap.py", line 14, in <module>
    for maybe in site.getsitepackages():
AttributeError: module 'site' has no attribute 'getsitepackages'
```

This originates with `pywin32` release 226 (issue there is mhammond/pywin32#1439). A workaround is to manually remove release 226 and replace it with 225, or explicitly install a prior version in a new virtual environment:
```sh
pip install pywin32==225 azure-identity
```

**Comment by chlowell** [comment]
Closing this as resolved: portalocker 1.5.2 excludes pywin32 226, and pywin32 227 includes a fix.
