### ISSUE TITLE
DefaultAzureCredential error message is displayed twice

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-python#8593]
Remove all credential related env vars, not managed identity, and not signed into VS 2019.

With this code:

```
from azure.identity import DefaultAzureCredential
credential = DefaultAzureCredential()
credential.get_token()
```

The following is outputted:

```
Traceback (most recent call last):
  File "c:\users\jong\onedrive - microsoft\code\azure-sdk-for-python\sdk\identity\azure-identity\azure\identity\_credentials\default.py", line 50, in get_token
    return super(DefaultAzureCredential, self).get_token(*scopes, **kwargs)
  File "c:\users\jong\onedrive - microsoft\code\azure-sdk-for-python\sdk\identity\azure-identity\azure\identity\_credentials\chained.py", line 52, in get_token
    raise ClientAuthenticationError(message=error_message)
azure.core.exceptions.ClientAuthenticationError: No credential in this chain provided a token.
Attempted credentials:
        EnvironmentCredential: Incomplete environment configuration
        ImdsCredential: IMDS endpoint unavailable
        SharedTokenCacheCredential: No cached token found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../../azure-identity/index2.py", line 4, in <module>
    credential.get_token()
  File "c:\users\jong\onedrive - microsoft\code\azure-sdk-for-python\sdk\identity\azure-identity\azure\identity\_credentials\default.py", line 56, in get_token
    .format(e.message))
azure.core.exceptions.ClientAuthenticationError:
No credential in this chain provided a token.
Attempted credentials:
        EnvironmentCredential: Incomplete environment configuration
        ImdsCredential: IMDS endpoint unavailable
        SharedTokenCacheCredential: No cached token found

Please visit the Azure identity Python SDK docs at
https://aka.ms/python-sdk-identity#defaultazurecredential
to learn what options DefaultAzureCredential supports

```

We should only be rendering the same error message once per get_token call.

**Comment by kaerm** [comment]
thanks @jongio // cc: @chlowell
