### ISSUE TITLE
Python3 : Azure Key Vault Keys, creating RAS key : TypeError 

### ISSUE THREAD

**Issue by mataralhawiti** [Azure/azure-sdk-for-python#8908]
Following example in :
https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/keyvault/azure-keyvault-keys

whenever I run the below code : 

```
rsa_key = key_client.create_rsa_key("rsa-key-demo", size=2048)
print(rsa_key.name)
print(rsa_key.key_type)
```

The key will be created in my Azure keyVult, however I always get the following error : 

> Traceback (most recent call last):
  File "c:/Users/user/Desktop/azure_keyValut_demo.py", line 152, in <module>
    rsa_key = key_client.create_rsa_key("rsa-key-demo", size=2048)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\azure\core\tracing\decorator.py", line 62, in wrapper_use_tracer
    return func(*args, **kwargs) # type: ignore
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\azure\keyvault\keys\_client.py", line 131, in create_rsa_key
    return self.create_key(name, key_type="RSA-HSM" if hsm else "RSA", **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\azure\core\tracing\decorator.py", line 62, in wrapper_use_tracer
    return func(*args, **kwargs) # type: ignore
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\azure\keyvault\keys\_client.py", line 96, in create_key
    **kwargs
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\azure\keyvault\keys\_shared\_generated\v7_0\operations\_key_vault_client_operations.py", line 96, in create_key
    deserialized = self._deserialize('KeyBundle', response)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\msrest\serialization.py", line 1180, in __call__
    data = self._unpack_content(response_data, content_type)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\msrest\serialization.py", line 1334, in _unpack_content
    return json.loads(data)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'method'

I didn't quite understand why that exception is being thrown.

I found this on stackoverflow but still couldn't understand what's going on: 
https://stackoverflow.com/questions/36804132/why-wont-python3-load-this-json-string

**The code run successfully with no issues with Python2.7**
**The exception will be thrown for all key operations (create, delete, get)**
**It also happens with all Cryptographic operations**

**Comment by chlowell** [comment]
Thanks for reporting this! Which version of `msrest` do you have installed? I observe this exception with 0.5.5 but not with 0.6.x.

**Comment by mataralhawiti** [comment]
Thank you for your support. Yes updating `msrest `to 0.6.x solved the issue.
here's stackoverflow post :
(https://stackoverflow.com/questions/59157372/python3-azure-key-vault-keys-creating-ras-key-typeerror/59168456#59168456)


I'm curious to understand how to debug this issue.

**Comment by chlowell** [comment]
This was my process:
1. Observe exception is in `msrest.serialization`
1. Recall we test the library on Python 3.5, 3.7, 3.8, and I've never seen that exception
1. Run your code in a new Python 3.6 virtual environment. Observe no exception.
1. Consult [msrest release history](https://pypi.org/project/msrest/#history). Downgrade to prior minor version's latest patch (0.5.5).
1. Run your code again. Observe the exception you reported.
1. Install `msrest==0.6.0`. Run your code. Observe no exception.

I concluded the problem is `msrest` 0.5.x and that your environment must have it installed. Then I determined how that could happen:
- `azure-keyvault-*` require `msrest>=0.5.0` ([setup.py](https://github.com/Azure/azure-sdk-for-python/blob/7e39c897a3df329e1feeeb133f5790c1c06ff1ce/sdk/keyvault/azure-keyvault-certificates/setup.py#L82))
  - so if you install `msrest` 0.5.x, you'll still have it after installing `azure-keyvault-*`
- we never see this exception in our test runs because they use a new environment in which pip installs the latest `msrest`
- workaround then is to manually upgrade `msrest`, permanent fix is to update requirements of `azure-keyvault-*`

Hope that's helpful and thanks again for reporting this, I doubt we'd have found it otherwise.
