### ISSUE TITLE
"RuntimeError: Event loop is closed" on 3.8/win32

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#9060]
Using aiohttp 3.6.2 and azure-core 1.1.1 with Python 3.8/win32, this program:
```py
import asyncio
from azure.core.pipeline.transport import AioHttpTransport, HttpRequest

async def main():
    transport = AioHttpTransport()
    request = HttpRequest('GET', 'https://www.bing.com')
    await transport.send(request)

asyncio.run(main())
```

Logs this to stderr:
```
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0348F3D0>
Traceback (most recent call last):
  File "C:\Python38-32\Lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python38-32\Lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python38-32\Lib\asyncio\base_events.py", line 711, in call_soon
    self._check_closed()
  File "C:\Python38-32\Lib\asyncio\base_events.py", line 504, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

Note the exception is logged to stderr; it doesn't crash the program. This may be related to aio-libs/aiohttp#4324. I see the same behavior with aiohttp 4.0.0a1 (and an appropriately modified `AioHttpTransport`).

This may also be related to aiohttp's shutdown behavior (see aio-libs/aiohttp#1925). The exception isn't logged when `asyncio.run` above is replaced with with:
```py
loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

**Comment by chlowell** [comment]
I'm closing this issue because the SDK can't prevent this error being raised. As described in the first aiohttp issue I linked above, the error is due to different behavior of `ProactorEventLoop` as compared to `SelectorEventLoop`, will not be raised in a future version of aiohttp, and can be prevented by application-level workarounds (though those may not be worth using because the error typically causes only a noisy shutdown).
