### ISSUE TITLE
Role assignment can't be created because the service principal "doesn't exist"

### ISSUE THREAD

**Issue by MMollyy** [Azure/azure-sdk-for-python#9074]
hi,

I'm having a troublesome issue where I am creating a service principal using graph-rbac library, and then creating a role assignment using auth-mgmt library.

However, I keep getting issues in my pipelines where it works every now and then, but most of the times it fails. What does it fail with:
```
INFO:Azure.Azure:Creating infra-user role assignment on service principal for acceptance environment ..
INFO:Azure.Azure:Verifying existence of service principal for acceptance environment ..
INFO:Azure.Azure:Service principal for 005-test-infra-user verified on acceptance, continuing ..
ERROR:Azure.Azure:Failed to assign the role assignment for infra-user in acceptance environment
Traceback (most recent call last):
  File "<input>", line 37, in create_azure_serviceprincipal_roleassignment
  File "C:\Applications\Python37\lib\site-packages\azure\mgmt\authorization\v2018_01_01_preview\operations\_role_assignments_operations.py", line 332, in create
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: PrincipalNotFound
Message: Principal 234-54566-324-76324 does not exist in the directory ##############################.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 33, in <module>
  File "<input>", line 43, in create_azure_serviceprincipal_roleassignment
AzureAuthorization: Error assigning the role to the service principal
```

Now I actually have a check built-in to the code that verifies if the service principal exists. But we can also see in the log output that I just created the service principal, then verify if it exists, and then try to create the role assignment.

The code to verify if the service principal exists:
```
def verify_sp_exists(environment, service_principal, stack_slug, role_name):
    try:
        logger_azure.info(
            'Verifying existence of service principal for %s environment ..', environment)
        sp_verification = graph_client.get(environment).service_principals.get(
            object_id=service_principal.object_id)
    except AttributeError:
        logger_azure.info(
            'Service principal %s-%s does not exist on %s, trying again ..', stack_slug, role_name, environment)
    if service_principal.object_id == sp_verification.object_id:
        logger_azure.info(
            'Service principal for %s-%s verified on %s, continuing ..', stack_slug, role_name, environment)
    while service_principal.object_id != sp_verification.object_id:
        logger_azure.info(
            'Service principal could not be verified on %s, trying again ..', environment)
        sp_verification = graph_client.get(environment).service_principals.get(
            object_id=service_principal.object_id)
        if service_principal.object_id == sp_verification.object_id:
            logger_azure.info(
                'Service principal %s-%s verified on %s..', stack_slug, role_name, environment)
            break
```
And this code is called during the creation of the role assignment, to make sure it is there before I try to create it:
```
def create_azure_serviceprincipal_roleassignment(resource_group, service_principal, role_definition,
                                                 role_name):
    for environment in ENVIRONMENTS:
        logger_azure.info(
            'Checking if %s role assignment already exists on service principal with scope %s for %s environment ..',
            role_name, resource_group.get(environment).name, environment)
        role_assignment = {'role_definition_id': ra.role_definition_id for ra in
                           auth_client.get(environment).role_assignments.list_for_resource_group(
                               resource_group_name=resource_group.get(environment).name,
                               filter=f"principalid eq '{service_principal.get(environment).object_id}'") if
                           ra.role_definition_id == role_definition.get(environment).get(
                               role_name)}
        print(f"The role assignment found = {role_assignment.get('role_definition_id')}")
        print(f"Going to match against: {role_definition.get(environment).get(role_name)}")
        if role_assignment.get('role_definition_id') == role_definition.get(environment).get(
                            role_name):
            logger_azure.info(
                '%s role assignment already exists on service principal for %s environment ..',
                role_name, environment)
        else:
            try:
                logger_azure.info(
                    'Creating %s role assignment on service principal for %s environment ..',
                    role_name, environment)

                verify_sp_exists(environment=environment,
                                 service_principal=service_principal.get(environment),
                                 stack_slug=stack_slug,
                                 role_name=role_name)

                auth_client.get(environment).role_assignments.create(
                    resource_group.get(environment).id,
                    uuid4(),
                    {
                        'role_definition_id': role_definition.get(environment).get(
                            role_name),
                        'principal_id': service_principal.get(environment).object_id
                    }
                )
                logger_azure.info('Succesfully created role assignment for %s environment ..', environment)
            except CloudError:
                logger_azure.error('Failed to assign the role assignment for %s in %s environment', role_name, environment)
                raise AzureAuthorization('Error assigning the role to the service principal')
```
But still it keeps failing, and my gut is telling me this is because I'm doing the existence check using the graph library. While the role assignment is created using the auth library. And somehow the auth library is not able to see it got created yet?

Does someone have a suggestion on how to fix this to prevent the role assignment creation from ever failing on a "non-existing" service principal. Note the quotation marks, because I am 100% positive the service principal exists.

**Comment by MMollyy** [comment]
So I am currently doing the following:
```
def create_azure_serviceprincipal_roleassignment(resource_group, service_principal, role_definition,
                                                 role_name):
    for environment in ENVIRONMENTS:
        logger_azure.info(
            'Checking if %s-%s role assignment already exists on service principal with scope %s for %s environment ..',
            stack_slug, role_name, resource_group.get(environment).name, environment)
        role_assignment = {'role_definition_id': ra.role_definition_id for ra in
                           auth_client.get(environment).role_assignments.list_for_resource_group(
                               resource_group_name=resource_group.get(environment).name,
                               filter=f"principalid eq '{service_principal.get(environment).object_id}'") if
                           ra.role_definition_id == role_definition.get(environment).get(
                               role_name)}
        print(f"Going to match against: {role_definition.get(environment).get(role_name)}")
        print(f"The role assignment found = {role_assignment.get('role_definition_id')}")
        if role_assignment.get('role_definition_id') == role_definition.get(environment).get(
                            role_name):
            logger_azure.info(
                '%s-%s role assignment already exists on service principal for %s environment ..',
                stack_slug, role_name, environment)
        else:
            try:
                logger_azure.info(
                    'Creating %s-%s role assignment on service principal for %s environment ..',
                    stack_slug, role_name, environment)

                time.sleep(5)
                verify_sp_exists(environment=environment,
                                 service_principal=service_principal.get(environment),
                                 stack_slug=stack_slug,
                                 role_name=role_name)
                time.sleep(5)

                auth_client.get(environment).role_assignments.create(
                    resource_group.get(environment).id,
                    uuid4(),
                    {
                        'role_definition_id': role_definition.get(environment).get(
                            role_name),
                        'principal_id': service_principal.get(environment).object_id
                    }
                )
                logger_azure.info('Successfully created role assignment for %s environment ..', environment)
            except CloudError as error:
                logger_azure.info(
                    'First attempt to assign the role assignment for %s in %s environment failed .. retrying ..',
                    role_name,
                    environment)
                if f'does not exist in the directory' in error.message:
                    try:
                        logger_azure.info(
                            'Creating %s-%s role assignment on service principal for %s environment ..',
                            stack_slug, role_name, environment)

                        time.sleep(5)
                        verify_sp_exists(environment=environment,
                                         service_principal=service_principal.get(environment),
                                         stack_slug=stack_slug,
                                         role_name=role_name)
                        time.sleep(5)

                        auth_client.get(environment).role_assignments.create(
                            resource_group.get(environment).id,
                            uuid4(),
                            {
                                'role_definition_id': role_definition.get(environment).get(
                                    role_name),
                                'principal_id': service_principal.get(environment).object_id
                            }
                        )
                        logger_azure.info('Successfully created role assignment for %s environment ..', environment)
                    except CloudError as error:
                        logger_azure.info('Second attempt failed .. retrying ..', role_name, environment)
                        if f'does not exist in the directory' in error.message:
                            try:
                                logger_azure.info(
                                    'Creating %s-%s role assignment on service principal for %s environment ..',
                                    stack_slug, role_name, environment)

                                time.sleep(5)
                                verify_sp_exists(environment=environment,
                                                 service_principal=service_principal.get(environment),
                                                 stack_slug=stack_slug,
                                                 role_name=role_name)
                                time.sleep(5)

                                auth_client.get(environment).role_assignments.create(
                                    resource_group.get(environment).id,
                                    uuid4(),
                                    {
                                        'role_definition_id': role_definition.get(environment).get(
                                            role_name),
                                        'principal_id': service_principal.get(environment).object_id
                                    }
                                )
                                logger_azure.info('Successfully created role assignment for %s environment ..',
                                                  environment)
                            except CloudError:
                                logger_azure.info('Final attempt failed .. re-run for stack %s  ..', role_name,
                                                  environment, stack_slug)
                                raise AzureAuthorization('Error assigning the role to the service principal')
                else:
                    raise AzureAuthorization('Error assigning the role to the service principal')
```

This helps me to circumvent getting the error, but I realy don't like this way of coding ..

**Comment by lmazuel** [comment]
Hi @MMollyy 
That's mostly the approach the CLI is using as well:
https://github.com/Azure/azure-cli/blob/4d5b1a942e48ce6f8674420f2b18d50f19ed860e/src/azure-cli/azure/cli/command_modules/role/custom.py#L1344-L1365

They comment it as "waiting for replication to do be done", so my guess is that because AAD and Azure Authorization are two different entities, there is some synchronization ongoing here. I'm sorry that it creates a burden, I keep this issue open for the service teams to investigate.

**Comment by MMollyy** [comment]
Hey @lmazuel ,

thanks. I had figured as much, thanks for confirming. I would definitely like to hear/read back on the results of that investigation.

**Comment by MMollyy** [comment]
Hi all,

some colleagues had figured out we could use some kind of backoff code for each Exception that python would throw out:
```
@backoff.on_exception(backoff.expo,
                          CloudError,
                          max_time=AZURE_MAX_BACKOFF_TIME)
```
Which comes from https://github.com/litl/backoff
and is a decorator that we were able to apply on any of the library its functions to get an exponential backoff up to a maximum of X seconds which is specified in a configuration variable.
It's been working great for me.

Perhaps an idea to incorporate into the default azure library? If not, atleast the idea can be found here in github.

**Comment by lmazuel** [comment]
Thanks for the feedback @MMollyy !!
FYI @johanste
