### ISSUE TITLE
Irregular Parallelization Error Occurring for Windows Builds

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#9379]
@iscai-msft saw a weird error in her certificates release build.

[Error](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=228211&view=logs&j=f2de612a-62c9-5121-75e8-36f1bc1a0f81&t=474ef29f-1c3f-5c08-e731-bdd0c8962b3b)
[Another instance of the error](https://dev.azure.com/azure-sdk/public/_build/results?buildId=228958&view=logs&j=be2373b3-6b66-526b-20b8-841c5ec5eb4b&t=27b6da23-3544-58b2-e3ed-4b7a28f27d9a) for `azure-core`.\
[Another keyvault scheduled build](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=230263&view=logs&j=be2373b3-6b66-526b-20b8-841c5ec5eb4b&t=27b6da23-3544-58b2-e3ed-4b7a28f27d9a)

This definitely has the hallmarks of a parallelization problem, but I'm not seeing the root cause yet.

**Comment by scbedd** [comment]
Common pattern, all these failures are on Windows.

**Comment by scbedd** [comment]
Also seeing this here. Great [repro opportunity](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=230514&view=results) here.

**Comment by scbedd** [comment]
I'm putting these errors into two buckets:

## Bucket 1 - Failure to Install due to connection hiccup

```
ERROR: Could not find a version that satisfies the requirement async-generator>=1.3; python_version == "3.5" (from pytest-asyncio->-r ../../../eng/test_tools.txt (line 4)) (from versions: none)
ERROR: No matching distribution found for async-generator>=1.3; python_version == "3.5" (from pytest-asyncio->-r ../../../eng/test_tools.txt (line 4))
```
This is just one example. This same issue occurs for random packages. This _must_ be resource contention on pip side. Something is being shared even if the tests are running on the appropriate environment. 

## Bucket 2 - EOF Errors installing generated wheel

```
Building wheels for collected packages: azure-devtools, azure-core, azure-identity, azure-mgmt-keyvault, azure-sdk-tools, azure-keyvault-nspkg
  Building wheel for azure-devtools (setup.py): started
  Building wheel for azure-devtools (setup.py): finished with status 'done'
  Created wheel for azure-devtools: filename=azure_devtools-1.1.1-py2.py3-none-any.whl size=22716 sha256=6a5b46461605d522b474f03b6a071824cc6f704258e49207cfc2baa7878b4136
  Stored in directory: C:\Users\VssAdministrator\AppData\Local\pip\Cache\wheels\c8\f7\a5\5d43de599f49166a14f46fd106b3185b19b732a546d1c96fac
  Building wheel for azure-core (setup.py): started
  Building wheel for azure-core (setup.py): finished with status 'done'
  Created wheel for azure-core: filename=azure_core-1.1.2-py2.py3-none-any.whl size=103982 sha256=b0d0c9eb767c1830e45ffceecbc9e3c5c5a7702be6dda9c07371c3eba74f2bc4
  Stored in directory: C:\Users\VssAdministrator\AppData\Local\pip\Cache\wheels\2c\20\75\de28f01a2c984171f40cda4f01511c4151119f052172f49e1e
  Building wheel for azure-identity (setup.py): started
  Building wheel for azure-identity (setup.py): finished with status 'done'
  Created wheel for azure-identity: filename=azure_identity-1.1.1-py2.py3-none-any.whl size=58163 sha256=f453eb0b4954c385b1b230b55a8638fab4c7f6d7f9302de7c100381afd93cb1b
  Stored in directory: C:\Users\VssAdministrator\AppData\Local\pip\Cache\wheels\07\43\68\6f7401793a654d56f952a4e104bc7df191af6da7578ef999fd
  Building wheel for azure-mgmt-keyvault (setup.py): started
  Building wheel for azure-mgmt-keyvault (setup.py): finished with status 'done'
  Created wheel for azure-mgmt-keyvault: filename=azure_mgmt_keyvault-2.0.0-py2.py3-none-any.whl size=80953 sha256=969def3d947cb38ffd1b0ec49bb475fa1f5e3ad33b541d0616e30e35f0d93ffc
  Stored in directory: C:\Users\VssAdministrator\AppData\Local\pip\Cache\wheels\20\0f\f3\774e2db406813a9d908ba24f90f83eecf0d97648851a9ba2fc
  Building wheel for azure-sdk-tools (setup.py): started
  Building wheel for azure-sdk-tools (setup.py): finished with status 'done'
  Created wheel for azure-sdk-tools: filename=azure_sdk_tools-0.0.0-cp35-none-any.whl size=37633 sha256=774d89396a0747b70d1c182f8ab41060223425da4039e28f4a8b6c575211caad
  Stored in directory: C:\Users\VssAdministrator\AppData\Local\pip\Cache\wheels\3c\4e\b9\f19561a53bd73e8b0c19d3a50ac02e77ac9b61e1e51b26eb54
ERROR: Exception:
Traceback (most recent call last):
  File "D:\a\1\s\sdk\keyvault\azure-keyvault-keys\.tox\whl\lib\site-packages\pip\_internal\cli\base_command.py", line 153, in _main
    status = self.run(options, args)
  File "D:\a\1\s\sdk\keyvault\azure-keyvault-keys\.tox\whl\lib\site-packages\pip\_internal\commands\install.py", line 417, in run
    legacy_requirements=legacy_requirements,
  File "D:\a\1\s\sdk\keyvault\azure-keyvault-keys\.tox\whl\lib\site-packages\pip\_internal\commands\install.py", line 94, in build_wheels
    should_unpack=True,
  File "D:\a\1\s\sdk\keyvault\azure-keyvault-keys\.tox\whl\lib\site-packages\pip\_internal\wheel.py", line 1165, in build
    unpack_file(req.link.file_path, req.source_dir)
  File "D:\a\1\s\sdk\keyvault\azure-keyvault-keys\.tox\whl\lib\site-packages\pip\_internal\utils\unpacking.py", line 252, in unpack_file
    flatten=not filename.endswith('.whl')
  File "D:\a\1\s\sdk\keyvault\azure-keyvault-keys\.tox\whl\lib\site-packages\pip\_internal\utils\unpacking.py", line 114, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "C:\hostedtoolcache\windows\Python\3.5.4\x64\Lib\zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "C:\hostedtoolcache\windows\Python\3.5.4\x64\Lib\zipfile.py", line 1093, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

This blows up in random locations, but most of the time it's because the generated wheel that is being installed for the sdist is getting messed up. I think this is where the problem actually lies.

I believe that Bucket #1 just needs additional retries, I'm not certain how else to approach that.

**Comment by scbedd** [comment]
Ok. From what I can tell, we have completely eliminated the wheel install caching errors that we were getting with #9531. 

Unfortunately, now Windows has a new error. It takes the form of:

```
_ ERROR collecting sdk/compute/azure-mgmt-compute/build/lib/azure/mgmt/compute/v2018_10_01/operations/__init__.py _
.tox\sdist\lib\site-packages\_pytest\runner.py:237: in from_call
    result = func()
.tox\sdist\lib\site-packages\_pytest\runner.py:257: in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
.tox\sdist\lib\site-packages\_pytest\python.py:645: in collect
    yield from self._collectfile(path)
.tox\sdist\lib\site-packages\_pytest\python.py:598: in _collectfile
    path, path.isdir(), path.exists(), path.islink()
E   AssertionError: local('D:\\a\\1\\s\\sdk\\compute\\azure-mgmt-compute\\build\\lib\\azure\\mgmt\\compute\\v2018_10_01\\operations\\_virtual_machine_scale_set_vms_operations.py') is not a file (isdir=False, exists=False, islink=False)
_ ERROR collecting sdk/compute/azure-mgmt-compute/build/lib/azure/mgmt/compute/v2019_03_01/__init__.py _
.tox\sdist\lib\site-packages\py\_error.py:66: in checked_call
    return func(*args, **kwargs)
E   FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\a\\1\\s\\sdk\\compute\\azure-mgmt-compute\\build\\lib\\azure\\mgmt\\compute\\v2019_03_01'
```

I have seen this error with the following two builds:
- [CogServices](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=241502&view=results)
- [Compute](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=241426&view=results)

Still evaluating where these errors are coming from.
