### ISSUE TITLE
Further Exception during retry attempt after 'Connection reset by peer' event

### ISSUE THREAD

**Issue by mkschuster** [Azure/azure-sdk-for-python#9620]
- **Package Name**: azure-core 
- **Package Version**: 1.2.1
- **Operating System**: Scientific Linux 6.2
- **Python Version**: 3.8

**Describe the bug**
During handling of an `azure.core.exceptions.ServiceResponseError` `Exception` caused by a `'Connection reset by peer'` event, another `Exception` is encountered, ultimately in Python `copy.deepcopy()`, that seems to prevent a successful retry.

**To Reproduce**
1. Uploading files of several GiB into block blob storage, a 'Connection reset by peer' error seems likely.
2. Rather than resuming after the connection error, an Exception gets raised, please see the Traceback below.
3. Reproducible for azure-core==1.2.1 and azure-storage-blob==12.1.0 under Python 3.8.1 and 3.7.4

**Expected behavior**
Up to 10 retries are requested via BlobServiceClient.from_connection_string(..., retries_total=10).

**Additional context**

Exception:
```
Traceback (most recent call last):
  File ".../python/3.8/lib/python3.8/site-packages/azure/storage/blob/_shared/policies.py", line 517, in send
    response = self.next.send(request)
  File ".../python/3.8/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 80, in send
    response = self.next.send(request)
  File ".../python/3.8/lib/python3.8/site-packages/azure/storage/blob/_shared/policies.py", line 318, in send
    response = self.next.send(request)
  File ".../python/3.8/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 80, in send
    response = self.next.send(request)
  File ".../python/3.8/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 80, in send
    response = self.next.send(request)
  File ".../python/3.8/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 112, in send
    self._sender.send(request.http_request, **request.context.options),
  File ".../python/3.8/lib/python3.8/site-packages/azure/storage/blob/_shared/base_client.py", line 295, in send
    return self._transport.send(request, **kwargs)
  File ".../python/3.8/lib/python3.8/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 263, in send
    raise error
azure.core.exceptions.ServiceResponseError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  ...
  File ".../src/bsfpython/bsf/cloud.py", line 207, in azure_block_blob_upload
    azure_blob_client.upload_blob(
  File ".../python/3.8/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 71, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ".../python/3.8/lib/python3.8/site-packages/azure/storage/blob/_blob_client.py", line 480, in upload_blob
    return upload_block_blob(**options)
  File ".../python/3.8/lib/python3.8/site-packages/azure/storage/blob/_upload_helpers.py", line 131, in upload_block_blob
    block_ids = upload_substream_blocks(
  File ".../python/3.8/lib/python3.8/site-packages/azure/storage/blob/_shared/uploads.py", line 121, in upload_substream_blocks
    range_ids = _parallel_uploads(executor, uploader.process_substream_block, upload_tasks, running_futures)
  File ".../python/3.8/lib/python3.8/site-packages/azure/storage/blob/_shared/uploads.py", line 33, in _parallel_uploads
    range_ids.extend([chunk.result() for chunk in done])
  File ".../python/3.8/lib/python3.8/site-packages/azure/storage/blob/_shared/uploads.py", line 33, in <listcomp>
    range_ids.extend([chunk.result() for chunk in done])
  File ".../python/3.8/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File ".../python/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File ".../python/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File ".../python/3.8/lib/python3.8/site-packages/azure/storage/blob/_shared/uploads.py", line 227, in process_substream_block
    return self._upload_substream_block_with_progress(block_data[0], block_data[1])
  File ".../python/3.8/lib/python3.8/site-packages/azure/storage/blob/_shared/uploads.py", line 233, in _upload_substream_block_with_progress
    range_id = self._upload_substream_block(block_id, block_stream)
  File ".../python/3.8/lib/python3.8/site-packages/azure/storage/blob/_shared/uploads.py", line 265, in _upload_substream_block
    self.service.stage_block(
  File ".../python/3.8/lib/python3.8/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 318, in stage_block
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File ".../python/3.8/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 208, in run
    return first_node.send(pipeline_request)  # type: ignore
  File ".../python/3.8/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 80, in send
    response = self.next.send(request)
  File ".../python/3.8/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 80, in send
    response = self.next.send(request)
  File ".../python/3.8/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 80, in send
    response = self.next.send(request)
  [Previous line repeated 5 more times]
  File ".../python/3.8/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 157, in send
    response = self.next.send(request)
  File ".../python/3.8/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 80, in send
    response = self.next.send(request)
  File ".../python/3.8/lib/python3.8/site-packages/azure/storage/blob/_shared/policies.py", line 533, in send
    retries_remaining = self.increment(
  File ".../python/3.8/lib/python3.8/site-packages/azure/storage/blob/_shared/policies.py", line 483, in increment
    settings['history'].append(RequestHistory(request, error=error))
  File ".../python/3.8/lib/python3.8/site-packages/azure/core/pipeline/policies/_base.py", line 151, in __init__
    self.http_request = copy.deepcopy(http_request)
  File ".../python/3.8/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
  File ".../python/3.8/lib/python3.8/site-packages/azure/core/pipeline/transport/_base.py", line 226, in __deepcopy__
    data = copy.deepcopy(self.body, memo)
  File ".../python/3.8/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File ".../python/3.8/lib/python3.8/copy.py", line 269, in _reconstruct
    state = deepcopy(state, memo)
  File ".../python/3.8/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File ".../python/3.8/lib/python3.8/copy.py", line 229, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File ".../python/3.8/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_thread.lock' object
```

List of installed packages:
```
$ pip3.8 freeze
azure-core==1.2.1
azure-storage-blob==12.1.0
biopython==1.76
bx-python==0.8.6
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
cryptography==2.8
cycler==0.10.0
Cython==0.29.14
dnspython==1.16.0
idna==2.8
isodate==0.6.0
kiwisolver==1.1.0
MACS2==2.2.6
matplotlib==3.1.2
mercurial==5.2.2
msrest==0.6.10
mysql-connector-python==8.0.19
numpy==1.18.1
oauthlib==3.1.0
protobuf==3.6.1
pyBigWig==0.3.17
pycparser==2.19
pyparsing==2.4.6
pysam==0.15.4
python-dateutil==2.8.1
requests==2.22.0
requests-oauthlib==1.3.0
RSeQC==3.0.1
scipy==1.4.1
six==1.14.0
SQLAlchemy==1.3.13
urllib3==1.25.8
virtualenv==16.7.9
```

**Comment by kaerm** [comment]
Hi @mkschuster thank you for reporting this, I am looping in my team to take a look at this //cc: @mayurid

**Comment by xiangyan99** [comment]
fixed.
