### ISSUE TITLE
CI fails randomly with version info not found error

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-for-python#9922]
Sample error log as follows:

================================= log start ===================================
ERROR: Exception:
Traceback (most recent call last):
  File "/home/vsts/work/1/s/sdk/textanalytics/azure-ai-nspkg/.tox/sdist/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2681, in version
    return self._version
  File "/home/vsts/work/1/s/sdk/textanalytics/azure-ai-nspkg/.tox/sdist/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vsts/work/1/s/sdk/textanalytics/azure-ai-nspkg/.tox/sdist/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/home/vsts/work/1/s/sdk/textanalytics/azure-ai-nspkg/.tox/sdist/lib/python3.6/site-packages/pip/_internal/commands/freeze.py", line 100, in run
    for line in freeze(**freeze_kwargs):
  File "/home/vsts/work/1/s/sdk/textanalytics/azure-ai-nspkg/.tox/sdist/lib/python3.6/site-packages/pip/_internal/operations/freeze.py", line 70, in freeze
    req = FrozenRequirement.from_dist(dist)
  File "/home/vsts/work/1/s/sdk/textanalytics/azure-ai-nspkg/.tox/sdist/lib/python3.6/site-packages/pip/_internal/operations/freeze.py", line 257, in from_dist
    req = dist.as_requirement()
  File "/home/vsts/work/1/s/sdk/textanalytics/azure-ai-nspkg/.tox/sdist/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2840, in as_requirement
    if isinstance(self.parsed_version, packaging.version.Version):
  File "/home/vsts/work/1/s/sdk/textanalytics/azure-ai-nspkg/.tox/sdist/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2648, in parsed_version
    self._parsed_version = parse_version(self.version)
  File "/home/vsts/work/1/s/sdk/textanalytics/azure-ai-nspkg/.tox/sdist/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2689, in version
    raise ValueError(msg, self)
ValueError: ("Missing 'Version:' header and/or PKG-INFO file at path: /home/vsts/work/1/s/sdk/textanalytics/azure-ai-nspkg/azure_ai_nspkg.egg-info/PKG-INFO", azure-ai-nspkg [unknown version] (/home/vsts/work/1/s/sdk/textanalytics/azure-ai-nspkg))

**Comment by praveenkuttappan** [comment]
PR to fix this issue: https://github.com/Azure/azure-sdk-for-python/pull/9951
