### ISSUE TITLE
QnA Maker - python SDK using the FileDTO()

### ISSUE THREAD

**Issue by SolomDancer** [Azure/azure-sdk-for-python#9959]
Hello folks,

So following the tutorial on the MS Doc worked fine when using the URL(S) now I removed the URL(S) and I wanted to use the file, which required me to use the FileDTO. For me this did not work So any pointers would help.

Here is the code:
`'''
Import the following libraries
'''
import os
import time

from azure.cognitiveservices.knowledge.qnamaker import QnAMakerClient
from azure.cognitiveservices.knowledge.qnamaker.models import QnADTO, FileDTO, MetadataDTO, CreateKbDTO, OperationStateType, UpdateKbOperationDTO,UpdateKbOperationDTOAdd
from msrest.authentication import CognitiveServicesCredentials
from pathlib import Path, PurePath, PureWindowsPath

'''
Create variables for your resource's Azure endpoint and key. If you
created the environment variable after you launched the application, you
will need to close and reopen the editor, IDE, or shell running it to
access the variable.
'''
'''
QNAMAKER_SUBSCRIPTION_KEY  subscription_key  The key is a 32 character
string and is available in the Azure portal, on the QnA Maker resource,
on the Quickstart page. This is not the same as the prediction endpoint
key.
'''
subscription_key = 'ceb746fffea04d0398a34edb84b530ab'
'''
QNAMAKER_HOST  host  Your authoring endpoint, in the format of
https://YOUR-RESOURCE-NAME.cognitiveservices.azure.com, includes your
resource name. This is not the same URL used to query the prediction
endpoint.
'''
host_key = 'https://aipowered-qna.cognitiveservices.azure.com/'
'''
Create a knowledge base
Use the client object to get a knowledge base operations object.
A knowledge base stores question and answer pairs for the CreateKbDTO object from three sources:
For editorial content, use the QnADTO object.
For files, use the FileDTO object.
For URLs, use a list of strings.
Call the create method then pass the returned operation ID to the Operations.getDetails method to poll for status.

Make sure to include the _monitor_operation function, referenced in the  code, in order to successfully create a knowledge base.
'''
def create_kb(client):

    qna = QnADTO(
        answer="You can cancel a flight or hotel anytime up to 24 hours before check-in. A cancellation fee may apply. Call us on 555 123 456; or visit our website: www.margiestravel.com.",
        questions=["How can I cancel my hotel reservation?"],
        metadata=[MetadataDTO(name="Category", value="api")]
    )
    urls = ["https://microsoft.sharepoint.com/:w:/t/PowerBIEmbeddingVABISLDemoIslam/EYAFP9GPpkBEpWvu0DQOjgwBTcjkwPPG8BAOTUemMk7yxA?e=BeNYX9"]
    files = FileDTO(
        file_name = "Margies Travel FAQ.docx",
        file_uri = PureWindowsPath('C:/Users/iselghaz/Desktop/')
    )
    
    create_kb_dto = CreateKbDTO(
        name="QnA Maker FAQ Margie/'s travel",
        qna_list=[qna],
        files = [files]
    )
    create_op = client.knowledgebase.create(create_kb_payload=create_kb_dto)
    
    create_op = _monitor_operation(client=client, operation=create_op)

    return create_op.resource_location.replace("/knowledgebases/", "")

'''
Update a knowledge base
You can update a knowledge base by passing in the knowledge base ID and
an UpdateKbOperationDTO containing add, update, and delete DTO objects
to the update method. Use the Operation.getDetail method to determine if
the update succeeded.

Make sure to include the _monitor_operation function, referenced in the  code, in order to successfully create a knowledge base.
'''
def update_kb(client, kb_id):
    update_kb_operation_dto = UpdateKbOperationDTO(
        add=UpdateKbOperationDTOAdd(
            qna_list=[
                QnADTO(questions=["bye"], answer="goodbye")
            ]
        )
    )
    update_op = client.knowledgebase.update(kb_id=kb_id, update_kb=update_kb_operation_dto)
    _monitor_operation(client=client, operation=update_op)

'''
Publish a knowledge base
Publish the knowledge base using the publish method. This takes the
current saved and trained model, referenced by the knowledge base ID,
and publishes that at an endpoint.
'''
def publish_kb(client, kb_id):
    client.knowledgebase.publish(kb_id=kb_id)

'''
Download a knowledge base
Use the download method to download the database as a list of
QnADocumentsDTO. This is not equivalent to the QnA Maker portal's export
from the Settings page because the result of this method is not a TSV
file.
'''
def download_kb(client, kb_id):
    kb_data = client.knowledgebase.download(kb_id=kb_id, environment="Prod")
    print("KB Downloaded. It has {} QnAs.".format(len(kb_data.qna_documents)))

'''
Delete a knowledge base
Delete the knowledge base using the delete method with a parameter of the knowledge base ID.
'''
##def delete_kb(client, kb_id):
##    client.knowledgebase.delete(kb_id=kb_id)

'''
Get status of an operation Some methods, such as create and update, can
take enough time that instead of waiting for the process to finish, an
operation is returned. Use the operation ID from the operation to poll
(with retry logic) to determine the status of the original method.

The setTimeout call in the following code block is used to simulate asynchronous code. Replace this with retry logic.
'''
def _monitor_operation(client, operation):

    for i in range(20):
        if operation.operation_state in [OperationStateType.not_started, OperationStateType.running]:
            print("Waiting for operation: {} to complete.".format(operation.operation_id))
            time.sleep(5)
            operation = client.operations.get_details(operation_id=operation.operation_id)
        else:
            break
    if operation.operation_state != OperationStateType.succeeded:
        raise Exception("Operation {} failed to complete.".format(operation.operation_id))
    return operation

'''
Next, create a CognitiveServicesCredentials object with your key, and
use it with your endpoint to create a QnAMakerClient object.
'''
client = QnAMakerClient(endpoint=host_key, credentials=CognitiveServicesCredentials(subscription_key))

# Create a KB
print("Creating KB...")
kb_id = create_kb(client=client)
print("Created KB with ID: {}".format(kb_id))
print()

# Update a KB
print("Updating KB...")
update_kb (client=client, kb_id=kb_id)
print("KB Updated.")
print()

# Publish the KB
print("Publishing KB...")
publish_kb (client=client, kb_id=kb_id)
print("KB Published.")
print()

# Download the KB
print("Downloading KB...")
download_kb (client=client, kb_id=kb_id)
print()

### Delete the KB
##print("Deleting KB...")
##delete_kb (client=client, kb_id=kb_id)
##print("KB Deleted.")
`
Here is the error I get:
`Traceback (most recent call last):
  File "C:\Python\knowledgebase_quickstart.py", line 144, in <module>
    kb_id = create_kb(client=client)
  File "C:\Python\knowledgebase_quickstart.py", line 62, in create_kb
    create_op = client.knowledgebase.create(create_kb_payload=create_kb_dto)
  File "C:\Users\iselghaz\AppData\Local\Programs\Python\Python38-32\lib\site-packages\azure\cognitiveservices\knowledge\qnamaker\operations\knowledgebase_operations.py", line 393, in create
    raise models.ErrorResponseException(self._deserialize, response)
azure.cognitiveservices.knowledge.qnamaker.models.error_response_py3.ErrorResponseException: (BadArgument) Invalid input. See details.`

**Comment by Momeo** [comment]
Same problem. Maybe we need a sample for FileDTO in python

**Comment by islamtg** [comment]
Any updates @azure-sdk @lmazuel ?

**Comment by lmazuel** [comment]
Hi @islamtg, I just sent an email to the service team for help around this sample question, thanks!

**Comment by sahithikkss** [comment]
@islamtg A valid FileDTO has the below format. Please host your files in a blob container or website (with public read access). Local drive/filepath cannot be used. Doc reference [here](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-knowledge-qnamaker/azure.cognitiveservices.knowledge.qnamaker.models.filedto?view=azure-python)
```
files = FileDTO(
    file_name = "Margies Travel FAQ.docx",
    file_uri = “https://siteorblob.withpublicreadaccess/Margies Travel FAQ.docx”
)

```

**Comment by lmazuel** [comment]
Fixed by https://github.com/Azure-Samples/cognitive-services-quickstart-code/pull/251
